import Mathlib.Algebra.FreeAlgebra
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.Ideal.Quotient.Defs

/-!
# PBW lemma L2: presentation correctness in the presented object

Roadmap: an unpublished note, §4,
lemma L2 (R1). This is the presentation side of generator-relations adequacy
for the quotient/PBW correspondence: the presented object `P n` with quotient
generators `q_i` satisfies `q_i q_j + q_j q_i = 0` for `i ≠ j` (the EKL §2.1.1
relations (2.1)/(2.9), first half; locked convention the sign convention:
`x_i x_j = -x_j x_i`), and these relation words generate the full relation
ideal.

Quotient API (roadmap §6 recommendation, decided here): `TwoSidedIdeal.span`
of the free algebra `FreeAlgebra ℤ (Fin n)`, viewed as an `Ideal` via
`TwoSidedIdeal.asIdeal` so that `Ideal.Quotient` applies. The two-sided span
(rather than the one-sided `Ideal.span`) is what makes the quotient a `Ring`;
the instance is automatic from `TwoSidedIdeal.asIdeal.IsTwoSided`.

What this module proves (sorry-free):
- `rel_word_mem`: each anticommutator word lies in the relation ideal.
- `rel_sum`: the imposed relations hold in the presented object,
  `q_i * q_j + q_j * q_i = 0` for `i ≠ j` — by construction (the word is one
  of the spanning generators, so the quotient map kills it).
- `rel_anticommute`: the anticommute form `q_i * q_j = -(q_j * q_i)`.
- `mk_rel_zero`: the quotient map sends each relation word to `0`.
- `ideal_is_span` / `span_generates`: the relation ideal IS the two-sided
  span of exactly the anticommutator words (generation both directions: the
  ideal equals the span by definition, and every generator lies in it).
- `pair_mem_iff`: index-level characterization `(i,j) ∈ relPairs n ↔ i ≠ j`.
- `presentation_correct`: the conjunction both successors need (relations
  hold AND the ideal is generated by exactly these words) — the exact
  presentation-side input the L3 evaluation map must respect to factor
  through the relation ideal.

Scope (NOT this module): the word-evaluation homomorphism `eval`, the
factorization `Φ` (L3); spanning/normal-form existence (L4); linear
independence (L5); the isomorphism/PBW corollary (L6). In particular, the
non-membership of generator squares in the relation ideal is NOT claimed
here: it is unprovable at presentation scope (it needs the L3 model section)
and is explicitly out of scope per roadmap §5 (`x_i^2 = 0` is a non-goal).
What IS proved is the index-level shadow: the diagonal pair `(i,i)` is not
among the imposed relation indices (`relPairs` + negative control).
Finite fixtures in `OddMath/Tests/PbwL2Fixtures.lean` are development aids
(`SUPPORTED_LOW_DEGREE` at most), never a proof of the correspondence.
-/

namespace OddMath.PbwL2

/-- L2 relation words: the anticommutator `ι i * ι j + ι j * ι i` for `i ≠ j`.
This is the exact equation the L3 evaluation map must kill. -/
def relSet (n : ℕ) : Set (FreeAlgebra ℤ (Fin n)) :=
  { w | ∃ i j : Fin n, i ≠ j ∧
    w = FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j
      + FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i }

/-- L2 relation indices: the off-diagonal pairs. The diagonal `(i,i)` is
deliberately excluded (roadmap §5: no square-zero law is imposed). -/
def relPairs (n : ℕ) : Finset (Fin n × Fin n) :=
  Finset.univ.filter (fun p => p.1 ≠ p.2)

/-- L2 relation ideal, two-sided: the span of exactly the relation words. -/
def relTwoSided (n : ℕ) : TwoSidedIdeal (FreeAlgebra ℤ (Fin n)) :=
  TwoSidedIdeal.span (relSet n)

/-- L2 relation ideal as an `Ideal`, for the `Ideal.Quotient` API. -/
def relIdeal (n : ℕ) : Ideal (FreeAlgebra ℤ (Fin n)) :=
  TwoSidedIdeal.asIdeal (relTwoSided n)

instance relIdealTwoSided (n : ℕ) : (relIdeal n).IsTwoSided :=
  inferInstanceAs ((relTwoSided n).asIdeal.IsTwoSided)

/-- L2 presented object `P n`: the free algebra modulo the relation ideal. -/
def Presented (n : ℕ) : Type :=
  FreeAlgebra ℤ (Fin n) ⧸ relIdeal n

instance presentedRing (n : ℕ) : Ring (Presented n) :=
  Ideal.Quotient.ring (relIdeal n)

/-- L2 quotient generators `q_i`: the images of the free generators. -/
def q (n : ℕ) (i : Fin n) : Presented n :=
  Ideal.Quotient.mk (relIdeal n) (FreeAlgebra.ι ℤ i)

/-- L2a: each anticommutator word lies in the relation ideal (it is one of
the spanning generators). -/
theorem rel_word_mem (n : ℕ) (i j : Fin n) (h : i ≠ j) :
    FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j
      + FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i ∈ relIdeal n := by
  rw [relIdeal, relTwoSided, TwoSidedIdeal.mem_asIdeal]
  exact TwoSidedIdeal.subset_span ⟨i, j, h, rfl⟩

/-- L2b: the imposed relations hold in the presented object — by
construction, the quotient map kills each spanning generator. -/
theorem rel_sum (n : ℕ) (i j : Fin n) (h : i ≠ j) :
    q n i * q n j + q n j * q n i = 0 := by
  have h0 : Ideal.Quotient.mk (relIdeal n)
      (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j
        + FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (rel_word_mem n i j h)
  have e : q n i * q n j + q n j * q n i
      = Ideal.Quotient.mk (relIdeal n)
        (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j
          + FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i) := by
    unfold q
    rw [map_add, map_mul, map_mul]
  rw [e]; exact h0

/-- L2c: anticommute form of the imposed relations. -/
theorem rel_anticommute (n : ℕ) (i j : Fin n) (h : i ≠ j) :
    q n i * q n j = -(q n j * q n i) :=
  add_eq_zero_iff_eq_neg.mp (rel_sum n i j h)

/-- L2d: the quotient map sends each relation word to `0`. -/
theorem mk_rel_zero (n : ℕ) (i j : Fin n) (h : i ≠ j) :
    Ideal.Quotient.mk (relIdeal n)
      (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j
        + FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (rel_word_mem n i j h)

/-- L2e: the relation ideal IS the two-sided span of the relation words
(generation, definitional direction). -/
theorem ideal_is_span (n : ℕ) :
    relIdeal n
      = TwoSidedIdeal.asIdeal (TwoSidedIdeal.span (relSet n)) :=
  rfl

/-- L2f: every generating word lies in the relation ideal (generation,
membership direction). -/
theorem span_generates (n : ℕ) (w : FreeAlgebra ℤ (Fin n))
    (hw : w ∈ relSet n) : w ∈ relIdeal n := by
  rw [relIdeal, relTwoSided, TwoSidedIdeal.mem_asIdeal]
  exact TwoSidedIdeal.subset_span hw

/-- L2g: index-level characterization — `(i,j)` is a relation index iff
`i ≠ j`. In particular the diagonal is never imposed. -/
theorem pair_mem_iff (n : ℕ) (i j : Fin n) :
    (i, j) ∈ relPairs n ↔ i ≠ j := by
  simp [relPairs]

/-- L2 adequacy conjunction: the relations hold in the presented object AND
the relation ideal is generated by exactly these words — the exact
presentation-side input the L3 factorization needs. -/
theorem presentation_correct (n : ℕ) (i j : Fin n) (h : i ≠ j) :
    (q n i * q n j + q n j * q n i = 0)
    ∧ relIdeal n
      = TwoSidedIdeal.asIdeal (TwoSidedIdeal.span (relSet n)) :=
  ⟨rel_sum n i j h, rfl⟩

end OddMath.PbwL2
