import OddMath.Frontier.Cyclotomic
import Mathlib.LinearAlgebra.Matrix.Ideal

/-! # Proposition 5.2: `ONH_a^N ≅ Mat_{a!}(OH_{a,N})`
EKL arXiv:1111.1320v1 §5, Proposition 5.2, p.45. Rank a = n+2, ungraded.

Route: Corollary 2.14 (`NilHeckeEndomorphism.matrixEquiv`, right Schubert coordinates) sends
`⟨x̃_1^N⟩` to `Mat(J)`, `J` the two-sided ideal generated by the entries of the matrix of `x̃_1^N`.
`J` is the least `I` with `x̃_1^N ∈ OPol_a·I` (`x̃_1` is normal in `OPol_a`), and
`J = rev⟨h_m : m > N − a⟩` (`entryIdeal_eq_rev`), with `rev = w₀` the ring automorphism of
EKL (2.55). The proof uses the complete sums `h_m(x̃_p, …, x̃_1)` in reversed alphabets and the
odd divided differences, not the recursion (5.8)–(5.9). -/
namespace OddMath.Frontier.Cyclotomic
open scoped BigOperators
noncomputable section

section MatrixQuotient
variable {A R S ι : Type*} [Ring A] [Ring R] [Ring S] [Fintype ι] [DecidableEq ι] [Nonempty ι]

/-- The two-sided ideal generated by the entries of a matrix. -/
def entryIdeal (M : Matrix ι ι R) : TwoSidedIdeal R :=
  TwoSidedIdeal.span (Set.range fun p : ι × ι => M p.1 p.2)

/-- In `Mat_ι(R)`, `⟨M⟩ = Mat_ι(⟨entries of M⟩)`. -/
theorem span_singleton_eq_matricesOver (M : Matrix ι ι R) :
    TwoSidedIdeal.span {M} = (entryIdeal M).matricesOver ι := by
  apply le_antisymm
  · rw [TwoSidedIdeal.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
      TwoSidedIdeal.mem_matricesOver]
    intro i j
    exact TwoSidedIdeal.subset_span ⟨(i, j), rfl⟩
  · set J' := TwoSidedIdeal.equivMatricesOver.symm (TwoSidedIdeal.span {M})
    have hJ' : J'.matricesOver ι = TwoSidedIdeal.span {M} :=
      TwoSidedIdeal.equivMatricesOver.apply_symm_apply _
    have hle : entryIdeal M ≤ J' := by
      rw [entryIdeal, TwoSidedIdeal.span_le]
      rintro _ ⟨⟨i, j⟩, rfl⟩
      have hM : M ∈ J'.matricesOver ι := by rw [hJ']; exact TwoSidedIdeal.subset_span rfl
      exact (TwoSidedIdeal.mem_matricesOver _ _ _).mp hM i j
    rw [← hJ']
    exact TwoSidedIdeal.matricesOver_monotone ι hle

omit [DecidableEq ι] [Nonempty ι] in
theorem mem_span_singleton_equiv (e : A ≃+* Matrix ι ι R) (x a : A) :
    a ∈ TwoSidedIdeal.span {x} ↔ e a ∈ TwoSidedIdeal.span {e x} := by
  constructor
  · intro h
    have hle : TwoSidedIdeal.span {x} ≤ TwoSidedIdeal.comap e (TwoSidedIdeal.span {e x}) := by
      rw [TwoSidedIdeal.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
        TwoSidedIdeal.mem_comap]
      exact TwoSidedIdeal.subset_span rfl
    exact (TwoSidedIdeal.mem_comap _).mp (hle h)
  · intro h
    have hle : TwoSidedIdeal.span {e x} ≤ TwoSidedIdeal.comap e.symm (TwoSidedIdeal.span {x}) := by
      rw [TwoSidedIdeal.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
        TwoSidedIdeal.mem_comap, RingEquiv.symm_apply_apply]
      exact TwoSidedIdeal.subset_span rfl
    simpa using (TwoSidedIdeal.mem_comap _).mp (hle h)

/-- The entrywise reduction `A ≅ Mat_ι(R) → Mat_ι(S)`. -/
def entrywise (e : A ≃+* Matrix ι ι R) (θ : R →+* S) : A →+* Matrix ι ι S :=
  θ.mapMatrix.comp e.toRingHom

theorem ker_entrywise (e : A ≃+* Matrix ι ι R) (θ : R →+* S) (x : A)
    (hθ : ∀ r, θ r = 0 ↔ r ∈ entryIdeal (e x)) :
    RingHom.ker (entrywise e θ) = (TwoSidedIdeal.span {x}).asIdeal := by
  ext a
  rw [RingHom.mem_ker, TwoSidedIdeal.mem_asIdeal, mem_span_singleton_equiv e,
    span_singleton_eq_matricesOver, TwoSidedIdeal.mem_matricesOver]
  constructor
  · intro h i j
    have := congrFun (congrFun h i) j
    exact (hθ _).mp this
  · intro h
    ext i j
    exact (hθ _).mpr (h i j)

/-- `A/⟨x⟩ ≅ Mat_ι(S)` when `θ : R → S` is onto with kernel `⟨entries of e x⟩`. -/
def quotientMatrixEquiv (e : A ≃+* Matrix ι ι R) (θ : R →+* S) (x : A)
    (hsurj : Function.Surjective θ) (hθ : ∀ r, θ r = 0 ↔ r ∈ entryIdeal (e x)) :
    A ⧸ (TwoSidedIdeal.span {x}).asIdeal ≃+* Matrix ι ι S :=
  (Ideal.quotEquivOfEq (ker_entrywise e θ x hθ).symm).trans
    (RingHom.quotientKerEquivOfSurjective (f := entrywise e θ) (by
      intro M
      choose f hf using hsurj
      refine ⟨e.symm (fun i j => f (M i j)), ?_⟩
      ext i j
      simp [entrywise, hf]))

end MatrixQuotient

section Coordinates
open OddMath.SkewPolynomial (SkewPolynomial generator)
open NilHeckeAction NilHeckeEndomorphism OddSchubertAction NilCoxeterWords

/-- The Corollary 2.14 identification `ONH_a ≅ Mat_{S_a}(OΛ_a)` (right coordinates). -/
def cor214 (n : ℕ) : Presented n ≃+* Matrix (Perm n) (Perm n) (K n) :=
  (actionEquiv n).trans (matrixEquiv n)

theorem action_firstDot_pow (n N : ℕ) (f : SkewPolynomial (n+2)) :
    action n (firstDot n ^ N) f = x1 n ^ N * f := by
  induction N generalizing f with
  | zero => simp
  | succ N ih =>
    rw [pow_succ, action_mul_apply, ih, firstDot, action_dot_apply, pow_succ, mul_assoc]

theorem cor214_firstDot_pow (n N : ℕ) (v w : Perm n) :
    cor214 n (firstDot n ^ N) v w = coordinates n (x1 n ^ N * schubert w) v := by
  rw [cor214, RingEquiv.trans_apply, matrixEquiv_apply, actionEquiv_apply, action_firstDot_pow]

/-- `P·I`: polynomials all of whose right Schubert coordinates lie in `I`. -/
def rightSpan (n : ℕ) (I : TwoSidedIdeal (K n)) : Set (SkewPolynomial (n+2)) :=
  {f | ∀ w, coordinates n f w ∈ I}

/-- `P·I` is stable under every right `OΛ_a`-linear additive map. -/
theorem rightSpan_map (n : ℕ) (I : TwoSidedIdeal (K n))
    (T : SkewPolynomial (n+2) →+ SkewPolynomial (n+2))
    (hT : ∀ f (k : K n), T (f * (k : SkewPolynomial (n+2))) = T f * k)
    {f : SkewPolynomial (n+2)} (hf : f ∈ rightSpan n I) : T f ∈ rightSpan n I := by
  intro v
  have he : T f = ∑ w, T (schubert w) * (coordinates n f w : SkewPolynomial (n+2)) := by
    conv_lhs => rw [← synthesis_coordinates n f]
    simp only [synthesis, LinearMap.coe_mk, AddHom.coe_mk, map_sum, hT]
  rw [he, map_sum, Finset.sum_apply]
  refine sum_mem (fun w _ => ?_)
  rw [coordinates_right_mul]
  exact TwoSidedIdeal.mul_mem_left _ _ _ (hf w)

theorem rightSpan_mul_left (n : ℕ) (I : TwoSidedIdeal (K n)) (p : SkewPolynomial (n+2))
    {f : SkewPolynomial (n+2)} (hf : f ∈ rightSpan n I) : p * f ∈ rightSpan n I :=
  rightSpan_map n I (AddMonoidHom.mulLeft p) (fun _ _ => (mul_assoc _ _ _).symm) hf

theorem rightSpan_divided (n : ℕ) (I : TwoSidedIdeal (K n)) (i : Fin (n+1))
    {f : SkewPolynomial (n+2)} (hf : f ∈ rightSpan n I) :
    AllRankDivided.divided i f ∈ rightSpan n I :=
  rightSpan_map n I (AllRankDivided.divided i).toAddMonoidHom
    (fun f k => NilHeckeRightKernel.divided_right_kernel n i k k.property f) hf

theorem rightSpan_add (n : ℕ) (I : TwoSidedIdeal (K n)) {f g : SkewPolynomial (n+2)}
    (hf : f ∈ rightSpan n I) (hg : g ∈ rightSpan n I) : f + g ∈ rightSpan n I := by
  intro w; rw [map_add, Pi.add_apply]; exact TwoSidedIdeal.add_mem _ (hf w) (hg w)

theorem rightSpan_neg (n : ℕ) (I : TwoSidedIdeal (K n)) {f : SkewPolynomial (n+2)}
    (hf : f ∈ rightSpan n I) : -f ∈ rightSpan n I := by
  intro w; rw [map_neg, Pi.neg_apply]; exact TwoSidedIdeal.neg_mem _ (hf w)

theorem rightSpan_zsmul (n : ℕ) (I : TwoSidedIdeal (K n)) (c : ℤ) {f : SkewPolynomial (n+2)}
    (hf : f ∈ rightSpan n I) : c • f ∈ rightSpan n I := by
  intro w; rw [map_zsmul, Pi.smul_apply]; exact TwoSidedIdeal.zsmul_mem _ _ (hf w)

theorem schubert_one_sq (n : ℕ) : ∃ c : ℤ, c * c = 1 ∧ schubert (1 : Perm n) = c • 1 := by
  rcases schubert_one_signed n with h | h
  · exact ⟨1, by norm_num, by simp [h]⟩
  · exact ⟨-1, by norm_num, by simp [h]⟩

/-- `P·I ∩ OΛ_a = I`. -/
theorem kernel_mem_rightSpan_iff (n : ℕ) (I : TwoSidedIdeal (K n)) (k : K n) :
    (k : SkewPolynomial (n+2)) ∈ rightSpan n I ↔ k ∈ I := by
  classical
  obtain ⟨c, hc, h1⟩ := schubert_one_sq n
  have hk : (k : SkewPolynomial (n+2)) = c • (schubert (1 : Perm n) * (k : SkewPolynomial (n+2))) := by
    rw [h1, smul_mul_assoc, one_mul, smul_smul, hc, one_smul]
  have hco : coordinates n (k : SkewPolynomial (n+2)) = fun w => c • ((Pi.single (1 : Perm n) (1 : K n) : Perm n → K n) w * k) := by
    rw [hk, map_zsmul, coordinates_right_mul, coordinates_schubert]
    rfl
  constructor
  · intro h
    have h1' := TwoSidedIdeal.zsmul_mem I c (h 1)
    rw [hco] at h1'
    simpa only [Pi.single_eq_same, one_mul, smul_smul, hc, one_smul] using h1'
  · intro h w
    rw [hco]
    by_cases hw : w = 1
    · subst hw; simpa using TwoSidedIdeal.zsmul_mem I c h
    · simp [hw, TwoSidedIdeal.zero_mem]

/-- `x̃_1` is a normal element of `OPol_a`: `x̃_1 f = g x̃_1` (it anticommutes with the other
variables). -/
theorem x1_normal (n : ℕ) (f : SkewPolynomial (n+2)) : ∃ g, x1 n * f = g * x1 n := by
  induction f using Finsupp.induction_linear with
  | zero => exact ⟨0, by rw [mul_zero, zero_mul]⟩
  | add f₁ f₂ h₁ h₂ =>
    obtain ⟨g₁, hg₁⟩ := h₁
    obtain ⟨g₂, hg₂⟩ := h₂
    exact ⟨g₁ + g₂, by rw [mul_add, hg₁, hg₂, add_mul]⟩
  | single a c =>
    refine ⟨OddMath.SkewPolynomial.monomial a (c * OddMath.skewSign a (OddMath.SkewPolynomial.expSingle 0)), ?_⟩
    change OddMath.SkewPolynomial.monomial (OddMath.SkewPolynomial.expSingle 0) 1 *
        OddMath.SkewPolynomial.monomial a c = _ *
      OddMath.SkewPolynomial.monomial (OddMath.SkewPolynomial.expSingle 0) 1
    rw [MonomialReversal.monomial_mul_monomial, MonomialReversal.monomial_mul_monomial,
      add_comm a, OddMath.skewSign, crossingCount_first_left]
    congr 1
    rw [OddMath.skewSign]
    simp only [pow_zero, one_mul, mul_one, mul_assoc, ← pow_add, ← two_mul, pow_mul, neg_one_sq,
      one_pow]

theorem x1_pow_normal (n N : ℕ) (f : SkewPolynomial (n+2)) : ∃ g, x1 n ^ N * f = g * x1 n ^ N := by
  induction N generalizing f with
  | zero => exact ⟨f, by simp⟩
  | succ N ih =>
    obtain ⟨g, hg⟩ := x1_normal n f
    obtain ⟨g', hg'⟩ := ih g
    exact ⟨g', by rw [pow_succ, mul_assoc, hg, ← mul_assoc, hg', mul_assoc, ← pow_succ]⟩

/-- The entries of the Corollary 2.14 matrix of `x̃_1^N` lie in `I` iff `x̃_1^N ∈ P·I`. -/
theorem entryIdeal_le_iff (n N : ℕ) (I : TwoSidedIdeal (K n)) :
    entryIdeal (cor214 n (firstDot n ^ N)) ≤ I ↔ x1 n ^ N ∈ rightSpan n I := by
  rw [entryIdeal, TwoSidedIdeal.span_le]
  constructor
  · intro h
    obtain ⟨c, hc, h1⟩ := schubert_one_sq n
    have hx : x1 n ^ N = c • (x1 n ^ N * schubert (1 : Perm n)) := by
      rw [h1, mul_smul_comm, mul_one, smul_smul, hc, one_smul]
    rw [hx]
    apply rightSpan_zsmul
    intro v
    rw [← cor214_firstDot_pow]
    exact h ⟨(v, 1), rfl⟩
  · intro h
    rintro _ ⟨⟨v, w⟩, rfl⟩
    change cor214 n (firstDot n ^ N) v w ∈ I
    rw [cor214_firstDot_pow]
    obtain ⟨g, hg⟩ := x1_pow_normal n N (schubert w)
    rw [hg]
    exact rightSpan_mul_left n I g h v

end Coordinates

section Reversed
open OddMath.SkewPolynomial (SkewPolynomial generator)
open FiniteCompleteElementary FiniteCompleteElementary.FiniteWords PlacticEvaluation
open OddSymmetricKernel

theorem weakSum_mem_of_strictSum_mem {R : Type*} [Ring R] (S : Subring R) {m : ℕ} (x : Fin m → R)
    (hx : ∀ i j, i ≠ j → x i * x j = -(x j * x i)) (hs : ∀ k, strictSum x k ∈ S) (k : ℕ) :
    weakSum x k ∈ S := by
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    rcases k with _ | k
    · simpa using S.one_mem
    have h := convolution x hx k
    rw [Finset.sum_range_succ'] at h
    simp only [signedStrict_zero, one_mul, Nat.sub_zero] at h
    rw [eq_neg_of_add_eq_zero_right h]
    refine S.neg_mem (S.sum_mem fun j hj => S.mul_mem ?_ (ih _ (by omega)))
    exact S.zsmul_mem (hs _) _

/-- The reversed alphabet `(x̃_p, …, x̃_1)` (paper labels), i.e. variables `p-1, …, 0`. -/
def revAlphabet (n p : ℕ) : Fin p → SkewPolynomial (n+2) :=
  fun i => if h : p - 1 - i.val < n+2 then tildeGenerator ⟨p - 1 - i.val, h⟩ else 0

/-- `h_m(x̃_p, …, x̃_1)`: complete sums in the reversed first `p` variables. -/
def revComplete (n p m : ℕ) : SkewPolynomial (n+2) := weakSum (revAlphabet n p) m

theorem revAlphabet_succ (n p : ℕ) :
    (fun i : Fin p => revAlphabet n (p+1) i.succ) = revAlphabet n p := by
  funext i
  simp only [revAlphabet, Fin.val_succ, show p + 1 - 1 - (i.val+1) = p - 1 - i.val by omega]

theorem revAlphabet_zero (n p : ℕ) (hp : p < n+2) :
    revAlphabet n (p+1) 0 = tildeGenerator ⟨p, hp⟩ := by
  simp [revAlphabet, hp]

theorem revAlphabet_anticommute (n p : ℕ) (i j : Fin p) (hij : i ≠ j) :
    revAlphabet n p i * revAlphabet n p j = -(revAlphabet n p j * revAlphabet n p i) := by
  unfold revAlphabet
  split_ifs with hi hj
  · apply tilde_anticommute
    intro h
    have := congrArg Fin.val h
    simp only at this
    exact hij (Fin.ext (by have := i.isLt; have := j.isLt; omega))
  all_goals simp

theorem revComplete_succ (n p m : ℕ) (hp : p < n+2) :
    revComplete n (p+1) (m+1) =
      tildeGenerator ⟨p, hp⟩ * revComplete n (p+1) m + revComplete n p (m+1) := by
  rw [revComplete, weakSum_succ, revAlphabet_succ, revAlphabet_zero n p hp]
  rfl

theorem revComplete_one (n m : ℕ) : revComplete n 1 m = x1 n ^ m := by
  induction m with
  | zero => simp [revComplete]
  | succ m ih =>
    rw [revComplete_succ n 0 m (by omega), ih]
    rw [revComplete, weakSum_empty.{0} (revAlphabet n 0)]
    simp [tildeGenerator, pow_succ']

/-- `h_m(x̃_{q+2}, …, x̃_1)` is killed by `∂_{q+1}` (paper labels): the leading pair is
`x̃_{q+2}, x̃_{q+1}`, all later letters are spectators. -/
theorem revComplete_mem_singleKernel (n q m : ℕ) (hq : q < n+1) :
    revComplete n (q+2) m ∈ singleKernel (⟨q, hq⟩ : Fin (n+1)) := by
  set i : Fin (n+1) := ⟨q, hq⟩
  have h0 : revAlphabet n (q+2) 0 = tildeGenerator i.succ := by
    simp [revAlphabet, i, Fin.succ, show q + 1 < n + 2 by omega]
  have h1 : revAlphabet n (q+2) 1 = tildeGenerator i.castSucc := by
    simp [revAlphabet, i, Fin.castSucc, show q < n + 2 by omega]
  apply weakSum_mem_of_strictSum_mem _ _ (revAlphabet_anticommute n (q+2))
  intro k
  apply strictSum_mem_front
  · intro j
    have hj : q - (j.val + 1) < n+2 := by omega
    have : revAlphabet n (q+2) j.succ.succ = tildeGenerator ⟨q - (j.val+1), hj⟩ := by
      simp [revAlphabet, hj]
    rw [this]
    apply divided_tilde_spectator
    · intro h; have := congrArg Fin.val h; simp [i] at this; omega
    · intro h; have := congrArg Fin.val h; simp [i] at this; omega
  · rw [h0, h1]
    show AllRankDivided.divided i _ = 0
    rw [add_comm (tildeGenerator i.succ)]; exact divided_tilde_pair_add i
  · rw [h0, h1]
    show AllRankDivided.divided i _ = 0
    rw [tilde_anticommute _ _ (AllRankDivided.adjacent_ne i).symm, map_neg,
      divided_tilde_pair_mul i, neg_zero]

/-- The odd analogue of `∂_q h_{m+1}(x_1..x_q) = h_m(x_1..x_{q+1})`, reversed alphabets. -/
theorem divided_revComplete (n q m : ℕ) (hq : q < n+1) :
    AllRankDivided.divided (⟨q, hq⟩ : Fin (n+1)) (revComplete n (q+1) (m+1)) =
      (-1 : ℤ)^q • revComplete n (q+2) m := by
  set i : Fin (n+1) := ⟨q, hq⟩
  have hk : AllRankDivided.divided i (revComplete n (q+2) (m+1)) = 0 :=
    revComplete_mem_singleKernel n q (m+1) hq
  have hg : AllRankDivided.divided i (revComplete n (q+2) m) = 0 :=
    revComplete_mem_singleKernel n q m hq
  rw [revComplete_succ n (q+1) m (by omega), map_add, AllRankDivided.divided_mul, hg, mul_zero,
    add_zero] at hk
  have ht : tildeGenerator (⟨q+1, by omega⟩ : Fin (n+2)) = (-1 : ℤ)^(q+1) • generator i.succ := rfl
  rw [ht, map_zsmul, AllRankDivided.divided_generator, if_pos (Or.inr rfl), smul_mul_assoc,
    one_mul] at hk
  rw [eq_neg_of_add_eq_zero_right hk, pow_succ, mul_neg_one, neg_smul, neg_neg]

theorem revAlphabet_full (n : ℕ) (j : Fin (n+2)) :
    revAlphabet n (n+2) j = tildeGenerator j.rev := by
  have hj : n + 2 - 1 - j.val < n+2 := by omega
  simp only [revAlphabet, hj, dif_pos]
  congr 1
  apply Fin.ext
  simp only [Fin.val_rev]
  omega

/-- The reversal `rev = w₀` (`x_i ↦ ± x_{a+1-i}`, EKL (2.55)) as a ring automorphism of `OΛ_a`. -/
def revK (n : ℕ) : K n ≃+* K n where
  toFun k := ⟨SignedPermutation.skewAction (LongestElementary.longest (n+2)) k,
    LongestElementary.action_mem_kernel n k k.property⟩
  invFun k := ⟨SignedPermutation.skewAction (LongestElementary.longest (n+2)) k,
    LongestElementary.action_mem_kernel n k k.property⟩
  left_inv _ := Subtype.ext (LongestElementary.action_involutive _ _)
  right_inv _ := Subtype.ext (LongestElementary.action_involutive _ _)
  map_mul' _ _ := Subtype.ext (map_mul _ _ _)
  map_add' _ _ := Subtype.ext (map_add _ _ _)

@[simp] theorem revK_val (n : ℕ) (k : K n) :
    (revK n k : SkewPolynomial (n+2)) =
      SignedPermutation.skewAction (LongestElementary.longest (n+2)) k := rfl

theorem revK_revK (n : ℕ) (k : K n) : revK n (revK n k) = k :=
  Subtype.ext (LongestElementary.action_involutive _ _)

/-- `rev(h_m) = ± h_m(x̃_a, …, x̃_1)`. -/
theorem revK_hK (n m : ℕ) :
    (revK n (hK n m) : SkewPolynomial (n+2)) =
      ((-1 : ℤ)^((n+2-1).choose 2))^m • revComplete n (n+2) m := by
  classical
  rw [revK_val, hK_val, completePoly, map_sum, revComplete, weakSum_eq, Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro f _
  by_cases hf : Monotone f
  · simp only [hf, if_true]
    have h := LongestElementary.action_tildeWord (List.ofFn f)
    simp only [List.map_ofFn, List.length_ofFn] at h
    rw [show (List.ofFn fun i => tildeGenerator (f i)) = List.ofFn (tildeGenerator ∘ f) from rfl, h]
    congr 1
    simp only [word, revAlphabet_full]
    rfl
  · simp [hf]

end Reversed

section Identification
open OddMath.SkewPolynomial (SkewPolynomial generator)
open FiniteCompleteElementary PlacticEvaluation

/-- `rev⟨h_m : m > N − a⟩`, the image of the Grassmannian ideal under `revK`. -/
def revGrassmannianIdeal (n N : ℕ) : TwoSidedIdeal (K n) :=
  TwoSidedIdeal.span {x | ∃ m, N < m + (n+2) ∧ revK n (hK n m) = x}

theorem sign_sq (c : ℤ) (m k : ℕ) (hc : c = (-1)^k) : c^m * c^m = 1 := by
  rw [← mul_pow, hc, ← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_pow]

theorem revComplete_full_eq (n m : ℕ) :
    revComplete n (n+2) m =
      ((-1 : ℤ)^((n+2-1).choose 2))^m • (revK n (hK n m) : SkewPolynomial (n+2)) := by
  rw [revK_hK, smul_smul, sign_sq _ m _ rfl, one_smul]

theorem entryIdeal_le_rev (n N : ℕ) :
    entryIdeal (cor214 n (firstDot n ^ N)) ≤ revGrassmannianIdeal n N := by
  rw [entryIdeal_le_iff]
  set I := revGrassmannianIdeal n N
  have key : ∀ r, r ≤ n+1 → ∀ m, N ≤ m + (n+1-r) → revComplete n (n+2-r) m ∈ rightSpan n I := by
    intro r
    induction r with
    | zero =>
      intro _ m hm
      rw [Nat.sub_zero, revComplete_full_eq]
      apply rightSpan_zsmul
      rw [kernel_mem_rightSpan_iff]
      exact TwoSidedIdeal.subset_span ⟨m, by omega, rfl⟩
    | succ r ih =>
      intro hr m hm
      have hp : n + 2 - (r+1) < n+2 := by omega
      have e1 : n + 2 - r = (n + 2 - (r+1)) + 1 := by omega
      rcases m with _ | m
      · have h0 := ih (by omega) 0 (by omega)
        simpa [revComplete] using h0
      · have hs := revComplete_succ n (n+2-(r+1)) m hp
        rw [← e1] at hs
        have hx : revComplete n (n+2-(r+1)) (m+1) = revComplete n (n+2-r) (m+1) -
            tildeGenerator ⟨n+2-(r+1), hp⟩ * revComplete n (n+2-r) m := by
          rw [hs]; abel
        rw [hx, sub_eq_add_neg]
        exact rightSpan_add n I (ih (by omega) _ (by omega))
          (rightSpan_neg n I (rightSpan_mul_left n I _ (ih (by omega) _ (by omega))))
  have h := key (n+1) le_rfl N (by omega)
  rwa [show n + 2 - (n+1) = 1 by omega, revComplete_one] at h

theorem rev_le_entryIdeal (n N : ℕ) :
    revGrassmannianIdeal n N ≤ entryIdeal (cor214 n (firstDot n ^ N)) := by
  set I := entryIdeal (cor214 n (firstDot n ^ N))
  have hx : x1 n ^ N ∈ rightSpan n I := (entryIdeal_le_iff n N I).mp le_rfl
  have key : ∀ q, q ≤ n+1 → ∀ m, N ≤ m + q → revComplete n (q+1) m ∈ rightSpan n I := by
    intro q
    induction q with
    | zero =>
      intro _ m hm
      rw [revComplete_one, show m = (m - N) + N by omega, pow_add]
      exact rightSpan_mul_left n I _ hx
    | succ q ih =>
      intro hq m hm
      have h := divided_revComplete n q m (by omega)
      have h' : revComplete n (q+2) m = (-1 : ℤ)^q •
          AllRankDivided.divided (⟨q, by omega⟩ : Fin (n+1)) (revComplete n (q+1) (m+1)) := by
        rw [h, smul_smul, ← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_smul]
      rw [h']
      exact rightSpan_zsmul n I _ (rightSpan_divided n I _ (ih (by omega) (m+1) (by omega)))
  rw [revGrassmannianIdeal, TwoSidedIdeal.span_le]
  rintro _ ⟨m, hm, rfl⟩
  rw [SetLike.mem_coe, ← kernel_mem_rightSpan_iff]
  have h := rightSpan_zsmul n I (((-1 : ℤ)^((n+2-1).choose 2))^m)
    (key (n+1) le_rfl m (by omega))
  rwa [revComplete_full_eq, smul_smul, sign_sq _ m _ rfl, one_smul] at h

/-- The ideal cut out in `OΛ_a` by the cyclotomic relation, in the right coordinates of
Corollary 2.14, is `rev⟨h_m : m > N − a⟩` (not `⟨h_m : m > N − a⟩` itself in general). -/
theorem entryIdeal_eq_rev (n N : ℕ) :
    entryIdeal (cor214 n (firstDot n ^ N)) = revGrassmannianIdeal n N :=
  le_antisymm (entryIdeal_le_rev n N) (rev_le_entryIdeal n N)

end Identification

section Prop52
open NilHeckeAction NilCoxeterWords

theorem revK_mem_iff (n N : ℕ) (r : K n) :
    revK n r ∈ grassmannianIdeal n N ↔ r ∈ revGrassmannianIdeal n N := by
  have h1 : revGrassmannianIdeal n N ≤ TwoSidedIdeal.comap (revK n) (grassmannianIdeal n N) := by
    rw [revGrassmannianIdeal, TwoSidedIdeal.span_le]
    rintro _ ⟨m, hm, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_comap, revK_revK]
    exact hK_mem n N m hm
  have h2 : grassmannianIdeal n N ≤ TwoSidedIdeal.comap (revK n) (revGrassmannianIdeal n N) := by
    rw [grassmannianIdeal, TwoSidedIdeal.span_le]
    rintro _ ⟨m, hm, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_comap]
    exact TwoSidedIdeal.subset_span ⟨m, hm, rfl⟩
  constructor
  · intro h
    have := (TwoSidedIdeal.mem_comap _).mp (h2 h)
    rwa [revK_revK] at this
  · intro h
    exact (TwoSidedIdeal.mem_comap _).mp (h1 h)

/-- The entry map `OΛ_a → OH_{a,N}`, `r ↦ [rev r]`. -/
def entryMap (n N : ℕ) : K n →+* OH n N := (toOH n N).comp (revK n).toRingHom

theorem entryMap_surjective (n N : ℕ) : Function.Surjective (entryMap n N) := by
  intro y
  obtain ⟨r, rfl⟩ := toOH_surjective n N y
  exact ⟨revK n r, by simp [entryMap, revK_revK]⟩

theorem entryMap_eq_zero_iff (n N : ℕ) (r : K n) :
    entryMap n N r = 0 ↔ r ∈ entryIdeal (cor214 n (firstDot n ^ N)) := by
  rw [entryIdeal_eq_rev, ← revK_mem_iff, ← toOH_eq_zero_iff]
  rfl

/-- EKL Proposition 5.2 (ungraded): `ONH_a^N ≅ Mat_{a!}(OH_{a,N})` as rings, rows and columns
indexed by `S_a`. The entry of `[T]` at `(v, w)` is `[rev T_{vw}]`, where `T_{vw}` is the right
Schubert coordinate matrix of Corollary 2.14 and `rev = w₀` (EKL (2.55)). -/
def prop_5_2 (n N : ℕ) : ONH n N ≃+* Matrix (Perm n) (Perm n) (OH n N) :=
  quotientMatrixEquiv (cor214 n) (entryMap n N) (firstDot n ^ N) (entryMap_surjective n N)
    (entryMap_eq_zero_iff n N)

theorem prop_5_2_apply (n N : ℕ) (T : Presented n) (v w : Perm n) :
    prop_5_2 n N (toONH n N T) v w = toOH n N (revK n (cor214 n T v w)) := rfl

/-- `ONH_a^N` vanishes unless `a ≤ N`. -/
theorem ONH_subsingleton {n N : ℕ} (h : N < n+2) : Subsingleton (ONH n N) := by
  haveI := OH_subsingleton h
  exact (prop_5_2 n N).toEquiv.subsingleton

end Prop52
end
end OddMath.Frontier.Cyclotomic
