import OddMath.Diagrammatics.Even.Basic
import OddMath.Frontier.SignedSwap
import OddMath.Frontier.VariableEmbedding

/-!
# Even → odd translation-layer dictionary, with one worked example

Direction: an unpublished note
(typed even calculus, odd bridge, translation-layer design). Sign conventions:
the sign convention, the translation table (increasing-index
normal order, Koszul re-sorting signs). Odd sign source: EKL arXiv:1111.1320v1,
§2.1.1, (2.1)–(2.2), p.3, exactly as already encoded in the existing
`DividedDifferences.symm1` (`s₁(x₁^a x₂^b) = (-1)^(a+b+ab) x₁^b x₂^a`).
Even side: `OddMath.Diagrammatics.Even.Basic` (Lean slot `j` = paper strand
`j+1`; `seq below above` applies `below` first).

Dictionary (this file):
* objects — an even boundary `Fin n` goes to the odd arity `n`; the carrier is
  the integer skew-polynomial model `SkewPolynomial n`, and endpoint `j` goes
  to the odd generator `x_{j+1}`;
* crossings — `Expr.swap k i` goes to the existing signed swap `symm1`
  acting on the rank-two subalgebra generated by the crossing's two strands
  `i, i+1`, transported along the order embedding `crossingStrands k i` by
  `VariableEmbedding.embed`. On monomials this is a signed-swap monomial
  operator whose sign is the two generator negations times the exact ambient
  crossing-count sign (`swapSign_eq_generator_mul_crossing`). The even
  denotation exchanges exactly those two strands
  (`denote_swap_crossingStrands`).

Worked example (the only one): the adjacent transposition
`exampleCrossing = swap 0 0 : Expr 2 2` and its square
`exampleSquare = seq exampleCrossing exampleCrossing`. The dictionary entry of
the example is exactly `symm1` (`exampleOp_eq`); it moves exponents along the
even denotation (`example_monomial_coherence`); it is involutive on every
rank-two integer skew polynomial, with no degree bound, by consuming the
existing `SignedSwap.symm1_involute` (`example_involutive`); and the
square's translation is the identity operator while its even denotation is
that of `Expr.id 2` (`example_denotation_coherence`).

Not here (see `DiagramTranslationAudit.lean`): no translation of `seq` beyond
the example, and no crossing entry outside its own rank-two subalgebra (no
all-rank odd action); no braid/crossing soundness or faithfulness; no
odd-symmetric quotient descent or kernel membership; no Schur/LR content.
-/

namespace OddMath.Frontier.DiagramTranslation

open OddMath.Diagrammatics.Even OddMath.SkewPolynomial OddMath.DividedDifferences
open OddMath.Frontier.VariableEmbedding

/-! ## Object map -/

/-- Odd arity attached to an even boundary with `n` endpoints. -/
abbrev arity (n : ℕ) : ℕ := n

/-- Odd carrier over an even boundary: the integer skew-polynomial model. -/
abbrev Carrier (n : ℕ) : Type := SkewPolynomial (arity n)

/-- Even endpoints and odd variables are counted by the same number. -/
theorem card_boundary (n : ℕ) : Fintype.card (Fin n) = arity n :=
  Fintype.card_fin n

/-- Endpoint `j` of the even boundary (paper strand `j+1`) goes to the odd
generator `x_{j+1}`. -/
noncomputable def boundaryVariable {n : ℕ} (j : Fin n) : Carrier n :=
  generator j

/-! ## Morphism map on crossings -/

/-- The strand pair `![i, i+1]` of a crossing is strictly increasing. -/
theorem crossingStrands_strictMono (k : ℕ) (i : Fin (k + 1)) :
    StrictMono (![i.castSucc, i.succ] : Fin 2 → Fin (k + 2)) :=
  Fin.strictMono_iff_lt_succ.mpr fun j => by
    rw [Subsingleton.elim j 0]
    exact Fin.castSucc_lt_succ i

/-- The two strands of `Expr.swap k i`, as an order embedding
`Fin 2 ↪o Fin (k+2)`: `0 ↦ i` (left slot), `1 ↦ i+1`. -/
def crossingStrands (k : ℕ) (i : Fin (k + 1)) : Fin 2 ↪o Fin (k + 2) :=
  OrderEmbedding.ofStrictMono _ (crossingStrands_strictMono k i)

theorem crossingStrands_zero (k : ℕ) (i : Fin (k + 1)) :
    crossingStrands k i 0 = i.castSucc := rfl

theorem crossingStrands_one (k : ℕ) (i : Fin (k + 1)) :
    crossingStrands k i 1 = i.succ := rfl

/-- Even semantics on the crossing's strands: `denote (swap k i)` exchanges
exactly the two strands selected by `crossingStrands k i`, i.e. it restricts
to the rank-two transposition `swapFin` underlying `symm1`. -/
theorem denote_swap_crossingStrands (k : ℕ) (i : Fin (k + 1)) :
    ∀ j : Fin 2,
      denote (Expr.swap k i) (crossingStrands k i j) = crossingStrands k i (swapFin j) :=
  Fin.forall_fin_two.mpr
    ⟨show adjacent k i i.castSucc = i.succ from adjacent_moves_left k i,
     show adjacent k i i.succ = i.castSucc from Equiv.swap_apply_right _ _⟩

/-- Morphism map on a crossing: the existing `symm1` on the crossing's
rank-two subalgebra, transported along `crossingStrands k i`. -/
noncomputable def crossingOp (k : ℕ) (i : Fin (k + 1)) (f : SkewPolynomial 2) :
    SkewPolynomial (k + 2) :=
  embed (crossingStrands k i) (symm1 f)

/-- Signed-swap monomial operator: `x^e ↦ swapSign e · x^(swapExp e)`, placed
on strands `i, i+1`. Arbitrary exponents and integer coefficients. -/
theorem crossingOp_monomial (k : ℕ) (i : Fin (k + 1)) (e : Fin 2 → ℕ) (r : ℤ) :
    crossingOp k i (monomial e r) =
      monomial (expEmbed (crossingStrands k i) (swapExp e)) (r * swapSign e) := by
  rw [crossingOp, symm1_monomial, embed_monomial]

/-- The crossing count of re-sorting the word `x_{i+2}^{e₀} · x_{i+1}^{e₁}`,
measured exactly in the ambient rank `k+2`. -/
theorem crossingCount_crossing_word (k : ℕ) (i : Fin (k + 1)) (e : Fin 2 → ℕ) :
    OddMath.crossingCount (expEmbed (crossingStrands k i) ![0, e 0])
      (expEmbed (crossingStrands k i) ![e 1, 0]) = e 0 * e 1 := by
  rw [crossingCount_expEmbed, SignedSwap.crossingCount_two]
  rfl

/-- Exact sign of the dictionary entry: the two generator negations
`(-1)^(e₀+e₁)` times the exact ambient crossing-count sign of re-sorting
`x_{i+2}^{e₀} · x_{i+1}^{e₁}` in rank `k+2`. -/
theorem swapSign_eq_generator_mul_crossing (k : ℕ) (i : Fin (k + 1)) (e : Fin 2 → ℕ) :
    swapSign e = (-1 : ℤ) ^ (e 0 + e 1) *
      OddMath.skewSign (expEmbed (crossingStrands k i) ![0, e 0])
        (expEmbed (crossingStrands k i) ![e 1, 0]) := by
  rw [OddMath.skewSign, crossingCount_crossing_word, swapSign,
    pow_add (-1 : ℤ) (e 0 + e 1) (e 0 * e 1)]

/-! ## The worked example: the adjacent transposition on two strands -/

/-- The example crossing `swap 0 0 : Expr 2 2` (paper strands 1 and 2). -/
def exampleCrossing : Expr 2 2 := Expr.swap 0 0

/-- The example square `seq below above`, both layers the example crossing. -/
def exampleSquare : Expr 2 2 := Expr.seq exampleCrossing exampleCrossing

/-- Even side: the example crossing is an involution. -/
theorem denote_exampleSquare : denote exampleSquare = Equiv.refl (Fin 2) :=
  Equiv.ext (Fin.forall_fin_two.mpr ⟨by decide, by decide⟩)

/-- For the example, the strand embedding is the identity of `Fin 2`. -/
theorem crossingStrands_example_apply :
    ∀ j : Fin 2, crossingStrands 0 0 j = j :=
  Fin.forall_fin_two.mpr ⟨rfl, rfl⟩

theorem expEmbed_example (a : Fin 2 → ℕ) : expEmbed (crossingStrands 0 0) a = a := by
  funext j
  have h := expEmbed_apply (crossingStrands 0 0) a j
  rwa [crossingStrands_example_apply] at h

theorem embed_example (g : SkewPolynomial 2) : embed (crossingStrands 0 0) g = g := by
  induction g using Finsupp.induction_linear with
  | zero => exact embed_zero _
  | add f₁ f₂ h₁ h₂ => rw [embed_add, h₁, h₂]
  | single a c =>
      show embed (crossingStrands 0 0) (monomial a c) = monomial a c
      rw [embed_monomial, expEmbed_example]

/-- The dictionary entry of the example crossing is exactly `symm1`. -/
theorem crossingOp_example (f : SkewPolynomial 2) : crossingOp 0 0 f = symm1 f :=
  embed_example (symm1 f)

/-- The dictionary entry of the example crossing, as an endomorphism of the
rank-two carrier. -/
noncomputable def exampleOp : SkewPolynomial 2 → SkewPolynomial 2 :=
  crossingOp 0 0

theorem exampleOp_eq (f : SkewPolynomial 2) : exampleOp f = symm1 f :=
  crossingOp_example f

/-- The example crossing on boundary variables: `x₁ ↦ -x₂` (EKL (2.2)). -/
theorem exampleOp_boundaryVariable_zero :
    exampleOp (boundaryVariable 0) = -boundaryVariable 1 := by
  rw [exampleOp_eq]
  exact symm1_generator_zero

/-- The example crossing on boundary variables: `x₂ ↦ -x₁` (EKL (2.2)). -/
theorem exampleOp_boundaryVariable_one :
    exampleOp (boundaryVariable 1) = -boundaryVariable 0 := by
  rw [exampleOp_eq]
  exact symm1_generator_one

/-- The rank-two exponent swap is precomposition with the inverse even
endpoint permutation of the example crossing. -/
theorem swapExp_eq_denote (e : Fin 2 → ℕ) :
    swapExp e = e ∘ (denote exampleCrossing).symm := by
  funext j
  revert j
  exact Fin.forall_fin_two.mpr ⟨rfl, rfl⟩

/-- Monomial-level denotation coherence of the example crossing: the
translated operator moves exponents along the even endpoint permutation
(`e ∘ σ⁻¹`, `σ = denote exampleCrossing`) with the exact signed-swap sign. -/
theorem example_monomial_coherence (e : Fin 2 → ℕ) (r : ℤ) :
    exampleOp (monomial e r) =
      monomial (e ∘ (denote exampleCrossing).symm) (r * swapSign e) := by
  rw [exampleOp_eq, symm1_monomial, swapExp_eq_denote]

/-- Worked example: the translated adjacent transposition is involutive on
every rank-two integer skew polynomial (no degree bound, arbitrary integer
coefficients). Genuine consumer of the existing `SignedSwap.symm1_involute`. -/
theorem example_involutive : Function.Involutive exampleOp := fun f => by
  rw [exampleOp_eq, exampleOp_eq]
  exact SignedSwap.symm1_involute f

/-- Translation of the example square `seq below above`: the entry of `below`
is applied first, then the entry of `above` (chronological order). -/
noncomputable def exampleSquareOp (f : SkewPolynomial 2) : SkewPolynomial 2 :=
  exampleOp (exampleOp f)

theorem exampleSquareOp_eq (f : SkewPolynomial 2) : exampleSquareOp f = f :=
  example_involutive f

/-- Denotation coherence for the worked example: the square has the even
denotation of the identity diagram `Expr.id 2`, and its translation is the
identity operator on every rank-two integer skew polynomial. -/
theorem example_denotation_coherence :
    denote exampleSquare = denote (Expr.id 2) ∧
      ∀ f : SkewPolynomial 2, exampleSquareOp f = f :=
  ⟨denote_exampleSquare, exampleSquareOp_eq⟩

end OddMath.Frontier.DiagramTranslation
