import OddMath.Frontier.EKAppendixData
import OddMath.Frontier.EKAppendixDataControls

/-! Audit: axioms of every owned named declaration
(production and controls), and post-production altered-entry controls: a
deliberately altered printed entry must be REFUTED by the production theorems. -/
namespace OddMath.Frontier.EKAppendixDataAudit
open EKAppendixData

/-- Altered Sec. 5.1 entry: K_((311),(11111)) printed 2, altered to 3, is refuted. -/
theorem altered_kostka_fails :
    ¬ TableauDominance.signedKostka (YoungDiagram.ofRowLens [3,1,1] (by decide))
      (YoungDiagram.ofRowLens [1,1,1,1,1] (by decide)) = 3 := by
  rw [kostka5_311_11111]; decide

/-- Altered Sec. 5.2 entry: (h221,h221) printed -3, altered to 3, is refuted. -/
theorem altered_gram_fails :
    ¬ EKDualBases.Mh 5 (hshapes5 2) (hshapes5 2) = 3 := by
  rw [gram_table5]; decide

/-- Altered whole-table control: the degree-5 Kostka table with the (311),(11111)
entry changed to 3 is not the existing table. -/
def alteredKostka5 : Matrix (Fin 7) (Fin 7) ℤ := !![1, 0, 0, 0, 0, 0, 0;
    0, 1, 0, 0, 0, 0, 0;
    (-1), 0, 1, 0, 0, 0, 0;
    3, 1, (-1), 1, 0, 0, 0;
    1, 1, 0, 1, 1, 0, 0;
    0, 1, 2, 0, (-1), 1, 0;
    1, 1, 1, 1, 1, 1, 1]

theorem altered_kostka_table_fails :
    ¬ ∀ i j, TableauDominance.signedKostka (shapes5 i) (shapes5 j) = alteredKostka5 i j := by
  intro h
  have := h 3 0
  rw [kostka_table5] at this
  revert this; decide

end OddMath.Frontier.EKAppendixDataAudit

#print axioms OddMath.Frontier.EKAppendixData.incWords
#print axioms OddMath.Frontier.EKAppendixData.mem_incWords
#print axioms OddMath.Frontier.EKAppendixData.rowCands
#print axioms OddMath.Frontier.EKAppendixData.Valid
#print axioms OddMath.Frontier.EKAppendixData.decColumnBelow
#print axioms OddMath.Frontier.EKAppendixData.decValid
#print axioms OddMath.Frontier.EKAppendixData.kEval
#print axioms OddMath.Frontier.EKAppendixData.mem_rowCands
#print axioms OddMath.Frontier.EKAppendixData.columnBelow_nil
#print axioms OddMath.Frontier.EKAppendixData.columns_all
#print axioms OddMath.Frontier.EKAppendixData.entry_of_rows
#print axioms OddMath.Frontier.EKAppendixData.rows_injective
#print axioms OddMath.Frontier.EKAppendixData.row_entry_ge
#print axioms OddMath.Frontier.EKAppendixData.count_rows
#print axioms OddMath.Frontier.EKAppendixData.content_above
#print axioms OddMath.Frontier.EKAppendixData.sign_rows
#print axioms OddMath.Frontier.EKAppendixData.shape_eq_of_rowLens
#print axioms OddMath.Frontier.EKAppendixData.fiber_sum
#print axioms OddMath.Frontier.EKAppendixData.rowLen_eq_getD
#print axioms OddMath.Frontier.EKAppendixData.shapeContent_apply
#print axioms OddMath.Frontier.EKAppendixData.shapeContent_zero
#print axioms OddMath.Frontier.EKAppendixData.shapeContent_succ
#print axioms OddMath.Frontier.EKAppendixData.fiberSum_shape
#print axioms OddMath.Frontier.EKAppendixData.signedKostka_eval
#print axioms OddMath.Frontier.EKAppendixData.signedKostka_ofRowLens
#print axioms OddMath.Frontier.EKAppendixData.comps
#print axioms OddMath.Frontier.EKAppendixData.mem_comps
#print axioms OddMath.Frontier.EKAppendixData.matCands
#print axioms OddMath.Frontier.EKAppendixData.mem_matCands
#print axioms OddMath.Frontier.EKAppendixData.ent
#print axioms OddMath.Frontier.EKAppendixData.colSumsL
#print axioms OddMath.Frontier.EKAppendixData.matSet
#print axioms OddMath.Frontier.EKAppendixData.toL
#print axioms OddMath.Frontier.EKAppendixData.ent_toL
#print axioms OddMath.Frontier.EKAppendixData.toL_injective
#print axioms OddMath.Frontier.EKAppendixData.list_sum_range
#print axioms OddMath.Frontier.EKAppendixData.forall₂_ofFn
#print axioms OddMath.Frontier.EKAppendixData.mat_sum
#print axioms OddMath.Frontier.EKAppendixData.crossL
#print axioms OddMath.Frontier.EKAppendixData.crossing_toL
#print axioms OddMath.Frontier.EKAppendixData.mhEval
#print axioms OddMath.Frontier.EKAppendixData.pairing_eval
#print axioms OddMath.Frontier.EKAppendixData.Mh_eval
#print axioms OddMath.Frontier.EKAppendixData.Mh_ofRowLens
#print axioms OddMath.Frontier.EKAppendixData.compPairing_eval
#print axioms OddMath.Frontier.EKAppendixData.card_yd
#print axioms OddMath.Frontier.EKAppendixData.shapes1
#print axioms OddMath.Frontier.EKAppendixData.printedKostka1
#print axioms OddMath.Frontier.EKAppendixData.kostka1_1_1
#print axioms OddMath.Frontier.EKAppendixData.kostka_table1
#print axioms OddMath.Frontier.EKAppendixData.shapes2
#print axioms OddMath.Frontier.EKAppendixData.printedKostka2
#print axioms OddMath.Frontier.EKAppendixData.kostka2_11_11
#print axioms OddMath.Frontier.EKAppendixData.kostka2_11_2
#print axioms OddMath.Frontier.EKAppendixData.kostka2_2_11
#print axioms OddMath.Frontier.EKAppendixData.kostka2_2_2
#print axioms OddMath.Frontier.EKAppendixData.kostka_table2
#print axioms OddMath.Frontier.EKAppendixData.shapes3
#print axioms OddMath.Frontier.EKAppendixData.printedKostka3
#print axioms OddMath.Frontier.EKAppendixData.kostka3_111_111
#print axioms OddMath.Frontier.EKAppendixData.kostka3_111_21
#print axioms OddMath.Frontier.EKAppendixData.kostka3_111_3
#print axioms OddMath.Frontier.EKAppendixData.kostka3_21_111
#print axioms OddMath.Frontier.EKAppendixData.kostka3_21_21
#print axioms OddMath.Frontier.EKAppendixData.kostka3_21_3
#print axioms OddMath.Frontier.EKAppendixData.kostka3_3_111
#print axioms OddMath.Frontier.EKAppendixData.kostka3_3_21
#print axioms OddMath.Frontier.EKAppendixData.kostka3_3_3
#print axioms OddMath.Frontier.EKAppendixData.kostka_table3
#print axioms OddMath.Frontier.EKAppendixData.shapes4
#print axioms OddMath.Frontier.EKAppendixData.printedKostka4
#print axioms OddMath.Frontier.EKAppendixData.kostka4_1111_1111
#print axioms OddMath.Frontier.EKAppendixData.kostka4_1111_211
#print axioms OddMath.Frontier.EKAppendixData.kostka4_1111_22
#print axioms OddMath.Frontier.EKAppendixData.kostka4_1111_31
#print axioms OddMath.Frontier.EKAppendixData.kostka4_1111_4
#print axioms OddMath.Frontier.EKAppendixData.kostka4_211_1111
#print axioms OddMath.Frontier.EKAppendixData.kostka4_211_211
#print axioms OddMath.Frontier.EKAppendixData.kostka4_211_22
#print axioms OddMath.Frontier.EKAppendixData.kostka4_211_31
#print axioms OddMath.Frontier.EKAppendixData.kostka4_211_4
#print axioms OddMath.Frontier.EKAppendixData.kostka4_22_1111
#print axioms OddMath.Frontier.EKAppendixData.kostka4_22_211
#print axioms OddMath.Frontier.EKAppendixData.kostka4_22_22
#print axioms OddMath.Frontier.EKAppendixData.kostka4_22_31
#print axioms OddMath.Frontier.EKAppendixData.kostka4_22_4
#print axioms OddMath.Frontier.EKAppendixData.kostka4_31_1111
#print axioms OddMath.Frontier.EKAppendixData.kostka4_31_211
#print axioms OddMath.Frontier.EKAppendixData.kostka4_31_22
#print axioms OddMath.Frontier.EKAppendixData.kostka4_31_31
#print axioms OddMath.Frontier.EKAppendixData.kostka4_31_4
#print axioms OddMath.Frontier.EKAppendixData.kostka4_4_1111
#print axioms OddMath.Frontier.EKAppendixData.kostka4_4_211
#print axioms OddMath.Frontier.EKAppendixData.kostka4_4_22
#print axioms OddMath.Frontier.EKAppendixData.kostka4_4_31
#print axioms OddMath.Frontier.EKAppendixData.kostka4_4_4
#print axioms OddMath.Frontier.EKAppendixData.kostka_table4
#print axioms OddMath.Frontier.EKAppendixData.shapes5
#print axioms OddMath.Frontier.EKAppendixData.printedKostka5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_11111_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_2111_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_221_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_311_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_32_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_41_5
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_11111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_2111
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_221
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_311
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_32
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_41
#print axioms OddMath.Frontier.EKAppendixData.kostka5_5_5
#print axioms OddMath.Frontier.EKAppendixData.kostka_table5
#print axioms OddMath.Frontier.EKAppendixData.hshapes1
#print axioms OddMath.Frontier.EKAppendixData.printedGram1
#print axioms OddMath.Frontier.EKAppendixData.gram1_1_1
#print axioms OddMath.Frontier.EKAppendixData.gram_table1
#print axioms OddMath.Frontier.EKAppendixData.hshapes2
#print axioms OddMath.Frontier.EKAppendixData.printedGram2
#print axioms OddMath.Frontier.EKAppendixData.gram2_11_11
#print axioms OddMath.Frontier.EKAppendixData.gram2_11_2
#print axioms OddMath.Frontier.EKAppendixData.gram2_2_11
#print axioms OddMath.Frontier.EKAppendixData.gram2_2_2
#print axioms OddMath.Frontier.EKAppendixData.gram_table2
#print axioms OddMath.Frontier.EKAppendixData.hshapes3
#print axioms OddMath.Frontier.EKAppendixData.printedGram3
#print axioms OddMath.Frontier.EKAppendixData.gram3_111_111
#print axioms OddMath.Frontier.EKAppendixData.gram3_111_21
#print axioms OddMath.Frontier.EKAppendixData.gram3_111_3
#print axioms OddMath.Frontier.EKAppendixData.gram3_21_111
#print axioms OddMath.Frontier.EKAppendixData.gram3_21_21
#print axioms OddMath.Frontier.EKAppendixData.gram3_21_3
#print axioms OddMath.Frontier.EKAppendixData.gram3_3_111
#print axioms OddMath.Frontier.EKAppendixData.gram3_3_21
#print axioms OddMath.Frontier.EKAppendixData.gram3_3_3
#print axioms OddMath.Frontier.EKAppendixData.gram_table3
#print axioms OddMath.Frontier.EKAppendixData.hshapes4
#print axioms OddMath.Frontier.EKAppendixData.printedGram4
#print axioms OddMath.Frontier.EKAppendixData.gram4_1111_1111
#print axioms OddMath.Frontier.EKAppendixData.gram4_1111_211
#print axioms OddMath.Frontier.EKAppendixData.gram4_1111_22
#print axioms OddMath.Frontier.EKAppendixData.gram4_1111_31
#print axioms OddMath.Frontier.EKAppendixData.gram4_1111_4
#print axioms OddMath.Frontier.EKAppendixData.gram4_211_1111
#print axioms OddMath.Frontier.EKAppendixData.gram4_211_211
#print axioms OddMath.Frontier.EKAppendixData.gram4_211_22
#print axioms OddMath.Frontier.EKAppendixData.gram4_211_31
#print axioms OddMath.Frontier.EKAppendixData.gram4_211_4
#print axioms OddMath.Frontier.EKAppendixData.gram4_22_1111
#print axioms OddMath.Frontier.EKAppendixData.gram4_22_211
#print axioms OddMath.Frontier.EKAppendixData.gram4_22_22
#print axioms OddMath.Frontier.EKAppendixData.gram4_22_31
#print axioms OddMath.Frontier.EKAppendixData.gram4_22_4
#print axioms OddMath.Frontier.EKAppendixData.gram4_31_1111
#print axioms OddMath.Frontier.EKAppendixData.gram4_31_211
#print axioms OddMath.Frontier.EKAppendixData.gram4_31_22
#print axioms OddMath.Frontier.EKAppendixData.gram4_31_31
#print axioms OddMath.Frontier.EKAppendixData.gram4_31_4
#print axioms OddMath.Frontier.EKAppendixData.gram4_4_1111
#print axioms OddMath.Frontier.EKAppendixData.gram4_4_211
#print axioms OddMath.Frontier.EKAppendixData.gram4_4_22
#print axioms OddMath.Frontier.EKAppendixData.gram4_4_31
#print axioms OddMath.Frontier.EKAppendixData.gram4_4_4
#print axioms OddMath.Frontier.EKAppendixData.gram_table4
#print axioms OddMath.Frontier.EKAppendixData.hshapes5
#print axioms OddMath.Frontier.EKAppendixData.printedGram5
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_11111_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_2111_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_221_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_311_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_32_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_41_5
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_11111
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_2111
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_221
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_311
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_32
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_41
#print axioms OddMath.Frontier.EKAppendixData.gram5_5_5
#print axioms OddMath.Frontier.EKAppendixData.gram_table5
#print axioms OddMath.Frontier.EKAppendixData.qi
#print axioms OddMath.Frontier.EKAppendixData.qf
#print axioms OddMath.Frontier.EKAppendixData.hword
#print axioms OddMath.Frontier.EKAppendixData.hword_pairing
#print axioms OddMath.Frontier.EKAppendixData.qgen1_1_1
#print axioms OddMath.Frontier.EKAppendixData.qgen2_11_11
#print axioms OddMath.Frontier.EKAppendixData.qgen2_11_2
#print axioms OddMath.Frontier.EKAppendixData.qgen2_2_2
#print axioms OddMath.Frontier.EKAppendixData.qgen3_111_111
#print axioms OddMath.Frontier.EKAppendixData.qgen3_111_12
#print axioms OddMath.Frontier.EKAppendixData.qgen3_111_21
#print axioms OddMath.Frontier.EKAppendixData.qgen3_111_3
#print axioms OddMath.Frontier.EKAppendixData.qgen3_12_12
#print axioms OddMath.Frontier.EKAppendixData.qgen3_12_21
#print axioms OddMath.Frontier.EKAppendixData.qgen3_12_3
#print axioms OddMath.Frontier.EKAppendixData.qgen3_21_21
#print axioms OddMath.Frontier.EKAppendixData.qgen3_21_3
#print axioms OddMath.Frontier.EKAppendixData.qgen3_3_3
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_1111
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_112
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_121
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_211
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_22
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_1111_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_112
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_121
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_211
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_22
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_112_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_121
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_211
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_22
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_121_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_211_211
#print axioms OddMath.Frontier.EKAppendixData.qgen4_211_22
#print axioms OddMath.Frontier.EKAppendixData.qgen4_211_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_211_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_211_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_22_22
#print axioms OddMath.Frontier.EKAppendixData.qgen4_22_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_22_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_22_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_13_13
#print axioms OddMath.Frontier.EKAppendixData.qgen4_13_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_13_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_31_31
#print axioms OddMath.Frontier.EKAppendixData.qgen4_31_4
#print axioms OddMath.Frontier.EKAppendixData.qgen4_4_4
#print axioms OddMath.Frontier.EKAppendixData.le1
#print axioms OddMath.Frontier.EKAppendixData.decLe1
#print axioms OddMath.Frontier.EKAppendixData.le1_toL
#print axioms OddMath.Frontier.EKAppendixData.mEval
#print axioms OddMath.Frontier.EKAppendixData.M_eval
#print axioms OddMath.Frontier.EKAppendixData.M_ofRowLens
#print axioms OddMath.Frontier.EKAppendixData.partL
#print axioms OddMath.Frontier.EKAppendixData.mem_partL
#print axioms OddMath.Frontier.EKAppendixData.rowLens_sum
#print axioms OddMath.Frontier.EKAppendixData.rowLens_mem_partL
#print axioms OddMath.Frontier.EKAppendixData.exhaust
#print axioms OddMath.Frontier.EKAppendixData.inj_of_rowLens
#print axioms OddMath.Frontier.EKAppendixData.m_of_table
#print axioms OddMath.Frontier.EKAppendixData.f_of_table
#print axioms OddMath.Frontier.EKAppendixData.kostka_inverse_relation
#print axioms OddMath.Frontier.EKAppendixData.pl1
#print axioms OddMath.Frontier.EKAppendixData.hs1
#print axioms OddMath.Frontier.EKAppendixData.exhaust1
#print axioms OddMath.Frontier.EKAppendixData.inj1
#print axioms OddMath.Frontier.EKAppendixData.gramM1
#print axioms OddMath.Frontier.EKAppendixData.gramM1_1_1
#print axioms OddMath.Frontier.EKAppendixData.gramM_table1
#print axioms OddMath.Frontier.EKAppendixData.mExp1_1
#print axioms OddMath.Frontier.EKAppendixData.fExp1_1
#print axioms OddMath.Frontier.EKAppendixData.printedSchur1
#print axioms OddMath.Frontier.EKAppendixData.schur_kostka_inverse1
#print axioms OddMath.Frontier.EKAppendixData.schur_relation1
#print axioms OddMath.Frontier.EKAppendixData.pl2
#print axioms OddMath.Frontier.EKAppendixData.hs2
#print axioms OddMath.Frontier.EKAppendixData.exhaust2
#print axioms OddMath.Frontier.EKAppendixData.inj2
#print axioms OddMath.Frontier.EKAppendixData.gramM2
#print axioms OddMath.Frontier.EKAppendixData.gramM2_11_11
#print axioms OddMath.Frontier.EKAppendixData.gramM2_11_2
#print axioms OddMath.Frontier.EKAppendixData.gramM2_2_11
#print axioms OddMath.Frontier.EKAppendixData.gramM2_2_2
#print axioms OddMath.Frontier.EKAppendixData.gramM_table2
#print axioms OddMath.Frontier.EKAppendixData.mExp2_11
#print axioms OddMath.Frontier.EKAppendixData.mExp2_2
#print axioms OddMath.Frontier.EKAppendixData.fExp2_11
#print axioms OddMath.Frontier.EKAppendixData.fExp2_2
#print axioms OddMath.Frontier.EKAppendixData.printedSchur2
#print axioms OddMath.Frontier.EKAppendixData.schur_kostka_inverse2
#print axioms OddMath.Frontier.EKAppendixData.schur_relation2
#print axioms OddMath.Frontier.EKAppendixData.pl3
#print axioms OddMath.Frontier.EKAppendixData.hs3
#print axioms OddMath.Frontier.EKAppendixData.exhaust3
#print axioms OddMath.Frontier.EKAppendixData.inj3
#print axioms OddMath.Frontier.EKAppendixData.gramM3
#print axioms OddMath.Frontier.EKAppendixData.gramM3_111_111
#print axioms OddMath.Frontier.EKAppendixData.gramM3_111_21
#print axioms OddMath.Frontier.EKAppendixData.gramM3_111_3
#print axioms OddMath.Frontier.EKAppendixData.gramM3_21_111
#print axioms OddMath.Frontier.EKAppendixData.gramM3_21_21
#print axioms OddMath.Frontier.EKAppendixData.gramM3_21_3
#print axioms OddMath.Frontier.EKAppendixData.gramM3_3_111
#print axioms OddMath.Frontier.EKAppendixData.gramM3_3_21
#print axioms OddMath.Frontier.EKAppendixData.gramM3_3_3
#print axioms OddMath.Frontier.EKAppendixData.gramM_table3
#print axioms OddMath.Frontier.EKAppendixData.mExp3_111
#print axioms OddMath.Frontier.EKAppendixData.mExp3_21
#print axioms OddMath.Frontier.EKAppendixData.mExp3_3
#print axioms OddMath.Frontier.EKAppendixData.fExp3_111
#print axioms OddMath.Frontier.EKAppendixData.fExp3_21
#print axioms OddMath.Frontier.EKAppendixData.fExp3_3
#print axioms OddMath.Frontier.EKAppendixData.printedSchur3
#print axioms OddMath.Frontier.EKAppendixData.schur_kostka_inverse3
#print axioms OddMath.Frontier.EKAppendixData.schur_relation3
#print axioms OddMath.Frontier.EKAppendixData.pl4
#print axioms OddMath.Frontier.EKAppendixData.hs4
#print axioms OddMath.Frontier.EKAppendixData.exhaust4
#print axioms OddMath.Frontier.EKAppendixData.inj4
#print axioms OddMath.Frontier.EKAppendixData.gramM4
#print axioms OddMath.Frontier.EKAppendixData.gramM4_1111_1111
#print axioms OddMath.Frontier.EKAppendixData.gramM4_1111_211
#print axioms OddMath.Frontier.EKAppendixData.gramM4_1111_22
#print axioms OddMath.Frontier.EKAppendixData.gramM4_1111_31
#print axioms OddMath.Frontier.EKAppendixData.gramM4_1111_4
#print axioms OddMath.Frontier.EKAppendixData.gramM4_211_1111
#print axioms OddMath.Frontier.EKAppendixData.gramM4_211_211
#print axioms OddMath.Frontier.EKAppendixData.gramM4_211_22
#print axioms OddMath.Frontier.EKAppendixData.gramM4_211_31
#print axioms OddMath.Frontier.EKAppendixData.gramM4_211_4
#print axioms OddMath.Frontier.EKAppendixData.gramM4_22_1111
#print axioms OddMath.Frontier.EKAppendixData.gramM4_22_211
#print axioms OddMath.Frontier.EKAppendixData.gramM4_22_22
#print axioms OddMath.Frontier.EKAppendixData.gramM4_22_31
#print axioms OddMath.Frontier.EKAppendixData.gramM4_22_4
#print axioms OddMath.Frontier.EKAppendixData.gramM4_31_1111
#print axioms OddMath.Frontier.EKAppendixData.gramM4_31_211
#print axioms OddMath.Frontier.EKAppendixData.gramM4_31_22
#print axioms OddMath.Frontier.EKAppendixData.gramM4_31_31
#print axioms OddMath.Frontier.EKAppendixData.gramM4_31_4
#print axioms OddMath.Frontier.EKAppendixData.gramM4_4_1111
#print axioms OddMath.Frontier.EKAppendixData.gramM4_4_211
#print axioms OddMath.Frontier.EKAppendixData.gramM4_4_22
#print axioms OddMath.Frontier.EKAppendixData.gramM4_4_31
#print axioms OddMath.Frontier.EKAppendixData.gramM4_4_4
#print axioms OddMath.Frontier.EKAppendixData.gramM_table4
#print axioms OddMath.Frontier.EKAppendixData.mExp4_1111
#print axioms OddMath.Frontier.EKAppendixData.mExp4_211
#print axioms OddMath.Frontier.EKAppendixData.mExp4_22
#print axioms OddMath.Frontier.EKAppendixData.mExp4_31
#print axioms OddMath.Frontier.EKAppendixData.mExp4_4
#print axioms OddMath.Frontier.EKAppendixData.fExp4_1111
#print axioms OddMath.Frontier.EKAppendixData.fExp4_211
#print axioms OddMath.Frontier.EKAppendixData.fExp4_22
#print axioms OddMath.Frontier.EKAppendixData.fExp4_31
#print axioms OddMath.Frontier.EKAppendixData.fExp4_4
#print axioms OddMath.Frontier.EKAppendixData.printedSchur4
#print axioms OddMath.Frontier.EKAppendixData.schur_kostka_inverse4
#print axioms OddMath.Frontier.EKAppendixData.schur_relation4
#print axioms OddMath.Frontier.EKAppendixData.pl5
#print axioms OddMath.Frontier.EKAppendixData.hs5
#print axioms OddMath.Frontier.EKAppendixData.exhaust5
#print axioms OddMath.Frontier.EKAppendixData.inj5
#print axioms OddMath.Frontier.EKAppendixData.printedSchur5
#print axioms OddMath.Frontier.EKAppendixData.schur_kostka_inverse5
#print axioms OddMath.Frontier.EKAppendixData.schur_relation5
#print axioms OddMath.Frontier.EKAppendixDataControls.printed_quotient_deg2
#print axioms OddMath.Frontier.EKAppendixDataControls.printed_kostka_deg2_diag
#print axioms OddMath.Frontier.EKAppendixDataControls.altered_entry_fails
#print axioms OddMath.Frontier.EKAppendixDataAudit.altered_kostka_fails
#print axioms OddMath.Frontier.EKAppendixDataAudit.altered_gram_fails
#print axioms OddMath.Frontier.EKAppendixDataAudit.alteredKostka5
#print axioms OddMath.Frontier.EKAppendixDataAudit.altered_kostka_table_fails
