import Mathlib.Logic.Relation
import Mathlib.Data.List.Sort

/-!
# EK Theorem 4.1 (classical plactic monoid): executable model and controls

Source: Ellis–Khovanov, arXiv:1107.5610v2, p.31, Sec. 4.1, relations (4.1):

    yzx = yxz  if x < y ≤ z   (K′)
    xzy = zxy  if x ≤ y < z   (K″)

and Theorem 4.1 (cited from Fulton, *Young Tableaux*, Sec. 2.1): every word is
equivalent via (K′), (K″) to the row word `wr(T)` of a unique semistandard tableau `T`.

This module is compiled BEFORE the production module and fixes the executable objects
that production reasons about:

* `bump1 R a` : Fulton row insertion of `a` into one row `R` (bump the first entry
  strictly greater than `a`; equal entries stay to the left);
* `ins rs a` : insertion into a list of rows (top row first, English convention);
* `P w := insW [] w` : insertion tableau of a word (letters inserted left to right);
* `readR rs` : row word, rows read left to right, bottom row first;
* `KStep` : one elementary Knuth transformation exactly as printed (K′)/(K″), in context;
* `moves w` : executable list of all words one printed transformation away from `w`
  (either direction).

Controls (kernel-checked with `decide`, no `native_decide`):
1. exhaustive over all words of length ≤ 5 on the alphabet {1,2,3}: `P` is constant
   along every printed elementary transformation, `P w` is a valid SSYT (rows weakly
   increasing, columns strictly increasing), `P (readR (P w)) = P w`, and the row word
   `readR (P w)` lies in the (K′)/(K″)-class of `w` (explicit closure);
2. a WRONG relation variant (K′ with `x ≤ y` in place of `x < y`) identifies the row
   words of two distinct SSYT, so it must fail.
-/

namespace OddMath.Frontier.EKClassicalPlactic

/-- Row insertion (Fulton §1.1): bump the first entry strictly greater than `a`. -/
def bump1 : List ℕ → ℕ → List ℕ × Option ℕ
  | [], a => ([a], none)
  | x :: xs, a => if a < x then (a :: xs, some x) else (x :: (bump1 xs a).1, (bump1 xs a).2)

/-- Row insertion into a tableau given as its rows, top row first. -/
def ins : List (List ℕ) → ℕ → List (List ℕ)
  | [], a => [[a]]
  | R :: rs, a => (bump1 R a).1 ::
      (match (bump1 R a).2 with
       | none => rs
       | some b => ins rs b)

/-- Insert the letters of `w` from left to right. -/
def insW (rs : List (List ℕ)) (w : List ℕ) : List (List ℕ) := w.foldl ins rs

/-- The insertion tableau `P(w)`. -/
def P (w : List ℕ) : List (List ℕ) := insW [] w

/-- Row word: left to right, bottom to top (rows are stored top row first). -/
def readR (rs : List (List ℕ)) : List ℕ := rs.reverse.flatten

/-- One elementary Knuth transformation, exactly as printed in EK (4.1), in a context
`u _ v`: (K′) `yzx → yxz` for `x < y ≤ z`, (K″) `xzy → zxy` for `x ≤ y < z`. -/
def KStep (w w' : List ℕ) : Prop :=
  ∃ (u v : List ℕ) (x y z : ℕ),
    (x < y ∧ y ≤ z ∧ w = u ++ [y, z, x] ++ v ∧ w' = u ++ [y, x, z] ++ v) ∨
    (x ≤ y ∧ y < z ∧ w = u ++ [x, z, y] ++ v ∧ w' = u ++ [z, x, y] ++ v)

/-- Knuth equivalence: the congruence (equivalence closure) generated by (K′), (K″). -/
def KnuthEquiv (w w' : List ℕ) : Prop := Relation.EqvGen KStep w w'

/-- The printed moves applicable at the head of a word (both directions). -/
def local3 (a b c : ℕ) : List (List ℕ) :=
  (if (a ≤ c ∧ c < b) ∨ (b ≤ c ∧ c < a) then [[b, a, c]] else []) ++
  (if (c < a ∧ a ≤ b) ∨ (b < a ∧ a ≤ c) then [[a, c, b]] else [])

/-- All words one printed elementary transformation away (either direction). -/
def moves : List ℕ → List (List ℕ)
  | a :: b :: c :: rest =>
      (local3 a b c).map (· ++ rest) ++ (moves (b :: c :: rest)).map (a :: ·)
  | _ => []

/-- All words of length exactly `k` over `{1,…,m}`. -/
def wordsOf (m : ℕ) : ℕ → List (List ℕ)
  | 0 => [[]]
  | k + 1 => (wordsOf m k).flatMap (fun w => (List.range m).map (fun i => (i + 1) :: w))

/-- All words of length ≤ `k` over `{1,…,m}`. -/
def wordsUpTo (m : ℕ) : ℕ → List (List ℕ)
  | 0 => [[]]
  | k + 1 => wordsUpTo m k ++ wordsOf m (k + 1)

/-- Boolean SSYT test on rows (top first): nonempty weakly increasing rows, columns strict. -/
def colStrictB : List ℕ → List ℕ → Bool
  | a :: as, b :: bs => decide (a < b) && colStrictB as bs
  | _, [] => true
  | [], _ :: _ => false

def sortedB : List ℕ → Bool
  | a :: b :: l => decide (a ≤ b) && sortedB (b :: l)
  | _ => true

def validB : List (List ℕ) → Bool
  | [] => true
  | [R] => !R.isEmpty && sortedB R
  | R :: R' :: S => !R.isEmpty && sortedB R && colStrictB R R' && validB (R' :: S)

/-- Knuth-class closure with fuel (dedup at every round). -/
def closeStep (S : List (List ℕ)) : List (List ℕ) :=
  (S ++ S.flatMap moves).dedup

def closure : ℕ → List (List ℕ) → List (List ℕ)
  | 0, S => S
  | k + 1, S => closure k (closeStep S)

/-- The exhaustive check set: all words of length ≤ 5 over {1,2,3} (364 words). -/
def controlWords : List (List ℕ) := wordsUpTo 3 5

theorem controlWords_length : controlWords.length = 364 := by decide +kernel

/-- Control 1a: `P` is constant along every printed elementary transformation. -/
theorem control_invariance :
    controlWords.all (fun w => (moves w).all (fun w' => P w' == P w)) = true := by decide +kernel

/-- Control 1b: `P w` is a semistandard tableau and `P` fixes its row word. -/
theorem control_valid_fixed :
    controlWords.all (fun w => validB (P w) && (P (readR (P w)) == P w)) = true := by decide +kernel

/-- Control 1c: `readR (P w)` lies in the explicit printed-move closure of `w`
(fuel 5 rounds, more than the diameter of every class of length ≤ 5). -/
theorem control_existence :
    controlWords.all (fun w => (closure 5 [w]).contains (readR (P w))) = true := by decide +kernel

/-- Control 1d (distinct row words of distinct tableaux stay separated): no two distinct
valid tableaux arising as `P w` have row words in one closure class. -/
theorem control_separation :
    controlWords.all (fun w => (closure 5 [w]).all (fun w' => P w' == P w)) = true := by decide +kernel

/-! ## Wrong relation variant (must fail) -/

/-- WRONG variant of (K′): `yzx = yxz` for `x ≤ y ≤ z` (weak instead of strict `x < y`). -/
def wrongLocal3 (a b c : ℕ) : List (List ℕ) :=
  (if (a ≤ c ∧ c < b) ∨ (b ≤ c ∧ c < a) then [[b, a, c]] else []) ++
  (if (c ≤ a ∧ a ≤ b) ∨ (b ≤ a ∧ a ≤ c) then [[a, c, b]] else [])

/-- The wrong variant relates `121` and `112`; the printed relations only give `121 ~ 211`. -/
theorem wrong_variant_step :
    wrongLocal3 1 2 1 = [[2, 1, 1], [1, 1, 2]] ∧ local3 1 2 1 = [[2, 1, 1]] := by decide

/-- `211` (row word of the SSYT with rows `[1,1]` over `[2]`) is printed-equivalent to
`121`, and `112` is the row word of the one-row SSYT `[1,1,2]`: two distinct tableaux. -/
theorem wrong_variant_breaks_uniqueness :
    (moves [2, 1, 1]).contains [1, 2, 1] = true ∧
    P [2, 1, 1] = [[1, 1], [2]] ∧ P [1, 1, 2] = [[1, 1, 2]] ∧
    readR [[1, 1], [2]] = [2, 1, 1] ∧ readR [[1, 1, 2]] = [1, 1, 2] ∧
    validB [[1, 1], [2]] = true ∧ validB [[1, 1, 2]] = true ∧
    P [2, 1, 1] ≠ P [1, 1, 2] := by decide

/-- The insertion invariant FAILS for the wrong variant (so the control really can fail). -/
theorem wrong_variant_fails :
    ¬ ((wrongLocal3 1 2 1).all (fun w' => P w' == P [1, 2, 1]) = true) := by decide

end OddMath.Frontier.EKClassicalPlactic
