import OddMath.Frontier.EKRestCenterQ
import OddMath.Frontier.EKGeneralQCoideal
import OddMath.Frontier.EKCompleteLemma215
import OddMath.Frontier.EKCompleteProp33
import Mathlib.RingTheory.AlgebraicIndependent.Basic

/-!
# EK over a base ring: the algebra `Λ_k = k ⊗ Λ_ℤ`, the centre over `ℚ`, Lemma 2.15 over any
# `k`, and Proposition 3.3 over any `k` in which `2` is not a zero divisor

Source: Ellis–Khovanov, arXiv:1107.5610v2.

Throughout `q = -1`, `k` is a commutative ring, `Λ_k = Lam (-1 : k)` is the quotient of
`Λ'_k` by the radical of the form (2.1) over `k`, and `Λ_ℤ = EKRadicalQuotient.Q`.
`psiRing : Λ_ℤ → Λ_k` is the comparison ring map `h_n ↦ h_n`.

* `baseChangeAlgEquiv k : k ⊗[ℤ] Λ_ℤ ≃ₐ[k] Λ_k` (Corollary 2.12, p. 15, as `k`-algebras).
* §3.2, p. 26 ("the center … is precisely the polynomial algebra generated by the `p_{2k}`'s"),
  over `ℚ`, for the paper's `Λ` itself:
  - `center_iff`: `w` is central in `Λ_ℚ` iff `w ∈ ℚ[p₂, p₄, …]`;
  - `algebraicIndependent_p`: the `p_{2k}` are algebraically independent over `ℚ`;
  - `centerEquiv : MvPolynomial ℕ ℚ ≃ₐ[ℚ] Z(Λ_ℚ)`, `X_j ↦ p_{2(j+1)}`.
* Lemma 2.15 (p. 18) over every commutative ring `k` (`lemma_2_15_K`): the Gram matrices of
  `{h_μ : μ ≥ λ}` and `{e_μ : μ > λᵀ}` in `Λ_k` have determinant `±1`, and the form is
  nondegenerate on `H_{≥λ}` and on `E_{>λᵀ}`.
* Proposition 3.3 (p. 25) over every commutative ring `k` in which `2` is not a zero divisor
  (in particular over every field of characteristic `0`, the setting of §3.2)
  (`proposition_3_3_K`): `x ∈ Λ_k` is primitive, `Δx = 1 ⊗ x + x ⊗ 1`, iff `x` lies in the
  `k`-span of `m_1, m_2, m_4, m_6, …`.  Here `Δ` is the coproduct of `Λ_k`
  (`EKGeneralQ.sepCoproduct`, Corollary 2.4 over `k`).  The hypothesis on `2` is needed only
  for odd degrees `≥ 3`, where `h₁h_{2j} + h_{2j}h₁ = 2h_{2j+1}` is used.
* Over `k = 𝔽₂` Proposition 3.3 fails (`proposition_3_3_fails_F2`): `m_3` is primitive in
  `Λ_{𝔽₂}` but is not in the span of `m_1, m_2, m_4, …`.  (The paper assumes characteristic
  `0` in §3.2, so this is not an erratum; it shows the hypothesis is needed.)
-/

noncomputable section
set_option synthInstance.maxHeartbeats 400000
open scoped TensorProduct BigOperators

namespace OddMath.Frontier.EKFinal
open EKGeneralQ

variable {k : Type*} [CommRing k]

/-! ## `Λ_k ≅ k ⊗ Λ_ℤ` as `k`-algebras -/

variable (k) in
/-- EK Corollary 2.12 as an isomorphism of `k`-algebras: `k ⊗_ℤ Λ_ℤ ≅ Λ_k`. -/
def baseChangeAlgEquiv : k ⊗[ℤ] EKRadicalQuotient.Q ≃ₐ[k] Lam (-1 : k) :=
  AlgEquiv.ofLinearEquiv baseChangeEquiv baseChangeEquiv_one baseChangeEquiv_mul

@[simp] theorem baseChangeAlgEquiv_tmul (c : k) (z : EKRadicalQuotient.Q) :
    baseChangeAlgEquiv k (c ⊗ₜ[ℤ] z) = c • psiRing z := rfl

/-- The form of `Λ_k` on images of `Λ_ℤ` is the image of the integral form. -/
theorem quotientForm_psiRing (a b : EKRadicalQuotient.Q) :
    quotientForm (-1 : k) (psiRing a) (psiRing b) =
      ((EKRadicalQuotient.quotientPairing a b : ℤ) : k) := by
  obtain ⟨x, rfl⟩ := EKRadicalQuotient.pi_surjective a
  obtain ⟨y, rfl⟩ := EKRadicalQuotient.pi_surjective b
  rw [psiRing_pi, psiRing_pi, quotientForm_pi, form_iota, form_neg_one,
    EKRadicalQuotient.quotientPairing_pi]

theorem quotientForm_symm (x y : Lam (-1 : k)) :
    quotientForm (-1 : k) x y = quotientForm (-1 : k) y x := by
  obtain ⟨x, rfl⟩ := piQ_surjective (-1 : k) x
  obtain ⟨y, rfl⟩ := piQ_surjective (-1 : k) y
  rw [quotientForm_pi, quotientForm_pi, form_symm]

/-! ## The centre of `Λ_ℚ` -/

/-- The image in `Λ_ℚ` of the element `p_n` of §3.2 (`EKCenterPower.p`). -/
def pQ (n : ℕ) : Lam (-1 : ℚ) := psiRing (EKCenterPower.p n)

theorem ratEquiv_iota (x : EKRadicalQuotient.Q) :
    baseChangeAlgEquiv ℚ (EKRest.iota x) = psiRing x := by
  rw [EKRest.iota_apply, baseChangeAlgEquiv_tmul, one_smul]

/-- The subalgebra `ℚ[p₂, p₄, …]` of `Λ_ℚ`. -/
def pAlg : Subalgebra ℚ (Lam (-1 : ℚ)) :=
  Algebra.adjoin ℚ (Set.range fun j : ℕ => pQ (2 * (j + 1)))

theorem map_pAlgQ : EKRest.pAlgQ.map (baseChangeAlgEquiv ℚ).toAlgHom = pAlg := by
  rw [EKRest.pAlgQ, AlgHom.map_adjoin, pAlg, ← Set.range_comp]
  have : (⇑(baseChangeAlgEquiv ℚ).toAlgHom ∘ fun j : ℕ => EKRest.iota (EKCenterPower.p (2 * (j + 1))))
      = fun j => pQ (2 * (j + 1)) := by
    funext j
    simp only [Function.comp_apply, AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, ratEquiv_iota, pQ]
  rw [this]

theorem center_map_iff (v : EKRest.LQ) :
    baseChangeAlgEquiv ℚ v ∈ Subalgebra.center ℚ (Lam (-1 : ℚ)) ↔
      v ∈ Subalgebra.center ℚ EKRest.LQ := by
  set e := baseChangeAlgEquiv ℚ
  simp only [Subalgebra.mem_center_iff]
  constructor
  · intro h g
    apply e.injective
    rw [map_mul, map_mul]
    exact h (e g)
  · intro h g
    obtain ⟨g, rfl⟩ := e.surjective g
    rw [← map_mul, ← map_mul, h g]

/-- **EK p. 26 over `ℚ`:** the centre of `Λ_ℚ` is the subalgebra generated by the `p_{2k}`. -/
theorem center_iff (w : Lam (-1 : ℚ)) :
    w ∈ Subalgebra.center ℚ (Lam (-1 : ℚ)) ↔ w ∈ pAlg := by
  set e := baseChangeAlgEquiv ℚ
  obtain ⟨v, rfl⟩ := e.surjective w
  rw [center_map_iff, EKRest.centerQ_iff, ← map_pAlgQ]
  constructor
  · intro hv; exact ⟨v, hv, rfl⟩
  · rintro ⟨u, hu, he⟩
    have : u = v := e.injective he
    rwa [← this]

theorem center_eq : Subalgebra.center ℚ (Lam (-1 : ℚ)) = pAlg :=
  SetLike.ext center_iff

/-- `p_{2(j+1)}` as an element of the centre of `Λ_ℚ`. -/
def pcK (j : ℕ) : Subalgebra.center ℚ (Lam (-1 : ℚ)) :=
  ⟨pQ (2 * (j + 1)), (center_iff _).2 (Algebra.subset_adjoin ⟨j, rfl⟩)⟩

/-- The isomorphism `Λ_ℚ ≅ ℚ ⊗ Λ_ℤ`, restricted to centres. -/
def centerMap : Subalgebra.center ℚ EKRest.LQ →ₐ[ℚ] Subalgebra.center ℚ (Lam (-1 : ℚ)) :=
  ((baseChangeAlgEquiv ℚ).toAlgHom.comp (Subalgebra.center ℚ EKRest.LQ).val).codRestrict _
    (fun z => (center_map_iff z.val).2 z.2)

theorem centerMap_injective : Function.Injective centerMap := by
  intro a b h
  apply Subtype.ext
  apply (baseChangeAlgEquiv ℚ).injective
  have := congrArg Subtype.val h
  simpa [centerMap] using this

/-- **The `p_{2k}` are algebraically independent over `ℚ`** (in the centre of `Λ_ℚ`). -/
theorem algebraicIndependent_p : AlgebraicIndependent ℚ pcK := by
  have h := EKRest.algebraicIndependent_pQ.map' (f := centerMap) centerMap_injective
  convert h using 1
  funext j
  apply Subtype.ext
  show pQ (2 * (j + 1)) = baseChangeAlgEquiv ℚ (EKRest.iota (EKCenterPower.p (2 * (j + 1))))
  rw [ratEquiv_iota, pQ]

theorem adjoin_pcK : Algebra.adjoin ℚ (Set.range pcK) = ⊤ := by
  rw [eq_top_iff]
  intro z _
  have hz : z.val ∈ pAlg := (center_iff _).1 z.2
  have hmap : (Algebra.adjoin ℚ (Set.range pcK)).map (Subalgebra.center ℚ (Lam (-1 : ℚ))).val =
      pAlg := by
    rw [AlgHom.map_adjoin, pAlg, ← Set.range_comp]
    rfl
  rw [← hmap] at hz
  obtain ⟨u, hu, he⟩ := hz
  have : u = z := Subtype.ext he
  rwa [← this]

/-- **EK p. 26 over `ℚ`:** the centre of `Λ_ℚ` is a polynomial algebra on the `p_{2k}`,
`k ≥ 1`: `MvPolynomial ℕ ℚ ≅ Z(Λ_ℚ)`, `X_j ↦ p_{2(j+1)}`. -/
def centerEquiv : MvPolynomial ℕ ℚ ≃ₐ[ℚ] Subalgebra.center ℚ (Lam (-1 : ℚ)) :=
  algebraicIndependent_p.aevalEquiv.trans
    ((Subalgebra.equivOfEq _ _ adjoin_pcK).trans Subalgebra.topEquiv)

theorem centerEquiv_X (j : ℕ) :
    ((centerEquiv (MvPolynomial.X j) : Subalgebra.center ℚ (Lam (-1 : ℚ))) : Lam (-1 : ℚ)) =
      pQ (2 * (j + 1)) := by
  simp [centerEquiv, pcK]

/-! ## Lemma 2.15 over an arbitrary commutative ring -/

/-- Nondegeneracy of the form of `Λ_k` on a submodule: its restricted kernel is zero. -/
def RestrictedNondegK (S : Submodule k (Lam (-1 : k))) : Prop :=
  ∀ x ∈ S, (∀ y ∈ S, quotientForm (-1 : k) x y = 0) → x = 0

/-- The Gram matrix over `k` of a finite family in `Λ_k`. -/
def gramK {ι : Type*} (v : ι → Lam (-1 : k)) : Matrix ι ι k :=
  Matrix.of fun i j => quotientForm (-1 : k) (v i) (v j)

theorem gramK_psiRing {ι : Type*} (v : ι → EKRadicalQuotient.Q) :
    gramK (k := k) (fun i => psiRing (v i)) = (EKComplete.gram v).map (Int.cast : ℤ → k) := by
  ext i j
  simp [gramK, EKComplete.gram, quotientForm_psiRing]

theorem det_gramK_psiRing {ι : Type*} {_ : Fintype ι} {_ : DecidableEq ι}
    (v : ι → EKRadicalQuotient.Q) :
    (gramK (k := k) (fun i => psiRing (v i))).det = (((EKComplete.gram v).det : ℤ) : k) := by
  rw [gramK_psiRing]
  exact ((Int.castRingHom k).map_det (EKComplete.gram v)).symm

/-- A family of images of `Λ_ℤ` whose integral Gram determinant is a unit spans a
nondegenerate submodule of `Λ_k`, over every `k`. -/
theorem nondeg_of_isUnit_gram {ι : Type*} {_ : Fintype ι} {_ : DecidableEq ι}
    (v : ι → EKRadicalQuotient.Q) (hu : IsUnit (EKComplete.gram v).det) :
    RestrictedNondegK (Submodule.span k (Set.range fun i => psiRing (v i))) := by
  intro x hx h0
  obtain ⟨c, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun k).mp hx
  set G : Matrix ι ι k := gramK (k := k) (fun i => psiRing (v i))
  have hG : IsUnit G.det := by
    rw [det_gramK_psiRing]
    exact hu.map (Int.castRingHom k)
  have hv : Matrix.vecMul c G = 0 := by
    funext j
    have := h0 (psiRing (v j)) (Submodule.subset_span ⟨j, rfl⟩)
    rw [map_sum, LinearMap.sum_apply] at this
    simpa [Matrix.vecMul, dotProduct, G, gramK] using this
  have hc : c = 0 := by
    have := congrArg (fun u => Matrix.vecMul u G⁻¹) hv
    simpa [Matrix.vecMul_vecMul, Matrix.mul_nonsing_inv _ hG] using this
  simp [hc]

local instance (d : ℕ) : Fintype (DegreeShapes.DegreeShape d) := DegreeShapes.degreeFintype d
local instance (d : ℕ) : DecidableEq (DegreeShapes.DegreeShape d) := Classical.decEq _

variable (k) in
/-- `H_{≥λ}` in `Λ_k` (lexicographic order, `|ν| = |λ|`), as on p. 18. -/
def HgeK (lam : YoungDiagram) : Submodule k (Lam (-1 : k)) :=
  Submodule.span k {x | ∃ ν : YoungDiagram, ν.card = lam.card ∧
    (ν = lam ∨ List.Lex (· < ·) lam.rowLens ν.rowLens) ∧ hBasisK ν = x}

variable (k) in
/-- `E_{>λᵀ}` in `Λ_k` in degree `|λ|` (lexicographic order), as on p. 18. -/
def EgtK (lam : YoungDiagram) : Submodule k (Lam (-1 : k)) :=
  Submodule.span k {x | ∃ ν : YoungDiagram, ν.card = lam.card ∧
    List.Lex (· < ·) lam.transpose.rowLens ν.rowLens ∧ eBasisK ν = x}

theorem psiRing_hPartition (μ : YoungDiagram) :
    psiRing (EKPartitionSpanning.hPartition μ) = hBasisK (k := k) μ := by
  rw [psi_hPartition, hBasisK_apply]

theorem HgeK_eq (lam : YoungDiagram) :
    HgeK k lam = Submodule.span k (Set.range fun i =>
      psiRing (EKComplete.hFam lam.card (EKComplete.PGe lam) i)) := by
  unfold HgeK
  congr 1
  ext x
  constructor
  · rintro ⟨ν, hd, hl, rfl⟩
    exact ⟨⟨⟨ν, hd⟩, hl⟩, psiRing_hPartition ν⟩
  · rintro ⟨⟨ν, hl⟩, rfl⟩
    exact ⟨ν.val, ν.property, hl, (psiRing_hPartition ν.val).symm⟩

theorem EgtK_eq (lam : YoungDiagram) :
    EgtK k lam = Submodule.span k (Set.range fun i =>
      psiRing (EKComplete.eFam lam.card (EKComplete.PGt lam.card lam.transpose) i)) := by
  unfold EgtK
  congr 1
  ext x
  constructor
  · rintro ⟨ν, hd, hl, rfl⟩
    exact ⟨⟨⟨ν, hd⟩, hl⟩, (eBasisK_eq_psi ν).symm⟩
  · rintro ⟨⟨ν, hl⟩, rfl⟩
    exact ⟨ν.val, ν.property, hl, eBasisK_eq_psi ν.val⟩

theorem int_isUnit_of {u : ℤ} (h : u = 1 ∨ u = -1) : IsUnit u := by
  rcases h with h | h <;> rw [h] <;> simp

theorem cast_pm_one {u : ℤ} (h : u = 1 ∨ u = -1) : ((u : ℤ) : k) = 1 ∨ ((u : ℤ) : k) = -1 := by
  rcases h with h | h <;> simp [h]

/-- **EK Lemma 2.15 over every commutative ring `k`** (`q = -1`): for every partition `λ`,
the Gram matrices of `{h_μ : μ ≥ λ}` and of `{e_μ : μ > λᵀ}` (`|μ| = |λ|`, lexicographic
order) in `Λ_k` have determinant `±1`, and the form is nondegenerate on `H_{≥λ}` and on
`E_{>λᵀ}`. -/
theorem lemma_2_15_K (lam : YoungDiagram) :
    RestrictedNondegK (HgeK k lam) ∧ RestrictedNondegK (EgtK k lam) ∧
    ((gramK (k := k) (fun i => psiRing (EKComplete.hFam lam.card (EKComplete.PGe lam) i))).det
        = 1 ∨
      (gramK (k := k) (fun i => psiRing (EKComplete.hFam lam.card (EKComplete.PGe lam) i))).det
        = -1) ∧
    ((gramK (k := k) (fun i =>
        psiRing (EKComplete.eFam lam.card (EKComplete.PGt lam.card lam.transpose) i))).det = 1 ∨
      (gramK (k := k) (fun i =>
        psiRing (EKComplete.eFam lam.card (EKComplete.PGt lam.card lam.transpose) i))).det
        = -1) := by
  obtain ⟨hH, hE⟩ := EKComplete.lemma_2_15_det lam
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [HgeK_eq]; exact nondeg_of_isUnit_gram _ (int_isUnit_of hH)
  · rw [EgtK_eq]; exact nondeg_of_isUnit_gram _ (int_isUnit_of hE)
  · rw [det_gramK_psiRing]; exact cast_pm_one hH
  · rw [det_gramK_psiRing]; exact cast_pm_one hE

/-! ## Proposition 3.3 over `k` -/

/-- The coproduct of `Λ_k` (Corollary 2.4 over `k`, `q = -1`). -/
abbrev coproductK : Lam (-1 : k) →ₗ[k] Lam (-1 : k) ⊗[k] Lam (-1 : k) :=
  sepCoproduct (separating_neg_one (k := k))

/-- The source predicate `Δx = 1 ⊗ x + x ⊗ 1` in `Λ_k`. -/
def IsPrimitiveK (x : Lam (-1 : k)) : Prop :=
  coproductK x = (1 : Lam (-1 : k)) ⊗ₜ[k] x + x ⊗ₜ[k] (1 : Lam (-1 : k))

theorem tensorTest_coproductK (a b x : Lam (-1 : k)) :
    tensorTest (-1 : k) a b (coproductK x) = quotientForm (-1 : k) (a * b) x := by
  obtain ⟨a, rfl⟩ := piQ_surjective (-1 : k) a
  obtain ⟨b, rfl⟩ := piQ_surjective (-1 : k) b
  obtain ⟨x, rfl⟩ := piQ_surjective (-1 : k) x
  rw [coproductK, sepCoproduct_pi, tensorTest_map, tensorForm_symm, adjointness, ← map_mul,
    quotientForm_pi]

/-- Primitivity in `Λ_k` is the derivation identity against the form. -/
theorem isPrimitiveK_iff (x : Lam (-1 : k)) :
    IsPrimitiveK x ↔ ∀ a b : Lam (-1 : k), quotientForm (-1 : k) (a * b) x =
      quotientForm (-1 : k) a 1 * quotientForm (-1 : k) b x +
        quotientForm (-1 : k) a x * quotientForm (-1 : k) b 1 := by
  constructor
  · intro hx a b
    have := tensorTest_coproductK a b x
    rw [hx, map_add, tensorTest_tmul, tensorTest_tmul] at this
    rw [← this, quotientForm_symm 1 a, quotientForm_symm x b, quotientForm_symm x a,
      quotientForm_symm 1 b]
  · intro h
    unfold IsPrimitiveK
    rw [← sub_eq_zero]
    apply (separating_neg_one (k := k))
    intro a b
    rw [map_sub, tensorTest_coproductK, map_add, tensorTest_tmul, tensorTest_tmul, h a b,
      quotientForm_symm 1 a, quotientForm_symm x b, quotientForm_symm x a,
      quotientForm_symm 1 b]
    ring

theorem quotientForm_one_right (y : L k) :
    quotientForm (-1 : k) (piQ (-1 : k) y) 1 = counit k y := by
  rw [← map_one (piQ (-1 : k)), quotientForm_pi, form_right_one]

theorem counit_h_pos {a : ℕ} (ha : 0 < a) : counit k (h k a) = 0 := by
  obtain ⟨a, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt ha)
  exact counit_h_succ a

theorem counit_hWord_pos (t : List ℕ) (ht : t ≠ []) (hp : ∀ b ∈ t, 0 < b) :
    counit k (hWord k t) = 0 := by
  cases t with
  | nil => exact absurd rfl ht
  | cons b t =>
    simp only [hWord, List.map_cons, List.prod_cons, counit_mul,
      counit_h_pos (hp b (by simp)), zero_mul]

theorem hWord_cons (a : ℕ) (t : List ℕ) : hWord k (a :: t) = h k a * hWord k t := by
  simp [hWord]

theorem prim_one_zero {x : Lam (-1 : k)} (hx : IsPrimitiveK x) :
    quotientForm (-1 : k) 1 x = 0 := by
  have h := (isPrimitiveK_iff x).1 hx 1 1
  have h11 : quotientForm (-1 : k) (1 : Lam (-1 : k)) 1 = 1 := by
    have := quotientForm_one_right (k := k) 1
    rwa [map_one (piQ (-1 : k)), counit_one] at this
  rw [one_mul, h11] at h
  linear_combination -h

theorem prim_long_zero {x : Lam (-1 : k)} (hx : IsPrimitiveK x) (a : ℕ) (t : List ℕ)
    (ha : 0 < a) (ht : t ≠ []) (htp : ∀ b ∈ t, 0 < b) :
    quotientForm (-1 : k) (piQ (-1 : k) (hWord k (a :: t))) x = 0 := by
  rw [hWord_cons, map_mul, (isPrimitiveK_iff x).1 hx, quotientForm_one_right,
    quotientForm_one_right, counit_h_pos ha, counit_hWord_pos t ht htp]
  ring

theorem psiRing_hQ (n : ℕ) :
    psiRing (EKElementaryQuotient.h n) = piQ (-1 : k) (h k n) := by
  rw [EKElementaryQuotient.h, ← h_int, psiRing_pi, iota_h]

theorem hK_rel (j : ℕ) :
    piQ (-1 : k) (h k 1) * piQ (-1 : k) (h k (2 * j)) +
      piQ (-1 : k) (h k (2 * j)) * piQ (-1 : k) (h k 1) =
      (2 : k) • piQ (-1 : k) (h k (2 * j + 1)) := by
  have h0 := EKQuotientRelations.complete_one_even j
  rw [zsmul_eq_mul] at h0
  have := congrArg (psiRing (k := k)) h0
  simp only [map_add, map_mul, map_intCast, psiRing_hQ] at this
  rw [this]
  push_cast
  rw [two_mul, two_smul]

theorem prim_odd {x : Lam (-1 : k)} (hx : IsPrimitiveK x) {j : ℕ} (hj : 0 < j) :
    2 * quotientForm (-1 : k) (piQ (-1 : k) (h k (2 * j + 1))) x = 0 := by
  have e := congrArg (fun z => quotientForm (-1 : k) z x) (hK_rel (k := k) j)
  simp only [map_add, LinearMap.add_apply, map_smul, LinearMap.smul_apply, smul_eq_mul] at e
  rw [(isPrimitiveK_iff x).1 hx, (isPrimitiveK_iff x).1 hx, quotientForm_one_right,
    quotientForm_one_right, counit_h_pos (by norm_num : 0 < 1),
    counit_h_pos (by omega : 0 < 2 * j)] at e
  linear_combination -e

variable (k) in
/-- The image in `Λ_k` of the integral `m_(n)` (EK §3.1). -/
def mK (n : ℕ) : Lam (-1 : k) := psiRing ((EKPrimitives.mRow n).val)

variable (k) in
/-- The generators of Proposition 3.3 over `k`: `m_1` and the `m_{2j}`, `j ≥ 1`. -/
def primGenK : Set (Lam (-1 : k)) :=
  {y | ∃ n : ℕ, 0 < n ∧ (n = 1 ∨ Even n) ∧ y = mK k n}

theorem hBasisK_mK {n : ℕ} (hn : n = 1 ∨ Even n) (hpos : 0 < n) (ν : YoungDiagram) :
    quotientForm (-1 : k) (hBasisK ν) (mK k n) = if ν.rowLens = [n] then 1 else 0 := by
  rw [← psiRing_hPartition, mK, quotientForm_psiRing, EKPrimitives.pairing_mRow n hn hpos,
    EKPrimitives.phi_hPartition]
  split_ifs <;> simp

/-- The derivation identity against `m ∈ Λ_k` holds for all `a, b` as soon as it holds on
images of `Λ_ℤ`. -/
theorem deriv_of_key (m : Lam (-1 : k))
    (key : ∀ a' b' : EKRadicalQuotient.Q,
      quotientForm (-1 : k) (psiRing a' * psiRing b') m =
        quotientForm (-1 : k) (psiRing a') 1 * quotientForm (-1 : k) (psiRing b') m +
        quotientForm (-1 : k) (psiRing a') m * quotientForm (-1 : k) (psiRing b') 1)
    (a b : Lam (-1 : k)) :
    quotientForm (-1 : k) (a * b) m =
      quotientForm (-1 : k) a 1 * quotientForm (-1 : k) b m +
        quotientForm (-1 : k) a m * quotientForm (-1 : k) b 1 := by
  have hspan : ∀ z : Lam (-1 : k), z ∈ Submodule.span k (Set.range (hBasisK (k := k))) := by
    intro z; rw [hBasisK.span_eq]; trivial
  induction hspan a using Submodule.span_induction with
  | mem a ha =>
    obtain ⟨μ, rfl⟩ := ha
    induction hspan b using Submodule.span_induction with
    | mem b hb =>
      obtain ⟨ν, rfl⟩ := hb
      rw [← psiRing_hPartition, ← psiRing_hPartition]
      exact key _ _
    | zero => simp
    | add b c _ _ hb hc =>
      simp only [mul_add, map_add, LinearMap.add_apply]
      rw [hb, hc]
      ring
    | smul c b _ hb =>
      simp only [mul_smul_comm, map_smul, LinearMap.smul_apply, smul_eq_mul]
      rw [hb]
      ring
  | zero => simp
  | add a c _ _ ha hc =>
    simp only [add_mul, map_add, LinearMap.add_apply]
    rw [ha, hc]
    ring
  | smul c a _ ha =>
    simp only [smul_mul_assoc, map_smul, LinearMap.smul_apply, smul_eq_mul]
    rw [ha]
    ring

theorem mK_deriv {n : ℕ} (hn : n = 1 ∨ Even n) (hpos : 0 < n) (a b : Lam (-1 : k)) :
    quotientForm (-1 : k) (a * b) (mK k n) =
      quotientForm (-1 : k) a 1 * quotientForm (-1 : k) b (mK k n) +
        quotientForm (-1 : k) a (mK k n) * quotientForm (-1 : k) b 1 := by
  apply deriv_of_key
  intro a' b'
  rw [← map_one (psiRing (k := k)), ← map_mul, mK, quotientForm_psiRing, quotientForm_psiRing,
    quotientForm_psiRing, quotientForm_psiRing, quotientForm_psiRing,
    EKPrimitives.pairing_mRow n hn hpos, EKPrimitives.pairing_mRow n hn hpos,
    EKPrimitives.pairing_mRow n hn hpos, EKPrimitives.phi_mul,
    EKRadicalQuotient.quotientPairing_right_one, EKRadicalQuotient.quotientPairing_right_one]
  push_cast
  ring

theorem mK_primitive {n : ℕ} (hn : n = 1 ∨ Even n) (hpos : 0 < n) : IsPrimitiveK (mK k n) :=
  (isPrimitiveK_iff _).2 (mK_deriv hn hpos)

theorem isPrimitiveK_zero : IsPrimitiveK (0 : Lam (-1 : k)) := by
  simp [IsPrimitiveK]

theorem isPrimitiveK_add {x y : Lam (-1 : k)} (hx : IsPrimitiveK x) (hy : IsPrimitiveK y) :
    IsPrimitiveK (x + y) := by
  unfold IsPrimitiveK at *
  rw [map_add, hx, hy, TensorProduct.tmul_add, TensorProduct.add_tmul]
  abel

theorem isPrimitiveK_smul (c : k) {x : Lam (-1 : k)} (hx : IsPrimitiveK x) :
    IsPrimitiveK (c • x) := by
  unfold IsPrimitiveK at *
  rw [map_smul, hx, smul_add, ← TensorProduct.tmul_smul, ← TensorProduct.smul_tmul']

theorem hBasisK_eq (ν : YoungDiagram) : hBasisK (k := k) ν = piQ (-1 : k) (hWord k ν.rowLens) :=
  hBasisK_apply ν

theorem form_hBasisK_deg (ν μ : YoungDiagram) (hd : ν.card ≠ μ.card) :
    quotientForm (-1 : k) (hBasisK ν) (hBasisK μ) = 0 := by
  rw [quotientForm_hBasisK, pairing_hPartition_degreePiece ν hd (EKPrimitives.hPartition_mem μ)]
  simp

/-- **EK Proposition 3.3 over `k`** (`q = -1`), for every commutative ring `k` in which `2` is
not a zero divisor, in particular for every field of characteristic `0` (the setting of §3.2):
`x ∈ Λ_k` is primitive iff it lies in the `k`-span of `m_1, m_2, m_4, m_6, …`. -/
theorem proposition_3_3_K (h2 : ∀ c : k, 2 * c = 0 → c = 0) (x : Lam (-1 : k)) :
    IsPrimitiveK x ↔ x ∈ Submodule.span k (primGenK k) := by
  classical
  constructor
  · intro hx
    set S := (hBasisK (k := k)).repr x
    set N := (S.support.image (fun μ : YoungDiagram => μ.card)).filter
      (fun n => 0 < n ∧ (n = 1 ∨ Even n))
    set c : ℕ → k := fun n => quotientForm (-1 : k) (piQ (-1 : k) (h k n)) x
    set y := ∑ n ∈ N, c n • mK k n
    have hy : y ∈ Submodule.span k (primGenK k) := by
      apply Submodule.sum_mem
      intro n hn
      obtain ⟨-, hpos, hn'⟩ := Finset.mem_filter.mp hn
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨n, hpos, hn', rfl⟩)
    -- the coordinates of `x`
    have hxdeg : ∀ ν : YoungDiagram, ν.card ∉ S.support.image (fun μ : YoungDiagram => μ.card) →
        quotientForm (-1 : k) (hBasisK ν) x = 0 := by
      intro ν hν
      conv_lhs => rw [← (hBasisK (k := k)).linearCombination_repr x]
      rw [Finsupp.linearCombination_apply, Finsupp.sum, map_sum]
      apply Finset.sum_eq_zero
      intro μ hμ
      rw [map_smul, smul_eq_mul, form_hBasisK_deg ν μ, mul_zero]
      intro he
      exact hν (Finset.mem_image.mpr ⟨μ, hμ, he.symm⟩)
    have hyν : ∀ ν : YoungDiagram, quotientForm (-1 : k) (hBasisK ν) y =
        ∑ n ∈ N, c n * (if ν.rowLens = [n] then 1 else 0) := by
      intro ν
      rw [map_sum]
      apply Finset.sum_congr rfl
      intro n hn
      obtain ⟨-, hpos, hn'⟩ := Finset.mem_filter.mp hn
      rw [map_smul, smul_eq_mul, hBasisK_mK hn' hpos]
    have hcoord : ∀ ν : YoungDiagram,
        quotientForm (-1 : k) (hBasisK ν) x = quotientForm (-1 : k) (hBasisK ν) y := by
      intro ν
      rw [hyν]
      have hpν := ν.pos_of_mem_rowLens
      rw [hBasisK_eq]
      rcases hr : ν.rowLens with _ | ⟨m, _ | ⟨b, t⟩⟩
      · simp only [hWord, List.map_nil, List.prod_nil, map_one, prim_one_zero hx]
        simp
      · have hm : 0 < m := hpν m (by simp [hr])
        simp only [List.cons.injEq, and_true, mul_ite, mul_one, mul_zero]
        rw [Finset.sum_ite_eq]
        have hw : hWord k [m] = h k m := by simp [hWord]
        rw [hw]
        split_ifs with hmN
        · rfl
        · by_cases hS : m ∈ S.support.image (fun μ : YoungDiagram => μ.card)
          · -- `m` is odd and at least `3`
            have hodd : ¬ (m = 1 ∨ Even m) := fun h' =>
              hmN (Finset.mem_filter.mpr ⟨hS, hm, h'⟩)
            push_neg at hodd
            obtain ⟨j, hj⟩ := Nat.odd_iff.mpr (Nat.not_even_iff.mp hodd.2)
            subst hj
            exact h2 _ (prim_odd hx (by omega))
          · have := hxdeg ν (by
              have hc : ν.card = m := by
                rw [← EKIntegralBases.rowLens_sum, hr]; simp
              rwa [hc])
            rwa [hBasisK_eq, hr, hw] at this
      · rw [prim_long_zero hx m (b :: t) (hpν m (by simp [hr])) (List.cons_ne_nil _ _)
          (fun a ha => hpν a (by simp [hr, ha]))]
        symm
        apply Finset.sum_eq_zero
        intro n _
        simp
    have hxy : x - y = 0 := by
      apply quotientForm_nondegenerate_left
      have hF : (quotientForm (-1 : k)).flip (x - y) = 0 := by
        apply (hBasisK (k := k)).ext
        intro ν
        rw [LinearMap.flip_apply, map_sub, hcoord ν, sub_self, LinearMap.zero_apply]
      intro z
      rw [quotientForm_symm]
      exact LinearMap.congr_fun hF z
    rw [sub_eq_zero.mp hxy]
    exact hy
  · intro hx
    induction hx using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨n, hpos, hn, rfl⟩ := hy
      exact mK_primitive hn hpos
    | zero => exact isPrimitiveK_zero
    | add y z _ _ hy hz => exact isPrimitiveK_add hy hz
    | smul c y _ hy => exact isPrimitiveK_smul c hy

/-- Proposition 3.3 over a field of characteristic `0`. -/
theorem proposition_3_3_charZero {K : Type*} [Field K] [CharZero K] (x : Lam (-1 : K)) :
    IsPrimitiveK x ↔ x ∈ Submodule.span K (primGenK K) :=
  proposition_3_3_K (fun c hc => by
    rcases mul_eq_zero.mp hc with h | h
    · exact absurd h two_ne_zero
    · exact h) x

/-- Proposition 3.3 over `ℚ`. -/
theorem proposition_3_3_rat (x : Lam (-1 : ℚ)) :
    IsPrimitiveK x ↔ x ∈ Submodule.span ℚ (primGenK ℚ) :=
  proposition_3_3_charZero x

/-! ## Proposition 3.3 fails over `𝔽₂`

Over `k = 𝔽₂` (where `q = -1 = 1`) the image of `m_3` is primitive but does not lie in the
span of `m_1, m_2, m_4, …`.  The proof follows `EKPrimitives`: `h_3 ↦ ε`, `h_j ↦ 0` (`j ≠ 0, 3`)
kills every relator of the presentation (2.11)/(2.12) in the commutative ring `𝔽₂[ε]`,
because there `2 = 0`. -/

section F2
open CompleteElementary (A)
open scoped DualNumber

/-- `𝔽₂[ε]`, `ε² = 0`. -/
abbrev D2 := DualNumber (ZMod 2)

theorem D2_add_self (z : D2) : z + z = 0 := by
  ext
  · simp only [TrivSqZeroExt.fst_add, TrivSqZeroExt.fst_zero]
    generalize z.fst = t; fin_cases t <;> rfl
  · simp only [TrivSqZeroExt.snd_add, TrivSqZeroExt.snd_zero]
    generalize z.snd = t; fin_cases t <;> rfl

/-- `h_j ↦ ε` if `j = 3`, else `0` (`j ≥ 1`). -/
def freeChar3 : A →ₐ[ℤ] D2 := FreeAlgebra.lift ℤ (fun j => if j + 1 = 3 then (ε : D2) else 0)

def cval3 (j : ℕ) : D2 := if j = 0 then 1 else if j = 3 then ε else 0

theorem freeChar3_h (j : ℕ) : freeChar3 (CompleteElementary.h j) = cval3 j := by
  cases j with
  | zero => simp [cval3]
  | succ j =>
    simp only [CompleteElementary.h, freeChar3, FreeAlgebra.lift_ι_apply, cval3]
    simp

theorem neg_one_zsmul_D2 (a : ℕ) (z : D2) : ((-1 : ℤ) ^ a) • z = z := by
  rcases neg_one_pow_eq_or ℤ a with h | h
  · rw [h, one_smul]
  · rw [h, neg_one_smul, neg_eq_iff_add_eq_zero, D2_add_self]

theorem freeChar3_relator (r : A) (hr : r ∈ EKPresentation.relSet) : freeChar3 r = 0 := by
  cases hr with
  | even a b hab =>
    rw [map_sub, map_mul, map_mul, mul_comm, sub_self]
  | odd a b hb hab =>
    simp only [map_sub, map_add, map_mul, map_zsmul, freeChar3_h, neg_one_zsmul_D2]
    rw [mul_comm (cval3 b), mul_comm (cval3 (b - 1)), D2_add_self, D2_add_self, sub_self]

theorem freeChar3_ideal (r : A) (hr : r ∈ EKPresentation.relIdeal) :
    freeChar3.toRingHom r = 0 := by
  rw [EKPresentation.relIdeal, EKPresentation.relTwoSided, TwoSidedIdeal.mem_asIdeal] at hr
  induction hr using TwoSidedIdeal.span_induction with
  | mem x hx => exact freeChar3_relator x hx
  | zero => exact map_zero _
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx => rw [map_mul, hx, zero_mul]

/-- The descended character `Φ : Λ_ℤ → 𝔽₂[ε]`. -/
def Phi3 : EKRadicalQuotient.Q →+* D2 :=
  (Ideal.Quotient.lift EKPresentation.relIdeal freeChar3.toRingHom freeChar3_ideal).comp
    EKPresentation.presentationEquiv.symm.toRingHom

theorem Phi3_pi (x : A) : Phi3 (EKRadicalQuotient.pi x) = freeChar3 x := by
  have e : EKPresentation.presentationEquiv.symm (EKRadicalQuotient.pi x) =
      EKPresentation.mk x := by
    apply EKPresentation.presentationEquiv.injective
    rw [RingEquiv.apply_symm_apply]; rfl
  simp only [Phi3, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, e]
  rfl

theorem Phi3_fst (y : EKRadicalQuotient.Q) :
    (Phi3 y).fst = ((EKRadicalQuotient.quotientCounit y : ℤ) : ZMod 2) := by
  obtain ⟨x, rfl⟩ := EKRadicalQuotient.pi_surjective y
  rw [Phi3_pi, EKRadicalQuotient.quotientCounit_pi]
  have hext : (TrivSqZeroExt.fstHom ℤ (ZMod 2) (ZMod 2)).comp freeChar3 =
      (Algebra.ofId ℤ (ZMod 2)).comp EKFreeCoproduct.counitAlg := by
    apply FreeAlgebra.hom_ext
    funext j
    simp only [Function.comp_apply, AlgHom.comp_apply, freeChar3, FreeAlgebra.lift_ι_apply,
      EKFreeCoproduct.counitAlg]
    split_ifs <;> simp
  have := congrArg (fun f : A →ₐ[ℤ] ZMod 2 => f x) hext
  simpa [EKFreeCoproduct.counit] using this

theorem Phi3_word (w : List ℕ) (hw : ∀ j ∈ w, 0 < j) :
    Phi3 ((w.map EKElementaryQuotient.h).prod) = if w = [] then 1 else if w = [3] then ε else 0 := by
  induction w with
  | nil => simp
  | cons j t ih =>
    have hj : 0 < j := hw j (by simp)
    rw [List.map_cons, List.prod_cons, map_mul, EKElementaryQuotient.h, Phi3_pi, freeChar3_h,
      ih (fun i hi => hw i (by simp [hi]))]
    unfold cval3
    by_cases ht : t = []
    · subst ht; simp [show j ≠ 0 by omega]
    · have hne : j :: t ≠ [3] := by intro e; simp at e; exact ht e.2
      simp only [ht, if_false, List.cons_ne_nil, hne, show j ≠ 0 by omega]
      split_ifs <;> simp [DualNumber.eps_mul_eps]

theorem Phi3_hPartition (μ : YoungDiagram) :
    (Phi3 (EKPartitionSpanning.hPartition μ)).snd = if μ.rowLens = [3] then 1 else 0 := by
  rw [EKPartitionSpanning.hPartition, Phi3_word _ μ.pos_of_mem_rowLens]
  split_ifs <;> simp_all

theorem pairing_hPartition_m3 (μ : YoungDiagram) :
    EKRadicalQuotient.quotientPairing (EKPartitionSpanning.hPartition μ) (EKPrimitives.mRow 3).val =
      if μ.rowLens = [3] then 1 else 0 := by
  by_cases hc : μ.card = 3
  · have := EKDualBases.h_m 3 ⟨μ, hc⟩ (EKPrimitives.rowShape 3)
    rw [EKPrimitives.mRow, show EKPartitionSpanning.hPartition μ =
      EKPartitionSpanning.hPartition (⟨μ, hc⟩ : DegreeShapes.DegreeShape 3).val from rfl, this]
    congr 1
    apply propext
    constructor
    · intro e; rw [← EKPrimitives.rowShape_rows (by norm_num : 0 < 3), ← e]
    · intro e; exact EKPrimitives.eq_rowShape (by norm_num) _ e
  · rw [EKPrimitives.pairing_degree_orth hc (EKPrimitives.hPartition_mem μ)
      (EKPrimitives.mRow 3).property, if_neg]
    intro e
    apply hc
    rw [← EKIntegralBases.rowLens_sum, e]; simp

/-- Pairing with `m_3`, reduced mod `2`, is the second component of `Φ`. -/
theorem pairing_m3_mod2 (y : EKRadicalQuotient.Q) :
    ((EKRadicalQuotient.quotientPairing y (EKPrimitives.mRow 3).val : ℤ) : ZMod 2) =
      (Phi3 y).snd := by
  let F : EKRadicalQuotient.Q →ₗ[ℤ] ZMod 2 :=
    (Algebra.linearMap ℤ (ZMod 2)).comp
      (EKRadicalQuotient.quotientPairing.flip (EKPrimitives.mRow 3).val)
  let G : EKRadicalQuotient.Q →ₗ[ℤ] ZMod 2 :=
    { toFun := fun y => (Phi3 y).snd
      map_add' := fun a b => by rw [map_add, TrivSqZeroExt.snd_add]
      map_smul' := fun c y => by rw [map_zsmul, TrivSqZeroExt.snd_smul]; rfl }
  have hFG : F = G := by
    apply EKIntegralBases.hBasis.ext
    intro μ
    simp only [F, G, LinearMap.coe_comp, Function.comp_apply, LinearMap.flip_apply,
      EKIntegralBases.hBasis_apply, pairing_hPartition_m3, LinearMap.coe_mk, AddHom.coe_mk,
      Phi3_hPartition, Algebra.linearMap_apply]
    split_ifs <;> simp
  exact LinearMap.congr_fun hFG y

theorem Phi3_snd_mul (a b : EKRadicalQuotient.Q) :
    (Phi3 (a * b)).snd = (Phi3 a).fst * (Phi3 b).snd + (Phi3 a).snd * (Phi3 b).fst := by
  rw [map_mul, TrivSqZeroExt.snd_mul]
  simp only [smul_eq_mul, MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]

/-- **Over `𝔽₂` Proposition 3.3 fails:** `m_3` is primitive in `Λ_{𝔽₂}` and does not lie in
the span of `m_1, m_2, m_4, m_6, …`. -/
theorem proposition_3_3_fails_F2 :
    IsPrimitiveK (mK (ZMod 2) 3) ∧ mK (ZMod 2) 3 ∉ Submodule.span (ZMod 2) (primGenK (ZMod 2)) := by
  constructor
  · apply (isPrimitiveK_iff _).2
    apply deriv_of_key
    intro a' b'
    rw [← map_one (psiRing (k := ZMod 2)), ← map_mul, mK, quotientForm_psiRing,
      quotientForm_psiRing, quotientForm_psiRing, quotientForm_psiRing, quotientForm_psiRing,
      pairing_m3_mod2, pairing_m3_mod2, pairing_m3_mod2, Phi3_snd_mul, Phi3_fst, Phi3_fst,
      EKRadicalQuotient.quotientPairing_right_one, EKRadicalQuotient.quotientPairing_right_one]
  · intro hmem
    set ν := (EKPrimitives.rowShape 3).val
    have hν : ν.rowLens = [3] := EKPrimitives.rowShape_rows (by norm_num)
    have hzero : ∀ z ∈ Submodule.span (ZMod 2) (primGenK (ZMod 2)),
        quotientForm (-1 : ZMod 2) (hBasisK ν) z = 0 := by
      intro z hz
      induction hz using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨n, hpos, hn, rfl⟩ := hy
        rw [hBasisK_mK hn hpos, hν, if_neg]
        intro e
        have : n = 3 := (List.singleton_inj.mp e).symm
        subst this
        rcases hn with h | h
        · omega
        · exact absurd h (by decide)
      | zero => simp
      | add y z _ _ hy hz => rw [map_add, hy, hz, add_zero]
      | smul c y _ hy => rw [map_smul, hy, smul_zero]
    have h1 := hzero _ hmem
    rw [← psiRing_hPartition, mK, quotientForm_psiRing, pairing_hPartition_m3, if_pos hν] at h1
    exact one_ne_zero (by exact_mod_cast h1)

end F2

end OddMath.Frontier.EKFinal
