import OddMath.Frontier.EKGeneralQNondeg
import OddMath.Frontier.EKGeneralQSpecial
import OddMath.Frontier.EKRskBijection
import OddMath.Frontier.EKProp310
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel

/-!
# EK §2.1 at q = 1: the radical is the commutator ideal

Source: Ellis–Khovanov, arXiv:1107.5610v2, §2.1, pp.8–9: "If `q = 1`, the inner product
`(h_β, h_α) = |βS_α|` is the number of double cosets, and it coincides with the standard inner
product on the bialgebra of symmetric functions ... In this case the ideal `I` is generated by
commutators `[hₙ, hₘ]` over all `n, m`, and the bialgebra `Λ₁` is the maximal commutative
quotient of `Λ'`. ... The bilinear form in the `q = 1` case forces commutativity but nothing
else."

Over an arbitrary commutative ring `k`:

* `classicalGram_det`: the classical Gram matrix `N_{λμ} = #{ℕ-matrices with row sums λ and
  column sums μ}` on partitions of `d` has determinant `1`, since `N = K⁰ᵀK⁰` (RSK,
  `EKRskBijection.ek_eq_4_4`) with `K⁰` the unsigned Kostka matrix, unitriangular for the
  lexicographic order (this replaces the paper's unitriangularity against `e_{λᵀ}`);
* `radical_one_iff_commutator`: `I₁` is the two-sided ideal generated by the commutators
  `xy - yx`, equivalently by the `[hₙ, hₘ]` (`commutatorIdeal_eq_span_generators`);
* `lam_one_universal`: every ring homomorphism out of `Λ'` with commuting image kills `I₁`, so
  `Λ₁ = Λ'/I₁` (commutative, `EKGeneralQSpecial.lam_one_mul_comm`) is the maximal commutative
  quotient;
* `hBasisOne`: `Λ₁` is free with basis `h_λ` (all partitions `λ`), the ring of symmetric
  functions; the induced form is nondegenerate by construction.

Not formalized: the identification with a separately defined ring of symmetric functions and
its Hall inner product (only the value `⟨h_β, h_α⟩ = #matrices` is proved,
`EKGeneralQSpecial.form_one_hWords_mat`), and the paper's unitriangularity against `e_{λᵀ}`.
-/
noncomputable section
open scoped BigOperators
namespace OddMath.Frontier.EKGeneralQ
open EKPairingMatrices DegreeShapes
open EKFreeCoproduct (W degree partWord partWord_degree)
attribute [local instance] degreeFintype Classical.propDecidable

/-! ## The classical Gram matrix is unimodular -/

/-- The classical `⟨h_λ, h_μ⟩`: `ℕ`-matrices with row sums `λ`, column sums `μ`. -/
def classicalGram (d : ℕ) : Matrix (DegreeShape d) (DegreeShape d) ℤ :=
  fun la mu => Nat.card (Mat la.val.rowLens.get mu.val.rowLens.get)

/-- Unsigned Kostka numbers `K⁰_{νμ}` on partitions of `d`. -/
def kostkaMat (d : ℕ) : Matrix (DegreeShape d) (DegreeShape d) ℤ :=
  fun nu mu => EKRskBijection.kostka0 nu.val mu.val.rowLens.get

theorem compContent_rowLens (μ : YoungDiagram) :
    EKRskBijection.compContent μ.rowLens.get = TableauDominance.shapeContent μ := by
  ext e
  rcases e with _ | i
  · rw [EKAppendixData.shapeContent_zero, EKRskBijection.compContent_above _ (Or.inr rfl)]
  · rw [EKAppendixData.shapeContent_succ]
    by_cases hi : i < μ.rowLens.length
    · rw [List.getD_eq_getElem _ _ hi]
      exact EKRskBijection.compContent_apply μ.rowLens.get ⟨i, hi⟩
    · rw [List.getD_eq_default _ _ (by omega)]
      exact EKRskBijection.compContent_above _ (Or.inl (by omega))

theorem kostkaMat_diag (d : ℕ) (μ : DegreeShape d) : kostkaMat d μ μ = 1 := by
  rw [kostkaMat, EKRskBijection.kostka0, compContent_rowLens, TableauDominance.diagonal_fiber]
  simp

theorem kostkaMat_eq_zero (d : ℕ) (nu mu : DegreeShape d)
    (h : ¬ (mu = nu ∨ EKProp310.LexLT mu.val nu.val)) : kostkaMat d nu mu = 0 := by
  rw [kostkaMat, EKRskBijection.kostka0, compContent_rowLens]
  have hdom : ¬ EKProp310.Dom mu.val nu.val := fun hd => h (by
    rcases EKProp310.lex_le_of_dom hd with h1 | h1
    · exact Or.inl (Subtype.ext h1)
    · exact Or.inr h1)
  have hne : ∃ k, TableauDominance.shapePrefix nu.val k <
      TableauDominance.contentPrefix (TableauDominance.shapeContent mu.val) k := by
    by_contra hc
    push_neg at hc
    exact hdom (fun k => by simpa using hc k)
  rw [TableauDominance.fiber_empty_of_prefix _ _ hne]
  rfl

theorem rows_injective (d : ℕ) :
    Function.Injective (fun μ : DegreeShape d => μ.val.rowLens) := by
  intro μ ν h
  apply Subtype.ext
  apply YoungDiagram.equivListRowLens.injective
  exact Subtype.ext h

theorem kostkaMat_det (d : ℕ) : (kostkaMat d).det = 1 := by
  letI : LinearOrder (DegreeShape d) :=
    LinearOrder.lift' (fun μ : DegreeShape d => μ.val.rowLens) (rows_injective d)
  have ht : (kostkaMat d).BlockTriangular OrderDual.toDual := by
    intro nu mu hlt
    change nu.val.rowLens < mu.val.rowLens at hlt
    apply kostkaMat_eq_zero
    rintro (h | h)
    · subst h; exact lt_irrefl _ hlt
    · exact lt_asymm hlt h
  rw [Matrix.det_of_lowerTriangular _ ht]
  exact Finset.prod_eq_one (fun μ _ => kostkaMat_diag d μ)

theorem sum_rowLens_get (μ : YoungDiagram) : (∑ i, μ.rowLens.get i) = μ.card := by
  rw [← List.sum_ofFn, List.ofFn_get, EKIntegralBases.rowLens_sum]

theorem sum_degreeShape_cast {m d : ℕ} (h : m = d) (f : YoungDiagram → ℤ) :
    ∑ la : DegreeShape m, f la.val = ∑ la : DegreeShape d, f la.val := by
  subst h; rfl

theorem card_mat_eq {r c : ℕ} (β : Fin r → ℕ) (α : Fin c → ℕ) :
    Nat.card (Mat β α) = Nat.card (EKRskBijection.Mat β α) :=
  Nat.card_congr (Equiv.subtypeEquivRight (fun M => by
    simp only [funext_iff, rowSum, colSum]))

theorem classicalGram_eq (d : ℕ) : classicalGram d = (kostkaMat d).transpose * kostkaMat d := by
  ext la mu
  rw [classicalGram, card_mat_eq, EKRskBijection.ek_eq_4_4, Matrix.mul_apply]
  push_cast
  rw [sum_degreeShape_cast (by rw [sum_rowLens_get, la.2])
    (fun x => (EKRskBijection.kostka0 x la.val.rowLens.get : ℤ) *
      EKRskBijection.kostka0 x mu.val.rowLens.get)]
  rfl

/-- The classical Gram matrix of the `h_λ`, `λ ⊢ d`, has determinant `1`. -/
theorem classicalGram_det (d : ℕ) : (classicalGram d).det = 1 := by
  rw [classicalGram_eq, Matrix.det_mul, Matrix.det_transpose, kostkaMat_det, one_mul]

/-! ## `(h_λ, h_μ)` at `q = 1` -/

variable {k : Type*} [CommRing k]

theorem form_one_partitions (d : ℕ) (la mu : DegreeShape d) :
    form (1 : k) (hWord k la.val.rowLens) (hWord k mu.val.rowLens) =
      ((classicalGram d la mu : ℤ) : k) := by
  rw [form_one_hWords_mat, classicalGram, Nat.card_eq_fintype_card]
  simp

/-! ## The commutator ideal -/

variable (k) in
/-- The two-sided ideal of `Λ'` generated by all commutators `xy - yx`. -/
def commutatorIdeal : TwoSidedIdeal (L k) :=
  TwoSidedIdeal.span {z | ∃ x y : L k, z = x*y - y*x}

theorem commutator_mem (x y : L k) : x*y - y*x ∈ commutatorIdeal k :=
  TwoSidedIdeal.subset_span ⟨x, y, rfl⟩

theorem smul_mem_commutatorIdeal (r : k) {z : L k} (hz : z ∈ commutatorIdeal k) :
    r • z ∈ commutatorIdeal k := by
  rw [← smul_one_mul]
  exact TwoSidedIdeal.mul_mem_left _ _ _ hz

theorem hWord_perm_sub_mem {l₁ l₂ : List ℕ} (hp : l₁.Perm l₂) :
    hWord k l₁ - hWord k l₂ ∈ commutatorIdeal k := by
  induction hp with
  | nil => simp [TwoSidedIdeal.zero_mem]
  | cons a _ ih =>
    have := TwoSidedIdeal.mul_mem_left _ (h k a) _ ih
    simpa [hWord, mul_sub] using this
  | swap a b l =>
    have := TwoSidedIdeal.mul_mem_right _ _ (hWord k l) (commutator_mem (h k b) (h k a))
    simpa [hWord, sub_mul, mul_assoc] using this
  | trans _ _ ih₁ ih₂ =>
    have := TwoSidedIdeal.add_mem _ ih₁ ih₂
    simpa using this

/-- The commutator ideal lies in the radical at `q = 1` (EK p.8). -/
theorem commutatorIdeal_le_radical {x : L k} (hx : x ∈ commutatorIdeal k) :
    x ∈ radical (1 : k) := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem z hz =>
    obtain ⟨a, b, rfl⟩ := hz
    exact commutator_mem_radical_one a b
  | zero => exact (radical (1 : k)).zero_mem
  | add a b _ _ ha hb => exact (radical (1 : k)).add_mem ha hb
  | neg a _ ha => exact (radical (1 : k)).neg_mem ha
  | left_absorb a b _ hb => exact radical_mul_left _ a hb
  | right_absorb a b _ hb => exact radical_mul_right _ hb a

/-! ## Sorting a composition into a partition -/

/-- The partition obtained by sorting the blocks of a composition. -/
def sortComp (β : Composition n) : DegreeShape n :=
  ⟨YoungDiagram.ofRowLens (β.blocks.insertionSort (· ≥ ·))
      (List.sorted_insertionSort _ _), by
    rw [EKPartitionSpanning.card_ofRowLens, (List.perm_insertionSort _ _).sum_eq, β.blocks_sum]⟩

theorem sortComp_rowLens (β : Composition n) :
    (sortComp β).val.rowLens = β.blocks.insertionSort (· ≥ ·) :=
  YoungDiagram.rowLens_ofRowLens_eq_self (hw := List.sorted_insertionSort _ _) (fun _ ha =>
    β.blocks_pos ((List.perm_insertionSort _ _).mem_iff.mp ha))

theorem hWord_sort_sub_mem (β : Composition n) :
    hWord k β.blocks - hWord k (sortComp β).val.rowLens ∈ commutatorIdeal k := by
  rw [sortComp_rowLens]
  exact hWord_perm_sub_mem (List.perm_insertionSort _ _).symm

/-! ## Each homogeneous component of a radical element lies in the commutator ideal -/

theorem vecMul_eq_zero_of_det_one {ι : Type*} [Fintype ι] [DecidableEq ι]
    (N : Matrix ι ι ℤ) (hN : N.det = 1) (a : ι → k)
    (ha : Matrix.vecMul a (N.map (Int.cast : ℤ → k)) = 0) : a = 0 := by
  have hdet : IsUnit (N.map (Int.cast : ℤ → k)).det := by
    rw [show N.map (Int.cast : ℤ → k) = (Int.castRingHom k).mapMatrix N from rfl,
      ← RingHom.map_det, hN, map_one]
    exact isUnit_one
  have := congrArg (fun v => Matrix.vecMul v (N.map (Int.cast : ℤ → k))⁻¹) ha
  simpa [Matrix.vecMul_vecMul, Matrix.mul_nonsing_inv _ hdet] using this

theorem degreeProj_mem_commutatorIdeal {x : L k} (hx : x ∈ radical (1 : k)) (d : ℕ) :
    degreeProj k d x ∈ commutatorIdeal k := by
  set v : Composition d → k := fun β => (wordBasis k).repr x (partWord β.blocks)
  set y : L k := ∑ β : Composition d, v β • hWord k (sortComp β).val.rowLens
  have hdiff : degreeProj k d x - y ∈ commutatorIdeal k := by
    rw [degreeProj_eq_sum, ← Finset.sum_sub_distrib]
    apply sum_mem
    intro β _
    rw [← smul_sub]
    exact smul_mem_commutatorIdeal _ (hWord_sort_sub_mem β)
  have hy : y ∈ radical (1 : k) := by
    have h1 : degreeProj k d x ∈ radical (1 : k) := (radical_homogeneous _ x).mp hx d
    have h2 := commutatorIdeal_le_radical hdiff
    have := (radical (1 : k)).sub_mem h1 h2
    simpa using this
  set a : DegreeShape d → k := fun la =>
    ∑ β ∈ Finset.univ.filter (fun β : Composition d => sortComp β = la), v β
  have hya : y = ∑ la : DegreeShape d, a la • hWord k la.val.rowLens := by
    simp only [y, a, Finset.sum_smul]
    rw [← Finset.sum_fiberwise (Finset.univ : Finset (Composition d)) sortComp
      (fun β => v β • hWord k (sortComp β).val.rowLens)]
    apply Finset.sum_congr rfl
    intro la _
    apply Finset.sum_congr rfl
    intro β hβ
    rw [(Finset.mem_filter.mp hβ).2]
  have ha : a = 0 := by
    apply vecMul_eq_zero_of_det_one (classicalGram d) (classicalGram_det d) a
    funext mu
    have := hy (hWord k mu.val.rowLens)
    rw [hya, map_sum, LinearMap.sum_apply] at this
    simp only [map_smul, LinearMap.smul_apply, smul_eq_mul, form_one_partitions] at this
    simpa [Matrix.vecMul, dotProduct] using this
  have hy0 : y = 0 := by rw [hya, ha]; simp
  rw [hy0, sub_zero] at hdiff
  exact hdiff

theorem sum_degreeProj (x : L k) :
    ∑ d ∈ ((wordBasis k).repr x).support.image degree, degreeProj k d x = x := by
  conv_rhs => rw [← (wordBasis k).linearCombination_repr x]
  conv_lhs => arg 2; ext d; rw [← (wordBasis k).linearCombination_repr x]
  simp only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul, degreeProj_basis,
    smul_ite, smul_zero]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro w hw
  rw [Finset.sum_ite_eq]
  rw [if_pos (Finset.mem_image_of_mem _ hw)]

/-! ## The theorem -/

/-- EK p.8, `q = 1`: the radical `I₁` of the form is exactly the two-sided ideal generated by
commutators (any commutative ring `k`). -/
theorem radical_one_iff_commutator (x : L k) :
    x ∈ radical (1 : k) ↔ x ∈ commutatorIdeal k := by
  refine ⟨fun hx => ?_, commutatorIdeal_le_radical⟩
  rw [← sum_degreeProj x]
  exact sum_mem (fun d _ => degreeProj_mem_commutatorIdeal hx d)

/-- The commutator ideal is generated by the commutators `[hₙ, hₘ]` of generators. -/
theorem commutatorIdeal_eq_span_generators :
    commutatorIdeal k = TwoSidedIdeal.span {z | ∃ n m : ℕ, z = h k n * h k m - h k m * h k n} := by
  apply le_antisymm
  · apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨x, y, rfl⟩
    set J := TwoSidedIdeal.span {z | ∃ n m : ℕ, z = h k n * h k m - h k m * h k n}
    -- x commutes with every generator modulo J, then with every y
    have hgen : ∀ (n : ℕ) (x : L k), x * h k n - h k n * x ∈ J := by
      intro n x
      induction x using basis_induction k (wordBasis k) with
      | hz => simp [TwoSidedIdeal.zero_mem]
      | ha a b ha hb =>
        have := TwoSidedIdeal.add_mem _ ha hb
        simpa [add_mul, mul_add, add_sub_add_comm] using this
      | hb w r =>
        suffices hw : wordBasis k w * h k n - h k n * wordBasis k w ∈ J by
          have := smul_mem_span_twoSided r hw
          simpa [smul_sub, smul_mul_assoc, mul_smul_comm] using this
        induction w using FreeMonoid.recOn with
        | h0 => simp [TwoSidedIdeal.zero_mem]
        | ih i w ih =>
          rw [wordBasis_mul, wordBasis_of]
          have e : h k (i+1) * wordBasis k w * h k n - h k n * (h k (i+1) * wordBasis k w) =
              h k (i+1) * (wordBasis k w * h k n - h k n * wordBasis k w) +
              (h k (i+1) * h k n - h k n * h k (i+1)) * wordBasis k w := by noncomm_ring
          rw [e]
          exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_left _ _ _ ih)
            (TwoSidedIdeal.mul_mem_right _ _ _ (TwoSidedIdeal.subset_span ⟨i+1, n, rfl⟩))
    induction y using basis_induction k (wordBasis k) with
    | hz => simp [TwoSidedIdeal.zero_mem]
    | ha a b ha hb =>
      have := TwoSidedIdeal.add_mem _ ha hb
      simpa [add_mul, mul_add, add_sub_add_comm] using this
    | hb w r =>
      suffices hw : x * wordBasis k w - wordBasis k w * x ∈ J by
        have := smul_mem_span_twoSided r hw
        simpa [smul_sub, smul_mul_assoc, mul_smul_comm] using this
      induction w using FreeMonoid.recOn with
      | h0 => simp [TwoSidedIdeal.zero_mem]
      | ih i w ih =>
        rw [wordBasis_mul, wordBasis_of]
        have e : x * (h k (i+1) * wordBasis k w) - h k (i+1) * wordBasis k w * x =
            (x * h k (i+1) - h k (i+1) * x) * wordBasis k w +
            h k (i+1) * (x * wordBasis k w - wordBasis k w * x) := by noncomm_ring
        rw [e]
        exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_right _ _ _ (hgen (i+1) x))
          (TwoSidedIdeal.mul_mem_left _ _ _ ih)
  · apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨n, m, rfl⟩
    exact commutator_mem _ _
where
  smul_mem_span_twoSided (r : k) {S : Set (L k)} {z : L k} (hz : z ∈ TwoSidedIdeal.span S) :
      r • z ∈ TwoSidedIdeal.span S := by
    rw [← smul_one_mul]
    exact TwoSidedIdeal.mul_mem_left _ _ _ hz

/-- EK p.8, `q = 1`: `Λ₁` is the maximal commutative quotient of `Λ'`: every ring homomorphism
from `Λ'` with commuting image vanishes on `I₁`. -/
theorem lam_one_universal {S : Type*} [Ring S] (f : L k →+* S)
    (hf : ∀ x y, f x * f y = f y * f x) {x : L k} (hx : x ∈ radical (1 : k)) : f x = 0 := by
  have hle : commutatorIdeal k ≤ TwoSidedIdeal.ker f := by
    apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨a, b, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker f, map_sub, map_mul, map_mul, hf, sub_self]
  exact (TwoSidedIdeal.mem_ker f).mp (hle ((radical_one_iff_commutator x).mp hx))

/-! ## `Λ₁` is free with basis `h_λ` (the classical symmetric functions) -/

theorem classicalGram_symm (d : ℕ) : (classicalGram d).transpose = classicalGram d := by
  rw [classicalGram_eq, Matrix.transpose_mul, Matrix.transpose_transpose]

variable (k) in
/-- The dual vector to `h_μ` at `q = 1`: `Σ_ν (N⁻¹)_{μν} h_ν`. -/
def dualOne (μ : YoungDiagram) : L k :=
  ∑ ν : DegreeShape μ.card, (((classicalGram μ.card)⁻¹ ⟨μ, rfl⟩ ν : ℤ) : k) •
    hWord k ν.val.rowLens

theorem form_hWord_partition_ne {la mu : YoungDiagram} (h : la.card ≠ mu.card) (q : k) :
    form q (hWord k la.rowLens) (hWord k mu.rowLens) = 0 := by
  rw [← partWord_value, ← partWord_value]
  apply form_degree_ne
  rw [partWord_degree, partWord_degree, EKIntegralBases.rowLens_sum, EKIntegralBases.rowLens_sum]
  exact h

theorem form_dualOne (la mu : YoungDiagram) :
    form (1 : k) (hWord k la.rowLens) (dualOne k mu) = if la = mu then 1 else 0 := by
  unfold dualOne
  rw [map_sum]
  simp only [map_smul, smul_eq_mul]
  by_cases hd : la.card = mu.card
  · have hunit : IsUnit (classicalGram mu.card).det := by rw [classicalGram_det]; exact isUnit_one
    have hm := congrFun (congrFun (Matrix.mul_nonsing_inv _ hunit) ⟨la, hd⟩) ⟨mu, rfl⟩
    rw [Matrix.mul_apply] at hm
    have e : ∀ ν : DegreeShape mu.card, form (1 : k) (hWord k la.rowLens) (hWord k ν.val.rowLens) =
        ((classicalGram mu.card ⟨la, hd⟩ ν : ℤ) : k) := fun ν =>
      form_one_partitions (k := k) mu.card ⟨la, hd⟩ ν
    simp only [e]
    have hm' := congrArg (Int.cast : ℤ → k) hm
    push_cast at hm'
    have hsymm : ∀ ν : DegreeShape mu.card,
        ((classicalGram mu.card)⁻¹ ν ⟨mu, rfl⟩ : ℤ) = (classicalGram mu.card)⁻¹ ⟨mu, rfl⟩ ν := by
      intro ν
      have := congrFun (congrFun (Matrix.transpose_nonsing_inv (classicalGram mu.card)) ⟨mu, rfl⟩) ν
      rw [Matrix.transpose_apply, classicalGram_symm] at this
      exact this
    simp only [hsymm] at hm'
    rw [Finset.sum_congr rfl (fun ν _ => mul_comm _ _), hm']
    by_cases h : la = mu
    · subst h; simp [Matrix.one_apply]
    · have hne : (⟨la, hd⟩ : DegreeShape mu.card) ≠ ⟨mu, rfl⟩ :=
        fun e => h (congrArg Subtype.val e)
      simp [Matrix.one_apply_ne hne, h]
  · rw [if_neg (fun e => hd (by rw [e]))]
    apply Finset.sum_eq_zero
    intro ν _
    rw [form_hWord_partition_ne (fun e => hd (e.trans ν.2)), mul_zero]

theorem hFamilyOne_linearIndependent :
    LinearIndependent k (fun μ : YoungDiagram => piQ (1 : k) (hWord k μ.rowLens)) := by
  rw [linearIndependent_iff]
  intro l hl
  ext μ
  have h := congrArg ((quotientForm (1 : k)).flip (piQ (1 : k) (dualOne k μ))) hl
  rw [Finsupp.linearCombination_apply, map_finsuppSum, map_zero] at h
  simp only [map_smul, LinearMap.flip_apply, quotientForm_pi, form_dualOne, smul_eq_mul,
    mul_ite, mul_one, mul_zero] at h
  rw [Finsupp.sum_ite_eq'] at h
  split_ifs at h with hμ
  · exact h
  · simpa using hμ

theorem wordBasis_mem_span_one (w : W) :
    piQ (1 : k) (wordBasis k w) ∈ Submodule.span k
      (Set.range (fun μ : YoungDiagram => piQ (1 : k) (hWord k μ.rowLens))) := by
  set β : Composition (degree w) := (wordEquiv (degree w)).symm ⟨w, rfl⟩
  have hw : partWord β.blocks = w :=
    congrArg Subtype.val ((wordEquiv (degree w)).apply_symm_apply ⟨w, rfl⟩)
  have hb : wordBasis k w = hWord k β.blocks := by rw [← partWord_value, hw]
  have he : piQ (1 : k) (wordBasis k w) = piQ (1 : k) (hWord k (sortComp β).val.rowLens) := by
    rw [← sub_eq_zero, ← map_sub, piQ_eq_zero_iff, hb]
    exact commutatorIdeal_le_radical (hWord_sort_sub_mem β)
  rw [he]
  exact Submodule.subset_span ⟨_, rfl⟩

theorem hFamilyOne_span :
    ⊤ ≤ Submodule.span k (Set.range (fun μ : YoungDiagram => piQ (1 : k) (hWord k μ.rowLens))) := by
  rintro z -
  obtain ⟨x, rfl⟩ := piQ_surjective (1 : k) z
  induction x using basis_induction k (wordBasis k) with
  | hz => simp
  | ha x y hx hy => rw [map_add]; exact add_mem hx hy
  | hb w r => rw [map_smul]; exact Submodule.smul_mem _ r (wordBasis_mem_span_one w)

/-- EK p.8, `q = 1`: `Λ₁` is a free `k`-module with basis `h_λ` (all partitions), i.e. the ring
of symmetric functions `k[h₁, h₂, …]` (any commutative ring `k`). -/
def hBasisOne : Basis YoungDiagram k (Lam (1 : k)) :=
  Basis.mk hFamilyOne_linearIndependent hFamilyOne_span

@[simp] theorem hBasisOne_apply (μ : YoungDiagram) :
    hBasisOne (k := k) μ = piQ (1 : k) (hWord k μ.rowLens) := Basis.mk_apply _ _ _

end OddMath.Frontier.EKGeneralQ
