import OddMath.Frontier.EKLemma311CondControls

/-!
# EK1107.5610v2 p.29, Lemma 3.11 (3.13), CONDITIONAL on (3.11) in degree d

Printed (3.13) (governs): "Lemma 3.11. The involution ψ1ψ2 acts on Schur functions as follows:
ψ1ψ2(sλ) = (−1)^{ℓ(wλ)+|λ|} sλT."

Main result: `lemma_3_11_of_identity311 d h311 λ`, for EVERY degree `d`:
  `Identity311 d → EKAutomorphisms.psi12 (s_λ) = (-1)^(ell λ + |λ|) • s_{λᵀ}`.
This is CONDITIONAL on `Identity311 d` (exact (3.11) in degree d, copied character-for-character
from EKProp310.lean into `EKLemma311CondControls`).  It is NOT the unconditional Lemma 3.11.

Objects (original existing ones): `ψ1ψ2 = EKAutomorphisms.psi12`; `s_λ = schur d λ =
KostkaModuleInversion.recover d (degreeHBasis d) λ` (the (3.6) solution, `K = signedKostka`);
`ℓ(w_λ) = EKSemiorthogonality.ell λ`, whose parity is the (2.21) sign
`(h_λ, e_{λᵀ}) = (-1)^{ℓ(w_λ)}` (`proposition_2_14_diagonal` = `EKDualBases.triangularMatrix_diag`);
`|λ| = λ.card`.

Route (EK's printed proof, with its one gapped step repaired; no Lemma 2.15 is used):
* (3.12)/(3.6) side, unconditional, DOMINANCE support: `s_λ ∈ span{h_ν : ν ⊵ λ}`, hence
  `ψ1ψ2 s_λ ∈ span{e_ν : ν ⊵ λ}`.
* Prop 3.10 side (copied `schur_sub_e_mem`, needs (3.11)): `s_λ - sgn(λ) e_{λᵀ} ∈
  span{e_μ : μ >lex λᵀ}`, hence `ψ1ψ2 s_λ - σ h_{λᵀ} ∈ span{h_μ : μ >lex λᵀ}`.
* Replacement of EK's step "H≥λ ∩ E≥λᵀ is generated by s_λᵀ" (false in the lex form at λ=(3,3)):
  coefficient extraction in the Schur basis.  NEW unconditional input: Gale–Ryser necessity for
  0/1 matrices (`gale_ryser`), giving `(h_ν, e_μ) ≠ 0 → ν ⊴ μᵀ` via the existing Prop 3.1
  `EKDualBases.proposition_3_1_M`; hence `(s_ρ, ψ1ψ2 s_λ) ≠ 0 → ρ ⊴ λᵀ`.  With (3.11),
  `(s_ρ, h_μ) = ±K_{ρμ}`, so the h-side gives `(s_ρ, ψ1ψ2 s_λ) = σ ε_ρ K_{ρ,λᵀ}` when
  `ρ ≤lex λᵀ` and forces `ρ ⊵ λᵀ`; hence only `ρ = λᵀ` survives, and the Schur expansion
  (copied `expansion`) gives `ψ1ψ2 s_λ = σ s_{λᵀ}` with `σ = sgn(λ)·wordSign(λᵀ) =
  (-1)^{ℓ(w_λ)+|λ|}` (`sign_identity`).

Copied blocks (verbatim apart from namespace/open lines), source
OddMath/Frontier/EKProp310.lean
sha256 3dfc4c9023ef6c999a8e12b1e9debf5bf3bfb55814c4de50828952b421eb0024:
  BLOCK P1 = lines 63-254, BLOCK P2 = lines 262-344, BLOCK P3 = lines 350-428.
(Lines 255-260 `schur`, `schur_defining` and 345-348 `Identity311` live in the Controls module.)
Everything after "New" is new.
-/
noncomputable section
set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 200000
open scoped BigOperators
namespace OddMath.Frontier.EKLemma311Cond
open EKRadicalQuotient EKIntegralBases DegreeShapes EKDualBases TableauDominance
open EKPartitionSpanning (hPartition ePartition)
open EKLemma311CondControls (transposeChoose schur schur_defining Identity311)
local instance (d : ℕ) : Fintype (DegreeShape d) := degreeFintype d
local instance (d : ℕ) : DecidableEq (DegreeShape d) := Classical.decEq _

/-! ### BEGIN COPIED BLOCK P1 (EKProp310.lean lines 63-254) -/
/-! ## Orders: lexicographic and dominance -/

/-- Source "lexicographic order" on partitions: row-length lists compared lexicographically. -/
def LexLT (μ ν : YoungDiagram) : Prop := μ.rowLens < ν.rowLens

/-- Dominance `μ ⊴ ν` by the existing row-prefix cell counts. -/
def Dom (μ ν : YoungDiagram) : Prop := ∀ k, shapePrefix μ k ≤ shapePrefix ν k

theorem dom_trans {a b c : YoungDiagram} (h1 : Dom a b) (h2 : Dom b c) : Dom a c :=
  fun k => (h1 k).trans (h2 k)

theorem dom_antisymm {a b : YoungDiagram} (h1 : Dom a b) (h2 : Dom b a) : a = b :=
  SignedKostkaInvertibility.shapePrefix_injective (funext fun k => le_antisymm (h1 k) (h2 k))

theorem dom_of_kostka_ne_zero {lam mu : YoungDiagram} (h : signedKostka lam mu ≠ 0) : Dom mu lam := by
  intro k
  by_contra hk
  exact h (signedKostka_zero_of_prefix lam mu ⟨k, by omega⟩)

/-- Converse of `EKSemiorthogonality.lex_first_larger`. -/
theorem lex_of_first_larger : ∀ {L M : List ℕ} (_hpos : ∀ a ∈ L, 0 < a) (j : ℕ),
    (∀ k < j, L[k]?.getD 0 = M[k]?.getD 0) → L[j]?.getD 0 < M[j]?.getD 0 →
      List.Lex (· < ·) L M
  | [], [], _, j, _, hj => by simp at hj
  | [], _ :: _, _, _, _, _ => List.Lex.nil
  | a :: L, [], hpos, j, hprev, hj => by
      exfalso
      cases j with
      | zero => simp at hj
      | succ j =>
        have h0 := hprev 0 (by omega)
        have ha := hpos a (by simp)
        simp at h0
        omega
  | a :: L, b :: M, hpos, j, hprev, hj => by
      cases j with
      | zero => exact List.Lex.rel (by simpa using hj)
      | succ j =>
        have h0 : a = b := by simpa using hprev 0 (by omega)
        subst h0
        exact List.Lex.cons (lex_of_first_larger (fun x hx => hpos x (by simp [hx])) j
          (fun k hk => by simpa using hprev (k+1) (by omega)) (by simpa using hj))

theorem shapePrefix_zero (μ : YoungDiagram) : shapePrefix μ 0 = 0 := by
  simp [shapePrefix]

theorem shapePrefix_eq_of_rowLen {μ ν : YoungDiagram} : ∀ j,
    (∀ k < j, μ.rowLen k = ν.rowLen k) → shapePrefix μ j = shapePrefix ν j
  | 0, _ => by rw [shapePrefix_zero, shapePrefix_zero]
  | j+1, h => by
    rw [SignedKostkaInvertibility.shapePrefix_succ, SignedKostkaInvertibility.shapePrefix_succ,
      shapePrefix_eq_of_rowLen j (fun k hk => h k (by omega)), h j (by omega)]

/-- D1: dominance implies lexicographic `≤`. -/
theorem lex_le_of_dom {μ ν : YoungDiagram} (h : Dom μ ν) : μ = ν ∨ LexLT μ ν := by
  by_cases he : μ = ν
  · exact Or.inl he
  right
  have hex : ∃ j, μ.rowLen j ≠ ν.rowLen j := by
    by_contra hc
    push_neg at hc
    apply he
    apply YoungDiagram.ext
    ext ⟨r, c⟩
    simp only [YoungDiagram.mem_cells, YoungDiagram.mem_iff_lt_rowLen, hc]
  classical
  let j := Nat.find hex
  have hj : μ.rowLen j ≠ ν.rowLen j := Nat.find_spec hex
  have hprev : ∀ k < j, μ.rowLen k = ν.rowLen k := fun k hk => by
    have := Nat.find_min hex hk
    simpa using this
  have hp := h (j+1)
  rw [SignedKostkaInvertibility.shapePrefix_succ, SignedKostkaInvertibility.shapePrefix_succ,
    shapePrefix_eq_of_rowLen j hprev] at hp
  have hlt : μ.rowLen j < ν.rowLen j := by omega
  show List.Lex (· < ·) μ.rowLens ν.rowLens
  apply lex_of_first_larger (μ.pos_of_mem_rowLens) j
  · intro k hk
    rw [EKSemiorthogonality.rowLens_getD, EKSemiorthogonality.rowLens_getD]
    exact hprev k hk
  · rw [EKSemiorthogonality.rowLens_getD, EKSemiorthogonality.rowLens_getD]
    exact hlt

/-- Column-prefix cell counts. -/
def colPrefix (μ : YoungDiagram) (k : ℕ) : ℕ := (μ.cells.filter (fun p => p.2 < k)).card

theorem shapePrefix_transpose (μ : YoungDiagram) (k : ℕ) :
    shapePrefix μ.transpose k = colPrefix μ k := by
  unfold shapePrefix colPrefix
  apply Finset.card_bij (fun p _ => p.swap)
  · intro p hp
    simp only [Finset.mem_filter, YoungDiagram.mem_cells] at hp ⊢
    exact ⟨YoungDiagram.mem_transpose.mp hp.1, by simpa using hp.2⟩
  · intro a _ b _ h
    simpa using h
  · intro p hp
    simp only [Finset.mem_filter, YoungDiagram.mem_cells] at hp
    refine ⟨p.swap, ?_, by simp⟩
    simp only [Finset.mem_filter, YoungDiagram.mem_cells]
    exact ⟨YoungDiagram.mem_transpose.mpr (by simpa using hp.1), by simpa using hp.2⟩

private theorem rect_card (μ : YoungDiagram) (k : ℕ) :
    (μ.cells.filter (fun p => p.1 < μ.colLen k ∧ p.2 < k)).card = μ.colLen k * k := by
  have : μ.cells.filter (fun p => p.1 < μ.colLen k ∧ p.2 < k) =
      Finset.range (μ.colLen k) ×ˢ Finset.range k := by
    ext ⟨i, j⟩
    simp only [Finset.mem_filter, YoungDiagram.mem_cells, Finset.mem_product, Finset.mem_range]
    constructor
    · rintro ⟨_, h1, h2⟩; exact ⟨h1, h2⟩
    · rintro ⟨h1, h2⟩
      refine ⟨?_, h1, h2⟩
      have hk : (i, k) ∈ μ := YoungDiagram.mem_iff_lt_colLen.mpr h1
      exact μ.up_left_mem le_rfl (Nat.le_of_lt h2) hk
  rw [this, Finset.card_product, Finset.card_range, Finset.card_range]

private theorem rect_card_le (μ : YoungDiagram) (r k : ℕ) :
    (μ.cells.filter (fun p => p.1 < r ∧ p.2 < k)).card ≤ r * k := by
  calc (μ.cells.filter (fun p => p.1 < r ∧ p.2 < k)).card
      ≤ (Finset.range r ×ˢ Finset.range k).card := by
        apply Finset.card_le_card
        intro p hp
        simp only [Finset.mem_filter] at hp
        simp [hp.2.1, hp.2.2]
    _ = r * k := by simp

/-- D2: dominance reverses under transposition (equal sizes). -/
theorem dom_transpose {μ ν : YoungDiagram} (hc : μ.card = ν.card) (h : Dom μ ν) :
    Dom ν.transpose μ.transpose := by
  intro k
  rw [shapePrefix_transpose, shapePrefix_transpose]
  set r := μ.colLen k
  -- cells of μ in columns ≥ k all lie in rows < r
  have hA : (μ.cells.filter (fun p => ¬ p.2 < k)) =
      μ.cells.filter (fun p => p.1 < r ∧ ¬ p.2 < k) := by
    apply Finset.filter_congr
    intro p hp
    simp only [YoungDiagram.mem_cells] at hp
    constructor
    · intro hk
      refine ⟨?_, hk⟩
      have : (p.1, k) ∈ μ := μ.up_left_mem le_rfl (by omega) hp
      exact YoungDiagram.mem_iff_lt_colLen.mp this
    · exact fun h => h.2
  have hsplit (τ : YoungDiagram) : shapePrefix τ r =
      (τ.cells.filter (fun p => p.1 < r ∧ ¬ p.2 < k)).card +
      (τ.cells.filter (fun p => p.1 < r ∧ p.2 < k)).card := by
    unfold shapePrefix
    rw [← Finset.filter_card_add_filter_neg_card_eq_card (fun p : ℕ × ℕ => p.2 < k),
      Finset.filter_filter, Finset.filter_filter, add_comm]
  have hμ := hsplit μ
  have hν := hsplit ν
  rw [rect_card μ k] at hμ
  have hrk : μ.colLen k * k = r * k := rfl
  have hν2 := rect_card_le ν r k
  have hsub : (ν.cells.filter (fun p => p.1 < r ∧ ¬ p.2 < k)).card ≤
      (ν.cells.filter (fun p => ¬ p.2 < k)).card := by
    apply Finset.card_le_card
    intro p hp
    simp only [Finset.mem_filter] at hp ⊢
    exact ⟨hp.1, hp.2.2⟩
  have hdom := h r
  have hμA : (μ.cells.filter (fun p => ¬ p.2 < k)).card ≤
      (ν.cells.filter (fun p => ¬ p.2 < k)).card := by
    rw [hA]; omega
  have htμ := Finset.filter_card_add_filter_neg_card_eq_card (s := μ.cells) (fun p : ℕ × ℕ => p.2 < k)
  have htν := Finset.filter_card_add_filter_neg_card_eq_card (s := ν.cells) (fun p : ℕ × ℕ => p.2 < k)
  unfold colPrefix
  change _ = μ.card at htμ
  change _ = ν.card at htν
  omega


/-! ## Degree-d algebra -/


theorem lexLT_trichotomy (a b : YoungDiagram) : LexLT a b ∨ a = b ∨ LexLT b a := by
  rcases lt_trichotomy a.rowLens b.rowLens with h | h | h
  · exact Or.inl h
  · exact Or.inr (Or.inl (YoungDiagram.equivListRowLens.injective (Subtype.ext h)))
  · exact Or.inr (Or.inr h)

@[simp] theorem transposeShape_val (d : ℕ) (lam : DegreeShape d) :
    (transposeShape d lam).val = lam.val.transpose := rfl

theorem pair_h_e_vanish (ν μ : YoungDiagram) (h : LexLT ν.transpose μ) :
    quotientPairing (hPartition ν) (ePartition μ) = 0 :=
  (EKSemiorthogonality.proposition_2_14_vanishing ν μ.rowLens μ.pos_of_mem_rowLens h).1

theorem pair_h_e_diag (ν : YoungDiagram) :
    quotientPairing (hPartition ν) (ePartition ν.transpose) = (-1 : ℤ) ^ EKSemiorthogonality.ell ν :=
  EKSemiorthogonality.proposition_2_14_diagonal ν

/-! ### END COPIED BLOCK P1; BEGIN COPIED BLOCK P2 (lines 262-344) -/

def Up (d : ℕ) (lam : DegreeShape d) : Submodule ℤ (degreePiece d) :=
  Submodule.span ℤ (degreeHBasis d '' {ν | Dom lam.val ν.val})

def UpS (d : ℕ) (lam : DegreeShape d) : Submodule ℤ (degreePiece d) :=
  Submodule.span ℤ (degreeHBasis d '' {ν | Dom lam.val ν.val ∧ ν ≠ lam})

def Above (d : ℕ) (a b : DegreeShape d) : Prop := Dom b.val a.val ∧ a ≠ b

instance (d : ℕ) : IsTrans (DegreeShape d) (Above d) :=
  ⟨fun a b c h1 h2 => ⟨dom_trans h2.1 h1.1, by
    rintro rfl
    exact h1.2 (Subtype.ext (dom_antisymm h1.1 h2.1)).symm⟩⟩

instance (d : ℕ) : IsIrrefl (DegreeShape d) (Above d) := ⟨fun _ h => h.2 rfl⟩

theorem above_wf (d : ℕ) : WellFounded (Above d) := Finite.wellFounded_of_trans_of_irrefl _

theorem up_of_upS {d : ℕ} {lam : DegreeShape d} (h : schur d lam - degreeHBasis d lam ∈ UpS d lam) :
    schur d lam ∈ Up d lam := by
  have h1 : UpS d lam ≤ Up d lam := Submodule.span_mono (Set.image_subset _ (fun ν hν => hν.1))
  have h2 : degreeHBasis d lam ∈ Up d lam := Submodule.subset_span ⟨lam, fun _ => le_rfl, rfl⟩
  have := Submodule.add_mem _ (h1 h) h2
  simpa using this

/-- (3.6) inverted: `s_λ - h_λ` lies in the span of `h_ν`, `ν` strictly dominating `λ`. -/
theorem schur_sub_mem_upS (d : ℕ) (lam : DegreeShape d) :
    schur d lam - degreeHBasis d lam ∈ UpS d lam := by
  induction lam using (above_wf d).induction with
  | _ lam ih =>
  have hdef := schur_defining d lam
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ lam), signedKostka_diag, one_smul] at hdef
  have hs : schur d lam - degreeHBasis d lam =
      -(∑ κ ∈ Finset.univ.erase lam, signedKostka κ.val lam.val • schur d κ) := by
    rw [hdef, sub_add_eq_sub_sub, sub_self, zero_sub]
  rw [hs]
  refine Submodule.neg_mem _ (Submodule.sum_mem _ fun κ hκ => ?_)
  by_cases hK : signedKostka κ.val lam.val = 0
  · rw [hK, zero_smul]; exact Submodule.zero_mem _
  have hdom : Dom lam.val κ.val := dom_of_kostka_ne_zero hK
  have hne : κ ≠ lam := Finset.ne_of_mem_erase hκ
  have hup := up_of_upS (ih κ ⟨hdom, hne⟩)
  refine Submodule.smul_mem _ _ ((Submodule.span_mono ?_) hup)
  rintro _ ⟨ν, hν, rfl⟩
  refine ⟨ν, ⟨dom_trans hdom hν, ?_⟩, rfl⟩
  rintro rfl
  exact hne (Subtype.ext (dom_antisymm hν hdom))

/-- Property (1) for `s_λ`: `(s_λ, e_μ) = 0` for `μ > λᵀ` (lex). -/
theorem pair_schur_e_vanish (d : ℕ) (lam μ : DegreeShape d) (h : LexLT lam.val.transpose μ.val) :
    quotientPairing (schur d lam : Q) (ePartition μ.val) = 0 := by
  have hle : Up d lam ≤ LinearMap.ker (pairingMap d (degreeEBasis d μ)) := by
    rw [Up, Submodule.span_le]
    rintro _ ⟨ν, hν, rfl⟩
    simp only [SetLike.mem_coe, LinearMap.mem_ker, pairingMap_apply, degreeHBasis_apply,
      degreeEBasis_apply]
    apply pair_h_e_vanish
    have ht := dom_transpose (lam.property.trans ν.property.symm) hν
    rcases lex_le_of_dom ht with he | hl
    · rw [he]; exact h
    · exact lt_trans hl h
  have := hle (up_of_upS (schur_sub_mem_upS d lam))
  simpa [pairingMap_apply] using this

/-- Source (2.21) transported to `s_λ`: `(s_λ, e_{λᵀ}) = (-1)^{ℓ(w_λ)}`. -/
theorem pair_schur_e_diag (d : ℕ) (lam : DegreeShape d) :
    quotientPairing (schur d lam : Q) (ePartition lam.val.transpose) =
      (-1 : ℤ) ^ EKSemiorthogonality.ell lam.val := by
  have hle : UpS d lam ≤ LinearMap.ker (pairingMap d (degreeEBasis d (transposeShape d lam))) := by
    rw [UpS, Submodule.span_le]
    rintro _ ⟨ν, ⟨hν, hne⟩, rfl⟩
    simp only [SetLike.mem_coe, LinearMap.mem_ker, pairingMap_apply, degreeHBasis_apply,
      degreeEBasis_apply, transposeShape_val]
    apply pair_h_e_vanish
    have ht := dom_transpose (lam.property.trans ν.property.symm) hν
    rcases lex_le_of_dom ht with he | hl
    · exact absurd (Subtype.ext (YoungDiagram.transpose_eq_iff.mp he)) hne
    · exact hl
  have h1 := hle (schur_sub_mem_upS d lam)
  simp only [LinearMap.mem_ker, pairingMap_apply, Submodule.coe_sub, map_sub,
    LinearMap.sub_apply, degreeHBasis_apply, degreeEBasis_apply, transposeShape_val] at h1
  rw [← pair_h_e_diag]
  omega

/-! ### END COPIED BLOCK P2; BEGIN COPIED BLOCK P3 (lines 350-428) -/

theorem sign_mul_self (n : ℕ) : (-1 : ℤ) ^ n * (-1 : ℤ) ^ n = 1 := by
  rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow]

theorem schur_span (d : ℕ) : Submodule.span ℤ (Set.range (schur d)) = ⊤ := by
  rw [eq_top_iff, ← (degreeHBasis d).span_eq, Submodule.span_le]
  rintro _ ⟨μ, rfl⟩
  rw [SetLike.mem_coe, schur_defining]
  exact Submodule.sum_mem _ fun κ _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨κ, rfl⟩)

theorem expansion (d : ℕ) (h311 : Identity311 d) (x : degreePiece d) :
    x = ∑ κ, ((-1 : ℤ) ^ transposeChoose κ.val * quotientPairing (schur d κ : Q) (x : Q)) •
      schur d κ := by
  have hx : x ∈ Submodule.span ℤ (Set.range (schur d)) := by rw [schur_span]; trivial
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℤ).mp hx
  have hcoef (κ : DegreeShape d) :
      (-1 : ℤ) ^ transposeChoose κ.val * quotientPairing (schur d κ : Q) (x : Q) = c κ := by
    have h' := h311
    unfold Identity311 at h'
    rw [← hc, Submodule.coe_sum, map_sum]
    simp only [Submodule.coe_smul, map_zsmul, h', smul_eq_mul, mul_ite, mul_zero]
    rw [Finset.sum_ite_eq]
    simp only [Finset.mem_univ, if_true]
    rw [mul_left_comm, sign_mul_self, mul_one]
  simp only [hcoef]
  exact hc.symm

def EAbove (d : ℕ) (κ : YoungDiagram) : Submodule ℤ (degreePiece d) :=
  Submodule.span ℤ (degreeEBasis d '' {μ | LexLT κ μ.val})

def TAbove (d : ℕ) (a b : DegreeShape d) : Prop := LexLT b.val.transpose a.val.transpose

instance (d : ℕ) : IsTrans (DegreeShape d) (TAbove d) := ⟨fun _ _ _ h1 h2 => lt_trans h2 h1⟩
instance (d : ℕ) : IsIrrefl (DegreeShape d) (TAbove d) := ⟨fun _ h => lt_irrefl _ h⟩
theorem tabove_wf (d : ℕ) : WellFounded (TAbove d) := Finite.wellFounded_of_trans_of_irrefl _

/-- The Proposition 3.10 sign `(-1)^{ℓ(w_λ) + C(λᵀ,2)}`. -/
def sgn (lam : YoungDiagram) : ℤ := (-1 : ℤ) ^ (EKSemiorthogonality.ell lam + transposeChoose lam)

theorem sgn_sq (lam : YoungDiagram) : sgn lam * sgn lam = 1 := sign_mul_self _

theorem eAbove_mono (d : ℕ) {a b : YoungDiagram} (h : LexLT a b) : EAbove d b ≤ EAbove d a :=
  Submodule.span_mono (Set.image_subset _ (fun _ hμ => lt_trans h hμ))

/-- Triangular inversion: `s_λ - sgn(λ) e_{λᵀ} ∈ span{e_μ : μ > λᵀ}`. -/
theorem schur_sub_e_mem (d : ℕ) (h311 : Identity311 d) (lam : DegreeShape d) :
    schur d lam - sgn lam.val • degreeEBasis d (transposeShape d lam) ∈
      EAbove d lam.val.transpose := by
  induction lam using (tabove_wf d).induction with
  | _ lam ih =>
  have hx := expansion d h311 (degreeEBasis d (transposeShape d lam))
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ lam)] at hx
  have hc : (-1 : ℤ) ^ transposeChoose lam.val *
      quotientPairing (schur d lam : Q) ((degreeEBasis d (transposeShape d lam)) : Q) = sgn lam.val := by
    rw [degreeEBasis_apply, transposeShape_val, pair_schur_e_diag, sgn, pow_add, mul_comm]
  rw [hc] at hx
  set rest := ∑ κ ∈ Finset.univ.erase lam, ((-1 : ℤ) ^ transposeChoose κ.val *
      quotientPairing (schur d κ : Q) ((degreeEBasis d (transposeShape d lam)) : Q)) • schur d κ
    with hrest_def
  have hrest : rest ∈ EAbove d lam.val.transpose := by
    refine Submodule.sum_mem _ fun κ hκ => ?_
    have hne : κ ≠ lam := Finset.ne_of_mem_erase hκ
    rcases lexLT_trichotomy κ.val.transpose lam.val.transpose with hl | he | hg
    · rw [degreeEBasis_apply, pair_schur_e_vanish d κ (transposeShape d lam) hl, mul_zero, zero_smul]
      exact Submodule.zero_mem _
    · exact absurd (Subtype.ext (YoungDiagram.transpose_eq_iff.mp he)) hne
    · refine Submodule.smul_mem _ _ ?_
      have h1 := eAbove_mono d hg (ih κ hg)
      have h2 : degreeEBasis d (transposeShape d κ) ∈ EAbove d lam.val.transpose :=
        Submodule.subset_span ⟨transposeShape d κ, hg, rfl⟩
      have := Submodule.add_mem _ h1 (Submodule.smul_mem _ (sgn κ.val) h2)
      rwa [sub_add_cancel] at this
  have hs : schur d lam - sgn lam.val • degreeEBasis d (transposeShape d lam) =
      -(sgn lam.val • rest) := by
    conv_lhs => rw [hx]
    rw [smul_add, smul_smul, sgn_sq, one_smul]
    abel
  rw [hs]
  exact Submodule.neg_mem _ (Submodule.smul_mem _ _ hrest)

/-! ### END COPIED BLOCK P3 -/

/-! ## New: Gale–Ryser necessity (0/1 margins force dominance) -/

open EKPairingMatrices (Mat Raw rowSum colSum)

theorem shapePrefix_eq_sum_range (μ : YoungDiagram) (k : ℕ) :
    shapePrefix μ k = ∑ j ∈ Finset.range k, μ.rowLen j := by
  induction k with
  | zero => rw [shapePrefix_zero, Finset.sum_range_zero]
  | succ k ih => rw [SignedKostkaInvertibility.shapePrefix_succ, ih, Finset.sum_range_succ]

theorem rowLen_eq_zero_of_colLen_le (μ : YoungDiagram) {j : ℕ} (hj : μ.colLen 0 ≤ j) :
    μ.rowLen j = 0 := by
  by_contra h
  have h1 : (j, 0) ∈ μ := YoungDiagram.mem_iff_lt_rowLen.mpr (Nat.pos_of_ne_zero h)
  have h2 := YoungDiagram.mem_iff_lt_colLen.mp h1
  omega

theorem sum_range_eq_fin (f : ℕ → ℕ) (c k : ℕ) (hf : ∀ j, c ≤ j → f j = 0) :
    ∑ j ∈ Finset.range k, f j = ∑ j : Fin c, if j.val < k then f j.val else 0 := by
  have h2 := Fin.sum_univ_eq_sum_range (fun j => if j < k then f j else 0) c
  simp only at h2
  rw [h2, ← Finset.sum_filter]
  have h1 : ∑ j ∈ Finset.range k, f j = ∑ j ∈ Finset.range k, if j < c then f j else 0 := by
    refine Finset.sum_congr rfl fun j _ => ?_
    split_ifs with h
    · rfl
    · exact hf j (by omega)
  rw [h1, ← Finset.sum_filter]
  congr 1
  ext j
  simp only [Finset.mem_filter, Finset.mem_range]
  omega

theorem row_bound {r c : ℕ} {β : Fin r → ℕ} {α : Fin c → ℕ} (A : Mat β α)
    (h01 : ∀ i j, A i j ≤ 1) (i : Fin r) (k : ℕ) :
    (∑ j : Fin c, if j.val < k then A i j else 0) ≤ min k (β i) := by
  apply le_min
  · calc (∑ j : Fin c, if j.val < k then A i j else 0)
          ≤ ∑ j : Fin c, if j.val < k then 1 else 0 :=
            Finset.sum_le_sum fun j _ => by split_ifs <;> simp [h01 i j]
        _ = min k c := EKSemiorthogonality.sum_initial c k
        _ ≤ k := min_le_left _ _
  · calc (∑ j : Fin c, if j.val < k then A i j else 0) ≤ ∑ j : Fin c, A i j :=
            Finset.sum_le_sum fun j _ => by split_ifs <;> simp
        _ = β i := congrFun A.property.1 i

theorem sum_min_rowLen (ν : YoungDiagram) (k : ℕ) :
    (∑ i : Fin (ν.colLen 0), min k (ν.rowLen i)) = shapePrefix ν.transpose k := by
  rw [shapePrefix_eq_sum_range, ← Fin.sum_univ_eq_sum_range]
  simp only [YoungDiagram.rowLen_transpose]
  have he (i : Fin (ν.colLen 0)) (j : Fin k) :
      (j.val < ν.rowLen i.val) ↔ i.val < ν.colLen j.val :=
    YoungDiagram.mem_iff_lt_rowLen.symm.trans YoungDiagram.mem_iff_lt_colLen
  calc (∑ i : Fin (ν.colLen 0), min k (ν.rowLen i))
      = ∑ i : Fin (ν.colLen 0), ∑ j : Fin k, if j.val < ν.rowLen i then 1 else 0 := by
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [EKSemiorthogonality.sum_initial, min_comm]
    _ = ∑ j : Fin k, ∑ i : Fin (ν.colLen 0), if i.val < ν.colLen j then 1 else 0 := by
        rw [Finset.sum_comm]
        refine Finset.sum_congr rfl fun j _ => Finset.sum_congr rfl fun i _ => ?_
        simp only [he i j]
    _ = ∑ j : Fin k, ν.colLen j := by
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [EKSemiorthogonality.sum_initial, min_eq_left (ν.colLen_anti 0 j.val (Nat.zero_le _))]

/-- Gale–Ryser necessity: a 0/1 matrix with row sums `ν` and column sums `μ` forces `μ ⊴ νᵀ`. -/
theorem gale_ryser (ν μ : YoungDiagram) (A : ZeroOneMatrices ν μ) : Dom μ ν.transpose := by
  intro k
  obtain ⟨A, h01⟩ := A
  rw [shapePrefix_eq_sum_range μ k,
    sum_range_eq_fin _ (μ.colLen 0) k (fun j hj => rowLen_eq_zero_of_colLen_le μ hj),
    ← sum_min_rowLen]
  calc (∑ j : Fin (μ.colLen 0), if j.val < k then μ.rowLen j.val else 0)
      = ∑ j : Fin (μ.colLen 0), if j.val < k then ∑ i, A i j else 0 := by
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [show (∑ i, A i j) = μ.rowLen j from congrFun A.property.2 j]
    _ = ∑ j : Fin (μ.colLen 0), ∑ i, if j.val < k then A i j else 0 := by
        refine Finset.sum_congr rfl fun j _ => ?_
        split_ifs with h <;> simp [h]
    _ = ∑ i, ∑ j : Fin (μ.colLen 0), if j.val < k then A i j else 0 := Finset.sum_comm
    _ ≤ ∑ i : Fin (ν.colLen 0), min k (ν.rowLen i) :=
        Finset.sum_le_sum fun i _ => row_bound A h01 i k

/-- Dominance vanishing of the mixed pairing, via the existing Prop 3.1 (signed 0/1 count). -/
theorem pair_h_e_dom (d : ℕ) (ν μ : DegreeShape d)
    (h : quotientPairing (hPartition ν.val) (ePartition μ.val) ≠ 0) :
    Dom ν.val μ.val.transpose := by
  rw [quotientPairing_symm] at h
  have hM : M d μ ν ≠ 0 := h
  rw [proposition_3_1_M] at hM
  by_contra hd
  apply hM
  apply Finset.sum_eq_zero
  intro A _
  exact absurd (gale_ryser μ.val ν.val A) hd

/-- Unconditional: `(s_ρ, e_μ) ≠ 0 → ρ ⊴ μᵀ`. -/
theorem pair_schur_e_dom (d : ℕ) (rho μ : DegreeShape d)
    (h : quotientPairing (schur d rho : Q) (ePartition μ.val) ≠ 0) :
    Dom rho.val μ.val.transpose := by
  by_contra hd
  apply h
  have hle : Up d rho ≤ LinearMap.ker (pairingMap d (degreeEBasis d μ)) := by
    rw [Up, Submodule.span_le]
    rintro _ ⟨ν, hν, rfl⟩
    simp only [SetLike.mem_coe, LinearMap.mem_ker, pairingMap_apply, degreeHBasis_apply,
      degreeEBasis_apply]
    by_contra hne
    exact hd (dom_trans hν (pair_h_e_dom d ν μ hne))
  have := hle (up_of_upS (schur_sub_mem_upS d rho))
  simpa [pairingMap_apply] using this

/-- With (3.11): `(s_ρ, h_μ) = ε_ρ K_{ρμ}`. -/
theorem pair_schur_h (d : ℕ) (h311 : Identity311 d) (rho μ : DegreeShape d) :
    quotientPairing (schur d rho : Q) (hPartition μ.val) =
      (-1 : ℤ) ^ transposeChoose rho.val * signedKostka rho.val μ.val := by
  have h' := h311
  unfold Identity311 at h'
  have hdef := congrArg Subtype.val (schur_defining d μ)
  rw [degreeHBasis_apply] at hdef
  rw [hdef, Submodule.coe_sum, map_sum]
  simp only [Submodule.coe_smul, map_zsmul, h' rho, smul_eq_mul, mul_ite, mul_zero]
  rw [Finset.sum_ite_eq]
  simp only [Finset.mem_univ, if_true]
  ring

/-! ## New: ψ1ψ2 transport -/

theorem psi12_degree {d : ℕ} {x : Q} (hx : x ∈ degreePiece d) :
    EKAutomorphisms.psi12 x ∈ degreePiece d := by
  rw [EKAutomorphisms.psi12_apply]
  exact EKAutomorphisms.psi1_degree (EKAutomorphisms.psi2_degree hx)

theorem psi12_hPartition (μ : YoungDiagram) :
    EKAutomorphisms.psi12 (hPartition μ) = EKAutomorphisms.wordSign μ.rowLens • ePartition μ :=
  EKAutomorphisms.psi12_hWord μ.rowLens

theorem psi12_ePartition (μ : YoungDiagram) :
    EKAutomorphisms.psi12 (ePartition μ) = EKAutomorphisms.wordSign μ.rowLens • hPartition μ :=
  EKAutomorphisms.psi12_eWord μ.rowLens

/-- E-side (unconditional): for `y ∈ span{h_ν : ν ⊵ λ}`, `(s_ρ, ψ1ψ2 y) = 0` unless `ρ ⊴ λᵀ`. -/
theorem pair_psi12_up (d : ℕ) (lam rho : DegreeShape d)
    (hd : ¬ Dom rho.val lam.val.transpose) :
    ∀ y ∈ Up d lam, quotientPairing (schur d rho : Q) (EKAutomorphisms.psi12 (y : Q)) = 0 := by
  intro y hy
  induction hy using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ν, hν, rfl⟩ := hx
    rw [degreeHBasis_apply, psi12_hPartition, map_zsmul]
    by_cases h0 : quotientPairing (schur d rho : Q) (ePartition ν.val) = 0
    · rw [h0, smul_zero]
    · exact absurd (dom_trans (pair_schur_e_dom d rho ν h0)
        (dom_transpose (lam.property.trans ν.property.symm) hν)) hd
  | zero => simp
  | add x y _ _ hx hy => rw [Submodule.coe_add, map_add, map_add, hx, hy, add_zero]
  | smul a x _ hx => rw [Submodule.coe_smul, map_zsmul, map_zsmul, hx, smul_zero]

/-- H-side (needs (3.11)): for `y ∈ span{e_μ : μ >lex λᵀ}`, `(s_ρ, ψ1ψ2 y) = 0` if `ρ ≤lex λᵀ`. -/
theorem pair_psi12_eAbove (d : ℕ) (h311 : Identity311 d) (lam rho : DegreeShape d)
    (hr : ¬ LexLT lam.val.transpose rho.val) :
    ∀ y ∈ EAbove d lam.val.transpose,
      quotientPairing (schur d rho : Q) (EKAutomorphisms.psi12 (y : Q)) = 0 := by
  intro y hy
  induction hy using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨μ, hμ, rfl⟩ := hx
    rw [degreeEBasis_apply, psi12_ePartition, map_zsmul, pair_schur_h d h311]
    by_cases hK : signedKostka rho.val μ.val = 0
    · rw [hK, mul_zero, smul_zero]
    · exfalso
      rcases lex_le_of_dom (dom_of_kostka_ne_zero hK) with he | hl
      · exact hr (by rw [← he]; exact hμ)
      · exact hr (lt_trans hμ hl)
  | zero => simp
  | add x y _ _ hx hy => rw [Submodule.coe_add, map_add, map_add, hx, hy, add_zero]
  | smul a x _ hx => rw [Submodule.coe_smul, map_zsmul, map_zsmul, hx, smul_zero]

/-! ## New: the sign -/

theorem wordSign_eq (w : List ℕ) :
    EKAutomorphisms.wordSign w = (-1 : ℤ) ^ ((w.map (fun a => a.choose 2)).sum + w.sum) := by
  induction w with
  | nil => simp [EKAutomorphisms.wordSign]
  | cons a w ih =>
    have key : (a+1).choose 2 = a.choose 2 + a := by
      rw [show (2:ℕ) = 1 + 1 from rfl, Nat.choose_succ_succ', Nat.choose_one_right]; omega
    simp only [EKAutomorphisms.wordSign, List.map_cons, List.prod_cons, List.sum_cons] at ih ⊢
    rw [ih, EKAutomorphisms.s, key, ← pow_add]
    congr 1
    omega

/-- `sgn(λ) · wordSign(λᵀ) = (-1)^{ℓ(w_λ)+|λ|}` (the printed (3.13) sign). -/
theorem sign_identity (d : ℕ) (lam : DegreeShape d) :
    sgn lam.val * EKAutomorphisms.wordSign (transposeShape d lam).val.rowLens =
      (-1 : ℤ) ^ (EKSemiorthogonality.ell lam.val + lam.val.card) := by
  have hcard : (transposeShape d lam).val.rowLens.sum = lam.val.card := by
    rw [EKIntegralBases.rowLens_sum]
    exact (transposeShape d lam).property.trans lam.property.symm
  rw [sgn, wordSign_eq, hcard, ← pow_add]
  have hexp : EKSemiorthogonality.ell lam.val + transposeChoose lam.val +
      (((transposeShape d lam).val.rowLens.map (fun a => a.choose 2)).sum + lam.val.card) =
      (EKSemiorthogonality.ell lam.val + lam.val.card) + 2 * transposeChoose lam.val := by
    unfold transposeChoose
    simp only [transposeShape_val]
    ring
  rw [hexp, pow_add, pow_mul]
  norm_num

/-! ## New: main theorem -/

/-- Coefficient extraction: `(s_ρ, ψ1ψ2 s_λ) = [ρ = λᵀ] · σ · ε_ρ`, assuming (3.11). -/
theorem pair_schur_psi12_schur (d : ℕ) (h311 : Identity311 d) (lam rho : DegreeShape d) :
    quotientPairing (schur d rho : Q) (EKAutomorphisms.psi12 (schur d lam : Q)) =
      if rho = transposeShape d lam then
        (sgn lam.val * EKAutomorphisms.wordSign (transposeShape d lam).val.rowLens) *
          (-1 : ℤ) ^ transposeChoose rho.val
      else 0 := by
  have hsplit : EKAutomorphisms.psi12 (schur d lam : Q) =
      EKAutomorphisms.psi12
        ((schur d lam - sgn lam.val • degreeEBasis d (transposeShape d lam) : degreePiece d) : Q) +
      (sgn lam.val * EKAutomorphisms.wordSign (transposeShape d lam).val.rowLens) •
        hPartition (transposeShape d lam).val := by
    rw [Submodule.coe_sub, Submodule.coe_smul, map_sub, map_zsmul, degreeEBasis_apply,
      psi12_ePartition, smul_smul]
    abel
  have hup := up_of_upS (schur_sub_mem_upS d lam)
  by_cases hlex : LexLT lam.val.transpose rho.val
  · have hnd : ¬ Dom rho.val lam.val.transpose := by
      intro hd
      rcases lex_le_of_dom hd with he | hl
      · rw [he] at hlex; exact lt_irrefl _ hlex
      · exact lt_irrefl _ (lt_trans hl hlex)
    have hne : rho ≠ transposeShape d lam := by
      rintro rfl; exact lt_irrefl _ hlex
    rw [if_neg hne]
    exact pair_psi12_up d lam rho hnd _ hup
  · by_cases heq : rho = transposeShape d lam
    · rw [if_pos heq, hsplit, map_add,
        pair_psi12_eAbove d h311 lam rho hlex _ (schur_sub_e_mem d h311 lam), zero_add,
        map_zsmul, pair_schur_h d h311, smul_eq_mul]
      subst heq
      rw [signedKostka_diag]
      ring
    · rw [if_neg heq]
      by_cases hd2 : Dom rho.val lam.val.transpose
      · rw [hsplit, map_add,
          pair_psi12_eAbove d h311 lam rho hlex _ (schur_sub_e_mem d h311 lam), zero_add,
          map_zsmul, pair_schur_h d h311, smul_eq_mul]
        have hK : signedKostka rho.val (transposeShape d lam).val = 0 := by
          by_contra hK
          exact heq (Subtype.ext (dom_antisymm hd2 (dom_of_kostka_ne_zero hK)))
        rw [hK]
        ring
      · exact pair_psi12_up d lam rho hd2 _ hup

/-- **EK Lemma 3.11, (3.13), CONDITIONAL on (3.11) in degree `d`, for every `d`.**
`Identity311 d → ψ1ψ2(s_λ) = (-1)^{ℓ(w_λ)+|λ|} s_{λᵀ}` for all `λ ⊢ d`. -/
theorem lemma_3_11_of_identity311 (d : ℕ) (h311 : Identity311 d) (lam : DegreeShape d) :
    EKAutomorphisms.psi12 (schur d lam : Q) =
      ((-1 : ℤ) ^ (EKSemiorthogonality.ell lam.val + lam.val.card)) •
        (schur d (transposeShape d lam) : Q) := by
  have hxd := psi12_degree (schur d lam).property
  have hexp := congrArg Subtype.val (expansion d h311 ⟨_, hxd⟩)
  simp only [Subtype.coe_mk] at hexp
  rw [hexp, Submodule.coe_sum]
  simp only [Submodule.coe_smul, pair_schur_psi12_schur d h311 lam]
  rw [Finset.sum_eq_single (transposeShape d lam)]
  · rw [if_pos rfl, mul_left_comm, sign_mul_self, mul_one, sign_identity]
  · intro b _ hb
    rw [if_neg hb, mul_zero, zero_smul]
  · intro h
    exact absurd (Finset.mem_univ _) h

end OddMath.Frontier.EKLemma311Cond
