import OddMath.Frontier.ZeroHecke
import Mathlib.Algebra.RingQuot
import Mathlib.Algebra.FreeAlgebra

/-! # EKL §3.2.1: the `∂̄_r` generate a copy of the 0-Hecke algebra

EKL = Ellis–Khovanov–Lauda, *The odd nilHecke algebra and its diagrammatics*,
arXiv:1111.1320v1, §3.2.1, after (3.16), p. 22. Rank `a = n+2`; products act rightmost first.

`H_0(S_a)` (`ZeroHeckeAlg`) is the `ℤ`-algebra with generators `T_1, …, T_{a-1}` and relations
`T_i² = T_i`, `T_i T_{i+1} T_i = T_{i+1} T_i T_{i+1}`, `T_i T_j = T_j T_i` (`|i-j| > 1`). By
(3.17)–(3.18) (`ZeroHecke.zeroHecke_sq`, `zeroHecke_braid`, `zeroHecke_distant`), `T_i ↦ ∂̄_i =
x_i ∂_i` defines `H_0(S_a) → ONH_a` (`zeroHeckeToONH`).

* Matsumoto (`wordProd_reduced_eq`) and `T_i² = T_i` show that `H_0(S_a)` is spanned by the
  `T_w`, `w ∈ S_a` (`span_chosen_eq_top`).
* In `ONH_a`, `∂̄_w = ± x^{A_w} ∂_w` modulo the span of the `x^B ∂_u` with `ℓ(u) < ℓ(w)`
  (`zeroHecke_lead_basis`), so by the PBW basis (2.39) the `∂̄_w` are linearly independent
  (`zeroHeckeProduct_linearIndependent`).
* Hence `H_0(S_a) → ONH_a` is injective (`zeroHeckeToONH_injective`), `H_0(S_a)` is free on the
  `T_w` (`zeroHeckeBasis`), and `H_0(S_a)` is isomorphic to the subalgebra generated by the
  `∂̄_r` (`zeroHeckeCopy`).
-/

namespace OddMath.Frontier.EKLGaps
open NilCoxeterWords
noncomputable section

theorem length_one' (n : ℕ) : length (1 : Perm n) = 0 := by
  unfold length
  exact Finset.sum_eq_zero fun a _ => Finset.sum_eq_zero fun b _ =>
    if_neg fun h => lt_asymm h.1 h.2

theorem reduced_nil {n : ℕ} : Reduced ([] : Word n) := by
  unfold Reduced
  rw [List.length_nil, permutation, length_one']

/-! ### Words in a monoid satisfying the braid relations -/

section Monoid
variable {M : Type*} [Monoid M] {n : ℕ} (T : Fin (n+1) → M)

/-- The product `T_{i_1} ⋯ T_{i_k}` along a word. -/
def wordProd : Word n → M
  | [] => 1
  | i::w => T i * wordProd w

@[simp] theorem wordProd_nil : wordProd T [] = 1 := rfl
@[simp] theorem wordProd_cons (i : Fin (n+1)) (w : Word n) :
    wordProd T (i::w) = T i * wordProd T w := rfl

theorem wordProd_append (u v : Word n) : wordProd T (u++v) = wordProd T u * wordProd T v := by
  induction u with
  | nil => simp
  | cons i u ih => simp [ih, mul_assoc]

@[simp] theorem wordProd_singleton (i : Fin (n+1)) : wordProd T [i] = T i := by simp

variable {T}
variable (hbraid : ∀ i j : Fin (n+1), j.val = i.val+1 → T i * T j * T i = T j * T i * T j)
  (hdist : ∀ i j : Fin (n+1), (i.val+1 < j.val ∨ j.val+1 < i.val) → T i * T j = T j * T i)
include hbraid hdist

private theorem join (p : Perm n) (i j : Fin (n+1)) (hi : Descent p i) (hj : Descent p j) :
    ∃ a b : Word n, permutation a = p * simple i ∧ permutation b = p * simple j ∧
      Reduced a ∧ Reduced b ∧ wordProd T a * T i = wordProd T b * T j := by
  by_cases he : i = j
  · subst j
    obtain ⟨u, hu, hl⟩ := exists_reduced (p * simple i)
    exact ⟨u, u, hu, hu, by simpa [Reduced, hu] using hl, by simpa [Reduced, hu] using hl, rfl⟩
  have adj : ∀ i j : Fin (n+1), Descent p i → Descent p j → j.val = i.val+1 →
      ∃ a b : Word n, permutation a = p * simple i ∧ permutation b = p * simple j ∧
        Reduced a ∧ Reduced b ∧ wordProd T a * T i = wordProd T b * T j := by
    intro i j hi hj h
    obtain ⟨u, hu, hul⟩ := exists_reduced (p * simple i * simple j * simple i)
    have hb : p * simple i * simple j * simple i = p * simple j * simple i * simple j := by
      simpa only [mul_assoc] using congrArg (p * ·) (simple_braid i j h)
    have hpi : permutation (u++[i,j]) = p * simple i := by
      simp [permutation_append, hu, permutation, ← mul_assoc]
    have hpj : permutation (u++[j,i]) = p * simple j := by
      rw [permutation_append, hu, hb]
      simp [permutation, ← mul_assoc]
    have hli := length_descend p i hi
    have hlj := length_descend p j hj
    have hd := descent_adjacent p i j h hi hj
    have hlq := length_descend (p * simple i) j hd.1
    have hlr := length_descend (p * simple i * simple j) i hd.2
    refine ⟨u++[i,j], u++[j,i], hpi, hpj, ?_, ?_, ?_⟩
    · unfold Reduced; rw [hpi]
      simp only [List.length_append, List.length_cons, List.length_nil]; omega
    · unfold Reduced; rw [hpj]
      simp only [List.length_append, List.length_cons, List.length_nil]; omega
    · simpa only [wordProd_append, wordProd_cons, wordProd_nil, mul_one, mul_assoc] using
        congrArg (wordProd T u * ·) (hbraid i j h)
  by_cases h₁ : j.val = i.val+1
  · exact adj i j hi hj h₁
  by_cases h₂ : i.val = j.val+1
  · obtain ⟨a, b, ha, hb, hra, hrb, hs⟩ := adj j i hj hi h₂
    exact ⟨b, a, hb, ha, hrb, hra, hs.symm⟩
  have h : i.val+1 < j.val ∨ j.val+1 < i.val := by
    have : i.val ≠ j.val := fun h => he (Fin.ext h)
    omega
  obtain ⟨u, hu, hul⟩ := exists_reduced (p * simple i * simple j)
  have hpi : permutation (u++[j]) = p * simple i := by simp [hu, mul_assoc]
  have hpj : permutation (u++[i]) = p * simple j := by
    simp only [permutation_append, permutation_singleton, hu]
    calc
      p * simple i * simple j * simple i = p * (simple i * simple j) * simple i := by
        simp [mul_assoc]
      _ = p * (simple j * simple i) * simple i := by rw [simple_distant i j h]
      _ = p * simple j := by simp [mul_assoc]
  have hli := length_descend p i hi
  have hlj := length_descend p j hj
  have hlq := length_descend (p * simple i) j ((descent_distant p i j h).mpr hj)
  refine ⟨u++[j], u++[i], hpi, hpj, ?_, ?_, ?_⟩
  · unfold Reduced; rw [hpi]; simp only [List.length_append, List.length_singleton]; omega
  · unfold Reduced; rw [hpj]; simp only [List.length_append, List.length_singleton]; omega
  · simp only [wordProd_append, wordProd_singleton, mul_assoc]
    rw [hdist j i (by omega)]

/-- Matsumoto: in a monoid satisfying the braid and distant commutation relations, the products
along two reduced words of one permutation are equal. -/
theorem wordProd_reduced_eq (w v : Word n) (hw : Reduced w) (hv : Reduced v)
    (hp : permutation w = permutation v) : wordProd T w = wordProd T v := by
  induction h : w.length using Nat.strong_induction_on generalizing w v with
  | h k ih =>
    cases w using List.reverseRecOn with
    | nil =>
        have hv0 : v.length = 0 := by simpa [Reduced, ← hp, permutation] using hv
        have : v = [] := List.length_eq_zero_iff.mp hv0
        subst v
        rfl
    | append_singleton w i =>
        cases v using List.reverseRecOn with
        | nil => simp [Reduced, hp, permutation] at hw
        | append_singleton v j =>
            obtain ⟨hwr, hwi⟩ := reduced_prefix w i hw
            obtain ⟨hvr, hvj⟩ := reduced_prefix v j hv
            let p := permutation (w++[i])
            have hpi : p * simple i = permutation w := by simp [p, mul_assoc]
            have hpj : p * simple j = permutation v := by simp [p, hp, mul_assoc]
            have hd₁ : Descent p i := by
              simpa [p] using descent_after_ascend (permutation w) i hwi
            have hd₂ : Descent p j := by
              simpa [p, hp] using descent_after_ascend (permutation v) j hvj
            obtain ⟨a, b, ha, hb, hra, hrb, hs⟩ := join hbraid hdist p i j hd₁ hd₂
            have hwa := ih w.length
              (by simp only [List.length_append, List.length_singleton] at h; omega)
              w a hwr hra (by rw [ha, hpi]) rfl
            have hvb := ih v.length (by
                have he : v.length = w.length := by
                  unfold Reduced at hw hv
                  rw [← hp] at hv
                  simp only [List.length_append, List.length_singleton] at hw hv
                  omega
                simp only [List.length_append, List.length_singleton] at h
                omega) v b hvr hrb (by rw [hb, hpj]) rfl
            simp only [wordProd_append, wordProd_singleton, hwa, hvb, hs]

/-- With `T_i² = T_i` in addition, the product along ANY word equals the product along a reduced
word (of the Demazure product). -/
theorem exists_reduced_wordProd (hsq : ∀ i, T i * T i = T i) (w : Word n) :
    ∃ v : Word n, Reduced v ∧ wordProd T w = wordProd T v := by
  induction w using List.reverseRecOn with
  | nil => exact ⟨[], reduced_nil, rfl⟩
  | append_singleton w i ih =>
    obtain ⟨v, hv, hwv⟩ := ih
    rw [wordProd_append, wordProd_singleton, hwv]
    by_cases hd : Descent (permutation v) i
    · obtain ⟨u, hu, hul⟩ := exists_reduced (permutation v * simple i)
      have hl := length_descend (permutation v) i hd
      have hperm : permutation (u++[i]) = permutation v := by
        rw [permutation_append, hu, permutation_singleton, mul_assoc, simple_square, mul_one]
      have hred : Reduced (u++[i]) := by
        unfold Reduced
        rw [hperm, List.length_append, List.length_singleton, hul, hl]
      have he := wordProd_reduced_eq hbraid hdist v (u++[i]) hv hred hperm.symm
      refine ⟨v, hv, ?_⟩
      rw [he, wordProd_append, wordProd_singleton, mul_assoc, hsq]
    · refine ⟨v++[i], ?_, by rw [wordProd_append, wordProd_singleton]⟩
      unfold Reduced
      rw [permutation_append, permutation_singleton, length_ascend _ i hd, List.length_append,
        List.length_singleton, hv]

end Monoid

/-! ### The `∂`-length filtration of `ONH_a` -/

section Filtration
open NilHeckeAction NilHeckeBasis
variable {n : ℕ}

/-- `F_L`: the span of `x^v ∂_w` with `ℓ(w) < L`. -/
def lenFilt (n L : ℕ) : Submodule ℤ (Presented n) :=
  Submodule.span ℤ {x | ∃ (v : List (Fin (n+2))) (w : Word n), w.length < L ∧
    x = dotWord v * product w}

theorem lenFilt_mono {L L' : ℕ} (h : L ≤ L') : lenFilt n L ≤ lenFilt n L' :=
  Submodule.span_mono fun _ ⟨v, w, hw, hx⟩ => ⟨v, w, by omega, hx⟩

theorem mem_lenFilt {v : List (Fin (n+2))} {w : Word n} {L : ℕ} (h : w.length < L) :
    dotWord v * product w ∈ lenFilt n L := Submodule.subset_span ⟨v, w, h, rfl⟩

theorem dot_mul_lenFilt (j : Fin (n+2)) {L : ℕ} {x : Presented n} (hx : x ∈ lenFilt n L) :
    dot n j * x ∈ lenFilt n L := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨v, w, hw, rfl⟩ := hx
      simpa only [dotWord_cons, mul_assoc] using mem_lenFilt (v := j::v) hw
  | zero => simp
  | add x y _ _ hx hy => simpa only [mul_add] using (lenFilt n L).add_mem hx hy
  | smul r x _ hx => simpa only [mul_smul_comm] using (lenFilt n L).smul_mem r hx

/-- The transposition `s_i` on dot positions. -/
def swapPos (i : Fin (n+1)) : Fin (n+2) → Fin (n+2) := Equiv.swap i.castSucc i.succ

/-- Leading term of `∂_i x^v ∂_w`: `(-1)^{|v|} x^{s_i(v)} ∂_i ∂_w`, modulo `F_{ℓ(w)+1}`. -/
theorem crossing_lead (i : Fin (n+1)) (v : List (Fin (n+2))) (w : Word n) :
    ∃ g ∈ lenFilt n (w.length + 1), crossing n i * (dotWord v * product w) =
      (-1 : ℤ)^v.length • (dotWord (v.map (swapPos i)) * product (i::w)) + g := by
  induction v with
  | nil => exact ⟨0, zero_mem _, by simp [product]⟩
  | cons j v ih =>
    obtain ⟨g, hg, hc⟩ := ih
    have hY : dotWord v * product w ∈ lenFilt n (w.length + 1) := mem_lenFilt (by omega)
    rw [dotWord_cons, mul_assoc (dot n j), ← mul_assoc (crossing n i), List.map_cons,
      dotWord_cons, List.length_cons, pow_succ]
    by_cases hl : j = i.castSucc
    · subst j
      have hs : swapPos i i.castSucc = i.succ := Equiv.swap_apply_left _ _
      refine ⟨dotWord v * product w - dot n i.succ * g,
        sub_mem hY (dot_mul_lenFilt _ hg), ?_⟩
      rw [crossing_dot_left, sub_mul, one_mul, mul_assoc, hc, hs]
      simp only [mul_add, mul_smul_comm, mul_assoc]
      module
    · by_cases hr : j = i.succ
      · subst j
        have hs : swapPos i i.succ = i.castSucc := Equiv.swap_apply_right _ _
        refine ⟨dotWord v * product w - dot n i.castSucc * g,
          sub_mem hY (dot_mul_lenFilt _ hg), ?_⟩
        rw [crossing_dot_right, sub_mul, one_mul, mul_assoc, hc, hs]
        simp only [mul_add, mul_smul_comm, mul_assoc]
        module
      · have hs : swapPos i j = j := Equiv.swap_apply_of_ne_of_ne hl hr
        refine ⟨-(dot n j * g), neg_mem (dot_mul_lenFilt _ hg), ?_⟩
        rw [crossing_dot_other i j hl hr, neg_mul, mul_assoc, hc, hs]
        simp only [mul_add, mul_smul_comm, mul_assoc]
        module

theorem crossing_mul_lenFilt (i : Fin (n+1)) {L : ℕ} {x : Presented n} (hx : x ∈ lenFilt n L) :
    crossing n i * x ∈ lenFilt n (L + 1) := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨v, w, hw, rfl⟩ := hx
      obtain ⟨g, hg, hc⟩ := crossing_lead i v w
      rw [hc]
      exact add_mem (Submodule.smul_mem _ _ (mem_lenFilt (by simp; omega)))
        (lenFilt_mono (by omega) hg)
  | zero => simp
  | add x y _ _ hx hy => simpa only [mul_add] using (lenFilt n (L+1)).add_mem hx hy
  | smul r x _ hx => simpa only [mul_smul_comm] using (lenFilt n (L+1)).smul_mem r hx

/-- Leading term of a 0-Hecke product: `∂̄_w = ± x^v ∂_w` modulo `F_{ℓ(w)}`. -/
theorem zeroHecke_lead (w : Word n) :
    ∃ (v : List (Fin (n+2))) (ε : ℤ), (ε = 1 ∨ ε = -1) ∧
      ∃ g ∈ lenFilt n w.length, ZeroHecke.zeroHeckeProduct w = ε • (dotWord v * product w) + g := by
  induction w with
  | nil => exact ⟨[], 1, Or.inl rfl, 0, zero_mem _, by simp [product]⟩
  | cons i w ih =>
    obtain ⟨v, ε, hε, g, hg, hz⟩ := ih
    obtain ⟨g', hg', hc⟩ := crossing_lead i v w
    refine ⟨i.castSucc :: v.map (swapPos i), ε * (-1 : ℤ)^v.length, ?_,
      ε • (dot n i.castSucc * g') + dot n i.castSucc * (crossing n i * g), ?_, ?_⟩
    · rcases hε with rfl | rfl <;> rcases neg_one_pow_eq_or ℤ v.length with h | h <;>
        simp [h]
    · exact add_mem (Submodule.smul_mem _ _ (dot_mul_lenFilt _ hg'))
        (dot_mul_lenFilt _ (crossing_mul_lenFilt i hg))
    · rw [ZeroHecke.zeroHeckeProduct_cons, ZeroHecke.zeroHecke, hz, mul_assoc, mul_add,
        mul_smul_comm, hc, dotWord_cons]
      simp only [mul_add, mul_smul_comm, mul_assoc, smul_add, smul_smul, List.length_cons]
      module

theorem dotWord_mul_product_basis (v : List (Fin (n+2))) (w : Word n) (hw : Reduced w) :
    ∃ ε : ℤ, (ε = 1 ∨ ε = -1) ∧
      dotWord v * product w = ε • basis n ((fun j => v.count j), permutation w) := by
  rw [dotWord_normalize, basis_apply, basisElement]
  rcases reduced_dividedElement w hw with h | h <;> rw [h]
  · refine ⟨(-1 : ℤ)^PbwNormalization.sortCrossings v, ?_, smul_mul_assoc _ _ _⟩
    exact neg_one_pow_eq_or ℤ _
  · refine ⟨-(-1 : ℤ)^PbwNormalization.sortCrossings v, ?_, ?_⟩
    · rcases neg_one_pow_eq_or ℤ (PbwNormalization.sortCrossings v) with e | e <;> simp [e]
    · rw [smul_mul_assoc, mul_neg, neg_smul, smul_neg]

/-- Elements of `F_L` have no component on `x^A ∂_u` with `ℓ(u) ≥ L`. -/
theorem repr_lenFilt {L : ℕ} {x : Presented n} (hx : x ∈ lenFilt n L) (A : Fin (n+2) → ℕ)
    (u : Perm n) (hu : L ≤ length u) : (basis n).repr x (A, u) = 0 := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨v, w, hw, rfl⟩ := hx
      by_cases hr : Reduced w
      · obtain ⟨ε, -, he⟩ := dotWord_mul_product_basis v w hr
        rw [he, map_zsmul, Basis.repr_self, Finsupp.smul_apply,
          Finsupp.single_eq_of_ne (fun e => by
            have := congrArg (fun p => length p.2) e
            simp only at this
            unfold Reduced at hr
            omega), smul_zero]
      · rw [nonreduced_zero w hr, mul_zero, map_zero, Finsupp.zero_apply]
  | zero => simp
  | add x y _ _ hx hy => simp [hx, hy]
  | smul r x _ hx => rw [map_zsmul, Finsupp.smul_apply, hx, smul_zero]

/-- `∂̄_p = ± x^A ∂_p + (terms x^B ∂_u with ℓ(u) < ℓ(p))` for the chosen reduced word of `p`. -/
theorem zeroHecke_lead_basis (p : Perm n) :
    ∃ (A : Fin (n+2) → ℕ) (ε : ℤ), (ε = 1 ∨ ε = -1) ∧
      ∃ g ∈ lenFilt n (length p),
        ZeroHecke.zeroHeckeProduct (chosenWord p) = ε • basis n (A, p) + g := by
  obtain ⟨v, ε, hε, g, hg, hz⟩ := zeroHecke_lead (chosenWord p)
  obtain ⟨η, hη, he⟩ := dotWord_mul_product_basis v (chosenWord p) (chosenWord_reduced p)
  rw [chosenWord_permutation] at he
  refine ⟨_, ε * η, ?_, g, by rwa [chosenWord_length] at hg, by rw [hz, he, smul_smul]⟩
  rcases hε with rfl | rfl <;> rcases hη with rfl | rfl <;> simp

/-- **The 0-Hecke products `∂̄_w`, `w ∈ S_a`, are linearly independent in `ONH_a`** (one reduced
word per permutation; by Matsumoto the choice does not matter). -/
theorem zeroHeckeProduct_linearIndependent (n : ℕ) :
    LinearIndependent ℤ (fun p : Perm n => ZeroHecke.zeroHeckeProduct (chosenWord p)) := by
  classical
  rw [linearIndependent_iff']
  intro s c hsum
  by_contra hne
  push_neg at hne
  obtain ⟨p1, hp1s, hp1⟩ := hne
  set s' := s.filter (fun q => c q ≠ 0)
  have hs' : s'.Nonempty := ⟨p1, Finset.mem_filter.mpr ⟨hp1s, hp1⟩⟩
  obtain ⟨p0, hp0, hmax⟩ := s'.exists_max_image length hs'
  obtain ⟨hp0s, hc0⟩ := Finset.mem_filter.mp hp0
  obtain ⟨A0, ε0, hε0, g0, hg0, hz0⟩ := zeroHecke_lead_basis p0
  have key := congrArg (fun x => (basis n).repr x (A0, p0)) hsum
  simp only [map_sum, map_zsmul, Finsupp.coe_finset_sum, Finset.sum_apply,
    Finsupp.smul_apply, map_zero, Finsupp.zero_apply] at key
  rw [Finset.sum_eq_single_of_mem p0 hp0s] at key
  · rw [hz0, map_add, map_zsmul, Basis.repr_self, Finsupp.add_apply, Finsupp.smul_apply,
      Finsupp.single_eq_same, repr_lenFilt hg0 A0 p0 le_rfl, add_zero, smul_eq_mul,
      smul_eq_mul, mul_one] at key
    rcases mul_eq_zero.mp key with h | h
    · exact hc0 h
    · rcases hε0 with rfl | rfl <;> simp at h
  · intro q hqs hq
    by_cases hcq : c q = 0
    · rw [hcq, zero_smul]
    · have hle := hmax q (Finset.mem_filter.mpr ⟨hqs, hcq⟩)
      obtain ⟨A, ε, -, g, hg, hz⟩ := zeroHecke_lead_basis q
      rw [hz, map_add, map_zsmul, Basis.repr_self, Finsupp.add_apply, Finsupp.smul_apply,
        Finsupp.single_eq_of_ne (fun e => hq (congrArg Prod.snd e)),
        repr_lenFilt hg A0 p0 hle, smul_zero, add_zero, smul_zero]

end Filtration

/-! ### The 0-Hecke algebra `H_0(S_a)` over `ℤ` -/

section Presented
variable (n : ℕ)

/-- The defining relations of the 0-Hecke algebra of `S_{n+2}`: `T_i² = T_i`, the braid relation
for adjacent indices and commutation of distant ones. -/
inductive ZHRel : FreeAlgebra ℤ (Fin (n+1)) → FreeAlgebra ℤ (Fin (n+1)) → Prop
  | sq (i : Fin (n+1)) : ZHRel (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ i) (FreeAlgebra.ι ℤ i)
  | braid (i j : Fin (n+1)) (h : j.val = i.val + 1) :
      ZHRel (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i)
        (FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j)
  | distant (i j : Fin (n+1)) (h : i.val + 1 < j.val ∨ j.val + 1 < i.val) :
      ZHRel (FreeAlgebra.ι ℤ i * FreeAlgebra.ι ℤ j) (FreeAlgebra.ι ℤ j * FreeAlgebra.ι ℤ i)

/-- The 0-Hecke algebra `H_0(S_a)` over `ℤ`, `a = n+2`, by generators and relations. -/
abbrev ZeroHeckeAlg : Type := RingQuot (ZHRel n)

variable {n}

/-- The generator `T_i`. -/
def zhGen (i : Fin (n+1)) : ZeroHeckeAlg n := RingQuot.mkAlgHom ℤ (ZHRel n) (FreeAlgebra.ι ℤ i)

theorem zhGen_sq (i : Fin (n+1)) : zhGen i * zhGen i = zhGen i := by
  simpa [zhGen] using RingQuot.mkAlgHom_rel ℤ (ZHRel.sq i)

theorem zhGen_braid (i j : Fin (n+1)) (h : j.val = i.val + 1) :
    zhGen i * zhGen j * zhGen i = zhGen j * zhGen i * zhGen j := by
  simpa [zhGen] using RingQuot.mkAlgHom_rel ℤ (ZHRel.braid i j h)

theorem zhGen_distant (i j : Fin (n+1)) (h : i.val + 1 < j.val ∨ j.val + 1 < i.val) :
    zhGen i * zhGen j = zhGen j * zhGen i := by
  simpa [zhGen] using RingQuot.mkAlgHom_rel ℤ (ZHRel.distant i j h)

variable (n) in
/-- `T_i ↦ ∂̄_i = x_i ∂_i`: the ring map `H_0(S_a) → ONH_a` of EKL §3.2.1. -/
def zeroHeckeToONH : ZeroHeckeAlg n →ₐ[ℤ] NilHeckeAction.Presented n :=
  RingQuot.liftAlgHom ℤ ⟨FreeAlgebra.lift ℤ (ZeroHecke.zeroHecke n), fun x y h => by
    cases h with
    | sq i => simpa using ZeroHecke.zeroHecke_sq i
    | braid i j h => simpa using ZeroHecke.zeroHecke_braid i j h
    | distant i j h => simpa using ZeroHecke.zeroHecke_distant i j h⟩

@[simp] theorem zeroHeckeToONH_gen (i : Fin (n+1)) :
    zeroHeckeToONH n (zhGen i) = ZeroHecke.zeroHecke n i := by
  simp [zeroHeckeToONH, zhGen]

theorem zeroHeckeToONH_wordProd (w : Word n) :
    zeroHeckeToONH n (wordProd zhGen w) = ZeroHecke.zeroHeckeProduct w := by
  induction w with
  | nil => simp
  | cons i w ih => simp [ih]

/-- The span of all words in the `T_i`. -/
def wordSpan (n : ℕ) : Submodule ℤ (ZeroHeckeAlg n) :=
  Submodule.span ℤ (Set.range (wordProd (zhGen (n := n))))

theorem gen_mul_wordSpan (i : Fin (n+1)) {x : ZeroHeckeAlg n} (hx : x ∈ wordSpan n) :
    zhGen i * x ∈ wordSpan n := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨w, rfl⟩ := hx
      exact Submodule.subset_span ⟨i::w, rfl⟩
  | zero => simp
  | add x y _ _ hx hy => simpa only [mul_add] using (wordSpan n).add_mem hx hy
  | smul r x _ hx => simpa only [mul_smul_comm] using (wordSpan n).smul_mem r hx

theorem mem_wordSpan (x : ZeroHeckeAlg n) : x ∈ wordSpan n := by
  have key : ∀ (a : FreeAlgebra ℤ (Fin (n+1))) (x : ZeroHeckeAlg n), x ∈ wordSpan n →
      RingQuot.mkAlgHom ℤ (ZHRel n) a * x ∈ wordSpan n := by
    intro a
    induction a using FreeAlgebra.induction with
    | grade0 r =>
        intro x hx
        rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
        exact (wordSpan n).smul_mem r hx
    | grade1 i => intro x hx; exact gen_mul_wordSpan i hx
    | add a b ha hb =>
        intro x hx; rw [map_add, add_mul]; exact add_mem (ha x hx) (hb x hx)
    | mul a b ha hb =>
        intro x hx; rw [map_mul, mul_assoc]; exact ha _ (hb x hx)
  obtain ⟨a, rfl⟩ := RingQuot.mkAlgHom_surjective ℤ (ZHRel n) x
  simpa using key a 1 (Submodule.subset_span ⟨[], rfl⟩)

/-- Every word in the `T_i` equals `T_{w}` along the chosen reduced word of some permutation. -/
theorem exists_chosen (w : Word n) : ∃ p : Perm n, wordProd zhGen w = wordProd zhGen (chosenWord p) := by
  obtain ⟨v, hv, he⟩ := exists_reduced_wordProd zhGen_braid zhGen_distant zhGen_sq w
  exact ⟨permutation v, he.trans (wordProd_reduced_eq zhGen_braid zhGen_distant v _ hv
    (chosenWord_reduced _) (chosenWord_permutation _).symm)⟩

/-- `H_0(S_a)` is spanned by the `T_w`, `w ∈ S_a`. -/
theorem span_chosen_eq_top (n : ℕ) :
    Submodule.span ℤ (Set.range fun p : Perm n => wordProd zhGen (chosenWord p)) = ⊤ := by
  refine top_unique fun x _ => ?_
  have hle : wordSpan n ≤ Submodule.span ℤ (Set.range fun p : Perm n =>
      wordProd zhGen (chosenWord p)) := by
    apply Submodule.span_le.mpr
    rintro _ ⟨w, rfl⟩
    obtain ⟨p, hp⟩ := exists_chosen w
    exact Submodule.subset_span ⟨p, hp.symm⟩
  exact hle (mem_wordSpan x)

/-- **EKL §3.2.1: the `∂̄_r` generate a copy of the 0-Hecke algebra.** The map
`H_0(S_a) → ONH_a`, `T_i ↦ ∂̄_i`, is injective, for every `a = n+2 ≥ 2`. -/
theorem zeroHeckeToONH_injective (n : ℕ) : Function.Injective (zeroHeckeToONH n) := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  have hmem : x ∈ Submodule.span ℤ (Set.range fun p : Perm n => wordProd zhGen (chosenWord p)) := by
    rw [span_chosen_eq_top]; exact Submodule.mem_top
  obtain ⟨c, rfl⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp hmem
  have h0 : c.sum (fun p a => a • ZeroHecke.zeroHeckeProduct (chosenWord p)) = 0 := by
    rw [← hx, map_finsuppSum]
    simp [zeroHeckeToONH_wordProd]
  have hc : c = 0 := by
    have := (zeroHeckeProduct_linearIndependent n).finsuppLinearCombination_injective
      (show Finsupp.linearCombination ℤ _ c = Finsupp.linearCombination ℤ _ 0 by
        rw [Finsupp.linearCombination_apply, map_zero]; exact h0)
    exact this
  simp [hc]

/-- `H_0(S_a)` is free over `ℤ` with basis `T_w`, `w ∈ S_a`. -/
def zeroHeckeBasis (n : ℕ) : Basis (Perm n) ℤ (ZeroHeckeAlg n) :=
  Basis.mk (LinearIndependent.of_comp (zeroHeckeToONH n).toLinearMap (by
      simpa [Function.comp_def, zeroHeckeToONH_wordProd] using
        zeroHeckeProduct_linearIndependent n))
    (span_chosen_eq_top n).ge

/-- The subalgebra of `ONH_a` generated by the `∂̄_r` is isomorphic to `H_0(S_a)`. -/
def zeroHeckeCopy (n : ℕ) :
    ZeroHeckeAlg n ≃ₐ[ℤ] Algebra.adjoin ℤ (Set.range (ZeroHecke.zeroHecke n)) :=
  (AlgEquiv.ofInjective (zeroHeckeToONH n) (zeroHeckeToONH_injective n)).trans
    (Subalgebra.equivOfEq _ _ (by
      rw [Algebra.adjoin_range_eq_range_freeAlgebra_lift]
      have h1 : (zeroHeckeToONH n).comp (RingQuot.mkAlgHom ℤ (ZHRel n)) =
          FreeAlgebra.lift ℤ (ZeroHecke.zeroHecke n) := by
        apply FreeAlgebra.hom_ext
        funext i
        simp only [Function.comp_apply, AlgHom.comp_apply, FreeAlgebra.lift_ι_apply]
        exact zeroHeckeToONH_gen i
      rw [← h1, AlgHom.range_comp, (AlgHom.range_eq_top _).mpr
        (RingQuot.mkAlgHom_surjective ℤ (ZHRel n)), Algebra.map_top]))

end Presented

end
end OddMath.Frontier.EKLGaps
