import OddMath.Frontier.EKLSectionTwo
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.Algebra.Module.Equiv.Opposite

/-! # Bases of `OΛ_a` and Noetherianity of `OPol_a`

EKL arXiv:1111.1320v1.

* p. 44, "The products `ε_λ = ε_{λ_1} ⋯ ε_{λ_r}` form a basis of `OΛ_a` just like the `h_λ`'s".
  The first half holds for `λ_1 ≤ a` (`elementary_basis`, from `ElementaryBasis.gradedBasis`).
  The comparison with the `h_λ` fails if `λ` runs over all partitions, as for the basis of `OΛ`:
  in `OΛ_2`, `h_3 = h_1³` (`complete_three_rank_two`), so the `h_λ`, `λ ⊢ 3`, are linearly
  dependent (`complete_parts_not_linearIndependent`, `complete_parts_not_basis`). With the index
  set of the `ε_λ`, or with at most `a` parts, the `h_λ` do form a basis in the smallest case
  where this restricts the index set, `a = 2` in degree `3` (`complete_basis_rank_two`).
* p. 4, "`OPol_a` is left and right Noetherian" (`left_noetherian`, `right_noetherian`), for the
  model `SkewPolynomial N` of `OPol_N`: the squares `x_i²` are central (`squares_central`) and
  span a copy of `ℤ[y_1, …, y_N]` over which `OPol_N` is generated by the `2^N` monomials `x^ε`,
  `ε ∈ {0,1}^N` (`squares_span`). -/

namespace OddMath.Frontier.EKLMisc
open scoped BigOperators

/-! ## p. 44: `ε_λ` and `h_λ` in `OΛ_a` -/

section Bases
open OddMath.SkewPolynomial (SkewPolynomial monomial)
open FiniteCompleteElementary ElementaryGeneration ElementaryBasis

/-- EKL p. 44, first half: the products `ε_λ = ε_{λ_1} ⋯ ε_{λ_r}` with `λ_1 ≤ a` form a `ℤ`-basis of
each degree piece of `OΛ_a`, `a = n+2` (EKL Prop 2.2; `ElementaryBasis.gradedBasis`). The index
`r ∈ Index a d` is a partition of `d` with at most `a` rows; the factors are its column heights. -/
theorem elementary_basis (n d : ℕ) :
    ∃ b : Basis (Index (n+2) d) ℤ (degreePiece n d), ∀ r,
      (b r : SkewPolynomial (n+2)) = elementaryWord (n+2) (columns r.1) ∧
        (columns r.1).sum = d ∧ ∀ k ∈ columns r.1, 1 ≤ k ∧ k ≤ n+2 :=
  ⟨gradedBasis n d, fun r => ⟨gradedBasis_apply n d r, (columns_sum r.1 r.2.1).trans r.2.2,
    columns_valid r.1⟩⟩

/-- `h_λ = h_{λ_1} h_{λ_2} ⋯` for a partition `λ`, parts in decreasing order. -/
noncomputable def completePart (N : ℕ) {d : ℕ} (l : Nat.Partition d) : SkewPolynomial N :=
  ((l.parts.sort (· ≥ ·)).map (completePoly N)).prod

/-- In `OΛ_2`: `h_3 = h_1³`. -/
theorem complete_three_rank_two :
    completePoly 2 3 = completePoly 2 1 * completePoly 2 1 * completePoly 2 1 := by
  rw [EKLSectionTwo.complete_three, EKLSectionTwo.complete_one,
    elementaryPoly_eq_zero_of_lt (by norm_num : 2 < 3), add_zero]

/-- The partition `(3)` of `3`. -/
def partThree : Nat.Partition 3 := ⟨{3}, by simp, rfl⟩

/-- The partition `(1,1,1)` of `3`. -/
def partOneOneOne : Nat.Partition 3 := ⟨{1, 1, 1}, by simp, rfl⟩

/-- EKL p. 44, "the products `ε_λ` form a basis of `OΛ_a` just like the `h_λ`'s": the `h_λ` over all
partitions `λ` (the basis of `OΛ`) are not linearly independent in `OΛ_a`. For `a = 2`, `h_{(3)}`
and `h_{(1,1,1)}` coincide. -/
theorem complete_parts_not_linearIndependent :
    ¬ LinearIndependent ℤ (fun l : Nat.Partition 3 => completePart 2 l) := by
  intro h
  have hne : partThree ≠ partOneOneOne := by
    intro e
    have := congrArg (fun l : Nat.Partition 3 => Multiset.card l.parts) e
    simp [partThree, partOneOneOne] at this
  apply hne
  apply h.injective
  have e1 : partThree.parts.sort (· ≥ ·) = [3] := Multiset.sort_singleton _ _
  have e2 : partOneOneOne.parts.sort (· ≥ ·) = [1, 1, 1] := by
    show Multiset.sort _ (1 ::ₘ 1 ::ₘ {1}) = _
    rw [Multiset.sort_cons _ _ _ (by simp), Multiset.sort_cons _ _ _ (by simp),
      Multiset.sort_singleton]
  simp only [completePart, e1, e2, List.map_cons, List.map_nil, List.prod_cons, List.prod_nil,
    mul_one]
  rw [complete_three_rank_two, mul_assoc]

/-- Hence no basis of the degree-3 piece of `OΛ_2` consists of the `h_λ`, `λ ⊢ 3`. -/
theorem complete_parts_not_basis :
    ¬ ∃ b : Basis (Nat.Partition 3) ℤ (degreePiece 0 3),
      ∀ l, (b l : SkewPolynomial 2) = completePart 2 l := by
  rintro ⟨b, hb⟩
  apply complete_parts_not_linearIndependent
  have := b.linearIndependent.map' (degreePiece 0 3).subtype (Submodule.ker_subtype _)
  convert this using 1
  funext l
  exact (hb l).symm

/-- The rows `(3,0)`: `ε_{(1,1,1)}` in `gradedBasis 0 3`. -/
def rowsThreeZero : Index 2 3 :=
  ⟨![3, 0], fun i j h => by fin_cases i <;> fin_cases j <;> simp_all, by decide⟩

/-- The rows `(2,1)`: `ε_{(2,1)}` in `gradedBasis 0 3`. -/
def rowsTwoOne : Index 2 3 :=
  ⟨![2, 1], fun i j h => by fin_cases i <;> fin_cases j <;> simp_all, by decide⟩

theorem index_two_three (r : Index 2 3) : r = rowsThreeZero ∨ r = rowsTwoOne := by
  obtain ⟨a, ha, hw⟩ := r
  have h10 : a 1 ≤ a 0 := ha (by decide : (0 : Fin 2) ≤ 1)
  simp only [weight, Fin.sum_univ_two] at hw
  rcases (by omega : a 1 = 0 ∨ a 1 = 1) with h | h
  · left
    refine Subtype.ext (funext fun i => ?_)
    fin_cases i <;> simp [rowsThreeZero] <;> omega
  · right
    refine Subtype.ext (funext fun i => ?_)
    fin_cases i <;> simp [rowsTwoOne] <;> omega

theorem gradedBasis_threeZero :
    (gradedBasis 0 3 rowsThreeZero : SkewPolynomial 2) =
      elementaryPoly 2 1 * elementaryPoly 2 1 * elementaryPoly 2 1 := by
  rw [gradedBasis_apply, show columns rowsThreeZero.1 = [1, 1, 1] by decide]
  simp [elementaryWord, mul_assoc]

theorem gradedBasis_twoOne :
    (gradedBasis 0 3 rowsTwoOne : SkewPolynomial 2) = elementaryPoly 2 2 * elementaryPoly 2 1 := by
  rw [gradedBasis_apply, show columns rowsTwoOne.1 = [2, 1] by decide]
  simp [elementaryWord]

theorem rowsThreeZero_ne_rowsTwoOne : rowsThreeZero ≠ rowsTwoOne := by
  intro h
  have := congrArg (fun r : Index 2 3 => r.1 1) h
  simp [rowsThreeZero, rowsTwoOne] at this

/-- `h_{(2,1)} = ε_{(1,1,1)} + ε_{(2,1)}` and `h_{(1,1,1)} = ε_{(1,1,1)}` in `OΛ_2`. -/
noncomputable def completeFamily : Fin 2 → degreePiece 0 3 :=
  ![gradedBasis 0 3 rowsThreeZero + gradedBasis 0 3 rowsTwoOne, gradedBasis 0 3 rowsThreeZero]

theorem completeFamily_zero :
    completeFamily 0 = gradedBasis 0 3 rowsThreeZero + gradedBasis 0 3 rowsTwoOne := rfl

theorem completeFamily_one : completeFamily 1 = gradedBasis 0 3 rowsThreeZero := rfl

theorem completeFamily_linearIndependent : LinearIndependent ℤ completeFamily := by
  refine LinearIndependent.pair_iff.mpr fun s t hst => ?_
  have hne := rowsThreeZero_ne_rowsTwoOne
  have h1 := congrArg (fun x => (gradedBasis 0 3).repr x rowsThreeZero) hst
  have h2 := congrArg (fun x => (gradedBasis 0 3).repr x rowsTwoOne) hst
  simp only [map_add, map_smul, Basis.repr_self, Finsupp.add_apply, Finsupp.smul_apply,
    Finsupp.single_apply, if_pos, hne, hne.symm, if_false, map_zero, Finsupp.coe_zero,
    Pi.zero_apply, smul_eq_mul, mul_one, mul_zero, add_zero, zero_add] at h1 h2
  omega

theorem completeFamily_span : ⊤ ≤ Submodule.span ℤ (Set.range completeFamily) := by
  rw [← (gradedBasis 0 3).span_eq, Submodule.span_le]
  rintro _ ⟨r, rfl⟩
  have h0 : completeFamily 0 ∈ Submodule.span ℤ (Set.range completeFamily) :=
    Submodule.subset_span ⟨0, rfl⟩
  have h1 : completeFamily 1 ∈ Submodule.span ℤ (Set.range completeFamily) :=
    Submodule.subset_span ⟨1, rfl⟩
  rcases index_two_three r with rfl | rfl
  · exact h1
  · have := Submodule.sub_mem _ h0 h1
    rwa [completeFamily_zero, completeFamily_one, add_sub_cancel_left] at this

/-- In contrast, the `h_λ` with `λ_1 ≤ a`, and the `h_λ` with at most `a` parts, do form a basis
in the smallest case where not all partitions qualify: `a = 2`, degree `3`. The degree-3 piece of
`OΛ_2` has the `ℤ`-basis `h_{(2,1)}, h_{(1,1,1)}`, and `h_{(1,1,1)} = h_{(3)}`. -/
theorem complete_basis_rank_two :
    ∃ b : Basis (Fin 2) ℤ (degreePiece 0 3),
      (b 0 : SkewPolynomial 2) = completePoly 2 2 * completePoly 2 1 ∧
      (b 1 : SkewPolynomial 2) = completePoly 2 1 * completePoly 2 1 * completePoly 2 1 ∧
      (b 1 : SkewPolynomial 2) = completePoly 2 3 := by
  have e1 : ((completeFamily 1 : degreePiece 0 3) : SkewPolynomial 2) =
      completePoly 2 1 * completePoly 2 1 * completePoly 2 1 := by
    rw [completeFamily_one, gradedBasis_threeZero, EKLSectionTwo.complete_one]
  refine ⟨Basis.mk completeFamily_linearIndependent completeFamily_span, ?_, ?_, ?_⟩
  · rw [Basis.mk_apply, completeFamily_zero, Submodule.coe_add,
      gradedBasis_threeZero, gradedBasis_twoOne, EKLSectionTwo.complete_two,
      EKLSectionTwo.complete_one, add_mul]
  · rw [Basis.mk_apply, e1]
  · rw [Basis.mk_apply, e1, complete_three_rank_two]

end Bases

/-! ## p. 4: `OPol_a` is left and right Noetherian -/

section Noetherian
open OddMath.SkewPolynomial (SkewPolynomial monomial)

variable (N : ℕ)

private theorem crossingCount_double_left (m b : Fin N → ℕ) :
    OddMath.crossingCount (fun i => 2 * m i) b = 2 * OddMath.crossingCount m b := by
  simp only [OddMath.crossingCount, Finset.mul_sum, mul_assoc]

private theorem crossingCount_double_right (m b : Fin N → ℕ) :
    OddMath.crossingCount b (fun i => 2 * m i) = 2 * OddMath.crossingCount b m := by
  simp only [OddMath.crossingCount, Finset.mul_sum]
  refine Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring

private theorem skewSign_double_left (m b : Fin N → ℕ) :
    OddMath.skewSign (fun i => 2 * m i) b = 1 := by
  rw [OddMath.skewSign, crossingCount_double_left, pow_mul]; norm_num

private theorem skewSign_double_right (m b : Fin N → ℕ) :
    OddMath.skewSign b (fun i => 2 * m i) = 1 := by
  rw [OddMath.skewSign, crossingCount_double_right, pow_mul]; norm_num

private theorem monomial_mul_monomial (a b : Fin N → ℕ) (r s : ℤ) :
    monomial a r * monomial b s = monomial (a + b) (r * s * OddMath.skewSign a b) :=
  OddMath.SkewPolynomial.mul_monomial a b r s

/-- `x^{2m}`: a monomial in the squares `x_i²`. -/
noncomputable def squareMonomial : Multiplicative ((Fin N) →₀ ℕ) →* SkewPolynomial N where
  toFun m := monomial (fun i => 2 * Multiplicative.toAdd m i) 1
  map_one' := rfl
  map_mul' m m' := by
    rw [monomial_mul_monomial, skewSign_double_left, toAdd_mul]
    congr 1
    funext i
    simp [Nat.mul_add]

/-- `ℤ[y_1, …, y_N] → OPol_N`, `y_i ↦ x_i²`. -/
noncomputable def squares : MvPolynomial (Fin N) ℤ →ₐ[ℤ] SkewPolynomial N :=
  AddMonoidAlgebra.lift ℤ ((Fin N) →₀ ℕ) (SkewPolynomial N) (squareMonomial N)

theorem squares_monomial (m : (Fin N) →₀ ℕ) (c : ℤ) :
    squares N (MvPolynomial.monomial m c) = monomial (fun i => 2 * m i) c := by
  show AddMonoidAlgebra.lift ℤ ((Fin N) →₀ ℕ) (SkewPolynomial N) (squareMonomial N)
    (Finsupp.single m c) = _
  rw [AddMonoidAlgebra.lift_single]
  show c • monomial _ 1 = _
  rw [Finsupp.smul_single, smul_eq_mul, mul_one]
  rfl

/-- The squares `x_i²` are central in `OPol_N`. -/
theorem squares_central (p : MvPolynomial (Fin N) ℤ) (x : SkewPolynomial N) :
    squares N p * x = x * squares N p := by
  induction p using MvPolynomial.induction_on' with
  | monomial m c =>
    rw [squares_monomial]
    induction x using Finsupp.induction_linear with
    | zero => rw [mul_zero, zero_mul]
    | add f g hf hg => rw [mul_add, add_mul, hf, hg]
    | single b s =>
      show monomial _ c * monomial b s = monomial b s * monomial _ c
      rw [monomial_mul_monomial, monomial_mul_monomial, skewSign_double_left,
        skewSign_double_right, add_comm, mul_comm c s]
  | add p q hp hq => rw [map_add, add_mul, mul_add, hp, hq]

/-- `OPol_N` as an algebra over `ℤ[y_1, …, y_N]` through `squares`. -/
noncomputable def squaresAlgebra : Algebra (MvPolynomial (Fin N) ℤ) (SkewPolynomial N) :=
  (squares N).toRingHom.toAlgebra' fun p x => squares_central N p x

attribute [local instance] squaresAlgebra

theorem squares_smul (p : MvPolynomial (Fin N) ℤ) (x : SkewPolynomial N) :
    p • x = squares N p * x := rfl

/-- `OPol_N` is generated over `ℤ[x_1², …, x_N²]` by the `2^N` monomials `x^ε`, `ε ∈ {0,1}^N`. -/
theorem squares_span :
    Submodule.span (MvPolynomial (Fin N) ℤ)
      (Set.range fun ε : Fin N → Fin 2 => monomial (fun i => (ε i : ℕ)) (1 : ℤ)) = ⊤ := by
  refine Submodule.eq_top_iff'.mpr fun x => ?_
  induction x using Finsupp.induction_linear with
  | zero => exact Submodule.zero_mem _
  | add f g hf hg => exact Submodule.add_mem _ hf hg
  | single a c =>
    let m : (Fin N) →₀ ℕ := Finsupp.equivFunOnFinite.symm fun i => a i / 2
    let ε : Fin N → Fin 2 := fun i => ⟨a i % 2, Nat.mod_lt _ (by norm_num)⟩
    have e : Finsupp.single a c =
        MvPolynomial.monomial m c • monomial (fun i => (ε i : ℕ)) (1 : ℤ) := by
      rw [squares_smul, squares_monomial, monomial_mul_monomial, skewSign_double_left, mul_one,
        mul_one]
      congr 1
      funext i
      simp only [Pi.add_apply, m, ε, Finsupp.equivFunOnFinite_symm_apply_toFun]
      omega
    rw [e]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨ε, rfl⟩)

theorem squares_finite : Module.Finite (MvPolynomial (Fin N) ℤ) (SkewPolynomial N) :=
  ⟨⟨Finset.univ.image fun ε : Fin N → Fin 2 => monomial (fun i => (ε i : ℕ)) (1 : ℤ), by
    rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]; exact squares_span N⟩⟩

attribute [local instance] squares_finite

/-- EKL p. 4: `OPol_N` is left Noetherian. -/
theorem left_noetherian : IsNoetherianRing (SkewPolynomial N) :=
  isNoetherian_of_tower (MvPolynomial (Fin N) ℤ) inferInstance

/-- EKL p. 4: `OPol_N` is right Noetherian. -/
theorem right_noetherian : IsNoetherianRing (SkewPolynomial N)ᵐᵒᵖ := by
  haveI : IsNoetherian (MvPolynomial (Fin N) ℤ) (SkewPolynomial N)ᵐᵒᵖ :=
    isNoetherian_of_linearEquiv (MulOpposite.opLinearEquiv (MvPolynomial (Fin N) ℤ))
  exact isNoetherian_of_tower (MvPolynomial (Fin N) ℤ) inferInstance

end Noetherian

end OddMath.Frontier.EKLMisc
