import OddMath.Frontier.EKLSectionTwo
import Mathlib.RingTheory.MvPolynomial.Symmetric.FundamentalTheorem
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Supported

/-! EKL arXiv:1111.1320v1, §2.1.1, display (2.13), p.5, and the last claim of
Remark 2.28, p.20.

Reduction modulo 2 sends the ordered monomial `x^a` to the commutative monomial `x^a`
over `𝔽₂`; the skew sign becomes `1`, so this is a ring homomorphism
`OPol_a → 𝔽₂[x₁,…,x_a]`. It is surjective with kernel `2·OPol_a`, and it maps `OΛ_a`
onto the symmetric polynomials over `𝔽₂` with kernel `2·OΛ_a` (the two isomorphisms
of (2.13); `Λ_a ⊗ ℤ/2` is the ring of symmetric polynomials over `𝔽₂` by the fundamental
theorem). As an application, `ε₄` is not in the subring generated by
`h₁, h₂, h₃, ε₁, ε₂, ε₃` in any rank `a ≥ 4`. -/
namespace OddMath.Frontier.EKLSectionTwo
open OddMath.SkewPolynomial (SkewPolynomial monomial generator)
open FiniteCompleteElementary OddSymmetricKernel
open scoped BigOperators
noncomputable section

/-- Commutative polynomials over `𝔽₂` in `N` variables. -/
abbrev Pol2 (N : ℕ) := MvPolynomial (Fin N) (ZMod 2)

/-- An exponent vector as a finitely supported function. -/
def expFinsupp {N : ℕ} (a : Fin N → ℕ) : Fin N →₀ ℕ := Finsupp.equivFunOnFinite.symm a

theorem expFinsupp_add {N : ℕ} (a b : Fin N → ℕ) :
    expFinsupp (a + b) = expFinsupp a + expFinsupp b := by
  ext i; simp [expFinsupp]

theorem expFinsupp_injective {N : ℕ} : Function.Injective (expFinsupp (N := N)) :=
  Finsupp.equivFunOnFinite.symm.injective

/-- Additive reduction modulo 2. -/
def reduceAdd (N : ℕ) : SkewPolynomial N →+ Pol2 N :=
  Finsupp.liftAddHom fun a =>
    (MvPolynomial.monomial (expFinsupp a)).toAddMonoidHom.comp (Int.castAddHom (ZMod 2))

theorem reduceAdd_monomial {N : ℕ} (a : Fin N → ℕ) (c : ℤ) :
    reduceAdd N (monomial a c) = MvPolynomial.monomial (expFinsupp a) (c : ZMod 2) := by
  simp [reduceAdd]

theorem skewSign_cast {N : ℕ} (a b : Fin N → ℕ) : ((OddMath.skewSign a b : ℤ) : ZMod 2) = 1 := by
  unfold OddMath.skewSign
  push_cast
  rw [show (-1 : ZMod 2) = 1 from rfl, one_pow]

theorem reduceAdd_mul_monomial {N : ℕ} (a b : Fin N → ℕ) (r s : ℤ) :
    reduceAdd N (monomial a r * monomial b s) =
      reduceAdd N (monomial a r) * reduceAdd N (monomial b s) := by
  change reduceAdd N (OddMath.SkewPolynomial.mul _ _) = _
  rw [OddMath.SkewPolynomial.mul_monomial, reduceAdd_monomial, reduceAdd_monomial,
    reduceAdd_monomial, MvPolynomial.monomial_mul, expFinsupp_add]
  push_cast [skewSign_cast]
  rw [mul_one]

/-- Reduction modulo 2, `OPol_a → 𝔽₂[x₁,…,x_a]`. -/
def reduce (N : ℕ) : SkewPolynomial N →+* Pol2 N where
  toFun := reduceAdd N
  map_one' := by
    change reduceAdd N (monomial 0 1) = 1
    rw [reduceAdd_monomial]
    have : expFinsupp (0 : Fin N → ℕ) = 0 := by ext; simp [expFinsupp]
    rw [this]; simp
  map_mul' f g := by
    induction f using Finsupp.induction_linear with
    | zero => simp
    | add f₁ f₂ h₁ h₂ => rw [add_mul, map_add, map_add, h₁, h₂, add_mul]
    | single a r =>
      induction g using Finsupp.induction_linear with
      | zero => simp
      | add g₁ g₂ h₁ h₂ => rw [mul_add, map_add, map_add, h₁, h₂, mul_add]
      | single b s => exact reduceAdd_mul_monomial a b r s
  map_zero' := map_zero _
  map_add' := map_add _

theorem reduce_monomial {N : ℕ} (a : Fin N → ℕ) (c : ℤ) :
    reduce N (monomial a c) = MvPolynomial.monomial (expFinsupp a) (c : ZMod 2) :=
  reduceAdd_monomial a c

theorem coeff_reduce {N : ℕ} (f : SkewPolynomial N) (a : Fin N → ℕ) :
    MvPolynomial.coeff (expFinsupp a) (reduce N f) = (f a : ZMod 2) := by
  classical
  induction f using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg => rw [map_add, MvPolynomial.coeff_add, hf, hg, Finsupp.add_apply, Int.cast_add]
  | single b c =>
    rw [show Finsupp.single b c = monomial b c from rfl, reduce_monomial, MvPolynomial.coeff_monomial]
    by_cases h : b = a
    · subst h; simp
    · rw [if_neg (fun e => h (expFinsupp_injective e)), Finsupp.single_eq_of_ne h, Int.cast_zero]

theorem reduce_two_smul {N : ℕ} (g : SkewPolynomial N) : reduce N ((2 : ℤ) • g) = 0 := by
  rw [map_zsmul, two_zsmul, CharTwo.add_self_eq_zero]

/-- (2.13), first line: the kernel of reduction is `2·OPol_a`. -/
theorem reduce_eq_zero_iff {N : ℕ} (f : SkewPolynomial N) :
    reduce N f = 0 ↔ ∃ g : SkewPolynomial N, f = (2 : ℤ) • g := by
  constructor
  · intro hf
    have hd : ∀ a, (2 : ℤ) ∣ f a := by
      intro a
      have := coeff_reduce f a
      rw [hf, MvPolynomial.coeff_zero] at this
      exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ 2).mp this.symm
    refine ⟨Finsupp.mapRange (fun z => z / 2) (by simp) f, ?_⟩
    ext a
    simp only [Finsupp.smul_apply, Finsupp.mapRange_apply, smul_eq_mul]
    exact (Int.mul_ediv_cancel' (hd a)).symm
  · rintro ⟨g, rfl⟩
    exact reduce_two_smul g

theorem reduce_surjective (N : ℕ) : Function.Surjective (reduce N) := by
  intro p
  induction p using MvPolynomial.induction_on' with
  | monomial s c =>
    refine ⟨monomial (⇑s) (c.val : ℤ), ?_⟩
    rw [reduce_monomial]
    have : expFinsupp (⇑s) = s := by ext; simp [expFinsupp]
    rw [this]
    simp
  | add p q hp hq =>
    obtain ⟨f, rfl⟩ := hp
    obtain ⟨g, rfl⟩ := hq
    exact ⟨f + g, map_add _ _ _⟩

/-- (2.13), first line: `OPol_a ⊗ ℤ/2 ≅ Pol_a ⊗ ℤ/2`; the kernel is `2·OPol_a`
by `reduce_eq_zero_iff`. -/
def polynomialModTwo (N : ℕ) : SkewPolynomial N ⧸ RingHom.ker (reduce N) ≃+* Pol2 N :=
  RingHom.quotientKerEquivOfSurjective (reduce_surjective N)

/-! ### Elementary and complete polynomials modulo 2 -/

theorem reduce_generator {N : ℕ} (i : Fin N) : reduce N (generator i) = MvPolynomial.X i := by
  rw [generator, reduce_monomial]
  have : expFinsupp (OddMath.SkewPolynomial.expSingle i) = Finsupp.single i 1 := by
    ext j; simp [expFinsupp, OddMath.SkewPolynomial.expSingle, Finsupp.single_apply]
  rw [this]; simp [MvPolynomial.X]

theorem neg_one_pow_cast (k : ℕ) : (((-1 : ℤ) ^ k : ℤ) : ZMod 2) = 1 := by
  push_cast; rw [show (-1 : ZMod 2) = 1 from rfl, one_pow]

theorem reduce_subsetTilde {N : ℕ} (I : Finset (Fin N)) :
    reduce N (OddSchurPieri.subsetTilde I) = ∏ i ∈ I, MvPolynomial.X i := by
  classical
  rw [OddSchurPieri.subsetTilde, map_zsmul, reduce_monomial]
  have he : expFinsupp (OddSchurPieri.subsetExp I) = ∑ i ∈ I, Finsupp.single i 1 := by
    ext j
    simp [expFinsupp, OddSchurPieri.subsetExp, Finsupp.finset_sum_apply, Finsupp.single_apply]
  rw [he, Int.cast_one, MvPolynomial.monomial_sum_one, zsmul_eq_mul]
  push_cast
  rw [CharTwo.neg_eq, one_pow, one_mul]
  rfl

/-- Modulo 2, `ε_k` is the elementary symmetric polynomial `e_k`. -/
theorem reduce_elementary (N k : ℕ) :
    reduce N (elementaryPoly N k) = MvPolynomial.esymm (Fin N) (ZMod 2) k := by
  classical
  rw [OddSchurPieri.elementary_subsets, map_sum, MvPolynomial.esymm, Finset.powersetCard_eq_filter,
    Finset.powerset_univ]
  exact Finset.sum_congr rfl fun I _ => reduce_subsetTilde I

open MvPolynomial (esymm X) in
theorem reduce_complete_mem (N : ℕ) (k : ℕ) (hk : k = 1 ∨ k = 2 ∨ k = 3) :
    reduce N (completePoly N k) ∈ Subring.closure
      ({esymm (Fin N) (ZMod 2) 1, esymm (Fin N) (ZMod 2) 2, esymm (Fin N) (ZMod 2) 3} :
        Set (Pol2 N)) := by
  have m : ∀ j, j = 1 ∨ j = 2 ∨ j = 3 → esymm (Fin N) (ZMod 2) j ∈ Subring.closure
      ({esymm (Fin N) (ZMod 2) 1, esymm (Fin N) (ZMod 2) 2, esymm (Fin N) (ZMod 2) 3} :
        Set (Pol2 N)) := by
    intro j hj
    apply Subring.subset_closure
    rcases hj with rfl | rfl | rfl <;> simp
  rcases hk with rfl | rfl | rfl
  · rw [complete_one, reduce_elementary]; exact m 1 (by simp)
  · rw [complete_two, map_add, map_mul, reduce_elementary, reduce_elementary]
    exact add_mem (mul_mem (m 1 (by simp)) (m 1 (by simp))) (m 2 (by simp))
  · rw [complete_three, map_add, map_mul, map_mul, reduce_elementary, reduce_elementary]
    exact add_mem (mul_mem (mul_mem (m 1 (by simp)) (m 1 (by simp))) (m 1 (by simp)))
      (m 3 (by simp))

/-- Remark 2.28, last claim: `ε₄` is not in the subring generated by
`h₁, h₂, h₃, ε₁, ε₂, ε₃`, in every rank `a ≥ 4`. -/
theorem elementary_four_not_mem (n : ℕ) :
    elementaryPoly (n+4) 4 ∉ Subring.closure
      ({completePoly (n+4) 1, completePoly (n+4) 2, completePoly (n+4) 3,
        elementaryPoly (n+4) 1, elementaryPoly (n+4) 2, elementaryPoly (n+4) 3} :
        Set (SkewPolynomial (n+4))) := by
  intro hmem
  set E := fun j : ℕ => MvPolynomial.esymm (Fin (n+4)) (ZMod 2) j
  let κ : MvPolynomial (Fin 4) (ZMod 2) →+* Pol2 (n+4) :=
    (MvPolynomial.aeval (fun i : Fin 4 => E (i.val + 1))).toRingHom
  have hκ : ∀ p, κ p = (MvPolynomial.esymmAlgHom (Fin (n+4)) (ZMod 2) 4 p).val := fun p =>
    (MvPolynomial.esymmAlgHom_apply p).symm
  have hinj : Function.Injective κ := by
    intro p q h
    rw [hκ, hκ] at h
    exact MvPolynomial.esymmAlgHom_injective (ZMod 2) (by simp) (Subtype.ext h)
  have hX : ∀ i : Fin 4, κ (MvPolynomial.X i) = E (i.val + 1) := fun i =>
    MvPolynomial.aeval_X _ _
  let T := (MvPolynomial.supported (ZMod 2) ({0, 1, 2} : Set (Fin 4))).toSubring
  have hE : ∀ j, j = 1 ∨ j = 2 ∨ j = 3 → E j ∈ T.map κ := by
    intro j hj
    rcases hj with rfl | rfl | rfl
    · exact ⟨_, MvPolynomial.X_mem_supported.mpr (by simp), hX 0⟩
    · exact ⟨_, MvPolynomial.X_mem_supported.mpr (by simp), hX 1⟩
    · exact ⟨_, MvPolynomial.X_mem_supported.mpr (by simp), hX 2⟩
  have hcl : Subring.closure ({E 1, E 2, E 3} : Set (Pol2 (n+4))) ≤ T.map κ := by
    rw [Subring.closure_le]
    rintro _ (rfl | rfl | rfl)
    exacts [hE 1 (by simp), hE 2 (by simp), hE 3 (by simp)]
  have hmap : (Subring.closure ({completePoly (n+4) 1, completePoly (n+4) 2,
      completePoly (n+4) 3, elementaryPoly (n+4) 1, elementaryPoly (n+4) 2,
      elementaryPoly (n+4) 3} : Set (SkewPolynomial (n+4)))).map (reduce (n+4)) ≤ T.map κ := by
    rw [RingHom.map_closure, Subring.closure_le]
    rintro _ ⟨f, hf, rfl⟩
    apply hcl
    rcases hf with rfl | rfl | rfl | rfl | rfl | rfl
    · exact reduce_complete_mem _ 1 (by simp)
    · exact reduce_complete_mem _ 2 (by simp)
    · exact reduce_complete_mem _ 3 (by simp)
    all_goals rw [reduce_elementary]; exact Subring.subset_closure (by simp [E])
  obtain ⟨p, hp, hpe⟩ := hmap ⟨_, hmem, rfl⟩
  rw [reduce_elementary] at hpe
  have h3 := hinj (hpe.trans (hX 3).symm)
  rw [h3] at hp
  have := MvPolynomial.X_mem_supported.mp hp
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at this
  rcases this with h | h | h <;> exact absurd h (by decide)

/-! ### Odd symmetric polynomials modulo 2 -/

/-- (2.13), second line: reduction maps `OΛ_a` onto the symmetric polynomials over `𝔽₂`. -/
theorem map_kernel (n : ℕ) :
    (kernelSubring n).map (reduce (n+2)) =
      (MvPolynomial.symmetricSubalgebra (Fin (n+2)) (ZMod 2)).toSubring := by
  rw [ElementaryGeneration.kernel_eq_elementaryClosure, ElementaryGeneration.elementaryClosure,
    RingHom.map_closure]
  apply le_antisymm
  · rw [Subring.closure_le]
    rintro _ ⟨f, ⟨k, _, _, rfl⟩, rfl⟩
    rw [reduce_elementary]
    exact MvPolynomial.esymm_isSymmetric _ _ _
  · intro p hp
    obtain ⟨q, hq⟩ := MvPolynomial.esymmAlgHom_surjective (ZMod 2) (σ := Fin (n+2)) (n := n+2)
      (by simp) ⟨p, hp⟩
    have hpq : p = MvPolynomial.aeval (fun i : Fin (n+2) =>
        MvPolynomial.esymm (Fin (n+2)) (ZMod 2) (i.val + 1)) q := by
      rw [← MvPolynomial.esymmAlgHom_apply, hq]
    rw [hpq]
    clear hpq hq hp
    induction q using MvPolynomial.induction_on with
    | C c =>
      rw [MvPolynomial.aeval_C, show c = ((c.val : ℕ) : ZMod 2) by simp, map_natCast]
      exact natCast_mem _ _
    | add p q hp hq => rw [map_add]; exact add_mem hp hq
    | mul_X p i hp =>
      rw [map_mul, MvPolynomial.aeval_X]
      refine mul_mem hp (Subring.subset_closure ⟨elementaryPoly (n+2) (i.val + 1),
        ⟨i.val + 1, by omega, by omega, rfl⟩, reduce_elementary _ _⟩)

/-- Reduction modulo 2 on `OΛ_a`, with values in the symmetric polynomials over `𝔽₂`. -/
def reduceSymmetric (n : ℕ) :
    kernelSubring n →+* MvPolynomial.symmetricSubalgebra (Fin (n+2)) (ZMod 2) :=
  RingHom.codRestrict ((reduce (n+2)).comp (kernelSubring n).subtype) _ fun x => by
    have : reduce (n+2) x ∈ (kernelSubring n).map (reduce (n+2)) := ⟨x, x.2, rfl⟩
    rw [map_kernel] at this
    exact this

theorem reduceSymmetric_surjective (n : ℕ) : Function.Surjective (reduceSymmetric n) := by
  rintro ⟨p, hp⟩
  have : p ∈ (kernelSubring n).map (reduce (n+2)) := by rw [map_kernel]; exact hp
  obtain ⟨x, hx, rfl⟩ := this
  exact ⟨⟨x, hx⟩, rfl⟩

/-- (2.13), second line: the kernel of reduction on `OΛ_a` is `2·OΛ_a`. -/
theorem reduceSymmetric_eq_zero_iff (n : ℕ) (f : kernelSubring n) :
    reduceSymmetric n f = 0 ↔ ∃ g : kernelSubring n, f = (2 : ℤ) • g := by
  constructor
  · intro hf
    have h0 : reduce (n+2) f.1 = 0 := congrArg Subtype.val hf
    obtain ⟨g, hg⟩ := (reduce_eq_zero_iff _).mp h0
    have hgk : g ∈ kernelSubring n := by
      intro i
      have h1 := f.2 i
      rw [hg, map_zsmul] at h1
      exact (smul_eq_zero.mp h1).resolve_left (by norm_num)
    exact ⟨⟨g, hgk⟩, Subtype.ext hg⟩
  · rintro ⟨g, rfl⟩
    exact Subtype.ext (reduce_two_smul g.1)

/-- (2.13), second line: `OΛ_a ⊗ ℤ/2 ≅ Λ_a ⊗ ℤ/2`; the kernel is `2·OΛ_a` by
`reduceSymmetric_eq_zero_iff`. -/
def symmetricModTwo (n : ℕ) :
    kernelSubring n ⧸ RingHom.ker (reduceSymmetric n) ≃+*
      MvPolynomial.symmetricSubalgebra (Fin (n+2)) (ZMod 2) :=
  RingHom.quotientKerEquivOfSurjective (reduceSymmetric_surjective n)

end
end OddMath.Frontier.EKLSectionTwo
