import OddMath.Frontier.EKOverKStructure

/-!
# EK Corollary 2.13 over an arbitrary commutative ring

Source: Ellis–Khovanov, arXiv:1107.5610v2, §2.2, Corollary 2.13 (p. 15): `Λ` is the
`k`-algebra generated by `h_1, h_2, …` subject to (2.11)–(2.12), namely
* `h_a h_b = h_b h_a` if `a + b` is even,
* `h_a h_b + (-1)^a h_b h_a = (-1)^a h_{a+1} h_{b-1} + h_{b-1} h_{a+1}` if `a + b` is odd;
it is also generated by `e_1, e_2, …` subject to the same relations with `e` in place of `h`,
and `h_n ↦ e_n` extends to an automorphism of `Λ`.

Here `k` is an arbitrary commutative ring and `q = -1`.

* `RelatorK k`: the relators (2.11)–(2.12) in the free `k`-algebra `Λ'_k` (`h_0 = 1`);
  `PresentedK k` is the quotient by the two-sided ideal they generate.
* `presentationK : PresentedK k ≃ₐ[k] Λ_k`, `h_n ↦ h_n` (Cor. 2.13, `h`-presentation).
* `elementaryPresentationK : PresentedK k ≃ₐ[k] Λ_k`, `h_n ↦ e_n` (Cor. 2.13,
  `e`-presentation).
* `psi1K_eq`: ψ₁ (`h_n ↦ e_n`) is `elementaryPresentationK ∘ presentationK⁻¹`.
-/

noncomputable section
set_option synthInstance.maxHeartbeats 400000
open scoped TensorProduct BigOperators

namespace OddMath.Frontier.EKOverK
open EKGeneralQ

variable (k : Type*) [CommRing k]

/-- The relators (2.11)–(2.12) in `Λ'_k = k⟨h_1, h_2, …⟩` (with `h_0 = 1`). -/
inductive RelatorK : L k → Prop
  | even (a b : ℕ) (hab : Even (a + b)) : RelatorK (h k a * h k b - h k b * h k a)
  | odd (a b : ℕ) (hb : 0 < b) (hab : Odd (a + b)) :
      RelatorK (h k a * h k b + (-1 : k) ^ a • (h k b * h k a) -
        ((-1 : k) ^ a • (h k (a + 1) * h k (b - 1)) + h k (b - 1) * h k (a + 1)))

/-- The two-sided ideal generated by (2.11)–(2.12). -/
def relIdealK : Ideal (L k) := (TwoSidedIdeal.span {r | RelatorK k r}).asIdeal

instance relIdealK_isTwoSided : (relIdealK k).IsTwoSided :=
  inferInstanceAs (TwoSidedIdeal.span {r | RelatorK k r}).asIdeal.IsTwoSided

/-- The `k`-algebra presented by generators `h_1, h_2, …` and relations (2.11)–(2.12). -/
abbrev PresentedK := L k ⧸ relIdealK k

variable {k}

/-- The generator `h_n` of the presented algebra. -/
def hP (n : ℕ) : PresentedK k := Ideal.Quotient.mk (relIdealK k) (h k n)

theorem mkₐ_h (n : ℕ) : Ideal.Quotient.mkₐ k (relIdealK k) (h k n) = hP n := rfl

theorem relatorK_mem {r : L k} (hr : RelatorK k r) : r ∈ relIdealK k := by
  change r ∈ (TwoSidedIdeal.span {r | RelatorK k r}).asIdeal
  rw [TwoSidedIdeal.mem_asIdeal]
  exact TwoSidedIdeal.subset_span hr

theorem iota_zsmul (c : ℤ) (x : L ℤ) : iota k (c • x) = (c : k) • iota k x := by
  rw [map_zsmul, ← Int.cast_smul_eq_zsmul k]

/-- The relators over `k` are exactly the images of the integral relators. -/
theorem relatorK_iff (r : L k) :
    RelatorK k r ↔ ∃ r₀ : L ℤ, EKPresentation.Relator r₀ ∧ iota k r₀ = r := by
  constructor
  · rintro (⟨a, b, hab⟩ | ⟨a, b, hb, hab⟩)
    · refine ⟨_, EKPresentation.Relator.even a b hab, ?_⟩
      simp only [map_sub, map_mul, ← h_int, iota_h]
    · refine ⟨_, EKPresentation.Relator.odd a b hb hab, ?_⟩
      simp only [map_sub, map_add, map_mul, iota_zsmul, ← h_int, iota_h]
      push_cast; rfl
  · rintro ⟨r₀, (⟨a, b, hab⟩ | ⟨a, b, hb, hab⟩), rfl⟩
    · have := RelatorK.even (k := k) a b hab
      simpa only [map_sub, map_mul, ← h_int, iota_h] using this
    · have := RelatorK.odd (k := k) a b hb hab
      simp only [map_sub, map_add, map_mul, iota_zsmul, ← h_int, iota_h]
      push_cast
      exact this

/-! ## The map to `Λ_k` -/

/-- An algebra hom out of `Λ'_k` that kills the images of the integral relators kills
`relIdealK`. -/
theorem kills_relIdealK {B : Type*} [Ring B] [Algebra k B] (F : L k →ₐ[k] B)
    (hF : ∀ r₀ : L ℤ, EKPresentation.Relator r₀ → F (iota k r₀) = 0) :
    ∀ r ∈ relIdealK k, F r = 0 := by
  intro r hr
  change r ∈ (TwoSidedIdeal.span {r | RelatorK k r}).asIdeal at hr
  rw [TwoSidedIdeal.mem_asIdeal] at hr
  induction hr using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨r₀, h₀, rfl⟩ := (relatorK_iff x).mp hx
    exact hF r₀ h₀
  | zero => exact map_zero _
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx => rw [map_mul, hx, zero_mul]

theorem psiRing_freeToColor_false (x : L ℤ) :
    psiRing (k := k) (EKPresentation.freeToColor false x) = piQ (-1 : k) (iota k x) := by
  rfl

/-- `PresentedK k → Λ_k`, `h_n ↦ h_n`. -/
def toLamK : PresentedK k →ₐ[k] LamK k :=
  Ideal.Quotient.liftₐ (relIdealK k) (piQ (-1 : k)) (kills_relIdealK (piQ (-1 : k)) (by
    intro r₀ h₀
    rw [← psiRing_freeToColor_false,
      EKPresentation.relation_killed false r₀ h₀, map_zero]))

@[simp] theorem toLamK_mk (x : L k) :
    toLamK (Ideal.Quotient.mk (relIdealK k) x) = piQ (-1 : k) x := rfl

@[simp] theorem toLamK_hP (n : ℕ) : toLamK (hP n) = hK k n := by
  rw [hP, toLamK_mk, hK_eq]

/-! ## The inverse map -/

/-- `Λ'_ℤ → PresentedK k`. -/
def fromFreeZ : L ℤ →+* PresentedK k :=
  (Ideal.Quotient.mk (relIdealK k)).comp (iota k).toRingHom

theorem fromFreeZ_killed (r : L ℤ) (hr : r ∈ EKPresentation.relIdeal) : fromFreeZ (k := k) r = 0 := by
  rw [EKPresentation.relIdeal, EKPresentation.relTwoSided, TwoSidedIdeal.mem_asIdeal] at hr
  induction hr using TwoSidedIdeal.span_induction with
  | mem x hx =>
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    exact relatorK_mem ((relatorK_iff _).mpr ⟨x, hx, rfl⟩)
  | zero => exact map_zero _
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx => rw [map_mul, hx, zero_mul]

/-- The integral presented ring maps to `PresentedK k`. -/
def fromPresentedZ : EKPresentation.Presented →+* PresentedK k :=
  Ideal.Quotient.lift EKPresentation.relIdeal fromFreeZ fromFreeZ_killed

/-- `Λ_ℤ → PresentedK k`, `h_n ↦ h_n`. -/
def fromQ : QZ →+* PresentedK k :=
  fromPresentedZ.comp EKPresentation.presentationEquiv.symm.toRingHom

theorem fromQ_h (n : ℕ) : fromQ (k := k) (EKElementaryQuotient.h n) = hP n := by
  have h1 : EKPresentation.presentationEquiv.symm (EKElementaryQuotient.h n) =
      EKPresentation.h n := by
    apply EKPresentation.presentationEquiv.injective
    rw [RingEquiv.apply_symm_apply, EKPresentation.presentationEquiv_h]
  simp only [fromQ, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, h1]
  change fromFreeZ (CompleteElementary.h n) = _
  simp only [fromFreeZ, RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
  rw [← h_int, iota_h]
  rfl

/-- `Λ_k → PresentedK k`, the inverse of `toLamK`. -/
def fromLamK : LamK k →ₐ[k] PresentedK k :=
  (Algebra.TensorProduct.lift (Algebra.ofId k (PresentedK k)) (fromQ (k := k)).toIntAlgHom
    (fun _ _ => Algebra.commutes' _ _)).comp (EKFinal.baseChangeAlgEquiv k).symm.toAlgHom

@[simp] theorem fromLamK_psiRing (z : QZ) : fromLamK (psiRing (k := k) z) = fromQ z := by
  simp [fromLamK, baseChangeAlgEquiv_symm_psiRing]

theorem toLamK_fromQ : (toLamK (k := k)).toRingHom.comp fromQ = psiRing := by
  apply EKAutomorphisms.hom_ext_h
  intro n
  show toLamK (fromQ (EKElementaryQuotient.h n)) = psiRing (EKElementaryQuotient.h n)
  rw [fromQ_h, toLamK_hP]
  rfl

theorem toLamK_fromLamK (x : LamK k) : toLamK (fromLamK x) = x := by
  have h := algHom_ext (F := (toLamK (k := k)).comp fromLamK) (G := AlgHom.id k (LamK k))
    (fun z => by
      simp only [AlgHom.comp_apply, fromLamK_psiRing, AlgHom.id_apply]
      exact RingHom.congr_fun toLamK_fromQ z)
  exact AlgHom.congr_fun h x

theorem fromLamK_toLamK (x : PresentedK k) : fromLamK (toLamK x) = x := by
  have h : (fromLamK (k := k)).comp toLamK = AlgHom.id k (PresentedK k) := by
    apply Ideal.Quotient.algHom_ext
    apply FreeAlgebra.hom_ext
    funext i
    show fromLamK (toLamK (Ideal.Quotient.mkₐ k (relIdealK k) (FreeAlgebra.ι k i))) =
      Ideal.Quotient.mkₐ k (relIdealK k) (FreeAlgebra.ι k i)
    have hi : FreeAlgebra.ι k i = h k (i + 1) := rfl
    rw [hi, mkₐ_h, toLamK_hP, hK, fromLamK_psiRing, fromQ_h]
  exact AlgHom.congr_fun h x

variable (k) in
/-- **EK Corollary 2.13 over every commutative ring `k`** (`h`-presentation):
`Λ_k` is the `k`-algebra generated by the `h_n` subject to (2.11)–(2.12). -/
def presentationK : PresentedK k ≃ₐ[k] LamK k :=
  AlgEquiv.ofAlgHom toLamK fromLamK (AlgHom.ext toLamK_fromLamK) (AlgHom.ext fromLamK_toLamK)

@[simp] theorem presentationK_hP (n : ℕ) : presentationK k (hP n) = hK k n := toLamK_hP n

/-! ## The `e`-presentation and the automorphism `h_n ↦ e_n` -/

variable (k) in
/-- **EK Corollary 2.13 over every commutative ring `k`** (`e`-presentation):
`h_n ↦ e_n` identifies the algebra presented by (2.11)–(2.12) with `Λ_k`; i.e. `Λ_k` is
generated by the `e_n` subject to (2.11)–(2.12) with `e` in place of `h`. -/
def elementaryPresentationK : PresentedK k ≃ₐ[k] LamK k :=
  (presentationK k).trans (psi1K k)

@[simp] theorem elementaryPresentationK_hP (n : ℕ) :
    elementaryPresentationK k (hP n) = eK' k n := by
  simp [elementaryPresentationK]

theorem relator_zero {r : L k} (hr : RelatorK k r) : Ideal.Quotient.mkₐ k (relIdealK k) r = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (relatorK_mem hr)

/-- The `e_n` satisfy (2.11) over `k`. -/
theorem eK'_even (a b : ℕ) (hab : Even (a + b)) : eK' k a * eK' k b = eK' k b * eK' k a := by
  have h0 := relator_zero (RelatorK.even (k := k) a b hab)
  rw [map_sub, map_mul, map_mul, mkₐ_h, mkₐ_h] at h0
  have := congrArg (elementaryPresentationK k) h0
  rw [map_zero, map_sub, map_mul, map_mul, elementaryPresentationK_hP,
    elementaryPresentationK_hP, sub_eq_zero] at this
  exact this

/-- The `e_n` satisfy (2.12) over `k`. -/
theorem eK'_odd (a b : ℕ) (hb : 0 < b) (hab : Odd (a + b)) :
    eK' k a * eK' k b + (-1 : k) ^ a • (eK' k b * eK' k a) =
      (-1 : k) ^ a • (eK' k (a + 1) * eK' k (b - 1)) + eK' k (b - 1) * eK' k (a + 1) := by
  have h0 := relator_zero (RelatorK.odd (k := k) a b hb hab)
  simp only [map_sub, map_add, map_mul, map_smul, mkₐ_h] at h0
  have := congrArg (elementaryPresentationK k) h0
  simp only [map_zero, map_sub, map_add, map_mul, map_smul, elementaryPresentationK_hP,
    sub_eq_zero] at this
  exact this

/-- **EK Corollary 2.13 over `k`:** the automorphism `ψ₁ : h_n ↦ e_n` is the composite of the
two presentations. -/
theorem psi1K_eq : psi1K k = (presentationK k).symm.trans (elementaryPresentationK k) := by
  ext x
  simp [elementaryPresentationK]

end OddMath.Frontier.EKOverK
