import OddMath.Frontier.EKCoideal
import OddMath.Frontier.EKQuotientRelations
import OddMath.Frontier.EKPresentation
import OddMath.Frontier.EKDualBases
import Mathlib.Algebra.DualNumber

/-!
# EK1107.5610v2 §3.2, printed p25, Proposition 3.3 (integral, actual `Q`)

Primitive elements of the actual integral quotient `Q` (radical quotient of the
free algebra, with the existing signed coproduct `EKCoideal.quotientCoproduct`)
in positive degree `n`:

* `n = 1` or `n` even: `x` primitive ↔ `x ∈ ℤ ∙ m_(n)`;
* `n` odd, `n ≥ 3`: `x` primitive ↔ `x = 0`.

Also the source's degreewise description of `I² ∩ Λ_n`, `I` the ideal generated by
the positive-degree pieces:
* `n = 1`: `I² ∩ Λ_1 = 0` (integrally; hence also after saturation / `⊗ℚ`);
* `n` even: `I² ∩ Λ_n = span_ℤ {h_λ : λ ≠ (n)}` integrally, and this is saturated;
* `n` odd `≥ 3`: `2 • Λ_n ⊆ I²`, so `I² ∩ Λ_n` has full rank (everything after `⊗ℚ`).

Method (no Milnor–Moore, no general Hopf theory): for `n = 1` or `n` even the
assignment `h_k ↦ δ_{k,n} ε` on generators (`h_0 = 1`) into the commutative dual
numbers `ℤ[ε]` kills EVERY literal EK relator (2.11)/(2.12) of the inherited
presentation `EKPresentation`; it therefore descends to a ring map `Φₙ : Q → ℤ[ε]`
(through the inherited ring isomorphism `Presented ≃+* Q`). Its first component is
the counit and its second component `φₙ` is a derivation-type functional:
`φₙ(ab) = ε(a) φₙ(b) + φₙ(a) ε(b)`. On the complete-partition basis `φₙ` agrees
with pairing against `m_(n)`; hence `⟨ab, m_(n)⟩ = ε(a)⟨b,m_(n)⟩ + ⟨a,m_(n)⟩ε(b)`,
which by adjointness and integral tensor separation is exactly primitivity.
This is the concrete, proved-here content of the source's `P = (I²)^⊥` step.
-/
noncomputable section
set_option synthInstance.maxHeartbeats 200000
open scoped TensorProduct BigOperators DualNumber
namespace OddMath.Frontier.EKPrimitives
open EKRadicalQuotient EKCoideal EKElementaryQuotient EKDualBases EKIntegralBases
  DegreeShapes
open EKPartitionSpanning (hPartition)
open CompleteElementary (A)

local instance (d : ℕ) : Fintype (DegreeShape d) := degreeFintype d
local instance (d : ℕ) : DecidableEq (DegreeShape d) := Classical.decEq _

/-! ## The source predicate -/

/-- The source predicate, literally `Δ x = 1 ⊗ x + x ⊗ 1`, on actual `Q`. -/
def IsPrimitive (x : Q) : Prop :=
  quotientCoproduct x = (1 : Q) ⊗ₜ[ℤ] x + x ⊗ₜ[ℤ] (1 : Q)

/-! ## One-row shapes -/

/-- The one-row shape `(n)`. -/
def rowShape (n : ℕ) : DegreeShape n :=
  ⟨YoungDiagram.ofRowLens [n] (List.sorted_singleton n), by
    rw [EKPartitionSpanning.card_ofRowLens]; simp⟩

theorem rowShape_rows {n : ℕ} (hn : 0 < n) : (rowShape n).val.rowLens = [n] :=
  YoungDiagram.rowLens_ofRowLens_eq_self (hw := List.sorted_singleton n) (by simpa using hn)

theorem eq_rowShape {n : ℕ} (hn : 0 < n) (μ : DegreeShape n) (h : μ.val.rowLens = [n]) :
    μ = rowShape n := by
  apply Subtype.ext
  apply YoungDiagram.equivListRowLens.injective
  apply Subtype.ext
  change μ.val.rowLens = (rowShape n).val.rowLens
  rw [h, rowShape_rows hn]

theorem hPartition_rowShape {n : ℕ} (hn : 0 < n) : hPartition (rowShape n).val = h n := by
  simp [hPartition, rowShape_rows hn]

/-- The source's `m_(n)`: the one-row member of the inherited dual basis. -/
def mRow (n : ℕ) : degreePiece n := mBasis n (rowShape n)

theorem h_mem_degreePiece {n : ℕ} (hn : 0 < n) : h n ∈ degreePiece n := by
  have := (degreeHBasis n (rowShape n)).property
  rwa [degreeHBasis_apply, hPartition_rowShape hn] at this

theorem hPartition_mem (μ : YoungDiagram) : hPartition μ ∈ degreePiece μ.card := by
  have := (degreeHBasis μ.card ⟨μ, rfl⟩).property
  rwa [degreeHBasis_apply] at this

/-- Exhaustive row-shape dichotomy in positive degree. -/
theorem shape_cases {n : ℕ} (hn : 0 < n) (μ : DegreeShape n) :
    μ.val.rowLens = [n] ∨ 2 ≤ μ.val.rowLens.length := by
  have hs := (rowLens_sum μ.val).trans μ.property
  cases he : μ.val.rowLens with
  | nil => simp [he] at hs; omega
  | cons a t =>
    cases t with
    | nil => left; simp only [he, List.sum_cons, List.sum_nil, add_zero] at hs; simp [hs]
    | cons b t => right; simp

/-! ## Degree orthogonality of the actual pairing -/

theorem pairing_degree_orth {a b : ℕ} (hab : a ≠ b) {x y : Q}
    (hx : x ∈ degreePiece a) (hy : y ∈ degreePiece b) : quotientPairing x y = 0 := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨v, rfl⟩ := hx
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨w, rfl⟩ := hy
      rw [quotientPairing_pi]
      exact EKPairingAdjoint.pairing_degree_mismatch v.val w.val (by rw [v.property, w.property]; exact hab)
    | zero => simp
    | add u w _ _ hu hw => rw [map_add, hu, hw, add_zero]
    | smul r u _ hu => rw [map_smul, hu, smul_zero]
  | zero => simp
  | add u w _ _ hu hw => rw [map_add, LinearMap.add_apply, hu, hw, add_zero]
  | smul r u _ hu => rw [map_smul, LinearMap.smul_apply, hu, smul_zero]

theorem counit_degree_pos {d : ℕ} (hd : 0 < d) {x : Q} (hx : x ∈ degreePiece d) :
    quotientCounit x = 0 := by
  rw [← quotientPairing_right_one]
  exact pairing_degree_orth (by omega) hx unit_mem_degree_zero

/-! ## Adjointness and the derivation property of primitives -/

theorem test_coproduct (a b x : Q) :
    tensorTest a b (quotientCoproduct x) = quotientPairing (a * b) x := by
  obtain ⟨a, rfl⟩ := pi_surjective a
  obtain ⟨b, rfl⟩ := pi_surjective b
  obtain ⟨x, rfl⟩ := pi_surjective x
  rw [quotientCoproduct_pi, tensorTest_map, EKPairingAdjoint.tensorPairing_symm,
    EKPairingAdjoint.adjointness, ← pi.map_mul, quotientPairing_pi]

theorem prim_deriv {x : Q} (hx : IsPrimitive x) (a b : Q) :
    quotientPairing (a * b) x =
      quotientCounit a * quotientPairing b x + quotientPairing a x * quotientCounit b := by
  rw [← test_coproduct, hx, map_add, tensorTest_tmul, tensorTest_tmul,
    quotientPairing_symm 1 a, quotientPairing_right_one, quotientPairing_symm 1 b,
    quotientPairing_right_one, quotientPairing_symm x b, quotientPairing_symm x a]

theorem counit_h_pos {k : ℕ} (hk : 0 < k) : quotientCounit (h k) = 0 := by
  rw [h, quotientCounit_pi, EKFreeCoproduct.counit_h, if_neg (by omega)]

theorem counit_prod_pos (t : List ℕ) (ht : ∀ k ∈ t, 0 < k) (hne : t ≠ []) :
    quotientCounit ((t.map h).prod) = 0 := by
  cases t with
  | nil => exact absurd rfl hne
  | cons k t =>
    rw [List.map_cons, List.prod_cons, map_mul, counit_h_pos (ht k (by simp)), zero_mul]

/-- A primitive is orthogonal to every complete word of at least two positive rows. -/
theorem prim_long_zero {x : Q} (hx : IsPrimitive x) (μ : YoungDiagram)
    (hμ : 2 ≤ μ.rowLens.length) : quotientPairing (hPartition μ) x = 0 := by
  have hp := μ.pos_of_mem_rowLens
  unfold hPartition
  cases he : μ.rowLens with
  | nil => simp [he] at hμ
  | cons a t =>
    have ht : t ≠ [] := by rintro rfl; simp [he] at hμ
    rw [List.map_cons, List.prod_cons, prim_deriv hx, counit_h_pos (hp a (by simp [he])),
      counit_prod_pos t (fun k hk => hp k (by simp [he, hk])) ht]
    ring

/-! ## Upper bound: primitives lie in `ℤ ∙ m_(n)`, and vanish in odd degree `≥ 3` -/

theorem primitive_upper {n : ℕ} (hn : 0 < n) (x : degreePiece n) (hx : IsPrimitive x.val) :
    x = quotientPairing (h n) x.val • mRow n := by
  conv_lhs => rw [reconstruct_m n x]
  rw [Finset.sum_eq_single (rowShape n)]
  · rw [hPartition_rowShape hn]; rfl
  · intro μ _ hne
    rcases shape_cases hn μ with hr | hr
    · exact absurd (eq_rowShape hn μ hr) hne
    · rw [prim_long_zero hx μ.val hr, zero_smul]
  · intro h; exact absurd (Finset.mem_univ _) h

theorem h_odd_orth {k : ℕ} (hk : 0 < k) {x : Q} (hx : IsPrimitive x) :
    quotientPairing (h (2 * k + 1)) x = 0 := by
  have hrel := EKQuotientRelations.complete_one_even k
  have e : quotientPairing ((2 : ℤ) • h (2 * k + 1)) x = 0 := by
    rw [← hrel, map_add, LinearMap.add_apply, prim_deriv hx, prim_deriv hx,
      counit_h_pos (by norm_num : 0 < 1), counit_h_pos (by omega : 0 < 2 * k)]
    ring
  rw [map_smul, LinearMap.smul_apply, smul_eq_mul] at e
  omega

/-! ## The dual-number character `Φₙ` -/

/-- Generator `k` of the free algebra is `h_(k+1)`; send it to `ε` iff `k+1 = n`. -/
def freeChar (n : ℕ) : A →ₐ[ℤ] ℤ[ε] :=
  FreeAlgebra.lift ℤ (fun k => if k + 1 = n then (ε : ℤ[ε]) else 0)

/-- The value of the character on a generator `h_k`. -/
def cval (n k : ℕ) : ℤ[ε] := if k = 0 then 1 else if k = n then ε else 0

theorem freeChar_h (n k : ℕ) : freeChar n (CompleteElementary.h k) = cval n k := by
  cases k with
  | zero => simp [cval]
  | succ k =>
    simp only [CompleteElementary.h, freeChar, FreeAlgebra.lift_ι_apply, cval]
    simp

theorem eps_sq : (ε * ε : ℤ[ε]) = 0 := DualNumber.eps_mul_eps

/-- The odd-relator identity in the commutative target. -/
theorem cval_odd_relator (n a b : ℕ) (hn : n = 1 ∨ Even n) (hab : Odd (a + b)) (hb : 0 < b) :
    cval n a * cval n b + (-1 : ℤ) ^ a • (cval n b * cval n a) -
      ((-1 : ℤ) ^ a • (cval n (a + 1) * cval n (b - 1)) + cval n (b - 1) * cval n (a + 1)) = 0 := by
  rcases Nat.even_or_odd a with ha | ha
  · rw [ha.neg_one_pow, one_smul, one_smul]
    have hb' : b % 2 = 1 := by
      have := Nat.odd_iff.mp hab; have := Nat.even_iff.mp ha; omega
    have ha' := Nat.even_iff.mp ha
    have hn' : n = 1 ∨ n % 2 = 0 := by
      rcases hn with hn | hn
      · exact Or.inl hn
      · exact Or.inr (Nat.even_iff.mp hn)
    have key : cval n a * cval n b = cval n (a + 1) * cval n (b - 1) := by
      unfold cval
      split_ifs <;> simp_all [eps_sq] <;> omega
    rw [mul_comm (cval n b), key, mul_comm (cval n (b - 1))]
    abel
  · rw [ha.neg_one_pow, neg_one_smul, neg_one_smul, mul_comm (cval n b),
      mul_comm (cval n (b - 1))]
    abel

theorem freeChar_relator (n : ℕ) (hn : n = 1 ∨ Even n) (r : A)
    (hr : r ∈ EKPresentation.relSet) : freeChar n r = 0 := by
  cases hr with
  | even a b hab =>
    rw [map_sub, map_mul, map_mul, mul_comm, sub_self]
  | odd a b hb hab =>
    simp only [map_sub, map_add, map_mul, map_zsmul, freeChar_h]
    exact cval_odd_relator n a b hn hab hb

theorem freeChar_ideal (n : ℕ) (hn : n = 1 ∨ Even n) (r : A)
    (hr : r ∈ EKPresentation.relIdeal) : (freeChar n).toRingHom r = 0 := by
  rw [EKPresentation.relIdeal, EKPresentation.relTwoSided, TwoSidedIdeal.mem_asIdeal] at hr
  induction hr using TwoSidedIdeal.span_induction with
  | mem x hx => exact freeChar_relator n hn x hx
  | zero => exact map_zero _
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx => rw [map_mul, hx, zero_mul]

/-- The descended character `Φₙ : Q →+* ℤ[ε]` (for `n = 1` or `n` even). -/
def Phi (n : ℕ) (hn : n = 1 ∨ Even n) : Q →+* ℤ[ε] :=
  (Ideal.Quotient.lift EKPresentation.relIdeal (freeChar n).toRingHom (freeChar_ideal n hn)).comp
    EKPresentation.presentationEquiv.symm.toRingHom

theorem Phi_pi (n : ℕ) (hn : n = 1 ∨ Even n) (x : A) : Phi n hn (pi x) = freeChar n x := by
  have e : EKPresentation.presentationEquiv.symm (pi x) = EKPresentation.mk x := by
    apply EKPresentation.presentationEquiv.injective
    rw [RingEquiv.apply_symm_apply]; rfl
  simp only [Phi, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, e]
  rfl

theorem Phi_h (n : ℕ) (hn : n = 1 ∨ Even n) (k : ℕ) : Phi n hn (h k) = cval n k := by
  rw [h, Phi_pi, freeChar_h]

/-- First component of `Φₙ` is the actual counit. -/
theorem Phi_fst (n : ℕ) (hn : n = 1 ∨ Even n) (y : Q) :
    (Phi n hn y).fst = quotientCounit y := by
  obtain ⟨x, rfl⟩ := pi_surjective y
  rw [Phi_pi, quotientCounit_pi]
  have hext : (TrivSqZeroExt.fstHom ℤ ℤ ℤ).comp (freeChar n) = EKFreeCoproduct.counitAlg := by
    apply FreeAlgebra.hom_ext
    funext k
    simp only [Function.comp_apply, AlgHom.comp_apply, freeChar, FreeAlgebra.lift_ι_apply,
      EKFreeCoproduct.counitAlg]
    split_ifs <;> simp
  exact congrArg (fun f : A →ₐ[ℤ] ℤ => f x) hext

/-- The derivation-type functional `φₙ = snd ∘ Φₙ`. -/
def phi (n : ℕ) (hn : n = 1 ∨ Even n) : Q →ₗ[ℤ] ℤ where
  toFun y := (Phi n hn y).snd
  map_add' a b := by rw [map_add, TrivSqZeroExt.snd_add]
  map_smul' c y := by
    rw [map_zsmul, TrivSqZeroExt.snd_smul, RingHom.id_apply]

theorem phi_apply (n : ℕ) (hn : n = 1 ∨ Even n) (y : Q) : phi n hn y = (Phi n hn y).snd := rfl

theorem phi_mul (n : ℕ) (hn : n = 1 ∨ Even n) (a b : Q) :
    phi n hn (a * b) = quotientCounit a * phi n hn b + phi n hn a * quotientCounit b := by
  simp only [phi_apply, map_mul, TrivSqZeroExt.snd_mul, ← Phi_fst n hn, smul_eq_mul,
    MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]

/-- `Φₙ` on a positive word. -/
theorem Phi_word (n : ℕ) (hn : n = 1 ∨ Even n) (w : List ℕ) (hw : ∀ k ∈ w, 0 < k) :
    Phi n hn ((w.map h).prod) = if w = [] then 1 else if w = [n] then ε else 0 := by
  induction w with
  | nil => simp
  | cons k t ih =>
    have hk : 0 < k := hw k (by simp)
    rw [List.map_cons, List.prod_cons, map_mul, Phi_h, ih (fun j hj => hw j (by simp [hj]))]
    unfold cval
    by_cases ht : t = []
    · subst ht; simp [show k ≠ 0 by omega]
    · have hne : k :: t ≠ [n] := by intro e; simp at e; exact ht e.2
      simp only [ht, if_false, List.cons_ne_nil, hne, show k ≠ 0 by omega]
      split_ifs <;> simp [eps_sq]

theorem phi_hPartition (n : ℕ) (hn : n = 1 ∨ Even n) (μ : YoungDiagram) :
    phi n hn (hPartition μ) = if μ.rowLens = [n] then 1 else 0 := by
  rw [phi_apply, hPartition, Phi_word n hn _ μ.pos_of_mem_rowLens]
  split_ifs <;> simp_all

/-- On all of `Q`, `φₙ` is pairing against `m_(n)`. -/
theorem pairing_mRow (n : ℕ) (hn : n = 1 ∨ Even n) (hpos : 0 < n) (y : Q) :
    quotientPairing y (mRow n).val = phi n hn y := by
  have hlin : quotientPairing.flip (mRow n).val = phi n hn := by
    apply hBasis.ext
    intro μ
    rw [LinearMap.flip_apply, hBasis_apply, phi_hPartition]
    by_cases hc : μ.card = n
    · subst hc
      have := h_m μ.card ⟨μ, rfl⟩ (rowShape μ.card)
      rw [mRow, this]
      congr 1
      apply propext
      constructor
      · intro e; rw [← rowShape_rows hpos, ← e]
      · intro e; exact eq_rowShape hpos _ e
    · rw [pairing_degree_orth hc (hPartition_mem μ) (mRow n).property]
      rw [if_neg]
      intro e
      apply hc
      rw [← rowLens_sum, e]; simp
  exact congrArg (fun f : Q →ₗ[ℤ] ℤ => f y) hlin

/-! ## Lower bound: `m_(n)` is primitive for `n = 1` and `n` even -/

theorem mRow_primitive (n : ℕ) (hn : n = 1 ∨ Even n) (hpos : 0 < n) :
    IsPrimitive (mRow n).val := by
  unfold IsPrimitive
  rw [← sub_eq_zero]
  apply tensor_separation
  intro a b
  rw [map_sub, test_coproduct, map_add, tensorTest_tmul, tensorTest_tmul, pairing_mRow n hn hpos,
    phi_mul, quotientPairing_symm 1 a, quotientPairing_right_one, quotientPairing_symm 1 b,
    quotientPairing_right_one, quotientPairing_symm (mRow n).val a,
    quotientPairing_symm (mRow n).val b, pairing_mRow n hn hpos, pairing_mRow n hn hpos]
  ring

theorem smul_primitive {x : Q} (hx : IsPrimitive x) (c : ℤ) : IsPrimitive (c • x) := by
  unfold IsPrimitive at *
  rw [map_zsmul, hx, smul_add, ← TensorProduct.tmul_smul, ← TensorProduct.smul_tmul']

/-! ## Proposition 3.3 -/

/-- EK Prop 3.3, degrees `n = 1` and `n` even: primitives are exactly `ℤ ∙ m_(n)`. -/
theorem primitive_iff_span (n : ℕ) (hpos : 0 < n) (hn : n = 1 ∨ Even n) (x : degreePiece n) :
    IsPrimitive x.val ↔ x ∈ ℤ ∙ mRow n := by
  constructor
  · intro hx
    rw [primitive_upper hpos x hx]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  · intro hx
    obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hx
    exact smul_primitive (mRow_primitive n hn hpos) c

/-- EK Prop 3.3, odd degree `n ≥ 3`: the only primitive is `0`. -/
theorem primitive_iff_zero (n : ℕ) (hodd : Odd n) (h3 : 3 ≤ n) (x : degreePiece n) :
    IsPrimitive x.val ↔ x = 0 := by
  constructor
  · intro hx
    obtain ⟨k, rfl⟩ := hodd
    rw [primitive_upper (by omega) x hx, h_odd_orth (by omega) hx, zero_smul]
  · rintro rfl
    simp [IsPrimitive]

/-- EK1107.5610v2 Proposition 3.3, combined, on actual integral `Q`. -/
theorem proposition_3_3 (n : ℕ) (hpos : 1 ≤ n) (x : degreePiece n) :
    ((n = 1 ∨ Even n) → (IsPrimitive x.val ↔ x ∈ ℤ ∙ mBasis n (rowShape n))) ∧
    ((Odd n ∧ 3 ≤ n) → (IsPrimitive x.val ↔ x = 0)) :=
  ⟨fun hn => primitive_iff_span n hpos hn x, fun h => primitive_iff_zero n h.1 h.2 x⟩

/-- The one-row element is a literal `mBasis` member with the source's one-row pairing. -/
theorem mRow_spec (n : ℕ) (hpos : 0 < n) (ν : DegreeShape n) :
    quotientPairing (hPartition ν.val) (mRow n).val = if ν.val.rowLens = [n] then 1 else 0 := by
  rw [mRow, h_m]
  congr 1
  apply propext
  constructor
  · intro e; rw [e, rowShape_rows hpos]
  · exact eq_rowShape hpos ν

/-! ## `I² ∩ Λ_n` -/

/-- `I`: the two-sided ideal generated by all positive-degree homogeneous elements. -/
def posIdeal : TwoSidedIdeal Q := TwoSidedIdeal.span (⋃ d, ⋃ (_ : 0 < d), (degreePiece d : Set Q))

/-- `I²`: the additive span of all products `a * b` with `a, b ∈ I` (the ideal product). -/
def posIdealSq : Submodule ℤ Q :=
  Submodule.span ℤ (Set.image2 (· * ·) (posIdeal : Set Q) (posIdeal : Set Q))

theorem mul_mem_posIdealSq {a b : Q} (ha : a ∈ posIdeal) (hb : b ∈ posIdeal) :
    a * b ∈ posIdealSq :=
  Submodule.subset_span (Set.mem_image2_of_mem ha hb)

theorem degreePiece_le_posIdeal {d : ℕ} (hd : 0 < d) {x : Q} (hx : x ∈ degreePiece d) :
    x ∈ posIdeal :=
  TwoSidedIdeal.subset_span (Set.mem_iUnion₂.mpr ⟨d, hd, hx⟩)

theorem counit_posIdeal {x : Q} (hx : x ∈ posIdeal) : quotientCounit x = 0 := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨d, hd, hx⟩ := Set.mem_iUnion₂.mp hx
    exact counit_degree_pos hd hx
  | zero => simp
  | add u w _ _ hu hw => rw [map_add, hu, hw, add_zero]
  | neg u _ hu => rw [map_neg, hu, neg_zero]
  | left_absorb a u _ hu => rw [map_mul, hu, mul_zero]
  | right_absorb a u _ hu => rw [map_mul, hu, zero_mul]

theorem phi_posIdeal_sq (n : ℕ) (hn : n = 1 ∨ Even n) {x : Q} (hx : x ∈ posIdealSq) :
    phi n hn x = 0 := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨a, ha, b, hb, rfl⟩ := hx
    rw [phi_mul, counit_posIdeal ha, counit_posIdeal hb]; ring
  | zero => simp
  | add u w _ _ hu hw => rw [map_add, hu, hw, add_zero]
  | smul r u _ hu => rw [map_smul, hu, smul_zero]

/-- h-coordinates are pairings against the dual `m`-basis. -/
theorem hrepr_eq_pairing (n : ℕ) (x : degreePiece n) (μ : DegreeShape n) :
    (degreeHBasis n).repr x μ = quotientPairing x.val (mBasis n μ).val := by
  have e := congrArg (fun f : Module.Dual ℤ (degreePiece n) => f x)
    ((pairingEquiv n).apply_symm_apply ((degreeHBasis n).dualBasis μ))
  simp only [pairingEquiv_apply, Basis.dualBasis_apply] at e
  rw [← e]; rfl

theorem hcoord_row_of_sq (n : ℕ) (hpos : 0 < n) (hn : n = 1 ∨ Even n) (x : degreePiece n)
    (c : ℤ) (hc : c ≠ 0) (hx : c • x.val ∈ posIdealSq) :
    (degreeHBasis n).repr x (rowShape n) = 0 := by
  have h0 := phi_posIdeal_sq n hn hx
  rw [map_zsmul, ← pairing_mRow n hn hpos, smul_eq_mul] at h0
  rw [hrepr_eq_pairing]
  exact (mul_eq_zero.mp h0).resolve_left hc

/-- A complete word of at least two positive rows lies in `I²`. -/
theorem long_word_mem_sq (w : List ℕ) (hw : ∀ k ∈ w, 0 < k) (hl : 2 ≤ w.length) :
    (w.map h).prod ∈ posIdealSq := by
  match w, hl with
  | a :: b :: t, _ =>
    rw [List.map_cons, List.prod_cons]
    apply mul_mem_posIdealSq
    · exact degreePiece_le_posIdeal (hw a (by simp)) (h_mem_degreePiece (hw a (by simp)))
    · rw [List.map_cons, List.prod_cons]
      exact posIdeal.mul_mem_right _ _
        (degreePiece_le_posIdeal (hw b (by simp)) (h_mem_degreePiece (hw b (by simp))))

theorem hPartition_long_mem_sq (μ : YoungDiagram) (hl : 2 ≤ μ.rowLens.length) :
    hPartition μ ∈ posIdealSq :=
  long_word_mem_sq _ μ.pos_of_mem_rowLens hl

/-- The span of `h_λ`, `λ ⊢ n`, `λ ≠ (n)`, inside `Λ_n`. -/
def nonRowSpan (n : ℕ) : Submodule ℤ (degreePiece n) :=
  Submodule.span ℤ (degreeHBasis n '' {μ | μ ≠ rowShape n})

theorem nonRowSpan_iff (n : ℕ) (x : degreePiece n) :
    x ∈ nonRowSpan n ↔ (degreeHBasis n).repr x (rowShape n) = 0 := by
  rw [nonRowSpan, Basis.mem_span_image]
  constructor
  · intro hs
    by_contra hne
    exact hs (Finsupp.mem_support_iff.mpr hne) rfl
  · intro h0 μ hμ
    change μ ≠ rowShape n
    rintro rfl
    exact (Finsupp.mem_support_iff.mp hμ) h0

theorem nonRowSpan_le_sq (n : ℕ) (hpos : 0 < n) (x : degreePiece n) (hx : x ∈ nonRowSpan n) :
    x.val ∈ posIdealSq := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨μ, hμ, rfl⟩ := hy
    rw [degreeHBasis_apply]
    rcases shape_cases hpos μ with hr | hr
    · exact absurd (eq_rowShape hpos μ hr) hμ
    · exact hPartition_long_mem_sq μ.val hr
  | zero => exact Submodule.zero_mem _
  | add u w _ _ hu hw => exact Submodule.add_mem _ hu hw
  | smul r u _ hu =>
    rw [Submodule.coe_smul]
    exact Submodule.smul_of_tower_mem _ r hu

/-- `I² ∩ Λ_1 = 0`, integrally and after saturation. -/
theorem sq_degree_one (x : degreePiece 1) (c : ℤ) (hc : c ≠ 0)
    (hx : c • x.val ∈ posIdealSq) : x = 0 := by
  have h0 := hcoord_row_of_sq 1 (by norm_num) (Or.inl rfl) x c hc hx
  apply (degreeHBasis 1).repr.injective
  ext μ
  rw [map_zero, Finsupp.zero_apply]
  have : μ = rowShape 1 := by
    rcases shape_cases (by norm_num) μ with hr | hr
    · exact eq_rowShape (by norm_num) μ hr
    · have hs := (rowLens_sum μ.val).trans μ.property
      have hp := μ.val.pos_of_mem_rowLens
      cases he : μ.val.rowLens with
      | nil => simp [he] at hr
      | cons a t =>
        cases t with
        | nil => simp [he] at hr
        | cons b t =>
          rw [he] at hs hp
          have ha := hp a (by simp); have hb := hp b (by simp)
          simp only [List.sum_cons] at hs; omega
  rw [this]; exact h0

theorem sq_degree_one_iff (x : degreePiece 1) : x.val ∈ posIdealSq ↔ x = 0 := by
  constructor
  · intro hx; exact sq_degree_one x 1 one_ne_zero (by rwa [one_smul])
  · rintro rfl; exact Submodule.zero_mem _

/-- Even degree: `I² ∩ Λ_n = span {h_λ : λ ≠ (n)}` integrally. -/
theorem sq_even_iff (n : ℕ) (hpos : 0 < n) (he : Even n) (x : degreePiece n) :
    x.val ∈ posIdealSq ↔ x ∈ nonRowSpan n := by
  constructor
  · intro hx
    rw [nonRowSpan_iff]
    exact hcoord_row_of_sq n hpos (Or.inr he) x 1 one_ne_zero (by rwa [one_smul])
  · exact nonRowSpan_le_sq n hpos x

/-- Even degree, saturated form (the statement after `⊗ ℚ`). -/
theorem sq_even_saturated_iff (n : ℕ) (hpos : 0 < n) (he : Even n) (x : degreePiece n) :
    (∃ c : ℤ, c ≠ 0 ∧ c • x.val ∈ posIdealSq) ↔ x ∈ nonRowSpan n := by
  constructor
  · rintro ⟨c, hc, hx⟩
    rw [nonRowSpan_iff]
    exact hcoord_row_of_sq n hpos (Or.inr he) x c hc hx
  · intro hx
    exact ⟨1, one_ne_zero, by rw [one_smul]; exact nonRowSpan_le_sq n hpos x hx⟩

/-- Odd degree `n ≥ 3`: `2 • Λ_n ⊆ I²`, i.e. `I² ∩ Λ_n` is everything after `⊗ ℚ`. -/
theorem sq_odd_two_smul (n : ℕ) (hodd : Odd n) (h3 : 3 ≤ n) (x : degreePiece n) :
    (2 : ℤ) • x.val ∈ posIdealSq := by
  obtain ⟨k, rfl⟩ := hodd
  have hpos : 0 < 2 * k + 1 := by omega
  have hsum := congrArg Subtype.val ((degreeHBasis (2 * k + 1)).sum_repr x)
  rw [← hsum, Submodule.coe_sum, Finset.smul_sum]
  apply Submodule.sum_mem
  intro μ _
  rw [Submodule.coe_smul, degreeHBasis_apply, smul_comm]
  apply Submodule.smul_of_tower_mem
  rcases shape_cases hpos μ with hr | hr
  · have : hPartition μ.val = h (2 * k + 1) := by simp [hPartition, hr]
    rw [this, ← EKQuotientRelations.complete_one_even k]
    have h1 : h 1 ∈ posIdeal := degreePiece_le_posIdeal (by norm_num) (h_mem_degreePiece (by norm_num))
    have h2 : h (2 * k) ∈ posIdeal :=
      degreePiece_le_posIdeal (by omega) (h_mem_degreePiece (by omega))
    exact Submodule.add_mem _ (mul_mem_posIdealSq h1 h2) (mul_mem_posIdealSq h2 h1)
  · exact Submodule.smul_mem _ _ (hPartition_long_mem_sq μ.val hr)

theorem sq_odd_saturated (n : ℕ) (hodd : Odd n) (h3 : 3 ≤ n) (x : degreePiece n) :
    ∃ c : ℤ, c ≠ 0 ∧ c • x.val ∈ posIdealSq :=
  ⟨2, by norm_num, sq_odd_two_smul n hodd h3 x⟩

end OddMath.Frontier.EKPrimitives
