import OddMath.Frontier.EKRestCenterIndep
import OddMath.Frontier.OddSymmetricLimit
import OddMath.Frontier.CenterCorrected
import OddMath.Frontier.EKCoideal
import Mathlib.Data.Fin.Tuple.Sort

/-! # The centre of `Λ` is the polynomial algebra on the `p_{2k}`

EK arXiv:1107.5610v2, §3.2, p. 26: "In fact, the center (which coincides with the supercenter)
is precisely the polynomial algebra generated by the `p_{2k}`'s. This will follow from the
results of [5]." §3.2 assumes the base ring is a field of characteristic `0`.

Here, integrally at q = -1 in the radical quotient `Q` (`p_n = m_n = EKCenterPower.p n`):

* `center_iff`: `z` is central iff `c • z ∈ ℤ[p₂, p₄, …]` for some integer `c ≠ 0`;
* `EKRestCenterIndep.algebraicIndependent_p`: the `p_{2k}` are algebraically independent.

Since `Λ_ℤ` is torsion-free, these two statements say that the centre of `Λ_ℤ ⊗ ℚ` is the
polynomial algebra `ℚ[p₂, p₄, …]`; this is `EKRestCenterQ.centerQ_iff` and
`EKRestCenterQ.algebraicIndependent_pQ`. The saturation `c` cannot be dropped over `ℤ`: see
`EKRestCenterZ.center_ne_pAlg`. The supercentre is treated in `EKRestSuperCenter`.

Route (via [5] = EKL, as the paper indicates). For a central `z` of degree `d`, the image of
`z` in `OΛ_N`, `N` even and `N ≥ d`, is central (`OddSymmetricLimit.piA_surjective`), hence a
symmetric polynomial in the squares `x_i²` (`CenterCorrected.center_oddSymmetric`). Such a
polynomial is determined by its coefficients at the exponents `2λ`, `λ ⊢ d/2` (sorting), and
`π_N` is injective in degree `d` (`OddSymmetricLimit.degreeMap_injective`). So the central part
of `Λ_d` embeds in `ℤ^{p(d/2)}`, while the `p_{2λ}`, `λ ⊢ d/2`, are `p(d/2)` independent central
elements of degree `d`.
-/

noncomputable section
open scoped BigOperators

namespace OddMath.Frontier.EKRest
open EKRadicalQuotient EKIntegralBases DegreeShapes
open EKPartitionSpanning (hPartition)
open OddMath.SkewPolynomial (SkewPolynomial)

local instance (d : ℕ) : Fintype (DegreeShape d) := degreeFintype d

/-! ## Homogeneous components of central elements are central -/

theorem decompose_mul_right (x y : Q) {k : ℕ} (hy : y ∈ degreePiece k) (d : ℕ) :
    decompose (x * y) (d + k) = decompose x d * y := by
  classical
  conv_lhs => rw [← recompose_decompose x]
  rw [recompose_apply, Finsupp.sum, Finset.sum_mul, map_sum, Finsupp.finset_sum_apply]
  rw [Finset.sum_congr rfl (fun d' _ => by
    rw [decompose_piece (degreePiece_mul (decompose_mem x d') hy)])]
  simp only [Finsupp.single_apply, add_left_inj]
  rw [Finset.sum_ite_eq']
  split_ifs with h
  · rfl
  · rw [Finsupp.not_mem_support_iff.mp h, zero_mul]

theorem decompose_mul_left (x y : Q) {k : ℕ} (hy : y ∈ degreePiece k) (d : ℕ) :
    decompose (y * x) (k + d) = y * decompose x d := by
  classical
  conv_lhs => rw [← recompose_decompose x]
  rw [recompose_apply, Finsupp.sum, Finset.mul_sum, map_sum, Finsupp.finset_sum_apply]
  rw [Finset.sum_congr rfl (fun d' _ => by
    rw [decompose_piece (degreePiece_mul hy (decompose_mem x d'))])]
  simp only [Finsupp.single_apply, add_right_inj]
  rw [Finset.sum_ite_eq']
  split_ifs with h
  · rfl
  · rw [Finsupp.not_mem_support_iff.mp h, mul_zero]

theorem hPartition_mem' (μ : YoungDiagram) : hPartition μ ∈ degreePiece μ.card := by
  have := (degreeHBasis μ.card ⟨μ, rfl⟩).property
  rwa [degreeHBasis_apply] at this

/-- An element commuting with every `h_μ` is central. -/
theorem central_of_hPartition {z : Q} (h : ∀ μ, z * hPartition μ = hPartition μ * z) :
    z ∈ Subring.center Q := by
  rw [Subring.mem_center_iff]
  intro y
  induction y using EKPairingAdjoint.basis_induction hBasis with
  | hz => simp
  | ha x y hx hy => rw [mul_add, add_mul, hx, hy]
  | hb μ r => rw [hBasis_apply, smul_mul_assoc, mul_smul_comm, h μ]

/-- The homogeneous components of a central element are central. -/
theorem decompose_central {z : Q} (hz : z ∈ Subring.center Q) (d : ℕ) :
    decompose z d ∈ Subring.center Q := by
  apply central_of_hPartition
  intro μ
  have hc := (Subring.mem_center_iff.mp hz) (hPartition μ)
  have h1 := decompose_mul_right z (hPartition μ) (hPartition_mem' μ) d
  have h2 := decompose_mul_left z (hPartition μ) (hPartition_mem' μ) d
  rw [← h1, add_comm, ← h2, hc]

/-! ## Antitone exponent vectors are partitions -/

theorem antitone_getD {N : ℕ} (f : Fin N → ℕ) (hf : Antitone f) (j : Fin N) :
    f j = ((List.ofFn f).filter (· ≠ 0)).getD j 0 := by
  induction N with
  | zero => exact j.elim0
  | succ N ih =>
    rw [List.ofFn_succ]
    by_cases h0 : f 0 = 0
    · have hall : ∀ i, f i = 0 := fun i => by have := hf (Fin.zero_le i); omega
      have hnil : ((List.ofFn fun i : Fin N => f i.succ).filter (· ≠ 0)) = [] := by
        rw [List.filter_eq_nil_iff]; intro a ha
        obtain ⟨i, rfl⟩ := List.mem_ofFn.mp ha
        simp [hall]
      rw [List.filter_cons_of_neg (by simp [h0]), hnil, hall j]
      simp
    · rw [List.filter_cons_of_pos (by simpa using h0)]
      refine Fin.cases ?_ (fun i => ?_) j
      · simp
      · have := ih (fun i => f i.succ) (fun a b hab => hf (Fin.succ_le_succ_iff.mpr hab)) i
        simp only [Fin.val_succ, List.getD_cons_succ]
        exact this

/-- The partition of the nonzero entries of an antitone exponent vector. -/
def partOf {N : ℕ} (f : Fin N → ℕ) (hf : Antitone f) : YoungDiagram :=
  YoungDiagram.ofRowLens ((List.ofFn f).filter (· ≠ 0))
    ((List.sorted_ge_ofFn_iff.mpr hf).filter _)

theorem partOf_rowLens {N : ℕ} (f : Fin N → ℕ) (hf : Antitone f) :
    (partOf f hf).rowLens = (List.ofFn f).filter (· ≠ 0) :=
  YoungDiagram.rowLens_ofRowLens_eq_self (fun x hx => by
    have := (List.mem_filter.mp hx).2; simp at this; omega)

theorem sum_filter_ne_zero (l : List ℕ) : (l.filter (· ≠ 0)).sum = l.sum := by
  induction l with
  | nil => rfl
  | cons a l ih =>
    by_cases ha : a = 0
    · rw [List.filter_cons_of_neg (by simp [ha]), ih, ha]; simp
    · rw [List.filter_cons_of_pos (by simpa using ha), List.sum_cons, List.sum_cons, ih]

theorem partOf_card {N : ℕ} (f : Fin N → ℕ) (hf : Antitone f) :
    (partOf f hf).card = ∑ i, f i := by
  rw [partOf, EKPartitionSpanning.card_ofRowLens, sum_filter_ne_zero, List.sum_ofFn]

/-! ## Central elements of even degree are determined by `2λ`-coefficients -/

open OddLREKIdentification (piN)
open OddSymmetricLimit (piA piA_surjective piA_coe)

/-- The exponent `2λ` in `N = 2m + 2` variables. -/
def twoExp (m : ℕ) (μ : YoungDiagram) : Fin (2 * m + 2) → ℕ := fun j => 2 * μ.rowLens.getD j 0

/-- `x ↦ (coefficient of x^{2λ} in π_N(x))_{λ ⊢ m}`, `N = 2m + 2`. -/
def Psi (m : ℕ) : degreePiece (2 * m) →ₗ[ℤ] (DegreeShape m → ℤ) where
  toFun x μ := piN (2 * m + 2) (x : Q) (twoExp m μ.val)
  map_add' x y := by funext μ; simp
  map_smul' c x := by
    funext μ
    simp only [Submodule.coe_smul, map_zsmul, Finsupp.smul_apply, smul_eq_mul, RingHom.id_apply,
      Pi.smul_apply]

theorem piA_central {n : ℕ} {x : Q} (hx : x ∈ Subring.center Q) :
    piA n x ∈ Subring.center (OddSymmetricKernel.kernelSubring n) := by
  rw [Subring.mem_center_iff]
  intro g
  obtain ⟨y, rfl⟩ := piA_surjective n g
  rw [← map_mul, ← map_mul, (Subring.mem_center_iff.mp hx) y]

theorem piN_mem_sq (m : ℕ) {x : Q} (hx : x ∈ Subring.center Q) :
    piN (2 * m + 2) x ∈ CenterPoly.sq (2 * m) := by
  obtain ⟨a, ha, b, _, heq⟩ :=
    (CenterCorrected.center_oddSymmetric (2 * m) (piA (2 * m) x)).mp (piA_central hx)
  have hodd : ¬ Odd (2 * m + 2) := by
    rw [Nat.not_odd_iff_even]; exact ⟨m + 1, by ring⟩
  rw [if_neg hodd, add_zero, piA_coe] at heq
  rw [heq]; exact ha

/-- A central element of degree `2m` with vanishing `Psi` is zero. -/
theorem eq_zero_of_Psi (m : ℕ) (x : degreePiece (2 * m)) (hx : (x : Q) ∈ Subring.center Q)
    (h0 : Psi m x = 0) : x = 0 := by
  classical
  obtain ⟨P, hPsym, hPx⟩ := (CenterPoly.mem_sq _).mp (piN_mem_sq m hx)
  have hsym : ∀ τ : Equiv.Perm (Fin (2 * m + 2)), MvPolynomial.rename τ P = P :=
    (MvPolynomial.mem_symmetricSubalgebra P).mp hPsym
  have hP0 : P = 0 := by
    ext e
    rw [MvPolynomial.coeff_zero, ← CenterPoly.squareHom_apply_dbl, hPx]
    by_cases hw : ElementaryBasis.weight (CenterPoly.dbl e) = 2 * m
    · let f : Fin (2 * m + 2) → ℕ := fun j => e j
      let τ : Equiv.Perm (Fin (2 * m + 2)) := Tuple.sort f * Fin.revPerm
      have hg : Antitone (f ∘ τ) := by
        intro a b hab
        have := Tuple.monotone_sort f (Fin.rev_le_rev.mpr hab)
        simpa [τ, Function.comp_def] using this
      let e' : Fin (2 * m + 2) →₀ ℕ := Finsupp.equivFunOnFinite.symm (f ∘ τ)
      have hmap : e'.mapDomain τ = e := by
        ext j
        rw [Finsupp.mapDomain_equiv_apply]
        simp [e', f]
      have hce : P.coeff e = P.coeff e' := by
        rw [← hmap, ← MvPolynomial.coeff_rename_mapDomain τ τ.injective P e', hsym τ]
      have hsum : ∑ i, (f ∘ τ) i = m := by
        show ∑ i, f (τ i) = m
        rw [Equiv.sum_comp τ f]
        have : ElementaryBasis.weight (CenterPoly.dbl e) = 2 * ∑ i, f i := by
          simp [ElementaryBasis.weight, CenterPoly.dbl, f, Finset.mul_sum]
        omega
      let μ : DegreeShape m := ⟨partOf (f ∘ τ) hg, by rw [partOf_card, hsum]⟩
      have hdbl : CenterPoly.dbl e' = twoExp m μ.val := by
        funext j
        simp only [CenterPoly.dbl, twoExp, μ, partOf_rowLens, e']
        rw [← antitone_getD (f ∘ τ) hg j]
        simp
      have := congrFun h0 μ
      simp only [Psi, LinearMap.coe_mk, AddHom.coe_mk, Pi.zero_apply] at this
      rw [← hPx, ← hdbl, CenterPoly.squareHom_apply_dbl, ← hce, ← CenterPoly.squareHom_apply_dbl,
        hPx] at this
      exact this
    · exact OddSymmetricLimit.piN_homogeneous (2 * m + 2) (2 * m) x _ hw
  have hpi : piN (2 * m + 2) (x : Q) = 0 := by rw [← hPx, hP0, map_zero]
  apply OddSymmetricLimit.degreeMap_injective (2 * m) (2 * m) (by omega)
  rw [map_zero]
  exact Subtype.ext hpi

/-- Central elements of odd degree vanish. -/
theorem eq_zero_of_odd (m : ℕ) (x : degreePiece (2 * m + 1)) (hx : (x : Q) ∈ Subring.center Q) :
    x = 0 := by
  classical
  obtain ⟨P, _, hPx⟩ := (CenterPoly.mem_sq _).mp (piN_mem_sq m hx)
  have hpi : piN (2 * m + 2) (x : Q) = 0 := by
    ext a
    rw [Finsupp.coe_zero, Pi.zero_apply]
    by_cases hw : ElementaryBasis.weight a = 2 * m + 1
    · have hodd : ∃ j, ¬ Even (a j) := by
        by_contra hall
        push_neg at hall
        have : Even (ElementaryBasis.weight a) := Finset.even_sum _ (fun j _ => hall j)
        rw [hw] at this
        exact Nat.not_even_two_mul_add_one m this
      obtain ⟨j, hj⟩ := hodd
      rw [← hPx]
      exact CenterPoly.squareHom_apply_of_not_even P a j hj
    · exact OddSymmetricLimit.piN_homogeneous (2 * m + 2) (2 * m + 1) x a hw
  apply OddSymmetricLimit.degreeMap_injective (2 * m) (2 * m + 1) (by omega)
  rw [map_zero]
  exact Subtype.ext hpi

/-! ## The saturation statement in one degree -/

theorem p_mem (k : ℕ) : EKCenterPower.p k ∈ degreePiece k :=
  (EKDualBases.mBasis k (EKCenterPower.rowShape k)).property

theorem pL_mem (l : List ℕ) : pL l ∈ degreePiece (2 * l.sum) := by
  induction l with
  | nil => exact unit_mem_degree_zero
  | cons a l ih =>
    rw [pL, List.map_cons, List.prod_cons, List.sum_cons, mul_add]
    exact degreePiece_mul (p_mem _) ih

theorem pP_mem (μ : YoungDiagram) : pP μ ∈ degreePiece (2 * μ.card) := by
  rw [← rowLens_sum]; exact pL_mem _

theorem pL_central (l : List ℕ) (hl : ∀ a ∈ l, 0 < a) : pL l ∈ Subring.center Q := by
  induction l with
  | nil => exact Subring.one_mem _
  | cons a l ih =>
    rw [pL, List.map_cons, List.prod_cons]
    obtain ⟨k, rfl⟩ : ∃ k, a = k + 1 := ⟨a - 1, by have := hl a (by simp); omega⟩
    exact Subring.mul_mem _ (p_even_central k) (ih (fun b hb => hl b (by simp [hb])))

theorem pP_central (μ : YoungDiagram) : pP μ ∈ Subring.center Q :=
  pL_central _ μ.pos_of_mem_rowLens

/-- **One degree.** A central element of degree `d` has a nonzero integer multiple in the
`ℤ`-span of the `p_{2λ}`, `2|λ| = d`. -/
theorem saturation_degree (d : ℕ) (z : Q) (hzd : z ∈ degreePiece d) (hz : z ∈ Subring.center Q) :
    ∃ c : ℤ, c ≠ 0 ∧ c • z ∈ Submodule.span ℤ (Set.range pP) := by
  classical
  obtain ⟨m, rfl | rfl⟩ := Nat.even_or_odd' d
  · let F : Option (DegreeShape m) → degreePiece (2 * m) := fun i =>
      match i with
      | none => ⟨z, hzd⟩
      | some μ => ⟨pP μ.val, by have := pP_mem μ.val; rwa [μ.property] at this⟩
    have hnot : ¬ LinearIndependent ℤ (Psi m ∘ F) := by
      intro hli
      have := hli.fintype_card_le_finrank
      rw [Module.finrank_fintype_fun_eq_card, Fintype.card_option] at this
      omega
    obtain ⟨g, hg, i0, hi0⟩ := Fintype.not_linearIndependent_iff.mp hnot
    have hw0 : ∑ i, g i • F i = 0 := by
      apply eq_zero_of_Psi m
      · rw [Submodule.coe_sum]
        apply Subring.sum_mem
        intro i _
        rw [Submodule.coe_smul]
        apply Subring.zsmul_mem
        cases i with
        | none => exact hz
        | some μ => exact pP_central μ.val
      · rw [map_sum]
        simpa only [map_zsmul, Function.comp_apply] using hg
    have hw : g none • z + ∑ μ : DegreeShape m, g (some μ) • pP μ.val = 0 := by
      rw [Fintype.sum_option] at hw0
      have := congrArg (fun w : degreePiece (2 * m) => (w : Q)) hw0
      simp only [Submodule.coe_add, Submodule.coe_sum, Submodule.coe_smul, Submodule.coe_zero,
        F] at this
      exact this
    have hnone : g none ≠ 0 := by
      intro h0
      rw [h0, zero_smul, zero_add] at hw
      have hli : LinearIndependent ℤ (fun μ : DegreeShape m => pP μ.val) :=
        pP_linearIndependent.comp _ Subtype.val_injective
      have hall := Fintype.linearIndependent_iff.mp hli (fun μ => g (some μ)) hw
      cases i0 with
      | none => exact hi0 h0
      | some μ => exact hi0 (hall μ)
    refine ⟨g none, hnone, ?_⟩
    rw [eq_neg_of_add_eq_zero_left hw]
    apply Submodule.neg_mem
    apply Submodule.sum_mem
    intro μ _
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨μ.val, rfl⟩)
  · refine ⟨1, one_ne_zero, ?_⟩
    have := eq_zero_of_odd m ⟨z, hzd⟩ hz
    rw [show z = 0 from congrArg Subtype.val this, smul_zero]
    exact Submodule.zero_mem _

/-! ## The centre -/

/-- `ℤ[p₂, p₄, …] ⊆ Q`, the subalgebra generated by the `p_{2k}`, `k ≥ 1`. -/
def pAlg : Subalgebra ℤ Q :=
  Algebra.adjoin ℤ (Set.range fun k : ℕ => EKCenterPower.p (2 * (k + 1)))

theorem pL_mem_pAlg (l : List ℕ) (hl : ∀ a ∈ l, 0 < a) : pL l ∈ pAlg := by
  apply Subalgebra.list_prod_mem
  intro x hx
  obtain ⟨a, ha, rfl⟩ := List.mem_map.mp hx
  obtain ⟨k, rfl⟩ : ∃ k, a = k + 1 := ⟨a - 1, by have := hl a ha; omega⟩
  exact Algebra.subset_adjoin ⟨k, rfl⟩

theorem pP_mem_pAlg (μ : YoungDiagram) : pP μ ∈ pAlg := pL_mem_pAlg _ μ.pos_of_mem_rowLens

theorem span_le_pAlg : Submodule.span ℤ (Set.range pP) ≤ Subalgebra.toSubmodule pAlg := by
  rw [Submodule.span_le]
  rintro _ ⟨μ, rfl⟩
  exact pP_mem_pAlg μ

theorem pAlg_central {x : Q} (hx : x ∈ pAlg) : x ∈ Subring.center Q := by
  have hle : pAlg ≤ Subalgebra.center ℤ Q := by
    apply Algebra.adjoin_le
    rintro _ ⟨k, rfl⟩
    rw [SetLike.mem_coe, Subalgebra.mem_center_iff]
    exact (Subring.mem_center_iff.mp (p_even_central k))
  have := hle hx
  rw [Subalgebra.mem_center_iff] at this
  exact Subring.mem_center_iff.mpr this

/-- **The centre of `Λ` (EK p. 26), integral form.** An element `z ∈ Λ_ℤ` is central if and
only if some nonzero integer multiple of `z` is a polynomial in the `p_{2k}` with integer
coefficients; more precisely an integer combination of the monomials `p_{2λ}`. -/
theorem center_iff_span (z : Q) :
    z ∈ Subring.center Q ↔ ∃ c : ℤ, c ≠ 0 ∧ c • z ∈ Submodule.span ℤ (Set.range pP) := by
  classical
  constructor
  · intro hz
    have hex : ∀ d, ∃ c : ℤ, c ≠ 0 ∧ c • decompose z d ∈ Submodule.span ℤ (Set.range pP) :=
      fun d => saturation_degree d _ (decompose_mem z d) (decompose_central hz d)
    choose cf hcf0 hcf using hex
    let S := (decompose z).support
    refine ⟨∏ d ∈ S, cf d, Finset.prod_ne_zero_iff.mpr (fun d _ => hcf0 d), ?_⟩
    have hz' : z = ∑ d ∈ S, decompose z d := by
      conv_lhs => rw [← recompose_decompose z]
      rfl
    rw [hz', Finset.smul_sum]
    apply Submodule.sum_mem
    intro d hd
    rw [← Finset.prod_erase_mul S cf hd, mul_smul]
    exact Submodule.smul_mem _ _ (hcf d)
  · rintro ⟨c, hc, hmem⟩
    have hcz := pAlg_central (span_le_pAlg hmem)
    rw [Subring.mem_center_iff] at hcz ⊢
    intro y
    have h := hcz y
    rw [mul_smul_comm, smul_mul_assoc, ← sub_eq_zero, ← smul_sub] at h
    exact sub_eq_zero.mp ((smul_eq_zero.mp h).resolve_left hc)

/-- **EK p. 26, the centre is `ℤ[p₂, p₄, …]` up to saturation:** `z` is central iff
`c • z ∈ ℤ[p₂, p₄, …]` for some integer `c ≠ 0`. Together with `algebraicIndependent_p`
(the `p_{2k}` are algebraically independent), this is the statement that the centre of
`Λ_ℤ ⊗ ℚ` is the polynomial algebra `ℚ[p₂, p₄, …]`. -/
theorem center_iff (z : Q) :
    z ∈ Subring.center Q ↔ ∃ c : ℤ, c ≠ 0 ∧ c • z ∈ pAlg := by
  constructor
  · intro hz
    obtain ⟨c, hc, hm⟩ := (center_iff_span z).mp hz
    exact ⟨c, hc, span_le_pAlg hm⟩
  · rintro ⟨c, hc, hmem⟩
    have hcz := pAlg_central hmem
    rw [Subring.mem_center_iff] at hcz ⊢
    intro y
    have h := hcz y
    rw [mul_smul_comm, smul_mul_assoc, ← sub_eq_zero, ← smul_sub] at h
    exact sub_eq_zero.mp ((smul_eq_zero.mp h).resolve_left hc)

/-- EK p. 26 (odd degrees): the centre has no nonzero homogeneous elements of odd degree. -/
theorem center_odd (m : ℕ) (z : Q) (hzd : z ∈ degreePiece (2 * m + 1))
    (hz : z ∈ Subring.center Q) : z = 0 :=
  congrArg Subtype.val (eq_zero_of_odd m ⟨z, hzd⟩ hz)

end OddMath.Frontier.EKRest
