import OddMath.Frontier.EKRestCenter
import OddMath.Frontier.EKRestData

/-! # Over `ℤ` the centre is larger than `ℤ[p₂, p₄, …]`

EK arXiv:1107.5610v2, §3.2 (p. 25: "For this section assume `k` is a field of characteristic
zero"; p. 26: the centre "is precisely the polynomial algebra generated by the `p_{2k}`'s").

The characteristic-zero hypothesis is needed: over `ℤ` (in the radical quotient `Q`, q = -1),
`x = -h₂₂ + 2h₄` is central, `2x = p₄ + p₂²`, but `x ∉ ℤ[p₂, p₄, …]` (`center_ne_pAlg`).
So `EKRest.center_iff` cannot drop its integer multiple `c`.

Proof that `x ∉ ℤ[p₂, p₄, …]`: every element of `ℤ[p₂, p₄, …]` is an integer combination of
products `p_{2l₁} ⋯ p_{2l_r}`, and the `h₂₂`-coefficient `(·, m₂₂)` of each such product is
even (`-2` for `p₄`, `0` for `p₂²`, `0` in other degrees), while that of `x` is `-1`.
-/

noncomputable section
open scoped BigOperators

namespace OddMath.Frontier.EKRest
open EKRadicalQuotient EKIntegralBases DegreeShapes EKAppendixData EKDualBases

/-- The integer span of all products `p_{2l₁} ⋯ p_{2l_r}`, `lᵢ ≥ 1`. -/
def plSpan : Submodule ℤ Q := Submodule.span ℤ {y | ∃ l : List ℕ, (∀ a ∈ l, 0 < a) ∧ pL l = y}

theorem pL_mem_plSpan (l : List ℕ) (hl : ∀ a ∈ l, 0 < a) : pL l ∈ plSpan :=
  Submodule.subset_span ⟨l, hl, rfl⟩

theorem plSpan_mul {x y : Q} (hx : x ∈ plSpan) (hy : y ∈ plSpan) : x * y ∈ plSpan := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨l, hl, rfl⟩ := hx
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨l', hl', rfl⟩ := hy
      have : pL l * pL l' = pL (l ++ l') := by rw [pL, pL, pL, List.map_append, List.prod_append]
      rw [this]
      exact pL_mem_plSpan _ (fun a ha => by
        rcases List.mem_append.mp ha with h | h
        · exact hl a h
        · exact hl' a h)
    | zero => simp
    | add a b _ _ ha hb => rw [mul_add]; exact Submodule.add_mem _ ha hb
    | smul c a _ ha => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ ha
  | zero => simp
  | add a b _ _ ha hb => rw [add_mul]; exact Submodule.add_mem _ ha hb
  | smul c a _ ha => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ ha

theorem pAlg_le_plSpan {x : Q} (hx : x ∈ pAlg) : x ∈ plSpan := by
  induction hx using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    show EKCenterPower.p (2 * (k + 1)) ∈ plSpan
    have : EKCenterPower.p (2 * (k + 1)) = pL [k + 1] := by simp [pL]
    rw [this]; exact pL_mem_plSpan _ (by simp)
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one]
    exact Submodule.smul_mem _ _ (pL_mem_plSpan [] (by simp))
  | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
  | mul x y _ _ hx hy => exact plSpan_mul hx hy

/-- The `h₂₂`-coefficient functional `y ↦ (y, m₂₂)` in degree 4. -/
def phi22 : Q →ₗ[ℤ] ℤ := quotientPairing.flip (mBasis 4 (hshapes4 2)).val

theorem phi22_hshape (j : Fin 5) : phi22 (EKPartitionSpanning.hPartition (hshapes4 j).val) =
    if j = 2 then 1 else 0 := by
  rw [phi22, LinearMap.flip_apply, h_m]
  by_cases hj : j = 2
  · subst hj; simp
  · rw [if_neg (fun h => hj (inj4 h)), if_neg hj]

theorem p_two_sq : EKCenterPower.p 2 = EKElementaryQuotient.h 1 * EKElementaryQuotient.h 1 :=
  EKCenterPowerControls.p2_fixture

theorem p_four_expansion : EKCenterPower.p 4 = -(hP [1,1,1,1]) - (2 : ℤ) • hP [2,2] +
    (4 : ℤ) • hP [4] := by
  have h := mBasis_val hshapes4 pl4 hs4 _ _ mExp4_4
  rw [EKCenterPower.p, show EKCenterPower.rowShape 4 = hshapes4 4 from Subtype.ext rfl, h]
  simp [Fin.sum_univ_succ, pl4]
  abel

theorem phi22_hP (j : Fin 5) : phi22 (hP (pl4 j)) = if j = 2 then 1 else 0 := by
  rw [← hPartition_eq_hP hshapes4 pl4 hs4, phi22_hshape]

theorem phi22_1111 : phi22 (hP [1,1,1,1]) = 0 := by
  rw [show hP [1,1,1,1] = hP (pl4 0) from rfl, phi22_hP]; simp
theorem phi22_22 : phi22 (hP [2,2]) = 1 := by
  rw [show hP [2,2] = hP (pl4 2) from rfl, phi22_hP]; simp
theorem phi22_4 : phi22 (hP [4]) = 0 := by
  rw [show hP [4] = hP (pl4 4) from rfl, phi22_hP]; simp

theorem phi22_pL_even (l : List ℕ) (hl : ∀ a ∈ l, 0 < a) : 2 ∣ phi22 (pL l) := by
  by_cases hs : l.sum = 2
  · rcases l with _ | ⟨a, _ | ⟨b, _ | ⟨c, t⟩⟩⟩
    · simp at hs
    · simp at hs; subst hs
      rw [show pL [2] = EKCenterPower.p 4 by simp [pL], p_four_expansion, map_add, map_sub,
        map_neg, map_zsmul, map_zsmul, phi22_1111, phi22_22, phi22_4]
      norm_num
    · have ha := hl a (by simp); have hb := hl b (by simp)
      simp at hs
      obtain ⟨rfl, rfl⟩ : a = 1 ∧ b = 1 := by omega
      rw [show pL [1, 1] = hP [1,1,1,1] by simp [pL, hP, p_two_sq, mul_assoc], phi22_1111]
      exact dvd_zero 2
    · have ha := hl a (by simp); have hb := hl b (by simp); have hc := hl c (by simp)
      simp at hs; omega
  · rw [phi22, LinearMap.flip_apply,
      EKCenterPower.orth (by omega) (pL_mem l) (mBasis 4 (hshapes4 2)).property]
    exact dvd_zero 2

theorem phi22_even {y : Q} (hy : y ∈ plSpan) : 2 ∣ phi22 y := by
  induction hy using Submodule.span_induction with
  | mem y hy => obtain ⟨l, hl, rfl⟩ := hy; exact phi22_pL_even l hl
  | zero => simp
  | add a b _ _ ha hb => rw [map_add]; exact dvd_add ha hb
  | smul c a _ ha => rw [map_zsmul, smul_eq_mul]; exact dvd_mul_of_dvd_right ha c

/-- The central element `-h₂₂ + 2h₄`. -/
def xZ : Q := -(hP [2,2]) + (2 : ℤ) • hP [4]

theorem two_xZ : (2 : ℤ) • xZ = EKCenterPower.p 4 + EKCenterPower.p 2 * EKCenterPower.p 2 := by
  rw [p_four_expansion, p_two_sq, xZ]
  have : EKElementaryQuotient.h 1 * EKElementaryQuotient.h 1 *
      (EKElementaryQuotient.h 1 * EKElementaryQuotient.h 1) = hP [1,1,1,1] := by
    simp [hP, mul_assoc]
  rw [this, smul_add, smul_neg, smul_smul]
  abel

theorem xZ_central : xZ ∈ Subring.center Q := by
  rw [center_iff]
  refine ⟨2, by norm_num, ?_⟩
  rw [two_xZ]
  apply Subalgebra.add_mem
  · exact Algebra.subset_adjoin ⟨1, rfl⟩
  · exact Subalgebra.mul_mem _ (Algebra.subset_adjoin ⟨0, rfl⟩) (Algebra.subset_adjoin ⟨0, rfl⟩)

theorem xZ_not_mem : xZ ∉ pAlg := by
  intro h
  have := phi22_even (pAlg_le_plSpan h)
  rw [xZ, map_add, map_neg, map_zsmul, phi22_22, phi22_4] at this
  norm_num at this

/-- **Over `ℤ`, the centre is strictly larger than `ℤ[p₂, p₄, …]`.** -/
theorem center_ne_pAlg : ∃ x : Q, x ∈ Subring.center Q ∧ x ∉ pAlg ∧ (2 : ℤ) • x ∈ pAlg :=
  ⟨xZ, xZ_central, xZ_not_mem, by
    rw [two_xZ]
    apply Subalgebra.add_mem
    · exact Algebra.subset_adjoin ⟨1, rfl⟩
    · exact Subalgebra.mul_mem _ (Algebra.subset_adjoin ⟨0, rfl⟩) (Algebra.subset_adjoin ⟨0, rfl⟩)⟩

end OddMath.Frontier.EKRest
