import OddMath.Frontier.EKRestCenter
import Mathlib.RingTheory.Localization.BaseChange
import Mathlib.RingTheory.Localization.Module

/-! # The centre of `Λ_ℚ = ℚ ⊗ Λ_ℤ` is the polynomial algebra `ℚ[p₂, p₄, …]`

EK arXiv:1107.5610v2, §3.2 (base field of characteristic `0`, p. 25), p. 26: "the center …
is precisely the polynomial algebra generated by the `p_{2k}`'s".

With `LQ = ℚ ⊗[ℤ] Q` (`Q` the integral radical quotient at q = -1) and `ι x = 1 ⊗ x`:

* `centerQ_iff`: `w ∈ Z(LQ) ↔ w ∈ ℚ[ι p₂, ι p₄, …]` (`Algebra.adjoin`);
* `algebraicIndependent_pQ`: the `ι p_{2k}` are algebraically independent over `ℚ`.

`LQ` is the rationalisation of `Λ_ℤ`; its identification with the quotient of `Λ′_ℚ` by the
radical of the form (the paper's `Λ` over `ℚ`) is a base-change statement not proved here.
-/

noncomputable section
set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 400000
open scoped BigOperators TensorProduct

namespace OddMath.Frontier.EKRest
open EKRadicalQuotient EKIntegralBases

/-- `Λ_ℚ = ℚ ⊗ Λ_ℤ`. -/
abbrev LQ := ℚ ⊗[ℤ] Q

/-- `x ↦ 1 ⊗ x`. -/
def iota : Q →ₐ[ℤ] LQ := Algebra.TensorProduct.includeRight

theorem iota_apply (x : Q) : iota x = (1 : ℚ) ⊗ₜ[ℤ] x := rfl

instance : IsLocalizedModule (nonZeroDivisors ℤ) (TensorProduct.mk ℤ ℚ Q 1) :=
  IsLocalization.tensorProduct_isLocalizedModule (M := Q) (nonZeroDivisors ℤ) ℚ

theorem iota_surj (w : LQ) : ∃ x : Q, ∃ s : ℤ, s ≠ 0 ∧ (s : ℚ) • w = iota x := by
  obtain ⟨⟨x, s⟩, h⟩ := IsLocalizedModule.surj (nonZeroDivisors ℤ) (TensorProduct.mk ℤ ℚ Q 1) w
  refine ⟨x, s, nonZeroDivisors.coe_ne_zero s, ?_⟩
  rw [Submonoid.smul_def, ← Int.cast_smul_eq_zsmul ℚ] at h
  exact h

theorem iota_injective : Function.Injective iota := by
  intro x y h
  obtain ⟨c, hc⟩ := IsLocalizedModule.exists_of_eq (S := nonZeroDivisors ℤ)
    (f := TensorProduct.mk ℤ ℚ Q 1) (x₁ := x) (x₂ := y) h
  rw [Submonoid.smul_def, Submonoid.smul_def, ← sub_eq_zero, ← smul_sub] at hc
  exact sub_eq_zero.mp ((smul_eq_zero.mp hc).resolve_left (nonZeroDivisors.coe_ne_zero c))

/-- The subalgebra `ℚ[p₂, p₄, …]` of `LQ`. -/
def pAlgQ : Subalgebra ℚ LQ :=
  Algebra.adjoin ℚ (Set.range fun k : ℕ => iota (EKCenterPower.p (2 * (k + 1))))

theorem smul_cancel {s : ℤ} (hs : s ≠ 0) {v : LQ} (h : (s : ℚ) • v = 0) : v = 0 := by
  have := congrArg (fun z : LQ => ((s : ℚ)⁻¹) • z) h
  simp only [smul_smul, smul_zero] at this
  rwa [inv_mul_cancel₀ (by exact_mod_cast hs), one_smul] at this

theorem iota_central {x : Q} (hx : x ∈ Subring.center Q) (w : LQ) : iota x * w = w * iota x := by
  obtain ⟨y, s, hs, hy⟩ := iota_surj w
  have h1 : (s : ℚ) • (iota x * w - w * iota x) = 0 := by
    rw [smul_sub, ← mul_smul_comm, ← smul_mul_assoc, hy, ← map_mul, ← map_mul,
      (Subring.mem_center_iff.mp hx y), sub_self]
  exact sub_eq_zero.mp (smul_cancel hs h1)

theorem central_of_iota {x : Q} (hx : iota x ∈ Subalgebra.center ℚ LQ) : x ∈ Subring.center Q := by
  rw [Subring.mem_center_iff]
  intro y
  apply iota_injective
  rw [map_mul, map_mul]
  exact (Subalgebra.mem_center_iff.mp hx (iota y))

/-- **EK p. 26 over `ℚ`:** the centre of `Λ_ℚ` is `ℚ[p₂, p₄, …]`. -/
theorem centerQ_iff (w : LQ) : w ∈ Subalgebra.center ℚ LQ ↔ w ∈ pAlgQ := by
  constructor
  · intro hw
    obtain ⟨x, s, hs, hxs⟩ := iota_surj w
    have hx : x ∈ Subring.center Q := by
      apply central_of_iota
      rw [← hxs]
      exact Subalgebra.smul_mem _ hw _
    obtain ⟨c, hc, hcx⟩ := (center_iff x).mp hx
    have hmem : iota (c • x) ∈ pAlgQ := by
      have hle : pAlg.map iota ≤ pAlgQ.restrictScalars ℤ := by
        rw [pAlg, AlgHom.map_adjoin]
        apply Algebra.adjoin_le
        rintro _ ⟨_, ⟨k, rfl⟩, rfl⟩
        exact Algebra.subset_adjoin ⟨k, rfl⟩
      exact hle ⟨c • x, hcx, rfl⟩
    have hw' : w = (((c : ℚ) * s)⁻¹) • iota (c • x) := by
      have hc' : (c : ℚ) ≠ 0 := by exact_mod_cast hc
      have hs' : (s : ℚ) ≠ 0 := by exact_mod_cast hs
      rw [map_zsmul, ← Int.cast_smul_eq_zsmul ℚ, ← hxs, smul_smul, smul_smul,
        show ((c : ℚ) * s)⁻¹ * c * s = 1 by field_simp, one_smul]
    rw [hw']
    exact Subalgebra.smul_mem _ hmem _
  · intro hw
    have hle : pAlgQ ≤ Subalgebra.center ℚ LQ := by
      apply Algebra.adjoin_le
      rintro _ ⟨k, rfl⟩
      rw [SetLike.mem_coe, Subalgebra.mem_center_iff]
      intro g
      exact (iota_central (p_even_central k) g).symm
    exact hle hw

/-- `ι p_{2(k+1)}` in the centre of `LQ`. -/
def pcQ (k : ℕ) : Subalgebra.center ℚ LQ :=
  ⟨iota (EKCenterPower.p (2 * (k + 1))), by
    rw [Subalgebra.mem_center_iff]; intro g; exact (iota_central (p_even_central k) g).symm⟩

/-- `ι` restricted to centres. -/
def iotaC : Subring.center Q →* Subalgebra.center ℚ LQ where
  toFun z := ⟨iota z, by
    rw [Subalgebra.mem_center_iff]; intro g; exact (iota_central z.2 g).symm⟩
  map_one' := by apply Subtype.ext; simp
  map_mul' a b := by apply Subtype.ext; simp

theorem monomialQ_coe (s : ℕ →₀ ℕ) :
    ((s.prod fun k n => pcQ k ^ n : Subalgebra.center ℚ LQ) : LQ) = iota (pP (shapeOf s)) := by
  have h : (s.prod fun k n => pcQ k ^ n) = iotaC (s.prod fun k n => pc k ^ n) := by
    rw [map_finsuppProd]
    simp only [map_pow]
    rfl
  rw [h, ← monomial_coe]
  rfl

/-- **The `p_{2k}` are algebraically independent over `ℚ`** (in the centre of `Λ_ℚ`). -/
theorem algebraicIndependent_pQ : AlgebraicIndependent ℚ pcQ := by
  classical
  rw [algebraicIndependent_iff]
  intro P hP
  have hli : LinearIndependent ℚ (fun s : ℕ →₀ ℕ => iota (pP (shapeOf s))) :=
    LinearIndependent.of_isLocalizedModule ℚ (nonZeroDivisors ℤ) (TensorProduct.mk ℤ ℚ Q 1)
      (pP_linearIndependent.comp shapeOf shapeOf_injective)
  have hsum : ∑ s ∈ P.support, P.coeff s • iota (pP (shapeOf s)) = 0 := by
    have h := congrArg (fun z : Subalgebra.center ℚ LQ => (z : LQ)) hP
    simp only at h
    rw [P.as_sum, map_sum, ZeroMemClass.coe_zero] at h
    simp only [MvPolynomial.aeval_monomial] at h
    rw [← h]
    push_cast
    apply Finset.sum_congr rfl
    intro s _
    rw [← monomialQ_coe, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
  ext s
  by_cases hs : s ∈ P.support
  · exact linearIndependent_iff'.mp hli P.support (fun s => P.coeff s) hsum s hs
  · simpa using hs

end OddMath.Frontier.EKRest
