import OddMath.Frontier.EKRskSignControls
import OddMath.Frontier.EKRskSign

/-! Axiom audit: every owned declaration of the Controls and production
modules.  Expected: only `propext`, `Classical.choice`, `Quot.sound` (or none). -/

#print axioms OddMath.Frontier.EKRskSignControls.insertRow
#print axioms OddMath.Frontier.EKRskSignControls.insertTab
#print axioms OddMath.Frontier.EKRskSignControls.placeAt
#print axioms OddMath.Frontier.EKRskSignControls.twoLine
#print axioms OddMath.Frontier.EKRskSignControls.rskFrom
#print axioms OddMath.Frontier.EKRskSignControls.rsk
#print axioms OddMath.Frontier.EKRskSignControls.inv
#print axioms OddMath.Frontier.EKRskSignControls.rowWord
#print axioms OddMath.Frontier.EKRskSignControls.shapeExp
#print axioms OddMath.Frontier.EKRskSignControls.crossingL
#print axioms OddMath.Frontier.EKRskSignControls.printed
#print axioms OddMath.Frontier.EKRskSignControls.variantNoShape
#print axioms OddMath.Frontier.EKRskSignControls.parts
#print axioms OddMath.Frontier.EKRskSignControls.partitions
#print axioms OddMath.Frontier.EKRskSignControls.rowsWith
#print axioms OddMath.Frontier.EKRskSignControls.matsWith
#print axioms OddMath.Frontier.EKRskSignControls.allMatrices
#print axioms OddMath.Frontier.EKRskSignControls.allMatrices_count
#print axioms OddMath.Frontier.EKRskSignControls.examples_4_5
#print axioms OddMath.Frontier.EKRskSignControls.examples_4_5_signs
#print axioms OddMath.Frontier.EKRskSignControls.exhaustive_le_four
#print axioms OddMath.Frontier.EKRskSignControls.variant_without_shape_fails
#print axioms OddMath.Frontier.EKRskSignControls.variant_without_shape_fails_exhaustive
#print axioms OddMath.Frontier.EKRskSignControls.ex1
#print axioms OddMath.Frontier.EKRskSignControls.ex2
#print axioms OddMath.Frontier.EKRskSignControls.ex3
#print axioms OddMath.Frontier.EKRskSignControls.ex4
#print axioms OddMath.Frontier.EKRskSignControls.crossing_agrees_examples
#print axioms OddMath.Frontier.EKRskSign.crossL
#print axioms OddMath.Frontier.EKRskSign.inversions_append
#print axioms OddMath.Frontier.EKRskSign.inversions_append_single
#print axioms OddMath.Frontier.EKRskSign.crossL_cons_of_ge
#print axioms OddMath.Frontier.EKRskSign.inversions_middle
#print axioms OddMath.Frontier.EKRskSign.inversions_of_sorted
#print axioms OddMath.Frontier.EKRskSign.neg_one_pow_eq_iff
#print axioms OddMath.Frontier.EKRskSign.sum_map_eq_count
#print axioms OddMath.Frontier.EKRskSign.length_filter_lt_eq
#print axioms OddMath.Frontier.EKRskSign.lab
#print axioms OddMath.Frontier.EKRskSign.crossL_map_lab
#print axioms OddMath.Frontier.EKRskSign.twoLine
#print axioms OddMath.Frontier.EKRskSign.rowV
#print axioms OddMath.Frontier.EKRskSign.twoLine_snd
#print axioms OddMath.Frontier.EKRskSign.rowV_sorted
#print axioms OddMath.Frontier.EKRskSign.count_rowV
#print axioms OddMath.Frontier.EKRskSign.count_flatMap_rowV
#print axioms OddMath.Frontier.EKRskSign.crossing_succ
#print axioms OddMath.Frontier.EKRskSign.inversions_flatMap_rowV
#print axioms OddMath.Frontier.EKRskSign.inversions_twoLine
#print axioms OddMath.Frontier.EKRskSign.LexLE
#print axioms OddMath.Frontier.EKRskSign.twoLine_sorted
#print axioms OddMath.Frontier.EKRskSign.rowLE_antisymm
#print axioms OddMath.Frontier.EKRskSign.rowCells_insert
#print axioms OddMath.Frontier.EKRskSign.rowCells_split
#print axioms OddMath.Frontier.EKRskSign.not_rowLE_iff
#print axioms OddMath.Frontier.EKRskSign.card_row
#print axioms OddMath.Frontier.EKRskSign.card_rows_below
#print axioms OddMath.Frontier.EKRskSign.newCell_mem
#print axioms OddMath.Frontier.EKRskSign.rows_above_mem
#print axioms OddMath.Frontier.EKRskSign.crossings_add_row
#print axioms OddMath.Frontier.EKRskSign.insert_inversions
#print axioms OddMath.Frontier.EKRskSign.rowFinWord_insert_perm
#print axioms OddMath.Frontier.EKRskSign.St
#print axioms OddMath.Frontier.EKRskSign.step
#print axioms OddMath.Frontier.EKRskSign.init
#print axioms OddMath.Frontier.EKRskSign.rskState
#print axioms OddMath.Frontier.EKRskSign.GoodQ
#print axioms OddMath.Frontier.EKRskSign.Good2
#print axioms OddMath.Frontier.EKRskSign.mem_step
#print axioms OddMath.Frontier.EKRskSign.good2_of
#print axioms OddMath.Frontier.EKRskSign.good2_next
#print axioms OddMath.Frontier.EKRskSign.shapeExp
#print axioms OddMath.Frontier.EKRskSign.qWord
#print axioms OddMath.Frontier.EKRskSign.sgnExp
#print axioms OddMath.Frontier.EKRskSign.Inv
#print axioms OddMath.Frontier.EKRskSign.inv_step
#print axioms OddMath.Frontier.EKRskSign.main_ind
#print axioms OddMath.Frontier.EKRskSign.init_good
#print axioms OddMath.Frontier.EKRskSign.init_inv
#print axioms OddMath.Frontier.EKRskSign.rskState_spec
#print axioms OddMath.Frontier.EKRskSign.rskShape
#print axioms OddMath.Frontier.EKRskSign.rskP
#print axioms OddMath.Frontier.EKRskSign.rskQ
#print axioms OddMath.Frontier.EKRskSign.rskP_bounded
#print axioms OddMath.Frontier.EKRskSign.rskQ_bounded
#print axioms OddMath.Frontier.EKRskSign.thm_3_7_sign
#print axioms OddMath.Frontier.EKRskSign.thm_3_7_sign_mat
#print axioms OddMath.Frontier.EKRskSign.shapeExp_eq_choose
#print axioms OddMath.Frontier.EKRskSign.shapeExp_mod_two
#print axioms OddMath.Frontier.EKRskSign.foldl_step_P
#print axioms OddMath.Frontier.EKRskSign.rskP_eq_run
#print axioms OddMath.Frontier.EKRskSign.thm_3_7_sign_printed
