import OddMath.Frontier.EQInductionBimodule

/-!
# Which left action of `OΛ_a ⊗ OΛ_b` on `Z_{a,b}` gives the induction half of Corollary 4.21

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.3, Definition 4.6 (the action of `OΛ_{a,b} = OΛ_a ⊗ OΛ_b` on `Z_{a,b}` is not specified) and §4.4,
Corollary 4.21 (the induction half needs `(Z_a ⊠ Z_b) ⊗_{OΛ_{a,b}} Z_{a,b} ≅ ι^* Z_{a+b}`).

For a dg ring endomorphism `T` of `OΛ_{a,b}`, let `Z^T_{a,b}` be `Z_{a,b}` with `g ∈ OΛ_{a,b}` acting by
`(w₀ × w₀)(T g)` (`EQFunctor.ZabT`; `T = id` is the action of `EQFunctor.Zab.instModuleAB`, which works,
`EQFunctor.indEquiv`). In Ellis–Qi's model `OΛ̃_a ⊠ OΛ̃_b · z`, `T = id` is the action through `θ ∘ w₀`
on each factor and `T = w₀ × w₀` the plain action through `θ`.

* `permPoly`: the ring endomorphism of `OPol_N` permuting the variables (no signs); it commutes with
  `d` (`d_permPoly`). From it: `xRev` (reverse the block `x`), `yRev` (reverse `y`) and, for `a = b`,
  `blockSwap` (`x ↔ y`); all three preserve `OΛ_{a,b}` and give dg ring endomorphisms (`osymABEndo`).
* `zabT_constraint`: if `T` acts on polynomials through an involution `P`, an isomorphism of dg
  `(ONH_a ⊗ ONH_b, OΛ_{a+b})`-bimodules `(Z_a ⊠ Z_b) ⊗ Z^T_{a,b} ≅ ι^* Z_{a+b}` forces
  `(w₀ × w₀)(P (w₀ × w₀)(φ h)) = φ h` for all `h ∈ OΛ_{a+b}`, `z · h = φ(h) z`.
* **`no_indEquiv_of_e2`** and its instances: for `a = b = 2` and each of the seven non-identity elements
  `T` of the group generated by `x`-reversal, `y`-reversal and the block swap (`w₀ × w₀` = the untwisted
  action, `w₀ × 1`, `1 × w₀`, the swap and the swap composed with each of the three reversals) there is no
  such isomorphism: the witness is `h = e_2`, through the coefficients of `x_1 x_2`, `y_1 y_2` and
  `x_1 y_1` (`no_indEquiv_xRev`, `no_indEquiv_yRev`, `no_indEquiv_blockRev`, `no_indEquiv_swap`,
  `no_indEquiv_swap_blockRev`, `no_indEquiv_swap_xRev`, `no_indEquiv_swap_yRev`).

Sign twists `x_i ↦ ± x_i` with some minus sign are not dg ring endomorphisms (`d x = x²`), and the grade
involution `f ↦ (-1)^{|f|} f` does not commute with `d` either (`parityInv_not_dg`), so they do not
define dg bimodules at all.
-/

noncomputable section

open CategoryTheory
open scoped TensorProduct

namespace OddMath.Frontier.EQFunctor

open OddMath.SkewPolynomial (SkewPolynomial generator)
open OddMath.Frontier.EQSkewDifferential
open OddMath.Frontier.EQZab (inclX inclY osymAB)
open OddMath.Frontier.EQOnhDG (ONH)
open DG MulOpposite TensorProductOver.RightAction

/-! ### Permutations of the variables -/

section Perm

variable {N : ℕ}

/-- The ring endomorphism of `OPol_N` with `x_j ↦ x_{π j}`. -/
def permPoly (π : Equiv.Perm (Fin N)) : SkewPolynomial N →+* SkewPolynomial N :=
  skewLift (fun j => generator (π j)) (EQZab.generator_anticomm_of_injective _ π.injective)

theorem permPoly_generator (π : Equiv.Perm (Fin N)) (j : Fin N) :
    permPoly π (generator j) = generator (π j) := by
  simp [permPoly]

theorem parityInv_permPoly (π : Equiv.Perm (Fin N)) (f : SkewPolynomial N) :
    parityInv N (permPoly π f) = permPoly π (parityInv N f) := by
  have h : (parityInv N).comp (permPoly π) = (permPoly π).comp (parityInv N) :=
    ringHom_ext fun j => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem d_permPoly (π : Equiv.Perm (Fin N)) (f : SkewPolynomial N) :
    d N (permPoly π f) = permPoly π (d N f) := by
  let D : SkewPolynomial N →+ SkewPolynomial N := (d N).comp (permPoly π).toAddMonoidHom
  let E : SkewPolynomial N →+ SkewPolynomial N := (permPoly π).toAddMonoidHom.comp (d N)
  exact EQZab.deriv_ext (D := D) (E := E) ((parityInv N).comp (permPoly π)) (permPoly π)
    (fun f g => by simp [D, EQSkewDifferential.d_mul])
    (fun f g => by simp [E, EQSkewDifferential.d_mul, parityInv_permPoly])
    (fun j => by simp [D, E, permPoly_generator]) f

theorem permPoly_mem_grading (π : Equiv.Perm (Fin N)) {k : ℤ} {f : SkewPolynomial N}
    (hf : f ∈ grading N k) : permPoly π f ∈ grading N k :=
  ringHom_mem_grading _ (fun j => by rw [permPoly_generator]; exact generator_mem_grading _) hf

theorem permPoly_mul (π σ : Equiv.Perm (Fin N)) (f : SkewPolynomial N) :
    permPoly π (permPoly σ f) = permPoly (σ.trans π) f := by
  have h : (permPoly π).comp (permPoly σ) = permPoly (σ.trans π) :=
    ringHom_ext fun j => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

end Perm

/-! ### Reversing one block, swapping the blocks -/

section Blocks

variable (A B : ℕ)

/-- Reverse the block `x`. -/
def xRevPerm : Equiv.Perm (Fin (A + B)) :=
  finSumFinEquiv.symm.trans ((Equiv.sumCongr Fin.revPerm (Equiv.refl _)).trans finSumFinEquiv)

/-- Reverse the block `y`. -/
def yRevPerm : Equiv.Perm (Fin (A + B)) :=
  finSumFinEquiv.symm.trans ((Equiv.sumCongr (Equiv.refl _) Fin.revPerm).trans finSumFinEquiv)

/-- Swap the two blocks of `Fin (A + A)`. -/
def swapPerm : Equiv.Perm (Fin (A + A)) :=
  finSumFinEquiv.symm.trans ((Equiv.sumComm _ _).trans finSumFinEquiv)

variable {A B}

@[simp] theorem xRevPerm_castAdd (i : Fin A) : xRevPerm A B (Fin.castAdd B i) = Fin.castAdd B i.rev := by
  simp [xRevPerm]

@[simp] theorem xRevPerm_natAdd (j : Fin B) : xRevPerm A B (Fin.natAdd A j) = Fin.natAdd A j := by
  simp [xRevPerm]

@[simp] theorem yRevPerm_castAdd (i : Fin A) : yRevPerm A B (Fin.castAdd B i) = Fin.castAdd B i := by
  simp [yRevPerm]

@[simp] theorem yRevPerm_natAdd (j : Fin B) : yRevPerm A B (Fin.natAdd A j) = Fin.natAdd A j.rev := by
  simp [yRevPerm]

@[simp] theorem swapPerm_castAdd (i : Fin A) : swapPerm A (Fin.castAdd A i) = Fin.natAdd A i := by
  simp only [swapPerm, Equiv.trans_apply, finSumFinEquiv_symm_apply_castAdd, Equiv.sumComm_apply,
    Sum.swap_inl, finSumFinEquiv_apply_right]

@[simp] theorem swapPerm_natAdd (j : Fin A) : swapPerm A (Fin.natAdd A j) = Fin.castAdd A j := by
  simp only [swapPerm, Equiv.trans_apply, finSumFinEquiv_symm_apply_natAdd, Equiv.sumComm_apply,
    Sum.swap_inr, finSumFinEquiv_apply_left]

theorem xRev_inclX (f : SkewPolynomial A) :
    permPoly (xRevPerm A B) (inclX A B f) = inclX A B (longestPerm A f) := by
  have h : (permPoly (xRevPerm A B)).comp (inclX A B) = (inclX A B).comp (longestPerm A) :=
    ringHom_ext fun i => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem xRev_inclY (f : SkewPolynomial B) : permPoly (xRevPerm A B) (inclY A B f) = inclY A B f := by
  have h : (permPoly (xRevPerm A B)).comp (inclY A B) = inclY A B :=
    ringHom_ext fun i => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem yRev_inclX (f : SkewPolynomial A) : permPoly (yRevPerm A B) (inclX A B f) = inclX A B f := by
  have h : (permPoly (yRevPerm A B)).comp (inclX A B) = inclX A B :=
    ringHom_ext fun i => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem yRev_inclY (f : SkewPolynomial B) :
    permPoly (yRevPerm A B) (inclY A B f) = inclY A B (longestPerm B f) := by
  have h : (permPoly (yRevPerm A B)).comp (inclY A B) = (inclY A B).comp (longestPerm B) :=
    ringHom_ext fun i => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem swap_inclX (f : SkewPolynomial A) : permPoly (swapPerm A) (inclX A A f) = inclY A A f := by
  have h : (permPoly (swapPerm A)).comp (inclX A A) = inclY A A :=
    ringHom_ext fun i => by simp [permPoly_generator]
  exact RingHom.congr_fun h f

theorem swapPerm_addNat (i : Fin A) : swapPerm A (i.addNat A) = Fin.castAdd A i := by
  rw [show i.addNat A = Fin.natAdd A i from Fin.ext (by simp [Nat.add_comm]), swapPerm_natAdd]

theorem swap_inclY (f : SkewPolynomial A) : permPoly (swapPerm A) (inclY A A f) = inclX A A f := by
  have h : (permPoly (swapPerm A)).comp (inclY A A) = inclX A A :=
    ringHom_ext fun i => by simp [permPoly_generator, swapPerm_addNat]
  exact RingHom.congr_fun h f

theorem blockRev_eq_permPoly : blockRev A B = permPoly (blockRevPerm A B) :=
  ringHom_ext fun j => by simp [blockRev_generator, permPoly_generator]

theorem xRev_mem {f : SkewPolynomial (A + B)} (hf : f ∈ osymAB A B) :
    permPoly (xRevPerm A B) f ∈ osymAB A B := by
  refine EQZab.osymAB_induction (P := fun f => permPoly (xRevPerm A B) f ∈ osymAB A B)
    ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
  · intro k; rw [xRev_inclX]; exact EQZab.inclX_mem (EQZab.longestPerm_mem_osym (EQZab.elementary_mem A k))
  · intro k; rw [xRev_inclY]; exact EQZab.inclY_mem (EQZab.elementary_mem B k)
  · rw [map_zero]; exact zero_mem _
  · rw [map_one]; exact one_mem _
  · intro f g hf hg; rw [map_add]; exact add_mem hf hg
  · intro f hf; rw [map_neg]; exact neg_mem hf
  · intro f g hf hg; rw [map_mul]; exact mul_mem hf hg

theorem yRev_mem {f : SkewPolynomial (A + B)} (hf : f ∈ osymAB A B) :
    permPoly (yRevPerm A B) f ∈ osymAB A B := by
  refine EQZab.osymAB_induction (P := fun f => permPoly (yRevPerm A B) f ∈ osymAB A B)
    ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
  · intro k; rw [yRev_inclX]; exact EQZab.inclX_mem (EQZab.elementary_mem A k)
  · intro k; rw [yRev_inclY]; exact EQZab.inclY_mem (EQZab.longestPerm_mem_osym (EQZab.elementary_mem B k))
  · rw [map_zero]; exact zero_mem _
  · rw [map_one]; exact one_mem _
  · intro f g hf hg; rw [map_add]; exact add_mem hf hg
  · intro f hf; rw [map_neg]; exact neg_mem hf
  · intro f g hf hg; rw [map_mul]; exact mul_mem hf hg

theorem swap_mem {f : SkewPolynomial (A + A)} (hf : f ∈ osymAB A A) :
    permPoly (swapPerm A) f ∈ osymAB A A := by
  refine EQZab.osymAB_induction (P := fun f => permPoly (swapPerm A) f ∈ osymAB A A)
    ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
  · intro k; rw [swap_inclX]; exact EQZab.inclY_mem (EQZab.elementary_mem A k)
  · intro k; rw [swap_inclY]; exact EQZab.inclX_mem (EQZab.elementary_mem A k)
  · rw [map_zero]; exact zero_mem _
  · rw [map_one]; exact one_mem _
  · intro f g hf hg; rw [map_add]; exact add_mem hf hg
  · intro f hf; rw [map_neg]; exact neg_mem hf
  · intro f g hf hg; rw [map_mul]; exact mul_mem hf hg

end Blocks

/-! ### Dg ring endomorphisms of `OΛ_{a,b}` from permutations -/

section Endo

variable {A B : ℕ}

/-- A permutation of the variables preserving `OΛ_{A,B}` as a dg ring endomorphism of `OΛ_{A,B}`. -/
def osymABEndo (π : Equiv.Perm (Fin (A + B)))
    (hmem : ∀ {f : SkewPolynomial (A + B)}, f ∈ osymAB A B → permPoly π f ∈ osymAB A B) :
    osymABDG A B →ᵈᵍ+* osymABDG A B where
  toFun g := ⟨OPol.equiv _ (permPoly π ((OPol.equiv _).symm g)), mem_osymABDG.mpr (by
    rw [RingEquiv.symm_apply_apply]; exact hmem (mem_osymABDG.mp g.2))⟩
  map_one' := Subtype.ext (by simp)
  map_mul' g g' := Subtype.ext (by simp)
  map_zero' := Subtype.ext (by simp)
  map_add' g g' := Subtype.ext (by simp)
  map_mem' {k g} hg := (DGSubring.mem_grading_iff _).mpr (OPol.equiv_mem_grading_iff.mpr
    (permPoly_mem_grading π (OPol.equiv_mem_grading_iff.mp ((DGSubring.mem_grading_iff _).mp hg))))
  map_d' g := Subtype.ext (by
    change OPol.equiv _ (permPoly π ((OPol.equiv _).symm (DG.d (g : OPol (A + B))))) =
      DG.d (OPol.equiv _ (permPoly π ((OPol.equiv _).symm (g : OPol (A + B)))))
    rw [OPol.symm_d, ← d_permPoly]
    rfl)

theorem skg_osymABEndo (π : Equiv.Perm (Fin (A + B)))
    (hmem : ∀ {f : SkewPolynomial (A + B)}, f ∈ osymAB A B → permPoly π f ∈ osymAB A B)
    (g : osymABDG A B) : skg (osymABEndo π hmem g) = permPoly π (skg g) := rfl

/-- `w₀ × 1` on `OΛ_{A,B}`. -/
abbrev xRevDG : osymABDG A B →ᵈᵍ+* osymABDG A B := osymABEndo (xRevPerm A B) xRev_mem

/-- `1 × w₀` on `OΛ_{A,B}`. -/
abbrev yRevDG : osymABDG A B →ᵈᵍ+* osymABDG A B := osymABEndo (yRevPerm A B) yRev_mem

/-- `w₀ × w₀` on `OΛ_{A,B}` (the plain permutation action, `EQFunctor.blockRevDG`). -/
abbrev bRevDG : osymABDG A B →ᵈᵍ+* osymABDG A B :=
  osymABEndo (blockRevPerm A B) fun hf => by rw [← blockRev_eq_permPoly]; exact blockRev_mem A B hf

/-- The block swap `x ↔ y` on `OΛ_{A,A}`. -/
abbrev swapDGAA : osymABDG A A →ᵈᵍ+* osymABDG A A := osymABEndo (swapPerm A) swap_mem

end Endo

/-! ### The constraint -/

variable {a b : ℕ}

local notation "𝒪a" => DGAlgebra.gradingSubmodule ℤ (ONH a)
local notation "𝒪b" => DGAlgebra.gradingSubmodule ℤ (ONH b)
local notation "Λa" => DGAlgebra.gradingSubmodule ℤ (osymDG (a + 2))
local notation "Λb" => DGAlgebra.gradingSubmodule ℤ (osymDG (b + 2))

variable (a b) in
/-- `f ⊗ g ↦ T(f(x) g(y))`. -/
def compT (T : osymABDG (a + 2) (b + 2) →ᵈᵍ+* osymABDG (a + 2) (b + 2)) :
    (Λa ᵍ⊗[ℤ] Λb) →ᵈᵍ+* osymABDG (a + 2) (b + 2) :=
  T.comp (tensorToOsymAB (a + 2) (b + 2))

variable (a b) in
/-- `Z_{a,b}` with `f ⊗ g ∈ OΛ_a ⊗ OΛ_b` acting by `(w₀ × w₀)(T (f(x) g(y)))`. -/
abbrev ZabT (T : osymABDG (a + 2) (b + 2) →ᵈᵍ+* osymABDG (a + 2) (b + 2)) : Type :=
  RestrictScalars (compT a b T) (EQFix.Zab (a + 2) (b + 2))

section Constraint

variable (π : Equiv.Perm (Fin ((a + 2) + (b + 2))))
  (hmem : ∀ {f : SkewPolynomial ((a + 2) + (b + 2))}, f ∈ osymAB (a + 2) (b + 2) →
    permPoly π f ∈ osymAB (a + 2) (b + 2))
  (ρ : Equiv.Perm (Fin ((a + 2) + (b + 2))))
  (hmemρ : ∀ {f : SkewPolynomial ((a + 2) + (b + 2))}, f ∈ osymAB (a + 2) (b + 2) →
    permPoly ρ f ∈ osymAB (a + 2) (b + 2))
  (hPQ : ∀ f, permPoly π (permPoly ρ f) = f) (hQP : ∀ f, permPoly ρ (permPoly π f) = f)

/-- The underlying skew polynomial. -/
def tVal (F : ZabT a b (osymABEndo π hmem)) : SkewPolynomial ((a + 2) + (b + 2)) :=
  EQFix.Zab.val (show EQFix.Zab (a + 2) (b + 2) from F)

theorem rHat_eq_skg (r : Λa ᵍ⊗[ℤ] Λb) : rHat r = skg (tensorToOsymAB (a + 2) (b + 2) r) := by
  rw [rHat, skg, coe_tensorToOsymAB]

theorem tVal_smul (r : Λa ᵍ⊗[ℤ] Λb) (F : ZabT a b (osymABEndo π hmem)) :
    tVal π hmem (r • F) = blockRev _ _ (permPoly π (rHat r)) * tVal π hmem F := by
  rw [rHat_eq_skg]; rfl

/-- The generator `z`. -/
def tOne : ZabT a b (osymABEndo π hmem) :=
  show EQFix.Zab (a + 2) (b + 2) from EQFix.Zab.mk 1 (one_mem _)

include hQP in
/-- A balanced map out of `(Z_a ⊠ Z_b) ⊗ Z^T_{a,b}` (used only to see that `1 ⊗ z ≠ 0`). -/
theorem tmul_yOne_tOne_ne_zero :
    TensorProductOver.tmul (Λa ᵍ⊗[ℤ] Λb) (yOne a b) (tOne π hmem) ≠ 0 := by
  let W : SkewPolynomial ((a + 2) + (b + 2)) →+* SkewPolynomial ((a + 2) + (b + 2)) :=
    ((blockRev _ _).comp (permPoly ρ)).comp (blockRev _ _)
  let uF : ZZ a b →+ ZabT a b (osymABEndo π hmem) →+ SkewPolynomial ((a + 2) + (b + 2)) :=
    AddMonoidHom.mk' (fun y => AddMonoidHom.mk' (fun F =>
        polyHom y * EQZab.tauAB (a + 2) (b + 2) (W (tVal π hmem F)))
        fun F F' => by
          change _ * EQZab.tauAB _ _ (W (tVal π hmem F + tVal π hmem F')) = _
          rw [map_add, map_add, mul_add])
      fun y y' => AddMonoidHom.ext fun F => by
        change polyHom (y + y') * _ = polyHom y * _ + polyHom y' * _
        rw [map_add, add_mul]
  have hb : ∀ (r : Λa ᵍ⊗[ℤ] Λb) (y : ZZ a b) (F : ZabT a b (osymABEndo π hmem)),
      uF (op r • y) F = uF y (r • F) := fun r y F => by
    change polyHom (op r • y) * _ = polyHom y * EQZab.tauAB _ _ (W (tVal π hmem (r • F)))
    rw [polyHom_op_smul, tVal_smul, map_mul W, map_mul (EQZab.tauAB _ _), EQBorel.sp_mul_assoc]
    congr 3
    change blockRev _ _ (rHat r) = blockRev _ _ (permPoly ρ (blockRev _ _ (blockRev _ _ (permPoly π (rHat r)))))
    rw [blockRev_blockRev, hQP]
  intro h
  have := congrArg (TensorProductOver.lift uF hb) h
  rw [TensorProductOver.lift_tmul, map_zero] at this
  change polyHom (yOne a b) * _ = 0 at this
  rw [polyHom_yOne] at this
  change (1 : SkewPolynomial _) * EQZab.tauAB _ _ (W 1) = 0 at this
  rw [map_one, map_one, sp_mul_one'] at this
  exact one_ne_zero (α := SkewPolynomial ((a + 2) + (b + 2))) this

theorem eq_of_zsmul_eq {N : ℕ} {c : ℤ} (hc : c ≠ 0) {f g : SkewPolynomial N} (h : c • f = c • g) :
    f = g := by
  ext α
  have := congrArg (fun F : SkewPolynomial N => F α) h
  simp only [Finsupp.smul_apply, smul_eq_mul] at this
  exact mul_left_cancel₀ hc this

include hmemρ hPQ hQP in
/-- **The constraint**: an isomorphism of dg `(ONH_a ⊗ ONH_b, OΛ_{a+b})`-bimodules
`(Z_a ⊠ Z_b) ⊗ Z^T_{a,b} ≅ ι^* Z_{a+b}`, for `T` acting through a permutation `P` of the variables with
inverse `Q`, forces `(w₀ × w₀)(Q((w₀ × w₀)(φ h))) = φ h` for every `h ∈ OΛ_{a+b}`. -/
theorem zabT_constraint
    (e : TensorProductOver (Λa ᵍ⊗[ℤ] Λb) (ZZ a b) (ZabT a b (osymABEndo π hmem)) ≃ᵈᵍ[𝒪a ᵍ⊗[ℤ] 𝒪b] IZ a b)
    (he : ∀ (h : osymDG ((a + 2) + (b + 2))) t, e (op h • t) = op h • e t)
    (h : osymDG ((a + 2) + (b + 2))) :
    blockRev _ _ (permPoly ρ (blockRev _ _ (EQZab.phiAB _ _ (EQFix.toSkew h)))) =
      EQZab.phiAB _ _ (EQFix.toSkew h) := by
  set t0 := TensorProductOver.tmul (Λa ᵍ⊗[ℤ] Λb) (yOne a b) (tOne π hmem)
  have t0_mem : t0 ∈ DG.grading (0 : ℤ) := by
    have hy : yOne a b ∈ DG.grading (0 : ℤ) := by
      have := DG.tmul_mem_grading (M := Zn (a + 2)) (N := Zn (b + 2))
        (OPolAlpha.mem_grading_iff.mpr (by rw [AddEquiv.symm_apply_apply]; exact one_mem_grading'))
        (OPolAlpha.mem_grading_iff.mpr (by rw [AddEquiv.symm_apply_apply]; exact one_mem_grading'))
      rwa [add_zero] at this
    have := TensorProductOver.tmul_mem_grading (A := Λa ᵍ⊗[ℤ] Λb) hy
      (show tOne π hmem ∈ DG.grading (0 : ℤ) from EQFix.Zab.mem_grading_iff.mpr one_mem_grading')
    rwa [add_zero] at this
  obtain ⟨c, hc⟩ : ∃ c : ℤ, (zE ((a + 2) + (b + 2))).symm (e t0) = c • 1 :=
    ⟨_, eq_smul_one_of_mem_grading_zero (OPolAlpha.mem_grading_iff.mp (e.map_mem t0_mem))⟩
  have het0 : e t0 = zE _ (c • polyHom (yOne a b)) := by
    rw [polyHom_yOne, ← hc, AddEquiv.apply_symm_apply]
  have hc0 : c ≠ 0 := fun hc0 => tmul_yOne_tOne_ne_zero π hmem ρ hQP (e.injective (by
    change e t0 = e 0
    rw [map_zero, het0, hc0, zero_smul, map_zero]))
  have key : ∀ s : 𝒪a ᵍ⊗[ℤ] 𝒪b,
      e (TensorProductOver.tmul _ (s • yOne a b) (tOne π hmem)) = zE _ (c • polyHom (s • yOne a b)) := by
    intro s
    rw [← TensorProductOver.smul_tmul, map_smul]
    change s • e t0 = _
    rw [het0, map_zsmul, map_zsmul]
    change ONH.iota a b s • ((c • zE _ (polyHom (yOne a b))) : Zn ((a + 2) + (b + 2))) = _
    rw [smul_comm (ONH.iota a b s) c, zE_polyHom_smul]
  set φh := EQZab.phiAB (a + 2) (b + 2) (EQFix.toSkew h)
  have hg : permPoly ρ (blockRev _ _ φh) ∈ osymAB (a + 2) (b + 2) :=
    hmemρ (blockRev_mem _ _ (EQZab.phiAB_mem (EQFix.toSkew_mem h)))
  obtain ⟨r, hr⟩ := tensorToOsymAB_surjective (a := a + 2) (b := b + 2)
    ⟨OPol.equiv _ (permPoly ρ (blockRev _ _ φh)), mem_osymABDG.mpr (by rwa [RingEquiv.symm_apply_apply])⟩
  have hrHat : rHat r = permPoly ρ (blockRev _ _ φh) := by
    rw [rHat_eq_skg, hr]
    exact RingEquiv.symm_apply_apply _ _
  have hop : op h • tOne π hmem = r • tOne π hmem := EQFix.Zab.ext (by
    change tVal π hmem (tOne π hmem) * _ = tVal π hmem (r • tOne π hmem)
    rw [tVal_smul, hrHat, hPQ, blockRev_blockRev]
    change 1 * φh = φh * 1
    rw [sp_one_mul', sp_mul_one'])
  obtain ⟨s, hs⟩ := exists_smul_yOne (op r • yOne a b)
  have hL : op h • t0 = TensorProductOver.tmul _ (s • yOne a b) (tOne π hmem) := by
    rw [TensorProductOver.op_smul_tmul_right, hop, ← TensorProductOver.op_smul_tmul, hs]
  have hlhs : (zE ((a + 2) + (b + 2))).symm (e (op h • t0)) =
      c • EQZab.tauAB _ _ (blockRev _ _ (permPoly ρ (blockRev _ _ φh))) := by
    rw [hL, key, AddEquiv.symm_apply_apply, ← hs, polyHom_op_smul, polyHom_yOne, hrHat, sp_one_mul']
  have hrhs : (zE ((a + 2) + (b + 2))).symm (op h • e t0) = c • EQZab.tauAB _ _ φh := by
    rw [EQZab.tauAB_phiAB]
    change (zE _).symm (e t0) * twistRev _ (EQFix.toSkew h) = _
    rw [hc, smul_mul_assoc, sp_one_mul']
  have h2 : c • EQZab.tauAB _ _ (blockRev _ _ (permPoly ρ (blockRev _ _ φh))) = c • EQZab.tauAB _ _ φh :=
    hlhs.symm.trans ((congrArg (zE ((a + 2) + (b + 2))).symm (he h t0)).trans hrhs)
  have h3 := congrArg (EQZab.tauAB (a + 2) (b + 2)) (eq_of_zsmul_eq hc0 h2)
  simpa only [EQZab.tauAB_tauAB] using h3

end Constraint


/-! ### Witnesses for `a = b = 2` -/

section Witness

/-- The coefficient of `x_1 x_2` after renaming the variables by `π` and setting `x_3 = x_4 = 0`. -/
def kap (π : Equiv.Perm (Fin (2 + 2))) : SkewPolynomial (2 + 2) →+ ℤ :=
  (Finsupp.applyAddHom (show Fin 2 → ℕ from ![1, 1])).comp
    ((projX 2 2).toAddMonoidHom.comp (permPoly π).toAddMonoidHom)

theorem kap_apply (π : Equiv.Perm (Fin (2 + 2))) (f : SkewPolynomial (2 + 2)) :
    kap π f = (projX 2 2 (permPoly π f)) (show Fin 2 → ℕ from ![1, 1]) := rfl

theorem coeff_g0g1 : (generator (0 : Fin 2) * generator 1 : SkewPolynomial 2) ![1, 1] = 1 :=
  OddMath.SkewPolynomial.ordered_rank_two_coordinate

theorem coeff_g1g0 : (generator (1 : Fin 2) * generator 0 : SkewPolynomial 2) ![1, 1] = -1 := by
  have h := OddMath.SkewPolynomial.generator_anticommute (1 : Fin 2) 0 (by decide)
  change (OddMath.SkewPolynomial.mul (generator (1 : Fin 2)) (generator 0)) ![1, 1] = -1
  rw [h, Finsupp.neg_apply]
  change -((generator (0 : Fin 2) * generator 1 : SkewPolynomial 2) ![1, 1]) = -1
  rw [coeff_g0g1]

theorem elementary_two_one : elementary 2 1 = generator 0 + generator 1 := by
  rw [elementary, EQZab.strictSum_one, Fin.sum_univ_two]

abbrev X2 : SkewPolynomial ((0 + 2) + (0 + 2)) := inclX (0 + 2) (0 + 2) (elementary 2 2)
abbrev Y2 : SkewPolynomial ((0 + 2) + (0 + 2)) := inclY (0 + 2) (0 + 2) (elementary 2 2)
abbrev X1 : SkewPolynomial ((0 + 2) + (0 + 2)) := inclX (0 + 2) (0 + 2) (elementary 2 1)
abbrev Y1 : SkewPolynomial ((0 + 2) + (0 + 2)) := inclY (0 + 2) (0 + 2) (elementary 2 1)

theorem e2_decomp : elementary ((0 + 2) + (0 + 2)) 2 = X2 + X1 * Y1 + Y2 := by
  rw [EQZab.elementary_add, Finset.Nat.sum_antidiagonal_succ, Finset.Nat.sum_antidiagonal_succ,
    Finset.Nat.antidiagonal_zero, Finset.sum_singleton]
  have h0 : ∀ m, elementary m 0 = 1 := fun m => FiniteCompleteElementary.FiniteWords.strictSum_zero _
  simp only [zero_add, Nat.reduceAdd, h0, map_one, sp_one_mul', sp_mul_one']
  abel

theorem longestPerm_e1 : longestPerm 2 (elementary 2 1) = elementary 2 1 := by
  rw [EQFix.longestPerm_elementary]; simp

theorem longestPerm_e2 : longestPerm 2 (elementary 2 2) = -elementary 2 2 := by
  rw [EQFix.longestPerm_elementary]; simp

theorem X2_eq : X2 = generator 0 * generator 1 := by
  rw [X2, elementary_two_two, map_mul, EQZab.inclX_generator, EQZab.inclX_generator]; rfl

theorem Y2_eq : Y2 = generator 2 * generator 3 := by
  rw [Y2, elementary_two_two, map_mul, EQZab.inclY_generator, EQZab.inclY_generator]; rfl

theorem X1_eq : X1 = generator 0 + generator 1 := by
  rw [X1, elementary_two_one, map_add, EQZab.inclX_generator, EQZab.inclX_generator]; rfl

theorem Y1_eq : Y1 = generator 2 + generator 3 := by
  rw [Y1, elementary_two_one, map_add, EQZab.inclY_generator, EQZab.inclY_generator]; rfl

theorem projX_gen0 : projX 2 2 (generator (0 : Fin (2 + 2))) = generator 0 := by simp [projX]
theorem projX_gen1 : projX 2 2 (generator (1 : Fin (2 + 2))) = generator 1 := by simp [projX]
theorem projX_gen2 : projX 2 2 (generator (2 : Fin (2 + 2))) = 0 := by simp [projX]
theorem projX_gen3 : projX 2 2 (generator (3 : Fin (2 + 2))) = 0 := by simp [projX]

/-- The renaming `x_3 ↔ x_2`, for the coefficient of `x_1 y_1`. -/
abbrev π02 : Equiv.Perm (Fin (2 + 2)) := Equiv.swap 1 2

/-- The test functionals on `X2`, `X1 Y1`, `Y1 X1`, `Y2`. -/
theorem kap_values :
    kap 1 X2 = 1 ∧ kap 1 (X1 * Y1) = 0 ∧ kap 1 (Y1 * X1) = 0 ∧ kap 1 Y2 = 0 ∧
    kap (swapPerm 2) X2 = 0 ∧ kap (swapPerm 2) (X1 * Y1) = 0 ∧ kap (swapPerm 2) (Y1 * X1) = 0 ∧
    kap (swapPerm 2) Y2 = 1 ∧
    kap π02 X2 = 0 ∧ kap π02 (X1 * Y1) = 1 ∧ kap π02 (Y1 * X1) = -1 ∧ kap π02 Y2 = 0 := by
  have s0 : swapPerm 2 (0 : Fin (2 + 2)) = 2 := swapPerm_castAdd (A := 2) 0
  have s1 : swapPerm 2 (1 : Fin (2 + 2)) = 3 := swapPerm_castAdd (A := 2) 1
  have s2 : swapPerm 2 (2 : Fin (2 + 2)) = 0 := swapPerm_natAdd (A := 2) 0
  have s3 : swapPerm 2 (3 : Fin (2 + 2)) = 1 := swapPerm_natAdd (A := 2) 1
  have p0 : π02 (0 : Fin (2 + 2)) = 0 := by decide
  have p1 : π02 (1 : Fin (2 + 2)) = 2 := by decide
  have p2 : π02 (2 : Fin (2 + 2)) = 1 := by decide
  have p3 : π02 (3 : Fin (2 + 2)) = 3 := by decide
  have i0 : (1 : Equiv.Perm (Fin (2 + 2))) 0 = 0 := rfl
  have i1 : (1 : Equiv.Perm (Fin (2 + 2))) 1 = 1 := rfl
  have i2 : (1 : Equiv.Perm (Fin (2 + 2))) 2 = 2 := rfl
  have i3 : (1 : Equiv.Perm (Fin (2 + 2))) 3 = 3 := rfl
  simp only [kap_apply, X2_eq, Y2_eq, X1_eq, Y1_eq, map_mul, map_add, permPoly_generator, s0, s1, s2,
    s3, p0, p1, p2, p3, i0, i1, i2, i3, projX_gen0, projX_gen1, projX_gen2, projX_gen3, add_zero,
    EQBorel.sp_mul_zero, EQBorel.sp_zero_mul, Finsupp.coe_zero, Pi.zero_apply, coeff_g0g1,
    coeff_g1g0, and_self]

theorem permPoly_trans {N : ℕ} (σ τ : Equiv.Perm (Fin N)) (f : SkewPolynomial N) :
    permPoly (σ.trans τ) f = permPoly τ (permPoly σ f) := (permPoly_mul τ σ f).symm

theorem permPoly_refl {N : ℕ} (f : SkewPolynomial N) : permPoly (Equiv.refl (Fin N)) f = f := by
  have h : permPoly (Equiv.refl (Fin N)) = RingHom.id _ := ringHom_ext fun j => by simp [permPoly_generator]
  rw [h, RingHom.id_apply]

theorem xRevPerm_invol (A B : ℕ) : (xRevPerm A B).trans (xRevPerm A B) = Equiv.refl _ := by
  ext j; refine Fin.addCases (fun i => ?_) (fun i => ?_) j <;> simp

theorem yRevPerm_invol (A B : ℕ) : (yRevPerm A B).trans (yRevPerm A B) = Equiv.refl _ := by
  ext j; refine Fin.addCases (fun i => ?_) (fun i => ?_) j <;> simp

theorem blockRevPerm_invol (A B : ℕ) : (blockRevPerm A B).trans (blockRevPerm A B) = Equiv.refl _ := by
  ext j; refine Fin.addCases (fun i => ?_) (fun i => ?_) j <;> simp [blockRevPerm_castAdd, blockRevPerm_natAdd]

theorem swapPerm_invol (A : ℕ) : (swapPerm A).trans (swapPerm A) = Equiv.refl _ := by
  ext j; refine Fin.addCases (fun i => ?_) (fun i => ?_) j <;> simp [swapPerm_addNat]

theorem permPoly_invol {N : ℕ} {π : Equiv.Perm (Fin N)} (h : π.trans π = Equiv.refl _)
    (f : SkewPolynomial N) : permPoly π (permPoly π f) = f := by
  rw [← permPoly_trans, h, permPoly_refl]

theorem permPoly_inv {N : ℕ} {σ τ : Equiv.Perm (Fin N)} (hσ : σ.trans σ = Equiv.refl _)
    (hτ : τ.trans τ = Equiv.refl _) (f : SkewPolynomial N) :
    permPoly (σ.trans τ) (permPoly (τ.trans σ) f) = f := by
  rw [permPoly_trans, permPoly_trans, permPoly_invol hσ, permPoly_invol hτ]

theorem blockRev_mem' {A B : ℕ} {f : SkewPolynomial (A + B)} (hf : f ∈ osymAB A B) :
    permPoly (blockRevPerm A B) f ∈ osymAB A B := by
  rw [← blockRev_eq_permPoly]; exact blockRev_mem A B hf

theorem trans_mem {A B : ℕ} {σ τ : Equiv.Perm (Fin (A + B))}
    (hσ : ∀ {f : SkewPolynomial (A + B)}, f ∈ osymAB A B → permPoly σ f ∈ osymAB A B)
    (hτ : ∀ {f : SkewPolynomial (A + B)}, f ∈ osymAB A B → permPoly τ f ∈ osymAB A B)
    {f : SkewPolynomial (A + B)} (hf : f ∈ osymAB A B) : permPoly (σ.trans τ) f ∈ osymAB A B := by
  rw [permPoly_trans]; exact hτ (hσ hf)

section NoGo

local notation "Λ2" => DGAlgebra.gradingSubmodule ℤ (osymDG (0 + 2))
local notation "𝒪2" => DGAlgebra.gradingSubmodule ℤ (ONH 0)

theorem toSkew_e2 : EQFix.toSkew (⟨OPol.equiv _ (elementary _ 2), elementary_mem_osymDG 2⟩ :
    osymDG ((0 + 2) + (0 + 2))) = elementary _ 2 := rfl

/-- **No isomorphism** for `a = b = 2` and the action through the permutation `P` (inverse `Q`) as soon
as `(w₀ × w₀) Q (w₀ × w₀)` moves `e_2`. -/
theorem no_indEquiv_of (π : Equiv.Perm (Fin ((0 + 2) + (0 + 2))))
    (hmem : ∀ {f : SkewPolynomial ((0 + 2) + (0 + 2))}, f ∈ osymAB (0 + 2) (0 + 2) →
      permPoly π f ∈ osymAB (0 + 2) (0 + 2))
    (ρ : Equiv.Perm (Fin ((0 + 2) + (0 + 2))))
    (hmemρ : ∀ {f : SkewPolynomial ((0 + 2) + (0 + 2))}, f ∈ osymAB (0 + 2) (0 + 2) →
      permPoly ρ f ∈ osymAB (0 + 2) (0 + 2))
    (hPQ : ∀ f, permPoly π (permPoly ρ f) = f) (hQP : ∀ f, permPoly ρ (permPoly π f) = f)
    (hne : blockRev (0 + 2) (0 + 2) (permPoly ρ (blockRev (0 + 2) (0 + 2) (elementary ((0 + 2) + (0 + 2)) 2))) ≠
      elementary ((0 + 2) + (0 + 2)) 2) :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo π hmem)) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  rintro ⟨e, he⟩
  have h := zabT_constraint π hmem ρ hmemρ hPQ hQP e he ⟨OPol.equiv _ (elementary _ 2), elementary_mem_osymDG 2⟩
  rw [toSkew_e2, phiAB_elementary_two, map_neg, map_neg, map_neg, neg_inj] at h
  exact hne h

theorem bX2 : blockRev (0 + 2) (0 + 2) X2 = -X2 := by rw [X2, blockRev_inclX, longestPerm_e2, map_neg]
theorem bY2 : blockRev (0 + 2) (0 + 2) Y2 = -Y2 := by rw [Y2, blockRev_inclY, longestPerm_e2, map_neg]
theorem bX1 : blockRev (0 + 2) (0 + 2) X1 = X1 := by rw [X1, blockRev_inclX, longestPerm_e1]
theorem bY1 : blockRev (0 + 2) (0 + 2) Y1 = Y1 := by rw [Y1, blockRev_inclY, longestPerm_e1]
theorem pbX2 : permPoly (blockRevPerm (0 + 2) (0 + 2)) X2 = -X2 := by rw [← blockRev_eq_permPoly, bX2]
theorem pbY2 : permPoly (blockRevPerm (0 + 2) (0 + 2)) Y2 = -Y2 := by rw [← blockRev_eq_permPoly, bY2]
theorem pbX1 : permPoly (blockRevPerm (0 + 2) (0 + 2)) X1 = X1 := by rw [← blockRev_eq_permPoly, bX1]
theorem pbY1 : permPoly (blockRevPerm (0 + 2) (0 + 2)) Y1 = Y1 := by rw [← blockRev_eq_permPoly, bY1]
theorem xX2 : permPoly (xRevPerm (0 + 2) (0 + 2)) X2 = -X2 := by rw [X2, xRev_inclX, longestPerm_e2, map_neg]
theorem xY2 : permPoly (xRevPerm (0 + 2) (0 + 2)) Y2 = Y2 := xRev_inclY _
theorem xX1 : permPoly (xRevPerm (0 + 2) (0 + 2)) X1 = X1 := by rw [X1, xRev_inclX, longestPerm_e1]
theorem xY1 : permPoly (xRevPerm (0 + 2) (0 + 2)) Y1 = Y1 := xRev_inclY _
theorem yX2 : permPoly (yRevPerm (0 + 2) (0 + 2)) X2 = X2 := yRev_inclX _
theorem yY2 : permPoly (yRevPerm (0 + 2) (0 + 2)) Y2 = -Y2 := by rw [Y2, yRev_inclY, longestPerm_e2, map_neg]
theorem yX1 : permPoly (yRevPerm (0 + 2) (0 + 2)) X1 = X1 := yRev_inclX _
theorem yY1 : permPoly (yRevPerm (0 + 2) (0 + 2)) Y1 = Y1 := by rw [Y1, yRev_inclY, longestPerm_e1]
theorem sX2 : permPoly (swapPerm (0 + 2)) X2 = Y2 := swap_inclX _
theorem sY2 : permPoly (swapPerm (0 + 2)) Y2 = X2 := swap_inclY _
theorem sX1 : permPoly (swapPerm (0 + 2)) X1 = Y1 := swap_inclX _
theorem sY1 : permPoly (swapPerm (0 + 2)) Y1 = X1 := swap_inclY _

/-- The value of `(w₀ × w₀) Q (w₀ × w₀) (e_2) = e_2` under the three test functionals. -/
theorem kap_e2 : kap 1 (elementary ((0 + 2) + (0 + 2)) 2) = 1 ∧
    kap (swapPerm 2) (elementary ((0 + 2) + (0 + 2)) 2) = 1 ∧ kap π02 (elementary ((0 + 2) + (0 + 2)) 2) = 1 := by
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp]
  simp only [map_add, h1, h2, h4, h5, h6, h8, h9, h10, h12]
  norm_num

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through `w₀ × w₀` (the plain action through `θ` in Ellis–Qi's model, `ZabU`). -/
theorem no_indEquiv_blockRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo (blockRevPerm (0 + 2) (0 + 2)) blockRev_mem')) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of (blockRevPerm (0 + 2) (0 + 2)) blockRev_mem' (blockRevPerm (0 + 2) (0 + 2)) blockRev_mem' (permPoly_invol (blockRevPerm_invol _ _)) (permPoly_invol (blockRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap 1) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through `w₀ × 1`. -/
theorem no_indEquiv_xRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo (xRevPerm (0 + 2) (0 + 2)) xRev_mem)) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of (xRevPerm (0 + 2) (0 + 2)) xRev_mem (xRevPerm (0 + 2) (0 + 2)) xRev_mem (permPoly_invol (xRevPerm_invol _ _)) (permPoly_invol (xRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap 1) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through `1 × w₀`. -/
theorem no_indEquiv_yRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo (yRevPerm (0 + 2) (0 + 2)) yRev_mem)) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of (yRevPerm (0 + 2) (0 + 2)) yRev_mem (yRevPerm (0 + 2) (0 + 2)) yRev_mem (permPoly_invol (yRevPerm_invol _ _)) (permPoly_invol (yRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap (swapPerm 2)) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through the block swap `x ↔ y`. -/
theorem no_indEquiv_swap :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo (swapPerm (0 + 2)) swap_mem)) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of (swapPerm (0 + 2)) swap_mem (swapPerm (0 + 2)) swap_mem (permPoly_invol (swapPerm_invol _)) (permPoly_invol (swapPerm_invol _)) fun h => ?_
  have hk := congrArg (kap π02) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through the block swap after `w₀ × w₀`. -/
theorem no_indEquiv_swap_blockRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo ((blockRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem blockRev_mem' swap_mem))) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of ((blockRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem blockRev_mem' swap_mem) ((swapPerm (0 + 2)).trans (blockRevPerm (0 + 2) (0 + 2))) (trans_mem swap_mem blockRev_mem') (permPoly_inv (blockRevPerm_invol _ _) (swapPerm_invol _)) (permPoly_inv (swapPerm_invol _) (blockRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap π02) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through the block swap after `w₀ × 1`. -/
theorem no_indEquiv_swap_xRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo ((xRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem xRev_mem swap_mem))) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of ((xRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem xRev_mem swap_mem) ((swapPerm (0 + 2)).trans (xRevPerm (0 + 2) (0 + 2))) (trans_mem swap_mem xRev_mem) (permPoly_inv (xRevPerm_invol _ _) (swapPerm_invol _)) (permPoly_inv (swapPerm_invol _) (xRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap π02) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

set_option linter.unusedSimpArgs false in
/-- **No isomorphism** (`a = b = 2`) for `OΛ_2 ⊗ OΛ_2` acting on `Z_{2,2}` through the block swap after `1 × w₀`. -/
theorem no_indEquiv_swap_yRev :
    ¬ ∃ e : TensorProductOver (Λ2 ᵍ⊗[ℤ] Λ2) (ZZ 0 0) (ZabT 0 0 (osymABEndo ((yRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem yRev_mem swap_mem))) ≃ᵈᵍ[𝒪2 ᵍ⊗[ℤ] 𝒪2]
        IZ 0 0, ∀ (h : osymDG ((0 + 2) + (0 + 2))) t, e (op h • t) = op h • e t := by
  refine no_indEquiv_of ((yRevPerm (0 + 2) (0 + 2)).trans (swapPerm (0 + 2))) (trans_mem yRev_mem swap_mem) ((swapPerm (0 + 2)).trans (yRevPerm (0 + 2) (0 + 2))) (trans_mem swap_mem yRev_mem) (permPoly_inv (yRevPerm_invol _ _) (swapPerm_invol _)) (permPoly_inv (swapPerm_invol _) (yRevPerm_invol _ _)) fun h => ?_
  have hk := congrArg (kap π02) h
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12⟩ := kap_values
  rw [e2_decomp] at hk
  simp only [map_add, map_mul, map_neg, permPoly_trans, bX2, bY2, bX1, bY1, pbX2, pbY2, pbX1, pbY1, xX2,
    xY2, xX1, xY1, yX2, yY2, yX1, yY1, sX2, sY2, sX1, sY1] at hk
  simp only [map_add, map_neg, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12] at hk
  norm_num at hk

end NoGo


/-- The grade involution `x_i ↦ -x_i` does not commute with `d` (`d x = x²`): sign twists of the variables
do not give dg ring endomorphisms. -/
theorem parityInv_not_dg {N : ℕ} (j : Fin N) :
    d N (parityInv N (generator j)) ≠ parityInv N (d N (generator j)) := by
  rw [parityInv_generator, map_neg, d_generator, map_mul, parityInv_generator, neg_mul_neg]
  intro h
  apply OddMath.SkewPolynomial.generator_square_ne_zero j
  have h2 : (2 : ℤ) • (generator j * generator j : SkewPolynomial N) = (2 : ℤ) • 0 := by
    rw [smul_zero, two_smul]
    nth_rewrite 1 [← h]
    exact neg_add_cancel _
  exact eq_of_zsmul_eq two_ne_zero h2

end Witness

end OddMath.Frontier.EQFunctor