import OddMath.Frontier.EQZabCell
import OddMath.Frontier.EQZabFiltration
import OddMath.Frontier.EQFixW0
import OddMath.Frontier.EQLimaAllRanks
import OddMath.Frontier.SmallRankCyclotomic
import OddMath.Frontier.OddGrassmannSchur
import OddMath.Frontier.EKAutomorphisms
import OddMath.Frontier.EKLSectionTwoG

/-!
# Ellis–Qi, Lemma 4.4: the Borel presentation of the odd Grassmannian ring

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.3.1, Lemma 4.4 and the paragraph before it.

Setting (untwisted odd symmetric polynomials, as in the source): `OΛ_a ⊠ OΛ_b ⊆ OPol_{a+b}` is the
subring generated by the `e_k(x)` and `e_k(y)` (`EQZab.osymAB`); `M` is the *left* submodule of
`OΛ_a ⊠ OΛ_b` generated by the `e_k(x, y)`, `k > 0` (`Mab`), so `(OΛ_a ⊠ OΛ_b)/M` (`BorelQuot`) is
a left `OΛ_a ⊠ OΛ_b`-module. The odd Grassmannian ring is EKL's
`OH_{a,a+b} = OΛ̃_a/⟨h̃_m : m > b⟩` (`SmallRank.OH a (a+b)`, every rank `a`), which `θ` identifies
with the untwisted `OΛ_a/⟨h_m : m > b⟩` of the source.

**Lemma 4.4, as proved here** (`lemma_4_4`). The map
`γ : OH_{a,a+b} → (OΛ_a ⊠ OΛ_b)/M`, `f ↦ (w₀ ∘ θ)(f)(x) mod M` (`gamma`), is well defined and
bijective, with `γ(ẽ_k) = (-1)^{binom(k,2)} e_k(x)` (`gamma_elementary`, the printed formula) and
`γ(h̃_k) = (-1)^k e_k(y)` (`gamma_complete`, as in the printed proof). It is **semilinear** for the
ring map `f ↦ (w₀ ∘ θ)(f)(x)` (`gamma_smul`): for `g` in the untwisted `OΛ_a` acting on `OH_{a,a+b}`
through `θ`, `γ(g · f) = w₀(g)(x) · γ(f)`.

The printed statement calls `γ` an isomorphism of left `OΛ_a`-modules; for the action
`g · [F] = [g(x) F]` this would force `γ(e_2) = e_2(x) γ(1)`, whereas the printed value is
`-e_2(x)`, so the reading recorded here is the `w₀`-semilinear one (ERRATA [EQ] 20). The printed
proof (relation (4.11) of EKL Lemma 2.8, relation (4.12), surjectivity, comparison of graded ranks)
is followed; the rank comparison uses the basis of `OΛ_a ⊠ OΛ_b` over `OΛ_{a+b}` of Corollary 4.8
(`EQZab.zab_span`, `EQZab.zab_indep`) and EKL Proposition 5.4 (`OddGrassmannSchur.proposition_5_4`).
Two-sidedness of `⟨h_m : m > b⟩`: the left ideal generated by the `h_m`, `m > b`, is already
two-sided (`leftIdeal_mul_mem`), from EKL's relations between the `h_k` (`EKAutomorphisms.h_even`,
`h_odd`).
-/

namespace OddMath.Frontier.EQBorel

open OddMath.SkewPolynomial (SkewPolynomial generator)
open OddMath.Frontier.EQSkewDifferential (theta longestPerm elementary osym parityInv skewLift
  ringHom_ext)
open OddMath.Frontier.EQZab (osymAB inclX inclY epsAB phiAB)
open OddMath.Frontier.SmallRank (OLam hAll grassGen grassIdeal)
open FiniteCompleteElementary
open scoped BigOperators

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) eqBorelNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))

local instance (priority := high) eqBorelNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

/-! ## Generalities on skew polynomials -/

theorem sp_mul_assoc {m : ℕ} (x y z : SkewPolynomial m) : x * y * z = x * (y * z) :=
  @mul_assoc _ (@SemigroupWithZero.toSemigroup _ (@NonUnitalSemiring.toSemigroupWithZero _
    (@Semiring.toNonUnitalSemiring _ (OddMath.PbwL3.instSemiring m)))) x y z

theorem sp_zero_mul {m : ℕ} (x : SkewPolynomial m) : 0 * x = 0 :=
  @zero_mul _ (@MulZeroOneClass.toMulZeroClass _ (@MonoidWithZero.toMulZeroOneClass _
    (@Semiring.toMonoidWithZero _ (OddMath.PbwL3.instSemiring m)))) x

theorem sp_mul_zero {m : ℕ} (x : SkewPolynomial m) : x * 0 = 0 :=
  @mul_zero _ (@MulZeroOneClass.toMulZeroClass _ (@MonoidWithZero.toMulZeroOneClass _
    (@Semiring.toMonoidWithZero _ (OddMath.PbwL3.instSemiring m)))) x

/-- Induction over the generators of `OPol_n`. -/
theorem skew_induction {n : ℕ} {P : SkewPolynomial n → Prop} (hgen : ∀ j, P (generator j))
    (hint : ∀ z : ℤ, P (z : SkewPolynomial n)) (hadd : ∀ f g, P f → P g → P (f + g))
    (hmul : ∀ f g, P f → P g → P (f * g)) (u : SkewPolynomial n) : P u := by
  let ρ : FreeAlgebra ℤ (Fin n) →+* SkewPolynomial n :=
    (PbwEquivalence.presentedEquiv n).toRingHom.comp
      (Ideal.Quotient.mk (OddMath.PbwL2.relIdeal n))
  have hρ : Function.Surjective ρ :=
    (PbwEquivalence.presentedEquiv n).surjective.comp Ideal.Quotient.mk_surjective
  obtain ⟨w, rfl⟩ := hρ u
  induction w using FreeAlgebra.induction with
  | grade0 r =>
    have : ρ (algebraMap ℤ (FreeAlgebra ℤ (Fin n)) r) = (r : SkewPolynomial n) := by
      rw [algebraMap_int_eq, eq_intCast, map_intCast]
    rw [this]; exact hint r
  | grade1 j =>
    have : ρ (FreeAlgebra.ι ℤ j) = generator j := OddMath.PbwL3.Phi_q n j
    rw [this]; exact hgen j
  | mul x y hx hy => rw [map_mul]; exact hmul _ _ hx hy
  | add x y hx hy => rw [map_add]; exact hadd _ _ hx hy

/-- The augmentation `OPol_n → ℤ`, `x_i ↦ 0`. -/
def aug (n : ℕ) : SkewPolynomial n →+* ℤ := skewLift (fun _ => (0 : ℤ)) (fun _ _ _ => by simp)

@[simp] theorem aug_generator {n : ℕ} (j : Fin n) : aug n (generator j) = 0 := by
  simp [aug]

theorem aug_longestPerm {n : ℕ} (f : SkewPolynomial n) : aug n (longestPerm n f) = aug n f := by
  have h : (aug n).comp (longestPerm n) = aug n := ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

theorem strictSum_const_zero {R : Type*} [Ring R] :
    ∀ (m k : ℕ), FiniteWords.strictSum (fun _ : Fin m => (0 : R)) (k+1) = 0
  | 0, k => by simp
  | m+1, k => by
    rw [FiniteWords.strictSum_succ, zero_mul, zero_add]
    exact strictSum_const_zero m k

theorem aug_elementary {n k : ℕ} (hk : 0 < k) : aug n (elementary n k) = 0 := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
  rw [elementary, EQZn.ringHom_strictSum]
  simp only [aug_generator]
  exact strictSum_const_zero n k

theorem elementary_eq_zero_of_lt {n k : ℕ} (h : n < k) : elementary n k = 0 := by
  have h1 := EQFix.theta_elementary n k
  rw [elementaryPoly_eq_zero_of_lt h] at h1
  rw [← EQSchur.theta_theta (elementary n k), h1, map_zero]

theorem neg_one_pow_choose_succ (k : ℕ) :
    (-1 : ℤ) ^ ((k+1).choose 2) * (-1) ^ (k.choose 2) = (-1) ^ k := by
  rw [Nat.choose_succ_succ', Nat.choose_one_right, ← pow_add, add_assoc, ← two_mul,
    EQFix.neg_one_pow_add_two_mul]

/-! ## The supercommutation of the two blocks -/

variable {a b : ℕ}

theorem inclY_generator_mul_inclX (j : Fin b) (u : SkewPolynomial a) :
    inclY a b (generator j) * inclX a b u = inclX a b (parityInv a u) * inclY a b (generator j) := by
  induction u using skew_induction with
  | hgen i =>
    rw [EQZab.inclY_generator, EQSkewDifferential.parityInv_generator, map_neg,
      EQZab.inclX_generator, neg_mul]
    have hne : Fin.natAdd a j ≠ Fin.castAdd b i := by
      intro h; have := congrArg Fin.val h; simp at this; omega
    have h := OddMath.PbwL1.rel_sum (Fin.natAdd a j) (Fin.castAdd b i) hne
    exact eq_neg_of_add_eq_zero_left h
  | hint z => simp only [map_intCast]; exact (Int.cast_comm _ _).symm
  | hadd f g hf hg => rw [map_add, map_add, map_add, mul_add, add_mul, hf, hg]
  | hmul f g hf hg =>
    rw [map_mul, map_mul, map_mul, ← sp_mul_assoc, hf, sp_mul_assoc, hg, ← sp_mul_assoc]

theorem strictSum_mul_inclX {m : ℕ} (x : Fin m → SkewPolynomial (a+b))
    (hx : ∀ j u, x j * inclX a b u = inclX a b (parityInv a u) * x j) :
    ∀ (k : ℕ) (u : SkewPolynomial a), FiniteWords.strictSum x k * inclX a b u =
      inclX a b ((parityInv a)^[k] u) * FiniteWords.strictSum x k := by
  induction m with
  | zero =>
    intro k u
    cases k with
    | zero => simp
    | succ k => simp [sp_mul_zero, sp_zero_mul]
  | succ m ih =>
    intro k u
    cases k with
    | zero => simp
    | succ k =>
      rw [FiniteWords.strictSum_succ, add_mul, mul_add, sp_mul_assoc,
        ih (fun i => x i.succ) (fun i => hx i.succ) k u, ← sp_mul_assoc, hx 0,
        ih (fun i => x i.succ) (fun i => hx i.succ) (k+1) u, Function.iterate_succ_apply',
        sp_mul_assoc]

theorem inclY_elementary_mul_inclX (k : ℕ) (u : SkewPolynomial a) :
    inclY a b (elementary b k) * inclX a b u =
      inclX a b ((parityInv a)^[k] u) * inclY a b (elementary b k) := by
  rw [elementary, EQZn.ringHom_strictSum]
  exact strictSum_mul_inclX _ (fun j u => inclY_generator_mul_inclX j u) k u

theorem iterate_parityInv_mem {u : SkewPolynomial a} (hu : u ∈ osym a) (k : ℕ) :
    (parityInv a)^[k] u ∈ osym a := by
  induction k with
  | zero => exact hu
  | succ k ih => rw [Function.iterate_succ_apply']; exact EQSkewDifferential.parityInv_mem_osym ih

/-! ## The map `f ↦ (w₀ ∘ θ)(f)(x)` -/

variable (a b)

/-- `Γ(f) = (w₀ ∘ θ)(f)(x)`. -/
def Γ : SkewPolynomial a →+* SkewPolynomial (a+b) :=
  (inclX a b).comp ((longestPerm a).comp (theta a))

theorem Γ_apply (f : SkewPolynomial a) : Γ a b f = inclX a b (longestPerm a (theta a f)) := rfl

variable {a b}

theorem Γ_mem {f : SkewPolynomial a} (hf : f ∈ OLam a) : Γ a b f ∈ osymAB a b :=
  EQZab.inclX_mem (EQZab.longestPerm_mem_osym (EQLima.theta_mem_osym_of_OLam hf))

/-- Every `u(x)`, `u ∈ OΛ_a`, is in the image of `Γ`. -/
theorem Γ_theta_longestPerm (u : SkewPolynomial a) :
    Γ a b (theta a (longestPerm a u)) = inclX a b u := by
  rw [Γ_apply, EQSchur.theta_theta, EQSchur.longestPerm_longestPerm]

theorem theta_longestPerm_mem {u : SkewPolynomial a} (hu : u ∈ osym a) :
    theta a (longestPerm a u) ∈ OLam a :=
  EQLima.theta_mem_OLam (EQZab.longestPerm_mem_osym hu)

variable (a b)

/-- `Γ` as a ring map `OΛ̃_a → OΛ_a ⊠ OΛ_b`. -/
def gam0 : OLam a →+* osymAB a b :=
  ((Γ a b).comp (OLam a).subtype).codRestrict (osymAB a b) (fun f => Γ_mem f.2)

@[simp] theorem coe_gam0 (f : OLam a) : (gam0 a b f : SkewPolynomial (a+b)) = Γ a b f := rfl

/-! ## The left submodule `M` -/

/-- `e_k(x, y) ∈ OΛ_a ⊠ OΛ_b`. -/
def exy (k : ℕ) : osymAB a b :=
  ⟨elementary (a+b) k, EQZab.osym_le_osymAB (EQZab.elementary_mem _ k)⟩

/-- `e_k(x) ∈ OΛ_a ⊠ OΛ_b`. -/
def ex (k : ℕ) : osymAB a b := ⟨inclX a b (elementary a k), EQZab.inclX_mem (EQZab.elementary_mem a k)⟩

/-- `e_k(y) ∈ OΛ_a ⊠ OΛ_b`. -/
def ey (k : ℕ) : osymAB a b := ⟨inclY a b (elementary b k), EQZab.inclY_mem (EQZab.elementary_mem b k)⟩

/-- `M = (OΛ_a ⊠ OΛ_b) · OΛ_{a+b}^+`, the left submodule generated by the `e_k(x, y)`, `k > 0`. -/
def Mab : Submodule (osymAB a b) (osymAB a b) :=
  Submodule.span (osymAB a b) {F | ∃ k, 0 < k ∧ exy a b k = F}

/-- `(OΛ_a ⊠ OΛ_b)/M`, a left `OΛ_a ⊠ OΛ_b`-module. -/
abbrev BorelQuot := osymAB a b ⧸ Mab a b

variable {a b}

theorem exy_mem_Mab {k : ℕ} (hk : 0 < k) : exy a b k ∈ Mab a b :=
  Submodule.subset_span ⟨k, hk, rfl⟩

theorem mul_exy_mem_Mab (r : osymAB a b) {k : ℕ} (hk : 0 < k) : r * exy a b k ∈ Mab a b :=
  (Mab a b).smul_mem r (exy_mem_Mab hk)

/-- (4.12): `e_k(x, y) = Σ_{p+q=k} e_p(x) e_q(y)`. -/
theorem exy_eq_sum (k : ℕ) :
    exy a b k = ∑ p ∈ Finset.range (k+1), ex a b p * ey a b (k - p) := by
  apply Subtype.ext
  rw [exy, AddSubmonoidClass.coe_finsetSum]
  simp only [Subring.coe_mul, ex, ey]
  rw [EQZab.elementary_add, Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk]

/-- (4.11) pushed through `Γ`: `Σ_{k=0}^N (-1)^k e_k(x) Γ(h̃_{N-k}) = 0` for `N > 0`. -/
theorem sum_ex_gam0_complete {N : ℕ} (hN : 0 < N) :
    ∑ k ∈ Finset.range (N+1), (-1 : ℤ) ^ k • (ex a b k * gam0 a b (hAll a (N - k))) = 0 := by
  apply Subtype.ext
  rw [AddSubmonoidClass.coe_finsetSum, ZeroMemClass.coe_zero]
  have h := congrArg (Γ a b) (elementary_complete_inverse a N hN)
  rw [map_zero, map_sum] at h
  rw [← h]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [AddSubgroupClass.coe_zsmul, Subring.coe_mul, coe_gam0, map_zsmul, map_mul]
  have he : Γ a b (elementaryPoly a k) = (-1 : ℤ) ^ (k.choose 2) • inclX a b (elementary a k) := by
    rw [Γ_apply, ← EQFix.theta_elementary, EQSchur.theta_theta, EQFix.longestPerm_elementary,
      map_zsmul]
  rw [he, smul_mul_assoc, smul_smul, neg_one_pow_choose_succ]
  rfl

/-- `ex 0 = 1`, `ey 0 = 1`. -/
@[simp] theorem ex_zero : ex a b 0 = 1 := Subtype.ext (by simp [ex, elementary])
@[simp] theorem ey_zero : ey a b 0 = 1 := Subtype.ext (by simp [ey, elementary])

theorem ey_eq_zero {k : ℕ} (hk : b < k) : ey a b k = 0 :=
  Subtype.ext (by simp [ey, elementary_eq_zero_of_lt hk])

/-- **Proof of Lemma 4.4**: `Γ(h̃_m) ≡ (-1)^m e_m(y) (mod M)`. -/
theorem gam0_complete_sub_mem (m : ℕ) :
    gam0 a b (hAll a m) - (-1 : ℤ) ^ m • ey a b m ∈ Mab a b := by
  induction m using Nat.strong_induction_on with
  | _ N ih =>
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · simp
  set D : ℕ → osymAB a b := fun j => gam0 a b (hAll a j) - (-1 : ℤ) ^ j • ey a b j with hD
  -- `T = Σ_k (-1)^k e_k(x) D_{N-k}` lies in `M`.
  have hT : ∑ k ∈ Finset.range (N+1), (-1 : ℤ) ^ k • (ex a b k * D (N - k)) ∈ Mab a b := by
    have : ∑ k ∈ Finset.range (N+1), (-1 : ℤ) ^ k • (ex a b k * D (N - k)) =
        -((-1 : ℤ) ^ N • exy a b N) := by
      simp only [hD, mul_sub, smul_sub, Finset.sum_sub_distrib, sum_ex_gam0_complete hN, zero_sub,
        exy_eq_sum, Finset.smul_sum]
      congr 1
      refine Finset.sum_congr rfl fun k hk => ?_
      have hk' : k ≤ N := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
      rw [mul_smul_comm, smul_smul, ← pow_add, Nat.add_sub_cancel' hk']
    rw [this]
    exact (Mab a b).neg_mem ((Mab a b).smul_of_tower_mem _ (exy_mem_Mab hN))
  rw [Finset.sum_range_succ'] at hT
  simp only [pow_zero, one_smul, ex_zero, one_mul, Nat.sub_zero] at hT
  have hrest : ∑ k ∈ Finset.range N, (-1 : ℤ) ^ (k+1) • (ex a b (k+1) * D (N - (k+1))) ∈
      Mab a b := by
    refine (Mab a b).sum_mem fun k hk => (Mab a b).smul_of_tower_mem _ ((Mab a b).smul_mem _ ?_)
    exact ih _ (by have := Finset.mem_range.mp hk; omega)
  have := (Mab a b).sub_mem hT hrest
  rwa [add_sub_cancel_left] at this

theorem gam0_complete_mem {m : ℕ} (hm : b < m) : gam0 a b (hAll a m) ∈ Mab a b := by
  have h := gam0_complete_sub_mem (a := a) (b := b) m
  rwa [ey_eq_zero hm, smul_zero, sub_zero] at h

/-! ## `⟨h_m : m > b⟩` is generated as a left ideal -/

theorem coe_hAll (m : ℕ) : (hAll a m : SkewPolynomial a) = completePoly a m := rfl

theorem complete_even (m k : ℕ) (h : Even (m + k)) :
    hAll a m * hAll a k = hAll a k * hAll a m := by
  apply Subtype.ext
  have := congrArg (OddLREKIdentification.piN a) (EKAutomorphisms.h_even m k h)
  simpa only [map_mul, OddLREKIdentification.piN_h, Subring.coe_mul, coe_hAll] using this

theorem complete_odd (m k : ℕ) (h : Even (m + k)) :
    hAll a m * hAll a (k+1) + (-1 : ℤ) ^ m • (hAll a (k+1) * hAll a m) =
      (-1 : ℤ) ^ m • (hAll a (m+1) * hAll a k) + hAll a k * hAll a (m+1) := by
  apply Subtype.ext
  have := congrArg (OddLREKIdentification.piN a) (EKAutomorphisms.h_odd m k h)
  simpa only [map_add, map_mul, map_zsmul, OddLREKIdentification.piN_h, Subring.coe_mul,
    Subring.coe_add, AddSubgroupClass.coe_zsmul, coe_hAll] using this

variable (a b)

/-- The left ideal of `OΛ̃_a` generated by the `h̃_m`, `m > b`. -/
def leftIdeal : Submodule (OLam a) (OLam a) := Submodule.span (OLam a) (grassGen a (a+b))

variable {a b}

theorem hAll_mem_leftIdeal {m : ℕ} (hm : b < m) : hAll a m ∈ leftIdeal a b :=
  Submodule.subset_span ⟨m, by omega, rfl⟩

theorem complete_mul_mem (k : ℕ) : ∀ m, b < m → hAll a m * hAll a k ∈ leftIdeal a b := by
  induction k with
  | zero => intro m hm; rw [SmallRank.hAll_zero, mul_one]; exact hAll_mem_leftIdeal hm
  | succ k ih =>
    intro m hm
    rcases Nat.even_or_odd (m + (k+1)) with he | ho
    · rw [complete_even m (k+1) he]
      exact (leftIdeal a b).smul_mem _ (hAll_mem_leftIdeal hm)
    · have he : Even (m + k) := by
        rcases ho with ⟨r, hr⟩; exact ⟨r, by omega⟩
      have h := complete_odd (a := a) m k he
      have e : hAll a m * hAll a (k+1) = (-1 : ℤ) ^ m • (hAll a (m+1) * hAll a k) +
          hAll a k * hAll a (m+1) - (-1 : ℤ) ^ m • (hAll a (k+1) * hAll a m) :=
        eq_sub_of_add_eq h
      rw [e]
      refine (leftIdeal a b).sub_mem ((leftIdeal a b).add_mem ?_ ?_) ?_
      · exact (leftIdeal a b).smul_of_tower_mem _ (ih (m+1) (by omega))
      · exact (leftIdeal a b).smul_mem _ (hAll_mem_leftIdeal (by omega))
      · exact (leftIdeal a b).smul_of_tower_mem _ ((leftIdeal a b).smul_mem _
          (hAll_mem_leftIdeal hm))

theorem mul_complete_mem {x : OLam a} (hx : x ∈ leftIdeal a b) (k : ℕ) :
    x * hAll a k ∈ leftIdeal a b := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨m, hm, rfl⟩ := hy
    exact complete_mul_mem k m (by omega)
  | zero => rw [zero_mul]; exact (leftIdeal a b).zero_mem
  | add y z _ _ hy hz => rw [add_mul]; exact (leftIdeal a b).add_mem hy hz
  | smul r y _ hy => rw [smul_eq_mul, mul_assoc]; exact (leftIdeal a b).smul_mem r hy

/-- The subring of `OPol_a` generated by the `h_k`. -/
def completeClosure (a : ℕ) : Subring (SkewPolynomial a) :=
  Subring.closure (Set.range (completePoly a))

theorem completeClosure_le : completeClosure a ≤ OLam a :=
  Subring.closure_le.mpr (by rintro _ ⟨k, rfl⟩; exact SmallRank.complete_mem_OLam a k)

theorem elementaryPoly_mem_completeClosure (N : ℕ) : elementaryPoly a N ∈ completeClosure a := by
  induction N using Nat.strong_induction_on with
  | _ N ih =>
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · rw [elementaryPoly_zero]; exact one_mem _
  have h := elementary_complete_inverse a N hN
  rw [Finset.sum_range_succ, Nat.sub_self, completePoly_zero, mul_one] at h
  have hrest : ∑ k ∈ Finset.range N, (-1 : ℤ) ^ ((k + 1).choose 2) •
      (elementaryPoly a k * completePoly a (N - k)) ∈ completeClosure a :=
    Subring.sum_mem _ fun k hk => Subring.zsmul_mem _ (Subring.mul_mem _
      (ih k (Finset.mem_range.mp hk)) (Subring.subset_closure ⟨_, rfl⟩)) _
  have e : elementaryPoly a N = (-1 : ℤ) ^ ((N + 1).choose 2) • -(∑ k ∈ Finset.range N,
      (-1 : ℤ) ^ ((k + 1).choose 2) • (elementaryPoly a k * completePoly a (N - k))) := by
    rw [← eq_neg_of_add_eq_zero_right h, smul_smul, ← pow_add, ← two_mul,
      pow_mul, neg_one_sq, one_pow, one_smul]
  rw [e]
  exact Subring.zsmul_mem _ (Subring.neg_mem _ hrest) _

theorem OLam_le_completeClosure : OLam a ≤ completeClosure a := by
  rw [SmallRank.OLam_eq_elementaryClosure]
  exact Subring.closure_le.mpr (by
    rintro _ ⟨k, -, -, rfl⟩; exact elementaryPoly_mem_completeClosure k)

/-- `⟨h̃_m : m > b⟩` is closed under right multiplication. -/
theorem leftIdeal_mul_mem {x : OLam a} (hx : x ∈ leftIdeal a b) (r : OLam a) :
    x * r ∈ leftIdeal a b := by
  obtain ⟨r, hr⟩ := r
  have hrC : r ∈ completeClosure a := OLam_le_completeClosure hr
  suffices H : ∀ (s : SkewPolynomial a) (hs : s ∈ completeClosure a), ∀ y ∈ leftIdeal a b,
      y * ⟨s, completeClosure_le hs⟩ ∈ leftIdeal a b from H r hrC x hx
  intro s hs
  induction hs using Subring.closure_induction with
  | mem s hs =>
    obtain ⟨k, rfl⟩ := hs
    intro y hy
    exact mul_complete_mem hy k
  | zero => intro y _; convert (leftIdeal a b).zero_mem; exact mul_zero y
  | one => intro y hy; convert hy; exact mul_one y
  | add s t _ _ hs ht =>
    intro y hy
    have : y * ⟨s + t, completeClosure_le (Subring.add_mem _ ‹_› ‹_›)⟩ =
        y * ⟨s, completeClosure_le ‹_›⟩ + y * ⟨t, completeClosure_le ‹_›⟩ := by
      rw [← mul_add]; rfl
    rw [this]; exact (leftIdeal a b).add_mem (hs y hy) (ht y hy)
  | neg s _ hs =>
    intro y hy
    have : y * ⟨-s, completeClosure_le (Subring.neg_mem _ ‹_›)⟩ =
        -(y * ⟨s, completeClosure_le ‹_›⟩) := by
      rw [← mul_neg]; rfl
    rw [this]; exact (leftIdeal a b).neg_mem (hs y hy)
  | mul s t _ _ hs ht =>
    intro y hy
    have : y * ⟨s * t, completeClosure_le (Subring.mul_mem _ ‹_› ‹_›)⟩ =
        y * ⟨s, completeClosure_le ‹_›⟩ * ⟨t, completeClosure_le ‹_›⟩ := by
      rw [mul_assoc]; rfl
    rw [this]; exact ht _ (hs y hy)

theorem grassIdeal_le_leftIdeal {x : OLam a} (hx : x ∈ grassIdeal a (a+b)) :
    x ∈ leftIdeal a b := by
  let J : TwoSidedIdeal (OLam a) := TwoSidedIdeal.mk' (leftIdeal a b)
    (leftIdeal a b).zero_mem (fun hx hy => (leftIdeal a b).add_mem hx hy)
    (fun hx => (leftIdeal a b).neg_mem hx) (fun hy => (leftIdeal a b).smul_mem _ hy)
    (fun hx => leftIdeal_mul_mem hx _)
  have hle : grassIdeal a (a+b) ≤ J := TwoSidedIdeal.span_le.mpr fun y hy => by
    show y ∈ (J : Set (OLam a))
    exact (TwoSidedIdeal.mem_mk' _ _ _ _ _ _ _).mpr (Submodule.subset_span hy)
  exact (TwoSidedIdeal.mem_mk' _ _ _ _ _ _ _).mp (hle hx)

/-! ## The map `γ` -/

variable (a b)

/-- `f ↦ Γ(f) mod M`, semilinear along `gam0`. -/
def gam1 : OLam a →ₛₗ[gam0 a b] BorelQuot a b where
  toFun f := Submodule.Quotient.mk (gam0 a b f)
  map_add' f g := by rw [map_add]; rfl
  map_smul' g f := by
    rw [smul_eq_mul, map_mul, ← smul_eq_mul, Submodule.Quotient.mk_smul]

variable {a b}

theorem gam1_apply (f : OLam a) : gam1 a b f = Submodule.Quotient.mk (gam0 a b f) := rfl

theorem grassIdeal_le_ker : (grassIdeal a (a+b)).asIdeal ≤ LinearMap.ker (gam1 a b) := by
  intro x hx
  have hL : leftIdeal a b ≤ LinearMap.ker (gam1 a b) := Submodule.span_le.mpr fun y hy => by
    obtain ⟨m, hm, rfl⟩ := hy
    rw [SetLike.mem_coe, LinearMap.mem_ker, gam1_apply, Submodule.Quotient.mk_eq_zero]
    exact gam0_complete_mem (by omega)
  exact hL (grassIdeal_le_leftIdeal (TwoSidedIdeal.mem_asIdeal.mp hx))

variable (a b)

/-- **Ellis–Qi, Lemma 4.4**, the map `γ : OH_{a,a+b} → (OΛ_a ⊠ OΛ_b)/M`,
`f ↦ (w₀ ∘ θ)(f)(x) mod M`, on `OH_{a,a+b} = OΛ̃_a/⟨h̃_m : m > b⟩` (`SmallRank.OH a (a+b)`). -/
def gamma : (OLam a ⧸ (grassIdeal a (a+b)).asIdeal) →ₛₗ[gam0 a b] BorelQuot a b :=
  (grassIdeal a (a+b)).asIdeal.liftQ (gam1 a b) grassIdeal_le_ker

variable {a b}

theorem gamma_mk (f : OLam a) :
    gamma a b (Submodule.Quotient.mk f) = Submodule.Quotient.mk (gam0 a b f) := rfl

/-- Semilinearity: `γ(g · f) = Γ(g) · γ(f)`; for `g = θ(g')`, `Γ(g) = w₀(g')(x)`. -/
theorem gamma_smul (g : OLam a) (x : OLam a ⧸ (grassIdeal a (a+b)).asIdeal) :
    gamma a b (g • x) = gam0 a b g • gamma a b x :=
  map_smulₛₗ (gamma a b) g x

theorem elementaryPoly_mem_OLam (k : ℕ) : elementaryPoly a k ∈ OLam a := by
  rw [← EQFix.theta_elementary]; exact EQLima.theta_mem_OLam (EQZab.elementary_mem a k)

/-- The printed formula: `γ(ẽ_k) = (-1)^{binom(k,2)} e_k(x)`. -/
theorem gamma_elementary (k : ℕ) :
    gamma a b (Submodule.Quotient.mk ⟨elementaryPoly a k, elementaryPoly_mem_OLam k⟩) =
      (-1 : ℤ) ^ (k.choose 2) • Submodule.Quotient.mk (ex a b k) := by
  rw [gamma_mk, ← Submodule.Quotient.mk_smul]
  congr 1
  apply Subtype.ext
  rw [coe_gam0, AddSubgroupClass.coe_zsmul, Γ_apply]
  show inclX a b (longestPerm a (theta a (elementaryPoly a k))) = _
  rw [← EQFix.theta_elementary, EQSchur.theta_theta,
    EQFix.longestPerm_elementary, map_zsmul]
  rfl

/-- As in the printed proof: `γ(h̃_k) = (-1)^k e_k(y)`. -/
theorem gamma_complete (k : ℕ) :
    gamma a b (Submodule.Quotient.mk (hAll a k)) =
      (-1 : ℤ) ^ k • Submodule.Quotient.mk (ey a b k) := by
  rw [gamma_mk, ← Submodule.Quotient.mk_smul, eq_comm, Submodule.Quotient.eq, ← neg_sub]
  exact (Mab a b).neg_mem (gam0_complete_sub_mem k)

/-! ## Surjectivity -/

/-- `F ≡ Γ(f) (mod M)` for some `f`. -/
def InImage (F : osymAB a b) : Prop := ∃ f : OLam a, F - gam0 a b f ∈ Mab a b

theorem InImage.add {F G : osymAB a b} (hF : InImage F) (hG : InImage G) : InImage (F + G) := by
  obtain ⟨f, hf⟩ := hF; obtain ⟨g, hg⟩ := hG
  exact ⟨f + g, by rw [map_add, add_sub_add_comm]; exact (Mab a b).add_mem hf hg⟩

theorem InImage.neg {F : osymAB a b} (hF : InImage F) : InImage (-F) := by
  obtain ⟨f, hf⟩ := hF
  exact ⟨-f, by rw [map_neg, neg_sub_neg, ← neg_sub]; exact (Mab a b).neg_mem hf⟩

theorem InImage.of_mem {F : osymAB a b} (hF : F ∈ Mab a b) : InImage F :=
  ⟨0, by rwa [map_zero, sub_zero]⟩

theorem InImage.sum {ι : Type*} (s : Finset ι) {F : ι → osymAB a b}
    (h : ∀ i ∈ s, InImage (F i)) : InImage (∑ i ∈ s, F i) := by
  classical
  induction s using Finset.induction_on with
  | empty => exact InImage.of_mem (by rw [Finset.sum_empty]; exact zero_mem _)
  | insert p s hp hs =>
    rw [Finset.sum_insert hp]
    exact (h p (Finset.mem_insert_self p s)).add
      (hs fun i hi => h i (Finset.mem_insert_of_mem hi))

theorem InImage.gam0 (f : OLam a) : InImage (gam0 a b f) := ⟨f, by rw [sub_self]; exact zero_mem _⟩

theorem inImage_inclX (u : SkewPolynomial a) (hu : u ∈ osym a) :
    gam0 a b ⟨theta a (longestPerm a u), theta_longestPerm_mem hu⟩ =
      ⟨inclX a b u, EQZab.inclX_mem hu⟩ :=
  Subtype.ext (Γ_theta_longestPerm u)

theorem inImage_inclX_mul_ey (k : ℕ) : ∀ (u : SkewPolynomial a) (hu : u ∈ osym a),
    InImage (⟨inclX a b u, EQZab.inclX_mem hu⟩ * ey a b k) := by
  induction k using Nat.strong_induction_on with
  | _ k ih =>
  intro u hu
  rcases Nat.eq_zero_or_pos k with rfl | hk
  · rw [ey_zero, mul_one, ← inImage_inclX u hu]; exact InImage.gam0 _
  -- `u(x) e_k(x,y) = Σ_p (u e_p)(x) e_{k-p}(y)`
  have hsplit : (⟨inclX a b u, EQZab.inclX_mem hu⟩ : osymAB a b) * ey a b k =
      (⟨inclX a b u, EQZab.inclX_mem hu⟩ : osymAB a b) * exy a b k -
        ∑ p ∈ Finset.range k, (⟨inclX a b (u * elementary a (p+1)),
          EQZab.inclX_mem (Subring.mul_mem _ hu (EQZab.elementary_mem a (p+1)))⟩ : osymAB a b) *
          ey a b (k - (p+1)) := by
    rw [exy_eq_sum, Finset.sum_range_succ', mul_add, Finset.mul_sum, ex_zero, one_mul,
      Nat.sub_zero]
    have hs : ∑ p ∈ Finset.range k, (⟨inclX a b u, EQZab.inclX_mem hu⟩ : osymAB a b) *
        (ex a b (p+1) * ey a b (k - (p+1))) = ∑ p ∈ Finset.range k,
          (⟨inclX a b (u * elementary a (p+1)),
            EQZab.inclX_mem (Subring.mul_mem _ hu (EQZab.elementary_mem a (p+1)))⟩ : osymAB a b) *
          ey a b (k - (p+1)) := by
      refine Finset.sum_congr rfl fun p _ => ?_
      rw [← mul_assoc]
      congr 1
      exact Subtype.ext (map_mul (inclX a b) u (elementary a (p+1))).symm
    rw [hs, add_sub_cancel_left]
  rw [hsplit, sub_eq_add_neg]
  refine (InImage.of_mem (mul_exy_mem_Mab _ hk)).add (InImage.neg ?_)
  exact InImage.sum _ fun p hp => ih (k - (p+1)) (by have := Finset.mem_range.mp hp; omega)
    (u * elementary a (p+1)) (Subring.mul_mem _ hu (EQZab.elementary_mem a (p+1)))

theorem ey_mul_gam0 (k : ℕ) (f : OLam a) : InImage (ey a b k * gam0 a b f) := by
  have hu : longestPerm a (theta a f) ∈ osym a :=
    EQZab.longestPerm_mem_osym (EQLima.theta_mem_osym_of_OLam f.2)
  have e : ey a b k * gam0 a b f =
      ⟨inclX a b ((parityInv a)^[k] (longestPerm a (theta a f))),
        EQZab.inclX_mem (iterate_parityInv_mem hu k)⟩ * ey a b k :=
    Subtype.ext (inclY_elementary_mul_inclX k _)
  rw [e]
  exact inImage_inclX_mul_ey k _ (iterate_parityInv_mem hu k)

/-- Every element of `OΛ_a ⊠ OΛ_b` is congruent to some `Γ(f)` modulo `M`. -/
theorem inImage (F : osymAB a b) : InImage F := by
  let S : Set (SkewPolynomial (a+b)) := Set.range (fun k => inclX a b (elementary a k)) ∪
    Set.range (fun k => inclY a b (elementary b k))
  suffices H : ∀ (F : SkewPolynomial (a+b)) (hF : F ∈ Subring.closure S) (G : osymAB a b),
      InImage G → InImage ((⟨F, hF⟩ : osymAB a b) * G) by
    have := H F.1 F.2 1 ⟨1, by rw [map_one, sub_self]; exact zero_mem _⟩
    rwa [mul_one] at this
  intro F hF
  induction hF using Subring.closure_induction with
  | mem F hF =>
    intro G hG
    obtain ⟨f, hf⟩ := hG
    rcases hF with ⟨k, rfl⟩ | ⟨k, rfl⟩
    · have hu := EQZab.elementary_mem a k
      have e : ∀ h, (⟨inclX a b (elementary a k), h⟩ : osymAB a b) =
          gam0 a b ⟨_, theta_longestPerm_mem hu⟩ := fun h => Subtype.ext (Γ_theta_longestPerm _).symm
      refine ⟨⟨_, theta_longestPerm_mem hu⟩ * f, ?_⟩
      rw [e, map_mul, ← mul_sub]
      exact (Mab a b).smul_mem _ hf
    · have e : ∀ h, (⟨inclY a b (elementary b k), h⟩ : osymAB a b) = ey a b k := fun h => rfl
      rw [e, show ey a b k * G = ey a b k * gam0 a b f + ey a b k * (G - gam0 a b f) by
        rw [← mul_add, add_sub_cancel]]
      exact (ey_mul_gam0 k f).add (InImage.of_mem ((Mab a b).smul_mem _ hf))
  | zero =>
    intro G _
    rw [show (⟨0, zero_mem _⟩ : osymAB a b) = 0 from rfl, zero_mul]
    exact InImage.of_mem (zero_mem _)
  | one =>
    intro G hG
    rwa [show (⟨1, one_mem _⟩ : osymAB a b) = 1 from rfl, one_mul]
  | add F F' hF₁ hF₂ hF hF' =>
    intro G hG
    rw [show (⟨F + F', add_mem hF₁ hF₂⟩ : osymAB a b) = ⟨F, hF₁⟩ + ⟨F', hF₂⟩ from rfl, add_mul]
    exact (hF G hG).add (hF' G hG)
  | neg F hF₁ hF =>
    intro G hG
    rw [show (⟨-F, neg_mem hF₁⟩ : osymAB a b) = -⟨F, hF₁⟩ from rfl, neg_mul]
    exact (hF G hG).neg
  | mul F F' hF₁ hF₂ hF hF' =>
    intro G hG
    rw [show (⟨F * F', mul_mem hF₁ hF₂⟩ : osymAB a b) = ⟨F, hF₁⟩ * ⟨F', hF₂⟩ from rfl, mul_assoc]
    exact hF _ (hF' G hG)

theorem gamma_surjective : Function.Surjective (gamma a b) := by
  intro y
  obtain ⟨F, rfl⟩ := Submodule.Quotient.mk_surjective _ y
  obtain ⟨f, hf⟩ := inImage F
  exact ⟨Submodule.Quotient.mk f, by rw [gamma_mk, eq_comm, Submodule.Quotient.eq]; exact hf⟩

/-! ## Injectivity: the coefficient functionals -/

variable (a b)

/-- The index set `Par(b, a)` of the basis of Corollary 4.8. -/
abbrev Idx : Type := ↥(BoxPartitionCount.box b a)

variable {a b}

/-- Basis coefficients for `ε(F) = Σ_μ s_μ(y) φ(c_μ)` (`EQZab.zab_span`). -/
def coeffs (F : osymAB a b) : (Fin b → ℕ) → SkewPolynomial (a+b) :=
  (EQZab.zab_span (EQZab.epsAB_mem F.2)).choose

theorem coeffs_mem (F : osymAB a b) (μ : Fin b → ℕ) : coeffs F μ ∈ osym (a+b) :=
  (EQZab.zab_span (EQZab.epsAB_mem F.2)).choose_spec.1 μ

theorem coeffs_spec (F : osymAB a b) :
    epsAB a b F = ∑ μ ∈ BoxPartitionCount.box b a,
      inclY a b (EQSchur.untwisted b μ) * phiAB a b (coeffs F μ) :=
  (EQZab.zab_span (EQZab.epsAB_mem F.2)).choose_spec.2

theorem coeffs_unique (F : osymAB a b) (c : (Fin b → ℕ) → SkewPolynomial (a+b))
    (hc : ∀ μ, c μ ∈ osym (a+b))
    (h : epsAB a b F = ∑ μ ∈ BoxPartitionCount.box b a,
      inclY a b (EQSchur.untwisted b μ) * phiAB a b (c μ)) :
    ∀ μ ∈ BoxPartitionCount.box b a, coeffs F μ = c μ := by
  intro μ hμ
  have h0 : ∑ μ ∈ BoxPartitionCount.box b a,
      inclY a b (EQSchur.untwisted b μ) * phiAB a b (coeffs F μ - c μ) = 0 := by
    simp only [map_sub, mul_sub, Finset.sum_sub_distrib, ← coeffs_spec, ← h, sub_self]
  exact sub_eq_zero.mp (EQZab.zab_indep _ (fun μ => sub_mem (coeffs_mem F μ) (hc μ)) h0 μ hμ)

theorem epsAB_epsAB (f : SkewPolynomial (a+b)) : epsAB a b (epsAB a b f) = f := by
  have h : (epsAB a b).comp (epsAB a b) = RingHom.id _ := ringHom_ext fun j => by
    simp only [RingHom.comp_apply, EQZab.epsAB, EQZab.diagHom_generator, map_zsmul, smul_smul,
      RingHom.id_apply, EQZab.epsCoeff]
    split_ifs <;> simp [← mul_pow]
  exact RingHom.congr_fun h f

variable (a b)

/-- The functionals `F ↦ aug(c_μ(F))`. -/
def Λ : osymAB a b →+ (Idx a b → ℤ) where
  toFun F μ := aug (a+b) (coeffs F μ.1)
  map_zero' := by
    funext μ
    have := coeffs_unique (0 : osymAB a b) (fun _ => 0) (fun _ => zero_mem _)
      (by simp [sp_mul_zero]) μ.1 μ.2
    simp [this]
  map_add' F G := by
    funext μ
    have := coeffs_unique (F + G) (fun ν => coeffs F ν + coeffs G ν)
      (fun ν => add_mem (coeffs_mem F ν) (coeffs_mem G ν))
      (by simp only [Subring.coe_add, map_add, coeffs_spec, ← Finset.sum_add_distrib, mul_add])
      μ.1 μ.2
    simp [this]

variable {a b}

theorem Λ_mul_exy (r : osymAB a b) {k : ℕ} (hk : 0 < k) : Λ a b (r * exy a b k) = 0 := by
  funext μ
  have he : epsAB a b (elementary (a+b) k) = phiAB a b (longestPerm (a+b) (elementary (a+b) k)) := by
    rw [EQZab.phiAB, RingHom.comp_apply, EQSchur.longestPerm_longestPerm]
  have := coeffs_unique (r * exy a b k)
    (fun ν => coeffs r ν * longestPerm (a+b) (elementary (a+b) k))
    (fun ν => Subring.mul_mem _ (coeffs_mem r ν)
      (EQZab.longestPerm_mem_osym (EQZab.elementary_mem _ k)))
    (by
      rw [Subring.coe_mul, map_mul, coeffs_spec, exy, he, Finset.sum_mul]
      refine Finset.sum_congr rfl fun ν _ => ?_
      rw [map_mul, sp_mul_assoc])
    μ.1 μ.2
  simp only [Λ, AddMonoidHom.coe_mk, ZeroHom.coe_mk, this, map_mul, aug_longestPerm,
    aug_elementary hk, mul_zero, Pi.zero_apply]

theorem Λ_eq_zero {F : osymAB a b} (hF : F ∈ Mab a b) : Λ a b F = 0 := by
  suffices H : ∀ r : osymAB a b, Λ a b (r * F) = 0 by simpa using H 1
  induction hF using Submodule.span_induction with
  | mem y hy => obtain ⟨k, hk, rfl⟩ := hy; exact fun r => Λ_mul_exy r hk
  | zero => intro r; rw [mul_zero, map_zero]
  | add y z _ _ hy hz => intro r; rw [mul_add, map_add, hy, hz, add_zero]
  | smul s y _ hy => intro r; rw [smul_eq_mul, ← mul_assoc]; exact hy _

/-- The basis element `ε(s_β(y))`, with `Λ = δ_β`. -/
def basisElt (β : Idx a b) : osymAB a b :=
  ⟨epsAB a b (inclY a b (EQSchur.untwisted b β.1)),
    EQZab.epsAB_mem (EQZab.inclY_mem (EQZab.untwisted_mem_osym β.1))⟩

theorem Λ_basisElt (β : Idx a b) : Λ a b (basisElt β) = Pi.single β 1 := by
  classical
  funext μ
  have := coeffs_unique (basisElt β) (fun ν => if ν = β.1 then 1 else 0)
    (fun ν => by split_ifs; exacts [one_mem _, zero_mem _])
    (by
      rw [basisElt, epsAB_epsAB, Finset.sum_eq_single β.1]
      · simp
      · intro ν _ hν; simp [hν, sp_mul_zero]
      · intro h; exact absurd β.2 h)
    μ.1 μ.2
  simp only [Λ, AddMonoidHom.coe_mk, ZeroHom.coe_mk, this]
  by_cases h : μ = β
  · subst h; simp
  · have h' : μ.1 ≠ β.1 := fun e => h (Subtype.ext e)
    simp [h, h']

theorem Λ_surjective : Function.Surjective (Λ a b) := by
  classical
  intro v
  refine ⟨∑ β, v β • basisElt β, ?_⟩
  rw [map_sum]
  simp only [map_zsmul, Λ_basisElt]
  funext μ
  simp [Finset.sum_apply, Pi.single_apply]

/-- `Λ ∘ γ`, as an additive map out of `OH_{a,a+b}`. -/
def T : (OLam a ⧸ (grassIdeal a (a+b)).asIdeal) →+ (Idx a b → ℤ) :=
  QuotientAddGroup.lift ((grassIdeal a (a+b)).asIdeal.toAddSubgroup)
    ((Λ a b).comp (gam0 a b).toAddMonoidHom) (fun x hx => by
      have h := grassIdeal_le_ker hx
      rw [LinearMap.mem_ker, gam1_apply, Submodule.Quotient.mk_eq_zero] at h
      exact Λ_eq_zero h)

theorem T_mk (f : OLam a) : T (Submodule.Quotient.mk f) = Λ a b (gam0 a b f) := rfl

theorem T_surjective : Function.Surjective (T (a := a) (b := b)) := by
  intro v
  obtain ⟨F, rfl⟩ := Λ_surjective v
  obtain ⟨f, hf⟩ := inImage F
  refine ⟨Submodule.Quotient.mk f, ?_⟩
  rw [T_mk]
  have := Λ_eq_zero hf
  rw [map_sub, sub_eq_zero] at this
  exact this.symm

/-- `OH_{a,a+b}` is free of rank `binom(a+b, a)` (EKL Proposition 5.4 for `a ≥ 2`). -/
theorem exists_basis_OH (a b : ℕ) : ∃ (ι : Type) (_ : Fintype ι),
    Fintype.card ι = (a+b).choose a ∧ Nonempty (Module.Basis ι ℤ (SmallRank.OH a (a+b))) := by
  match a with
  | 0 => exact ⟨Fin 1, inferInstance, by simp, ⟨SmallRank.basis_OH_zero _⟩⟩
  | 1 => exact ⟨Fin (1+b), inferInstance, by simp, ⟨SmallRank.basis_OH_one _⟩⟩
  | n+2 => exact ⟨_, inferInstance, OddGrassmannSchur.card_boxShape _ _,
      ⟨OddGrassmannSchur.proposition_5_4 n b⟩⟩

theorem T_injective : Function.Injective (T (a := a) (b := b)) := by
  obtain ⟨ι, _, hcard, ⟨B⟩⟩ := exists_basis_OH a b
  have hc : Fintype.card ι = Fintype.card (Idx a b) := by
    rw [hcard, Fintype.card_coe, BoxPartitionCount.card_box, add_comm b a, Nat.choose_symm_add]
  let e : (Idx a b → ℤ) ≃ₗ[ℤ] SmallRank.OH a (a+b) :=
    (LinearEquiv.funCongrLeft ℤ ℤ (Fintype.equivOfCardEq hc)).trans B.equivFun.symm
  let Tl : SmallRank.OH a (a+b) →ₗ[ℤ] (Idx a b → ℤ) := (T (a := a) (b := b)).toIntLinearMap
  have hs : Function.Surjective (Tl ∘ₗ e.toLinearMap) :=
    T_surjective.comp e.surjective
  have hi := OrzechProperty.injective_of_surjective_endomorphism _ hs
  intro x y hxy
  obtain ⟨x, rfl⟩ := e.surjective x
  obtain ⟨y, rfl⟩ := e.surjective y
  exact congrArg e (hi hxy)

theorem gamma_injective : Function.Injective (gamma a b) := by
  rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
  intro x hx
  obtain ⟨f, rfl⟩ := Submodule.Quotient.mk_surjective _ x
  rw [LinearMap.mem_ker, gamma_mk, Submodule.Quotient.mk_eq_zero] at hx
  apply T_injective
  rw [T_mk, Λ_eq_zero hx, map_zero]

/-- **Ellis–Qi, Lemma 4.4** (`w₀`-semilinear reading). The map
`γ : OH_{a,a+b} → (OΛ_a ⊠ OΛ_b)/M`, `f ↦ (w₀ ∘ θ)(f)(x) mod M`, is well defined (`gamma`) and
bijective; it is semilinear along `f ↦ (w₀ ∘ θ)(f)(x)` (`gamma_smul`) and sends `ẽ_k` to
`(-1)^{binom(k,2)} e_k(x)` (`gamma_elementary`) and `h̃_k` to `(-1)^k e_k(y)` (`gamma_complete`). -/
theorem lemma_4_4 (a b : ℕ) : Function.Bijective (gamma a b) :=
  ⟨gamma_injective, gamma_surjective⟩

/-! ## The printed (linear) reading fails -/

theorem shape11_box :
    EKLSectionTwo.shape11.colLen 0 ≤ 2 ∧ EKLSectionTwo.shape11.rowLen 0 ≤ 2 := by
  change (YoungDiagram.ofRowLens [1,1] (by decide)).colLen 0 ≤ 2 ∧
    (YoungDiagram.ofRowLens [1,1] (by decide)).rowLen 0 ≤ 2
  constructor
  · have h := YoungDiagram.rowLens_length_ofRowLens (w := [1,1]) (hw := by decide) (by decide)
    rw [YoungDiagram.length_rowLens] at h
    rw [h]; decide
  · have h := YoungDiagram.rowLen_ofRowLens (w := [1,1]) (hw := by decide) ⟨0, by decide⟩
    rw [show ((⟨0, by decide⟩ : Fin [1,1].length) : ℕ) = 0 from rfl] at h
    rw [h]; decide

/-- `ẽ_2 = h̃_2 − h̃_1²` in `OPol_2`. -/
theorem elementaryPoly_two :
    elementaryPoly 2 2 = completePoly 2 2 - completePoly 2 1 * completePoly 2 1 := by
  have h1 := elementary_complete_inverse 2 1 (by norm_num)
  have h2 := elementary_complete_inverse 2 2 (by norm_num)
  rw [Finset.sum_range_succ, Finset.sum_range_one] at h1
  rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_one] at h2
  norm_num at h1 h2
  have he1 : elementaryPoly 2 1 = completePoly 2 1 := by
    rw [← sub_eq_zero, ← neg_eq_zero, ← h1]; abel
  rw [he1] at h2
  rw [← sub_eq_zero, ← neg_eq_zero, ← h2]; abel

/-- `ẽ_2 ≠ 0` in `OH_{2,4}`: up to sign it is the basis vector `s_{(1,1)}` of EKL Proposition 5.4. -/
theorem mk_elementaryPoly_two_ne_zero :
    (Submodule.Quotient.mk ⟨elementaryPoly 2 2, elementaryPoly_mem_OLam 2⟩ :
      OLam 2 ⧸ (grassIdeal 2 (2+2)).asIdeal) ≠ 0 := by
  have hb := (OddGrassmannSchur.proposition_5_4 0 2).ne_zero ⟨EKLSectionTwo.shape11, shape11_box⟩
  rw [OddGrassmannSchur.proposition_5_4_apply, EKLSectionTwo.sK_shape11, map_sub, map_mul,
    OddGrassmannSchur.piA_h, OddGrassmannSchur.piA_h] at hb
  intro h
  apply hb
  have e : (⟨elementaryPoly 2 2, elementaryPoly_mem_OLam 2⟩ : OLam 2) =
      -(Cyclotomic.hK 0 1 * Cyclotomic.hK 0 1 - Cyclotomic.hK 0 2) := by
    apply Subtype.ext
    show elementaryPoly 2 2 = _
    rw [elementaryPoly_two]
    show _ = -((completePoly 2 1 * completePoly 2 1) - completePoly 2 2)
    rw [neg_sub]
  rw [e, Submodule.Quotient.mk_neg, neg_eq_zero] at h
  exact h

/-- **The printed Lemma 4.4 is false** (ERRATA [EQ] 20): for `(a, b) = (2, 2)` there is no additive
map `L : OH_{2,4} → (OΛ_2 ⊠ OΛ_2)/M` that is left `OΛ_2`-linear (`g ∈ OΛ_2` acting by `θ(g)` on
`OH_{2,4} = OΛ̃_2/⟨h̃_m : m > 2⟩` and by `g(x)` on the target) and takes the printed values
`ẽ_k ↦ (-1)^{binom(k,2)} e_k(x)`. -/
theorem lemma_4_4_printed_false :
    ¬ ∃ L : (OLam 2 ⧸ (grassIdeal 2 (2+2)).asIdeal) →+ BorelQuot 2 2,
      (∀ (g : SkewPolynomial 2) (hg : g ∈ osym 2) (x : OLam 2 ⧸ (grassIdeal 2 (2+2)).asIdeal),
        L ((⟨theta 2 g, EQLima.theta_mem_OLam hg⟩ : OLam 2) • x) =
          (⟨inclX 2 2 g, EQZab.inclX_mem hg⟩ : osymAB 2 2) • L x) ∧
      ∀ k, L (Submodule.Quotient.mk ⟨elementaryPoly 2 k, elementaryPoly_mem_OLam k⟩) =
        (-1 : ℤ) ^ (k.choose 2) • Submodule.Quotient.mk (ex 2 2 k) := by
  rintro ⟨L, hlin, hval⟩
  have h0 := hval 0
  have hone : (⟨elementaryPoly 2 0, elementaryPoly_mem_OLam 0⟩ : OLam 2) = 1 :=
    Subtype.ext (elementaryPoly_zero 2)
  rw [hone, ex_zero] at h0
  simp only [Nat.choose_zero_succ, pow_zero, one_smul] at h0
  have hl := hlin (elementary 2 2) (EQZab.elementary_mem 2 2) (Submodule.Quotient.mk 1)
  have ht : (⟨theta 2 (elementary 2 2), EQLima.theta_mem_OLam (EQZab.elementary_mem 2 2)⟩ :
      OLam 2) = ⟨elementaryPoly 2 2, elementaryPoly_mem_OLam 2⟩ :=
    Subtype.ext (EQFix.theta_elementary 2 2)
  rw [ht, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one, h0, ← Submodule.Quotient.mk_smul,
    smul_eq_mul, mul_one, hval 2] at hl
  -- `-[e_2(x)] = [e_2(x)]`
  have h2 : (2 : ℤ) • (Submodule.Quotient.mk (ex 2 2 2) : BorelQuot 2 2) = 0 := by
    have : (-1 : ℤ) ^ (Nat.choose 2 2) = -1 := by norm_num
    rw [this, neg_one_smul] at hl
    have hl' : -(Submodule.Quotient.mk (ex 2 2 2) : BorelQuot 2 2) =
      Submodule.Quotient.mk (ex 2 2 2) := hl
    rw [two_smul]
    nth_rewrite 1 [← hl']
    exact neg_add_cancel _
  have hg := gamma_elementary (a := 2) (b := 2) 2
  have : (-1 : ℤ) ^ (Nat.choose 2 2) = -1 := by norm_num
  rw [this, neg_one_smul] at hg
  have hγ : gamma 2 2 ((2 : ℤ) • Submodule.Quotient.mk
      ⟨elementaryPoly 2 2, elementaryPoly_mem_OLam 2⟩) = 0 := by
    rw [map_zsmul, hg, smul_neg, h2, neg_zero]
  have hz := gamma_injective (hγ.trans (map_zero _).symm)
  obtain ⟨ι, _, -, ⟨B⟩⟩ := exists_basis_OH 2 2
  have hx : B.repr (Submodule.Quotient.mk ⟨elementaryPoly 2 2, elementaryPoly_mem_OLam 2⟩) = 0 := by
    ext i
    have := congrArg (fun y => B.repr y i) hz
    simp only [map_zsmul, Finsupp.smul_apply, smul_eq_mul, map_zero, Finsupp.coe_zero,
      Pi.zero_apply] at this
    simpa using this
  exact mk_elementaryPoly_two_ne_zero (B.repr.injective (hx.trans (map_zero _).symm))

end

end OddMath.Frontier.EQBorel
