import OddMath.Frontier.EQFixZabCells

/-!
# `OΛ_a ⊗ OΛ_b` as a dg ring

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.3.1 (the algebra `OΛ_{a,b} = OΛ_a ⊗ OΛ_b` and the inclusion `OΛ_{a+b} ⊆ OΛ_{a,b}`) and §4.4
(the dg algebras of Definitions 4.14 and 4.15; printed numbering).

`OΛ_a ⊗ OΛ_b` is realized inside `OPol_{a+b}` as the subring `OΛ_a ⊠ OΛ_b`
(`OddMath.Frontier.EQZab.osymAB`) generated by the odd elementary polynomials `e_k(x)` in the first
`a` variables and `e_k(y)` in the last `b` variables. Since the variables `x_i` and `y_j` are odd
and anticommute in `OPol_{a+b}`, this is the super tensor product `OΛ_a ⊗ OΛ_b` (with the Koszul
sign rule for the product), with the differential `d(f ⊗ g) = d f ⊗ g + (-1)^{|f|} f ⊗ d g`
induced by `d(x_i) = x_i²`. The grading is the `DG`-library grading of `OPol_{a+b}`
(`OddMath.Frontier.EQSkewDifferential.OPol`): half the Ellis–Qi `q`-degree.

* `osymABDG a b`: `OΛ_{a,b} = OΛ_a ⊠ OΛ_b` as a dg subring of `OPol_{a+b}` (a dg ring);
* `osymDG_le_osymABDG`, `inclDG a b : OΛ_{a+b} →ᵈᵍ+* OΛ_{a,b}`: the inclusion of dg rings.
-/

namespace OddMath.Frontier.EQFunctor

open OddMath.SkewPolynomial (SkewPolynomial generator)
open OddMath.Frontier.EQSkewDifferential
open OddMath.Frontier.EQZab (osymAB inclX inclY)
open OddMath.Frontier.EQFix (osymABOPol osymABOPol_isHomogeneous)
open DirectSum

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) functorRingNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))
local instance (priority := high) functorRingNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

variable {a b : ℕ}

theorem mem_osymABOPol {f : OPol (a+b)} :
    f ∈ osymABOPol a b ↔ (OPol.equiv (a+b)).symm f ∈ osymAB a b :=
  Subring.mem_map_equiv

/-- **`OΛ_{a,b} = OΛ_a ⊗ OΛ_b` as a dg ring** (Ellis–Qi §4.3.1, §4.4): the dg subring
`OΛ_a ⊠ OΛ_b` of `OPol_{a+b}`. -/
def osymABDG (a b : ℕ) : DG.DGSubring (OPol (a+b)) where
  toSubring := osymABOPol a b
  isHomogeneous' := osymABOPol_isHomogeneous
  d_mem' ha := mem_osymABOPol.mpr (EQZab.d_mem (mem_osymABOPol.mp ha))

theorem mem_osymABDG {f : OPol (a+b)} :
    f ∈ osymABDG a b ↔ (OPol.equiv (a+b)).symm f ∈ osymAB a b :=
  mem_osymABOPol

/-- `OΛ_{a+b} ⊆ OΛ_a ⊠ OΛ_b`. -/
theorem osymDG_le_osymABDG (a b : ℕ) : osymDG (a+b) ≤ osymABDG a b := fun _ hf =>
  mem_osymABDG.mpr (EQZab.osym_le_osymAB (mem_osymDG.mp hf))

/-- The inclusion `OΛ_{a+b} → OΛ_a ⊗ OΛ_b` on elements. -/
def inclFun (a b : ℕ) (f : osymDG (a+b)) : osymABDG a b :=
  ⟨(f : OPol (a+b)), osymDG_le_osymABDG a b f.2⟩

theorem inclFun_eq (f : osymDG (a+b)) :
    inclFun a b f = ⟨(f : OPol (a+b)), osymDG_le_osymABDG a b f.2⟩ := rfl

@[simp]
theorem coe_inclFun (f : osymDG (a+b)) : ((inclFun a b f : osymABDG a b) : OPol (a+b)) = f := by
  rw [inclFun_eq]

/-- The inclusion `OΛ_{a+b} → OΛ_a ⊗ OΛ_b` as a ring homomorphism. -/
def inclRingHom (a b : ℕ) : osymDG (a+b) →+* osymABDG a b where
  toFun := inclFun a b
  map_one' := Subtype.ext (by rw [coe_inclFun, OneMemClass.coe_one, OneMemClass.coe_one])
  map_mul' x y := Subtype.ext (by
    rw [coe_inclFun, MulMemClass.coe_mul, MulMemClass.coe_mul, coe_inclFun, coe_inclFun])
  map_zero' := Subtype.ext (by rw [coe_inclFun, ZeroMemClass.coe_zero, ZeroMemClass.coe_zero])
  map_add' x y := Subtype.ext (by
    rw [coe_inclFun, AddMemClass.coe_add, AddMemClass.coe_add, coe_inclFun, coe_inclFun])

theorem inclRingHom_apply (f : osymDG (a+b)) : inclRingHom a b f = inclFun a b f := rfl

theorem coe_inclRingHom (f : osymDG (a+b)) :
    ((inclRingHom a b f : osymABDG a b) : OPol (a+b)) = f := by
  rw [inclRingHom_apply, coe_inclFun]

theorem inclRingHom_mem {n : ℤ} {f : osymDG (a+b)} (hf : f ∈ DG.grading n) :
    inclRingHom a b f ∈ DG.grading n := by
  rw [DG.DGSubring.mem_grading_iff, coe_inclRingHom]
  exact (DG.DGSubring.mem_grading_iff _).mp hf

theorem inclRingHom_d (f : osymDG (a+b)) :
    inclRingHom a b (DG.d f) = DG.d (inclRingHom a b f) := by
  apply Subtype.ext
  rw [coe_inclRingHom, DG.DGSubring.coe_d, DG.DGSubring.coe_d, coe_inclRingHom]

/-- **The inclusion `OΛ_{a+b} → OΛ_a ⊗ OΛ_b`** as a morphism of dg rings. -/
def inclDG (a b : ℕ) : osymDG (a+b) →ᵈᵍ+* osymABDG a b where
  __ := inclRingHom a b
  map_mem' := inclRingHom_mem
  map_d' := inclRingHom_d

theorem inclDG_apply (f : osymDG (a+b)) : inclDG a b f = inclRingHom a b f := rfl

@[simp]
theorem coe_inclDG (f : osymDG (a+b)) : ((inclDG a b f : osymABDG a b) : OPol (a+b)) = f := by
  rw [inclDG_apply, coe_inclRingHom]

end

end OddMath.Frontier.EQFunctor
