import OddMath.Frontier.EQPdgTheorem
import Mathlib.RingTheory.MvPolynomial.MonomialOrder
import Mathlib.Data.Finsupp.MonomialOrder

/-!
# Ellis–Qi, Theorem A.4 (2) in `n` variables

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
Appendix A.4.2, Theorem A.4 (2).

Over a field `𝕜` of characteristic `p`, let `N = ⌊n/p⌋` and let `A ⊆ Sym_n` be the subalgebra
generated by `e_p^p, e_{2p}^p, …, e_{Np}^p` (the `e_{jp}` with `jp > n` vanish in `n`
variables). Then `d = 0` on `A`, and the inclusion `A ↪ Sym_n` is a quasi-isomorphism of
p-complexes (`thmA4_2`); moreover `A` is a polynomial algebra on these generators
(`aeval_ePow_injective`).

The proof computes the lexicographic leading term of `a_δ · Π_j e_{p(j+1)}^{p c_j}`: the Schur
expansion of `Π_j e_{p(j+1)}^{p c_j}` is unitriangular with respect to the `p`-Lima partitions
`λ(c)` (`λ(c)_r = p Σ_{j ≥ ⌊r/p⌋} c_j`), and the classes `[s_λ]` of the `p`-Lima partitions form a
basis of `H_{/0}(Sym_n)` (Theorem A.4 (1)).
-/

namespace OddMath.Frontier.EQPdg

open MvPolynomial Finset MonomialOrder

noncomputable section

/-- The lexicographic monomial order on `𝕜[x_0, …, x_{n-1}]` (`x_0` most significant). -/
abbrev lexo (n : ℕ) : MonomialOrder (Fin n) := MonomialOrder.lex

section Degrees

variable {k : Type*} [Field k] {n : ℕ}



/-- The indicator exponent of the first `j` variables: `x_0 x_1 ⋯ x_{j-1}`. -/
def chi (n j : ℕ) : Fin n →₀ ℕ := ∑ i ∈ univ.filter (fun i : Fin n => (i : ℕ) < j), Finsupp.single i 1

/-- The indicator exponent of a set of variables. -/
def chiSet (t : Finset (Fin n)) : Fin n →₀ ℕ := ∑ i ∈ t, Finsupp.single i 1

theorem chiSet_apply (t : Finset (Fin n)) (i : Fin n) : chiSet t i = if i ∈ t then 1 else 0 := by
  simp [chiSet, Finsupp.finsetSum_apply, Finsupp.single_apply]

theorem chiSet_injective : Function.Injective (chiSet (n := n)) := by
  intro t t' h
  ext i
  have := congrArg (fun f => f i) h
  simp only [chiSet_apply] at this
  split_ifs at this with h1 h2 h2 <;> simp_all

theorem card_initial (j : ℕ) : (univ.filter (fun i : Fin n => (i : ℕ) < j)).card = min j n := by
  rw [← Finset.card_range (min j n), ← Finset.card_map Fin.valEmbedding]
  congr 1
  ext x
  simp only [Finset.mem_map, Finset.mem_filter, Finset.mem_univ, true_and, Fin.valEmbedding_apply,
    Finset.mem_range, lt_min_iff]
  constructor
  · rintro ⟨i, hi, rfl⟩; exact ⟨hi, i.2⟩
  · rintro ⟨h1, h2⟩; exact ⟨⟨x, h2⟩, h1, rfl⟩

/-- Among the `j`-element sets, the initial segment has the lex-largest indicator. -/
theorem chiSet_le_initial (j : ℕ) (t : Finset (Fin n)) (ht : t.card = j) :
    toLex (chiSet t) ≤ toLex (chiSet (univ.filter (fun i : Fin n => (i : ℕ) < j))) := by
  set T0 := univ.filter (fun i : Fin n => (i : ℕ) < j)
  by_cases hsub : T0 ⊆ t
  · have htn : t.card ≤ n := by
      have := Finset.card_le_univ t; simpa using this
    have hT0 : T0.card = min j n := card_initial j
    have : T0 = t := Finset.eq_of_subset_of_card_le hsub (by omega)
    rw [this]
  · have hne : (T0 \ t).Nonempty := by
      rw [Finset.sdiff_nonempty]; exact hsub
    set i := (T0 \ t).min' hne
    have hi : i ∈ T0 \ t := Finset.min'_mem _ hne
    rw [Finset.mem_sdiff] at hi
    refine le_of_lt ⟨i, fun l hl => ?_, ?_⟩
    · simp only [ofLex_toLex, chiSet_apply]
      have hlT0 : l ∈ T0 := by
        simp only [T0, Finset.mem_filter, Finset.mem_univ, true_and] at hi ⊢
        exact lt_trans (Fin.lt_def.mp hl) hi.1
      have hlt : l ∈ t := by
        by_contra hlt
        have := Finset.min'_le (T0 \ t) l (Finset.mem_sdiff.mpr ⟨hlT0, hlt⟩)
        exact absurd hl (not_lt.mpr this)
      simp [hlT0, hlt]
    · show chiSet t i < chiSet T0 i
      rw [chiSet_apply, chiSet_apply]
      simp [hi.1, hi.2]

theorem lex_le_antisymm {c d : Fin n →₀ ℕ} (h1 : c ≼[lexo n] d) (h2 : d ≼[lexo n] c) : c = d :=
  (lexo n).toSyn.injective (le_antisymm h1 h2)

theorem esymm_eq_sum_chiSet (j : ℕ) :
    esymm (Fin n) k j = ∑ t ∈ powersetCard j univ, monomial (chiSet t) 1 := by
  rw [esymm_eq_sum_monomial]; rfl

/-- The lex-leading term of `e_j` (`j ≤ n`) is `x_0 x_1 ⋯ x_{j-1}`. -/
theorem degree_esymm {j : ℕ} (hj : j ≤ n) :
    (lexo n).degree (esymm (Fin n) k j) = chiSet (univ.filter (fun i : Fin n => (i : ℕ) < j)) ∧
      (lexo n).Monic (esymm (Fin n) k j) := by
  set T0 := univ.filter (fun i : Fin n => (i : ℕ) < j)
  have hT0 : T0 ∈ powersetCard j univ := by
    rw [Finset.mem_powersetCard]
    refine ⟨Finset.subset_univ _, ?_⟩
    rw [card_initial]; omega
  have hcoeff : ∀ c, (esymm (Fin n) k j).coeff c =
      ∑ t ∈ powersetCard j univ, if chiSet t = c then (1 : k) else 0 := by
    intro c
    rw [esymm_eq_sum_chiSet, coeff_sum]
    simp only [coeff_monomial]
  have hc0 : (esymm (Fin n) k j).coeff (chiSet T0) = 1 := by
    rw [hcoeff, Finset.sum_eq_single T0]
    · simp
    · intro t _ ht
      exact ite_eq_right_of_eq_false _ _ (eq_false fun h => ht (chiSet_injective h))
    · intro h; exact absurd hT0 h
  have hsupp : ∀ c ∈ (esymm (Fin n) k j).support, c ≼[lexo n] chiSet T0 := by
    intro c hc
    rw [mem_support_iff, hcoeff] at hc
    obtain ⟨t, ht, htc⟩ : ∃ t ∈ powersetCard j univ, chiSet t = c := by
      by_contra h
      push Not at h
      exact hc (Finset.sum_eq_zero fun t ht => ite_eq_right_of_eq_false _ _ (eq_false (h t ht)))
    rw [← htc, lex_le_iff]
    exact chiSet_le_initial j t (Finset.mem_powersetCard.mp ht).2
  have hdeg : (lexo n).degree (esymm (Fin n) k j) = chiSet T0 :=
    lex_le_antisymm ((lexo n).degree_le_iff.mpr hsupp)
      ((lexo n).le_degree (by rw [mem_support_iff, hc0]; exact one_ne_zero))
  exact ⟨hdeg, by rw [Monic, leadingCoeff, hdeg, hc0]⟩

theorem degree_X_sub_X {i j : Fin n} (hij : i < j) :
    (lexo n).degree (X j - X i : MvPolynomial (Fin n) k) = Finsupp.single i 1 := by
  rw [show (X j - X i : MvPolynomial (Fin n) k) = -(X i - X j) by ring, degree_neg,
    degree_sub_of_lt, degree_X]
  rw [degree_X, degree_X, lex_lt_iff]
  exact Finsupp.Lex.single_strictAnti hij

/-- The lex-leading exponent of the Vandermonde determinant `a_δ` is `(n-1, n-2, …, 0)`. -/
theorem degree_alt_delta :
    (lexo n).degree (alt (delta n) : MvPolynomial (Fin n) k) =
      Finsupp.equivFunOnFinite.symm (fun i : Fin n => n - 1 - i) := by
  rw [alt_delta, degree_prod]
  · rw [Finset.sum_congr rfl fun i _ => degree_prod (fun j hj => by
        rw [sub_ne_zero]; intro h
        exact absurd (X_injective h) (ne_of_gt (Finset.mem_Ioi.mp hj)))]
    have hin : ∀ i : Fin n, ∑ j ∈ Ioi i, (lexo n).degree (X j - X i : MvPolynomial (Fin n) k) =
        ∑ j ∈ Ioi i, Finsupp.single i 1 :=
      fun i => Finset.sum_congr rfl fun j hj => degree_X_sub_X (Finset.mem_Ioi.mp hj)
    rw [Finset.sum_congr rfl fun i _ => hin i]
    ext l
    simp [Finsupp.finsetSum_apply, Finsupp.single_apply, Fin.card_Ioi]
    rw [Finset.sum_eq_single l]
    · simp
    · intro b _ hb; simp [hb]
    · simp
  · intro i _
    rw [Finset.prod_ne_zero_iff]
    intro j hj
    rw [sub_ne_zero]; intro h
    exact absurd (X_injective h) (ne_of_gt (Finset.mem_Ioi.mp hj))

/-! ## Schur coordinates as coefficients -/

theorem coeff_eq_altBasis_repr (y : (Alt : Submodule k (MvPolynomial (Fin n) k)))
    (β : {α : Fin n → ℕ // StrictMono α}) :
    (y : MvPolynomial (Fin n) k).coeff (Finsupp.equivFunOnFinite.symm β.1) =
      altBasis.repr y β := by
  conv_lhs => rw [← altBasis.linearCombination_repr y]
  rw [Finsupp.linearCombination_apply, Finsupp.sum, Submodule.coe_sum, coeff_sum]
  simp only [Submodule.coe_smul, coeff_smul, altBasis_apply, coeff_alt_subtype, smul_eq_mul,
    mul_ite, mul_one, mul_zero]
  rw [Finset.sum_ite_eq']
  split_ifs with h
  · rfl
  · exact (Finsupp.notMem_support_iff.mp h).symm

/-- The Schur coordinates of a symmetric polynomial `f` are the coefficients of `a_δ f` at the
strictly increasing exponents. -/
theorem schurBasis_repr_eq_coeff (f : (SymSub : Submodule k (MvPolynomial (Fin n) k)))
    (β : {α : Fin n → ℕ // StrictMono α}) :
    schurBasis.repr f β = (alt (delta n) * f.1).coeff (Finsupp.equivFunOnFinite.symm β.1) := by
  rw [schurBasis, Module.Basis.map_repr, LinearEquiv.trans_apply, LinearEquiv.symm_symm,
    ← coeff_eq_altBasis_repr, symToAlt_apply]

theorem mapDomain_revPerm (β : Fin n → ℕ) :
    Finsupp.mapDomain Fin.revPerm (Finsupp.equivFunOnFinite.symm β) =
      Finsupp.equivFunOnFinite.symm (β ∘ Fin.rev) := by
  ext l
  obtain ⟨l', rfl⟩ := Fin.revPerm.surjective l
  rw [Finsupp.mapDomain_apply_of_injective Fin.revPerm.injective]
  simp

/-- For an alternating `g`: `coeff_β(g) = sgn(w₀) · coeff_{β ∘ w₀}(g)`. -/
theorem coeff_Alt_rev {g : MvPolynomial (Fin n) k} (hg : g ∈ Alt) (β : Fin n → ℕ) :
    g.coeff (Finsupp.equivFunOnFinite.symm β) =
      ((Equiv.Perm.sign (Fin.revPerm : Equiv.Perm (Fin n)) : ℤ) : k) *
        g.coeff (Finsupp.equivFunOnFinite.symm (β ∘ Fin.rev)) := by
  have h := coeff_rename_mapDomain (Fin.revPerm : Equiv.Perm (Fin n)) Fin.revPerm.injective g
    (Finsupp.equivFunOnFinite.symm β)
  rw [Alt_rename Fin.revPerm hg, mapDomain_revPerm, ← map_intCast (C : k →+* MvPolynomial (Fin n) k),
    coeff_C_mul] at h
  exact h.symm

end Degrees

/-! ## Coordinates of classes in `H_{/0}` -/

section Classes

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

theorem h0Basis_repr_classT (y : symT (k := k) (n := n) p) :
    (h0Basis p).repr (classT p y) =
      (Module.Basis.span (linearIndependent_schur_trivial (k := k) (n := n) p)).repr y := by
  rw [h0Basis, Module.Basis.map_repr, LinearEquiv.trans_apply]
  congr 1
  exact (LinearEquiv.ofBijective (classT (k := k) (n := n) p) (classT_bijective p)).symm_apply_apply y

/-- The coordinates of the class `[x]` of a cycle `x ∈ Sym_n` in the basis `{[s_α]}` of
`H_{/0}(Sym_n)` are its Schur coordinates at the trivial `α`. -/
theorem h0Basis_repr_class (x : (SymSub : Submodule k (MvPolynomial (Fin n) k)))
    (hx : (dSym (k := k) (n := n) ^ (0 + 1)) x = 0) (α : ↥(ntSet (n := n) p)ᶜ) :
    (h0Basis p).repr (slashClass dSym p 0 x hx) α = schurBasis.repr x α.1 := by
  classical
  set c := schurBasis.repr x
  set S := c.support
  set S' : Finset ↥(ntSet (n := n) p)ᶜ := S.subtype (· ∈ (ntSet (n := n) p)ᶜ)
  set hli := linearIndependent_schur_trivial (k := k) (n := n) p
  set t : symT (k := k) (n := n) p := ∑ a ∈ S', c a.1 • Module.Basis.span hli a
  have ht : (t : (SymSub : Submodule k (MvPolynomial (Fin n) k))) =
      ∑ a ∈ S.filter (· ∈ (ntSet (n := n) p)ᶜ), c a • schurBasis a := by
    rw [← Finset.sum_subtype_eq_sum_filter, Submodule.coe_sum]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [Submodule.coe_smul, Module.Basis.span_apply]
  have hxsum : x = ∑ a ∈ S, c a • schurBasis a := by
    conv_lhs => rw [← schurBasis.linearCombination_repr x]
    rfl
  have hu : x - t ∈ symF (k := k) (n := n) p := by
    rw [ht, hxsum, ← Finset.sum_filter_add_sum_filter_not S (· ∈ (ntSet (n := n) p)ᶜ),
      add_sub_cancel_left]
    refine Submodule.sum_mem _ fun a ha => Submodule.smul_mem _ _ (Submodule.subset_span ?_)
    rw [Finset.mem_filter] at ha
    exact ⟨⟨a, by simpa using ha.2⟩, rfl⟩
  have hukernel : (dSym ^ 1) (x - (t : (SymSub : Submodule k (MvPolynomial (Fin n) k)))) = 0 := by
    rw [map_sub, show (dSym (k := k) (n := n) ^ 1) x = 0 by simpa using hx,
      show (dSym (k := k) (n := n) ^ 1) t.1 = 0 by simpa using symT_mem_ker p t, sub_zero]
  have hrange := symF_exact p 1 le_rfl (by have := hp.out.two_le; omega) _ hu hukernel
  have hclass : slashClass dSym p 0 x hx = classT p t := by
    rw [classT_apply, slashClass, slashClass, Submodule.Quotient.eq, Submodule.mem_comap,
      slashDen_zero]
    exact hrange
  rw [hclass, h0Basis_repr_classT]
  simp only [t, map_sum, map_smul, Module.Basis.repr_self, Finsupp.coe_finsetSum,
    Finset.sum_apply, Finsupp.smul_apply, Finsupp.single_apply, smul_eq_mul, mul_ite, mul_one,
    mul_zero]
  rw [Finset.sum_ite_eq']
  split_ifs with h
  · rfl
  · rw [Finset.mem_subtype] at h
    exact (Finsupp.notMem_support_iff.mp h).symm

end Classes

/-! ## The generators `e_{jp}^p` -/

section Gens

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

/-- The generator `e_{p(j+1)}^p`, `j < ⌊n/p⌋`. -/
def ePow (j : Fin (n / p)) : MvPolynomial (Fin n) k := esymm (Fin n) k (p * (j + 1)) ^ p

/-- The algebra map `𝕜[y_1, …, y_N] → 𝕜[x_1, …, x_n]`, `y_j ↦ e_{jp}^p`. -/
def evE : MvPolynomial (Fin (n / p)) k →ₐ[k] MvPolynomial (Fin n) k := aeval (ePow (k := k) p)

/-- The subalgebra `𝕜[e_p^p, e_{2p}^p, …]` of `Sym_n`. -/
def algA : Subalgebra k (MvPolynomial (Fin n) k) := Algebra.adjoin k (Set.range (ePow (k := k) p))

/-- `E(c) = Π_j (e_{p(j+1)}^p)^{c_j}`. -/
def Ec (c : Fin (n / p) →₀ ℕ) : MvPolynomial (Fin n) k := evE p (monomial c 1)

omit hp [CharP k p] in
theorem p_mul_le (j : Fin (n / p)) : p * ((j : ℕ) + 1) ≤ n := by
  have h1 : (j : ℕ) + 1 ≤ n / p := j.2
  exact le_trans (Nat.mul_le_mul_left p h1) (Nat.mul_div_le n p)

omit hp [CharP k p] in
theorem Ec_eq (c : Fin (n / p) →₀ ℕ) :
    Ec (k := k) p c = ∏ j : Fin (n / p), esymm (Fin n) k (p * ((j : ℕ) + 1)) ^ (p * c j) := by
  rw [Ec, evE, aeval_monomial, map_one, one_mul, Finsupp.prod_fintype _ _ (fun _ => pow_zero _)]
  refine Finset.prod_congr rfl fun j _ => ?_
  rw [ePow, ← pow_mul]

omit hp [CharP k p] in
theorem degree_Ec (c : Fin (n / p) →₀ ℕ) :
    (lexo n).degree (Ec (k := k) p c) =
      ∑ j : Fin (n / p), (p * c j) • chiSet (univ.filter (fun i : Fin n => (i : ℕ) < p * ((j : ℕ) + 1))) ∧
    (lexo n).Monic (Ec (k := k) p c) := by
  have hmon : ∀ j : Fin (n / p), (lexo n).Monic
      (esymm (Fin n) k (p * ((j : ℕ) + 1)) ^ (p * c j)) :=
    fun j => (degree_esymm (k := k) (p_mul_le p j)).2.pow
  rw [Ec_eq]
  refine ⟨?_, Monic.prod fun j _ => hmon j⟩
  rw [degree_prod fun j _ => (hmon j).ne_zero]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [degree_pow, (degree_esymm (k := k) (p_mul_le p j)).1]

omit hp [CharP k p] in
theorem ePow_isSymmetric (j : Fin (n / p)) : (ePow (k := k) p j).IsSymmetric := by
  rw [ePow]
  exact (mem_symmetricSubalgebra _).mp
    (Subalgebra.pow_mem _ ((mem_symmetricSubalgebra _).mpr (esymm_isSymmetric _ _ _)) _)

omit hp [CharP k p] in
theorem algA_le_sym : algA (k := k) (n := n) p ≤ symmetricSubalgebra (Fin n) k := by
  rw [algA, Algebra.adjoin_le_iff]
  rintro _ ⟨j, rfl⟩
  exact (mem_symmetricSubalgebra _).mpr (ePow_isSymmetric p j)

omit hp [CharP k p] in
theorem evE_mem_algA (f : MvPolynomial (Fin (n / p)) k) : evE (k := k) p f ∈ algA (n := n) p := by
  rw [algA, ← MvPolynomial.aeval_range]
  exact ⟨f, rfl⟩

omit hp [CharP k p] in
theorem evE_isSymmetric (f : MvPolynomial (Fin (n / p)) k) : (evE (k := k) (n := n) p f).IsSymmetric :=
  (mem_symmetricSubalgebra _).mp (algA_le_sym p (evE_mem_algA p f))

omit hp in
theorem pd_ePow (j : Fin (n / p)) : pd (Fin n) k (ePow (k := k) p j) = 0 := by
  rw [ePow, Derivation.leibniz_pow, ← Nat.cast_smul_eq_nsmul (MvPolynomial (Fin n) k),
    CharP.cast_eq_zero, zero_smul]

omit hp in
/-- `d = 0` on `𝕜[e_p^p, e_{2p}^p, …]`. -/
theorem pd_algA {a : MvPolynomial (Fin n) k} (ha : a ∈ algA (k := k) (n := n) p) :
    pd (Fin n) k a = 0 := by
  induction ha using Algebra.adjoin_induction with
  | mem x hx => obtain ⟨j, rfl⟩ := hx; exact pd_ePow p j
  | algebraMap r => exact (pd (Fin n) k).map_algebraMap r
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | mul x y _ _ hx hy => rw [Derivation.leibniz, hx, hy, smul_zero, smul_zero, add_zero]

end Gens

/-! ## The leading Schur term of `E(c)` -/

section Leading

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

/-- `λ(c)_r = p Σ_{j : r < p(j+1)} c_j` (on all rows `r ∈ ℕ`). -/
def lamCext (c : Fin (n / p) →₀ ℕ) (r : ℕ) : ℕ :=
  p * ∑ j : Fin (n / p), if r < p * ((j : ℕ) + 1) then c j else 0

/-- The `p`-Lima partition `λ(c)` indexing the leading term of `E(c)`. -/
def lamC (c : Fin (n / p) →₀ ℕ) : Fin n → ℕ := fun r => lamCext p c r

omit hp [CharP k p] in
theorem degree_vandermonde_mul_Ec (c : Fin (n / p) →₀ ℕ) :
    (lexo n).degree (alt (delta n) * Ec (k := k) p c) =
      Finsupp.equivFunOnFinite.symm (lamDelta (lamC p c) ∘ Fin.rev) := by
  rw [degree_mul alt_delta_ne_zero (degree_Ec (k := k) p c).2.ne_zero, degree_alt_delta,
    (degree_Ec p c).1]
  ext i
  rw [Finsupp.add_apply, Finsupp.coe_equivFunOnFinite_symm, Finsupp.coe_equivFunOnFinite_symm,
    Finsupp.finsetSum_apply]
  simp only [Finsupp.smul_apply, chiSet_apply, smul_eq_mul, Function.comp_apply, lamDelta,
    Fin.rev_rev, lamC, lamCext, Fin.val_rev, Finset.mul_sum, Finset.mem_filter, Finset.mem_univ,
    true_and, mul_ite, mul_one, mul_zero]
  omega

omit hp [CharP k p] in
theorem antitone_lamC (c : Fin (n / p) →₀ ℕ) : Antitone (lamC p c) := by
  intro r r' h
  simp only [lamC, lamCext]
  refine Nat.mul_le_mul_left _ (Finset.sum_le_sum fun j _ => ?_)
  have h' : (r : ℕ) ≤ r' := h
  split_ifs <;> omega

theorem isPLima_lamC (c : Fin (n / p) →₀ ℕ) : IsPLima p (lamC p c) := by
  refine ⟨fun q => ∑ j : Fin (n / p), if q ≤ (j : ℕ) then c j else 0, fun r => ?_⟩
  have hp0 := hp.out.pos
  have key : ∀ j : Fin (n / p), (r < p * ((j : ℕ) + 1)) ↔ (r / p ≤ (j : ℕ)) := by
    intro j
    rw [← Nat.lt_succ_iff, Nat.div_lt_iff_lt_mul hp0, mul_comm]
  by_cases hr : r < n
  · rw [lamExt_lt _ hr]
    simp only [lamC, lamCext]
    congr 1
    exact Finset.sum_congr rfl fun j _ => by simp only [key j]
  · rw [lamExt_ge _ hr]
    symm
    rw [Nat.mul_eq_zero]
    right
    refine Finset.sum_eq_zero fun j _ => ?_
    have : ¬ r / p ≤ (j : ℕ) := by
      rw [← key j]
      have := p_mul_le p j
      omega
    simp [this]

/-- The index of the leading Schur term of `E(c)`: `λ(c) + δ` (trivial by Theorem A.4). -/
def iota (c : Fin (n / p) →₀ ℕ) : ↥(ntSet (n := n) p)ᶜ :=
  ⟨⟨lamDelta (lamC p c), strictMono_lamDelta (antitone_lamC p c)⟩,
    (trivial_iff_isPLima p hp.out.pos (antitone_lamC p c)).mpr (isPLima_lamC p c)⟩

end Leading

/-! ## Unitriangularity -/

section Tri

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

/-- The sort key `α ↦ toLex(α ∘ w₀)` for exponents. -/
def keyL (β : Fin n → ℕ) : Lex (Fin n →₀ ℕ) := toLex (Finsupp.equivFunOnFinite.symm (β ∘ Fin.rev))

theorem keyL_injective : Function.Injective (keyL (n := n)) := by
  intro β β' h
  have h1 := Finsupp.equivFunOnFinite.symm.injective (toLex.injective h)
  funext i
  have := congrFun h1 (Fin.rev i)
  simpa using this

/-- `E(c)` as an element of `Sym_n`. -/
def EcSym (c : Fin (n / p) →₀ ℕ) : (SymSub : Submodule k (MvPolynomial (Fin n) k)) :=
  ⟨Ec p c, mem_SymSub.mpr (evE_isSymmetric p _)⟩

omit hp [CharP k p] in
theorem vandermonde_mul_Ec_mem_Alt (c : Fin (n / p) →₀ ℕ) :
    alt (delta n) * Ec (k := k) p c ∈ (Alt : Submodule k (MvPolynomial (Fin n) k)) :=
  vandermonde_mul_mem_Alt (evE_isSymmetric p _)

omit hp [CharP k p] in
/-- Only Schur functions `s_β` with `key β ≤ key (λ(c) + δ)` occur in `E(c)`. -/
theorem key_le_of_repr_ne_zero (c : Fin (n / p) →₀ ℕ) (β : {α : Fin n → ℕ // StrictMono α})
    (h : schurBasis.repr (EcSym (k := k) p c) β ≠ 0) :
    keyL β.1 ≤ keyL (lamDelta (lamC p c)) := by
  rw [schurBasis_repr_eq_coeff, EcSym, coeff_Alt_rev (vandermonde_mul_Ec_mem_Alt p c)] at h
  have h' := right_ne_zero_of_mul h
  have := (lexo n).le_degree (mem_support_iff.mpr h')
  rw [degree_vandermonde_mul_Ec, lex_le_iff] at this
  exact this

omit hp [CharP k p] in
theorem repr_Ec_leading (c : Fin (n / p) →₀ ℕ) (h : StrictMono (lamDelta (lamC p c))) :
    schurBasis.repr (EcSym (k := k) p c) ⟨lamDelta (lamC p c), h⟩ =
      ((Equiv.Perm.sign (Fin.revPerm : Equiv.Perm (Fin n)) : ℤ) : k) *
        (lexo n).leadingCoeff (alt (delta n) : MvPolynomial (Fin n) k) := by
  rw [schurBasis_repr_eq_coeff, EcSym, coeff_Alt_rev (vandermonde_mul_Ec_mem_Alt p c)]
  congr 1
  simp only
  rw [← degree_vandermonde_mul_Ec (k := k) p c]
  change (lexo n).leadingCoeff _ = _
  rw [leadingCoeff_mul, (degree_Ec p c).2.leadingCoeff_eq_one, mul_one]

omit hp [CharP k p] in
theorem leadUnit_ne_zero :
    ((Equiv.Perm.sign (Fin.revPerm : Equiv.Perm (Fin n)) : ℤ) : k) *
        (lexo n).leadingCoeff (alt (delta n) : MvPolynomial (Fin n) k) ≠ 0 := by
  refine mul_ne_zero ?_ ((lexo n).leadingCoeff_ne_zero_iff.mpr alt_delta_ne_zero)
  rcases Int.units_eq_one_or (Equiv.Perm.sign (Fin.revPerm : Equiv.Perm (Fin n))) with h | h <;>
    simp [h]

/-! ### `c ↦ λ(c)` is a bijection onto the `p`-Lima partitions -/

/-- `S_q(c) = Σ_{j ≥ q} c_j`. -/
def tailSum (c : Fin (n / p) →₀ ℕ) (q : ℕ) : ℕ := ∑ j : Fin (n / p), if q ≤ (j : ℕ) then c j else 0

omit hp in
theorem lamCext_eq (hp0 : 0 < p) (c : Fin (n / p) →₀ ℕ) (r : ℕ) :
    lamCext p c r = p * tailSum p c (r / p) := by
  simp only [lamCext, tailSum]
  congr 1
  refine Finset.sum_congr rfl fun j _ => ?_
  have : (r < p * ((j : ℕ) + 1)) ↔ (r / p ≤ (j : ℕ)) := by
    rw [← Nat.lt_succ_iff, Nat.div_lt_iff_lt_mul hp0, mul_comm]
  simp only [this]

omit hp in
theorem tailSum_succ (c : Fin (n / p) →₀ ℕ) (j : Fin (n / p)) :
    tailSum p c j = c j + tailSum p c ((j : ℕ) + 1) := by
  have h : ∀ j' : Fin (n / p), (if (j : ℕ) ≤ j' then c j' else 0) =
      (if j' = j then c j' else 0) + (if (j : ℕ) + 1 ≤ j' then c j' else 0) := by
    intro j'
    by_cases hj : j' = j
    · subst hj; simp
    · have : (j' : ℕ) ≠ j := fun e => hj (Fin.ext e)
      by_cases h1 : (j : ℕ) ≤ j'
      · have h2 : (j : ℕ) + 1 ≤ j' := by omega
        simp [hj, h1, h2]
      · have h2 : ¬ (j : ℕ) + 1 ≤ j' := by omega
        simp [hj, h1, h2]
  rw [tailSum, Finset.sum_congr rfl (fun j' _ => h j'), Finset.sum_add_distrib,
    Finset.sum_ite_eq']
  simp [tailSum]

omit hp in
theorem tailSum_top (c : Fin (n / p) →₀ ℕ) : tailSum p c (n / p) = 0 := by
  refine Finset.sum_eq_zero fun j _ => ?_
  have : ¬ n / p ≤ (j : ℕ) := by have := j.2; omega
  simp [this]

theorem iota_injective : Function.Injective (iota (n := n) p) := by
  intro c c' h
  have hp0 := hp.out.pos
  have h1 : lamC p c = lamC p c' := by
    have := congrArg (fun a => lamOfAlpha a.1.1) h
    simpa [iota, lamOfAlpha_lamDelta] using this
  have hS : ∀ q ≤ n / p, tailSum p c q = tailSum p c' q := by
    intro q hq
    rcases Nat.lt_or_eq_of_le hq with hq | hq
    · have hqn : p * q < n := by
        have h1 : p * (q + 1) ≤ p * (n / p) := Nat.mul_le_mul_left _ hq
        have h2 := Nat.mul_div_le n p
        rw [Nat.mul_succ] at h1
        omega
      have := congrFun h1 ⟨p * q, hqn⟩
      simp only [lamC, lamCext_eq p hp0, Nat.mul_div_cancel_left _ hp0] at this
      exact Nat.eq_of_mul_eq_mul_left hp0 this
    · rw [hq, tailSum_top, tailSum_top]
  ext j
  have e1 := tailSum_succ p c j
  have e2 := tailSum_succ p c' j
  have := hS j (le_of_lt j.2)
  have := hS ((j : ℕ) + 1) j.2
  omega

theorem sum_Ico_tsub {f : ℕ → ℕ} (hf : Antitone f) (q m : ℕ) :
    ∑ j ∈ Ico q (q + m), (f j - f (j + 1)) = f q - f (q + m) := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [← add_assoc, Finset.sum_Ico_succ_top (by omega), ih]
    have h1 := hf (show q ≤ q + m by omega)
    have h2 := hf (show q + m ≤ q + m + 1 by omega)
    omega

theorem iota_surjective : Function.Surjective (iota (n := n) p) := by
  intro α
  have hp0 := hp.out.pos
  set lam := lamOfAlpha α.1.1
  have hanti : Antitone lam := antitone_lamOfAlpha α.1.2
  have hL : IsPLima p lam := by
    have h := (trivial_iff_isPLima p hp0 hanti).mp
    rw [lamDelta_lamOfAlpha α.1.2] at h
    exact h α.2
  obtain ⟨ν, hν⟩ := hL
  set N := n / p
  have hn : n = p * N + n % p := n_eq n p
  have hρ : n % p < p := Nat.mod_lt _ hp0
  have hpN : p * N ≤ n := Nat.mul_div_le n p
  have hνN : ν N = 0 := by
    have h := hν (p * N + p - 1)
    rw [lamExt_ge lam (by generalize p * N = M at *; omega)] at h
    have : (p * N + p - 1) / p = N :=
      div_eq_of_bounds (by generalize p * N = M at *; omega) (by generalize p * N = M at *; omega)
    rw [this] at h
    exact (Nat.mul_eq_zero.mp h.symm).resolve_left (by omega)
  set ν' : ℕ → ℕ := fun q => if q < N then ν q else 0
  have hν' : ∀ q ≤ N, ν' q = ν q := by
    intro q hq
    simp only [ν']
    split_ifs with h
    · rfl
    · rw [show q = N by omega, hνN]
  have hanti' : Antitone ν' := by
    refine antitone_nat_of_succ_le fun q => ?_
    simp only [ν']
    split_ifs with h1 h2 h2
    · -- rows `pq` and `p(q+1)` of `λ`
      have hr1 : p * q < n := by
        have : p * (q + 1) ≤ p * N := Nat.mul_le_mul_left _ h2
        rw [Nat.mul_succ] at this
        omega
      have hr2 : p * (q + 1) < n := by
        have : p * (q + 1 + 1) ≤ p * N := Nat.mul_le_mul_left _ h1
        rw [Nat.mul_succ] at this
        omega
      have e1 := hν (p * q)
      have e2 := hν (p * (q + 1))
      rw [lamExt_lt lam hr1, Nat.mul_div_cancel_left _ hp0] at e1
      rw [lamExt_lt lam hr2, Nat.mul_div_cancel_left _ hp0] at e2
      have := hanti (show (⟨p * q, hr1⟩ : Fin n) ≤ ⟨p * (q + 1), hr2⟩ by
        rw [Fin.le_def]; exact Nat.mul_le_mul_left _ (by omega))
      rw [e1, e2] at this
      exact Nat.le_of_mul_le_mul_left this hp0
    · omega
    · exact Nat.zero_le _
    · exact le_rfl
  refine ⟨Finsupp.equivFunOnFinite.symm (fun j => ν' j - ν' ((j : ℕ) + 1)), ?_⟩
  apply Subtype.ext; apply Subtype.ext
  show lamDelta (lamC p _) = α.1.1
  rw [← lamDelta_lamOfAlpha α.1.2]
  congr 1
  funext r
  have hrN : (r : ℕ) / p ≤ N := Nat.div_le_div_right (le_of_lt r.2)
  simp only [lamC, lamCext_eq p hp0, tailSum, Finsupp.coe_equivFunOnFinite_symm]
  rw [show lamOfAlpha α.1.1 r = lamExt lam r from (lamExt_lt lam r.2).symm, hν, ← hν' _ hrN]
  congr 1
  rw [Fin.sum_univ_eq_sum_range (fun m => if (r : ℕ) / p ≤ m then ν' m - ν' (m + 1) else 0),
    ← Finset.sum_filter]
  have : (range N).filter (fun m => (r : ℕ) / p ≤ m) = Ico ((r : ℕ) / p) ((r : ℕ) / p + (N - (r : ℕ) / p)) := by
    ext m; simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_Ico]; omega
  rw [this, sum_Ico_tsub hanti', show (r : ℕ) / p + (N - (r : ℕ) / p) = N by omega]
  have : ν' N = 0 := by simp [ν']
  omega

end Tri

/-! ## `𝕜[y_1, …, y_N] → H_{/0}(Sym_n)` is an isomorphism -/

section Psi

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

omit hp in
theorem evE_mem_ker (f : MvPolynomial (Fin (n / p)) k) :
    (dSym (k := k) (n := n) ^ (0 + 1)) ⟨evE p f, mem_SymSub.mpr (evE_isSymmetric p f)⟩ = 0 := by
  apply Subtype.ext
  simp only [zero_add, pow_one, dSym_apply, ZeroMemClass.coe_zero]
  exact pd_algA p (evE_mem_algA p f)

/-- `Ψ : 𝕜[y_1, …, y_N] → H_{/0}(Sym_n)`, `f ↦ [f(e_p^p, e_{2p}^p, …)]`. -/
def psiMap : MvPolynomial (Fin (n / p)) k →ₗ[k] SlashCohomology (dSym (k := k) (n := n)) p 0 :=
  (Submodule.mkQ _) ∘ₗ
    (((evE (k := k) (n := n) p).toLinearMap.codRestrict SymSub
      (fun f => mem_SymSub.mpr (evE_isSymmetric p f))).codRestrict
      (LinearMap.ker (dSym ^ (0 + 1))) (fun f => evE_mem_ker p f))

omit hp in
theorem psiMap_apply (f : MvPolynomial (Fin (n / p)) k) :
    psiMap (k := k) (n := n) p f =
      slashClass dSym p 0 ⟨evE p f, mem_SymSub.mpr (evE_isSymmetric p f)⟩ (evE_mem_ker p f) :=
  rfl

theorem psiMap_monomial_repr (c : Fin (n / p) →₀ ℕ) (α : ↥(ntSet (n := n) p)ᶜ) :
    (h0Basis p).repr (psiMap (k := k) (n := n) p (monomial c 1)) α =
      schurBasis.repr (EcSym (k := k) p c) α.1 := by
  rw [psiMap_apply, h0Basis_repr_class]
  rfl

theorem psiMap_repr (f : MvPolynomial (Fin (n / p)) k) (α : ↥(ntSet (n := n) p)ᶜ) :
    (h0Basis p).repr (psiMap (k := k) (n := n) p f) α =
      ∑ c ∈ f.support, f.coeff c * schurBasis.repr (EcSym (k := k) p c) α.1 := by
  conv_lhs => rw [f.as_sum]
  simp only [map_sum, Finsupp.coe_finsetSum, Finset.sum_apply]
  refine Finset.sum_congr rfl fun c _ => ?_
  rw [show (monomial c (f.coeff c) : MvPolynomial (Fin (n / p)) k) = f.coeff c • monomial c 1 by
    rw [smul_monomial, smul_eq_mul, mul_one], map_smul, map_smul, Finsupp.smul_apply,
    psiMap_monomial_repr, smul_eq_mul]

theorem iota_val (c : Fin (n / p) →₀ ℕ) :
    ((iota (n := n) p c).1 : {α : Fin n → ℕ // StrictMono α}) =
      ⟨lamDelta (lamC p c), strictMono_lamDelta (antitone_lamC p c)⟩ := rfl

omit [CharP k p] in
/-- Off the leading index, `E(c)` has no component at `λ(c₀) + δ` unless `key` increases. -/
theorem repr_Ec_iota_eq_zero {c c₀ : Fin (n / p) →₀ ℕ} (hne : c ≠ c₀)
    (hle : keyL (lamDelta (lamC p c)) ≤ keyL (lamDelta (lamC p c₀))) :
    schurBasis.repr (EcSym (k := k) p c) (iota (n := n) p c₀).1 = 0 := by
  by_contra h
  have h1 := key_le_of_repr_ne_zero p c _ h
  rw [iota_val] at h1
  have heq := keyL_injective (le_antisymm hle h1)
  apply hne
  apply iota_injective p
  apply Subtype.ext; apply Subtype.ext
  exact heq

theorem psiMap_eq_zero {f : MvPolynomial (Fin (n / p)) k}
    (hf : psiMap (k := k) (n := n) p f = 0) : f = 0 := by
  by_contra hne
  have hsupp : f.support.Nonempty := by
    rw [Finset.nonempty_iff_ne_empty, Ne, MvPolynomial.support_eq_empty]; exact hne
  obtain ⟨c₀, hc₀, hmax⟩ := Finset.exists_max_image f.support
    (fun c => keyL (lamDelta (lamC p c))) hsupp
  have hcoord : (h0Basis (k := k) (n := n) p).repr (psiMap (k := k) (n := n) p f)
      (iota (n := n) p c₀) = 0 := by
    rw [hf, map_zero, Finsupp.zero_apply]
  rw [psiMap_repr, Finset.sum_eq_single c₀] at hcoord
  · rw [iota_val, repr_Ec_leading] at hcoord
    exact mul_ne_zero (mem_support_iff.mp hc₀) (leadUnit_ne_zero (k := k)) hcoord
  · intro c hc hcne
    rw [repr_Ec_iota_eq_zero p hcne (hmax c hc), mul_zero]
  · intro h; exact absurd hc₀ h

theorem psiMap_injective : Function.Injective (psiMap (k := k) (n := n) p) := by
  intro f g hfg
  have := psiMap_eq_zero (k := k) (n := n) p (f := f - g) (by rw [map_sub, hfg, sub_self])
  exact sub_eq_zero.mp this

theorem h0Basis_mem_range (α : ↥(ntSet (n := n) p)ᶜ) :
    h0Basis (k := k) (n := n) p α ∈ LinearMap.range (psiMap (k := k) (n := n) p) := by
  refine (InvImage.wf (fun α : ↥(ntSet (n := n) p)ᶜ => keyL α.1.1) wellFounded_lt).induction
    (C := fun α => h0Basis (k := k) (n := n) p α ∈ LinearMap.range (psiMap (k := k) (n := n) p))
    α ?_
  intro α ih
  obtain ⟨c, rfl⟩ := iota_surjective p α
  have hu : schurBasis.repr (EcSym (k := k) p c) (iota (n := n) p c).1 ≠ 0 := by
    rw [iota_val, repr_Ec_leading]; exact leadUnit_ne_zero
  have hxu : (h0Basis (k := k) (n := n) p).repr (psiMap (k := k) (n := n) p (monomial c 1))
      (iota p c) = schurBasis.repr (EcSym (k := k) p c) (iota (n := n) p c).1 :=
    psiMap_monomial_repr p c _
  have hmem : iota p c ∈ ((h0Basis (k := k) (n := n) p).repr
      (psiMap (k := k) (n := n) p (monomial c 1))).support := by
    rw [Finsupp.mem_support_iff, hxu]; exact hu
  have hx := ((h0Basis (k := k) (n := n) p).linearCombination_repr
    (psiMap (k := k) (n := n) p (monomial c 1))).symm
  rw [Finsupp.linearCombination_apply, Finsupp.sum, ← Finset.add_sum_erase _ _ hmem, hxu] at hx
  have hrest : ∑ α' ∈ ((h0Basis (k := k) (n := n) p).repr
      (psiMap (k := k) (n := n) p (monomial c 1))).support.erase (iota p c),
      (h0Basis (k := k) (n := n) p).repr (psiMap (k := k) (n := n) p (monomial c 1)) α' •
        h0Basis (k := k) (n := n) p α' ∈ LinearMap.range (psiMap (k := k) (n := n) p) := by
    refine Submodule.sum_mem _ fun α' hα' => Submodule.smul_mem _ _ (ih α' ?_)
    have hne := Finset.ne_of_mem_erase hα'
    have hsupp := Finset.mem_of_mem_erase hα'
    rw [Finsupp.mem_support_iff, psiMap_monomial_repr] at hsupp
    have hle := key_le_of_repr_ne_zero p c _ hsupp
    refine lt_of_le_of_ne hle fun heq => hne ?_
    apply Subtype.ext; apply Subtype.ext
    exact keyL_injective heq
  have hxr : psiMap (k := k) (n := n) p (monomial c 1) ∈
      LinearMap.range (psiMap (k := k) (n := n) p) := ⟨_, rfl⟩
  have h1 := Submodule.sub_mem _ hxr hrest
  rw [sub_eq_of_eq_add hx] at h1
  have h2 := Submodule.smul_mem _ (schurBasis.repr (EcSym (k := k) p c) (iota (n := n) p c).1)⁻¹ h1
  rwa [smul_smul, inv_mul_cancel₀ hu, one_smul] at h2

theorem psiMap_surjective : Function.Surjective (psiMap (k := k) (n := n) p) := by
  rw [← LinearMap.range_eq_top, eq_top_iff, ← (h0Basis (k := k) (n := n) p).span_eq,
    Submodule.span_le]
  rintro _ ⟨α, rfl⟩
  exact h0Basis_mem_range p α

/-- `Ψ : 𝕜[y_1, …, y_N] → H_{/0}(Sym_n)` is bijective. -/
theorem psiMap_bijective : Function.Bijective (psiMap (k := k) (n := n) p) :=
  ⟨psiMap_injective p, psiMap_surjective p⟩

end Psi

/-! ## Theorem A.4 (2) -/

section QIso

variable {k : Type*} [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p] {n : ℕ}

omit hp [CharP k p] in
theorem algA_le_SymSub : Subalgebra.toSubmodule (algA (k := k) (n := n) p) ≤ SymSub :=
  fun _ ha => algA_le_sym p ha

/-- The inclusion `𝕜[e_p^p, e_{2p}^p, …] ↪ Sym_n` as a linear map. -/
def inclA : Subalgebra.toSubmodule (algA (k := k) (n := n) p) →ₗ[k]
    (SymSub : Submodule k (MvPolynomial (Fin n) k)) :=
  Submodule.inclusion (algA_le_SymSub p)

omit hp in
/-- The inclusion is a morphism of p-complexes (`d = 0` on `𝕜[e_p^p, …]`). -/
theorem inclA_comm :
    inclA (k := k) (n := n) p ∘ₗ 0 = dSym ∘ₗ inclA p := by
  refine LinearMap.ext fun a => ?_
  simp only [LinearMap.comp_zero, LinearMap.zero_apply, LinearMap.comp_apply]
  apply Subtype.ext
  rw [dSym_apply]
  exact (pd_algA p a.2).symm

omit hp [CharP k p] in
theorem mem_algA_iff {a : MvPolynomial (Fin n) k} :
    a ∈ algA (k := k) (n := n) p ↔ ∃ f, evE p f = a := by
  rw [algA, ← MvPolynomial.aeval_range]
  rfl

/-- **Ellis–Qi, Theorem A.4 (2)** (in `n` variables, `N = ⌊n/p⌋`): the inclusion
`𝕜[e_p^p, e_{2p}^p, …, e_{Np}^p] ↪ Sym_n` is a quasi-isomorphism of p-complexes, i.e. it induces
isomorphisms on all slash cohomology groups `H_{/j}`, `0 ≤ j ≤ p - 2` (the differential of the
subalgebra is zero, `inclA_comm`). -/
theorem thmA4_2 : IsQuasiIso (0 : Module.End k (Subalgebra.toSubmodule (algA (k := k) (n := n) p)))
    dSym (inclA p) (inclA_comm p) p := by
  intro j hj
  rcases Nat.eq_zero_or_pos j with rfl | hj0
  · constructor
    · rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
      intro z hz
      induction z using Submodule.Quotient.induction_on with
      | H z =>
      obtain ⟨⟨a, ha⟩, hz'⟩ := z
      obtain ⟨f, rfl⟩ := (mem_algA_iff p).mp ha
      rw [slashMap_mk] at hz
      have h0 : psiMap (k := k) (n := n) p f = 0 := hz
      have hf := psiMap_injective (k := k) (n := n) p (h0.trans (map_zero _).symm)
      subst hf
      have : (⟨⟨evE p 0, ha⟩, hz'⟩ : LinearMap.ker ((0 : Module.End k
          (Subalgebra.toSubmodule (algA (k := k) (n := n) p))) ^ (0 + 1))) = 0 := by
        apply Subtype.ext; apply Subtype.ext; simp
      rw [this]
      rfl
    · intro y
      obtain ⟨f, rfl⟩ := psiMap_surjective (k := k) (n := n) p y
      refine ⟨Submodule.Quotient.mk ⟨⟨evE p f, (mem_algA_iff p).mpr ⟨f, rfl⟩⟩, by simp⟩, ?_⟩
      rw [slashMap_mk]
      rfl
  · have : Subsingleton (SlashCohomology (0 : Module.End k
        (Subalgebra.toSubmodule (algA (k := k) (n := n) p))) p j) := by
      rw [slashCohomology_subsingleton_iff]
      intro v _
      refine Submodule.mem_sup_right ?_
      rw [LinearMap.mem_ker, zero_pow (by omega), LinearMap.zero_apply]
    have := slash_sym_pos (k := k) (n := n) p j hj0 hj
    exact ⟨fun _ _ _ => Subsingleton.elim _ _, fun y => ⟨0, Subsingleton.elim _ _⟩⟩

/-- `𝕜[e_p^p, e_{2p}^p, …, e_{Np}^p]` is a polynomial algebra: the generators are algebraically
independent. -/
theorem evE_injective : Function.Injective (evE (k := k) (n := n) p) := by
  intro f g h
  apply psiMap_injective (k := k) (n := n) p
  rw [psiMap_apply, psiMap_apply]
  simp only [slashClass]
  congr 2
  exact Subtype.ext h

end QIso

end

end OddMath.Frontier.EQPdg
