import OddMath.Frontier.EQInductionPoly
import OddMath.Frontier.EQThickSlider

/-!
# The element `(x_{a+1} ⋯ x_{a+b})^a` of `OPol_{a+b}`

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.4, (4.32) and the sentence after it ("the right ideal generated by `(x_{a+1} ⋯ x_{a+b})^a`").

* `strictSum_top`, `strictSum_eq_zero_of_lt`: `e_n(x_1, …, x_n) = x_1 ⋯ x_n` and `e_k = 0` for
  `k > n`, for any letters in a ring;
* `generator_mul`: `x_k f = c_k(f) x_k`, `c_k` the diagonal map `x_k ↦ x_k`, `x_j ↦ -x_j` (`j ≠ k`);
* `generator_mul_elementary_top`: `x_k e_n = (-1)^{n-1} e_n x_k`;
* `d_elementary_top`: `d(e_n) = e_1 e_n`;
* for `P = e_b(y) = y_1 ⋯ y_b ∈ OPol_{a+b}`: `d_topY_pow`: `d(P^m) = {m} e_1(y) P^m`, and the
  (super)commutation of `P` with the variables (`inclX_generator_mul_topY`, `inclY_generator_mul_topY`);
* `d_topY_pow_ne_printed`, `etY_sq_add_d_ne_zero`: the printed differential of (4.32) is not that of the right
  ideal, and read literally it does not square to zero (`a = 3`, `b = 2`, via a `2 × 2` matrix
  representation of `OPol_5`; ERRATA [EQ] 24).
-/

namespace OddMath.Frontier.EQFunctor

open OddMath.SkewPolynomial (SkewPolynomial generator)
open OddMath.Frontier.EQSkewDifferential
open OddMath.Frontier.EQZab (inclX inclY diagHom diagHom_generator inclX_generator inclY_generator par)
open OddMath.Frontier.FiniteCompleteElementary (FiniteWords.strictSum FiniteWords.strictSum_succ
  FiniteWords.strictSum_zero FiniteWords.strictSum_empty)

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) restrPolyNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))
local instance (priority := high) restrPolyNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

/-! ### Top elementary polynomials of any letters -/

theorem strictSum_eq_zero_of_lt {R : Type*} [Ring R] :
    ∀ {n k : ℕ} (x : Fin n → R), n < k → FiniteWords.strictSum x k = 0
  | 0, k + 1, x, _ => FiniteWords.strictSum_empty x k
  | n + 1, k + 1, x, h => by
    rw [FiniteWords.strictSum_succ, strictSum_eq_zero_of_lt _ (by omega),
      strictSum_eq_zero_of_lt _ (by omega), mul_zero, add_zero]

theorem strictSum_top {R : Type*} [Ring R] :
    ∀ {n : ℕ} (x : Fin n → R), FiniteWords.strictSum x n = (List.ofFn x).prod
  | 0, x => by simp
  | n + 1, x => by
    rw [FiniteWords.strictSum_succ, strictSum_top, strictSum_eq_zero_of_lt _ (by omega), add_zero,
      List.ofFn_succ, List.prod_cons]

/-! ### Moving a variable across a polynomial -/

/-- `c_k`: `x_k ↦ x_k`, `x_j ↦ -x_j` (`j ≠ k`). -/
def cK {n : ℕ} (k : Fin n) (j : Fin n) : ℤ := if j = k then 1 else -1

theorem generator_mul {n : ℕ} (k : Fin n) (f : SkewPolynomial n) :
    generator k * f = diagHom n (cK k) f * generator k := by
  induction f using induction_generator with
  | hgen j =>
    rw [diagHom_generator, cK]
    split_ifs with h
    · subst h; rw [one_smul]
    · rw [generator_anticomm _ _ (Ne.symm h), neg_one_smul, neg_mul]
  | h0 => rw [EQBorel.sp_mul_zero, map_zero, EQBorel.sp_zero_mul]
  | h1 => rw [map_one]; simp
  | hadd f g hf hg => rw [mul_add, hf, hg, map_add, add_mul]
  | hneg f hf => rw [mul_neg, hf, map_neg, neg_mul]
  | hmul f g hf hg =>
    rw [← EQBorel.sp_mul_assoc, hf, EQBorel.sp_mul_assoc, hg, ← EQBorel.sp_mul_assoc, map_mul]

theorem prod_ofFn_smul {R : Type*} [Ring R] :
    ∀ {n : ℕ} (c : Fin n → ℤ) (x : Fin n → R),
      (List.ofFn fun j => c j • x j).prod = (∏ j, c j) • (List.ofFn x).prod
  | 0, c, x => by simp
  | n + 1, c, x => by
    rw [List.ofFn_succ, List.prod_cons, List.ofFn_succ, List.prod_cons, Fin.prod_univ_succ,
      prod_ofFn_smul (fun j => c j.succ) (fun j => x j.succ), smul_mul_smul_comm, mul_comm (c 0)]

theorem diagHom_elementary_top {n : ℕ} (c : Fin n → ℤ) :
    diagHom n c (elementary n n) = (∏ j, c j) • elementary n n := by
  rw [elementary, strictSum_top, map_list_prod, List.map_ofFn]
  simp only [Function.comp_def, diagHom_generator]
  exact prod_ofFn_smul c _

theorem prod_cK {n : ℕ} (k : Fin n) : ∏ j, cK k j = (-1) ^ (n - 1) := by
  simp only [cK]
  rw [Finset.prod_ite, Finset.prod_const_one, one_mul, Finset.prod_const, Finset.filter_ne',
    Finset.card_erase_of_mem (Finset.mem_univ _), Finset.card_univ, Fintype.card_fin]

/-- `x_k e_n = (-1)^{n-1} e_n x_k`. -/
theorem generator_mul_elementary_top {n : ℕ} (k : Fin n) :
    generator k * elementary n n = (-1 : ℤ) ^ (n - 1) • (elementary n n * generator k) := by
  rw [generator_mul, diagHom_elementary_top, prod_cK, smul_mul_assoc]

/-- `e_1 e_n = (-1)^{n-1} e_n e_1`. -/
theorem elementary_one_mul_top {n : ℕ} :
    elementary n 1 * elementary n n = (-1 : ℤ) ^ (n - 1) • (elementary n n * elementary n 1) := by
  rw [elementary, EQZab.strictSum_one, Finset.sum_mul, Finset.mul_sum, Finset.smul_sum]
  exact Finset.sum_congr rfl fun k _ => generator_mul_elementary_top k

/-- `d(e_n) = e_1 e_n` (Lemma 3.2 with `e_{n+1} = 0`). -/
theorem d_elementary_top {n : ℕ} : d n (elementary n n) = elementary n 1 * elementary n n := by
  rw [d_elementary, show elementary n (n + 1) = 0 from strictSum_eq_zero_of_lt _ (by omega),
    smul_zero, sub_zero]

/-! ### Permuting a product of anticommuting letters -/

theorem swap_succ_succ_apply {m : ℕ} (a b j : Fin m) :
    Equiv.swap a.succ b.succ j.succ = (Equiv.swap a b j).succ := by
  rw [Equiv.swap_apply_def, Equiv.swap_apply_def]
  simp only [Fin.succ_inj]
  split_ifs <;> rfl

/-- Swapping two adjacent letters in a product of pairwise anticommuting letters changes its sign. -/
theorem prod_ofFn_swap {R : Type*} [Ring R] :
    ∀ (m : ℕ) (x : Fin (m + 2) → R), (∀ i j, i ≠ j → x i * x j = -(x j * x i)) →
      ∀ k : Fin (m + 1),
        (List.ofFn fun j => x (Equiv.swap k.castSucc k.succ j)).prod = -(List.ofFn x).prod
  | m, x, hx, ⟨0, hk⟩ => by
    rw [List.ofFn_succ, List.ofFn_succ, List.prod_cons, List.prod_cons, List.ofFn_succ,
      List.ofFn_succ, List.prod_cons, List.prod_cons]
    have h0 : Equiv.swap (⟨0, hk⟩ : Fin (m + 1)).castSucc (⟨0, hk⟩ : Fin (m + 1)).succ 0 = 1 :=
      Equiv.swap_apply_left (0 : Fin (m + 2)) 1
    have h1 : Equiv.swap (⟨0, hk⟩ : Fin (m + 1)).castSucc (⟨0, hk⟩ : Fin (m + 1)).succ (Fin.succ 0) = 0 :=
      Equiv.swap_apply_right (0 : Fin (m + 2)) 1
    have h2 : ∀ j : Fin m, Equiv.swap (⟨0, hk⟩ : Fin (m + 1)).castSucc (⟨0, hk⟩ : Fin (m + 1)).succ
        j.succ.succ = j.succ.succ := fun j => Equiv.swap_apply_of_ne_of_ne
          (fun h => by simp [Fin.ext_iff] at h) (fun h => by simp [Fin.ext_iff] at h)
    simp only [h0, h1, h2]
    rw [← mul_assoc, ← mul_assoc, hx 1 0 (by simp), neg_mul]
    rfl
  | m + 1, x, hx, ⟨k + 1, hk⟩ => by
    have ih := prod_ofFn_swap m (fun j => x j.succ) (fun i j h => hx _ _ (fun e => h (Fin.succ_inj.mp e)))
      ⟨k, by omega⟩
    rw [List.ofFn_succ, List.prod_cons]
    conv_rhs => rw [List.ofFn_succ, List.prod_cons]
    have h0 : Equiv.swap (⟨k + 1, hk⟩ : Fin (m + 2)).castSucc (⟨k + 1, hk⟩ : Fin (m + 2)).succ 0 = 0 :=
      Equiv.swap_apply_of_ne_of_ne (fun h => by simp [Fin.ext_iff] at h)
        (fun h => by simp [Fin.ext_iff] at h)
    have hs : ∀ j : Fin (m + 2), Equiv.swap (⟨k + 1, hk⟩ : Fin (m + 2)).castSucc
        (⟨k + 1, hk⟩ : Fin (m + 2)).succ j.succ =
          (Equiv.swap (⟨k, by omega⟩ : Fin (m + 1)).castSucc (⟨k, by omega⟩ : Fin (m + 1)).succ j).succ := by
      intro j
      rw [← swap_succ_succ_apply]
      rfl
    simp only [h0, hs]
    rw [ih, mul_neg]

/-! ### `s_i` and `∂_i` on the top elementary polynomial -/

theorem theta_eq_diagHom (n : ℕ) : theta n = diagHom n (fun j => (-1 : ℤ) ^ j.val) :=
  ringHom_ext fun j => by rw [theta_generator, diagHom_generator]

/-- `∂_i e_n = 0`: `e_n = ±ẽ_n` is twisted odd symmetric. -/
theorem divided_elementary_top (m : ℕ) (i : Fin (m + 1)) :
    AllRankDivided.divided i (elementary (m + 2) (m + 2)) = 0 := by
  have h := EQZab.theta_elementary_mem_kernel m (m + 2) i
  rw [theta_eq_diagHom, diagHom_elementary_top, map_zsmul] at h
  have hc : (∏ j : Fin (m + 2), (-1 : ℤ) ^ j.val) * ∏ j : Fin (m + 2), (-1 : ℤ) ^ j.val = 1 := by
    rw [← Finset.prod_mul_distrib]
    exact Finset.prod_eq_one fun j _ => by rw [← pow_add, ← two_mul, pow_mul]; norm_num
  have h2 := congrArg (fun z => (∏ j : Fin (m + 2), (-1 : ℤ) ^ j.val) • z) h
  simp only [smul_zero, smul_smul, hc, one_smul] at h2
  exact h2

/-- `s_i e_n = (-1)^{n-1} e_n`. -/
theorem s_elementary_top (m : ℕ) (i : Fin (m + 1)) :
    AllRankDivided.s i (elementary (m + 2) (m + 2)) = (-1 : ℤ) ^ (m + 1) • elementary (m + 2) (m + 2) := by
  have h := EQZab.ringHom_strictSum (AllRankDivided.s i).toRingHom (generator (n := m + 2)) (m + 2)
  change AllRankDivided.s i (elementary (m + 2) (m + 2)) = _ at h
  rw [h, elementary, strictSum_top, strictSum_top]
  simp only [RingEquiv.toRingHom_eq_coe, RingHom.coe_coe, AllRankDivided.s_generator]
  rw [show (List.ofFn fun j => -generator (Equiv.swap i.castSucc i.succ j)) =
      List.ofFn fun j => (fun _ => (-1 : ℤ)) j • generator (Equiv.swap i.castSucc i.succ j) by simp,
    prod_ofFn_smul, prod_ofFn_swap m _ (fun a b h => generator_anticomm a b h), Finset.prod_const,
    Finset.card_univ, Fintype.card_fin, smul_neg, ← neg_smul, pow_succ, pow_succ]
  congr 1
  ring

/-! ### `P = y_1 ⋯ y_b ∈ OPol_{a+b}` -/

variable (A B : ℕ)

/-- `P = e_b(y) = y_1 ⋯ y_b`. -/
abbrev topY : SkewPolynomial (A + B) := inclY A B (elementary B B)

/-- `e_1(y)`. -/
abbrev e1Y : SkewPolynomial (A + B) := inclY A B (elementary B 1)

variable {A B}

theorem topY_mem_grading : topY A B ∈ grading (A + B) (B : ℤ) :=
  inclY_mem_grading (elementary_mem_grading B)

theorem topY_pow_mem_grading (m : ℕ) : topY A B ^ m ∈ grading (A + B) ((B : ℤ) * m) := by
  induction m with
  | zero => simpa using one_mem_grading'
  | succ m ih =>
    rw [pow_succ, show (B : ℤ) * ↑(m + 1) = B * m + B by push_cast; ring]
    exact mul_mem_grading' ih topY_mem_grading

theorem inclX_generator_mul_topY (i : Fin A) :
    inclX A B (generator i) * topY A B = (-1 : ℤ) ^ B • (topY A B * inclX A B (generator i)) := by
  have h := inclY_mul_inclX_of_mem (a := A) (b := B) (generator_mem_grading i)
    (elementary_mem_grading (n := B) B)
  rw [h, smul_smul, koszulSign_eq_neg_one_pow_natAbs, mul_one]
  rw [show ((-1 : ℤ) ^ B * (-1) ^ (B : ℤ).natAbs) = 1 by
    rw [Int.natAbs_natCast, ← pow_add, ← two_mul, pow_mul]; norm_num, one_smul]

theorem inclY_generator_mul_topY (j : Fin B) :
    inclY A B (generator j) * topY A B = (-1 : ℤ) ^ (B - 1) • (topY A B * inclY A B (generator j)) := by
  rw [← map_mul, generator_mul_elementary_top, map_zsmul, map_mul]

/-- A generator `g` with `g P = s • P g` satisfies `g P^m = s^m • P^m g`. -/
theorem mul_topY_pow {g : SkewPolynomial (A + B)} {s : ℤ} (hg : g * topY A B = s • (topY A B * g))
    (m : ℕ) : g * topY A B ^ m = s ^ m • (topY A B ^ m * g) := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [pow_succ, ← EQBorel.sp_mul_assoc, ih, smul_mul_assoc, EQBorel.sp_mul_assoc, hg, mul_smul_comm,
      smul_smul, ← EQBorel.sp_mul_assoc, pow_succ]

theorem e1Y_mul_topY : e1Y A B * topY A B = (-1 : ℤ) ^ (B - 1) • (topY A B * e1Y A B) := by
  rw [← map_mul, elementary_one_mul_top, map_zsmul, map_mul]

theorem d_topY : d (A + B) (topY A B) = e1Y A B * topY A B := by
  rw [EQZab.d_inclY, d_elementary_top, map_mul]

/-- **`d(P^m) = {m} e_1(y) P^m`** for `P = y_1 ⋯ y_b`. -/
theorem d_topY_pow (m : ℕ) : d (A + B) (topY A B ^ m) = par m • (e1Y A B * topY A B ^ m) := by
  induction m with
  | zero => simp [par]
  | succ m ih =>
    rcases Nat.eq_zero_or_pos B with hB | hB
    · subst hB
      have : e1Y A 0 = 0 := by
        rw [e1Y, show elementary 0 1 = 0 from FiniteWords.strictSum_empty _ 0, map_zero]
      have h1 : topY A 0 = 1 := by
        rw [topY, show elementary 0 0 = 1 from FiniteWords.strictSum_zero _, map_one]
      rw [this, h1, one_pow, EQBorel.sp_zero_mul, smul_zero]
      exact EQSkewDifferential.d_one
    have hc := mul_topY_pow (e1Y_mul_topY (A := A) (B := B)) m
    have hc' : topY A B ^ m * e1Y A B = ((-1 : ℤ) ^ (B - 1)) ^ m • (e1Y A B * topY A B ^ m) := by
      rw [hc, smul_smul, ← mul_pow, ← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_pow,
        one_smul]
    rw [pow_succ, EQSkewDifferential.d_mul, ih, d_topY, parityInv_of_mem (topY_pow_mem_grading m),
      smul_mul_assoc, smul_mul_assoc, ← EQBorel.sp_mul_assoc (topY A B ^ m), hc', smul_mul_assoc,
      smul_smul, EQBorel.sp_mul_assoc, ← add_smul,
      koszulSign_eq_neg_one_pow_natAbs, show ((B : ℤ) * m).natAbs = B * m by
        rw [Int.natAbs_mul]; simp]
    congr 1
    unfold par
    rcases Nat.even_or_odd m with hm | hm
    · rw [Nat.even_iff.mp hm, show (m + 1) % 2 = 1 by have := Nat.even_iff.mp hm; omega]
      have : ((-1 : ℤ) ^ (B * m)) * ((-1) ^ (B - 1)) ^ m = 1 := by
        rw [← pow_mul, ← pow_add]
        exact Even.neg_one_pow (by
          rcases hm with ⟨k, rfl⟩
          exact ⟨B * k + (B - 1) * k, by ring⟩)
      rw [this]; norm_num
    · rw [Nat.odd_iff.mp hm, show (m + 1) % 2 = 0 by have := Nat.odd_iff.mp hm; omega]
      have : ((-1 : ℤ) ^ (B * m)) * ((-1) ^ (B - 1)) ^ m = -1 := by
        rw [← pow_mul, ← pow_add, show B * m + (B - 1) * m = (2 * B - 1) * m by
          rw [← add_mul]; congr 1; omega]
        exact Odd.neg_one_pow (Nat.odd_mul.mpr ⟨⟨B - 1, by omega⟩, hm⟩)
      rw [this]; norm_num

/-! ### Witnesses for (4.32), `a = 3`, `b = 2` -/

/-- The Pauli matrices `σ_z`, `σ_x`, which anticommute. -/
def sigZ : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, -1]
def sigX : Matrix (Fin 2) (Fin 2) ℤ := !![0, 1; 1, 0]

/-- The images of the variables: `x_i ↦ 0`, `y_1 ↦ σ_z`, `y_2 ↦ σ_x`. -/
def rhoImg (j : Fin (3 + 2)) : Matrix (Fin 2) (Fin 2) ℤ :=
  if j.val = 3 then sigZ else if j.val = 4 then sigX else 0

theorem rhoImg_anticomm (i j : Fin (3 + 2)) (h : i ≠ j) :
    rhoImg i * rhoImg j + rhoImg j * rhoImg i = 0 := by
  fin_cases i <;> fin_cases j <;> first | exact absurd rfl h | decide

/-- A representation of `OPol_5` on `ℤ²` killing `x_1, x_2, x_3`. -/
def rho52 : SkewPolynomial (3 + 2) →+* Matrix (Fin 2) (Fin 2) ℤ := skewLift rhoImg rhoImg_anticomm

theorem rho52_inclY_gen0 : rho52 (inclY 3 2 (generator 0)) = sigZ := by
  rw [inclY_generator, rho52, skewLift_generator]; rfl

theorem rho52_inclY_gen1 : rho52 (inclY 3 2 (generator 1)) = sigX := by
  rw [inclY_generator, rho52, skewLift_generator]; rfl

theorem elementary_two_two' : elementary 2 2 = generator 0 * generator 1 := by
  simp [elementary, FiniteWords.strictSum_succ, EQBorel.sp_mul_zero]

theorem rho52_topY : rho52 (topY 3 2) = sigZ * sigX := by
  rw [topY, elementary_two_two', map_mul, map_mul, rho52_inclY_gen0, rho52_inclY_gen1]

theorem rho52_e1Y : rho52 (e1Y 3 2) = sigZ + sigX := by
  rw [e1Y, elementary, EQZab.strictSum_one, Fin.sum_univ_two, map_add, map_add, rho52_inclY_gen0,
    rho52_inclY_gen1]

theorem rho52_etY : rho52 (EQZab.etY 3 2) = sigZ - sigX := by
  rw [EQZab.etY, elementary, EQZab.strictSum_one, Fin.sum_univ_two]
  simp only [map_add, theta_generator, map_zsmul, rho52_inclY_gen0, rho52_inclY_gen1]
  simp [sub_eq_add_neg]

/-- **(4.32), right ideal reading**: for `a = 3`, `b = 2` and `P = y_1 y_2`, `d(P^3) = e_1(y) P^3`
(`d_topY_pow`) is not `{3} ẽ_1(y) P^3`, the printed `d(1^♮) = {a} ẽ_1(y) 1^♮`. -/
theorem d_topY_pow_ne_printed :
    d (3 + 2) (topY 3 2 ^ 3) ≠ par 3 • (EQZab.etY 3 2 * topY 3 2 ^ 3) := by
  intro h
  rw [d_topY_pow] at h
  have := congrArg rho52 h
  rw [map_zsmul, map_zsmul, map_mul, map_mul, map_pow, rho52_e1Y, rho52_etY, rho52_topY] at this
  revert this
  decide

/-- **(4.32), literal reading** (`1^♮ ONH_5`, free on `1^♮`, with `d(1^♮) = 1^♮ c`, `c = {3} ẽ_1(y)`):
the right Leibniz rule forces `d²(1^♮) = 1^♮ (c² + d c)`, and `c² + d c ≠ 0`. -/
theorem etY_sq_add_d_ne_zero :
    par 3 • EQZab.etY 3 2 * (par 3 • EQZab.etY 3 2) + d (3 + 2) (par 3 • EQZab.etY 3 2) ≠ 0 := by
  intro h
  have hd : d (3 + 2) (EQZab.etY 3 2) =
      inclY 3 2 (generator 0) * inclY 3 2 (generator 0) - inclY 3 2 (generator 1) * inclY 3 2 (generator 1) := by
    rw [EQZab.etY, EQZab.d_inclY, elementary, EQZab.strictSum_one, Fin.sum_univ_two, map_add,
      theta_generator, theta_generator, map_add, map_zsmul, map_zsmul, d_generator, d_generator,
      map_add, map_zsmul, map_zsmul, map_mul, map_mul]
    simp [sub_eq_add_neg]
  rw [map_zsmul, hd] at h
  have := congrArg rho52 h
  rw [map_add, map_mul, map_zsmul, map_zsmul, map_sub, map_mul, map_mul, rho52_etY, rho52_inclY_gen0,
    rho52_inclY_gen1, map_zero] at this
  revert this
  decide

end

end OddMath.Frontier.EQFunctor
