import OddMath.Frontier.SignedPermutation
import OddMath.Frontier.EKLSectionTwoH
import OddMath.Frontier.ElementaryBranching
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic.Module

/-!
# The local differential on skew polynomials

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§2.3 ((2.44), Lemma 2.18) and §3.1–§3.2 (Proposition 3.1, Lemma 3.2, Proposition 3.7,
Definition 3.8).

On `OPol_n = SkewPolynomial n` (integer coefficients, generators `x_i`, strands numbered from
`0`) this file constructs:

* `skewLift`: the universal property of `OPol_n` (a ring map is determined by images of the
  generators which pairwise anticommute);
* `parityInv` (`ι`, `ι(x_i) = -x_i`), `theta` (the twisting `θ(x_i) = (-1)^i x_i` of (2.35),
  0-indexed), `longestPerm` (`w₀(x_i) = x_{n-1-i}`, the plain permutation action) and
  `twistRev = θ ∘ w₀`;
* `d`, the local differential `d(x_i) = x_i²` of §3.1, with the super Leibniz rule
  `d(fg) = d(f) g + ι(f) d(g)` (`d_mul`), `d² = 0` (`d_d`) and `d ∘ ι = -ι ∘ d`;
* **Lemma 3.2** (`d_elementary`): for the untwisted odd elementary polynomials
  `e_k = Σ_{i_1<⋯<i_k} x_{i_1}⋯x_{i_k}` (`elementary`),
  `d(e_k) = e_1 e_k - {k+1} e_{k+1}`, where `{m} = m mod 2`; consequently `d` preserves the
  subring `OΛ_n` generated by the `e_k` (`d_mem_osym`). The identity is proved for any family
  of pairwise anticommuting elements in a ring with an odd derivation (`D_strictSum`);
* **Proposition 3.1** (`prop_3_1_left`, `prop_3_1_right`): for `α ∈ ℤⁿ`, the differential
  `d_α(f 1_α) = (d f + ι(f) Σ α_i x_i) 1_α` on the rank-one free left module squares to zero iff
  `α ∈ {0,1}ⁿ`; on the rank-one free right module with generator of parity `p`,
  `d(1_α f) = 1_α (Σ α_i x_i f + (-1)^p d f)` squares to zero iff `α_i ∈ {0, (-1)^{p+1}}`.
  In both cases the Leibniz rule holds by construction (`dAlpha_mul`, `dAlphaRight_mul`);
* **Proposition 3.7 / Definition 3.8** (`dAlpha_mul_twistRev`): for
  `α = (0,1,0,1,…)` (`zAlpha`, Ellis–Qi's `{i-1}` in 1-indexed notation), the rank-one free left
  dg module `Z_n = OPol_n(α)` with the right action `1_z f = (θ ∘ w₀)(f) 1_z` satisfies the
  Leibniz rule for the right action, `d(g 1_z · f) = d(g 1_z) · f + ι(g) 1_z · d(f)`. This is
  proved for every `f ∈ OPol_n` (not only `f ∈ OΛ_n`), from the identity
  `d(φ f) = φ(d f) + s φ(f) - ι(φ f) s` for `φ = θ ∘ w₀`, `s = Σ α_i x_i` (`d_twistRev`).

The dg (super)module structures are recorded here as the explicit additive maps and their
Leibniz rules and square-zero laws; the packaging as dg modules is separate.
-/

namespace OddMath.Frontier.EQSkewDifferential

open OddMath.SkewPolynomial (SkewPolynomial generator)
open OddMath.PbwL2 (relIdeal q)
open FiniteCompleteElementary
open scoped BigOperators

noncomputable section

/-! ## Elementary sums in a ring with an odd derivation -/

section Generic

variable {R : Type*} [Ring R]

/-- The Leibniz rule of an odd derivation `D` twisted by `ι` forces `D 1 = 0`. -/
theorem D_one (ι : R →+* R) (D : R →+ R) (hD : ∀ a b, D (a * b) = D a * b + ι a * D b) :
    D 1 = 0 := by
  have h := hD 1 1
  simp only [mul_one, map_one, one_mul] at h
  exact left_eq_add.mp h

/-- `ι` acts on the degree-`k` elementary sum of `ι`-odd elements by `(-1)^k`. -/
theorem iota_strictSum (ι : R →+* R) :
    ∀ {m : ℕ} (y : Fin m → R), (∀ i, ι (y i) = -y i) → ∀ k,
      ι (FiniteWords.strictSum y k) = (-1 : ℤ) ^ k • FiniteWords.strictSum y k := by
  intro m
  induction m with
  | zero =>
    intro y _ k
    cases k with
    | zero => simp
    | succ k => simp
  | succ m ih =>
    intro y hy k
    cases k with
    | zero => simp
    | succ k =>
      rw [FiniteWords.strictSum_succ, map_add, map_mul, hy, ih _ (fun i => hy _),
        ih _ (fun i => hy _)]
      rw [pow_succ, mul_comm, ← smul_smul, neg_one_smul, ← smul_smul, neg_one_smul]
      simp only [neg_mul, mul_smul_comm, smul_add, smul_neg, neg_add]

/-- An element anticommuting with every letter passes a degree-`k` elementary sum with the
sign `(-1)^k`. -/
theorem mul_strictSum (z : R) :
    ∀ {m : ℕ} (y : Fin m → R), (∀ i, z * y i = -(y i * z)) → ∀ k,
      z * FiniteWords.strictSum y k = (-1 : ℤ) ^ k • (FiniteWords.strictSum y k * z) := by
  intro m
  induction m with
  | zero =>
    intro y _ k
    cases k with
    | zero => simp
    | succ k => simp
  | succ m ih =>
    intro y hy k
    cases k with
    | zero => simp
    | succ k =>
      rw [FiniteWords.strictSum_succ, mul_add, ← mul_assoc, hy, neg_mul, mul_assoc,
        ih _ (fun i => hy _), ih _ (fun i => hy _)]
      rw [pow_succ, mul_comm, ← smul_smul, neg_one_smul, ← smul_smul, neg_one_smul]
      simp only [add_mul, mul_smul_comm, smul_add, mul_assoc, neg_add]

theorem mod_two_identity (j : ℕ) :
    (-1 : ℤ) ^ (j + 1) - (((j + 2) % 2 : ℕ) : ℤ) + (((j + 1) % 2 : ℕ) : ℤ) = 0 := by
  rcases Nat.even_or_odd j with ⟨r, rfl⟩ | ⟨r, rfl⟩
  · have h1 : (r + r + 2) % 2 = 0 := by omega
    have h2 : (r + r + 1) % 2 = 1 := by omega
    rw [h1, h2, pow_succ, Even.neg_one_pow ⟨r, rfl⟩]
    norm_num
  · have h1 : (2 * r + 1 + 2) % 2 = 1 := by omega
    have h2 : (2 * r + 1 + 1) % 2 = 0 := by omega
    rw [h1, h2, show 2 * r + 1 + 1 = 2 * (r + 1) by ring, pow_mul]
    norm_num

/-- **Ellis–Qi, Lemma 3.2**, for any family of pairwise anticommuting `ι`-odd elements `y_i`
with `D(y_i) = y_i²` in a ring with an odd derivation `D`:
`D(e_k) = e_1 e_k - {k+1} e_{k+1}` for the elementary sums `e_k = Σ_{i_1<⋯<i_k} y_{i_1}⋯y_{i_k}`. -/
theorem D_strictSum (ι : R →+* R) (D : R →+ R) (hD : ∀ a b, D (a * b) = D a * b + ι a * D b) :
    ∀ {m : ℕ} (y : Fin m → R), (∀ i j, i ≠ j → y i * y j = -(y j * y i)) →
      (∀ i, ι (y i) = -y i) → (∀ i, D (y i) = y i * y i) → ∀ k,
      D (FiniteWords.strictSum y k) =
        FiniteWords.strictSum y 1 * FiniteWords.strictSum y k -
          (((k + 1) % 2 : ℕ) : ℤ) • FiniteWords.strictSum y (k + 1) := by
  have hzero : ∀ {m : ℕ} (y : Fin m → R),
      D (FiniteWords.strictSum y 0) =
        FiniteWords.strictSum y 1 * FiniteWords.strictSum y 0 -
          (((0 + 1) % 2 : ℕ) : ℤ) • FiniteWords.strictSum y (0 + 1) := by
    intro m y
    simp [D_one ι D hD]
  intro m
  induction m with
  | zero =>
    intro y _ _ _ k
    cases k with
    | zero => exact hzero y
    | succ k => simp
  | succ m ih =>
    intro y hanti hι hD' k
    cases k with
    | zero => exact hzero y
    | succ j =>
      set y' : Fin m → R := fun i => y i.castSucc
      set z : R := y (Fin.last m)
      have hanti' : ∀ i j, i ≠ j → y' i * y' j = -(y' j * y' i) := fun i j h =>
        hanti _ _ (fun h' => h (Fin.castSucc_injective _ h'))
      have hzy : ∀ i, z * y' i = -(y' i * z) := fun i =>
        hanti _ _ (Fin.castSucc_ne_last i).symm
      have IH := ih y' hanti' (fun i => hι _) (fun i => hD' _)
      have hlast : ∀ k, FiniteWords.strictSum y (k + 1) =
          FiniteWords.strictSum y' (k + 1) + FiniteWords.strictSum y' k * z :=
        fun k => ElementaryBranching.strictSum_last m k y
      have hι' := iota_strictSum ι y' (fun i => hι _)
      have hcomm := mul_strictSum z y' hzy
      have hz2 : D z = z * z := hD' _
      have hιz : ι z = -z := hι _
      rw [show j + 1 + 1 = (j + 1) + 1 from rfl, hlast (j + 1), hlast j, hlast 0,
        FiniteWords.strictSum_zero, one_mul, Nat.zero_add]
      rw [map_add, hD, IH (j + 1), IH j, hz2, hι' j]
      -- move `z` to the right in the two products where it sits on the left
      have e1 : z * FiniteWords.strictSum y' (j + 1) =
          (-1 : ℤ) ^ (j + 1) • (FiniteWords.strictSum y' (j + 1) * z) := hcomm (j + 1)
      have e2 : z * (FiniteWords.strictSum y' j * z) =
          (-1 : ℤ) ^ j • (FiniteWords.strictSum y' j * (z * z)) := by
        rw [← mul_assoc, hcomm j, smul_mul_assoc, mul_assoc]
      have key := mod_two_identity j
      set A := FiniteWords.strictSum y' 1
      set S0 := FiniteWords.strictSum y' j
      set S1 := FiniteWords.strictSum y' (j + 1)
      set S2 := FiniteWords.strictSum y' (j + 1 + 1)
      have expand : (A + z) * (S1 + S0 * z) =
          A * S1 + A * (S0 * z) + z * S1 + z * (S0 * z) := by
        simp only [add_mul, mul_add]; abel
      rw [expand, e1, e2]
      simp only [sub_mul, smul_mul_assoc, mul_assoc, smul_add]
      have hc : (((j + 1 + 1) % 2 : ℕ) : ℤ) =
          (-1 : ℤ) ^ (j + 1) + (((j + 1) % 2 : ℕ) : ℤ) := by linarith
      rw [hc]
      module

end Generic

/-! ## The ring structure of `OPol_n` -/

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) opolNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))

local instance (priority := high) opolNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

variable {n : ℕ}

theorem generator_anticomm (i j : Fin n) (h : i ≠ j) :
    generator i * generator j = -(generator j * generator i) :=
  OddMath.PbwL1.rel_anticommute i j h

/-- Induction over the ring generated by the `x_i`, which is all of `OPol_n`. -/
theorem induction_generator {P : SkewPolynomial n → Prop} (hgen : ∀ j, P (generator j))
    (h0 : P 0) (h1 : P 1) (hadd : ∀ f g, P f → P g → P (f + g)) (hneg : ∀ f, P f → P (-f))
    (hmul : ∀ f g, P f → P g → P (f * g)) (f : SkewPolynomial n) : P f := by
  have hf : f ∈ Subring.closure (Set.range (generator : Fin n → SkewPolynomial n)) := by
    rw [EKLSectionTwo.closure_generators]; trivial
  induction hf using Subring.closure_induction with
  | mem x hx => obtain ⟨j, rfl⟩ := hx; exact hgen j
  | zero => exact h0
  | one => exact h1
  | add x y _ _ hx hy => exact hadd x y hx hy
  | neg x _ hx => exact hneg x hx
  | mul x y _ _ hx hy => exact hmul x y hx hy

/-- Two additive maps satisfying the same twisted Leibniz rule `D(fg) = D(f) g + σ(f) D(g)` and
agreeing on the generators agree. -/
theorem twistedDeriv_ext (σ : SkewPolynomial n →+* SkewPolynomial n)
    {D E : SkewPolynomial n →+ SkewPolynomial n}
    (hD : ∀ f g, D (f * g) = D f * g + σ f * D g) (hE : ∀ f g, E (f * g) = E f * g + σ f * E g)
    (h : ∀ j, D (generator j) = E (generator j)) (f : SkewPolynomial n) : D f = E f := by
  induction f using induction_generator with
  | hgen j => exact h j
  | h0 => simp
  | h1 => rw [D_one σ D hD, D_one σ E hE]
  | hadd f g hf hg => rw [map_add, map_add, hf, hg]
  | hneg f hf => rw [map_neg, map_neg, hf]
  | hmul f g hf hg => rw [hD, hE, hf, hg]

/-! ## The universal property -/

section Lift

variable {R : Type*} [Ring R]

theorem lift_kills (y : Fin n → R) (hy : ∀ i j, i ≠ j → y i * y j + y j * y i = 0)
    (w : FreeAlgebra ℤ (Fin n)) (hw : w ∈ relIdeal n) :
    (FreeAlgebra.lift ℤ y).toRingHom w = 0 := by
  rw [OddMath.PbwL2.relIdeal, OddMath.PbwL2.relTwoSided, TwoSidedIdeal.mem_asIdeal] at hw
  induction hw using TwoSidedIdeal.span_induction with
  | mem x h =>
      obtain ⟨i, j, hij, rfl⟩ := h
      simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, map_add, map_mul,
        FreeAlgebra.lift_ι_apply]
      exact hy i j hij
  | zero => exact map_zero _
  | add x y hx hy ihx ihy => rw [map_add, ihx, ihy, add_zero]
  | neg x hx ih => rw [map_neg, ih, neg_zero]
  | left_absorb a x hx ih => rw [map_mul, ih, mul_zero]
  | right_absorb b x hx ih => rw [map_mul, ih, zero_mul]

/-- The ring map out of `OPol_n` sending `x_j` to `y_j`, for pairwise anticommuting `y_j`. -/
def skewLift (y : Fin n → R) (hy : ∀ i j, i ≠ j → y i * y j + y j * y i = 0) :
    SkewPolynomial n →+* R :=
  (Ideal.Quotient.lift (relIdeal n) (FreeAlgebra.lift ℤ y).toRingHom (lift_kills y hy)).comp
    (PbwEquivalence.presentedEquiv n).symm.toRingHom

@[simp] theorem skewLift_generator (y : Fin n → R)
    (hy : ∀ i j, i ≠ j → y i * y j + y j * y i = 0) (j : Fin n) :
    skewLift y hy (generator j) = y j := by
  have h : (PbwEquivalence.presentedEquiv n).symm (generator j) = q n j := by
    rw [RingEquiv.symm_apply_eq]
    exact (OddMath.PbwL3.Phi_q n j).symm
  change Ideal.Quotient.lift (relIdeal n) (FreeAlgebra.lift ℤ y).toRingHom (lift_kills y hy)
    ((PbwEquivalence.presentedEquiv n).symm (generator j)) = y j
  rw [h, q, Ideal.Quotient.lift_mk]
  exact FreeAlgebra.lift_ι_apply y j

end Lift

theorem ringHom_ext {R : Type*} [Ring R] {f g : SkewPolynomial n →+* R}
    (h : ∀ j, f (generator j) = g (generator j)) : f = g :=
  SignedPermutation.skewHom_ext h

/-- Signed images of distinct generators anticommute. -/
theorem smul_generator_anticomm (c : Fin n → ℤ) (σ : Equiv.Perm (Fin n)) (i j : Fin n)
    (h : i ≠ j) :
    (c i • generator (σ i)) * (c j • generator (σ j)) +
      (c j • generator (σ j)) * (c i • generator (σ i)) = 0 := by
  simp only [smul_mul_assoc, mul_smul_comm, smul_smul]
  rw [generator_anticomm _ _ (σ.injective.ne h), mul_comm (c j), smul_neg, neg_add_cancel]

/-! ## The involutions `ι`, `θ`, `w₀` -/

/-- The parity involution `ι(x_i) = -x_i`. -/
def parityInv (n : ℕ) : SkewPolynomial n →+* SkewPolynomial n :=
  skewLift (fun j => (-1 : ℤ) • generator (Equiv.refl _ j))
    (fun i j h => smul_generator_anticomm (fun _ => -1) (Equiv.refl _) i j h)

@[simp] theorem parityInv_generator (j : Fin n) : parityInv n (generator j) = -generator j := by
  simp [parityInv]

theorem parityInv_parityInv (f : SkewPolynomial n) : parityInv n (parityInv n f) = f := by
  have h : (parityInv n).comp (parityInv n) = RingHom.id _ :=
    ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

/-- The twisting `θ(x_i) = (-1)^i x_i` of Ellis–Qi (2.35) (strands numbered from `0`). -/
def theta (n : ℕ) : SkewPolynomial n →+* SkewPolynomial n :=
  skewLift (fun j => (-1 : ℤ) ^ j.val • generator (Equiv.refl _ j))
    (fun i j h => smul_generator_anticomm (fun j => (-1 : ℤ) ^ j.val) (Equiv.refl _) i j h)

@[simp] theorem theta_generator (j : Fin n) :
    theta n (generator j) = (-1 : ℤ) ^ j.val • generator j := by
  simp [theta]

/-- The longest element `w₀(x_i) = x_{n-1-i}`, acting by permuting indices (the plain
permutation action of Ellis–Qi §2.3, not EKL's signed action). -/
def longestPerm (n : ℕ) : SkewPolynomial n →+* SkewPolynomial n :=
  skewLift (fun j => (1 : ℤ) • generator (Fin.revPerm j))
    (fun i j h => smul_generator_anticomm (fun _ => 1) Fin.revPerm i j h)

@[simp] theorem longestPerm_generator (j : Fin n) :
    longestPerm n (generator j) = generator j.rev := by
  simp [longestPerm]

/-- `φ = θ ∘ w₀`, the map in the right action `1_z f = (θ ∘ w₀)(f) 1_z` of Ellis–Qi (3.24). -/
def twistRev (n : ℕ) : SkewPolynomial n →+* SkewPolynomial n := (theta n).comp (longestPerm n)

@[simp] theorem twistRev_generator (j : Fin n) :
    twistRev n (generator j) = (-1 : ℤ) ^ j.rev.val • generator j.rev := by
  simp [twistRev]

theorem parityInv_comm_twistRev (f : SkewPolynomial n) :
    parityInv n (twistRev n f) = twistRev n (parityInv n f) := by
  have h : (parityInv n).comp (twistRev n) = (twistRev n).comp (parityInv n) :=
    ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

/-! ## The differential -/

/-- The image of `x_j` in `2 × 2` matrices encoding `(ι, d)`: `[[ι x, d x], [0, x]]`. -/
def dMat (j : Fin n) : Matrix (Fin 2) (Fin 2) (SkewPolynomial n) :=
  !![-generator j, generator j * generator j; 0, generator j]

theorem dMat_anticomm (i j : Fin n) (h : i ≠ j) : dMat i * dMat j + dMat j * dMat i = 0 := by
  have hab := generator_anticomm i j h
  have hsum : generator i * generator j + generator j * generator i = 0 :=
    OddMath.PbwL1.rel_sum i j h
  have h1 : generator i * (generator j * generator j) = generator j * generator j * generator i := by
    rw [← mul_assoc, hab, neg_mul, mul_assoc, hab, mul_neg, neg_neg, ← mul_assoc]
  have h2 : generator j * (generator i * generator i) = generator i * generator i * generator j := by
    have hba := generator_anticomm j i (Ne.symm h)
    rw [← mul_assoc, hba, neg_mul, mul_assoc, hba, mul_neg, neg_neg, ← mul_assoc]
  refine Matrix.ext fun r s => ?_
  fin_cases r <;> fin_cases s
  · simp [dMat, hsum]
  · simp only [dMat, Matrix.mul_apply, Fin.sum_univ_two, Matrix.add_apply, Matrix.zero_apply]
    simp [h1, h2]
  · simp [dMat]
  · simp [dMat, hsum]

/-- The ring map `f ↦ [[ι f, d f], [0, f]]`. -/
def dHom (n : ℕ) : SkewPolynomial n →+* Matrix (Fin 2) (Fin 2) (SkewPolynomial n) :=
  skewLift dMat dMat_anticomm

/-- The local differential of Ellis–Qi §3.1 on `OPol_n`. -/
def d (n : ℕ) : SkewPolynomial n →+ SkewPolynomial n :=
  (Matrix.entryAddMonoidHom (SkewPolynomial n) 0 1).comp (dHom n).toAddMonoidHom

theorem d_apply (f : SkewPolynomial n) : d n f = dHom n f 0 1 := rfl

theorem dHom_eq (f : SkewPolynomial n) : dHom n f = !![parityInv n f, d n f; 0, f] := by
  have key : dHom n f 1 0 = 0 ∧ dHom n f 1 1 = f ∧ dHom n f 0 0 = parityInv n f := by
    induction f using induction_generator with
    | hgen j => simp [dHom, dMat]
    | h0 => simp
    | h1 => simp
    | hadd f g hf hg => simp [hf.1, hg.1, hf.2.1, hg.2.1, hf.2.2, hg.2.2]
    | hneg f hf => simp [hf.1, hf.2.1, hf.2.2]
    | hmul f g hf hg =>
      simp [Matrix.mul_apply, Fin.sum_univ_two, hf.1, hg.1, hf.2.1, hg.2.1, hf.2.2, hg.2.2]
  refine Matrix.ext fun r s => ?_
  fin_cases r <;> fin_cases s <;> simp [key.1, key.2.1, key.2.2, d_apply]

/-- The super Leibniz rule `d(fg) = d(f) g + ι(f) d(g)` (Ellis–Qi (2.3)). -/
theorem d_mul (f g : SkewPolynomial n) :
    d n (f * g) = d n f * g + parityInv n f * d n g := by
  have h := congrFun (congrFun (map_mul (dHom n) f g) 0) 1
  rw [dHom_eq, dHom_eq, dHom_eq] at h
  simpa [Matrix.mul_apply, Fin.sum_univ_two, add_comm] using h

@[simp] theorem d_generator (j : Fin n) : d n (generator j) = generator j * generator j := by
  simp [d_apply, dHom, dMat]

@[simp] theorem d_one : d n 1 = 0 := by simp [d_apply]

theorem d_parityInv (f : SkewPolynomial n) : d n (parityInv n f) = -parityInv n (d n f) := by
  induction f using induction_generator with
  | hgen j => simp
  | h0 => simp
  | h1 => simp
  | hadd f g hf hg => simp [hf, hg, add_comm]
  | hneg f hf => simp [hf]
  | hmul f g hf hg => simp [d_mul, hf, hg, parityInv_parityInv, add_comm]

/-- `d² = 0`. -/
theorem d_d (f : SkewPolynomial n) : d n (d n f) = 0 := by
  induction f using induction_generator with
  | hgen j =>
    rw [d_generator, d_mul, d_generator, parityInv_generator, neg_mul, mul_assoc, add_neg_cancel]
  | h0 => simp
  | h1 => simp
  | hadd f g hf hg => simp [hf, hg]
  | hneg f hf => simp [hf]
  | hmul f g hf hg =>
    rw [d_mul, map_add, d_mul, d_mul, hf, hg, d_parityInv]
    simp only [zero_mul, mul_zero, add_zero, zero_add, neg_mul, add_neg_cancel]

/-! ## Lemma 3.2 -/

/-- The untwisted odd elementary polynomial `e_k = Σ_{i_1<⋯<i_k} x_{i_1}⋯x_{i_k}` of
Ellis–Qi §2.3. -/
def elementary (n k : ℕ) : SkewPolynomial n := FiniteWords.strictSum (generator (n := n)) k

theorem parityInv_elementary (k : ℕ) :
    parityInv n (elementary n k) = (-1 : ℤ) ^ k • elementary n k :=
  iota_strictSum (parityInv n) _ (fun i => parityInv_generator i) k

/-- **Ellis–Qi, Lemma 3.2**: `d(e_k) = e_1 e_k - {k+1} e_{k+1}`, `{m} = m mod 2`
(with `e_{n+1} = 0`). -/
theorem d_elementary (k : ℕ) :
    d n (elementary n k) =
      elementary n 1 * elementary n k - (((k + 1) % 2 : ℕ) : ℤ) • elementary n (k + 1) :=
  D_strictSum (parityInv n) (d n) d_mul (generator (n := n)) generator_anticomm
    (fun i => parityInv_generator i) (fun i => d_generator i) k

/-- The untwisted odd symmetric polynomials `OΛ_n ⊆ OPol_n`, generated by the `e_k`. -/
def osym (n : ℕ) : Subring (SkewPolynomial n) :=
  Subring.closure (Set.range (elementary n))

theorem parityInv_mem_osym {f : SkewPolynomial n} (hf : f ∈ osym n) : parityInv n f ∈ osym n := by
  induction hf using Subring.closure_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    rw [parityInv_elementary]
    exact Subring.zsmul_mem _ (Subring.subset_closure (Set.mem_range_self k)) _
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

/-- **Ellis–Qi, Lemma 3.2** (second part): `d` restricts to `OΛ_n`, so `OΛ_n ⊆ OPol_n` is an
inclusion of dg algebras. -/
theorem d_mem_osym {f : SkewPolynomial n} (hf : f ∈ osym n) : d n f ∈ osym n := by
  have hmem : ∀ k, elementary n k ∈ osym n := fun k => Subring.subset_closure ⟨k, rfl⟩
  induction hf using Subring.closure_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    rw [d_elementary]
    exact sub_mem (mul_mem (hmem 1) (hmem k)) (Subring.zsmul_mem _ (hmem _) _)
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx
  | mul x y hx' hy' hx hy =>
    rw [d_mul]
    exact add_mem (mul_mem hx hy') (mul_mem (parityInv_mem_osym hx') hy)

/-! ## Proposition 3.1 -/

/-- `s_α = Σ α_i x_i`. -/
def sAlpha (α : Fin n → ℤ) : SkewPolynomial n := ∑ i, α i • generator i

/-- The differential of `OPol_n(α)`, `d_α(f 1_α) = (d f + ι(f) s_α) 1_α` (Ellis–Qi (3.3)),
on the underlying `OPol_n`. -/
def dAlpha (α : Fin n → ℤ) : SkewPolynomial n →+ SkewPolynomial n :=
  d n + (AddMonoidHom.mulRight (sAlpha α)).comp (parityInv n).toAddMonoidHom

theorem dAlpha_apply (α : Fin n → ℤ) (f : SkewPolynomial n) :
    dAlpha α f = d n f + parityInv n f * sAlpha α := rfl

/-- The left Leibniz rule `d_α(g · f 1_α) = d(g) f 1_α + ι(g) d_α(f 1_α)`. -/
theorem dAlpha_mul (α : Fin n → ℤ) (g f : SkewPolynomial n) :
    dAlpha α (g * f) = d n g * f + parityInv n g * dAlpha α f := by
  simp only [dAlpha_apply, d_mul, map_mul, mul_add, mul_assoc, add_assoc]

theorem parityInv_sAlpha (α : Fin n → ℤ) : parityInv n (sAlpha α) = -sAlpha α := by
  simp [sAlpha, map_sum, Finset.sum_neg_distrib]

theorem sAlpha_mul_sAlpha (α : Fin n → ℤ) :
    sAlpha α * sAlpha α = ∑ i, (α i * α i) • (generator i * generator i) := by
  classical
  rw [sAlpha, Finset.sum_mul_sum]
  simp only [smul_mul_smul_comm]
  rw [← Finset.sum_product']
  have hsplit := Finset.sum_filter_add_sum_filter_not (Finset.univ ×ˢ Finset.univ)
    (fun p : Fin n × Fin n => p.1 = p.2)
    (fun p => (α p.1 * α p.2) • (generator p.1 * generator p.2))
  rw [← hsplit]
  have hdiag : ∑ p ∈ (Finset.univ ×ˢ Finset.univ).filter (fun p : Fin n × Fin n => p.1 = p.2),
      (α p.1 * α p.2) • (generator p.1 * generator p.2) =
        ∑ i, (α i * α i) • (generator i * generator i) := by
    rw [Finset.sum_filter, Finset.sum_product]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.sum_ite_eq]
    simp
  have hoff : ∑ p ∈ (Finset.univ ×ˢ Finset.univ).filter (fun p : Fin n × Fin n => ¬p.1 = p.2),
      (α p.1 * α p.2) • (generator p.1 * generator p.2) = 0 := by
    refine Finset.sum_involution (fun p _ => (p.2, p.1)) ?_ ?_ ?_ ?_
    · intro p hp
      simp only [Finset.mem_filter] at hp
      rw [generator_anticomm _ _ hp.2, mul_comm (α p.1), smul_neg, neg_add_cancel]
    · intro p hp _ h
      simp only [Finset.mem_filter] at hp
      exact hp.2 (Prod.ext_iff.mp h).1.symm
    · intro p hp
      simp only [Finset.mem_filter, Finset.mem_product, Finset.mem_univ, true_and] at hp ⊢
      exact fun h => hp h.symm
    · intro p _
      rfl
  rw [hdiag, hoff, add_zero]

theorem d_sAlpha (α : Fin n → ℤ) :
    d n (sAlpha α) = ∑ i, α i • (generator i * generator i) := by
  simp only [sAlpha, map_sum, map_zsmul, d_generator]

/-- `d_α² (f 1_α) = f · Σ (α_i - α_i²) x_i² 1_α` (Ellis–Qi, before Proposition 3.1). -/
theorem dAlpha_dAlpha (α : Fin n → ℤ) (f : SkewPolynomial n) :
    dAlpha α (dAlpha α f) = f * ∑ i, (α i - α i * α i) • (generator i * generator i) := by
  rw [dAlpha_apply, dAlpha_apply, map_add, map_add, d_d, d_mul, d_parityInv, parityInv_parityInv,
    map_mul, parityInv_parityInv, parityInv_sAlpha, d_sAlpha]
  have hss := sAlpha_mul_sAlpha α
  simp only [sub_smul, Finset.sum_sub_distrib, mul_sub, add_mul, neg_mul, mul_neg, mul_assoc,
    ← hss]
  abel

/-- A combination of the squares `x_i²` vanishes only if all coefficients vanish. -/
theorem sum_smul_square_eq_zero {c : Fin n → ℤ}
    (h : ∑ i, c i • (generator i * generator i) = 0) (i : Fin n) : c i = 0 := by
  classical
  have hsq : ∀ j : Fin n, generator j * generator j =
      Finsupp.single (OddMath.SkewPolynomial.expSingle j + OddMath.SkewPolynomial.expSingle j) 1 :=
    fun j => OddMath.SkewPolynomial.generator_square j
  have hinj : ∀ j : Fin n, (OddMath.SkewPolynomial.expSingle j +
      OddMath.SkewPolynomial.expSingle j = OddMath.SkewPolynomial.expSingle i +
      OddMath.SkewPolynomial.expSingle i) ↔ j = i := by
    intro j
    constructor
    · intro hji
      have := congrFun hji j
      by_contra hne
      simp [OddMath.SkewPolynomial.expSingle, Ne.symm hne] at this
    · rintro rfl; rfl
  have hc := congrArg (fun p : SkewPolynomial n =>
    p (OddMath.SkewPolynomial.expSingle i + OddMath.SkewPolynomial.expSingle i)) h
  simp only [hsq, Finsupp.finsetSum_apply, Finsupp.smul_apply, Finsupp.single_apply, hinj,
    smul_eq_mul, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq',
    Finset.mem_univ, ite_true, Finsupp.coe_zero, Pi.zero_apply] at hc
  exact hc

/-- **Ellis–Qi, Proposition 3.1** (left modules): `d_α² = 0` on `OPol_n(α)` iff
`α ∈ {0,1}ⁿ`. -/
theorem prop_3_1_left (α : Fin n → ℤ) :
    (∀ f, dAlpha α (dAlpha α f) = 0) ↔ ∀ i, α i = 0 ∨ α i = 1 := by
  constructor
  · intro h i
    have h1 := h 1
    rw [dAlpha_dAlpha, one_mul] at h1
    have := sum_smul_square_eq_zero h1 i
    have : α i * (1 - α i) = 0 := by linarith
    rcases mul_eq_zero.mp this with h0 | h0
    · exact Or.inl h0
    · exact Or.inr (by linarith)
  · intro h f
    rw [dAlpha_dAlpha]
    have : ∀ i, α i - α i * α i = 0 := fun i => by rcases h i with h | h <;> simp [h]
    simp [this]

/-- The differential of the rank-one free right module `1_α OPol_n` with generator of parity `p`,
`d(1_α f) = 1_α (s_α f + (-1)^p d f)`, on the underlying `OPol_n`. -/
def dAlphaRight (α : Fin n → ℤ) (p : ℕ) : SkewPolynomial n →+ SkewPolynomial n :=
  AddMonoidHom.mulLeft (sAlpha α) + (-1 : ℤ) ^ p • d n

theorem dAlphaRight_apply (α : Fin n → ℤ) (p : ℕ) (f : SkewPolynomial n) :
    dAlphaRight α p f = sAlpha α * f + (-1 : ℤ) ^ p • d n f := rfl

/-- The right Leibniz rule `d(1_α f · g) = d(1_α f) g + (-1)^{p + |f|} 1_α f d(g)`, with the
parity of `1_α f` recorded by `ι`. -/
theorem dAlphaRight_mul (α : Fin n → ℤ) (p : ℕ) (f g : SkewPolynomial n) :
    dAlphaRight α p (f * g) =
      dAlphaRight α p f * g + (-1 : ℤ) ^ p • (parityInv n f * d n g) := by
  simp only [dAlphaRight_apply, d_mul, add_mul, smul_mul_assoc, mul_assoc, smul_add, add_assoc]

/-- **Ellis–Qi, Proposition 3.1** (right modules): `d² = 0` on `1_α OPol_n` (generator of parity
`p`) iff `α_i ∈ {0, (-1)^{p+1}}` for all `i`. -/
theorem prop_3_1_right (α : Fin n → ℤ) (p : ℕ) :
    (∀ f, dAlphaRight α p (dAlphaRight α p f) = 0) ↔
      ∀ i, α i = 0 ∨ α i = (-1 : ℤ) ^ (p + 1) := by
  have e1 : ∑ i, (α i * α i + (-1 : ℤ) ^ p * α i) • (generator i * generator i) =
      sAlpha α * sAlpha α + (-1 : ℤ) ^ p • d n (sAlpha α) := by
    rw [d_sAlpha, sAlpha_mul_sAlpha, Finset.smul_sum]
    simp only [add_smul, mul_smul, Finset.sum_add_distrib]
  have hsq : ∀ f, dAlphaRight α p (dAlphaRight α p f) =
      (∑ i, (α i * α i + (-1 : ℤ) ^ p * α i) • (generator i * generator i)) * f := by
    intro f
    rw [e1, dAlphaRight_apply, dAlphaRight_apply, map_add, map_zsmul, d_mul, d_d, smul_zero,
      add_zero, parityInv_sAlpha]
    simp only [mul_add, add_mul, smul_add, mul_smul_comm, smul_mul_assoc, neg_mul, smul_neg,
      mul_assoc]
    abel
  constructor
  · intro h i
    have h1 := h 1
    rw [hsq, mul_one] at h1
    have := sum_smul_square_eq_zero h1 i
    have hs : ((-1 : ℤ) ^ p) * (-1) ^ p = 1 := by rw [← mul_pow]; norm_num
    have : α i * (α i + (-1 : ℤ) ^ p) = 0 := by linarith
    rcases mul_eq_zero.mp this with h0 | h0
    · exact Or.inl h0
    · exact Or.inr (by rw [pow_succ]; linarith)
  · intro h f
    rw [hsq]
    have : ∀ i, α i * α i + (-1 : ℤ) ^ p * α i = 0 := fun i => by
      rcases h i with h | h
      · simp [h]
      · rw [h, pow_succ]; ring
    simp [this]

/-! ## The bimodule `Z_n` (Proposition 3.7, Definition 3.8) -/

/-- `α = (0,1,0,1,…)`: `α_i = {i}` with strands numbered from `0` (Ellis–Qi's `{i-1}`). -/
def zAlpha (n : ℕ) : Fin n → ℤ := fun i => ((i.val % 2 : ℕ) : ℤ)

/-- `d(φ f) = φ(d f) + s φ(f) - ι(φ f) s` for `φ = θ ∘ w₀` and `s = Σ {i} x_i`, for every
`f ∈ OPol_n`. -/
theorem sAlpha_mul_generator_add (α : Fin n → ℤ) (r : Fin n) :
    sAlpha α * generator r + generator r * sAlpha α = (2 * α r) • (generator r * generator r) := by
  classical
  simp only [sAlpha, Finset.sum_mul, Finset.mul_sum, smul_mul_assoc, mul_smul_comm,
    ← Finset.sum_add_distrib]
  rw [Finset.sum_eq_single r]
  · rw [two_mul, add_smul]
  · intro i _ hi
    rw [generator_anticomm _ _ hi, smul_neg, neg_add_cancel]
  · simp

theorem twisted_leibniz_aux {R : Type*} [Ring R] (F G dF dG pF pG s ιF ιG : R)
    (hF : dF = pF + s * F - ιF * s) (hG : dG = pG + s * G - ιG * s) :
    dF * G + ιF * dG = pF * G + ιF * pG + s * (F * G) - ιF * ιG * s := by
  subst hF hG
  simp only [add_mul, sub_mul, mul_add, mul_sub, mul_assoc]
  abel

theorem d_twistRev (f : SkewPolynomial n) :
    d n (twistRev n f) = twistRev n (d n f) + sAlpha (zAlpha n) * twistRev n f -
      parityInv n (twistRev n f) * sAlpha (zAlpha n) := by
  induction f using induction_generator with
  | hgen j =>
    have hs := eq_sub_of_add_eq (sAlpha_mul_generator_add (zAlpha n) j.rev)
    have hc : ((-1 : ℤ) ^ j.rev.val) =
        (-1 : ℤ) ^ j.rev.val * (-1) ^ j.rev.val + (-1) ^ j.rev.val * (2 * zAlpha n j.rev) := by
      simp only [zAlpha]
      rcases Nat.even_or_odd j.rev.val with he | ho
      · rw [Nat.even_iff.mp he, he.neg_one_pow]; norm_num
      · rw [Nat.odd_iff.mp ho, ho.neg_one_pow]; norm_num
    rw [twistRev_generator, map_zsmul, d_generator, d_generator, map_mul, twistRev_generator,
      map_zsmul, parityInv_generator, smul_mul_smul_comm, mul_smul_comm, hs, smul_neg, neg_mul,
      smul_mul_assoc]
    set Y := generator j.rev * generator j.rev
    set Z := generator j.rev * sAlpha (zAlpha n)
    rw [smul_sub, smul_smul]
    conv_lhs => rw [hc]
    rw [add_smul]
    abel
  | h0 => simp
  | h1 => simp
  | hadd f g hf hg =>
    rw [map_add, map_add, hf, hg, map_add, map_add, map_add]
    simp only [mul_add, add_mul]
    abel
  | hneg f hf =>
    rw [map_neg, map_neg, hf, map_neg, map_neg, map_neg]
    simp only [mul_neg, neg_mul]
    abel
  | hmul f g hf hg =>
    rw [map_mul, d_mul, d_mul, map_add, map_mul, map_mul, ← parityInv_comm_twistRev, map_mul]
    exact twisted_leibniz_aux _ _ _ _ _ _ _ _ _ hf hg

/-- **Ellis–Qi, Proposition 3.7 / Definition 3.8**: on `Z_n = OPol_n(0,1,0,1,…)` with the right
action `g 1_z · f = g (θ ∘ w₀)(f) 1_z`, the differential satisfies the right Leibniz rule
`d(g 1_z · f) = d(g 1_z) · f + ι(g) 1_z · d(f)` (the generator `1_z` is even), for all
`f ∈ OPol_n`, in particular for `f ∈ OΛ_n`. -/
theorem dAlpha_mul_twistRev (g f : SkewPolynomial n) :
    dAlpha (zAlpha n) (g * twistRev n f) =
      dAlpha (zAlpha n) g * twistRev n f + parityInv n g * twistRev n (d n f) := by
  rw [dAlpha_apply, dAlpha_apply, d_mul, d_twistRev, map_mul]
  simp only [add_mul, mul_add, mul_sub, mul_assoc]
  abel

end

end OddMath.Frontier.EQSkewDifferential
