import OddMath.Frontier.EQSchurDifferential
import OddMath.Frontier.LongestElementary

/-!
# The dg bimodule `Z_{a,b}`

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.3.1–§4.3.2 (equation before Lemma 4.4, Definition 4.6; printed numbering).

Strands are numbered from `0`. In `OPol_{a+b} = SkewPolynomial (a+b)` the first `a` variables are
`x = (x_0, …, x_{a-1})` (`inclX`) and the last `b` variables are `y = (x_a, …, x_{a+b-1})`
(`inclY`). Odd elementary polynomials are Ellis–Qi's untwisted ones (`elementary`).

* `osymAB a b` is `OΛ_a ⊠ OΛ_b ⊆ OPol_{a+b}`, the subring generated by the `e_k(x)` and the
  `e_k(y)`; `elementary_add` is the relation `e_k(x, y) = Σ_{i+j=k} e_i(x) e_j(y)` used in the
  proof of Lemma 4.4, so `OΛ_{a+b} ⊆ OΛ_a ⊠ OΛ_b` (`osym_le_osymAB`).

**The model of `Z_{a,b}`.** Ellis–Qi define `Z_{a,b} = (OΛ_a ⊗ OΛ_b) · z` with
`(f ⊗ g) · z = (θ(f) ⊗ θ(g)) z`, where `θ` twists each tensor factor in its own variables,
`d(z) = {a} ẽ_1(y) z` extended by the Leibniz rule, and right action `z · h = (θ ∘ w₀)(h) z`
for `h ∈ OΛ_{a+b}`. We use the free left module on `z` directly: the element `(f ⊗ g) · z` is
represented by `f(x) g(y) ∈ OΛ_a ⊠ OΛ_b`, so

* the differential is `dZ a b = d_α` for `α_i = {a}` on the `y`-variables and `0` on the
  `x`-variables (`alphaAB`): `dZ(F) = d(F) + ι(F) {a} e_1(y)` (`dZ_apply`, `sAlpha_alphaAB`);
  since `ẽ_1(y) z = e_1(y) · z`, this is `d(z) = {a} ẽ_1(y) z`;
* the right action of `h` is right multiplication by `φ(h)`, `φ = ε ∘ w₀` (`phiAB`), where
  `ε(x_i) = x_i` and `ε(y_j) = (-1)^a y_j` (`epsAB`): indeed `(θ_a ⊗ θ_b) ∘ ε = θ_{a+b}`
  (`tauAB_epsAB`), so `z · h = (θ_{a+b} ∘ w₀)(h) z = φ(h) · z`.

Results (all for every `a, b`, over `ℤ`):

* `dZ_dZ`: `d² = 0`; `dZ_mem`: `d` preserves `OΛ_a ⊠ OΛ_b`;
* `dZ_mul`: the left Leibniz rule `d(F · G) = d(F) G + ι(F) d(G)`;
* `phiAB_mem`: `φ(OΛ_{a+b}) ⊆ OΛ_a ⊠ OΛ_b`, so `Z_{a,b}` is a bimodule;
* `dZ_mul_phiAB` (the compatibility asserted in **Definition 4.6**): the right Leibniz rule
  `d(G · h) = d(G) · h + ι(G) · d(h)` (`z` is even), proved for every `h ∈ OPol_{a+b}`;
* **the literal twisted model** (`dT`, on `OΛ̃_a ⊠ OΛ̃_b = τ(OΛ_a ⊠ OΛ_b)`, `τ = θ_a ⊗ θ_b`,
  `tauAB`): `dT_one` (`d(z) = {a} ẽ_1(y) z` with `ẽ_1(y) = θ_b(e_1)(y)`), `dT_left`
  (`d((f ⊗ g) · G) = d(f ⊗ g) · G + ι(f ⊗ g) · d(G)` for the twisted left action), `dT_right`
  (`d(G (θ ∘ w₀)(h)) = d(G) (θ ∘ w₀)(h) + ι(G) (θ ∘ w₀)(d h)`) and `dT_dT`. These determine the
  differential of Definition 4.6 uniquely, so `dT` is Ellis–Qi's `d` and `tauAB` is an
  isomorphism of dg bimodules from our model.
-/

namespace OddMath.Frontier.EQZab

open OddMath.SkewPolynomial (SkewPolynomial generator monomial expSingle)
open EQSkewDifferential
open FiniteCompleteElementary
open scoped BigOperators

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) zabNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))

local instance (priority := high) zabNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

/-! ## Increasing words -/

section Generic

variable {R : Type*} [Ring R]

theorem ringHom_strictSum {S : Type*} [Ring S] (φ : R →+* S) :
    ∀ {m : ℕ} (x : Fin m → R) (k : ℕ),
      φ (FiniteWords.strictSum x k) = FiniteWords.strictSum (fun j => φ (x j)) k
  | 0, x, 0 => by simp
  | 0, x, k+1 => by simp
  | m+1, x, 0 => by simp
  | m+1, x, k+1 => by
      rw [FiniteWords.strictSum_succ, FiniteWords.strictSum_succ, map_add, map_mul,
        ringHom_strictSum φ _ k, ringHom_strictSum φ _ (k+1)]

theorem strictSum_zsmul (c : ℤ) :
    ∀ {m : ℕ} (x : Fin m → R) (k : ℕ),
      FiniteWords.strictSum (fun j => c • x j) k = c ^ k • FiniteWords.strictSum x k
  | 0, x, 0 => by simp
  | 0, x, k+1 => by simp
  | m+1, x, 0 => by simp
  | m+1, x, k+1 => by
      have h1 := strictSum_zsmul c (fun i => x i.succ) k
      have h2 := strictSum_zsmul c (fun i => x i.succ) (k+1)
      rw [FiniteWords.strictSum_succ, FiniteWords.strictSum_succ, h1, h2, smul_mul_smul_comm,
        ← pow_succ', smul_add]

theorem strictSum_cast {n m : ℕ} (h : n = m) (x : Fin m → R) (k : ℕ) :
    FiniteWords.strictSum (fun i => x (Fin.cast h i)) k = FiniteWords.strictSum x k := by
  subst h; rfl

/-- The coproduct formula for increasing words in a concatenated alphabet:
`e_k(u, v) = Σ_{i+j=k} e_i(u) e_j(v)`. No commutation is needed. -/
theorem strictSum_append : ∀ {a b : ℕ} (u : Fin a → R) (v : Fin b → R) (k : ℕ),
    FiniteWords.strictSum (Fin.append u v) k =
      ∑ p ∈ Finset.antidiagonal k, FiniteWords.strictSum u p.1 * FiniteWords.strictSum v p.2
  | 0, b, u, v, k => by
      rw [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk, Finset.sum_range_succ']
      rw [Finset.sum_eq_zero fun i _ => by rw [FiniteWords.strictSum_empty, zero_mul]]
      simp only [FiniteWords.strictSum_zero, one_mul, zero_add, Nat.sub_zero]
      have h : Fin.append u v = fun i => v (Fin.cast (Nat.zero_add b) i) := by
        funext i
        rw [Fin.append_left_nil u v (by rfl)]
        rfl
      rw [h, strictSum_cast]
  | a+1, b, u, v, 0 => by simp
  | a+1, b, u, v, k+1 => by
      have hu : u = Fin.cons (u 0) (Fin.tail u) := (Fin.cons_self_tail u).symm
      have happ : Fin.append u v = fun i =>
          (Fin.cons (u 0) (Fin.append (Fin.tail u) v) : Fin (a + b + 1) → R)
            (Fin.cast (Nat.succ_add a b) i) := by
        conv_lhs => rw [hu]
        rw [Fin.append_cons]
        rfl
      rw [happ, strictSum_cast, FiniteWords.strictSum_succ]
      simp only [Fin.cons_zero, Fin.cons_succ]
      have e1 : (fun i : Fin (a + b) => Fin.append (Fin.tail u) v i) =
          Fin.append (Fin.tail u) v := rfl
      have hsplit : ∀ i, FiniteWords.strictSum u (i+1) =
          u 0 * FiniteWords.strictSum (Fin.tail u) i +
            FiniteWords.strictSum (Fin.tail u) (i+1) := fun i => by
        rw [FiniteWords.strictSum_succ]; rfl
      rw [e1, strictSum_append (Fin.tail u) v k, strictSum_append (Fin.tail u) v (k+1),
        Finset.Nat.sum_antidiagonal_succ, Finset.Nat.sum_antidiagonal_succ]
      simp only [FiniteWords.strictSum_zero, one_mul]
      simp only [hsplit, add_mul, Finset.sum_add_distrib, Finset.mul_sum, mul_assoc]
      abel

theorem strictSum_one {n : ℕ} (x : Fin n → R) : FiniteWords.strictSum x 1 = ∑ i, x i := by
  classical
  rw [FiniteWords.strictSum_eq]
  rw [← (Equiv.funUnique (Fin 1) (Fin n)).symm.sum_comp]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [ite_eq_left_iff.mpr (fun h => absurd (Subsingleton.strictMono _) h)]
  simp [FiniteWords.word]

end Generic

/-! ## Maps out of `OPol` -/

theorem deriv_ext {n : ℕ} {R : Type*} [Ring R] (σ τ : SkewPolynomial n →+* R)
    {D E : SkewPolynomial n →+ R}
    (hD : ∀ f g, D (f * g) = D f * τ g + σ f * D g)
    (hE : ∀ f g, E (f * g) = E f * τ g + σ f * E g)
    (h : ∀ j, D (generator j) = E (generator j)) (f : SkewPolynomial n) : D f = E f := by
  have h1 : ∀ F : SkewPolynomial n →+ R, (∀ f g, F (f * g) = F f * τ g + σ f * F g) →
      F 1 = 0 := fun F hF => by
    have := hF 1 1
    rw [mul_one, τ.map_one, σ.map_one, mul_one, one_mul] at this
    exact left_eq_add.mp this
  induction f using induction_generator with
  | hgen j => exact h j
  | h0 => simp
  | h1 => rw [h1 D hD, h1 E hE]
  | hadd f g hf hg => rw [map_add, map_add, hf, hg]
  | hneg f hf => rw [map_neg, map_neg, hf]
  | hmul f g hf hg => rw [hD, hE, hf, hg]

theorem generator_anticomm_of_injective {m n : ℕ} (f : Fin m → Fin n)
    (hf : Function.Injective f) (i j : Fin m) (h : i ≠ j) :
    generator (f i) * generator (f j) + generator (f j) * generator (f i) = 0 :=
  OddMath.PbwL1.rel_sum (f i) (f j) (hf.ne h)

/-- The diagonal ring endomorphism `x_i ↦ c_i x_i`. -/
def diagHom (n : ℕ) (c : Fin n → ℤ) : SkewPolynomial n →+* SkewPolynomial n :=
  skewLift (fun j => c j • generator (Equiv.refl _ j))
    (fun i j h => smul_generator_anticomm c (Equiv.refl _) i j h)

@[simp] theorem diagHom_generator {n : ℕ} (c : Fin n → ℤ) (j : Fin n) :
    diagHom n c (generator j) = c j • generator j := by
  simp [diagHom]

theorem parityInv_diagHom {n : ℕ} (c : Fin n → ℤ) (f : SkewPolynomial n) :
    parityInv n (diagHom n c f) = diagHom n c (parityInv n f) := by
  have h : (parityInv n).comp (diagHom n c) = (diagHom n c).comp (parityInv n) :=
    ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

variable {a b : ℕ}

/-! ## The two blocks of variables -/

/-- `OPol_a → OPol_{a+b}`, `x_i ↦ x_i` (the variables `x`). -/
def inclX (a b : ℕ) : SkewPolynomial a →+* SkewPolynomial (a+b) :=
  skewLift (fun i => generator (Fin.castAdd b i))
    (generator_anticomm_of_injective _ (Fin.castAdd_injective a b))

/-- `OPol_b → OPol_{a+b}`, `x_j ↦ x_{a+j}` (the variables `y`). -/
def inclY (a b : ℕ) : SkewPolynomial b →+* SkewPolynomial (a+b) :=
  skewLift (fun j => generator (Fin.natAdd a j))
    (generator_anticomm_of_injective _ (Fin.natAdd_injective b a))

@[simp] theorem inclX_generator (i : Fin a) : inclX a b (generator i) = generator (Fin.castAdd b i) := by
  simp [inclX]

@[simp] theorem inclY_generator (j : Fin b) : inclY a b (generator j) = generator (Fin.natAdd a j) := by
  simp [inclY]

theorem parityInv_inclX (f : SkewPolynomial a) :
    parityInv (a+b) (inclX a b f) = inclX a b (parityInv a f) := by
  have h : (parityInv (a+b)).comp (inclX a b) = (inclX a b).comp (parityInv a) :=
    ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

theorem parityInv_inclY (f : SkewPolynomial b) :
    parityInv (a+b) (inclY a b f) = inclY a b (parityInv b f) := by
  have h : (parityInv (a+b)).comp (inclY a b) = (inclY a b).comp (parityInv b) :=
    ringHom_ext fun j => by simp
  exact RingHom.congr_fun h f

theorem d_inclX (f : SkewPolynomial a) : d (a+b) (inclX a b f) = inclX a b (d a f) := by
  let D : SkewPolynomial a →+ SkewPolynomial (a+b) := (d (a+b)).comp (inclX a b).toAddMonoidHom
  let E : SkewPolynomial a →+ SkewPolynomial (a+b) := (inclX a b).toAddMonoidHom.comp (d a)
  exact deriv_ext (D := D) (E := E) ((parityInv (a+b)).comp (inclX a b)) (inclX a b)
    (fun f g => by simp [D, d_mul])
    (fun f g => by simp [E, d_mul, parityInv_inclX])
    (fun j => by simp [D, E]) f

theorem d_inclY (f : SkewPolynomial b) : d (a+b) (inclY a b f) = inclY a b (d b f) := by
  let D : SkewPolynomial b →+ SkewPolynomial (a+b) := (d (a+b)).comp (inclY a b).toAddMonoidHom
  let E : SkewPolynomial b →+ SkewPolynomial (a+b) := (inclY a b).toAddMonoidHom.comp (d b)
  exact deriv_ext (D := D) (E := E) ((parityInv (a+b)).comp (inclY a b)) (inclY a b)
    (fun f g => by simp [D, d_mul])
    (fun f g => by simp [E, d_mul, parityInv_inclY])
    (fun j => by simp [D, E]) f

/-- `e_k(x) = inclX(e_k)`, `e_k(y) = inclY(e_k)`: the variables `x` and `y` of the
concatenated alphabet. -/
theorem generator_eq_append :
    (generator : Fin (a+b) → SkewPolynomial (a+b)) =
      Fin.append (fun i => inclX a b (generator i)) (fun j => inclY a b (generator j)) := by
  funext i
  refine Fin.addCases (fun i => ?_) (fun j => ?_) i
  · rw [Fin.append_left, inclX_generator]
  · rw [Fin.append_right, inclY_generator]

/-- The relation `e_k(x, y) = Σ_{i+j=k} e_i(x) e_j(y)` (Ellis–Qi, proof of Lemma 4.4). -/
theorem elementary_add (k : ℕ) :
    elementary (a+b) k =
      ∑ p ∈ Finset.antidiagonal k, inclX a b (elementary a p.1) * inclY a b (elementary b p.2) := by
  rw [elementary, generator_eq_append, strictSum_append]
  refine Finset.sum_congr rfl fun p _ => ?_
  rw [elementary, elementary, ringHom_strictSum, ringHom_strictSum]

/-! ## `OΛ_a ⊠ OΛ_b` -/

/-- `OΛ_a ⊠ OΛ_b ⊆ OPol_{a+b}`: the subring generated by `e_k(x)` and `e_k(y)`. -/
def osymAB (a b : ℕ) : Subring (SkewPolynomial (a+b)) :=
  Subring.closure (Set.range (fun k => inclX a b (elementary a k)) ∪
    Set.range (fun k => inclY a b (elementary b k)))

theorem inclX_mem {f : SkewPolynomial a} (hf : f ∈ osym a) : inclX a b f ∈ osymAB a b := by
  induction hf using Subring.closure_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    exact Subring.subset_closure (Or.inl ⟨k, rfl⟩)
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

theorem inclY_mem {f : SkewPolynomial b} (hf : f ∈ osym b) : inclY a b f ∈ osymAB a b := by
  induction hf using Subring.closure_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    exact Subring.subset_closure (Or.inr ⟨k, rfl⟩)
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

theorem elementary_mem (m k : ℕ) : elementary m k ∈ osym m := Subring.subset_closure ⟨k, rfl⟩

/-- `OΛ_{a+b} ⊆ OΛ_a ⊠ OΛ_b`. -/
theorem osym_le_osymAB : osym (a+b) ≤ osymAB a b := by
  refine Subring.closure_le.mpr ?_
  rintro _ ⟨k, rfl⟩
  rw [elementary_add]
  exact Subring.sum_mem _ fun p _ =>
    mul_mem (inclX_mem (elementary_mem a p.1)) (inclY_mem (elementary_mem b p.2))

/-- A property of `OΛ_a ⊠ OΛ_b` checked on generators and closed under the ring operations. -/
theorem osymAB_induction {P : SkewPolynomial (a+b) → Prop}
    (hx : ∀ k, P (inclX a b (elementary a k))) (hy : ∀ k, P (inclY a b (elementary b k)))
    (h0 : P 0) (h1 : P 1) (hadd : ∀ f g, P f → P g → P (f + g)) (hneg : ∀ f, P f → P (-f))
    (hmul : ∀ f g, P f → P g → P (f * g)) {f : SkewPolynomial (a+b)} (hf : f ∈ osymAB a b) :
    P f := by
  induction hf using Subring.closure_induction with
  | mem x hmem =>
    rcases hmem with ⟨k, rfl⟩ | ⟨k, rfl⟩
    · exact hx k
    · exact hy k
  | zero => exact h0
  | one => exact h1
  | add x y _ _ ihx ihy => exact hadd x y ihx ihy
  | neg x _ ihx => exact hneg x ihx
  | mul x y _ _ ihx ihy => exact hmul x y ihx ihy

theorem parityInv_mem {f : SkewPolynomial (a+b)} (hf : f ∈ osymAB a b) :
    parityInv (a+b) f ∈ osymAB a b := by
  refine osymAB_induction (P := fun f => parityInv (a+b) f ∈ osymAB a b) ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
  · intro k; rw [parityInv_inclX]; exact inclX_mem (parityInv_mem_osym (elementary_mem a k))
  · intro k; rw [parityInv_inclY]; exact inclY_mem (parityInv_mem_osym (elementary_mem b k))
  · simp
  · simp
  · intro f g hf hg; rw [map_add]; exact add_mem hf hg
  · intro f hf; rw [map_neg]; exact neg_mem hf
  · intro f g hf hg; rw [map_mul]; exact mul_mem hf hg

theorem d_mem {f : SkewPolynomial (a+b)} (hf : f ∈ osymAB a b) : d (a+b) f ∈ osymAB a b := by
  have key : f ∈ osymAB a b ∧ d (a+b) f ∈ osymAB a b := by
    refine osymAB_induction (P := fun f => f ∈ osymAB a b ∧ d (a+b) f ∈ osymAB a b)
      ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
    · intro k
      exact ⟨inclX_mem (elementary_mem a k),
        by rw [d_inclX]; exact inclX_mem (d_mem_osym (elementary_mem a k))⟩
    · intro k
      exact ⟨inclY_mem (elementary_mem b k),
        by rw [d_inclY]; exact inclY_mem (d_mem_osym (elementary_mem b k))⟩
    · simp
    · simp
    · intro f g hf hg; rw [map_add]; exact ⟨add_mem hf.1 hg.1, add_mem hf.2 hg.2⟩
    · intro f hf; rw [map_neg]; exact ⟨neg_mem hf.1, neg_mem hf.2⟩
    · intro f g hf hg
      rw [d_mul]
      exact ⟨mul_mem hf.1 hg.1,
        add_mem (mul_mem hf.2 hg.1) (mul_mem (parityInv_mem hf.1) hg.2)⟩
  exact key.2

/-! ## The differential of `Z_{a,b}` -/

/-- `{m} = m mod 2`. -/
abbrev par (m : ℕ) : ℤ := ((m % 2 : ℕ) : ℤ)

/-- `α_i = {a}` on the variables `y` (`i ≥ a`) and `0` on the variables `x`. -/
def alphaAB (a b : ℕ) : Fin (a+b) → ℤ := fun i => if a ≤ i.val then par a else 0

theorem alphaAB_castAdd (i : Fin a) : alphaAB a b (Fin.castAdd b i) = 0 := by
  simp [alphaAB, i.isLt]

theorem alphaAB_natAdd (j : Fin b) : alphaAB a b (Fin.natAdd a j) = par a := by
  simp [alphaAB]

/-- `s_α = {a} e_1(y)`. -/
theorem sAlpha_alphaAB : sAlpha (alphaAB a b) = par a • inclY a b (elementary b 1) := by
  rw [sAlpha, Fin.sum_univ_add, elementary, strictSum_one, map_sum, Finset.smul_sum]
  simp [alphaAB_castAdd, alphaAB_natAdd]

/-- The differential of `Z_{a,b}` (Ellis–Qi, Definition 4.6):
`d(F z) = (d F + ι(F) {a} e_1(y)) z`. -/
abbrev dZ (a b : ℕ) : SkewPolynomial (a+b) →+ SkewPolynomial (a+b) := dAlpha (alphaAB a b)

theorem dZ_apply (F : SkewPolynomial (a+b)) :
    dZ a b F = d (a+b) F + parityInv (a+b) F * (par a • inclY a b (elementary b 1)) := by
  rw [dAlpha_apply, sAlpha_alphaAB]

/-- `d(z) = {a} e_1(y) z`. -/
theorem dZ_one : dZ a b 1 = par a • inclY a b (elementary b 1) := by
  rw [dZ_apply, d_one, map_one, one_mul, zero_add]

/-- `d² = 0` on `Z_{a,b}`. -/
theorem dZ_dZ (F : SkewPolynomial (a+b)) : dZ a b (dZ a b F) = 0 := by
  refine (prop_3_1_left (alphaAB a b)).mpr (fun i => ?_) F
  unfold alphaAB par
  split_ifs
  · rcases Nat.mod_two_eq_zero_or_one a with h | h <;> simp [h]
  · exact Or.inl rfl

/-- The left Leibniz rule: `d(F · G z) = d(F) G z + ι(F) d(G z)`. -/
theorem dZ_mul (F G : SkewPolynomial (a+b)) :
    dZ a b (F * G) = d (a+b) F * G + parityInv (a+b) F * dZ a b G :=
  dAlpha_mul _ F G

theorem sAlpha_mem : sAlpha (alphaAB a b) ∈ osymAB a b := by
  rw [sAlpha_alphaAB]
  exact Subring.zsmul_mem _ (inclY_mem (elementary_mem b 1)) _

/-- `d` preserves `Z_{a,b} = OΛ_a ⊠ OΛ_b · z`. -/
theorem dZ_mem {F : SkewPolynomial (a+b)} (hF : F ∈ osymAB a b) : dZ a b F ∈ osymAB a b := by
  rw [dAlpha_apply]
  exact add_mem (d_mem hF) (mul_mem (parityInv_mem hF) sAlpha_mem)

/-! ## The right action -/

/-- `ε(x_i) = x_i`, `ε(y_j) = (-1)^a y_j`. -/
def epsCoeff (a b : ℕ) : Fin (a+b) → ℤ := fun i => if a ≤ i.val then (-1) ^ a else 1

/-- `ε = (θ_a ⊗ θ_b) ∘ θ_{a+b}`. -/
def epsAB (a b : ℕ) : SkewPolynomial (a+b) →+* SkewPolynomial (a+b) := diagHom (a+b) (epsCoeff a b)

/-- `φ = ε ∘ w₀`: in our model, `z · h = φ(h) z`. -/
def phiAB (a b : ℕ) : SkewPolynomial (a+b) →+* SkewPolynomial (a+b) :=
  (epsAB a b).comp (longestPerm (a+b))

theorem epsCoeff_identity (i : Fin (a+b)) :
    epsCoeff a b i = epsCoeff a b i * epsCoeff a b i + epsCoeff a b i * (2 * alphaAB a b i) := by
  unfold epsCoeff alphaAB par
  split_ifs
  · rcases Nat.even_or_odd a with h | h
    · rw [Nat.even_iff.mp h, h.neg_one_pow]; norm_num
    · rw [Nat.odd_iff.mp h, h.neg_one_pow]; norm_num
  · norm_num

/-- `d(ε f) = ε(d f) + s ε(f) - ι(ε f) s`, `s = {a} e_1(y)`. -/
theorem d_epsAB (f : SkewPolynomial (a+b)) :
    d (a+b) (epsAB a b f) = epsAB a b (d (a+b) f) + sAlpha (alphaAB a b) * epsAB a b f -
      parityInv (a+b) (epsAB a b f) * sAlpha (alphaAB a b) := by
  induction f using induction_generator with
  | hgen j =>
    have hs := eq_sub_of_add_eq (sAlpha_mul_generator_add (alphaAB a b) j)
    have hc := epsCoeff_identity (a := a) (b := b) j
    rw [epsAB, diagHom_generator, map_zsmul, d_generator, map_mul, diagHom_generator,
      map_zsmul, parityInv_generator, smul_mul_smul_comm, mul_smul_comm, hs, smul_neg, neg_mul,
      smul_mul_assoc]
    set Y := generator j * generator j
    set Z := generator j * sAlpha (alphaAB a b)
    rw [smul_sub, smul_smul]
    conv_lhs => rw [hc]
    rw [add_smul]
    abel
  | h0 => simp
  | h1 => simp
  | hadd f g hf hg =>
    rw [map_add, map_add, hf, hg, map_add, map_add, map_add]
    simp only [mul_add, add_mul]
    abel
  | hneg f hf =>
    rw [map_neg, map_neg, hf, map_neg, map_neg, map_neg]
    simp only [mul_neg, neg_mul]
    abel
  | hmul f g hf hg =>
    rw [map_mul, d_mul, d_mul, map_add, map_mul, map_mul, epsAB, ← parityInv_diagHom, map_mul]
    exact twisted_leibniz_aux _ _ _ _ _ _ _ _ _ hf hg

theorem d_longestPerm (f : SkewPolynomial (a+b)) :
    d (a+b) (longestPerm (a+b) f) = longestPerm (a+b) (d (a+b) f) := by
  let D : SkewPolynomial (a+b) →+ SkewPolynomial (a+b) :=
    (d (a+b)).comp (longestPerm (a+b)).toAddMonoidHom
  let E : SkewPolynomial (a+b) →+ SkewPolynomial (a+b) :=
    (longestPerm (a+b)).toAddMonoidHom.comp (d (a+b))
  exact deriv_ext (D := D) (E := E) ((parityInv (a+b)).comp (longestPerm (a+b)))
    (longestPerm (a+b))
    (fun f g => by simp [D, d_mul])
    (fun f g => by simp [E, d_mul, EQSchur.parityInv_longestPerm])
    (fun j => by simp [D, E]) f

/-- `d(φ f) = φ(d f) + s φ(f) - ι(φ f) s` for every `f ∈ OPol_{a+b}`. -/
theorem d_phiAB (f : SkewPolynomial (a+b)) :
    d (a+b) (phiAB a b f) = phiAB a b (d (a+b) f) + sAlpha (alphaAB a b) * phiAB a b f -
      parityInv (a+b) (phiAB a b f) * sAlpha (alphaAB a b) := by
  simp only [phiAB, RingHom.comp_apply]
  rw [d_epsAB, d_longestPerm]

/-- **Ellis–Qi, Definition 4.6** (compatibility of the right action with `d`): for the right action
`G z · h = G φ(h) z` (`= G (θ ∘ w₀)(h) z` in Ellis–Qi's twisted notation),
`d(G z · h) = d(G z) · h + ι(G) z · d(h)`, for every `h ∈ OPol_{a+b}`. -/
theorem dZ_mul_phiAB (G h : SkewPolynomial (a+b)) :
    dZ a b (G * phiAB a b h) =
      dZ a b G * phiAB a b h + parityInv (a+b) G * phiAB a b (d (a+b) h) := by
  rw [dAlpha_apply, dAlpha_apply, d_mul, d_phiAB, map_mul]
  simp only [add_mul, mul_add, mul_sub, mul_assoc]
  abel

theorem epsAB_inclX (f : SkewPolynomial a) : epsAB a b (inclX a b f) = inclX a b f := by
  have h : (epsAB a b).comp (inclX a b) = inclX a b := ringHom_ext fun j => by
    simp [epsAB, epsCoeff, j.isLt]
  exact RingHom.congr_fun h f

theorem epsAB_inclY_elementary (k : ℕ) :
    epsAB a b (inclY a b (elementary b k)) = ((-1 : ℤ) ^ a) ^ k • inclY a b (elementary b k) := by
  rw [elementary, ringHom_strictSum, ringHom_strictSum, ← strictSum_zsmul]
  congr 1
  funext j
  simp [epsAB, epsCoeff]

theorem epsAB_mem {f : SkewPolynomial (a+b)} (hf : f ∈ osymAB a b) : epsAB a b f ∈ osymAB a b := by
  refine osymAB_induction (P := fun f => epsAB a b f ∈ osymAB a b) ?_ ?_ ?_ ?_ ?_ ?_ ?_ hf
  · intro k; rw [epsAB_inclX]; exact inclX_mem (elementary_mem a k)
  · intro k; rw [epsAB_inclY_elementary]
    exact Subring.zsmul_mem _ (inclY_mem (elementary_mem b k)) _
  · simp
  · simp
  · intro f g hf hg; rw [map_add]; exact add_mem hf hg
  · intro f hf; rw [map_neg]; exact neg_mem hf
  · intro f g hf hg; rw [map_mul]; exact mul_mem hf hg

/-- `w₀(e_k) = ± e_k` for the plain permutation action. -/
theorem longestPerm_elementary_mem (N k : ℕ) : longestPerm N (elementary N k) ∈ osym N := by
  open PlacticEvaluation SignedPermutation LongestElementary in
  have hc : (fun j : Fin N => twistRev N (generator j)) = fun j =>
      (-1 : ℤ) ^ ((N-1).choose 2) • (skewAction (longest N)).toRingHom (tildeGenerator j) := by
    funext j
    change _ = _ • skewAction (longest N) (tildeGenerator j)
    rw [action_tilde, smul_smul, ← pow_add, ← two_mul, pow_mul,
      neg_one_sq, one_pow, one_smul, twistRev_generator]
    rfl
  open PlacticEvaluation SignedPermutation LongestElementary in
  have htw : twistRev N (elementary N k) =
      ((-1 : ℤ) ^ ((N-1).choose 2)) ^ k • skewAction (longest N) (elementaryPoly N k) := by
    rw [elementary, ringHom_strictSum, hc, strictSum_zsmul, ← ringHom_strictSum,
      ← elementaryPoly_eq_strictSum]
    rfl
  have hθ : theta N (elementaryPoly N k) = elementary N k := by
    rw [elementaryPoly_eq_strictSum, ringHom_strictSum, elementary]
    congr 1
    funext j
    simp only [PlacticEvaluation.tildeGenerator, map_zsmul, theta_generator, smul_smul]
    rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_smul]
  have hw : longestPerm N (elementary N k) = theta N (twistRev N (elementary N k)) := by
    rw [twistRev, RingHom.comp_apply, EQSchur.theta_theta]
  rw [hw, htw, LongestElementary.action_elementary, smul_smul, map_zsmul, hθ]
  exact Subring.zsmul_mem _ (elementary_mem N k) _

theorem longestPerm_mem_osym {N : ℕ} {f : SkewPolynomial N} (hf : f ∈ osym N) :
    longestPerm N f ∈ osym N := by
  induction hf using Subring.closure_induction with
  | mem x hx => obtain ⟨k, rfl⟩ := hx; exact longestPerm_elementary_mem N k
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

/-- The right action of `OΛ_{a+b}` preserves `Z_{a,b}`: `φ(OΛ_{a+b}) ⊆ OΛ_a ⊠ OΛ_b`. -/
theorem phiAB_mem {h : SkewPolynomial (a+b)} (hh : h ∈ osym (a+b)) : phiAB a b h ∈ osymAB a b :=
  epsAB_mem (osym_le_osymAB (longestPerm_mem_osym hh))

/-- The right action is a right action: `(G · h) · h' = G · (h h')`. -/
theorem phiAB_mul (h h' : SkewPolynomial (a+b)) : phiAB a b (h * h') = phiAB a b h * phiAB a b h' :=
  map_mul _ h h'

/-! ## The literal twisted model -/

/-- `θ_a ⊗ θ_b`: `x_i ↦ (-1)^i x_i`, `y_j ↦ (-1)^j y_j` (each block twisted in its own
variables). -/
def tauCoeff (a b : ℕ) : Fin (a+b) → ℤ := fun i => if a ≤ i.val then (-1) ^ (i.val - a) else (-1) ^ i.val

def tauAB (a b : ℕ) : SkewPolynomial (a+b) →+* SkewPolynomial (a+b) := diagHom (a+b) (tauCoeff a b)

theorem tauAB_inclX (f : SkewPolynomial a) : tauAB a b (inclX a b f) = inclX a b (theta a f) := by
  have h : (tauAB a b).comp (inclX a b) = (inclX a b).comp (theta a) := ringHom_ext fun j => by
    simp [tauAB, tauCoeff, j.isLt]
  exact RingHom.congr_fun h f

theorem tauAB_inclY (f : SkewPolynomial b) : tauAB a b (inclY a b f) = inclY a b (theta b f) := by
  have h : (tauAB a b).comp (inclY a b) = (inclY a b).comp (theta b) := ringHom_ext fun j => by
    simp [tauAB, tauCoeff]
  exact RingHom.congr_fun h f

theorem tauAB_tauAB (f : SkewPolynomial (a+b)) : tauAB a b (tauAB a b f) = f := by
  have h : (tauAB a b).comp (tauAB a b) = RingHom.id _ := ringHom_ext fun j => by
    simp only [tauAB, RingHom.comp_apply, diagHom_generator, map_zsmul, smul_smul,
      RingHom.id_apply]
    unfold tauCoeff
    split_ifs <;> rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_smul]
  exact RingHom.congr_fun h f

theorem tauAB_epsAB (f : SkewPolynomial (a+b)) : tauAB a b (epsAB a b f) = theta (a+b) f := by
  have h : (tauAB a b).comp (epsAB a b) = theta (a+b) := ringHom_ext fun j => by
    simp only [tauAB, epsAB, RingHom.comp_apply, diagHom_generator, map_zsmul, smul_smul,
      theta_generator]
    congr 1
    unfold tauCoeff epsCoeff
    split_ifs with hj
    · rw [← pow_add]; congr 1; omega
    · simp
  exact RingHom.congr_fun h f

theorem parityInv_tauAB (f : SkewPolynomial (a+b)) :
    parityInv (a+b) (tauAB a b f) = tauAB a b (parityInv (a+b) f) :=
  parityInv_diagHom _ f

/-- `τ(φ(h)) = (θ ∘ w₀)(h)`: our right action is Ellis–Qi's `z · h = (θ ∘ w₀)(h) z`. -/
theorem tauAB_phiAB (h : SkewPolynomial (a+b)) : tauAB a b (phiAB a b h) = twistRev (a+b) h := by
  rw [phiAB, RingHom.comp_apply, tauAB_epsAB]
  rfl

/-- `OΛ̃_a ⊠ OΛ̃_b = τ(OΛ_a ⊠ OΛ_b)`. -/
def tosymAB (a b : ℕ) : Subring (SkewPolynomial (a+b)) := (osymAB a b).map (tauAB a b)

/-- The differential of Definition 4.6 on the literal `OΛ̃_a ⊠ OΛ̃_b · z`. -/
def dT (a b : ℕ) : SkewPolynomial (a+b) →+ SkewPolynomial (a+b) :=
  (tauAB a b).toAddMonoidHom.comp ((dZ a b).comp (tauAB a b).toAddMonoidHom)

theorem dT_apply (G : SkewPolynomial (a+b)) : dT a b G = tauAB a b (dZ a b (tauAB a b G)) := rfl

/-- `ẽ_1(y) = θ_b(e_1)(y)`, the twisted `e_1` in the variables `y`. -/
def etY (a b : ℕ) : SkewPolynomial (a+b) := inclY a b (theta b (elementary b 1))

/-- **Definition 4.6**: `d(z) = {a} ẽ_1(y) z`. -/
theorem dT_one : dT a b 1 = par a • etY a b := by
  rw [dT_apply, map_one, dZ_one, map_zsmul, tauAB_inclY]
  rfl

/-- **Definition 4.6**, left Leibniz rule for the twisted left action
`(f ⊗ g) · G z = (θ(f) ⊗ θ(g)) G z` of `F = f(x) g(y) ∈ OΛ_a ⊗ OΛ_b`:
`d(F · G z) = d(F) · G z + ι(F) · d(G z)`. -/
theorem dT_left (F G : SkewPolynomial (a+b)) :
    dT a b (tauAB a b F * G) =
      tauAB a b (d (a+b) F) * G + tauAB a b (parityInv (a+b) F) * dT a b G := by
  rw [dT_apply, map_mul, tauAB_tauAB, dZ_mul, map_add, map_mul, map_mul, dT_apply, tauAB_tauAB]

/-- **Definition 4.6**, right Leibniz rule for `G z · h = G (θ ∘ w₀)(h) z`:
`d(G z · h) = d(G z) · h + ι(G) z · d(h)`, for every `h ∈ OPol_{a+b}`. -/
theorem dT_right (G h : SkewPolynomial (a+b)) :
    dT a b (G * twistRev (a+b) h) =
      dT a b G * twistRev (a+b) h + parityInv (a+b) G * twistRev (a+b) (d (a+b) h) := by
  rw [← tauAB_phiAB, ← tauAB_phiAB, dT_apply, map_mul, tauAB_tauAB, dZ_mul_phiAB, map_add,
    map_mul, map_mul, dT_apply, ← parityInv_tauAB, tauAB_tauAB]

theorem dT_dT (G : SkewPolynomial (a+b)) : dT a b (dT a b G) = 0 := by
  rw [dT_apply, dT_apply, tauAB_tauAB, dZ_dZ, map_zero]

end

end OddMath.Frontier.EQZab
