import OddMath.Frontier.EQBorelPresentation
import OddMath.Frontier.MonomialReversal

/-!
# Ellis–Qi, Proposition 4.13 (1) for any number of blocks

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§4.3.2, Proposition 4.13 (1) (see ERRATA [EQ] 11 for the printed basis).

Model. A composition `(a_1, …, a_r)` of `n` is a list written **last block first**,
`k :: a` being `a` followed by a block of size `k` (`blocksN`: the total size). The ring
`OΛ̃_{a_1} ⊠ ⋯ ⊠ OΛ̃_{a_r} ⊆ OPol_n` (`TB`) is the subring generated by the twisted odd
elementary polynomials of each block of variables; for two blocks it is `EQZab.tosymAB`
(`tosymAB_eq`). As in the two-block model of Corollary 4.8 (`EQZab.zab_span_twisted`), `OΛ̃_n ⊆ TB`
acts by right multiplication.

**Proposition 4.13 (1), corrected** (`prop_4_13_one_span`, `prop_4_13_one_indep`): the products
`s̃_{λ_1}(X_1) s̃_{λ_2}(X_2) ⋯ s̃_{λ_r}(X_r)` of twisted odd Schur polynomials in the blocks of
variables `X_i`, with `λ_i` in an `a_i × (a_1 + ⋯ + a_{i−1})` box (`Idx`, `Bas`; `λ_1 = ∅`), form a
basis of `OΛ̃_{a_1} ⊠ ⋯ ⊠ OΛ̃_{a_r}` as a free right `OΛ̃_n`-module; there are
`n! / (a_1! ⋯ a_r!)` of them (`card_Idx`). The proof is by induction on `r` from the two-block case: the
spanning step uses the supercommutation of disjoint blocks (`EQBorel.inclY_elementary_mul_inclX`),
the independence step the factorisation of monomials across two blocks
(`inclX_mul_inclY_monomial`, `eq_zero_of_sum_inclX_mul_inclY`).

Not covered here: Proposition 4.13 (2) (`d`-stability) and (3) (graded ranks of `HOM`) for three
or more blocks.
-/

namespace OddMath.Frontier.EQBlocks

open OddMath.SkewPolynomial (SkewPolynomial generator monomial)
open OddMath.Frontier.EQSkewDifferential (theta longestPerm elementary osym parityInv
  ringHom_ext twistRev)
open OddMath.Frontier.EQZab (osymAB tosymAB inclX inclY tauAB phiAB)
open OddMath.Frontier.SmallRank (OLam)
open OddMath.Frontier.EQBorel (sp_mul_assoc sp_zero_mul sp_mul_zero)
open FiniteCompleteElementary
open scoped BigOperators

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) eqBlocksNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))

local instance (priority := high) eqBlocksNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

local instance eqBlocksAssoc (n : ℕ) :
    Std.Associative (fun x y : SkewPolynomial n => x * y) := ⟨sp_mul_assoc⟩

variable {m k : ℕ}

/-! ## Monomials across two blocks -/

theorem inclX_mul_inclY_monomial (α : Fin m → ℕ) (γ : Fin k → ℕ) :
    inclX m k (monomial α 1) * inclY m k (monomial γ 1) = monomial (Fin.append α γ) 1 := by
  rw [MonomialReversal.monomial_eq_prod, MonomialReversal.monomial_eq_prod,
    MonomialReversal.monomial_eq_prod (Fin.append α γ), map_list_prod, map_list_prod,
    List.map_ofFn, List.map_ofFn, List.ofFn_add, List.prod_append]
  congr 2
  · congr 1; funext i
    show inclX m k (generator i ^ α i) = generator (Fin.castAdd k i) ^ Fin.append α γ (Fin.castAdd k i)
    rw [map_pow, EQZab.inclX_generator, Fin.append_left]
  · congr 1; funext i
    show inclY m k (generator i ^ γ i) = generator (Fin.natAdd m i) ^ Fin.append α γ (Fin.natAdd m i)
    rw [map_pow, EQZab.inclY_generator, Fin.append_right]

theorem append_eq_append_iff (α α' : Fin m → ℕ) (γ γ' : Fin k → ℕ) :
    Fin.append α γ = Fin.append α' γ' ↔ α = α' ∧ γ = γ' := by
  constructor
  · intro h
    refine ⟨funext fun i => ?_, funext fun i => ?_⟩
    · have := congrFun h (Fin.castAdd k i); simpa [Fin.append_left] using this
    · have := congrFun h (Fin.natAdd m i); simpa [Fin.append_right] using this
  · rintro ⟨rfl, rfl⟩; rfl

theorem inclX_mul_inclY_monomial_apply (P : SkewPolynomial m) (γ : Fin k → ℕ)
    (α' : Fin m → ℕ) (γ' : Fin k → ℕ) :
    (inclX m k P * inclY m k (monomial γ 1)) (Fin.append α' γ') =
      if γ' = γ then P α' else 0 := by
  classical
  induction P using Finsupp.induction_linear with
  | zero => rw [map_zero, sp_zero_mul]; simp
  | add P Q hP hQ =>
    rw [map_add, add_mul, Finsupp.add_apply, hP, hQ]
    split_ifs <;> simp
  | single α c =>
    rw [show Finsupp.single α c = c • monomial α 1 from (Finsupp.smul_single_one α c).symm,
      map_zsmul, smul_mul_assoc, inclX_mul_inclY_monomial, Finsupp.smul_apply]
    simp only [monomial, Finsupp.single_apply, append_eq_append_iff, smul_eq_mul]
    by_cases h1 : γ' = γ
    · subst h1; by_cases h2 : α = α' <;> simp [h2]
    · have h1' : ¬ γ = γ' := fun h => h1 h.symm
      simp [h1, h1']

/-- The factorisation `OPol_{m+k} = OPol_m ⊗ OPol_k` on monomials of the second block. -/
theorem eq_zero_of_sum_inclX_mul_inclY (s : Finset (Fin k → ℕ))
    (P : (Fin k → ℕ) → SkewPolynomial m)
    (h : ∑ γ ∈ s, inclX m k (P γ) * inclY m k (monomial γ 1) = 0) : ∀ γ ∈ s, P γ = 0 := by
  classical
  intro γ hγ
  ext α
  have := congrArg (fun F : SkewPolynomial (m+k) => F (Fin.append α γ)) h
  simp only [Finsupp.finsetSum_apply, inclX_mul_inclY_monomial_apply, Finsupp.coe_zero,
    Pi.zero_apply] at this
  rw [Finset.sum_ite_eq] at this
  simpa [hγ] using this

/-! ## Parity and the twist -/

theorem parityInv_theta (n : ℕ) (f : SkewPolynomial n) :
    parityInv n (theta n f) = theta n (parityInv n f) := by
  have h : (parityInv n).comp (theta n) = (theta n).comp (parityInv n) := ringHom_ext fun j => by
    simp [EQSkewDifferential.theta_generator, EQSkewDifferential.parityInv_generator]
  exact RingHom.congr_fun h f

theorem parityInv_mem_OLam {n : ℕ} {f : SkewPolynomial n} (hf : f ∈ OLam n) :
    parityInv n f ∈ OLam n := by
  have h := EQLima.theta_mem_OLam (EQSkewDifferential.parityInv_mem_osym
    (EQLima.theta_mem_osym_of_OLam hf))
  rwa [← parityInv_theta, EQSchur.theta_theta] at h

theorem iterate_parityInv_mem_OLam {n : ℕ} {f : SkewPolynomial n} (hf : f ∈ OLam n) (j : ℕ) :
    (parityInv n)^[j] f ∈ OLam n := by
  induction j with
  | zero => exact hf
  | succ j ih => rw [Function.iterate_succ_apply']; exact parityInv_mem_OLam ih

theorem parityInv_elementaryPoly (n j : ℕ) :
    parityInv n (elementaryPoly n j) = (-1 : ℤ) ^ j • elementaryPoly n j := by
  rw [← EQFix.theta_elementary, parityInv_theta, EQSkewDifferential.parityInv_elementary,
    map_zsmul]

/-- Supercommutation of the twisted elementary polynomials of the second block. -/
theorem inclY_elementaryPoly_mul_inclX (j : ℕ) (u : SkewPolynomial m) :
    inclY m k (elementaryPoly k j) * inclX m k u =
      inclX m k ((parityInv m)^[j] u) * inclY m k (elementaryPoly k j) := by
  rw [elementaryPoly_eq_strictSum, EQZn.ringHom_strictSum]
  refine EQBorel.strictSum_mul_inclX _ (fun i u => ?_) j u
  rw [PlacticEvaluation.tildeGenerator, map_zsmul, smul_mul_assoc,
    EQBorel.inclY_generator_mul_inclX, mul_smul_comm]

theorem elementaryPoly_mem_OLam (n j : ℕ) : elementaryPoly n j ∈ OLam n := by
  rw [← EQFix.theta_elementary]; exact EQLima.theta_mem_OLam (EQZab.elementary_mem n j)

/-! ## Two blocks: `OΛ̃_m ⊠ OΛ̃_k` -/

/-- `OΛ̃_m ⊠ OΛ̃_k` is generated by the twisted elementary polynomials of the two blocks. -/
theorem tosymAB_eq (m k : ℕ) :
    tosymAB m k = Subring.closure
      (Set.range (fun j => inclX m k (elementaryPoly m j)) ∪
        Set.range (fun j => inclY m k (elementaryPoly k j))) := by
  rw [EQZab.tosymAB, EQZab.osymAB, RingHom.map_closure, Set.image_union, ← Set.range_comp,
    ← Set.range_comp]
  congr 3
  · funext j
    simp only [Function.comp, EQZab.tauAB_inclX, EQFix.theta_elementary]
  · funext j
    simp only [Function.comp, EQZab.tauAB_inclY, EQFix.theta_elementary]

theorem inclY_elementaryPoly_mem (j : ℕ) : inclY m k (elementaryPoly k j) ∈ tosymAB m k := by
  rw [tosymAB_eq]; exact Subring.subset_closure (Or.inr ⟨j, rfl⟩)

theorem inclX_mem_tosymAB {f : SkewPolynomial m} (hf : f ∈ OLam m) : inclX m k f ∈ tosymAB m k := by
  rw [SmallRank.OLam_eq_elementaryClosure] at hf
  have : (Subring.closure {f | ∃ j, 1 ≤ j ∧ j ≤ m ∧ f = elementaryPoly m j}).map (inclX m k) ≤
      tosymAB m k := by
    rw [RingHom.map_closure, Subring.closure_le, tosymAB_eq]
    rintro _ ⟨f, ⟨j, -, -, rfl⟩, rfl⟩
    exact Subring.subset_closure (Or.inl ⟨j, rfl⟩)
  exact this ⟨f, hf, rfl⟩

/-- `H ∈ OΛ̃_m ⊗ OPol_k`: `H = Σ_γ F_γ(x) y^γ` with `F_γ ∈ OΛ̃_m`. -/
def Dec (m k : ℕ) (H : SkewPolynomial (m+k)) : Prop :=
  ∃ F : (Fin k → ℕ) →₀ SkewPolynomial m, (∀ γ, F γ ∈ OLam m) ∧
    H = F.sum fun γ P => inclX m k P * inclY m k (monomial γ 1)

theorem Dec.zero : Dec m k 0 := ⟨0, fun _ => zero_mem _, by simp⟩

theorem Dec.add {H H' : SkewPolynomial (m+k)} (hH : Dec m k H) (hH' : Dec m k H') :
    Dec m k (H + H') := by
  obtain ⟨F, hF, rfl⟩ := hH
  obtain ⟨F', hF', rfl⟩ := hH'
  refine ⟨F + F', fun γ => add_mem (hF γ) (hF' γ), ?_⟩
  rw [Finsupp.sum_add_index']
  · intro γ; rw [map_zero, sp_zero_mul]
  · intro γ P Q; rw [map_add, add_mul]

theorem Dec.sum {ι : Type*} (s : Finset ι) {H : ι → SkewPolynomial (m+k)}
    (h : ∀ i ∈ s, Dec m k (H i)) : Dec m k (∑ i ∈ s, H i) := by
  classical
  induction s using Finset.induction_on with
  | empty => rw [Finset.sum_empty]; exact Dec.zero
  | insert p s hp hs =>
    rw [Finset.sum_insert hp]
    exact (h p (Finset.mem_insert_self p s)).add (hs fun i hi => h i (Finset.mem_insert_of_mem hi))

theorem Dec.neg {H : SkewPolynomial (m+k)} (hH : Dec m k H) : Dec m k (-H) := by
  obtain ⟨F, hF, rfl⟩ := hH
  refine ⟨-F, fun γ => neg_mem (hF γ), ?_⟩
  rw [Finsupp.sum_neg_index]
  · simp only [map_neg, neg_mul, Finsupp.sum, Finset.sum_neg_distrib]
  · intro γ; rw [map_zero, sp_zero_mul]

theorem Dec.single {f : SkewPolynomial m} (hf : f ∈ OLam m) (γ : Fin k → ℕ) :
    Dec m k (inclX m k f * inclY m k (monomial γ 1)) := by
  classical
  refine ⟨Finsupp.single γ f, fun γ' => ?_, ?_⟩
  · rw [Finsupp.single_apply]; split_ifs; exacts [hf, zero_mem _]
  · rw [Finsupp.sum_single_index]; rw [map_zero, sp_zero_mul]

theorem Dec.inclX_mul_inclY {f : SkewPolynomial m} (hf : f ∈ OLam m) (Q : SkewPolynomial k) :
    Dec m k (inclX m k f * inclY m k Q) := by
  have hQ : Q = Q.sum fun γ c => c • monomial γ 1 := by
    conv_lhs => rw [← Finsupp.sum_single Q]
    exact Finsupp.sum_congr fun γ _ => (Finsupp.smul_single_one γ _).symm
  rw [hQ, Finsupp.sum, map_sum, Finset.mul_sum]
  refine Dec.sum _ fun γ _ => ?_
  rw [map_zsmul, mul_smul_comm, ← smul_mul_assoc, ← map_zsmul]
  exact Dec.single (zsmul_mem hf _) γ

theorem Dec.inclX_mul {f : SkewPolynomial m} (hf : f ∈ OLam m) {H : SkewPolynomial (m+k)}
    (hH : Dec m k H) : Dec m k (inclX m k f * H) := by
  obtain ⟨F, hF, rfl⟩ := hH
  rw [Finsupp.sum, Finset.mul_sum]
  refine Dec.sum _ fun γ _ => ?_
  rw [← sp_mul_assoc, ← map_mul]
  exact Dec.single (mul_mem hf (hF γ)) γ

theorem Dec.inclY_mul (j : ℕ) {H : SkewPolynomial (m+k)} (hH : Dec m k H) :
    Dec m k (inclY m k (elementaryPoly k j) * H) := by
  obtain ⟨F, hF, rfl⟩ := hH
  rw [Finsupp.sum, Finset.mul_sum]
  refine Dec.sum _ fun γ _ => ?_
  rw [← sp_mul_assoc, inclY_elementaryPoly_mul_inclX, sp_mul_assoc, ← map_mul]
  exact Dec.inclX_mul_inclY (iterate_parityInv_mem_OLam (hF γ) j) _

theorem dec_of_mem {H : SkewPolynomial (m+k)} (hH : H ∈ tosymAB m k) : Dec m k H := by
  suffices h : ∀ G ∈ tosymAB m k, ∀ H, Dec m k H → Dec m k (G * H) by
    have := h H hH 1 (by
      have h1 := Dec.single (m := m) (k := k) (one_mem (OLam m)) 0
      rwa [map_one, show (monomial (0 : Fin k → ℕ) 1 : SkewPolynomial k) = 1 from rfl, map_one,
        one_mul] at h1)
    rwa [mul_one] at this
  intro G hG
  rw [tosymAB_eq] at hG
  induction hG using Subring.closure_induction with
  | mem G hG =>
    rcases hG with ⟨j, rfl⟩ | ⟨j, rfl⟩
    · exact fun H hH => Dec.inclX_mul (elementaryPoly_mem_OLam m j) hH
    · exact fun H hH => Dec.inclY_mul j hH
  | zero => intro H _; rw [sp_zero_mul]; exact Dec.zero
  | one => intro H hH; rwa [one_mul]
  | add G G' _ _ hG hG' => intro H hH; rw [add_mul]; exact (hG H hH).add (hG' H hH)
  | neg G _ hG => intro H hH; rw [neg_mul]; exact (hG H hH).neg
  | mul G G' _ _ hG hG' => intro H hH; rw [sp_mul_assoc]; exact hG _ (hG' H hH)

/-- Two blocks, spanning (Corollary 4.8, coefficients in `OΛ̃_{m+k}`). -/
theorem two_span {G : SkewPolynomial (m+k)} (hG : G ∈ tosymAB m k) :
    ∃ d : (Fin k → ℕ) → SkewPolynomial (m+k), (∀ μ, d μ ∈ OLam (m+k)) ∧
      G = ∑ μ ∈ BoxPartitionCount.box k m, inclY m k (EQSchur.twisted k μ) * d μ := by
  obtain ⟨c, hc, rfl⟩ := EQZab.zab_span_twisted hG
  refine ⟨fun μ => twistRev (m+k) (c μ), fun μ => ?_, rfl⟩
  exact EQLima.theta_mem_OLam (EQZab.longestPerm_mem_osym (hc μ))

/-- Two blocks, independence (Corollary 4.8, coefficients in `OΛ̃_{m+k}`). -/
theorem two_indep (d : (Fin k → ℕ) → SkewPolynomial (m+k)) (hd : ∀ μ, d μ ∈ OLam (m+k))
    (h0 : ∑ μ ∈ BoxPartitionCount.box k m, inclY m k (EQSchur.twisted k μ) * d μ = 0) :
    ∀ μ ∈ BoxPartitionCount.box k m, d μ = 0 := by
  have e : ∀ μ, d μ = twistRev (m+k) (longestPerm (m+k) (theta (m+k) (d μ))) := fun μ => by
    rw [twistRev, RingHom.comp_apply, EQSchur.longestPerm_longestPerm, EQSchur.theta_theta]
  intro μ hμ
  have := EQZab.zab_indep_twisted (fun μ => longestPerm (m+k) (theta (m+k) (d μ)))
    (fun μ => EQZab.longestPerm_mem_osym (EQLima.theta_mem_osym_of_OLam (hd μ)))
    (by rw [← h0]; exact Finset.sum_congr rfl fun ν _ => by rw [← e]) μ hμ
  rw [e μ, this, map_zero]

theorem sum_mem_tosymAB (d : (Fin k → ℕ) → SkewPolynomial (m+k)) (hd : ∀ μ, d μ ∈ OLam (m+k)) :
    ∑ μ ∈ BoxPartitionCount.box k m, inclY m k (EQSchur.twisted k μ) * d μ ∈ tosymAB m k := by
  refine ⟨∑ μ ∈ BoxPartitionCount.box k m, inclY m k (EQSchur.untwisted k μ) *
    phiAB m k (longestPerm (m+k) (theta (m+k) (d μ))), ?_, ?_⟩
  · exact Subring.sum_mem _ fun μ _ => Subring.mul_mem _
      (EQZab.inclY_mem (EQZab.untwisted_mem_osym μ))
      (EQZab.phiAB_mem (EQZab.longestPerm_mem_osym (EQLima.theta_mem_osym_of_OLam (hd μ))))
  · simp only [map_sum, map_mul, EQZab.tauAB_inclY_untwisted, EQZab.tauAB_phiAB]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [twistRev, RingHom.comp_apply, EQSchur.longestPerm_longestPerm, EQSchur.theta_theta]

/-! ## Compositions -/

/-- The size of a composition, written last block first. -/
def blocksN : List ℕ → ℕ
  | [] => 0
  | k :: a => blocksN a + k

/-- `OΛ̃_{a_1} ⊠ ⋯ ⊠ OΛ̃_{a_r} ⊆ OPol_n` for the composition `a` (last block first). -/
def TB : (a : List ℕ) → Subring (SkewPolynomial (blocksN a))
  | [] => ⊤
  | k :: a => Subring.closure ((inclX (blocksN a) k '' (TB a : Set (SkewPolynomial (blocksN a)))) ∪
      Set.range (fun j => inclY (blocksN a) k (elementaryPoly k j)))

/-- The index set: one partition `λ_i` in an `a_i × (a_1 + ⋯ + a_{i−1})` box for each block. -/
def Idx : List ℕ → Type
  | [] => Unit
  | k :: a => Idx a × ↥(BoxPartitionCount.box k (blocksN a))

/-- `Idx a` is finite. -/
abbrev Idx.fintype : (a : List ℕ) → Fintype (Idx a)
  | [] => inferInstanceAs (Fintype Unit)
  | _ :: a => @instFintypeProd _ _ (Idx.fintype a) _

instance (a : List ℕ) : Fintype (Idx a) := Idx.fintype a

/-- The basis elements `s̃_{λ_1}(X_1) ⋯ s̃_{λ_r}(X_r)`. -/
def Bas : (a : List ℕ) → Idx a → SkewPolynomial (blocksN a)
  | [] => fun _ => 1
  | k :: a => fun i => inclX (blocksN a) k (Bas a i.1) * inclY (blocksN a) k (EQSchur.twisted k i.2.1)

theorem inclX_mem_TB {a : List ℕ} {k : ℕ} {f : SkewPolynomial (blocksN a)} (hf : f ∈ TB a) :
    inclX (blocksN a) k f ∈ TB (k :: a) :=
  Subring.subset_closure (Or.inl ⟨f, hf, rfl⟩)

theorem inclY_elementaryPoly_mem_TB (a : List ℕ) (k j : ℕ) :
    inclY (blocksN a) k (elementaryPoly k j) ∈ TB (k :: a) :=
  Subring.subset_closure (Or.inr ⟨j, rfl⟩)

theorem inclY_mem_TB (a : List ℕ) (k : ℕ) {f : SkewPolynomial k} (hf : f ∈ OLam k) :
    inclY (blocksN a) k f ∈ TB (k :: a) := by
  rw [SmallRank.OLam_eq_elementaryClosure] at hf
  have : (Subring.closure {f | ∃ j, 1 ≤ j ∧ j ≤ k ∧ f = elementaryPoly k j}).map
      (inclY (blocksN a) k) ≤ TB (k :: a) := by
    rw [RingHom.map_closure, Subring.closure_le]
    rintro _ ⟨f, ⟨j, -, -, rfl⟩, rfl⟩
    exact inclY_elementaryPoly_mem_TB a k j
  exact this ⟨f, hf, rfl⟩

theorem twisted_mem_OLam (k : ℕ) (μ : Fin k → ℕ) : EQSchur.twisted k μ ∈ OLam k := by
  rw [EQSchur.twisted_eq_theta_untwisted]
  exact EQLima.theta_mem_OLam (EQZab.untwisted_mem_osym μ)

theorem Bas_mem : ∀ (a : List ℕ) (i : Idx a), Bas a i ∈ TB a
  | [], _ => trivial
  | k :: a, i => Subring.mul_mem _ (inclX_mem_TB (Bas_mem a i.1))
      (inclY_mem_TB a k (twisted_mem_OLam k i.2.1))

theorem parityInv_mem_TB : ∀ (a : List ℕ) {f : SkewPolynomial (blocksN a)}, f ∈ TB a →
    parityInv (blocksN a) f ∈ TB a
  | [], _, _ => trivial
  | k :: a, f, hf => by
    have : TB (k :: a) ≤ (TB (k :: a)).comap (parityInv (blocksN a + k)) := by
      change Subring.closure _ ≤ _
      rw [Subring.closure_le]
      rintro _ (⟨g, hg, rfl⟩ | ⟨j, rfl⟩)
      · show parityInv _ (inclX _ k g) ∈ TB (k :: a)
        rw [EQZab.parityInv_inclX]
        exact inclX_mem_TB (parityInv_mem_TB a hg)
      · show parityInv _ (inclY _ k _) ∈ TB (k :: a)
        rw [EQZab.parityInv_inclY, parityInv_elementaryPoly, map_zsmul]
        exact zsmul_mem (inclY_elementaryPoly_mem_TB a k j) _
    exact this hf

theorem iterate_parityInv_mem_TB (a : List ℕ) {f : SkewPolynomial (blocksN a)} (hf : f ∈ TB a)
    (j : ℕ) : (parityInv (blocksN a))^[j] f ∈ TB a := by
  induction j with
  | zero => exact hf
  | succ j ih => rw [Function.iterate_succ_apply']; exact parityInv_mem_TB a ih

/-! ## Proposition 4.13 (1) -/

/-- `G = Σ_β (Bas β)(x) H_β` with `H_β ∈ OΛ̃_m ⊠ OΛ̃_k`. -/
def Spans (a : List ℕ) (k : ℕ) (G : SkewPolynomial (blocksN a + k)) : Prop :=
  ∃ H : Idx a → SkewPolynomial (blocksN a + k), (∀ β, H β ∈ tosymAB (blocksN a) k) ∧
    G = ∑ β, inclX (blocksN a) k (Bas a β) * H β

/-- **Proposition 4.13 (1), spanning**: every element of `OΛ̃_{a_1} ⊠ ⋯ ⊠ OΛ̃_{a_r}` is
`Σ_i (s̃_{λ_1}(X_1) ⋯ s̃_{λ_r}(X_r)) c_i` with `c_i ∈ OΛ̃_n`. -/
theorem prop_4_13_one_span : ∀ (a : List ℕ) {G : SkewPolynomial (blocksN a)}, G ∈ TB a →
    ∃ c : Idx a → SkewPolynomial (blocksN a), (∀ i, c i ∈ OLam (blocksN a)) ∧
      G = ∑ i, Bas a i * c i
  | [], G, _ => ⟨fun _ => G, fun _ => SmallRank.mem_OLam_small (by simp [blocksN]) _,
      by show G = ∑ _i : Unit, (1 : SkewPolynomial (blocksN [])) * G; simp⟩
  | k :: a, G, hG => by
    classical
    set m := blocksN a
    -- spanning with coefficients in `OΛ̃_m ⊠ OΛ̃_k`
    have hof : ∀ {Y : SkewPolynomial m} {H : SkewPolynomial (m+k)}, Y ∈ TB a →
        H ∈ tosymAB m k → Spans a k (inclX m k Y * H) := by
      intro Y H hY hH
      obtain ⟨c, hc, rfl⟩ := prop_4_13_one_span a hY
      refine ⟨fun β => inclX m k (c β) * H, fun β => Subring.mul_mem _
        (inclX_mem_tosymAB (hc β)) hH, ?_⟩
      rw [map_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun β _ => ?_
      rw [map_mul, sp_mul_assoc]
    have hadd : ∀ {G G'}, Spans a k G → Spans a k G' → Spans a k (G + G') := by
      rintro _ _ ⟨H, hH, rfl⟩ ⟨H', hH', rfl⟩
      exact ⟨H + H', fun β => add_mem (hH β) (hH' β), by
        simp only [Pi.add_apply, mul_add, Finset.sum_add_distrib]⟩
    have hsum : ∀ (s : Finset (Idx a)) (G : Idx a → SkewPolynomial (m+k)),
        (∀ β ∈ s, Spans a k (G β)) → Spans a k (∑ β ∈ s, G β) := by
      intro s G h
      induction s using Finset.induction_on with
      | empty => exact ⟨0, fun _ => zero_mem _, by simp [sp_mul_zero]⟩
      | insert p s hp hs =>
        rw [Finset.sum_insert hp]
        exact hadd (h p (Finset.mem_insert_self p s)) (hs fun i hi => h i (Finset.mem_insert_of_mem hi))
    have key : ∀ F : SkewPolynomial (m+k), F ∈ TB (k :: a) → ∀ G, Spans a k G →
        Spans a k (F * G) := by
      intro F hF
      induction hF using Subring.closure_induction with
      | mem F hF =>
        rintro G ⟨H, hH, rfl⟩
        rw [Finset.mul_sum]
        refine hsum _ _ fun β _ => ?_
        rcases hF with ⟨g, hg, rfl⟩ | ⟨j, rfl⟩
        · rw [← sp_mul_assoc, ← map_mul]
          exact hof (Subring.mul_mem _ hg (Bas_mem a β)) (hH β)
        · rw [← sp_mul_assoc, inclY_elementaryPoly_mul_inclX, sp_mul_assoc]
          exact hof (iterate_parityInv_mem_TB a (Bas_mem a β) j)
            (Subring.mul_mem _ (inclY_elementaryPoly_mem j) (hH β))
      | zero => rintro G -; rw [sp_zero_mul]; exact ⟨0, fun _ => zero_mem _, by simp [sp_mul_zero]⟩
      | one => intro G hG; rwa [one_mul]
      | add F F' _ _ hF hF' => intro G hG; rw [add_mul]; exact hadd (hF G hG) (hF' G hG)
      | neg F _ hF =>
        intro G hG
        obtain ⟨H, hH, e⟩ := hF G hG
        refine ⟨-H, fun β => neg_mem (hH β), ?_⟩
        rw [neg_mul, e]; simp only [Pi.neg_apply, mul_neg, Finset.sum_neg_distrib]
      | mul F F' _ _ hF hF' => intro G hG; rw [sp_mul_assoc]; exact hF _ (hF' G hG)
    have h1 : Spans a k 1 := by
      have := hof (Y := 1) (H := 1) (one_mem _) (one_mem _)
      rwa [map_one, one_mul] at this
    obtain ⟨H, hH, e⟩ := key G hG 1 h1
    rw [mul_one] at e
    choose d hd hdH using fun β => two_span (hH β)
    refine ⟨fun i => d i.1 i.2.1, fun i => hd i.1 i.2.1, ?_⟩
    show G = ∑ i : Idx a × ↥(BoxPartitionCount.box k m),
      inclX m k (Bas a i.1) * inclY m k (EQSchur.twisted k i.2.1) * d i.1 i.2.1
    rw [e, Fintype.sum_prod_type]
    refine Finset.sum_congr rfl fun β _ => ?_
    rw [hdH β, Finset.mul_sum, ← Finset.sum_coe_sort]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [sp_mul_assoc]

/-- **Proposition 4.13 (1), independence**: the coefficients are unique. -/
theorem prop_4_13_one_indep : ∀ (a : List ℕ) (c : Idx a → SkewPolynomial (blocksN a)),
    (∀ i, c i ∈ OLam (blocksN a)) → ∑ i, Bas a i * c i = 0 → ∀ i, c i = 0
  | [], c, _, h0, i => by
    have h : ∑ _j : Unit, (1 : SkewPolynomial (blocksN [])) * c () = 0 := h0
    rw [show i = () from rfl]
    simpa using h
  | k :: a, c, hc, h0, i => by
    classical
    set m := blocksN a
    let c' : Idx (k :: a) → SkewPolynomial (m+k) := c
    have hc' : ∀ i, c' i ∈ OLam (m+k) := hc
    let H : Idx a → SkewPolynomial (m+k) := fun β =>
      ∑ μ ∈ BoxPartitionCount.box k m, inclY m k (EQSchur.twisted k μ) *
        (if hμ : μ ∈ BoxPartitionCount.box k m then c' (β, ⟨μ, hμ⟩) else 0)
    have hdmem : ∀ β μ, (if hμ : μ ∈ BoxPartitionCount.box k m then
        c' (β, ⟨μ, hμ⟩) else 0) ∈ OLam (m+k) := fun β μ => by
      split_ifs; exacts [hc' _, zero_mem _]
    have h0' : ∑ i : Idx a × ↥(BoxPartitionCount.box k m),
        inclX m k (Bas a i.1) * inclY m k (EQSchur.twisted k i.2.1) *
          c' i = 0 := h0
    have hsumH : ∑ β, inclX m k (Bas a β) * H β = 0 := by
      rw [← h0', Fintype.sum_prod_type]
      refine Finset.sum_congr rfl fun β _ => ?_
      simp only [H, Finset.mul_sum]
      rw [← Finset.sum_coe_sort]
      refine Finset.sum_congr rfl fun μ _ => ?_
      simp only [μ.2, ↓reduceDIte]
      rw [← sp_mul_assoc]
    -- each `H β` lies in `OΛ̃_m ⊗ OPol_k`
    choose F hF hFH using fun β => dec_of_mem (sum_mem_tosymAB _ (hdmem β))
    let s : Finset (Fin k → ℕ) := Finset.univ.biUnion fun β => (F β).support
    have hFs : ∀ β, H β = ∑ γ ∈ s, inclX m k (F β γ) * inclY m k (monomial γ 1) := by
      intro β
      refine (hFH β).trans ?_
      rw [Finsupp.sum_of_support_subset]
      · exact fun γ hγ => Finset.mem_biUnion.mpr ⟨β, Finset.mem_univ _, hγ⟩
      · intro γ _; rw [map_zero, sp_zero_mul]
    have hγ : ∑ γ ∈ s, inclX m k (∑ β, Bas a β * F β γ) * inclY m k (monomial γ 1) = 0 := by
      rw [← hsumH]
      simp only [hFs, Finset.mul_sum, map_sum, Finset.sum_mul]
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl fun β _ => Finset.sum_congr rfl fun γ _ => ?_
      rw [map_mul, sp_mul_assoc]
    have hF0 : ∀ β, F β = 0 := by
      intro β
      refine Finsupp.ext fun γ => ?_
      by_cases hs : γ ∈ s
      · exact prop_4_13_one_indep a (fun β => F β γ) (fun β => hF β γ)
          (eq_zero_of_sum_inclX_mul_inclY s _ hγ γ hs) β
      · have : γ ∉ (F β).support := fun h => hs (Finset.mem_biUnion.mpr ⟨β, Finset.mem_univ _, h⟩)
        simpa using this
    have hH0 : H i.1 = 0 := by rw [hFs i.1]; simp [hF0, sp_zero_mul]
    have := two_indep (m := m) (k := k) (fun μ => if hμ : μ ∈ BoxPartitionCount.box k m then
      c' (i.1, ⟨μ, hμ⟩) else 0) (hdmem i.1) hH0 i.2.1 i.2.2
    split_ifs at this with h
    · exact this
    · exact absurd i.2.2 h

/-- The number of basis elements is the multinomial coefficient `n! / (a_1! ⋯ a_r!)`. -/
theorem card_Idx : ∀ a : List ℕ, Fintype.card (Idx a) * (a.map Nat.factorial).prod =
    (blocksN a).factorial
  | [] => rfl
  | k :: a => by
    show Fintype.card (Idx a × ↥(BoxPartitionCount.box k (blocksN a))) *
      (List.map Nat.factorial (k :: a)).prod = (blocksN a + k).factorial
    rw [Fintype.card_prod, Fintype.card_coe, BoxPartitionCount.card_box, List.map_cons,
      List.prod_cons, add_comm k, ← Nat.choose_symm_add,
      ← Nat.add_choose_mul_factorial_mul_factorial (blocksN a) k, ← card_Idx a]
    simp only [Nat.choose_symm_add]
    ring

end

end OddMath.Frontier.EQBlocks
