import OddMath.Frontier.EQSkewDifferential
import OddMath.Frontier.NilHeckeEndomorphism
import OddMath.Frontier.OnhReflection
import OddMath.Frontier.OnhPolynomial
import OddMath.Frontier.StaircaseIndependence
import OddMath.Frontier.LongestElementary
import OddMath.Frontier.LongestKernel
import OddMath.Diagrams.OddNilHecke.DifferentialLongestComparison

/-!
# The odd nilHecke action on `Z_n` and the differential of `ONH_n`

Source: A. P. Ellis, Y. Qi, *The differential graded odd nilHecke algebra*, arXiv:1504.01712v2,
§3.2 (Corollary 3.6, Proposition 3.7, Definition 3.8, Corollary 3.9) and §3.4
(Proposition 3.16 (2)).

Rank `N = n + 2` (odd-lean's `NilHeckeAction.Presented n` is `ONH_{n+2}`), integer coefficients,
strands numbered from `0`. `Z_N = OPol_N(α)` with `α = (0,1,0,1,…)` (`zAlpha`), differential
`D = dAlpha (zAlpha N)` (`d(g 1_z) = (d g + ι(g) Σ_i {i} x_i) 1_z`) and right action of `OΛ_N`
by `g 1_z · c = g (θ ∘ w₀)(c) 1_z`. `ONH_N` acts by `x_j` (left multiplication) and `∂_i` (the odd
divided differences `AllRankDivided.divided i` of EKL).

* **Operator identities** (the dg action): `dAlpha_generator_anticomm`
  (`D x_j + x_j D = x_j²`, i.e. `d(x_j) = x_j²` in the super commutator sense),
  `dAlpha_divided_anticomm` (`D ∂_i + ∂_i D = id`, i.e. `d(∂_i) = 1`), for general `α` the formula
  `dAlpha_divided_general` (`d_α ∂_i + ∂_i d_α = id + (α_i + α_{i+1} - 1) s_i ι`), and the auxiliary
  `ι ∂_i = -∂_i ι`, `d s_i = -s_i d`, `d ∂_i + ∂_i d = id - s_i ι`.
* **Twisted symmetry** (`map_twistRev_osym`): `(θ ∘ w₀)(OΛ_N) = OΛ̃_N`, the subring generated by
  EKL's elementary polynomials, i.e. (for `N ≥ 2`) the common kernel of the `∂_i`; hence each `∂_i`
  is right `OΛ_N`-linear on `Z_N` (`divided_mul_twistRev`).
* **Corollary 3.9** (`action_dONH`, `action_dONH_of_mem_parity`, `corollary_3_9`): the action map
  `ONH_N → End(Z_N)` intertwines `dONH` with the super commutator `[D, -]`, and it is a ring
  isomorphism onto the right `OΛ_N`-linear endomorphisms of `Z_N` (transporting EKL's
  `ONH_N ≅ End_{OΛ̃_N}(OPol_N)`, `NilHeckeEndomorphism.actionEquiv`).
* **Corollary 3.6 / Proposition 3.7** (`corollary_3_6`): `f ↦ f e_N` is an isomorphism of left dg
  `OPol_N`-modules `OPol_N(0,1,0,1,…) ≅ ONH_N e_N` (injective, image the left ideal `ONH_N e_N`,
  `d(f e_N) = (D f) e_N`).
* **Proposition 3.16 (2)** (`dONH_acyclic`): for `N ≥ 2` every `dONH`-cocycle `p` is the
  coboundary of `∂_0 p`.
-/

namespace OddMath.Frontier.EQZn

open OddMath.SkewPolynomial (SkewPolynomial generator monomial)
open EQSkewDifferential
open AllRankDivided (divided s)
open NilHeckeAction
open scoped BigOperators

noncomputable section

/-- The ring structure of `OPol`, preferred over the pointwise `Finsupp` structure. -/
local instance (priority := high) znActNUNASemiring (m : ℕ) :
    NonUnitalNonAssocSemiring (SkewPolynomial m) :=
  @NonAssocSemiring.toNonUnitalNonAssocSemiring _
    (@Semiring.toNonAssocSemiring _ (OddMath.PbwL3.instSemiring m))

local instance (priority := high) znActNUNARing (m : ℕ) :
    NonUnitalNonAssocRing (SkewPolynomial m) :=
  @NonAssocRing.toNonUnitalNonAssocRing _ (@Ring.toNonAssocRing _ (OddMath.PbwL3.instRing m))

variable {n : ℕ}

/-! ## Operator identities on `OPol_N` -/

theorem parityInv_s (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    parityInv (n+2) (s i f) = s i (parityInv (n+2) f) := by
  have h : (parityInv (n+2)).comp (s i).toRingHom = (s i).toRingHom.comp (parityInv (n+2)) :=
    ringHom_ext fun j => by simp [AllRankDivided.s_generator]
  exact RingHom.congr_fun h f

/-- `∂_i` is odd: `ι ∂_i = -∂_i ι`. -/
theorem parityInv_divided (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    parityInv (n+2) (divided i f) = -divided i (parityInv (n+2) f) := by
  induction f using induction_generator with
  | hgen j =>
    rw [AllRankDivided.divided_generator, parityInv_generator, map_neg,
      AllRankDivided.divided_generator, neg_neg]
    split <;> simp
  | h0 => simp
  | h1 => simp [AllRankDivided.divided_one]
  | hadd f g hf hg => simp only [map_add, hf, hg, neg_add]
  | hneg f hf => simp only [map_neg, hf]
  | hmul f g hf hg =>
    rw [AllRankDivided.divided_mul, map_add, map_mul, map_mul, hf, hg, parityInv_s, map_mul,
      AllRankDivided.divided_mul]
    simp only [neg_mul, mul_neg, neg_add]

/-- `d s_i = -s_i d`. -/
theorem d_s (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    d (n+2) (s i f) = -s i (d (n+2) f) := by
  induction f using induction_generator with
  | hgen j => simp [AllRankDivided.s_generator]
  | h0 => simp
  | h1 => simp
  | hadd f g hf hg => simp only [map_add, hf, hg, neg_add]
  | hneg f hf => simp only [map_neg, hf]
  | hmul f g hf hg =>
    rw [map_mul, d_mul, hf, hg, parityInv_s, d_mul, map_add, map_mul, map_mul]
    simp only [neg_mul, mul_neg, neg_add]

theorem comm_mul_aux {R : Type*} [Ring R] (f g dpf dpg pdf pdg ipf pif dsf sdf isf sif
    dg pg sig : R)
    (hf : dpf + pdf = f - sif) (hg : dpg + pdg = g - sig) (hip : ipf = -pif) (hds : dsf = -sdf)
    (his : isf = sif) :
    (dpf * g + ipf * dg + (dsf * pg + isf * dpg)) + (pdf * g + sdf * pg + (pif * dg + sif * pdg)) =
      f * g - sif * sig := by
  rw [hip, hds, his, ← sub_eq_iff_eq_add'.mpr hf.symm, ← sub_eq_iff_eq_add'.mpr hg.symm]
  simp only [sub_mul, mul_sub, neg_mul]
  abel

/-- `d ∂_i + ∂_i d = id - s_i ι` on `OPol_N` (the untwisted differential). -/
theorem d_divided_anticomm (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    d (n+2) (divided i f) + divided i (d (n+2) f) = f - s i (parityInv (n+2) f) := by
  induction f using induction_generator with
  | hgen j =>
    rw [d_generator, AllRankDivided.divided_mul, AllRankDivided.divided_generator,
      parityInv_generator, map_neg, AllRankDivided.s_generator, neg_neg]
    by_cases hj : j = i.castSucc ∨ j = i.succ
    · simp only [hj, ite_true, d_one, one_mul, mul_one, zero_add]
      abel
    · have hsw : Equiv.swap i.castSucc i.succ j = j :=
        Equiv.swap_apply_of_ne_of_ne (fun h => hj (Or.inl h)) (fun h => hj (Or.inr h))
      simp only [hj, ite_false, map_zero, zero_mul, mul_zero, add_zero, hsw, sub_self]
  | h0 => simp
  | h1 => simp [AllRankDivided.divided_one]
  | hadd f g hf hg =>
    rw [map_add, map_add, map_add, map_add, map_add, map_add]
    rw [show d (n+2) (divided i f) + d (n+2) (divided i g) +
        (divided i (d (n+2) f) + divided i (d (n+2) g)) =
        (d (n+2) (divided i f) + divided i (d (n+2) f)) +
        (d (n+2) (divided i g) + divided i (d (n+2) g)) by abel, hf, hg]
    abel
  | hneg f hf =>
    rw [map_neg, map_neg, map_neg, map_neg, map_neg, map_neg, ← neg_add, hf, neg_sub,
      neg_sub_neg]
  | hmul f g hf hg =>
    rw [AllRankDivided.divided_mul, map_add, d_mul, d_mul, d_mul, map_add,
      AllRankDivided.divided_mul, AllRankDivided.divided_mul, map_mul, map_mul]
    exact comm_mul_aux _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ hf hg (parityInv_divided i f)
      (d_s i f) (parityInv_s i f)

theorem divided_sAlpha (α : Fin (n+2) → ℤ) (i : Fin (n+1)) :
    divided i (sAlpha α) = (α i.castSucc + α i.succ) • (1 : SkewPolynomial (n+2)) := by
  have hne := AllRankDivided.adjacent_ne i
  simp only [sAlpha, map_sum, map_zsmul, AllRankDivided.divided_generator]
  have h : ∀ j : Fin (n+2), α j • (if j = i.castSucc ∨ j = i.succ then
      (1 : SkewPolynomial (n+2)) else 0) =
      (if j = i.castSucc then α j • 1 else 0) + (if j = i.succ then α j • 1 else 0) := by
    intro j
    by_cases h1 : j = i.castSucc
    · subst h1; simp [hne]
    · by_cases h2 : j = i.succ
      · subst h2; simp [h1]
      · simp [h1, h2]
  simp only [h, Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ, ite_true, add_smul]

/-- For general `α`: `d_α ∂_i + ∂_i d_α = id + (α_i + α_{i+1} - 1) s_i ι` on `OPol_N(α)`. -/
theorem dAlpha_divided_general (α : Fin (n+2) → ℤ) (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    dAlpha α (divided i f) + divided i (dAlpha α f) =
      f + (α i.castSucc + α i.succ - 1) • s i (parityInv (n+2) f) := by
  have h1 := d_divided_anticomm i f
  have h2 := parityInv_divided i f
  rw [dAlpha_apply, dAlpha_apply, map_add, AllRankDivided.divided_mul, divided_sAlpha, h2,
    mul_smul_comm, mul_one, sub_smul, one_smul]
  rw [show d (n+2) (divided i f) + -divided i (parityInv (n+2) f) * sAlpha α +
      (divided i (d (n+2) f) + (divided i (parityInv (n+2) f) * sAlpha α +
        (α i.castSucc + α i.succ) • s i (parityInv (n+2) f))) =
      (d (n+2) (divided i f) + divided i (d (n+2) f)) +
        (α i.castSucc + α i.succ) • s i (parityInv (n+2) f) by
    simp only [neg_mul]; abel, h1]
  abel

theorem zAlpha_adjacent (i : Fin (n+1)) :
    zAlpha (n+2) i.castSucc + zAlpha (n+2) i.succ = 1 := by
  simp only [zAlpha, Fin.val_castSucc, Fin.val_succ]
  rcases Nat.mod_two_eq_zero_or_one i.val with h | h
  · rw [h, show (i.val + 1) % 2 = 1 by omega]; rfl
  · rw [h, show (i.val + 1) % 2 = 0 by omega]; rfl

/-- **`d(∂_i) = 1`** on `Z_N` (Ellis–Qi, Proposition 3.3 / Corollary 3.9): the super commutator of
the differential `D` of `Z_N = OPol_N(0,1,0,1,…)` with the odd operator `∂_i` is the identity,
`D ∂_i + ∂_i D = id`. -/
theorem dAlpha_divided_anticomm (i : Fin (n+1)) (f : SkewPolynomial (n+2)) :
    dAlpha (zAlpha (n+2)) (divided i f) + divided i (dAlpha (zAlpha (n+2)) f) = f := by
  rw [dAlpha_divided_general, zAlpha_adjacent, sub_self, zero_smul, add_zero]

/-- **`d(x_j) = x_j²`** on `Z_N` (Ellis–Qi, Corollary 3.9): `D x_j + x_j D = x_j²` as operators
(for every `α`). -/
theorem dAlpha_generator_anticomm {N : ℕ} (α : Fin N → ℤ) (j : Fin N) (f : SkewPolynomial N) :
    dAlpha α (generator j * f) + generator j * dAlpha α f = generator j * generator j * f := by
  rw [dAlpha_mul, d_generator, parityInv_generator, neg_mul, neg_add_cancel_right]


/-! ## `(θ ∘ w₀)(OΛ_N)` is the twisted symmetric subring -/

section Twisted

open FiniteCompleteElementary PlacticEvaluation SignedPermutation LongestElementary

theorem ringHom_strictSum {R S : Type*} [Ring R] [Ring S] (φ : R →+* S) :
    ∀ {m : ℕ} (x : Fin m → R) (k : ℕ),
      φ (FiniteWords.strictSum x k) = FiniteWords.strictSum (fun j => φ (x j)) k
  | 0, x, 0 => by simp
  | 0, x, k+1 => by simp
  | m+1, x, 0 => by simp
  | m+1, x, k+1 => by
      rw [FiniteWords.strictSum_succ, FiniteWords.strictSum_succ, map_add, map_mul,
        ringHom_strictSum φ _ k, ringHom_strictSum φ _ (k+1)]

theorem strictSum_zsmul {R : Type*} [Ring R] (c : ℤ) :
    ∀ {m : ℕ} (x : Fin m → R) (k : ℕ),
      FiniteWords.strictSum (fun j => c • x j) k = c ^ k • FiniteWords.strictSum x k
  | 0, x, 0 => by simp
  | 0, x, k+1 => by simp
  | m+1, x, 0 => by simp
  | m+1, x, k+1 => by
      have h1 := strictSum_zsmul c (fun i => x i.succ) k
      have h2 := strictSum_zsmul c (fun i => x i.succ) (k+1)
      rw [FiniteWords.strictSum_succ, FiniteWords.strictSum_succ, h1, h2, smul_mul_smul_comm,
        ← pow_succ', smul_add]

theorem strictSum_tilde (N k : ℕ) :
    FiniteWords.strictSum (tildeGenerator (n := N)) k = elementaryPoly N k := by
  classical
  rw [FiniteWords.strictSum_eq, elementaryPoly]
  refine Finset.sum_congr rfl fun f _ => ?_
  split_ifs <;> rfl

theorem neg_one_pow_mul_self (m : ℕ) : (-1 : ℤ) ^ m * (-1) ^ m = 1 := by
  rw [← pow_add, ← two_mul, pow_mul]; norm_num

/-- `(θ ∘ w₀)(e_k) = ± ε_k`: the image of Ellis–Qi's untwisted elementary polynomial is, up to
sign, EKL's elementary polynomial `ε_k = Σ x̃_{i_1}⋯x̃_{i_k}`, `x̃_i = (-1)^i x_i`. -/
theorem twistRev_elementary (N k : ℕ) :
    twistRev N (elementary N k) =
      ((-1 : ℤ) ^ ((N-1).choose 2 * k + (k.choose 2 + k * (N-1).choose 2))) •
        elementaryPoly N k := by
  have hc : (fun j : Fin N => twistRev N (generator j)) = fun j =>
      (-1 : ℤ) ^ ((N-1).choose 2) • (skewAction (longest N)).toRingHom (tildeGenerator j) := by
    funext j
    change _ = _ • skewAction (longest N) (tildeGenerator j)
    rw [action_tilde, smul_smul, ← pow_add, ← two_mul, pow_mul,
      neg_one_sq, one_pow, one_smul, twistRev_generator]
    rfl
  rw [elementary, ringHom_strictSum, hc, strictSum_zsmul, ← ringHom_strictSum,
    strictSum_tilde]
  change _ • skewAction (longest N) (elementaryPoly N k) = _
  rw [action_elementary, smul_smul, ← pow_mul, ← pow_add]

/-- `(θ ∘ w₀)(OΛ_N) = OΛ̃_N`, the subring generated by EKL's elementary polynomials (Ellis–Qi,
before Proposition 3.7: `(θ ∘ w₀)(f) ∈ OΛ̃_N` for `f ∈ OΛ_N`, and conversely). -/
theorem map_twistRev_osym (N : ℕ) : (osym N).map (twistRev N) = ElementaryBranching.E N := by
  apply le_antisymm
  · rw [Subring.map_le_iff_le_comap]
    refine Subring.closure_le.mpr ?_
    rintro _ ⟨k, rfl⟩
    change twistRev N (elementary N k) ∈ ElementaryBranching.E N
    rw [twistRev_elementary]
    exact Subring.zsmul_mem _ (Subring.subset_closure (Set.mem_range_self k)) _
  · refine Subring.closure_le.mpr ?_
    rintro _ ⟨k, rfl⟩
    refine ⟨((-1 : ℤ) ^ ((N-1).choose 2 * k + (k.choose 2 + k * (N-1).choose 2))) •
      elementary N k, Subring.zsmul_mem _ (Subring.subset_closure (Set.mem_range_self k)) _, ?_⟩
    change twistRev N (_ • elementary N k) = _
    rw [map_zsmul, twistRev_elementary, smul_smul, neg_one_pow_mul_self, one_smul]

theorem twistRev_mem_E {N : ℕ} {c : SkewPolynomial N} (hc : c ∈ osym N) :
    twistRev N c ∈ ElementaryBranching.E N := by
  rw [← map_twistRev_osym]; exact ⟨c, hc, rfl⟩

theorem twistRev_mem_kernel {c : SkewPolynomial (n+2)} (hc : c ∈ osym (n+2)) :
    twistRev (n+2) c ∈ OddSymmetricKernel.kernelSubring n := by
  rw [← StaircaseIndependence.E_eq_kernel]; exact twistRev_mem_E hc

theorem exists_twistRev_of_mem_kernel {k : SkewPolynomial (n+2)}
    (hk : k ∈ OddSymmetricKernel.kernelSubring n) : ∃ c ∈ osym (n+2), twistRev (n+2) c = k := by
  rw [← StaircaseIndependence.E_eq_kernel, ← map_twistRev_osym] at hk
  exact hk

/-- `∂_i` is right `OΛ_N`-linear on `Z_N`: `∂_i(g 1_z · c) = ∂_i(g 1_z) · c` for `c ∈ OΛ_N`. -/
theorem divided_mul_twistRev (i : Fin (n+1)) (g : SkewPolynomial (n+2))
    {c : SkewPolynomial (n+2)} (hc : c ∈ osym (n+2)) :
    divided i (g * twistRev (n+2) c) = divided i g * twistRev (n+2) c := by
  rw [AllRankDivided.divided_mul, twistRev_mem_kernel hc i, mul_zero, add_zero]

end Twisted

/-! ## Corollary 3.9 -/

open OddMath.Diagrams.OddNilHecke (dONH dONH_mul dONH_dot_mul dONH_crossing_mul dONH_crossing
  parity one_mem_parity eqIdempotent dONH_eqIdempotent)

/-- The right `OΛ_N`-linear endomorphisms of `Z_N` (right action `g 1_z · c = g (θ∘w₀)(c) 1_z`). -/
def rightOsymEnd (N : ℕ) : Subring (Module.End ℤ (SkewPolynomial N)) where
  carrier := {T | ∀ (f c : SkewPolynomial N), c ∈ osym N →
    T (f * twistRev N c) = T f * twistRev N c}
  zero_mem' := by intro f c _; simp
  one_mem' := by intro f c _; rfl
  add_mem' := by
    intro T U hT hU f c hc
    simp only [LinearMap.add_apply, hT f c hc, hU f c hc, add_mul]
  neg_mem' := by
    intro T hT f c hc
    simp only [LinearMap.neg_apply, hT f c hc, neg_mul]
  mul_mem' := by
    intro T U hT hU f c hc
    change T (U (f * twistRev N c)) = T (U f) * twistRev N c
    rw [hU f c hc, hT _ c hc]

theorem rightOsymEnd_eq (n : ℕ) :
    rightOsymEnd (n+2) = NilHeckeEndomorphism.rightKernelEnd n := by
  ext T
  constructor
  · intro hT f k
    obtain ⟨c, hc, hck⟩ := exists_twistRev_of_mem_kernel k.property
    rw [← hck]
    exact hT f c hc
  · intro hT f c hc
    exact hT f ⟨twistRev (n+2) c, twistRev_mem_kernel hc⟩

theorem dONH_one : dONH n (1 : Presented n) = 0 := by
  have h := dONH_mul (one_mem_parity n) (1 : Presented n)
  simp only [mul_one, ZMod.val_zero, pow_zero, one_mul] at h
  exact left_eq_add.mp h

/-- The statement of Corollary 3.9 for one element `p ∈ ONH_N`: the operator of `d(p)` on `Z_N` is
the super commutator `[D, p] = D ∘ p - (ι ∘ p ∘ ι) ∘ D`. -/
def Intertwines (p : Presented n) : Prop :=
  ∀ f, action n (dONH n p) f = dAlpha (zAlpha (n+2)) (action n p f) -
    parityInv (n+2) (action n p (parityInv (n+2) (dAlpha (zAlpha (n+2)) f)))

theorem intertwines_one : Intertwines (1 : Presented n) := by
  intro f
  rw [dONH_one, map_zero, map_one]
  simp only [LinearMap.zero_apply, Module.End.one_apply, parityInv_parityInv, sub_self]

theorem intertwines_add {p q : Presented n} (hp : Intertwines p) (hq : Intertwines q) :
    Intertwines (p + q) := by
  intro f
  rw [map_add, map_add, LinearMap.add_apply, hp f, hq f]
  simp only [map_add, LinearMap.add_apply]
  abel

theorem neg_one_pow_mul_eq_zsmul (m : ℕ) (x : Presented n) :
    (-1 : Presented n) ^ m * x = ((-1 : ℤ) ^ m) • x := by
  rw [zsmul_eq_mul]; push_cast; rfl

theorem intertwines_zsmul {p : Presented n} (r : ℤ) (hp : Intertwines p) :
    Intertwines (r • p) := by
  intro f
  rw [map_zsmul, map_zsmul, LinearMap.smul_apply, hp f, map_zsmul, LinearMap.smul_apply,
    LinearMap.smul_apply, map_zsmul, map_zsmul, smul_sub]

theorem intertwines_dot_mul (j : Fin (n+2)) {q : Presented n} (hq : Intertwines q) :
    Intertwines (dot n j * q) := by
  intro f
  rw [dONH_dot_mul, map_sub, LinearMap.sub_apply, sq]
  simp only [action_mul_apply, action_dot_apply]
  rw [hq f, dAlpha_mul, map_mul, d_generator, parityInv_generator]
  simp only [mul_sub, neg_mul, mul_assoc]
  abel

theorem intertwines_crossing_mul (i : Fin (n+1)) {q : Presented n} (hq : Intertwines q) :
    Intertwines (crossing n i * q) := by
  intro f
  rw [dONH_crossing_mul, map_sub, LinearMap.sub_apply, action_mul_apply, hq f, action_mul_apply,
    action_mul_apply, action_crossing_apply, action_crossing_apply, action_crossing_apply,
    parityInv_divided, map_sub]
  rw [eq_sub_of_add_eq (dAlpha_divided_anticomm i (action n q f))]
  abel

/-- The quotient map from the free algebra onto `ONH_N`. -/
def mkHom (n : ℕ) : Free n →+* Presented n := Ideal.Quotient.mk (relIdeal n)

theorem intertwines_mk_mul (w : Free n) :
    ∀ q : Presented n, Intertwines q → Intertwines (mkHom n w * q) := by
  induction w using FreeAlgebra.induction with
  | grade0 r =>
    intro q hq
    rw [algebraMap_int_eq, eq_intCast, map_intCast, ← zsmul_eq_mul]
    exact intertwines_zsmul r hq
  | grade1 x =>
    intro q hq
    cases x with
    | inl j => exact intertwines_dot_mul j hq
    | inr i => exact intertwines_crossing_mul i hq
  | add a b ha hb =>
    intro q hq
    rw [map_add, add_mul]
    exact intertwines_add (ha q hq) (hb q hq)
  | mul a b ha hb =>
    intro q hq
    rw [map_mul, mul_assoc]
    exact ha _ (hb q hq)

/-- **Ellis–Qi, Corollary 3.9** (the differential): for every `p ∈ ONH_N`, the operator of
`d(p)` on `Z_N` is the super commutator of `D = d_{Z_N}` with the operator of `p`:
`d(p) = D ∘ p - (ι ∘ p ∘ ι) ∘ D` (for `p` of parity `k`, `ι ∘ p ∘ ι = (-1)^k p`, see
`action_dONH_of_mem_parity`). -/
theorem action_dONH (p : Presented n) (f : SkewPolynomial (n+2)) :
    action n (dONH n p) f = dAlpha (zAlpha (n+2)) (action n p f) -
      parityInv (n+2) (action n p (parityInv (n+2) (dAlpha (zAlpha (n+2)) f))) := by
  obtain ⟨w, rfl⟩ : ∃ w, mkHom n w = p := Ideal.Quotient.mk_surjective p
  have h := intertwines_mk_mul w 1 intertwines_one
  rw [mul_one] at h
  exact h f

/-- A parity-`k` element of `ONH_N` acts on `OPol_N` by an operator of parity `k`:
`ι ∘ p ∘ ι = (-1)^k p`. (Derived from `d(p ∂_0) = d(p) ∂_0 + (-1)^k p` and Corollary 3.9.) -/
theorem parityInv_action_of_mem_parity {p : Presented n} {k : ZMod 2} (hp : p ∈ parity n k)
    (g : SkewPolynomial (n+2)) :
    parityInv (n+2) (action n p (parityInv (n+2) g)) = ((-1 : ℤ) ^ k.val) • action n p g := by
  set D := dAlpha (zAlpha (n+2))
  set ι := parityInv (n+2)
  have e1 := action_dONH (p * crossing n 0) g
  rw [dONH_mul hp, dONH_crossing, mul_one, neg_one_pow_mul_eq_zsmul, map_add, map_zsmul,
    LinearMap.add_apply, LinearMap.smul_apply, action_mul_apply, action_dONH p,
    action_mul_apply, action_mul_apply, action_crossing_apply, action_crossing_apply] at e1
  have key : ι (D (divided 0 g)) - divided 0 (ι (D g)) = ι g := by
    have h := congrArg ι (dAlpha_divided_anticomm (0 : Fin (n+1)) g)
    rw [map_add, parityInv_divided] at h
    rw [← h, sub_eq_add_neg]
  have e2 : ((-1 : ℤ) ^ k.val) • action n p g =
      ι (action n p (ι (D (divided 0 g)))) - ι (action n p (divided 0 (ι (D g)))) := by
    rw [← add_right_inj (D (action n p (divided 0 g)) - ι (action n p (ι (D (divided 0 g))))), e1]
    abel
  rw [e2, ← map_sub, ← map_sub, key]

/-- **Ellis–Qi, Corollary 3.9** for homogeneous elements: if `p ∈ ONH_N` has parity `k`, then
`d(p) = D ∘ p - (-1)^k p ∘ D` as operators on `Z_N`. -/
theorem action_dONH_of_mem_parity {p : Presented n} {k : ZMod 2} (hp : p ∈ parity n k)
    (f : SkewPolynomial (n+2)) :
    action n (dONH n p) f = dAlpha (zAlpha (n+2)) (action n p f) -
      ((-1 : ℤ) ^ k.val) • action n p (dAlpha (zAlpha (n+2)) f) := by
  rw [action_dONH, parityInv_action_of_mem_parity hp]

/-- The isomorphism `ONH_N ≅ END_{OΛ_N^op}(Z_N)` of Corollary 3.9: EKL's
`ONH_N ≅ End_{OΛ̃_N}(OPol_N)` (`NilHeckeEndomorphism.actionEquiv`), with the right `OΛ̃_N`-linear
maps identified with the right `OΛ_N`-linear maps of `Z_N` (`rightOsymEnd_eq`). -/
def onhEndEquiv (n : ℕ) : Presented n ≃+* rightOsymEnd (n+2) :=
  (NilHeckeEndomorphism.actionEquiv n).trans (RingEquiv.subringCongr (rightOsymEnd_eq n).symm)

@[simp] theorem onhEndEquiv_apply (p : Presented n) (f : SkewPolynomial (n+2)) :
    (onhEndEquiv n p).val f = action n p f := rfl

/-- **Ellis–Qi, Corollary 3.9**: `(ONH_N, d) ≅ END_{OΛ_N^op}(Z_N)` as dg algebras. The ring
isomorphism `onhEndEquiv` onto the right `OΛ_N`-linear endomorphisms of `Z_N` carries the
differential `dONH` (with `d(x_i) = x_i²`, `d(∂_i) = 1`) to the super commutator with the
differential of `Z_N`. -/
theorem corollary_3_9 (p : Presented n) (f : SkewPolynomial (n+2)) :
    (onhEndEquiv n (dONH n p)).val f =
      dAlpha (zAlpha (n+2)) ((onhEndEquiv n p).val f) -
        parityInv (n+2) ((onhEndEquiv n p).val (parityInv (n+2) (dAlpha (zAlpha (n+2)) f))) :=
  action_dONH p f

/-! ## Corollary 3.6 and Proposition 3.7 -/

theorem action_eqIdempotent (g : SkewPolynomial (n+2)) :
    action n (eqIdempotent n) g = ((-1 : ℤ) ^ (n+2).choose 3) •
      LongestDivided.D (n+2) (LongestDivided.staircase (n+2) * g) := by
  rw [eqIdempotent, neg_one_pow_mul_eq_zsmul, map_zsmul, LinearMap.smul_apply, action_mul_apply,
    OnhReflection.action_DElem, OnhReflection.action_staircaseElem]

theorem action_eqIdempotent_mem (g : SkewPolynomial (n+2)) :
    action n (eqIdempotent n) g ∈ OddSymmetricKernel.kernelSubring n := by
  rw [action_eqIdempotent]
  exact Subring.zsmul_mem _ (LongestKernel.D_mem_kernel n _) _

theorem action_eqIdempotent_one : action n (eqIdempotent n) 1 = 1 := by
  rw [action_eqIdempotent, mul_one, LongestDivided.D_staircase, smul_smul, neg_one_pow_mul_self,
    one_smul]

/-- `d(f q) = d(f) q + ι(f) d(q)` for a polynomial `f ∈ OPol_N ⊂ ONH_N` and any `q ∈ ONH_N`. -/
theorem dONH_polyElem_mul (f : SkewPolynomial (n+2)) (q : Presented n) :
    dONH n (OnhPolynomial.polyElem n f * q) =
      OnhPolynomial.polyElem n (d (n+2) f) * q +
        OnhPolynomial.polyElem n (parityInv (n+2) f) * dONH n q := by
  apply NilHeckeBasis.action_injective n
  apply LinearMap.ext
  intro g
  rw [action_dONH, map_add, LinearMap.add_apply, action_mul_apply, action_mul_apply,
    action_mul_apply, action_mul_apply, OnhPolynomial.action_polyElem,
    OnhPolynomial.action_polyElem, OnhPolynomial.action_polyElem, OnhPolynomial.action_polyElem,
    action_dONH q, dAlpha_mul, map_mul, mul_sub]
  abel

/-- `d` restricts to the local differential on the polynomial subring `OPol_N ⊂ ONH_N`. -/
theorem dONH_polyElem (f : SkewPolynomial (n+2)) :
    dONH n (OnhPolynomial.polyElem n f) = OnhPolynomial.polyElem n (d (n+2) f) := by
  have h := dONH_polyElem_mul f 1
  rwa [mul_one, mul_one, dONH_one, mul_zero, add_zero] at h

theorem dONH_eqIdempotent_eq :
    dONH n (eqIdempotent n) =
      OnhPolynomial.polyElem n (sAlpha (zAlpha (n+2))) * eqIdempotent n := by
  rw [dONH_eqIdempotent, sAlpha, map_sum, Finset.sum_mul]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [map_zsmul, OnhPolynomial.polyElem_generator, smul_mul_assoc, zsmul_eq_mul, zAlpha,
    Int.cast_natCast]

/-- The map `OPol_N(0,1,0,1,…) → ONH_N e_N`, `f ↦ f e_N`, of Corollary 3.6. -/
def toONH (n : ℕ) : SkewPolynomial (n+2) →+ Presented n :=
  (AddMonoidHom.mulRight (eqIdempotent n)).comp (OnhPolynomial.polyElem n).toAddMonoidHom

theorem toONH_apply (f : SkewPolynomial (n+2)) :
    toONH n f = OnhPolynomial.polyElem n f * eqIdempotent n := rfl

/-- **Ellis–Qi, Corollary 3.6 / Proposition 3.7**: `ONH_N e_N ≅ OPol_N(0,1,0,1,…)` as left dg
`OPol_N`-modules, via `f ↦ f e_N`: the map is injective, left `OPol_N`-linear, its image is the
left ideal `ONH_N e_N`, and it intertwines the differentials, `d(f e_N) = (D f) e_N` with
`D = d_{(0,1,0,1,…)}`. -/
theorem corollary_3_6 :
    Function.Injective (toONH n) ∧
    (∀ g f : SkewPolynomial (n+2),
      toONH n (g * f) = OnhPolynomial.polyElem n g * toONH n f) ∧
    (∀ a : Presented n, a * eqIdempotent n = toONH n (action n a 1)) ∧
    (∀ f : SkewPolynomial (n+2), dONH n (toONH n f) = toONH n (dAlpha (zAlpha (n+2)) f)) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro f g h
    have := congrArg (fun p => action n p 1) h
    simpa only [toONH_apply, action_mul_apply, OnhPolynomial.action_polyElem,
      action_eqIdempotent_one, mul_one] using this
  · intro g f
    rw [toONH_apply, toONH_apply, map_mul, mul_assoc]
  · intro a
    apply NilHeckeBasis.action_injective n
    apply LinearMap.ext
    intro g
    rw [toONH_apply, action_mul_apply, action_mul_apply, OnhPolynomial.action_polyElem]
    have := NilHeckeRightKernel.action_right_mul_kernel n a ⟨_, action_eqIdempotent_mem g⟩ 1
    rwa [one_mul] at this
  · intro f
    rw [toONH_apply, dONH_polyElem_mul, dONH_eqIdempotent_eq, ← mul_assoc, ← map_mul, ← add_mul,
      ← map_add, dAlpha_apply, toONH_apply]

/-! ## Proposition 3.16 (2) -/

/-- **Ellis–Qi, Proposition 3.16 (2)**: `ONH_N` is acyclic for `N ≥ 2` (here `N = n + 2`): every
cocycle `p` is the coboundary of `∂_0 p`, since `d(∂_0) = 1`. -/
theorem dONH_acyclic {p : Presented n} (hp : dONH n p = 0) : dONH n (crossing n 0 * p) = p := by
  rw [dONH_crossing_mul, hp, mul_zero, sub_zero]

end

end OddMath.Frontier.EQZn
