import OddMath.Frontier.OddLRPlacticPieri
import OddMath.Frontier.OddGrassmannSchur

/-!
# E Corollary 3.9: the ŝ_λ span a subring of ℤPl_n isomorphic to OΛ_n

Ellis, *The odd Littlewood–Richardson rule*, arXiv:1111.3932v1 ("E"), Corollary 3.9, p. 11:
"The span of the ŝ_λ in ZPl_n is a subalgebra isomorphic to OΛ_n, and this subalgebra is
taken isomorphically onto OΛ_n ⊂ OPol_n by the map w ↦ x̃^w."

E gives no proof, and the statement does not follow from Theorem 3.8 alone (the evaluation
ℤPl_n → OPol_n is far from injective).  Proof here, for `N = n+2` letters:
1. ŝ_λ satisfies the e-right Pieri rule (3.10) in ℤPl_N (`OddLRPlactic.rightPieri`).
2. The triangular elimination of the proof of Theorem 3.8 (λᵀ-lex induction, last paragraph,
   p. 11), run as a membership statement (`mem_closure_of_rightPieri`), puts every ŝ_λ in the
   subring generated by the ŝ_{(1^k)}.  Conversely (3.10) shows that the span of the ŝ_λ is
   stable under right multiplication by the ŝ_{(1^k)}.  Hence span = generated subring.
3. `toSkew` sends ŝ_λ to s^p_λ = π_N s^K_λ (Theorem 3.8, `OddLRThm38.sK_eq_sp`).  Injectivity
   on the span: `ker π_N` is spanned by the s^K_λ with more than N rows
   (`OddSymmetricLimit.piN_eq_zero_iff_mem_tallSpan`), the s^K_λ are independent
   (`OddGrassmannSchur.sK_linearIndependent`) and ŝ_λ = 0 for such λ.  Surjectivity:
   s^p_{(1^k)} = ±e_k (Lemma 3.5) and OΛ_N is generated by the e_k
   (`ElementaryGeneration.kernel_eq_elementaryClosure`).

Carriers: ℤPl_N = `OddPlactic.Plactic (n+2)`, OΛ_N = `OddSymmetricKernel.kernelSubring n`,
the evaluation w ↦ x̃^w = `PlacticEvaluation.toSkew`.
-/

namespace OddMath.Frontier.OddLRPlactic

open scoped BigOperators
open OddSymmetrizer (PartitionExponent)
open OddLRElimination (toYoung)

noncomputable section
set_option synthInstance.maxHeartbeats 200000

/-! ## Elimination as a membership statement -/

/-- The last paragraph of the proof of E Theorem 3.8, as a membership statement: a family on
partitions with at most n+2 rows satisfying the e-right Pieri rule lies in the subring
generated by its column values. -/
theorem mem_closure_of_rightPieri {n : ℕ} {R : Type*} [Ring R] (F : PartitionExponent n → R)
    (hF : OddLRElimination.RightPieri F) (α : PartitionExponent n) :
    F α ∈ Subring.closure {x | ∃ k, k ≤ n+2 ∧ x = F (OddSchurPieri.column n k)} := by
  set C := Subring.closure {x | ∃ k, k ≤ n+2 ∧ x = F (OddSchurPieri.column n k)}
  have hcol : ∀ k, k ≤ n+2 → F (OddSchurPieri.column n k) ∈ C :=
    fun k hk => Subring.subset_closure ⟨k, hk, rfl⟩
  suffices H : ∀ r, ∀ α : PartitionExponent n, α.val 0 = r → F α ∈ C from H _ α rfl
  intro r
  induction r using Nat.strong_induction_on with
  | _ r ihr =>
  rcases Nat.eq_zero_or_pos r with h0 | hpos
  · intro α hα
    rw [OddLRElimination.column_zero_eq α (hα.trans h0)]
    exact hcol 0 (Nat.zero_le _)
  suffices H : ∀ v : Lex (Fin r → Fin (n+3)), ∀ α : PartitionExponent n, α.val 0 = r →
      OddLRElimination.colVec r α = v → F α ∈ C from fun α hα => H _ α hα rfl
  intro v
  induction v using (wellFounded_gt (α := Lex (Fin r → Fin (n+3)))).induction with
  | _ v ihv =>
  intro α hα hv
  have hr : 1 ≤ α.val 0 := by omega
  have hβ : F (OddLRElimination.trunc α) ∈ C :=
    ihr (r - 1) (by omega) (OddLRElimination.trunc α) (by
      change min (α.val 0) (α.val 0 - 1) = r - 1
      rw [hα]; omega)
  have hterm : ∀ I ∈ Finset.univ.erase (OddLRElimination.topStrip α hr),
      F (OddSchurPieri.stripPartition I) ∈ C := by
    intro I hI
    have hI' := Finset.ne_of_mem_erase hI
    have hne : OddSchurPieri.stripPartition I ≠ α := by
      intro h
      apply hI'
      apply Subtype.ext
      apply OddLRElimination.increment_inj (OddLRElimination.trunc α).val
      change OddSchurPieri.increment (OddLRElimination.trunc α).val I.val =
        OddSchurPieri.increment (OddLRElimination.trunc α).val (OddLRElimination.topSet α)
      rw [OddLRElimination.increment_trunc_top α hr]
      exact congrArg Subtype.val h
    have hle : (OddSchurPieri.stripPartition I).val 0 ≤ r :=
      hα ▸ OddLRElimination.strip_le α hr I 0
    rcases lt_or_eq_of_le hle with hlt | heq
    · exact ihr _ hlt _ rfl
    · exact ihv (OddLRElimination.colVec r (OddSchurPieri.stripPartition I))
        (hv ▸ OddLRElimination.strip_lex α hα hpos I hne) _ heq rfl
  have hsum : (-1 : ℤ) ^ OddSchurPieri.lowerRows (OddLRElimination.trunc α).val
      (OddLRElimination.topSet α) • F α ∈ C := by
    rw [OddLRElimination.isolate F hF α hr]
    exact sub_mem (mul_mem hβ (hcol _ (OddLRElimination.colLen_le _ _)))
      (sum_mem fun I hI => zsmul_mem (hterm I hI) _)
  have hs : ((-1 : ℤ) ^ OddSchurPieri.lowerRows (OddLRElimination.trunc α).val
      (OddLRElimination.topSet α)) * ((-1 : ℤ) ^ OddSchurPieri.lowerRows
      (OddLRElimination.trunc α).val (OddLRElimination.topSet α)) = 1 := by
    rw [← mul_pow]; norm_num
  have he : F α = (((-1 : ℤ) ^ OddSchurPieri.lowerRows (OddLRElimination.trunc α).val
      (OddLRElimination.topSet α)) * ((-1 : ℤ) ^ OddSchurPieri.lowerRows
      (OddLRElimination.trunc α).val (OddLRElimination.topSet α))) • F α := by
    rw [hs, one_smul]
  rw [he, mul_smul]
  exact zsmul_mem hsum _

/-! ## The span of the ŝ_λ is a subring -/

/-- The ℤ-span of the ŝ_λ in ℤPl_N. -/
def shatSpan (N : ℕ) : Submodule ℤ (OddPlactic.Plactic N) :=
  Submodule.span ℤ (Set.range (shat N))

/-- The column elements ŝ_{(1^k)}, k ≤ n+2. -/
def columns (n : ℕ) : Set (OddPlactic.Plactic (n+2)) :=
  {x | ∃ k, k ≤ n+2 ∧ x = shat (n+2) (TableauExtremal.columnShape k)}

/-- The subring of ℤPl_{n+2} generated by the ŝ_{(1^k)}. -/
def shatSubring (n : ℕ) : Subring (OddPlactic.Plactic (n+2)) := Subring.closure (columns n)

theorem shat_mem_shatSpan (N : ℕ) (lam : YoungDiagram) : shat N lam ∈ shatSpan N :=
  Submodule.subset_span ⟨lam, rfl⟩

/-- (3.10): the span is stable under right multiplication by ŝ_{(1^k)}. -/
theorem mul_column_mem {N : ℕ} {x : OddPlactic.Plactic N} (hx : x ∈ shatSpan N) (k : ℕ) :
    x * shat N (TableauExtremal.columnShape k) ∈ shatSpan N := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨lam, rfl⟩ := hx
    rw [pieri_rows]
    exact sum_mem fun I _ => Submodule.smul_mem _ _ (shat_mem_shatSpan N _)
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ hx hy => rw [add_mul]; exact add_mem hx hy
  | smul c x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hx

theorem mul_mem_of_mem_shatSubring {n : ℕ} {y : OddPlactic.Plactic (n+2)}
    (hy : y ∈ shatSubring n) {x : OddPlactic.Plactic (n+2)} (hx : x ∈ shatSpan (n+2)) :
    x * y ∈ shatSpan (n+2) := by
  induction hy using Subring.closure_induction generalizing x with
  | mem y hy =>
    obtain ⟨k, -, rfl⟩ := hy
    exact mul_column_mem hx k
  | zero => rw [mul_zero]; exact zero_mem _
  | one => rw [mul_one]; exact hx
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem (hy hx) (hz hx)
  | neg y _ hy => rw [mul_neg]; exact neg_mem (hy hx)
  | mul y z _ _ hy hz => rw [← mul_assoc]; exact hz (hy hx)

theorem shat_mem_shatSubring (n : ℕ) (lam : YoungDiagram) : shat (n+2) lam ∈ shatSubring n := by
  by_cases hl : lam.colLen 0 ≤ n+2
  · have h := mem_closure_of_rightPieri _ (rightPieri n) (OddLRElimination.ofYoung (n := n) lam)
    rw [OddLRElimination.toYoung_ofYoung lam hl] at h
    refine Subring.closure_mono ?_ h
    rintro _ ⟨k, hk, rfl⟩
    exact ⟨k, hk, by rw [OddLRElimination.toYoung_column n k hk]⟩
  · rw [shat_tall (n+2) lam (YoungDiagram.mem_iff_lt_colLen.mpr (by omega))]
    exact zero_mem _

/-- The span of the ŝ_λ equals the subring generated by the ŝ_{(1^k)}. -/
theorem mem_shatSubring_iff (n : ℕ) (x : OddPlactic.Plactic (n+2)) :
    x ∈ shatSubring n ↔ x ∈ shatSpan (n+2) := by
  constructor
  · intro hx
    have h := mul_mem_of_mem_shatSubring hx (shat_mem_shatSpan (n+2) ⊥)
    rwa [shat_bot, one_mul] at h
  · intro hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨lam, rfl⟩ := hx
      exact shat_mem_shatSubring n lam
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul c x _ hx => exact zsmul_mem hx c

/-- **E Corollary 3.9, first half**: the ℤ-span of the ŝ_λ is closed under multiplication
(and contains `1 = ŝ_∅`), i.e. it is a subring of ℤPl_{n+2}. -/
theorem shatSpan_mul_mem (n : ℕ) {x y : OddPlactic.Plactic (n+2)}
    (hx : x ∈ shatSpan (n+2)) (hy : y ∈ shatSpan (n+2)) : x * y ∈ shatSpan (n+2) := by
  rw [← mem_shatSubring_iff] at hx hy ⊢
  exact mul_mem hx hy

theorem one_mem_shatSpan (N : ℕ) : (1 : OddPlactic.Plactic N) ∈ shatSpan N := by
  rw [← shat_bot N]
  exact shat_mem_shatSpan N ⊥

/-! ## The isomorphism onto OΛ_{n+2} -/

open OddLREKIdentification (sK piN)

theorem toSkew_linearCombination (N : ℕ) (c : YoungDiagram →₀ ℤ) :
    PlacticEvaluation.toSkew N (Finsupp.linearCombination ℤ (shat N) c) =
      piN N (Finsupp.linearCombination ℤ sK c) := by
  induction c using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg => rw [map_add, map_add, map_add, map_add, hf, hg]
  | single lam a =>
    rw [Finsupp.linearCombination_single, Finsupp.linearCombination_single, map_zsmul,
      map_zsmul, toSkew_shat, OddLRThm38.sK_eq_sp]

/-- The evaluation is injective on the span of the ŝ_λ. -/
theorem toSkew_injOn (N : ℕ) {x : OddPlactic.Plactic N} (hx : x ∈ shatSpan N)
    (h0 : PlacticEvaluation.toSkew N x = 0) : x = 0 := by
  obtain ⟨c, rfl⟩ := (Finsupp.mem_span_range_iff_exists_finsupp).mp hx
  rw [← Finsupp.linearCombination_apply] at h0 ⊢
  rw [toSkew_linearCombination, OddSymmetricLimit.piN_eq_zero_iff_mem_tallSpan] at h0
  have ht : OddSymmetricLimit.tallSpan N =
      Submodule.span ℤ (sK '' {lam : YoungDiagram | N < lam.colLen 0}) := by
    unfold OddSymmetricLimit.tallSpan
    congr 1
    ext x
    simp only [Set.mem_setOf_eq, Set.mem_image]
    constructor
    · rintro ⟨lam, hl, rfl⟩; exact ⟨lam, hl, rfl⟩
    · rintro ⟨lam, hl, rfl⟩; exact ⟨lam, hl, rfl⟩
  rw [ht, Finsupp.mem_span_image_iff_linearCombination] at h0
  obtain ⟨l, hl, he⟩ := h0
  have hcl : l = c := OddGrassmannSchur.sK_linearIndependent.finsuppLinearCombination_injective he
  subst hcl
  rw [Finsupp.linearCombination_apply, Finsupp.sum]
  apply Finset.sum_eq_zero
  intro lam hlam
  have htall : N < lam.colLen 0 := (Finsupp.mem_supported ℤ l).mp hl hlam
  rw [shat_tall N lam (YoungDiagram.mem_iff_lt_colLen.mpr htall), smul_zero]

theorem toSkew_mem_kernel (n : ℕ) {x : OddPlactic.Plactic (n+2)} (hx : x ∈ shatSubring n) :
    PlacticEvaluation.toSkew (n+2) x ∈ OddSymmetricKernel.kernelSubring n := by
  rw [mem_shatSubring_iff] at hx
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨lam, rfl⟩ := hx
    rw [toSkew_shat]
    exact CompleteTableauExpansion.sp_mem n lam
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul c x _ hx => rw [map_zsmul]; exact zsmul_mem hx c

/-- The evaluation w ↦ x̃^w restricted to the ŝ-subring, with values in OΛ_{n+2}. -/
def evalHom (n : ℕ) : shatSubring n →+* OddSymmetricKernel.kernelSubring n :=
  (PlacticEvaluation.toSkew (n+2)).restrict (shatSubring n) (OddSymmetricKernel.kernelSubring n)
    (fun _ hx => toSkew_mem_kernel n hx)

theorem evalHom_injective (n : ℕ) : Function.Injective (evalHom n) := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  apply Subtype.ext
  exact toSkew_injOn (n+2) ((mem_shatSubring_iff n x).mp x.2) (congrArg Subtype.val hx)

theorem evalHom_surjective (n : ℕ) : Function.Surjective (evalHom n) := by
  rintro ⟨f, hf⟩
  rw [ElementaryGeneration.kernel_eq_elementaryClosure] at hf
  have hle : ElementaryGeneration.elementaryClosure n ≤
      (shatSubring n).map (PlacticEvaluation.toSkew (n+2)) := by
    apply Subring.closure_le.mpr
    rintro _ ⟨k, _, hk, rfl⟩
    refine ⟨(-1 : ℤ) ^ k.choose 2 • shat (n+2) (TableauExtremal.columnShape k),
      zsmul_mem (Subring.subset_closure (s := columns n) ⟨k, hk, rfl⟩) _, ?_⟩
    rw [map_zsmul, toSkew_shat, OddLRElimination.sp_column, smul_smul, ← mul_pow]
    norm_num
  obtain ⟨x, hx, hxf⟩ := Subring.mem_map.mp (hle hf)
  exact ⟨⟨x, hx⟩, Subtype.ext hxf⟩

/-- **E Corollary 3.9** (N = n+2 letters): the subring of ℤPl_N spanned by the ŝ_λ
(`mem_shatSubring_iff`) is carried isomorphically onto OΛ_N ⊂ OPol_N by w ↦ x̃^w. -/
def cor39 (n : ℕ) : shatSubring n ≃+* OddSymmetricKernel.kernelSubring n :=
  RingEquiv.ofBijective (evalHom n) ⟨evalHom_injective n, evalHom_surjective n⟩

@[simp] theorem cor39_apply (n : ℕ) (x : shatSubring n) :
    (cor39 n x : OddMath.SkewPolynomial.SkewPolynomial (n+2)) =
      PlacticEvaluation.toSkew (n+2) x := rfl

/-- Under Corollary 3.9, ŝ_λ ↦ s^p_λ. -/
theorem cor39_shat (n : ℕ) (lam : YoungDiagram) :
    (cor39 n ⟨shat (n+2) lam, shat_mem_shatSubring n lam⟩ :
      OddMath.SkewPolynomial.SkewPolynomial (n+2)) = CompleteTableauExpansion.sp (n+2) lam :=
  toSkew_shat (n+2) lam

end

end OddMath.Frontier.OddLRPlactic
