import OddMath.Frontier.OddLRPlacticBasis

/-!
# The tableau basis of the odd plactic ring on the alphabet `ℤ_{>0}`

Ellis, "The odd Littlewood–Richardson rule", arXiv:1111.3932v1 ("E"), §3.1, p. 8: "Thus the set
of all Young tableaux with entries in `A` forms a basis of `ℤPl`", where `A` may be `ℤ_{>0}`
(E §2.1, p. 5: "When considering `OΛ` we will take `A = ℤ_{>0}`").

* `PlacticInf`: the ring `ℤ⟨A⟩` modulo the signed Knuth relations (3.1), for `A = ℤ_{>0}`
  (letter `a : ℕ` stands for the positive integer `a + 1`, as for `OddPlactic.Plactic n`).
* `emb n : ℤPl_n → ℤPl` (inclusion of the letters `1, …, n`) and `res n : ℤPl → ℤPl_n` (the
  letters above `n` are sent to `0`) are ring maps with `res n ∘ emb n = id` (`res_emb`).
* `Tab = Σ μ, TableauSign.PositiveTableau μ`: all semistandard Young tableaux with entries in
  `ℤ_{>0}`; `tabWord T = w_r(T)` (E (3.2)).
* `tableauBasis`: the `w_r(T)`, `T ∈ Tab`, form a `ℤ`-basis of `ℤPl`. It is compatible with the
  finite alphabets (`emb_tableauBasis`), and is deduced from `OddLRPlactic.tableauBasis`: a
  finite family of tableaux lies in some alphabet `{1, …, n}`, and every word lies in the image
  of some `emb n`.
-/

noncomputable section
open scoped BigOperators

namespace OddMath.Frontier.OddLRGaps

open TableauSign TableauRowWord TableauEvaluation

/-! ## The odd plactic ring on `ℤ_{>0}` -/

/-- The signed Knuth relation polynomials (3.1) on the letters `ℕ ≅ ℤ_{>0}`. -/
def relSetInf : Set (FreeAlgebra ℤ ℕ) :=
  {p | (∃ x y z : ℕ, x < y ∧ y ≤ z ∧
      p = FreeAlgebra.ι ℤ y * FreeAlgebra.ι ℤ z * FreeAlgebra.ι ℤ x +
        FreeAlgebra.ι ℤ y * FreeAlgebra.ι ℤ x * FreeAlgebra.ι ℤ z) ∨
    (∃ x y z : ℕ, x ≤ y ∧ y < z ∧
      p = FreeAlgebra.ι ℤ x * FreeAlgebra.ι ℤ z * FreeAlgebra.ι ℤ y +
        FreeAlgebra.ι ℤ z * FreeAlgebra.ι ℤ x * FreeAlgebra.ι ℤ y)}

/-- The two-sided ideal generated by (3.1). -/
def relIdealInf : Ideal (FreeAlgebra ℤ ℕ) := (TwoSidedIdeal.span relSetInf).asIdeal

instance relIdealInf_isTwoSided : relIdealInf.IsTwoSided :=
  inferInstanceAs ((TwoSidedIdeal.span relSetInf).asIdeal.IsTwoSided)

/-- E §3.1: the odd plactic ring `ℤPl` on the alphabet `ℤ_{>0}`. -/
def PlacticInf : Type := FreeAlgebra ℤ ℕ ⧸ relIdealInf

instance : Ring PlacticInf := Ideal.Quotient.ring relIdealInf

/-- The quotient map. -/
def mkInf : FreeAlgebra ℤ ℕ →+* PlacticInf := Ideal.Quotient.mk relIdealInf

/-- The letter `a + 1`. -/
def qInf (a : ℕ) : PlacticInf := mkInf (FreeAlgebra.ι ℤ a)

/-- Word evaluation. -/
def wordInf (w : List ℕ) : PlacticInf := (w.map qInf).prod

@[simp] theorem wordInf_nil : wordInf [] = 1 := rfl

theorem wordInf_append (u v : List ℕ) : wordInf (u ++ v) = wordInf u * wordInf v := by
  simp [wordInf]

theorem mkInf_rel {p : FreeAlgebra ℤ ℕ} (hp : p ∈ relSetInf) : mkInf p = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (TwoSidedIdeal.subset_span hp)

theorem knuthInf_left (x y z : ℕ) (hxy : x < y) (hyz : y ≤ z) :
    qInf y * qInf z * qInf x = -(qInf y * qInf x * qInf z) := by
  apply add_eq_zero_iff_eq_neg.mp
  have h := mkInf_rel (Or.inl ⟨x, y, z, hxy, hyz, rfl⟩)
  simpa only [map_add, map_mul, qInf] using h

theorem knuthInf_right (x y z : ℕ) (hxy : x ≤ y) (hyz : y < z) :
    qInf x * qInf z * qInf y = -(qInf z * qInf x * qInf y) := by
  apply add_eq_zero_iff_eq_neg.mp
  have h := mkInf_rel (Or.inr ⟨x, y, z, hxy, hyz, rfl⟩)
  simpa only [map_add, map_mul, qInf] using h

section Lift
variable {R : Type*} [Ring R]

/-- The signed Knuth relations for a letter assignment `ℕ → R`. -/
def RespectsKnuthInf (f : ℕ → R) : Prop :=
  (∀ x y z, x < y → y ≤ z → f y * f z * f x = -(f y * f x * f z)) ∧
  (∀ x y z, x ≤ y → y < z → f x * f z * f y = -(f z * f x * f y))

theorem freeEvalInf_kills (f : ℕ → R) (hf : RespectsKnuthInf f) (p : FreeAlgebra ℤ ℕ)
    (hp : p ∈ relIdealInf) : (FreeAlgebra.lift ℤ f).toRingHom p = 0 := by
  rw [relIdealInf, TwoSidedIdeal.mem_asIdeal] at hp
  induction hp using TwoSidedIdeal.span_induction with
  | mem p hp =>
      rcases hp with ⟨x, y, z, hxy, hyz, rfl⟩ | ⟨x, y, z, hxy, hyz, rfl⟩
      · simpa only [map_add, map_mul, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
          FreeAlgebra.lift_ι_apply] using (add_eq_zero_iff_eq_neg.mpr (hf.1 x y z hxy hyz))
      · simpa only [map_add, map_mul, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
          FreeAlgebra.lift_ι_apply] using (add_eq_zero_iff_eq_neg.mpr (hf.2 x y z hxy hyz))
  | zero => exact map_zero _
  | add a b ha hb ia ib => rw [map_add, ia, ib, add_zero]
  | neg a ha ia => rw [map_neg, ia, neg_zero]
  | left_absorb a b hb ib => rw [map_mul, ib, mul_zero]
  | right_absorb a b hb ib => rw [map_mul, ib, zero_mul]

/-- The universal property of `ℤPl`. -/
def liftInf (f : ℕ → R) (hf : RespectsKnuthInf f) : PlacticInf →+* R :=
  Ideal.Quotient.lift relIdealInf (FreeAlgebra.lift ℤ f).toRingHom (freeEvalInf_kills f hf)

@[simp] theorem liftInf_q (f : ℕ → R) (hf : RespectsKnuthInf f) (a : ℕ) :
    liftInf f hf (qInf a) = f a := by
  change (FreeAlgebra.lift ℤ f).toRingHom (FreeAlgebra.ι ℤ a) = f a
  simp

theorem liftInf_word (f : ℕ → R) (hf : RespectsKnuthInf f) (w : List ℕ) :
    liftInf f hf (wordInf w) = (w.map f).prod := by
  induction w with
  | nil => exact map_one _
  | cons a w ih =>
    change liftInf f hf (qInf a * wordInf w) = _
    rw [map_mul, liftInf_q, ih, List.map_cons, List.prod_cons]

end Lift

/-! ## Comparison with the finite alphabets -/

theorem qInf_respects (n : ℕ) : OddPlactic.RespectsKnuth (fun i : Fin n => qInf i.val) :=
  ⟨fun x y z hxy hyz => knuthInf_left x y z hxy hyz,
   fun x y z hxy hyz => knuthInf_right x y z hxy hyz⟩

/-- The inclusion `ℤPl_n → ℤPl` of the letters `1, …, n`. -/
def emb (n : ℕ) : OddPlactic.Plactic n →+* PlacticInf :=
  OddPlactic.lift (fun i : Fin n => qInf i.val) (qInf_respects n)

theorem emb_word (n : ℕ) (w : List (Fin n)) :
    emb n (OddPlactic.word n w) = wordInf (w.map Fin.val) := by
  rw [emb, OddPlactic.lift_word, wordInf, List.map_map]
  rfl

/-- Letters of `{1, …, n}`, the others sent to `0`. -/
def resLetter (n : ℕ) (a : ℕ) : OddPlactic.Plactic n :=
  if h : a < n then OddPlactic.q n ⟨a, h⟩ else 0

theorem resLetter_respects (n : ℕ) : RespectsKnuthInf (resLetter n) := by
  constructor
  · intro x y z hxy hyz
    by_cases hz : z < n
    · simp only [resLetter, dif_pos hz, dif_pos (show y < n by omega),
        dif_pos (show x < n by omega)]
      exact OddPlactic.knuth_left n _ _ _ (Fin.mk_lt_mk.mpr hxy) (Fin.mk_le_mk.mpr hyz)
    · simp [resLetter, dif_neg hz]
  · intro x y z hxy hyz
    by_cases hz : z < n
    · simp only [resLetter, dif_pos hz, dif_pos (show y < n by omega),
        dif_pos (show x < n by omega)]
      exact OddPlactic.knuth_right n _ _ _ (Fin.mk_le_mk.mpr hxy) (Fin.mk_lt_mk.mpr hyz)
    · simp [resLetter, dif_neg hz]

/-- The restriction `ℤPl → ℤPl_n` killing the letters above `n`. -/
def res (n : ℕ) : PlacticInf →+* OddPlactic.Plactic n := liftInf (resLetter n) (resLetter_respects n)

theorem res_emb (n : ℕ) (x : OddPlactic.Plactic n) : res n (emb n x) = x := by
  have h : (res n).comp (emb n) = RingHom.id _ := by
    apply OddPlactic.hom_ext
    intro i
    simp only [RingHom.comp_apply, emb, OddPlactic.lift_q, res, liftInf_q, resLetter,
      dif_pos i.isLt, RingHom.id_apply]
  exact congrArg (fun f : OddPlactic.Plactic n →+* OddPlactic.Plactic n => f x) h

theorem emb_injective (n : ℕ) : Function.Injective (emb n) :=
  Function.LeftInverse.injective (res_emb n)

/-- `emb n` as a `ℤ`-linear map. -/
def embLin (n : ℕ) : OddPlactic.Plactic n →ₗ[ℤ] PlacticInf := (emb n).toIntAlgHom.toLinearMap

theorem embLin_apply (n : ℕ) (x : OddPlactic.Plactic n) : embLin n x = emb n x := rfl

theorem ker_embLin (n : ℕ) : LinearMap.ker (embLin n) = ⊥ :=
  LinearMap.ker_eq_bot.mpr (emb_injective n)

/-! ## Tableaux with entries in `ℤ_{>0}` -/

/-- All semistandard Young tableaux with entries in `ℤ_{>0}`, with their shapes. -/
abbrev Tab := Σ μ : YoungDiagram, PositiveTableau μ

/-- E (3.2): the row word `w_r(T)` in `ℤPl`. -/
def tabWord (T : Tab) : PlacticInf := wordInf ((rowWord T.2).map (· - 1))

/-- Forget the alphabet bound. -/
def forget {n : ℕ} (S : OddLRPlactic.State n) : Tab := ⟨S.1, S.2.1⟩

theorem rowFinWord_val (n : ℕ) {μ : YoungDiagram} (T : PositiveTableau μ) (h : InAlphabet n T) :
    (rowFinWord n T h).map Fin.val = (rowWord T).map (· - 1) := by
  rw [rowFinWord, List.map_map]
  exact List.attach_map_val (l := rowWord T) (f := fun k => k - 1)

theorem emb_tabWord {n : ℕ} (S : OddLRPlactic.State n) :
    emb n (OddLRPlactic.tabWord n S) = tabWord (forget S) := by
  rw [OddLRPlactic.tabWord, emb_word, OddLRPlactic.rw, rowFinWord_val]
  rfl

theorem entry_le_sum {μ : YoungDiagram} (T : PositiveTableau μ) {p : ℕ × ℕ} (hp : p ∈ μ.cells) :
    T.entry p.1 p.2 ≤ (rowWord T).sum :=
  List.le_sum_of_mem (List.mem_map.mpr ⟨p, (mem_rowCells μ p).mpr hp, rfl⟩)

/-- A tableau with entries at most `n`, as a state of the finite alphabet. -/
def toState (n : ℕ) (T : Tab) (h : InAlphabet n T.2) : OddLRPlactic.State n := ⟨T.1, ⟨T.2, h⟩⟩

theorem forget_toState (n : ℕ) (T : Tab) (h : InAlphabet n T.2) : forget (toState n T h) = T := rfl

/-- Linear independence of the row words, from the finite alphabets. -/
theorem tabWord_linearIndependent : LinearIndependent ℤ tabWord := by
  classical
  rw [linearIndependent_iff_finset_linearIndependent]
  intro s
  set n := ∑ T ∈ s, (rowWord T.2).sum with hn
  have hb : ∀ T : s, InAlphabet n T.1.2 := by
    intro T p hp
    exact (entry_le_sum T.1.2 hp).trans
      (Finset.single_le_sum (f := fun T : Tab => (rowWord T.2).sum) (fun _ _ => Nat.zero_le _)
        T.2)
  let e : s → OddLRPlactic.State n := fun T => toState n T.1 (hb T)
  have he : Function.Injective e := by
    intro T T' h
    apply Subtype.ext
    have := congrArg forget h
    simpa only [e, forget_toState] using this
  have hli := ((OddLRPlactic.tabWord_linearIndependent n).comp e he).map' (embLin n)
    (ker_embLin n)
  convert hli using 1
  funext T
  simp only [Function.comp_apply, embLin_apply, e, emb_tabWord, forget_toState]

/-! ## Spanning -/

theorem wordInf_mem_span (w : List ℕ) :
    wordInf w ∈ Submodule.span ℤ (Set.range tabWord) := by
  set n := w.sum + 1
  have hw : ∀ a ∈ w, a < n := fun a ha => Nat.lt_succ_of_le (List.le_sum_of_mem ha)
  let w' : List (Fin n) := w.pmap (fun a h => ⟨a, h⟩) hw
  have hw' : w'.map Fin.val = w := by
    simp only [w', List.map_pmap]
    exact List.pmap_eq_self.mpr fun _ _ => rfl
  have hmem := Submodule.mem_map_of_mem (f := embLin n) (OddLRPlactic.word_mem_span w')
  rw [Submodule.map_span, embLin_apply, emb_word, hw'] at hmem
  refine Submodule.span_mono ?_ hmem
  rintro _ ⟨_, ⟨S, rfl⟩, rfl⟩
  exact ⟨forget S, (emb_tabWord S).symm⟩

theorem mul_mem_span {x y : PlacticInf} (hx : x ∈ Submodule.span ℤ (Set.range tabWord))
    (hy : y ∈ Submodule.span ℤ (Set.range tabWord)) :
    x * y ∈ Submodule.span ℤ (Set.range tabWord) := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨T', rfl⟩ := hy
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨T, rfl⟩ := hx
      rw [tabWord, tabWord, ← wordInf_append]
      exact wordInf_mem_span _
    | zero => rw [zero_mul]; exact zero_mem _
    | add x z _ _ hx hz => rw [add_mul]; exact add_mem hx hz
    | smul c x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hx
  | zero => rw [mul_zero]; exact zero_mem _
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
  | smul c y _ hy => rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

theorem mkInf_mem_span (p : FreeAlgebra ℤ ℕ) :
    mkInf p ∈ Submodule.span ℤ (Set.range tabWord) := by
  induction p using FreeAlgebra.induction with
  | grade0 r =>
    have h : mkInf (algebraMap ℤ _ r) = r • wordInf [] := by
      simp [wordInf_nil]
    rw [h]
    exact Submodule.smul_mem _ _ (wordInf_mem_span [])
  | grade1 a =>
    have h := wordInf_mem_span [a]
    simpa [wordInf, qInf] using h
  | mul a b ha hb => rw [map_mul]; exact mul_mem_span ha hb
  | add a b ha hb => rw [map_add]; exact add_mem ha hb

theorem span_tabWord : Submodule.span ℤ (Set.range tabWord) = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective (I := relIdealInf) x
  exact mkInf_mem_span p

/-! ## The basis -/

/-- **E §3.1, p. 8**, for the alphabet `A = ℤ_{>0}`: the row words `w_r(T)` of all semistandard
Young tableaux `T` with entries in `ℤ_{>0}` form a `ℤ`-basis of `ℤPl`. -/
def tableauBasis : Basis Tab ℤ PlacticInf :=
  Basis.mk tabWord_linearIndependent span_tabWord.ge

@[simp] theorem tableauBasis_apply (T : Tab) : tableauBasis T = tabWord T :=
  Basis.mk_apply _ _ _

/-- Compatibility with the finite alphabets `{1, …, n}`. -/
theorem emb_tableauBasis {n : ℕ} (S : OddLRPlactic.State n) :
    emb n (OddLRPlactic.tableauBasis n S) = tableauBasis (forget S) := by
  rw [OddLRPlactic.tableauBasis_apply, tableauBasis_apply, emb_tabWord]

end OddMath.Frontier.OddLRGaps
