import OddMath.Frontier.OddLREvenPlactic
import OddMath.Frontier.OddLREvenPieri
import OddMath.Frontier.OddLRExamplesLemma47

/-!
# The even plactic ring, E (4.1), and `s_λ = Σ_T x^{w_r(T)}`

Ellis, "The odd Littlewood–Richardson rule", arXiv:1111.3932v1 ("E"), §4.1, p.12 ("in the even
setting"):
* "Schur functions are generating functions for semistandard Young tableaux of a given shape,
  `s_λ = Σ_{T ∈ SSYT(λ)} x^{w_r(T)}`";
* (4.1): "for any fixed semistandard Young tableau `T₀` of shape `λ`,
  `c^λ_{μν} = #{U ∈ SSYT(μ), V ∈ SSYT(ν) : UV = T₀}`", the product taken in the even plactic ring.

Here, on the alphabet `1, …, n`:
* `PlM n`: the plactic monoid, tableaux with entries at most `n` under `S · T = S ← w_r(T)`;
  `EPl n = ℤ[PlM n]`, the even plactic ring, with the tableaux as a `ℤ`-basis by construction;
  `shatE n λ = Σ_{T ∈ SSYT(λ)} T`.
* `shatE_mul_Hk`: the even Pieri rule in `EPl n`, `ŝ_μ H_k = Σ_{ν/μ horizontal} ŝ_ν`, where
  `H_k = Σ_{w weakly increasing} P(w)` (row insertion, `TableauHorizontalPieri.aggregateEquiv`).
* `shatE_mul_mem`: the span of the `ŝ_λ` is closed under multiplication (the `ŝ_λ` lie in the
  subring generated by the `H_k`, by Kostka inversion); hence the number of factorizations
  `UV = T` depends only on the shape of `T` (`pairCountE_shape`).
* `eq_4_1`: E (4.1) for every `T₀` (entries at most `n`, `n ≥ ℓ(ν)`);
  `shatE_mul_shatE`: `ŝ_μ ŝ_ν = Σ_λ c^λ_{μν} ŝ_λ`.
* `placticHom n : Λ₁ →+* EPl n` with `s_λ ↦ Σ_{T ∈ SSYT(λ)} T` (`placticHom_sE`), and
  `evalN n : Λ₁ →+* ℤ[x₁, …, x_n]` with `s_λ ↦ Σ_{T ∈ SSYT(λ)} x^{w_r(T)}` (`evalN_sE`), where
  `x^{w}` is the monomial of the word `w`; in particular `h_k ↦ Σ_{T ∈ SSYT((k))} x^{w_r(T)}`
  (`evalN_hk`), the complete homogeneous symmetric polynomial.
-/

namespace OddMath.Frontier.OddLREven

open scoped BigOperators
open TableauSign TableauEvaluation TableauContent OddLRTableau DegreeShapes
open OddLRPlactic (State TabOf)
open TableauStripCorners
open EKClassicalPlactic (KnuthEquiv lab knuth_symm knuth_trans)

noncomputable section

attribute [local instance] Classical.propDecidable degreeFintype

/-! ## The plactic monoid -/

/-- `w_r(S ← w) ≡ w_r(S) w` in the plactic monoid. -/
theorem rw_run_knuth {n : ℕ} (S : State n) (w : List (Fin n)) :
    KnuthEquiv ((OddLRPlactic.rw (TableauWordInsertion.run n S w).1).map lab)
      ((OddLRPlactic.rw S ++ w).map lab) := by
  rw [OddLRPlactic.rw_labels, OddLRRule.rowWord_eq_readR_nrows, OddLRRule.nrows_run,
    OddLRRule.insW_readR _ (OddLRRule.nrows_valid _), ← OddLRRule.rowWord_eq_readR_nrows,
    List.map_append, OddLRPlactic.rw_labels]
  exact knuth_symm (EKClassicalPlactic.knuth_readR_P _)

/-- The plactic monoid on the letters `1, …, n`: tableaux with entries at most `n`. -/
def PlM (n : ℕ) : Type := State n

instance (n : ℕ) : Monoid (PlM n) where
  mul S T := (TableauWordInsertion.run n S (OddLRPlactic.rw T)).1
  one := OddLRPlactic.empty n
  mul_assoc S T U := by
    show (TableauWordInsertion.run n (TableauWordInsertion.run n S (OddLRPlactic.rw T)).1
      (OddLRPlactic.rw U)).1 = (TableauWordInsertion.run n S
        (OddLRPlactic.rw (TableauWordInsertion.run n T (OddLRPlactic.rw U)).1)).1
    rw [← OddLRPlactic.run_append]
    exact OddLRPlactic.run_eq_of_knuth S (knuth_symm (rw_run_knuth T _))
  one_mul S := OddLRPlactic.P_rw S
  mul_one S := by
    show (TableauWordInsertion.run n S (OddLRPlactic.rw (OddLRPlactic.empty n))).1 = S
    rw [OddLRPlactic.rw_empty]
    rfl

/-- A tableau as an element of the plactic monoid. -/
abbrev toPl {n : ℕ} (S : State n) : PlM n := S

theorem PlM.mul_def {n : ℕ} (S T : PlM n) :
    S * T = (TableauWordInsertion.run n S (OddLRPlactic.rw T)).1 := rfl

theorem PlM.one_def {n : ℕ} : (1 : PlM n) = OddLRPlactic.empty n := rfl

/-- `S · P(w) = S ← w`. -/
theorem PlM.mul_P {n : ℕ} (S : State n) (w : List (Fin n)) :
    toPl S * toPl (OddLRPlactic.P w) = toPl (TableauWordInsertion.run n S w).1 := by
  rw [PlM.mul_def]
  apply OddLRPlactic.run_eq_of_knuth
  have h := rw_run_knuth (OddLRPlactic.empty n) w
  rwa [OddLRPlactic.rw_empty, List.nil_append] at h

/-- The even plactic ring `ℤPl_n = ℤ[PlM n]`. -/
abbrev EPl (n : ℕ) : Type := MonoidAlgebra ℤ (PlM n)

/-- `ŝ_λ = Σ_{T ∈ SSYT(λ)} T ∈ ℤPl_n` (E §4.1). -/
def shatE (n : ℕ) (lam : YoungDiagram) : EPl n :=
  ∑ T : TabOf n lam, MonoidAlgebra.single (toPl ⟨lam, T⟩) (1 : ℤ)

/-- `H_k = Σ_{w weakly increasing of length k} P(w) ∈ ℤPl_n`. -/
def Hk (n k : ℕ) : EPl n :=
  ∑ w : TableauHorizontalPieri.Weak n k,
    MonoidAlgebra.single (toPl (OddLRPlactic.P (List.ofFn w.val))) (1 : ℤ)

theorem smul_apply' {n : ℕ} (a : ℤ) (f : EPl n) (S : PlM n) : (a • f) S = a * f S := rfl

theorem shatE_apply (n : ℕ) (lam : YoungDiagram) (S : PlM n) :
    shatE n lam S = if S.1 = lam then 1 else 0 := by
  obtain ⟨sig, T0⟩ := S
  unfold shatE
  rw [Finsupp.finset_sum_apply]
  by_cases h : sig = lam
  · subst h
    rw [if_pos rfl, Finset.sum_eq_single T0]
    · simp [MonoidAlgebra.single_apply]
    · intro T _ hT
      rw [MonoidAlgebra.single_apply, if_neg]
      intro he
      exact hT (eq_of_heq (Sigma.mk.inj_iff.mp he).2)
    · intro h; exact absurd (Finset.mem_univ _) h
  · rw [if_neg h]
    apply Finset.sum_eq_zero
    intro T _
    rw [MonoidAlgebra.single_apply, if_neg]
    intro he
    exact h (Sigma.mk.inj_iff.mp he).1.symm

theorem shatE_bot (n : ℕ) : shatE n ⊥ = 1 := by
  have hu : ∀ T : TabOf n ⊥, T = ⟨EKClassicalPlactic.emptyTableau,
      EKClassicalPlactic.emptyTableau_inAlphabet n⟩ := by
    intro T
    apply Subtype.ext
    apply ext_cells
    intro p hp
    exact absurd hp (by simp)
  letI : Unique (TabOf n ⊥) := ⟨⟨_⟩, hu⟩
  rw [shatE, Fintype.sum_unique, MonoidAlgebra.one_def]
  rfl

/-! ## The even Pieri rule in `ℤPl_n` -/

theorem shatE_mul_Hk (n : ℕ) (mu : YoungDiagram) (k : ℕ) :
    shatE n mu * Hk n k = ∑ nu : DegreeShape (mu.card + k),
      if Horizontal mu nu.val then shatE n nu.val else 0 := by
  unfold shatE Hk
  rw [Finset.sum_mul_sum]
  simp only [MonoidAlgebra.single_mul_single, mul_one, PlM.mul_P]
  rw [← Fintype.sum_prod_type' (f := fun (T : TabOf n mu) (w : TableauHorizontalPieri.Weak n k) =>
    MonoidAlgebra.single (toPl (TableauWordInsertion.run n ⟨mu, T⟩ (List.ofFn w.val)).1) (1 : ℤ))]
  have hpt : ∀ x : TabOf n mu × TableauHorizontalPieri.Weak n k,
      toPl (TableauWordInsertion.run n ⟨mu, x.1⟩ (List.ofFn x.2.val)).1 =
        toPl (TableauHorizontalPieri.outputMap n mu k (TableauHorizontalPieri.aggregateEquiv n mu k x)).val := by
    intro x
    have he : TableauHorizontalPieri.outputMap n mu k (TableauHorizontalPieri.aggregateEquiv n mu k x) =
        TableauStripBijection.insertionEquiv n mu k (TableauHorizontalPieri.inputMap n mu k x) :=
      (TableauHorizontalPieri.outputEquiv n mu k).apply_symm_apply _
    rw [he, TableauStripBijection.insertionEquiv_apply]
    rfl
  simp_rw [hpt]
  rw [Fintype.sum_equiv (TableauHorizontalPieri.aggregateEquiv n mu k)
    (fun x => MonoidAlgebra.single
      (toPl (TableauHorizontalPieri.outputMap n mu k (TableauHorizontalPieri.aggregateEquiv n mu k x)).val)
      (1 : ℤ))
    (fun y => MonoidAlgebra.single (toPl (TableauHorizontalPieri.outputMap n mu k y).val) (1 : ℤ))
    (fun _ => rfl)]
  rw [Fintype.sum_sigma]
  rw [← Finset.sum_filter]
  symm
  exact Finset.sum_subtype _ (by simp) _

/-- Iterated even Pieri rule in `ℤPl_n`. -/
theorem pieri_iterE (n : ℕ) (mu : YoungDiagram) (c : ℕ → ℕ) (t : ℕ) :
    shatE n mu * ((List.range t).map (fun i => Hk n (c (i + 1)))).prod =
      ∑ lam : DegreeShape (OddLRRule.mdeg mu c t), (W0 mu c t lam.val : ℤ) • shatE n lam.val := by
  induction t with
  | zero =>
    simp only [List.range_zero, List.map_nil, List.prod_nil, mul_one]
    have hd : OddLRRule.mdeg mu c 0 = mu.card := by
      simp [OddLRRule.mdeg, CompleteTableauExpansion.prefixDegree]
    symm
    rw [Fintype.sum_eq_single (α := DegreeShape (OddLRRule.mdeg mu c 0)) ⟨mu, hd.symm⟩ ?_]
    · rw [W0_zero, if_pos rfl]; simp
    · intro b hb
      rw [W0_zero, if_neg (fun h => hb (Subtype.ext h))]; simp
  | succ t ih =>
    rw [List.range_succ, List.map_append, List.prod_append, List.map_singleton, List.prod_singleton,
      ← mul_assoc, ih, Finset.sum_mul]
    simp_rw [smul_mul_assoc]
    have hstep : ∀ u : DegreeShape (OddLRRule.mdeg mu c t),
        shatE n u.val * Hk n (c (t + 1)) = ∑ w : DegreeShape (OddLRRule.mdeg mu c (t + 1)),
          if Horizontal u.val w.val then shatE n w.val else 0 := fun u => by
      rw [shatE_mul_Hk n u.val (c (t + 1))]
      exact sum_degreeShape_eq (by rw [u.property, OddLRRule.mdeg, OddLRRule.mdeg,
        CompleteTableauExpansion.prefixDegree_succ]; ring)
        (fun w => if Horizontal u.val w then shatE n w else 0)
    simp_rw [hstep, Finset.smul_sum]
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro w _
    rw [W0_succ, Nat.cast_sum, Finset.sum_smul]
    apply Finset.sum_congr rfl
    intro u _
    split_ifs <;> simp

/-- `H_{β₁} ⋯ H_{β_r} = Σ_λ K_{λβ} ŝ_λ` in `ℤPl_n`. -/
theorem prod_Hk (n d : ℕ) (β : DegreeShape d) :
    ((List.range (β.val.colLen 0)).map (fun i => Hk n (OddLRRule.rowC β.val (i + 1)))).prod =
      ∑ lam : DegreeShape d, K d lam β • shatE n lam.val := by
  have h := pieri_iterE n ⊥ (OddLRRule.rowC β.val) (β.val.colLen 0)
  rw [shatE_bot, one_mul] at h
  rw [h]
  have hm : OddLRRule.mdeg ⊥ (OddLRRule.rowC β.val) (β.val.colLen 0) = d := by
    rw [OddLRRule.mdeg_rowC]; simp [β.property]
  rw [sum_degreeShape_eq hm (fun lam => (W0 ⊥ (OddLRRule.rowC β.val) (β.val.colLen 0) lam : ℤ) •
    shatE n lam)]
  apply Finset.sum_congr rfl
  intro lam _
  rw [W0_bot, OddLRRule.prefixContent_rowC, K_apply]

/-! ## The span of the `ŝ_λ` is a subring -/

/-- The subring of `ℤPl_n` generated by the `H_k`. -/
def hRing (n : ℕ) : Subring (EPl n) := Subring.closure (Set.range (Hk n))

theorem shatE_mem_hRing (n : ℕ) (lam : YoungDiagram) : shatE n lam ∈ hRing n := by
  have e := inv_action' lam.card (fun ν : DegreeShape lam.card => shatE n ν.val) ⟨lam, rfl⟩
  simp only at e
  rw [← e]
  refine sum_mem fun β _ => zsmul_mem ?_ _
  rw [← prod_Hk]
  apply Subring.list_prod_mem
  intro x hx
  obtain ⟨i, -, rfl⟩ := List.mem_map.mp hx
  exact Subring.subset_closure ⟨_, rfl⟩

/-- The `ℤ`-span of the `ŝ_λ` in `ℤPl_n`. -/
def spanE (n : ℕ) : Submodule ℤ (EPl n) := Submodule.span ℤ (Set.range (shatE n))

theorem mul_Hk_mem {n : ℕ} {x : EPl n} (hx : x ∈ spanE n) (k : ℕ) : x * Hk n k ∈ spanE n := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨lam, rfl⟩ := hx
    rw [shatE_mul_Hk]
    exact sum_mem fun nu _ => by
      split_ifs
      · exact Submodule.subset_span ⟨_, rfl⟩
      · exact zero_mem _
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ hx hy => rw [add_mul]; exact add_mem hx hy
  | smul c x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hx

theorem mul_mem_of_hRing {n : ℕ} {y : EPl n} (hy : y ∈ hRing n) {x : EPl n} (hx : x ∈ spanE n) :
    x * y ∈ spanE n := by
  induction hy using Subring.closure_induction generalizing x with
  | mem y hy =>
    obtain ⟨k, rfl⟩ := hy
    exact mul_Hk_mem hx k
  | zero => rw [mul_zero]; exact zero_mem _
  | one => rw [mul_one]; exact hx
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem (hy hx) (hz hx)
  | neg y _ hy => rw [mul_neg]; exact neg_mem (hy hx)
  | mul y z _ _ hy hz => rw [← mul_assoc]; exact hz (hy hx)

/-- The span of the `ŝ_λ` is closed under multiplication (the even form of E Corollary 3.9). -/
theorem shatE_mul_mem (n : ℕ) {x y : EPl n} (hx : x ∈ spanE n) (hy : y ∈ spanE n) :
    x * y ∈ spanE n := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨lam, rfl⟩ := hy
    exact mul_mem_of_hRing (shatE_mem_hRing n lam) hx
  | zero => rw [mul_zero]; exact zero_mem _
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
  | smul c y _ hy => rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-! ## Factorization counts -/

/-- `#{U ∈ SSYT(μ), V ∈ SSYT(ν) : UV = S}` (entries at most `n`). -/
def pairCountE (n : ℕ) (mu nu : YoungDiagram) (S : PlM n) : ℕ :=
  (Finset.univ.filter (fun x : TabOf n mu × TabOf n nu =>
    toPl ⟨mu, x.1⟩ * toPl ⟨nu, x.2⟩ = S)).card

theorem shatE_mul_shatE_apply (n : ℕ) (mu nu : YoungDiagram) (S : PlM n) :
    (shatE n mu * shatE n nu) S = pairCountE n mu nu S := by
  unfold shatE pairCountE
  rw [Finset.sum_mul_sum]
  simp only [MonoidAlgebra.single_mul_single, mul_one]
  rw [← Fintype.sum_prod_type' (f := fun (U : TabOf n mu) (V : TabOf n nu) =>
    MonoidAlgebra.single (toPl ⟨mu, U⟩ * toPl ⟨nu, V⟩) (1 : ℤ)), Finsupp.finset_sum_apply]
  simp only [MonoidAlgebra.single_apply]
  rw [Finset.sum_boole]

/-- **Factorization lemma (Fulton, *Young Tableaux*, §5.1)**: the number of factorizations
`UV = T` in the plactic monoid depends only on the shape of `T`. -/
theorem pairCountE_shape (n : ℕ) (mu nu : YoungDiagram) {S S' : PlM n}
    (h : S.1 = S'.1) : pairCountE n mu nu S = pairCountE n mu nu S' := by
  have hm := shatE_mul_mem n (Submodule.subset_span ⟨mu, rfl⟩ : shatE n mu ∈ spanE n)
    (Submodule.subset_span ⟨nu, rfl⟩ : shatE n nu ∈ spanE n)
  obtain ⟨c, hc⟩ := (Finsupp.mem_span_range_iff_exists_finsupp).mp hm
  have key : ∀ T : PlM n, (pairCountE n mu nu T : ℤ) = c T.1 := by
    intro T
    rw [← shatE_mul_shatE_apply, ← hc, Finsupp.sum, Finsupp.finset_sum_apply]
    simp only [smul_apply', shatE_apply, mul_ite, mul_one, mul_zero]
    rw [Finset.sum_ite_eq]
    split_ifs with h
    · rfl
    · rw [Finsupp.not_mem_support_iff.mp h]
  have := (key S).trans ((congrArg c h).trans (key S').symm)
  exact_mod_cast this

/-! ## E (4.1) -/

theorem colLen_le_of_tab {n : ℕ} {lam : YoungDiagram} (T : TabOf n lam) : lam.colLen 0 ≤ n := by
  by_contra h
  push_neg at h
  have hm : (n, 0) ∈ lam := YoungDiagram.mem_iff_lt_colLen.mpr h
  have h1 := T.2 (n, 0) (by simpa using hm)
  have h2 := TableauDominance.entry_ge_row T.1 hm
  simp only at h1
  omega

theorem pairCountE_eq (n : ℕ) (mu nu : YoungDiagram) (S : State n) :
    pairCountE n mu nu (toPl S) =
      (Finset.univ.filter (fun x : TabOf n mu × TabOf n nu => OddLRPlactic.prodState x = S)).card := by
  unfold pairCountE
  congr 1
  apply Finset.filter_congr
  intro x _
  exact Iff.rfl

theorem pairCountE_canonical (n : ℕ) (lam mu nu : YoungDiagram) (hl : lam.colLen 0 ≤ n)
    (hn : nu.colLen 0 ≤ n) :
    pairCountE n mu nu (toPl (OddLRExamples.canonState n lam hl)) =
      (OddLRRule.lemma47Set lam mu nu).card := by
  have h1 := OddLRExamples.sum_filter_eq_lemma47Set n lam mu nu hl hn (fun _ => (1 : ℤ))
  simp only [Finset.sum_const, nsmul_eq_mul, mul_one, Nat.cast_inj] at h1
  rw [← h1, pairCountE_eq]
  symm
  apply Finset.card_nbij (fun U => (U, OddLRExamples.canonTab n nu hn))
  · intro U hU
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, (Finset.mem_filter.mp hU).2⟩
  · intro U _ U' _ h
    exact congrArg Prod.fst h
  · intro x hx
    have hx' := (Finset.mem_filter.mp (Finset.mem_coe.mp hx)).2
    have h2 : x.2 = OddLRExamples.canonTab n nu hn :=
      Subtype.ext (OddLRExamples.eq_canonical_of_prodState hl x hx')
    refine ⟨x.1, Finset.mem_coe.mpr (Finset.mem_filter.mpr ⟨Finset.mem_univ _, ?_⟩),
      Prod.ext rfl h2.symm⟩
    rw [← h2]
    exact hx'

/-- **E (4.1)**: for every tableau `T₀` of shape `λ` (entries at most `n`, `n ≥ ℓ(ν)`),
`c^λ_{μν} = #{U ∈ SSYT(μ), V ∈ SSYT(ν) : UV = T₀}`, the product taken in the even plactic
monoid on `1, …, n`. -/
theorem eq_4_1 (n : ℕ) (lam mu nu : YoungDiagram) (T0 : TabOf n lam) (hn : nu.colLen 0 ≤ n) :
    evenLR lam mu nu = pairCountE n mu nu (toPl ⟨lam, T0⟩) := by
  have hl := colLen_le_of_tab T0
  rw [pairCountE_shape n mu nu (S := toPl ⟨lam, T0⟩)
    (S' := toPl (OddLRExamples.canonState n lam hl)) rfl,
    pairCountE_canonical n lam mu nu hl hn, evenLR_eq_card_lemma47Set]

theorem pairCountE_of_card (n : ℕ) (mu nu : YoungDiagram) (S : PlM n)
    (h : S.1.card ≠ mu.card + nu.card) : pairCountE n mu nu S = 0 := by
  rw [pairCountE, Finset.card_eq_zero, Finset.filter_eq_empty_iff]
  intro x _ hx
  apply h
  rw [← hx]
  exact OddLRPlactic.prodState_card x

theorem evenLR_eq_zero_of_not_le {lam mu nu : YoungDiagram} (h : ¬ nu ≤ lam) :
    evenLR lam mu nu = 0 := by
  have he : lrTableaux lam nu mu = ∅ := by
    rw [Finset.eq_empty_iff_forall_not_mem]
    intro S _
    exact h S.sub
  rw [thm_4_1, card_lrTableaux_comm, he]
  rfl

/-- `ŝ_μ ŝ_ν = Σ_λ c^λ_{μν} ŝ_λ` in `ℤPl_n`, every `n`. -/
theorem shatE_mul_shatE (n : ℕ) (mu nu : YoungDiagram) :
    shatE n mu * shatE n nu =
      ∑ lam : DegreeShape (mu.card + nu.card), evenLR lam.val mu nu • shatE n lam.val := by
  ext S
  rw [shatE_mul_shatE_apply, Finsupp.finset_sum_apply]
  simp only [smul_apply', shatE_apply, mul_ite, mul_one, mul_zero]
  by_cases hd : S.1.card = mu.card + nu.card
  · rw [Fintype.sum_eq_single (α := DegreeShape (mu.card + nu.card)) ⟨S.1, hd⟩ ?_]
    · rw [if_pos rfl]
      by_cases hn : nu.colLen 0 ≤ n
      · exact (eq_4_1 n S.1 mu nu S.2 hn).symm
      · have hl := colLen_le_of_tab S.2
        have hnle : ¬ nu ≤ S.1 := by
          intro hle
          apply hn
          by_contra hc'
          have hm : (n, 0) ∈ nu := YoungDiagram.mem_iff_lt_colLen.mpr (by omega)
          have := YoungDiagram.mem_iff_lt_colLen.mp (hle hm)
          omega
        rw [evenLR_eq_zero_of_not_le hnle, Nat.cast_eq_zero, pairCountE, Finset.card_eq_zero,
          Finset.filter_eq_empty_iff]
        intro x _ _
        exact hn (colLen_le_of_tab x.2)
    · intro lam hne
      rw [if_neg (fun he => hne (Subtype.ext he.symm))]
  · rw [pairCountE_of_card n mu nu S hd, Nat.cast_zero]
    symm
    apply Finset.sum_eq_zero
    intro lam _
    rw [if_neg (fun he => hd (by rw [he]; exact lam.property))]

/-! ## `s_λ ↦ Σ_T T` and `s_λ ↦ Σ_T x^{w_r(T)}` -/

theorem hE_bot : hE ⊥ = 1 := by
  have h : (⊥ : YoungDiagram).rowLens = [] := by
    unfold YoungDiagram.rowLens; rw [colLen_bot]; rfl
  rw [hE, h]
  simp [EKGeneralQ.hWord]

theorem sE_bot : sE ⊥ = 1 := by
  have h := hE_expand 0 ⟨⊥, rfl⟩
  rw [Fintype.sum_eq_single (α := DegreeShape 0) ⟨⊥, rfl⟩] at h
  · rw [hE_bot, show K 0 ⟨⊥, rfl⟩ ⟨⊥, rfl⟩ = 1 from EKGeneralQ.kostkaMat_diag 0 _, one_smul] at h
    exact h.symm
  · intro ν hν
    exfalso
    apply hν
    apply Subtype.ext
    apply YoungDiagram.ext
    have : ν.val.cells.card = 0 := ν.property
    rw [Finset.card_eq_zero] at this
    rw [this]
    rfl

/-- `s_λ ↦ ŝ_λ`, as a linear map `Λ₁ → ℤPl_n`. -/
def placticLin (n : ℕ) : Sym →ₗ[ℤ] EPl n := sBasisE.constr ℤ (shatE n)

theorem placticLin_sE (n : ℕ) (lam : YoungDiagram) : placticLin n (sE lam) = shatE n lam := by
  rw [← sBasisE_apply, placticLin, Basis.constr_basis]

theorem placticLin_mul (n : ℕ) (x y : Sym) :
    placticLin n (x * y) = placticLin n x * placticLin n y := by
  have h : (LinearMap.mul ℤ Sym).compr₂ (placticLin n) =
      (LinearMap.mul ℤ (EPl n)).compl₁₂ (placticLin n) (placticLin n) := by
    apply LinearMap.ext_basis sBasisE sBasisE
    intro mu nu
    simp only [LinearMap.compr₂_apply, LinearMap.mul_apply', LinearMap.compl₁₂_apply,
      sBasisE_apply]
    rw [sE_mul_sE, map_sum, placticLin_sE, placticLin_sE, shatE_mul_shatE]
    apply Finset.sum_congr rfl
    intro lam _
    rw [map_zsmul, placticLin_sE, thm_4_1]
  exact congrArg (fun B => B x y) h

/-- **`s_λ = Σ_{T ∈ SSYT(λ)} T` in the even plactic ring** (E §4.1): the ring homomorphism
`Λ₁ → ℤPl_n` sending `s_λ` to `ŝ_λ`. -/
def placticHom (n : ℕ) : Sym →+* EPl n where
  toFun := placticLin n
  map_one' := by rw [← sE_bot, placticLin_sE, shatE_bot]
  map_mul' := placticLin_mul n
  map_zero' := (placticLin n).map_zero
  map_add' := (placticLin n).map_add

theorem placticHom_sE (n : ℕ) (lam : YoungDiagram) : placticHom n (sE lam) = shatE n lam :=
  placticLin_sE n lam

theorem perm_of_map_lab {n : ℕ} {u v : List (Fin n)} (h : (u.map lab).Perm (v.map lab)) :
    u.Perm v := by
  rw [List.perm_iff_count] at h ⊢
  intro a
  have := h (lab a)
  rwa [List.count_map_of_injective _ _ (EKClassicalPlactic.lab_injective n),
    List.count_map_of_injective _ _ (EKClassicalPlactic.lab_injective n)] at this

/-- The monomial `x^{w_r(S)} = x_{w₁} ⋯ x_{w_m}` of the row word of a tableau: a monoid
homomorphism from the plactic monoid to `ℤ[x₁, …, x_n]` (`x_{i+1} = X i`). -/
def xw (n : ℕ) : PlM n →* MvPolynomial (Fin n) ℤ where
  toFun S := ((OddLRPlactic.rw S).map MvPolynomial.X).prod
  map_one' := by
    show ((OddLRPlactic.rw (OddLRPlactic.empty n)).map MvPolynomial.X).prod = 1
    rw [OddLRPlactic.rw_empty]; rfl
  map_mul' S T := by
    show ((OddLRPlactic.rw (TableauWordInsertion.run n S (OddLRPlactic.rw T)).1).map
      MvPolynomial.X).prod = ((OddLRPlactic.rw S).map MvPolynomial.X).prod *
        ((OddLRPlactic.rw T).map MvPolynomial.X).prod
    rw [← List.prod_append, ← List.map_append]
    exact ((perm_of_map_lab (EKClassicalPlactic.perm_of_knuth (rw_run_knuth S _))).map _).prod_eq

/-- The specialization `Λ₁ → ℤ[x₁, …, x_n]`: `ℤPl_n → ℤ[x₁, …, x_n]` (commuting the letters)
after `placticHom`. -/
def evalN (n : ℕ) : Sym →+* MvPolynomial (Fin n) ℤ :=
  (MonoidAlgebra.lift ℤ (PlM n) (MvPolynomial (Fin n) ℤ) (xw n)).toRingHom.comp (placticHom n)

/-- **E §4.1, p.12: `s_λ = Σ_{T ∈ SSYT(λ)} x^{w_r(T)}`**, in `ℤ[x₁, …, x_n]` (tableaux with
entries at most `n`). -/
theorem evalN_sE (n : ℕ) (lam : YoungDiagram) :
    evalN n (sE lam) =
      ∑ T : TabOf n lam, ((rowFinWord n T.1 T.2).map MvPolynomial.X).prod := by
  rw [evalN, RingHom.comp_apply, placticHom_sE, shatE, map_sum]
  apply Finset.sum_congr rfl
  intro T _
  rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, MonoidAlgebra.lift_single, one_smul]
  rfl

/-- `h_k ↦ Σ_{T ∈ SSYT((k))} x^{w_r(T)}`, the complete homogeneous symmetric polynomial of
degree `k` in `x₁, …, x_n`. -/
theorem evalN_hk (n k : ℕ) :
    evalN n (hk k) = ∑ T : TabOf n (TableauExtremal.rowShape k),
      ((rowFinWord n T.1 T.2).map MvPolynomial.X).prod := by
  rw [hk_eq_sE_row, evalN_sE]

end

end OddMath.Frontier.OddLREven
