import OddMath.Frontier.OddLRThm38
import OddMath.Frontier.ElementaryBasis
import OddMath.Frontier.EKProp310
import OddMath.Frontier.EKAutomorphisms

/-!
# OΛ_a as a quotient of OΛ, and OΛ as a graded inverse limit

EKL arXiv:1111.1320v1, §5, p. 44.

Carriers: `Q = EKRadicalQuotient.Q` is OΛ (EK, over ℤ); `piN N : Q →+* SkewPolynomial N` is the
map OΛ → OΛ_N (`h_k ↦ h_k`, `ε_k ↦ ε_k`); OΛ_a for `a = n+2` is
`OddSymmetricKernel.kernelSubring n`; `sK λ` is EK's `s^H_λ` ((5.10), p. 46).

* `piN_eq_zero_iff_mem_elemIdeal`: for every `N`, `ker π_N` is the two-sided ideal generated by the
  `ε_m`, `m > N`; with `piA_surjective` this gives (5.3), `OΛ_a ≅ OΛ/⟨ε_m : m > a⟩`
  (`equation_5_3`).
* `transition`: OΛ_{a+1} → OΛ_a, `ε_j ↦ ε_j` (`j ≤ a`), `ε_{a+1} ↦ 0`, compatible with the maps
  from OΛ (`transition_piA`) and unique with these values (`transition_unique`).
* Graded inverse limit: `π_a` is surjective in every degree and bijective in degrees `d ≤ a`
  (`degreeEquiv`); every compatible family of degree-`d` elements lifts uniquely
  (`inverse_limit`).
* `piN_eq_zero_iff_mem_tallSpan`: `ker π_N` is also the ℤ-span of the `s^H_λ` with more than `N`
  rows; the images of the `s^H_λ` with at most `N` rows are linearly independent in each degree
  (`piN_schurK_degree_linearIndependent`).
-/

noncomputable section
set_option synthInstance.maxHeartbeats 200000
open scoped BigOperators

namespace OddMath.Frontier.OddSymmetricLimit

open OddMath.SkewPolynomial
open EKRadicalQuotient (Q)
open OddLREKIdentification (piN sK schurK)
open DegreeShapes (DegreeShape)
open ElementaryGeneration (Leading Exp columnExponent elementaryWord)
open EKPartitionSpanning (ePartition hPartition)

/-! ## Linear independence from distinct unit leading terms -/

/-- Distinct lexicographic leading exponents with unit leading coefficients give ℤ-linear
independence. -/
theorem linearIndependent_of_leading {N : ℕ} {ι : Type*} (v : ι → SkewPolynomial N)
    (L : ι → Exp N) (hL : Function.Injective L)
    (hv : ∀ i, ∃ c : ℤ, c * c = 1 ∧ Leading (v i) (L i) c) :
    LinearIndependent ℤ v := by
  classical
  apply linearIndependent_iff'.mpr
  intro s z hz i hi
  by_contra hzi
  let t := s.filter (fun a => z a ≠ 0)
  have ht : t.Nonempty := ⟨i, Finset.mem_filter.mpr ⟨hi, hzi⟩⟩
  obtain ⟨a, ha, hmax⟩ := Finset.exists_max_image t (fun a => toLex (L a)) ht
  obtain ⟨c, hc, hl⟩ := hv a
  have hc0 : c ≠ 0 := by intro h; rw [h] at hc; norm_num at hc
  have he := congrArg (fun f : SkewPolynomial N => f (L a)) hz
  simp only [Finsupp.coe_zero, Pi.zero_apply] at he
  rw [Finsupp.finset_sum_apply, Finset.sum_eq_single a] at he
  · rw [Finsupp.smul_apply, hl.2, smul_eq_mul] at he
    exact (Finset.mem_filter.mp ha).2 ((mul_eq_zero.mp he).resolve_right hc0)
  · intro b hb hba
    by_cases hzb : z b = 0
    · rw [hzb, zero_smul]; rfl
    · have hle := hmax b (Finset.mem_filter.mpr ⟨hb, hzb⟩)
      obtain ⟨_, _, hbl⟩ := hv b
      have hzero : v b (L a) = 0 := by
        by_contra hne
        have hab := hbl.1 (L a) hne
        exact hba (hL (toLex.injective (le_antisymm hle hab)))
      rw [Finsupp.smul_apply, hzero, smul_zero]
  · intro has
    exact False.elim (has (Finset.mem_filter.mp ha).1)

/-! ## Column exponents of row-length words -/

theorem columnExponent_apply {N : ℕ} (w : List ℕ) (j : Fin N) :
    columnExponent N w j = (w.map (fun k => if j.val < k then 1 else 0)).sum := by
  induction w with
  | nil => simp [columnExponent]
  | cons k w ih =>
    simp only [columnExponent, List.map_cons, List.sum_cons, Pi.add_apply] at ih ⊢
    rw [ih]
    rfl

theorem sum_range_ite_lt (c m : ℕ) (h : m ≤ c) :
    ((List.range c).map (fun i => if i < m then 1 else 0)).sum = m := by
  induction c with
  | zero => simp only [List.range_zero, List.map_nil, List.sum_nil]; omega
  | succ c ih =>
    rw [List.range_succ, List.map_append, List.sum_append]
    by_cases hm : m ≤ c
    · rw [ih hm]; simp; omega
    · have hmc : m = c + 1 := by omega
      subst hmc
      have h2 : ((List.range c).map (fun i => if i < c + 1 then 1 else 0)) =
          (List.range c).map (fun _ => 1) := by
        apply List.map_congr_left
        intro i hi
        rw [List.mem_range] at hi
        rw [if_pos (by omega)]
      rw [h2]
      simp

theorem columnExponent_rowLens {N : ℕ} (μ : YoungDiagram) (j : Fin N) :
    columnExponent N μ.rowLens j = μ.colLen j.val := by
  rw [columnExponent_apply, YoungDiagram.rowLens, List.map_map]
  have h : ((fun k => if j.val < k then 1 else 0) ∘ μ.rowLen) =
      (fun i => if i < μ.colLen j.val then 1 else 0) := by
    funext i
    simp only [Function.comp_apply]
    have : j.val < μ.rowLen i ↔ i < μ.colLen j.val := by
      rw [← YoungDiagram.mem_iff_lt_rowLen, ← YoungDiagram.mem_iff_lt_colLen]
    by_cases hi : i < μ.colLen j.val
    · rw [if_pos (this.mpr hi), if_pos hi]
    · rw [if_neg (fun h => hi (this.mp h)), if_neg hi]
  rw [h]
  exact sum_range_ite_lt _ _ (μ.colLen_anti 0 j.val (Nat.zero_le _))

theorem colLen_eq_zero_of_rowLen_le {μ : YoungDiagram} {N j : ℕ} (hμ : μ.rowLen 0 ≤ N)
    (hj : N ≤ j) : μ.colLen j = 0 := by
  by_contra h
  have h0 : (0, j) ∈ μ := YoungDiagram.mem_iff_lt_colLen.mpr (Nat.pos_of_ne_zero h)
  have := YoungDiagram.mem_iff_lt_rowLen.mp h0
  omega

theorem diagram_ext_colLen {μ ν : YoungDiagram} (h : ∀ j, μ.colLen j = ν.colLen j) : μ = ν := by
  apply YoungDiagram.ext
  ext ⟨a, b⟩
  change (a, b) ∈ μ ↔ (a, b) ∈ ν
  rw [YoungDiagram.mem_iff_lt_colLen, YoungDiagram.mem_iff_lt_colLen, h b]

theorem columnExponent_rowLens_injective (N : ℕ) :
    Function.Injective (fun μ : {μ : YoungDiagram // μ.rowLen 0 ≤ N} =>
      columnExponent N μ.1.rowLens) := by
  intro μ ν h
  apply Subtype.ext
  apply diagram_ext_colLen
  intro j
  by_cases hj : j < N
  · have := congrFun h ⟨j, hj⟩
    simp only [columnExponent_rowLens] at this
    exact this
  · rw [colLen_eq_zero_of_rowLen_le μ.2 (by omega), colLen_eq_zero_of_rowLen_le ν.2 (by omega)]

theorem le_rowLen_zero_of_mem_rowLens {μ : YoungDiagram} {k : ℕ} (hk : k ∈ μ.rowLens) :
    k ≤ μ.rowLen 0 := by
  rw [YoungDiagram.rowLens, List.mem_map] at hk
  obtain ⟨i, _, rfl⟩ := hk
  exact μ.rowLen_anti 0 i (Nat.zero_le _)

theorem rowLen_zero_mem_rowLens {μ : YoungDiagram} (h : 0 < μ.rowLen 0) :
    μ.rowLen 0 ∈ μ.rowLens := by
  rw [YoungDiagram.rowLens, List.mem_map]
  refine ⟨0, List.mem_range.mpr ?_, rfl⟩
  rw [← YoungDiagram.mem_iff_lt_colLen, YoungDiagram.mem_iff_lt_rowLen]
  exact h

theorem rowLen_zero_le_card (μ : YoungDiagram) : μ.rowLen 0 ≤ μ.card := by
  rw [YoungDiagram.rowLen_eq_card]
  exact Finset.card_le_card (Finset.filter_subset _ _)

/-! ## π_N on the elementary basis -/

theorem piN_ePartition (N : ℕ) (μ : YoungDiagram) :
    piN N (ePartition μ) = elementaryWord N μ.rowLens := by
  simp only [ePartition, elementaryWord, map_list_prod, List.map_map, Function.comp_def,
    OddLREKIdentification.piN_e]

theorem piN_ePartition_eq_zero {N : ℕ} {μ : YoungDiagram} (h : N < μ.rowLen 0) :
    piN N (ePartition μ) = 0 := by
  rw [piN_ePartition, elementaryWord]
  apply List.prod_eq_zero
  rw [List.mem_map]
  exact ⟨μ.rowLen 0, rowLen_zero_mem_rowLens (by omega),
    FiniteCompleteElementary.elementaryPoly_eq_zero_of_lt h⟩

/-- The `π_N(ε_μ)` with `μ₁ ≤ N` are linearly independent (distinct unit leading terms). -/
theorem piN_ePartition_linearIndependent (N : ℕ) :
    LinearIndependent ℤ (fun μ : {μ : YoungDiagram // μ.rowLen 0 ≤ N} =>
      piN N (ePartition μ.1)) := by
  apply linearIndependent_of_leading _ _ (columnExponent_rowLens_injective N)
  intro μ
  simp only [piN_ePartition]
  exact ElementaryBasis.word_leading N μ.1.rowLens
    (fun k hk => (le_rowLen_zero_of_mem_rowLens hk).trans μ.2)

theorem piN_ePartition_linearIndependent' (N : ℕ) {ι : Type*} (f : ι → YoungDiagram)
    (hf : Function.Injective f) (hN : ∀ i, (f i).rowLen 0 ≤ N) :
    LinearIndependent ℤ (fun i => piN N (ePartition (f i))) := by
  apply linearIndependent_of_leading _ (fun i => columnExponent N (f i).rowLens)
  · intro i j h
    exact hf (congrArg Subtype.val (columnExponent_rowLens_injective N
      (a₁ := ⟨f i, hN i⟩) (a₂ := ⟨f j, hN j⟩) h))
  · intro i
    simp only [piN_ePartition]
    exact ElementaryBasis.word_leading N (f i).rowLens
      (fun k hk => (le_rowLen_zero_of_mem_rowLens hk).trans (hN i))

/-! ## ker π_N and (5.3) -/

/-- ℤ-span of the `ε_μ` with `μ₁ > N`. -/
def wideSpan (N : ℕ) : Submodule ℤ Q :=
  Submodule.span ℤ {x | ∃ μ : YoungDiagram, N < μ.rowLen 0 ∧ x = ePartition μ}

/-- The two-sided ideal `⟨ε_m : m > N⟩` of OΛ. -/
def elemIdeal (N : ℕ) : TwoSidedIdeal Q :=
  TwoSidedIdeal.span {x | ∃ m, N < m ∧ x = EKElementaryQuotient.e m}

theorem list_prod_mem {R : Type*} [Ring R] (I : TwoSidedIdeal R) {l : List R} {x : R}
    (hx : x ∈ l) (hI : x ∈ I) : l.prod ∈ I := by
  induction l with
  | nil => simp at hx
  | cons y l ih =>
    rw [List.prod_cons]
    rcases List.mem_cons.mp hx with rfl | hx
    · exact I.mul_mem_right _ _ hI
    · exact I.mul_mem_left _ _ (ih hx)

theorem ePartition_mem_elemIdeal {N : ℕ} {μ : YoungDiagram} (h : N < μ.rowLen 0) :
    ePartition μ ∈ elemIdeal N :=
  list_prod_mem _ (List.mem_map.mpr ⟨μ.rowLen 0, rowLen_zero_mem_rowLens (by omega), rfl⟩)
    (TwoSidedIdeal.subset_span ⟨_, h, rfl⟩)

theorem mem_elemIdeal_of_mem_wideSpan {N : ℕ} {x : Q} (hx : x ∈ wideSpan N) :
    x ∈ elemIdeal N := by
  induction hx using Submodule.span_induction with
  | mem x hx => obtain ⟨μ, hμ, rfl⟩ := hx; exact ePartition_mem_elemIdeal hμ
  | zero => exact zero_mem _
  | add x y _ _ hx hy => exact add_mem hx hy
  | smul z x _ hx => exact (elemIdeal N).zsmul_mem z hx

theorem piN_eq_zero_of_mem_elemIdeal {N : ℕ} {x : Q} (hx : x ∈ elemIdeal N) :
    piN N x = 0 := by
  have hle : elemIdeal N ≤ TwoSidedIdeal.ker (piN N) := by
    apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨m, hm, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker, OddLREKIdentification.piN_e]
    exact FiniteCompleteElementary.elementaryPoly_eq_zero_of_lt hm
  exact (TwoSidedIdeal.mem_ker _).mp (hle hx)

theorem eBasis_expand (x : Q) :
    x = ∑ μ ∈ (EKIntegralBases.eBasis.repr x).support,
      EKIntegralBases.eBasis.repr x μ • ePartition μ := by
  conv_lhs => rw [← EKIntegralBases.eBasis.linearCombination_repr x]
  rw [Finsupp.linearCombination_apply, Finsupp.sum]
  simp only [EKIntegralBases.eBasis_apply]

theorem mem_wideSpan_of_piN_eq_zero {N : ℕ} {x : Q} (hx : piN N x = 0) : x ∈ wideSpan N := by
  classical
  set c := EKIntegralBases.eBasis.repr x
  have hsum := eBasis_expand x
  rw [hsum, ← Finset.sum_filter_add_sum_filter_not c.support (fun μ => μ.rowLen 0 ≤ N)] at hx ⊢
  have hwide : ∑ μ ∈ c.support.filter (fun μ => ¬ μ.rowLen 0 ≤ N), c μ • ePartition μ ∈
      wideSpan N := by
    apply Submodule.sum_mem
    intro μ hμ
    rw [Finset.mem_filter] at hμ
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨μ, by omega, rfl⟩)
  have h1 : piN N (∑ μ ∈ c.support.filter (fun μ => ¬ μ.rowLen 0 ≤ N), c μ • ePartition μ) = 0 := by
    rw [map_sum]
    apply Finset.sum_eq_zero
    intro μ hμ
    rw [Finset.mem_filter] at hμ
    rw [map_zsmul, piN_ePartition_eq_zero (by omega), smul_zero]
  rw [map_add, h1, add_zero, map_sum] at hx
  have hli := linearIndependent_iff'.mp (piN_ePartition_linearIndependent N)
    (c.support.subtype (fun μ => μ.rowLen 0 ≤ N)) (fun μ => c μ.1) (by
      rw [Finset.sum_subtype_eq_sum_filter (f := fun μ => c μ • piN N (ePartition μ))]
      simpa only [map_zsmul] using hx)
  have hz : ∑ μ ∈ c.support.filter (fun μ => μ.rowLen 0 ≤ N), c μ • ePartition μ = 0 := by
    apply Finset.sum_eq_zero
    intro μ hμ
    rw [Finset.mem_filter] at hμ
    have h0 := hli ⟨μ, hμ.2⟩ (Finset.mem_subtype.mpr hμ.1)
    simp only at h0
    rw [h0, zero_smul]
  rw [hz, zero_add]
  exact hwide

/-- `ker(OΛ → OΛ_N) = ⟨ε_m : m > N⟩`, for every `N` (EKL p. 44, (5.3)). -/
theorem piN_eq_zero_iff_mem_elemIdeal (N : ℕ) (x : Q) : piN N x = 0 ↔ x ∈ elemIdeal N :=
  ⟨fun h => mem_elemIdeal_of_mem_wideSpan (mem_wideSpan_of_piN_eq_zero h),
    piN_eq_zero_of_mem_elemIdeal⟩

theorem ker_piN (N : ℕ) : TwoSidedIdeal.ker (piN N) = elemIdeal N := by
  ext x
  rw [TwoSidedIdeal.mem_ker]
  exact piN_eq_zero_iff_mem_elemIdeal N x

theorem piN_eq_zero_iff_mem_wideSpan (N : ℕ) (x : Q) : piN N x = 0 ↔ x ∈ wideSpan N :=
  ⟨mem_wideSpan_of_piN_eq_zero,
    fun h => piN_eq_zero_of_mem_elemIdeal (mem_elemIdeal_of_mem_wideSpan h)⟩

theorem elemIdeal_mono {M N : ℕ} (h : M ≤ N) : elemIdeal N ≤ elemIdeal M :=
  TwoSidedIdeal.span_mono (by rintro _ ⟨m, hm, rfl⟩; exact ⟨m, by omega, rfl⟩)

/-- OΛ → OΛ_a, `a = n+2`, with values in the odd symmetric polynomials. -/
def piA (n : ℕ) : Q →+* OddSymmetricKernel.kernelSubring n :=
  (piN (n+2)).codRestrict _ (OddLREKIdentification.piN_mem_kernel n)

@[simp] theorem piA_coe (n : ℕ) (x : Q) : (piA n x : SkewPolynomial (n+2)) = piN (n+2) x := rfl

theorem piA_surjective (n : ℕ) : Function.Surjective (piA n) := by
  rintro ⟨f, hf⟩
  rw [ElementaryGeneration.kernel_eq_elementaryClosure] at hf
  have hle : ElementaryGeneration.elementaryClosure n ≤ (piN (n+2)).range := by
    apply Subring.closure_le.mpr
    rintro _ ⟨k, _, _, rfl⟩
    exact ⟨EKElementaryQuotient.e k, OddLREKIdentification.piN_e _ _⟩
  obtain ⟨x, hx⟩ := hle hf
  exact ⟨x, Subtype.ext hx⟩

theorem piA_eq_zero_iff (n : ℕ) (x : Q) : piA n x = 0 ↔ x ∈ elemIdeal (n+2) := by
  rw [← piN_eq_zero_iff_mem_elemIdeal, ← piA_coe]
  exact ⟨fun h => by rw [h]; rfl, fun h => Subtype.ext h⟩

/-- **EKL (5.3)** (p. 44): `OΛ_a ≅ OΛ/⟨ε_m : m > a⟩`, `a = n+2`, induced by `π_a`. -/
def equation_5_3 (n : ℕ) :
    Q ⧸ (elemIdeal (n+2)).asIdeal ≃+* OddSymmetricKernel.kernelSubring n :=
  RingEquiv.ofBijective
    (Ideal.Quotient.lift _ (piA n) (fun x hx =>
      (piA_eq_zero_iff n x).mpr (TwoSidedIdeal.mem_asIdeal.mp hx)))
    ⟨by
      rw [injective_iff_map_eq_zero]
      intro y hy
      obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective y
      rw [Ideal.Quotient.lift_mk] at hy
      apply Ideal.Quotient.eq_zero_iff_mem.mpr
      exact TwoSidedIdeal.mem_asIdeal.mpr ((piA_eq_zero_iff n x).mp hy),
     by
      intro y
      obtain ⟨x, rfl⟩ := piA_surjective n y
      exact ⟨Ideal.Quotient.mk _ x, Ideal.Quotient.lift_mk _ _ _⟩⟩

@[simp] theorem equation_5_3_mk (n : ℕ) (x : Q) :
    equation_5_3 n (Ideal.Quotient.mk _ x) = piA n x := rfl

theorem equation_5_3_symm_piA (n : ℕ) (x : Q) :
    (equation_5_3 n).symm (piA n x) = Ideal.Quotient.mk _ x := by
  apply (equation_5_3 n).injective
  rw [RingEquiv.apply_symm_apply, equation_5_3_mk]

/-! ## Transition maps and the inverse limit (p. 44) -/

/-- The transition map OΛ_{a+1} → OΛ_a (`a = n+2`), `ε_j ↦ ε_j` for `j ≤ a`, `ε_{a+1} ↦ 0`. -/
def transition (n : ℕ) :
    OddSymmetricKernel.kernelSubring (n+1) →+* OddSymmetricKernel.kernelSubring n :=
  (Ideal.Quotient.lift (elemIdeal (n+1+2)).asIdeal (piA n) (fun x hx =>
    (piA_eq_zero_iff n x).mpr (elemIdeal_mono (M := n+2) (N := n+1+2) (by omega)
      (TwoSidedIdeal.mem_asIdeal.mp hx)))).comp
    (equation_5_3 (n+1)).symm.toRingHom

/-- Compatibility with the maps from OΛ. -/
@[simp] theorem transition_piA (n : ℕ) (x : Q) : transition n (piA (n+1) x) = piA n x := by
  simp only [transition, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom,
    equation_5_3_symm_piA, Ideal.Quotient.lift_mk]

theorem piA_e (n k : ℕ) :
    piA n (EKElementaryQuotient.e k) =
      ⟨FiniteCompleteElementary.elementaryPoly (n+2) k, OddSymmetricKernel.elementary_mem n k⟩ :=
  Subtype.ext (OddLREKIdentification.piN_e _ _)

/-- `ε_j ↦ ε_j` for every `j` (the right side is `0` for `j > a`). -/
theorem transition_elementary (n j : ℕ) :
    transition n ⟨FiniteCompleteElementary.elementaryPoly (n+1+2) j,
        OddSymmetricKernel.elementary_mem (n+1) j⟩ =
      ⟨FiniteCompleteElementary.elementaryPoly (n+2) j, OddSymmetricKernel.elementary_mem n j⟩ := by
  rw [← piA_e, ← piA_e, transition_piA]

/-- `ε_{a+1} ↦ 0`. -/
theorem transition_elementary_top (n : ℕ) :
    transition n ⟨FiniteCompleteElementary.elementaryPoly (n+1+2) (n+3),
        OddSymmetricKernel.elementary_mem (n+1) (n+3)⟩ = 0 := by
  rw [transition_elementary]
  exact Subtype.ext (FiniteCompleteElementary.elementaryPoly_eq_zero_of_lt (by omega))

/-- The transition map is the unique ring map with `ε_j ↦ ε_j`. -/
theorem transition_unique (n : ℕ)
    (f : OddSymmetricKernel.kernelSubring (n+1) →+* OddSymmetricKernel.kernelSubring n)
    (hf : ∀ j, f ⟨FiniteCompleteElementary.elementaryPoly (n+1+2) j,
        OddSymmetricKernel.elementary_mem (n+1) j⟩ =
      ⟨FiniteCompleteElementary.elementaryPoly (n+2) j, OddSymmetricKernel.elementary_mem n j⟩) :
    f = transition n := by
  have hc : (f.comp (piA (n+1))).comp EKPresentation.psi1.toRingHom =
      ((transition n).comp (piA (n+1))).comp EKPresentation.psi1.toRingHom := by
    apply EKAutomorphisms.hom_ext_h
    intro k
    simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom,
      EKPresentation.psi1_h, piA_e, hf, transition_elementary]
  have hc2 : f.comp (piA (n+1)) = (transition n).comp (piA (n+1)) := by
    refine RingHom.ext fun x => ?_
    have := congrArg (fun g : Q →+* _ => g (EKPresentation.psi1.symm x)) hc
    simpa only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom,
      RingEquiv.apply_symm_apply] using this
  refine RingHom.ext fun y => ?_
  obtain ⟨x, rfl⟩ := piA_surjective (n+1) y
  exact congrArg (fun g : Q →+* _ => g x) hc2

/-! ## Degree pieces and the graded inverse limit -/

theorem degree_e_expand (d : ℕ) (x : EKIntegralBases.degreePiece d) :
    letI := DegreeShapes.degreeFintype d
    (x : Q) = ∑ μ, (EKIntegralBases.degreeEBasis d).repr x μ • ePartition μ.val := by
  letI := DegreeShapes.degreeFintype d
  have h := congrArg (fun z : EKIntegralBases.degreePiece d => (z : Q))
    ((EKIntegralBases.degreeEBasis d).sum_repr x)
  simp only [Submodule.coe_sum, Submodule.coe_smul, EKIntegralBases.degreeEBasis_apply] at h
  exact h.symm

/-- `π_N` maps the degree-`d` piece of OΛ to polynomials homogeneous of degree `d`. -/
theorem piN_homogeneous (N d : ℕ) (x : EKIntegralBases.degreePiece d) :
    ElementaryBasis.Homogeneous d (piN N x) := by
  classical
  letI := DegreeShapes.degreeFintype d
  rw [degree_e_expand d x, map_sum]
  apply ElementaryBasis.homogeneous_sum
  intro μ _
  rw [map_zsmul, piN_ePartition]
  apply ElementaryBasis.homogeneous_smul
  have := ElementaryBasis.word_homogeneous N μ.val.rowLens
  rwa [EKIntegralBases.rowLens_sum, μ.property] at this

/-- `π_a` on degree-`d` pieces, `a = n+2`. -/
def degreeMap (n d : ℕ) :
    EKIntegralBases.degreePiece d →ₗ[ℤ] ElementaryBasis.degreePiece n d where
  toFun x := ⟨piN (n+2) x, OddLREKIdentification.piN_mem_kernel n x, piN_homogeneous (n+2) d x⟩
  map_add' x y := Subtype.ext (by simp)
  map_smul' z x := Subtype.ext (by simp)

@[simp] theorem degreeMap_coe (n d : ℕ) (x : EKIntegralBases.degreePiece d) :
    (degreeMap n d x : SkewPolynomial (n+2)) = piN (n+2) x := rfl

/-- `π_a` is surjective in every degree. -/
theorem degreeMap_surjective (n d : ℕ) : Function.Surjective (degreeMap n d) := by
  rw [← LinearMap.range_eq_top, eq_top_iff, ← (ElementaryBasis.gradedBasis n d).span_eq,
    Submodule.span_le]
  rintro _ ⟨α, rfl⟩
  have hw : (ElementaryBasis.columns α.1).Sorted (· ≥ ·) := ElementaryBasis.columns_descending α.1
  have hpos : ∀ x ∈ ElementaryBasis.columns α.1, 0 < x :=
    fun x hx => (ElementaryBasis.columns_valid α.1 x hx).1
  have hμr : (YoungDiagram.ofRowLens _ hw).rowLens = ElementaryBasis.columns α.1 :=
    YoungDiagram.rowLens_ofRowLens_eq_self hpos
  have hμc : (YoungDiagram.ofRowLens _ hw).card = d := by
    rw [← EKIntegralBases.rowLens_sum, hμr, ElementaryBasis.columns_sum α.1 α.2.1, α.2.2]
  refine ⟨⟨ePartition (YoungDiagram.ofRowLens _ hw), ?_⟩, ?_⟩
  · have := (EKIntegralBases.degreeEBasis d ⟨_, hμc⟩).2
    rwa [EKIntegralBases.degreeEBasis_apply] at this
  · apply Subtype.ext
    rw [degreeMap_coe, ElementaryBasis.gradedBasis_apply, piN_ePartition, hμr]

/-- `π_a` is injective in degrees `d ≤ a`. -/
theorem degreeMap_injective (n d : ℕ) (hd : d ≤ n+2) : Function.Injective (degreeMap n d) := by
  classical
  letI := DegreeShapes.degreeFintype d
  rw [injective_iff_map_eq_zero]
  intro x hx
  have h0 : piN (n+2) x = 0 := congrArg Subtype.val hx
  rw [degree_e_expand d x, map_sum] at h0
  have hli := (piN_ePartition_linearIndependent (n+2)).comp
    (fun μ : DegreeShape d =>
      (⟨μ.val, (rowLen_zero_le_card _).trans (by rw [μ.property]; exact hd)⟩ :
        {μ : YoungDiagram // μ.rowLen 0 ≤ n+2}))
    (fun a b h => Subtype.ext (by simpa only [Subtype.mk.injEq] using h))
  have hc := Fintype.linearIndependent_iff.mp hli
    (fun μ => (EKIntegralBases.degreeEBasis d).repr x μ)
    (by simpa only [map_zsmul, Function.comp_apply] using h0)
  apply (EKIntegralBases.degreeEBasis d).repr.injective
  ext μ
  simp only [hc μ, map_zero, Finsupp.coe_zero, Pi.zero_apply]

/-- In degree `d ≤ a`, `π_a : OΛ_d → (OΛ_a)_d` is an isomorphism (EKL p. 44). -/
def degreeEquiv (n d : ℕ) (hd : d ≤ n+2) :
    EKIntegralBases.degreePiece d ≃ₗ[ℤ] ElementaryBasis.degreePiece n d :=
  LinearEquiv.ofBijective (degreeMap n d) ⟨degreeMap_injective n d hd, degreeMap_surjective n d⟩

theorem transition_degree_injective (n d : ℕ) (hd : d ≤ n+2)
    (u v : ElementaryBasis.degreePiece (n+1) d)
    (h : transition n ⟨u.1, u.2.1⟩ = transition n ⟨v.1, v.2.1⟩) : u = v := by
  obtain ⟨yu, rfl⟩ := degreeMap_surjective (n+1) d u
  obtain ⟨yv, rfl⟩ := degreeMap_surjective (n+1) d v
  have eu : (⟨(degreeMap (n+1) d yu).1, (degreeMap (n+1) d yu).2.1⟩ :
      OddSymmetricKernel.kernelSubring (n+1)) = piA (n+1) yu := rfl
  have ev : (⟨(degreeMap (n+1) d yv).1, (degreeMap (n+1) d yv).2.1⟩ :
      OddSymmetricKernel.kernelSubring (n+1)) = piA (n+1) yv := rfl
  rw [eu, ev, transition_piA, transition_piA] at h
  have : degreeMap n d yu = degreeMap n d yv :=
    Subtype.ext (show piN (n+2) yu = piN (n+2) yv from congrArg Subtype.val h)
  rw [degreeMap_injective n d hd this]

/-- **Graded inverse limit** (EKL p. 44): in each degree `d`, OΛ is the inverse limit of the
`(OΛ_a)_d` along the transition maps. Every compatible family `(x_a)_{a ≥ 2}` of degree-`d`
elements comes from a unique degree-`d` element of OΛ. -/
theorem inverse_limit (d : ℕ) (x : ∀ n, ElementaryBasis.degreePiece n d)
    (hx : ∀ n, (transition n ⟨(x (n+1)).1, (x (n+1)).2.1⟩ : SkewPolynomial (n+2)) = (x n).1) :
    ∃! y : EKIntegralBases.degreePiece d, ∀ n, piN (n+2) y = (x n).1 := by
  let y := (degreeEquiv d d (by omega)).symm (x d)
  have hy : degreeMap d d y = x d := (degreeEquiv d d (by omega)).apply_symm_apply (x d)
  have down : ∀ n, piN (n+1+2) y = (x (n+1)).1 → piN (n+2) y = (x n).1 := by
    intro n h
    rw [← hx n]
    have e1 : (⟨(x (n+1)).1, (x (n+1)).2.1⟩ : OddSymmetricKernel.kernelSubring (n+1)) =
        piA (n+1) y := Subtype.ext h.symm
    rw [e1, transition_piA]
    rfl
  have up : ∀ n, d ≤ n → piN (n+2) y = (x n).1 → piN (n+1+2) y = (x (n+1)).1 := by
    intro n hn h
    have := transition_degree_injective n d (by omega) (degreeMap (n+1) d y) (x (n+1)) (by
      have e1 : (⟨(degreeMap (n+1) d y).1, (degreeMap (n+1) d y).2.1⟩ :
          OddSymmetricKernel.kernelSubring (n+1)) = piA (n+1) y := rfl
      rw [e1, transition_piA]
      exact Subtype.ext ((hx n).trans h.symm).symm)
    exact congrArg Subtype.val this
  have hd : piN (d+2) y = (x d).1 := congrArg Subtype.val hy
  have hge : ∀ n, d ≤ n → piN (n+2) y = (x n).1 := by
    intro n hn
    induction n, hn using Nat.le_induction with
    | base => exact hd
    | succ n hn ih => exact up n hn ih
  have hle : ∀ k, piN (d - k + 2) y = (x (d - k)).1 := by
    intro k
    induction k with
    | zero => exact hd
    | succ k ih =>
      by_cases hk : d ≤ k
      · have e : d - (k+1) = d - k := by omega
        rw [e]; exact ih
      · have e : d - k = d - (k+1) + 1 := by omega
        rw [e] at ih
        exact down _ ih
  refine ⟨y, fun n => ?_, fun y' hy' => ?_⟩
  · by_cases hn : d ≤ n
    · exact hge n hn
    · have e : n = d - (d - n) := by omega
      rw [e]; exact hle _
  · apply degreeMap_injective d d (by omega)
    apply Subtype.ext
    rw [degreeMap_coe, degreeMap_coe, hy' d, hd]

/-! ## Odd Schur functions: bases and kernels -/

/-- A family spanning the same ℤ-module as a finite linearly independent family of the same
cardinality is linearly independent (surjective endomorphisms of `ℤ^r` are injective). -/
theorem linearIndependent_of_span_eq {M : Type*} [AddCommGroup M] {ι κ : Type*} [Fintype ι]
    [Fintype κ] {v : ι → M} (hv : LinearIndependent ℤ v) (u : κ → M)
    (hcard : Fintype.card κ = Fintype.card ι)
    (hspan : Submodule.span ℤ (Set.range u) = Submodule.span ℤ (Set.range v)) :
    LinearIndependent ℤ u := by
  classical
  let P := Submodule.span ℤ (Set.range v)
  let b : Basis ι ℤ P := Basis.span hv
  haveI : Module.Finite ℤ P := Module.Finite.of_basis b
  have hu : ∀ k, u k ∈ P := fun k => by
    show u k ∈ Submodule.span ℤ (Set.range v)
    rw [← hspan]
    exact Submodule.subset_span ⟨k, rfl⟩
  let f : (κ → ℤ) →ₗ[ℤ] P :=
    { toFun := fun c => ∑ k, c k • (⟨u k, hu k⟩ : P)
      map_add' := fun c c' => by simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
      map_smul' := fun z c => by
        simp only [Pi.smul_apply, smul_eq_mul, mul_smul, Finset.smul_sum, RingHom.id_apply] }
  have hf : Function.Surjective f := by
    intro p
    have hp : (p : M) ∈ Submodule.span ℤ (Set.range u) := by rw [hspan]; exact p.2
    obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℤ).mp hp
    refine ⟨c, Subtype.ext ?_⟩
    simp only [f, LinearMap.coe_mk, AddHom.coe_mk, Submodule.coe_sum, Submodule.coe_smul]
    exact hc
  let e : ι ≃ κ := Fintype.equivOfCardEq hcard.symm
  let i : (κ → ℤ) →ₗ[ℤ] P :=
    b.equivFun.symm.toLinearMap ∘ₗ (LinearEquiv.funCongrLeft ℤ ℤ e).toLinearMap
  have hi : Function.Injective i :=
    b.equivFun.symm.injective.comp (LinearEquiv.funCongrLeft ℤ ℤ e).injective
  have hinj := OrzechProperty.injective_of_surjective_of_injective i f hi hf
  rw [Fintype.linearIndependent_iff]
  intro g hg k
  have : f g = f 0 := by
    apply Subtype.ext
    simp only [f, LinearMap.coe_mk, AddHom.coe_mk, Submodule.coe_sum, Submodule.coe_smul,
      Pi.zero_apply, zero_smul, Finset.sum_const_zero, ZeroMemClass.coe_zero]
    exact hg
  exact congrFun (hinj this) k

attribute [local instance] DegreeShapes.degreeFintype

/-- The `s^H_λ`, `λ ⊢ d`, are linearly independent (EKL p. 46: an integral basis). -/
theorem schurK_linearIndependent (d : ℕ) : LinearIndependent ℤ (schurK d) := by
  apply linearIndependent_of_span_eq (EKIntegralBases.degreeHBasis d).linearIndependent _ rfl
  rw [(EKIntegralBases.degreeHBasis d).span_eq]
  exact EKProp310.schur_span d

/-- The odd Schur basis `{s^H_λ : λ ⊢ d}` of the degree-`d` piece of OΛ. -/
def schurBasis (d : ℕ) : Basis (DegreeShape d) ℤ (EKIntegralBases.degreePiece d) :=
  Basis.mk (schurK_linearIndependent d) (EKProp310.schur_span d).ge

@[simp] theorem schurBasis_apply (d : ℕ) (lam : DegreeShape d) :
    schurBasis d lam = schurK d lam :=
  Basis.mk_apply _ _ _

theorem sK_eq (d : ℕ) (lam : DegreeShape d) : sK lam.val = (schurK d lam : Q) := by
  obtain ⟨l, rfl⟩ := lam
  rfl

theorem sK_mem (lam : YoungDiagram) : sK lam ∈ EKIntegralBases.degreePiece lam.card :=
  (schurK lam.card ⟨lam, rfl⟩).2

theorem schur_expand (d : ℕ) (x : EKIntegralBases.degreePiece d) :
    (x : Q) = ∑ lam, (schurBasis d).repr x lam • (schurK d lam : Q) := by
  have h := congrArg (fun z : EKIntegralBases.degreePiece d => (z : Q))
    ((schurBasis d).sum_repr x)
  simp only [Submodule.coe_sum, Submodule.coe_smul, schurBasis_apply] at h
  exact h.symm

theorem piN_schurK_tall {N d : ℕ} {lam : DegreeShape d} (h : N < lam.val.colLen 0) :
    piN N (schurK d lam : Q) = 0 := by
  rw [← sK_eq]
  exact (OddLRThm38.thm38_tall N lam.val h).1

/-- Transposition matches `λ₁ ≤ N` with `ℓ(λ) ≤ N`. -/
def transposeBounded (N d : ℕ) :
    {lam : DegreeShape d // lam.val.colLen 0 ≤ N} ≃ {μ : DegreeShape d // μ.val.rowLen 0 ≤ N} :=
  (EKDualBases.transposeShape d).subtypeEquiv (fun lam => by
    change _ ↔ lam.val.transpose.rowLen 0 ≤ N
    rw [YoungDiagram.rowLen_transpose])

open Classical in
/-- In degree `d`, the images in `N` odd variables of the `s^H_λ` with at most `N` rows are
linearly independent. -/
theorem piN_schurK_degree_linearIndependent (N d : ℕ) :
    LinearIndependent ℤ (fun lam : {lam : DegreeShape d // lam.val.colLen 0 ≤ N} =>
      piN N (schurK d lam.1 : Q)) := by
  have hv := piN_ePartition_linearIndependent' N
    (fun μ : {μ : DegreeShape d // μ.val.rowLen 0 ≤ N} => μ.1.val)
    (fun a b h => Subtype.ext (Subtype.ext h)) (fun μ => μ.2)
  refine linearIndependent_of_span_eq hv _ (Fintype.card_congr (transposeBounded N d)) ?_
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨lam, rfl⟩
    change piN N ((schurK d lam.1 : EKIntegralBases.degreePiece d) : Q) ∈ _
    rw [degree_e_expand d (schurK d lam.1), map_sum]
    apply Submodule.sum_mem
    intro μ _
    rw [map_zsmul]
    apply Submodule.smul_mem
    by_cases hμ : μ.val.rowLen 0 ≤ N
    · exact Submodule.subset_span ⟨⟨μ, hμ⟩, rfl⟩
    · rw [piN_ePartition_eq_zero (by omega)]
      exact zero_mem _
  · rw [Submodule.span_le]
    rintro _ ⟨μ, rfl⟩
    have hmem : ePartition μ.1.val ∈ EKIntegralBases.degreePiece d := by
      have := (EKIntegralBases.degreeEBasis d μ.1).2
      rwa [EKIntegralBases.degreeEBasis_apply] at this
    change piN N ((⟨_, hmem⟩ : EKIntegralBases.degreePiece d) : Q) ∈ _
    rw [schur_expand d ⟨_, hmem⟩, map_sum]
    apply Submodule.sum_mem
    intro lam _
    rw [map_zsmul]
    apply Submodule.smul_mem
    by_cases hl : lam.val.colLen 0 ≤ N
    · exact Submodule.subset_span ⟨⟨lam, hl⟩, rfl⟩
    · rw [piN_schurK_tall (by omega)]
      exact zero_mem _

/-- ℤ-span of the `s^H_λ` with more than `N` rows. -/
def tallSpan (N : ℕ) : Submodule ℤ Q :=
  Submodule.span ℤ {x | ∃ lam : YoungDiagram, N < lam.colLen 0 ∧ x = sK lam}

open Classical in
theorem ePartition_mem_tallSpan {N : ℕ} {μ : YoungDiagram} (h : N < μ.rowLen 0) :
    ePartition μ ∈ tallSpan N := by
  set d := μ.card
  have hmem : ePartition μ ∈ EKIntegralBases.degreePiece d := by
    have := (EKIntegralBases.degreeEBasis d ⟨μ, rfl⟩).2
    rwa [EKIntegralBases.degreeEBasis_apply] at this
  set x : EKIntegralBases.degreePiece d := ⟨_, hmem⟩
  set c := (schurBasis d).repr x
  have hx : ePartition μ = ∑ lam, c lam • (schurK d lam : Q) := schur_expand d x
  have h0 := piN_ePartition_eq_zero h
  rw [hx, ← Finset.sum_filter_add_sum_filter_not Finset.univ (fun lam => lam.val.colLen 0 ≤ N)]
    at h0 ⊢
  have htall : piN N (∑ lam ∈ Finset.univ.filter (fun lam : DegreeShape d =>
      ¬ lam.val.colLen 0 ≤ N), c lam • (schurK d lam : Q)) = 0 := by
    rw [map_sum]
    apply Finset.sum_eq_zero
    intro lam hlam
    rw [Finset.mem_filter] at hlam
    rw [map_zsmul, piN_schurK_tall (by omega), smul_zero]
  rw [map_add, htall, add_zero, map_sum] at h0
  have hli := linearIndependent_iff'.mp (piN_schurK_degree_linearIndependent N d)
    (Finset.univ.subtype (fun lam : DegreeShape d => lam.val.colLen 0 ≤ N)) (fun lam => c lam.1) (by
      rw [Finset.sum_subtype_eq_sum_filter (f := fun lam => c lam • piN N (schurK d lam : Q))]
      simpa only [map_zsmul] using h0)
  have hz : ∑ lam ∈ Finset.univ.filter (fun lam : DegreeShape d => lam.val.colLen 0 ≤ N),
      c lam • (schurK d lam : Q) = 0 := by
    apply Finset.sum_eq_zero
    intro lam hlam
    rw [Finset.mem_filter] at hlam
    have h1 := hli ⟨lam, hlam.2⟩ (Finset.mem_subtype.mpr (Finset.mem_univ _))
    simp only at h1
    rw [h1, zero_smul]
  rw [hz, zero_add]
  apply Submodule.sum_mem
  intro lam hlam
  rw [Finset.mem_filter] at hlam
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨lam.val, by omega, (sK_eq d lam).symm⟩)

/-- `ker(OΛ → OΛ_N)` is the ℤ-span of the `s^H_λ` with more than `N` rows, for every `N`. -/
theorem piN_eq_zero_iff_mem_tallSpan (N : ℕ) (x : Q) : piN N x = 0 ↔ x ∈ tallSpan N := by
  constructor
  · intro h
    have hw := mem_wideSpan_of_piN_eq_zero h
    clear h
    induction hw using Submodule.span_induction with
    | mem x hx => obtain ⟨μ, hμ, rfl⟩ := hx; exact ePartition_mem_tallSpan hμ
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul z x _ hx => exact Submodule.smul_mem _ z hx
  · intro h
    induction h using Submodule.span_induction with
    | mem x hx => obtain ⟨lam, hl, rfl⟩ := hx; exact (OddLRThm38.thm38_tall N lam hl).1
    | zero => exact map_zero _
    | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
    | smul z x _ hx => rw [map_zsmul, hx, smul_zero]

theorem mem_elemIdeal_iff_mem_tallSpan (N : ℕ) (x : Q) : x ∈ elemIdeal N ↔ x ∈ tallSpan N :=
  (piN_eq_zero_iff_mem_elemIdeal N x).symm.trans (piN_eq_zero_iff_mem_tallSpan N x)

end OddMath.Frontier.OddSymmetricLimit
