import OddMath.Frontier.NilHeckeBasis

/-! # Strand windows in the odd nilHecke ring

EKL arXiv:1111.1320v1 §3.2.4 and §4.1: the tensor-product inclusions
`ONH_a ⊗ ONH_b ⊂ ONH_{a+b}` place diagrams on disjoint blocks of strands, and diagrams on
disjoint strands supercommute with respect to the super-degree (p. 29, text before (3.44)).

* `windowHom m n p h : Presented m →+* Presented n` shifts every strand index by `p`,
  realizing rank `m+2` on the strands `[p, p+m+2)` of rank `n+2`.  It is constructed on the
  free algebra and shown to kill each of the seven relator families.
* `IsGen l r` singles out the generators supported in the strand window `[l, r)`: dots `x_j`
  with `l ≤ j < r` and crossings `∂_i` with `l ≤ i`, `i+1 < r`.
* `Homog l r k` is the ℤ-module of products of `k` such generators; for `r ≤ l'`,
  `Homog l r k u → Homog l' r' k' v → u*v = (-1)^(k*k') * (v*u)` (`Homog.supercomm`).
* `SupportedEven`, `SupportedOdd` (spans of even/odd homogeneous pieces) and `Supported`
  (the subring generated by the window) give the parity statements used downstream.

Rank is `n+2`; products act rightmost first.
-/

namespace OddMath.Frontier.OnhWindow
open NilHeckeAction NilCoxeterWords NilHeckeBasis
open OddMath.SkewPolynomial (SkewPolynomial generator)
noncomputable section

/-! ## Generator extensionality -/

/-- Ring homs out of the presented ring agree once they agree on dots and crossings. -/
theorem presented_hom_ext {m : ℕ} {R : Type*} [Ring R] {f g : Presented m →+* R}
    (hd : ∀ j, f (dot m j) = g (dot m j)) (hc : ∀ i, f (crossing m i) = g (crossing m i)) :
    f = g := by
  apply Ideal.Quotient.ringHom_ext
  apply RingHom.ext
  intro w
  induction w using FreeAlgebra.induction with
  | grade0 r => simp
  | grade1 x =>
      cases x with
      | inl j => exact hd j
      | inr i => exact hc i
  | mul a b ha hb => simpa only [map_mul] using congrArg₂ (· * ·) ha hb
  | add a b ha hb => simpa only [map_add] using congrArg₂ (· + ·) ha hb

private theorem relator_zero {n : ℕ} (r : Free n) (h : Relator n r) :
    Ideal.Quotient.mk (relIdeal n) r = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  change r ∈ (relTwoSided n).asIdeal
  rw [TwoSidedIdeal.mem_asIdeal]
  exact TwoSidedIdeal.subset_span h

/-! ## The window homomorphism -/

/-- The shifted crossing index. -/
def shiftIndex {m n p : ℕ} (h : p + (m+2) ≤ n+2) (i : Fin (m+1)) : Fin (n+1) :=
  ⟨i.val + p, by have := i.isLt; omega⟩

@[simp] theorem shiftIndex_val {m n p : ℕ} (h : p + (m+2) ≤ n+2) (i : Fin (m+1)) :
    (shiftIndex h i).val = i.val + p := rfl

section Window
variable (m n p : ℕ) (h : p + (m+2) ≤ n+2)

/-- Images of the generators under the shift by `p`. -/
def windowGen : Gen m → Presented n
  | Sum.inl j => dot n ⟨j.val + p, by have := j.isLt; omega⟩
  | Sum.inr i => crossing n ⟨i.val + p, by have := i.isLt; omega⟩

/-- The shift on the free algebra. -/
def windowFree : Free m →ₐ[ℤ] Presented n := FreeAlgebra.lift ℤ (windowGen m n p h)

variable {m n p h}

theorem windowFree_dot (j : Fin (m+2)) :
    windowFree m n p h (dotFree m j) = dot n ⟨j.val + p, by have := j.isLt; omega⟩ := by
  simp [windowFree, dotFree, windowGen]

theorem windowFree_crossing (i : Fin (m+1)) :
    windowFree m n p h (crossingFree m i) =
      crossing n ⟨i.val + p, by have := i.isLt; omega⟩ := by
  simp [windowFree, crossingFree, windowGen]

/-- Each of the seven relator families is sent to the corresponding shifted relation. -/
theorem windowFree_relator (r : Free m) (hr : Relator m r) : windowFree m n p h r = 0 := by
  cases hr with
  | square i =>
      rw [map_mul, windowFree_crossing]
      exact crossing_square _
  | braid i j hij =>
      rw [map_sub, map_mul, map_mul, map_mul, map_mul, windowFree_crossing, windowFree_crossing,
        sub_eq_zero]
      exact crossing_braid _ _ (by simp only; omega)
  | dots i j hij =>
      rw [map_add, map_mul, map_mul, windowFree_dot, windowFree_dot]
      refine dots_anticommute _ _ ?_
      intro he
      exact hij (Fin.ext (by simpa using congrArg Fin.val he))
  | distant i j hij =>
      rw [map_add, map_mul, map_mul, windowFree_crossing, windowFree_crossing]
      exact add_eq_zero_iff_eq_neg.mpr (crossing_distant _ _ (by simp only; omega))
  | mixedRight i =>
      have hi := i.isLt
      set I : Fin (n+1) := ⟨i.val + p, by omega⟩
      rw [map_sub, map_add, map_mul, map_mul, map_one, windowFree_dot, windowFree_dot,
        windowFree_crossing]
      rw [show (⟨i.castSucc.val + p, _⟩ : Fin (n+2)) = I.castSucc from Fin.ext rfl,
        show (⟨i.succ.val + p, _⟩ : Fin (n+2)) = I.succ from
          Fin.ext (by simp only [Fin.val_succ, I]; omega),
        crossing_dot_right]
      abel
  | mixedLeft i =>
      have hi := i.isLt
      set I : Fin (n+1) := ⟨i.val + p, by omega⟩
      rw [map_sub, map_add, map_mul, map_mul, map_one, windowFree_dot, windowFree_dot,
        windowFree_crossing]
      rw [show (⟨i.castSucc.val + p, _⟩ : Fin (n+2)) = I.castSucc from Fin.ext rfl,
        show (⟨i.succ.val + p, _⟩ : Fin (n+2)) = I.succ from
          Fin.ext (by simp only [Fin.val_succ, I]; omega),
        crossing_dot_left]
      abel
  | spectator i j hl hr =>
      rw [map_add, map_mul, map_mul, windowFree_dot, windowFree_crossing,
        crossing_dot_other, add_neg_cancel]
      · intro he
        apply hl
        exact Fin.ext (by simpa using congrArg Fin.val he)
      · intro he
        apply hr
        exact Fin.ext (by simp only [Fin.val_succ, Fin.ext_iff] at he ⊢; omega)

theorem windowFree_ideal (r : Free m) (hr : r ∈ relIdeal m) : windowFree m n p h r = 0 := by
  rw [relIdeal, relTwoSided, TwoSidedIdeal.mem_asIdeal] at hr
  induction hr using TwoSidedIdeal.span_induction with
  | mem r hr => exact windowFree_relator r hr
  | zero => exact map_zero _
  | add a b _ _ ha hb => rw [map_add, ha, hb, add_zero]
  | neg a _ ha => rw [map_neg, ha, neg_zero]
  | left_absorb a b _ hb => rw [map_mul, hb, mul_zero]
  | right_absorb a b _ hb => rw [map_mul, hb, zero_mul]

variable (m n p h) in
/-- Rank `m+2` placed on the strands `[p, p+m+2)` of rank `n+2`. -/
def windowHom : Presented m →+* Presented n :=
  Ideal.Quotient.lift (relIdeal m) (windowFree m n p h).toRingHom windowFree_ideal

@[simp] theorem windowHom_dot (j : Fin (m+2)) :
    windowHom m n p h (dot m j) = dot n ⟨j.val + p, by have := j.isLt; omega⟩ :=
  windowFree_dot j

@[simp] theorem windowHom_crossing (i : Fin (m+1)) :
    windowHom m n p h (crossing m i) = crossing n ⟨i.val + p, by have := i.isLt; omega⟩ :=
  windowFree_crossing i

/-- Words are carried to the shifted words. -/
theorem windowHom_product (w : Word m) :
    windowHom m n p h (product w) = product (w.map (shiftIndex h)) := by
  induction w with
  | nil => simp [product]
  | cons i w ih => simp only [product, map_mul, windowHom_crossing, ih, List.map_cons]; rfl

/-- Dot words are carried to the shifted dot words. -/
theorem windowHom_dotWord (v : List (Fin (m+2))) :
    windowHom m n p h (dotWord v) =
      dotWord (v.map fun j => (⟨j.val + p, by have := j.isLt; omega⟩ : Fin (n+2))) := by
  induction v with
  | nil => simp
  | cons j v ih => simp only [dotWord_cons, map_mul, windowHom_dot, ih, List.map_cons]

/-- A shifted word acts on rank `n+2` by the shifted composite of divided differences. -/
theorem action_windowHom_product (w : Word m) :
    action n (windowHom m n p h (product w)) = LongestDivided.applyWord (w.map (shiftIndex h)) := by
  rw [windowHom_product, action_product]

/-- A shifted dot acts by left multiplication by the shifted variable. -/
theorem action_windowHom_dot_apply (j : Fin (m+2)) (f : SkewPolynomial (n+2)) :
    action n (windowHom m n p h (dot m j)) f =
      generator ⟨j.val + p, by have := j.isLt; omega⟩ * f := by
  rw [windowHom_dot, action_dot_apply]

end Window

@[simp] theorem windowHom_id (n : ℕ) (h : 0 + (n+2) ≤ n+2) :
    windowHom n n 0 h = RingHom.id (Presented n) := by
  apply presented_hom_ext
  · intro j; simp
  · intro i; simp

/-- Shifting by `p` and then by `q` is shifting by `p+q`. -/
theorem windowHom_comp {m n k p q : ℕ} (h₁ : p + (m+2) ≤ n+2) (h₂ : q + (n+2) ≤ k+2)
    (h₃ : (p+q) + (m+2) ≤ k+2) :
    (windowHom n k q h₂).comp (windowHom m n p h₁) = windowHom m k (p+q) h₃ := by
  apply presented_hom_ext
  · intro j
    simp only [RingHom.comp_apply, windowHom_dot]
    congr 1
    exact Fin.ext (by simp only; omega)
  · intro i
    simp only [RingHom.comp_apply, windowHom_crossing]
    congr 1
    exact Fin.ext (by simp only; omega)

theorem windowHom_comp_apply {m n k p q : ℕ} (h₁ : p + (m+2) ≤ n+2) (h₂ : q + (n+2) ≤ k+2)
    (h₃ : (p+q) + (m+2) ≤ k+2) (u : Presented m) :
    windowHom n k q h₂ (windowHom m n p h₁ u) = windowHom m k (p+q) h₃ u := by
  rw [← windowHom_comp h₁ h₂ h₃, RingHom.comp_apply]

/-! ## Generators supported in a strand window -/

section Support
variable {n : ℕ}

/-- Generators supported in the strands `[l, r)`. -/
inductive IsGen (l r : ℕ) : Presented n → Prop
  | dot (j : Fin (n+2)) : l ≤ j.val → j.val < r → IsGen l r (dot n j)
  | crossing (i : Fin (n+1)) : l ≤ i.val → i.val + 1 < r → IsGen l r (crossing n i)

/-- Generators on disjoint strand windows anticommute. -/
theorem IsGen.anticomm {l r l' r' : ℕ} {x y : Presented n} (hx : IsGen l r x)
    (hy : IsGen l' r' y) (hrl : r ≤ l') : x * y = -(y * x) := by
  cases hx with
  | dot j hj₁ hj₂ =>
      cases hy with
      | dot j' hj₁' hj₂' =>
          refine eq_neg_of_add_eq_zero_left (dots_anticommute j j' ?_)
          intro he; subst he; omega
      | crossing i' hi₁' hi₂' =>
          rw [crossing_dot_other i' j, neg_neg]
          · intro he; rw [Fin.ext_iff, Fin.coe_castSucc] at he; omega
          · intro he; rw [Fin.ext_iff, Fin.val_succ] at he; omega
  | crossing i hi₁ hi₂ =>
      cases hy with
      | dot j' hj₁' hj₂' =>
          refine crossing_dot_other i j' ?_ ?_
          · intro he; rw [Fin.ext_iff, Fin.coe_castSucc] at he; omega
          · intro he; rw [Fin.ext_iff, Fin.val_succ] at he; omega
      | crossing i' hi₁' hi₂' => exact crossing_distant i i' (Or.inl (by omega))

/-- The ℤ-modules of products of `k` generators supported in `[l, r)`. -/
inductive Homog (l r : ℕ) : ℕ → Presented n → Prop
  | one : Homog l r 0 1
  | gen {x : Presented n} : IsGen l r x → Homog l r 1 x
  | mul {k k' : ℕ} {x y : Presented n} :
      Homog l r k x → Homog l r k' y → Homog l r (k+k') (x*y)
  | zero (k : ℕ) : Homog l r k 0
  | add {k : ℕ} {x y : Presented n} : Homog l r k x → Homog l r k y → Homog l r k (x+y)
  | neg {k : ℕ} {x : Presented n} : Homog l r k x → Homog l r k (-x)

theorem Homog.zsmul {l r k : ℕ} {x : Presented n} (hx : Homog l r k x) (c : ℤ) :
    Homog l r k (c • x) := by
  induction c using Int.induction_on with
  | hz => simpa using Homog.zero k
  | hp c ih => rw [add_zsmul, one_zsmul]; exact ih.add hx
  | hn c ih => rw [sub_zsmul, one_zsmul]; exact ih.add hx.neg

/-- A product of `k` generators supported in `[l, r)`. -/
theorem Homog.list_prod {l r : ℕ} (xs : List (Presented n)) (hx : ∀ x ∈ xs, IsGen l r x) :
    Homog l r xs.length xs.prod := by
  induction xs with
  | nil => exact Homog.one
  | cons x xs ih =>
      rw [List.prod_cons, List.length_cons, add_comm]
      exact (Homog.gen (hx x (List.mem_cons_self ..))).mul
        (ih fun y hy => hx y (List.mem_cons_of_mem _ hy))

private theorem neg_one_pow_cases (k : ℕ) :
    (-1 : Presented n) ^ k = 1 ∨ (-1 : Presented n) ^ k = -1 := by
  rcases Nat.even_or_odd k with hk | hk
  · exact Or.inl hk.neg_one_pow
  · exact Or.inr hk.neg_one_pow

private theorem Homog.supercomm_gen {l r l' r' k : ℕ} {u y : Presented n} (hu : Homog l r k u)
    (hy : IsGen l' r' y) (hrl : r ≤ l') : u * y = (-1) ^ k * (y * u) := by
  induction hu with
  | one => simp
  | gen hx => rw [hx.anticomm hy hrl, pow_one, neg_one_mul]
  | @mul k k' x x' _ _ ihx ihx' =>
      rw [mul_assoc, ihx', pow_add]
      rw [← mul_assoc x, ((Commute.neg_one_right x).pow_right k').eq, mul_assoc,
        ← mul_assoc x, ihx]
      rcases neg_one_pow_cases (n := n) k with hk | hk <;>
        rcases neg_one_pow_cases (n := n) k' with hk' | hk' <;>
        simp [hk, hk', mul_assoc]
  | zero k => simp
  | add _ _ ihx ihy => rw [add_mul, ihx, ihy, mul_add, mul_add]
  | neg _ ihx => rw [neg_mul, ihx, mul_neg, mul_neg]

/-- Supercommutation of products of generators on disjoint strand windows. -/
theorem Homog.supercomm {l r l' r' k k' : ℕ} {u v : Presented n} (hu : Homog l r k u)
    (hv : Homog l' r' k' v) (hrl : r ≤ l') : u * v = (-1) ^ (k * k') * (v * u) := by
  induction hv with
  | one => simp
  | gen hy => rw [mul_one]; exact hu.supercomm_gen hy hrl
  | @mul j j' y y' _ _ ihy ihy' =>
      rw [← mul_assoc, ihy, mul_add, pow_add, mul_assoc, mul_assoc, ihy']
      rcases neg_one_pow_cases (n := n) (k * j) with hk | hk <;>
        rcases neg_one_pow_cases (n := n) (k * j') with hk' | hk' <;>
        simp [hk, hk', mul_assoc]
  | zero j => simp
  | add _ _ ihx ihy => rw [mul_add, ihx, ihy, add_mul, mul_add]
  | neg _ ihx => rw [mul_neg, ihx, neg_mul, mul_neg]

/-- The sign rule for literal products of generators. -/
theorem list_prod_supercomm {l r l' r' : ℕ} (xs ys : List (Presented n))
    (hx : ∀ x ∈ xs, IsGen l r x) (hy : ∀ y ∈ ys, IsGen l' r' y) (hrl : r ≤ l') :
    xs.prod * ys.prod = (-1) ^ (xs.length * ys.length) * (ys.prod * xs.prod) :=
  (Homog.list_prod xs hx).supercomm (Homog.list_prod ys hy) hrl

/-- The subring generated by the generators supported in `[l, r)`. -/
def Supported (n l r : ℕ) : Subring (Presented n) := Subring.closure {x | IsGen l r x}

/-- Even super-degree part: the span of products of an even number of window generators. -/
def SupportedEven (n l r : ℕ) : Submodule ℤ (Presented n) :=
  Submodule.span ℤ {u | ∃ k, Even k ∧ Homog l r k u}

/-- Odd super-degree part: the span of products of an odd number of window generators. -/
def SupportedOdd (n l r : ℕ) : Submodule ℤ (Presented n) :=
  Submodule.span ℤ {u | ∃ k, Odd k ∧ Homog l r k u}

theorem IsGen.mem_supported {l r : ℕ} {x : Presented n} (hx : IsGen l r x) :
    x ∈ Supported n l r :=
  Subring.subset_closure hx

theorem Homog.mem_supported {l r k : ℕ} {u : Presented n} (hu : Homog l r k u) :
    u ∈ Supported n l r := by
  induction hu with
  | one => exact Subring.one_mem _
  | gen hx => exact hx.mem_supported
  | mul _ _ hx hy => exact Subring.mul_mem _ hx hy
  | zero => exact Subring.zero_mem _
  | add _ _ hx hy => exact Subring.add_mem _ hx hy
  | neg _ hx => exact Subring.neg_mem _ hx

theorem Homog.mem_even {l r k : ℕ} {u : Presented n} (hu : Homog l r k u) (hk : Even k) :
    u ∈ SupportedEven n l r :=
  Submodule.subset_span ⟨k, hk, hu⟩

theorem Homog.mem_odd {l r k : ℕ} {u : Presented n} (hu : Homog l r k u) (hk : Odd k) :
    u ∈ SupportedOdd n l r :=
  Submodule.subset_span ⟨k, hk, hu⟩

private theorem span_le_supported {l r : ℕ} {P : ℕ → Prop} {u : Presented n}
    (hu : u ∈ Submodule.span ℤ {u | ∃ k, P k ∧ Homog l r k u}) : u ∈ Supported n l r := by
  induction hu using Submodule.span_induction with
  | mem x hx => obtain ⟨k, -, hx⟩ := hx; exact hx.mem_supported
  | zero => exact Subring.zero_mem _
  | add x y _ _ hx hy => exact Subring.add_mem _ hx hy
  | smul c x _ hx => exact Subring.zsmul_mem _ hx c

theorem SupportedEven.le_supported {l r : ℕ} {u : Presented n}
    (hu : u ∈ SupportedEven n l r) : u ∈ Supported n l r :=
  span_le_supported hu

theorem SupportedOdd.le_supported {l r : ℕ} {u : Presented n}
    (hu : u ∈ SupportedOdd n l r) : u ∈ Supported n l r :=
  span_le_supported hu

/-- An even homogeneous element commutes with every generator of a later window. -/
private theorem even_commute_gen {l r l' r' k : ℕ} {u y : Presented n} (hu : Homog l r k u)
    (hk : Even k) (hy : IsGen l' r' y) (hrl : r ≤ l') : u * y = y * u := by
  rw [hu.supercomm (Homog.gen hy) hrl, mul_one, hk.neg_one_pow, one_mul]

/-- An even homogeneous element commutes with every generator of an earlier window. -/
private theorem gen_commute_even {l r l' r' k : ℕ} {x u : Presented n} (hx : IsGen l r x)
    (hu : Homog l' r' k u) (hk : Even k) (hrl : r ≤ l') : x * u = u * x := by
  rw [(Homog.gen hx).supercomm hu hrl, one_mul, hk.neg_one_pow, one_mul]

/-- Commuting with every generator of a window means commuting with the window subring. -/
private theorem commute_supported {l r : ℕ} {u v : Presented n}
    (hg : ∀ y, IsGen l r y → Commute u y) (hv : v ∈ Supported n l r) : Commute u v := by
  have hle : Supported n l r ≤ Subring.centralizer {u} := by
    refine Subring.closure_le.mpr ?_
    intro y hy
    rw [SetLike.mem_coe, Subring.mem_centralizer_iff]
    intro g hg'
    rw [Set.mem_singleton_iff] at hg'
    subst hg'
    exact (hg y hy).eq
  exact Subring.mem_centralizer_iff.mp (hle hv) u rfl

private theorem commute_span {l r : ℕ} {P : ℕ → Prop} {u v : Presented n}
    (hg : ∀ k w, P k → Homog l r k w → Commute w v)
    (hu : u ∈ Submodule.span ℤ {u | ∃ k, P k ∧ Homog l r k u}) : Commute u v := by
  induction hu using Submodule.span_induction with
  | mem x hx => obtain ⟨k, hk, hx⟩ := hx; exact hg k x hk hx
  | zero => exact Commute.zero_left v
  | add x y _ _ hx hy => exact hx.add_left hy
  | smul c x _ hx => exact hx.smul_left c

/-- (a) Even super-degree elements commute with the whole subring of a later window. -/
theorem even_commute {l r l' r' : ℕ} {u v : Presented n} (hu : u ∈ SupportedEven n l r)
    (hv : v ∈ Supported n l' r') (hrl : r ≤ l') : u * v = v * u := by
  refine (commute_span (fun k w hk hw => ?_) hu).eq
  exact commute_supported (fun y hy => even_commute_gen hw hk hy hrl) hv

/-- Mirror image: the whole subring of an earlier window commutes with even elements. -/
theorem commute_even {l r l' r' : ℕ} {u v : Presented n} (hu : u ∈ Supported n l r)
    (hv : v ∈ SupportedEven n l' r') (hrl : r ≤ l') : u * v = v * u := by
  refine (commute_span (fun k w hk hw => ?_) hv).symm.eq
  exact (commute_supported (fun y hy => (gen_commute_even hy hw hk hrl).symm) hu)

/-- Odd super-degree elements on disjoint windows anticommute. -/
theorem odd_anticomm {l r l' r' : ℕ} {u v : Presented n} (hu : u ∈ SupportedOdd n l r)
    (hv : v ∈ SupportedOdd n l' r') (hrl : r ≤ l') : u * v = -(v * u) := by
  induction hu using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨k, hk, hx⟩ := hx
      induction hv using Submodule.span_induction with
      | mem y hy =>
          obtain ⟨k', hk', hy⟩ := hy
          rw [hx.supercomm hy hrl, (hk.mul hk').neg_one_pow, neg_one_mul]
      | zero => simp
      | add y z _ _ hy hz => rw [mul_add, hy, hz, add_mul, neg_add]
      | smul c y _ hy => rw [mul_smul_comm, hy, smul_mul_assoc, smul_neg]
  | zero => simp
  | add x y _ _ hx hy => rw [add_mul, hx, hy, mul_add, neg_add]
  | smul c x _ hx => rw [smul_mul_assoc, hx, mul_smul_comm, smul_neg]

end Support

/-! ## Windows and the sign rule -/

section WindowSupport
variable {m n p : ℕ} {h : p + (m+2) ≤ n+2}

/-- Every generator of rank `m+2` is supported in its full window. -/
theorem isGen_full_dot (j : Fin (m+2)) : IsGen 0 (m+2) (dot m j) :=
  IsGen.dot j (Nat.zero_le _) j.isLt

theorem isGen_full_crossing (i : Fin (m+1)) : IsGen 0 (m+2) (crossing m i) :=
  IsGen.crossing i (Nat.zero_le _) (by have := i.isLt; omega)

/-- `windowHom` carries generators supported in `[l, r)` into `[l+p, r+p)`. -/
theorem IsGen.windowHom {l r : ℕ} {x : Presented m} (hx : IsGen l r x) :
    IsGen (l+p) (r+p) (windowHom m n p h x) := by
  cases hx with
  | dot j h₁ h₂ =>
      rw [windowHom_dot]
      exact IsGen.dot _ (by simp only; omega) (by simp only; omega)
  | crossing i h₁ h₂ =>
      rw [windowHom_crossing]
      exact IsGen.crossing _ (by simp only; omega) (by simp only; omega)

theorem Homog.windowHom {l r k : ℕ} {u : Presented m} (hu : Homog l r k u) :
    Homog (l+p) (r+p) k (windowHom m n p h u) := by
  induction hu with
  | one => rw [map_one]; exact Homog.one
  | gen hx => exact Homog.gen hx.windowHom
  | mul _ _ hx hy => rw [map_mul]; exact hx.mul hy
  | zero k => rw [map_zero]; exact Homog.zero k
  | add _ _ hx hy => rw [map_add]; exact hx.add hy
  | neg _ hx => rw [map_neg]; exact hx.neg

/-- The whole image of `windowHom` lies in the subring of the window `[p, p+m+2)`. -/
theorem windowHom_mem_supported (u : Presented m) :
    windowHom m n p h u ∈ Supported n p (p+(m+2)) := by
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective u
  induction a using FreeAlgebra.induction with
  | grade0 c =>
      rw [show Ideal.Quotient.mk (relIdeal m) (algebraMap ℤ (Free m) c) = (c : Presented m) by
        simp, map_intCast]
      exact intCast_mem _ c
  | grade1 x =>
      cases x with
      | inl j =>
          have := (isGen_full_dot j).windowHom (n := n) (p := p) (h := h)
          rw [zero_add, add_comm] at this
          exact this.mem_supported
      | inr i =>
          have := (isGen_full_crossing i).windowHom (n := n) (p := p) (h := h)
          rw [zero_add, add_comm] at this
          exact this.mem_supported
  | add a b ha hb => rw [map_add, map_add]; exact Subring.add_mem _ ha hb
  | mul a b ha hb => rw [map_mul, map_mul]; exact Subring.mul_mem _ ha hb

/-- (b) Sign rule for images of products of generators at disjoint offsets. -/
theorem windowHom_supercomm {m' q k k' : ℕ} {h' : q + (m'+2) ≤ n+2} {u : Presented m}
    {v : Presented m'} (hu : Homog 0 (m+2) k u) (hv : Homog 0 (m'+2) k' v)
    (hpq : p + (m+2) ≤ q) :
    windowHom m n p h u * windowHom m' n q h' v =
      (-1) ^ (k * k') * (windowHom m' n q h' v * windowHom m n p h u) :=
  (hu.windowHom (p := p) (h := h)).supercomm (hv.windowHom (p := q) (h := h'))
    (by omega)

/-- (b) Parity form: an even image commutes with the whole later window image. -/
theorem windowHom_even_commute {m' q k : ℕ} {h' : q + (m'+2) ≤ n+2} {u : Presented m}
    (hu : Homog 0 (m+2) k u) (hk : Even k) (v : Presented m') (hpq : p + (m+2) ≤ q) :
    windowHom m n p h u * windowHom m' n q h' v = windowHom m' n q h' v * windowHom m n p h u :=
  even_commute ((hu.windowHom (p := p) (h := h)).mem_even hk)
    (windowHom_mem_supported v) (by omega)

/-- (b) Parity form: the whole earlier window image commutes with an even later image. -/
theorem windowHom_commute_even {m' q k' : ℕ} {h' : q + (m'+2) ≤ n+2} (u : Presented m)
    {v : Presented m'} (hv : Homog 0 (m'+2) k' v) (hk : Even k') (hpq : p + (m+2) ≤ q) :
    windowHom m n p h u * windowHom m' n q h' v = windowHom m' n q h' v * windowHom m n p h u :=
  commute_even (windowHom_mem_supported u)
    ((hv.windowHom (p := q) (h := h')).mem_even hk) (by omega)

end WindowSupport

end

end OddMath.Frontier.OnhWindow
