import Mathlib
import OddMath.Frontier.BoxPartitionCount

/-! # The integral form of `U_q^+(sl_2)`

Lusztig's integral form of the positive half `U_q^+(sl_2)`, as used in EKL arXiv:1111.1320v1,
§6, (6.3).

Let `A = ℤ[q, q⁻¹]` (`LaurentPolynomial ℤ`, with `q = T 1`).

* `qInt n = [n] = q^{n-1} + q^{n-3} + ⋯ + q^{1-n}`, `qFact n = [n]!`, and the balanced Gaussian
  binomial `qBinom a b = [a+b, a] = ∑_{α ∈ P(a,b)} q^{2|α| - ab}`, with
  `[a+b, a] [a]! [b]! = [a+b]!` (`qBinom_mul_qFact`).
* `U_q^+(sl_2)` over `K = Frac A` is the polynomial ring `K[E]`; its integral form `UA` is the
  `A`-subalgebra generated by the divided powers `E^{(a)} = E^a / [a]!` (`dp a`). Since
  `E^{(a)} E^{(b)} = [a+b, a] E^{(a+b)}`, it is the `A`-span of the divided powers
  (`toSubmodule_UA`), free with basis `{E^{(a)}}` (`UA.basis`).
* `DivPowAlg` is the abstract `A`-algebra, free on symbols `ϑ^{(a)}` with
  `ϑ^{(a)} ϑ^{(b)} = [a+b, a] ϑ^{(a+b)}`; `DivPowAlg.equivUA : DivPowAlg ≃ₐ[A] UA`.
* Universal property: a linear map out of `DivPowAlg` (or `UA`) sending `1 ↦ 1` whose values on the
  basis satisfy the same product law is an algebra map (`DivPowAlg.ofLinearMap`, `UA.ofLinearMap`);
  it is bijective iff the images of the basis form a basis (`DivPowAlg.bijective_iff`,
  `UA.bijective_iff`).
-/
namespace OddMath.Frontier.QuantumSl2Plus
open Finset LaurentPolynomial
open OddMath.Frontier.BoxPartitionCount (box sum_box_succ box_zero_left box_zero_right)

local notation "A" => LaurentPolynomial ℤ

/-! ### Quantum integers and the balanced Gaussian binomial -/

/-- The quantum integer `[n] = q^{n-1} + q^{n-3} + ⋯ + q^{1-n}`. -/
noncomputable def qInt (n : ℕ) : A := ∑ i ∈ range n, T ((n : ℤ) - 1 - 2 * i)

/-- The quantum factorial `[n]! = [1][2]⋯[n]`. -/
noncomputable def qFact (n : ℕ) : A := ∏ i ∈ range n, qInt (i + 1)

/-- The balanced Gaussian binomial `[a+b, a] = ∑_{α ∈ P(a,b)} q^{2|α| - ab}`. -/
noncomputable def qBinom (a b : ℕ) : A := ∑ α ∈ box a b, T (2 * ((∑ i, α i : ℕ) : ℤ) - a * b)

theorem T_injective : Function.Injective (T : ℤ → A) :=
  Finsupp.single_left_injective one_ne_zero

@[simp] theorem qInt_zero : qInt 0 = 0 := by simp [qInt]

theorem qInt_succ (n : ℕ) : qInt (n + 1) = T n + T (-1) * qInt n := by
  rw [qInt, sum_range_succ', qInt, mul_sum, add_comm]
  congr 1
  · simp
  · refine sum_congr rfl fun i _ => ?_
    rw [← T_add]
    congr 1
    push_cast
    ring

/-- `[m+n] = q^{-m} [n] + q^n [m]`. -/
theorem qInt_add (m n : ℕ) : qInt (m + n) = T (-(m : ℤ)) * qInt n + T (n : ℤ) * qInt m := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [show m + 1 + n = m + n + 1 by omega, qInt_succ, ih, qInt_succ,
      show (-((m + 1 : ℕ) : ℤ)) = -1 + -(m : ℤ) by push_cast; ring,
      show ((m + n : ℕ) : ℤ) = n + m by push_cast; ring, T_add, T_add]
    ring

/-- `(q - q⁻¹) [n] = q^n - q^{-n}`. -/
theorem qInt_mul (n : ℕ) : (T 1 - T (-1)) * qInt n = T n - T (-(n : ℤ)) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [qInt_succ, show (-((n + 1 : ℕ) : ℤ)) = -1 + -(n : ℤ) by push_cast; ring,
      show ((n + 1 : ℕ) : ℤ) = 1 + n by push_cast; ring, T_add, T_add]
    linear_combination T (-1) * ih

theorem qInt_ne_zero {n : ℕ} (hn : n ≠ 0) : qInt n ≠ 0 := by
  intro h
  have := qInt_mul n
  rw [h, mul_zero, eq_comm, sub_eq_zero] at this
  have := T_injective this
  omega

@[simp] theorem qFact_zero : qFact 0 = 1 := by simp [qFact]

theorem qFact_succ (n : ℕ) : qFact (n + 1) = qFact n * qInt (n + 1) := prod_range_succ _ _

theorem qFact_ne_zero (n : ℕ) : qFact n ≠ 0 :=
  prod_ne_zero_iff.2 fun i _ => qInt_ne_zero i.succ_ne_zero

@[simp] theorem qBinom_zero_left (b : ℕ) : qBinom 0 b = 1 := by simp [qBinom, box_zero_left]

@[simp] theorem qBinom_zero_right (a : ℕ) : qBinom a 0 = 1 := by simp [qBinom, box_zero_right]

/-- The `q`-Pascal recursion `[a+b+2, a+1] = q^{-(a+1)} [a+b+1, a+1] + q^{b+1} [a+b+1, a]`. -/
theorem qBinom_succ_succ (a b : ℕ) :
    qBinom (a + 1) (b + 1) =
      T (-((a + 1 : ℕ) : ℤ)) * qBinom (a + 1) b + T ((b + 1 : ℕ) : ℤ) * qBinom a (b + 1) := by
  rw [qBinom, sum_box_succ (fun w => (T (2 * (w : ℤ) - ((a + 1 : ℕ) : ℤ) * ((b + 1 : ℕ) : ℤ)) : A)),
    qBinom, qBinom, mul_sum, mul_sum]
  congr 1 <;> refine sum_congr rfl fun α _ => ?_ <;> rw [← T_add] <;> congr 1 <;> push_cast <;> ring

/-- The product formula `[a+b, a] [a]! [b]! = [a+b]!`. -/
theorem qBinom_mul_qFact (a b : ℕ) : qBinom a b * qFact a * qFact b = qFact (a + b) := by
  induction a generalizing b with
  | zero => simp
  | succ a iha =>
    induction b with
    | zero => simp
    | succ b ihb =>
      have h1 := ihb
      have h2 := iha (b + 1)
      rw [show a + 1 + b = a + b + 1 by omega] at h1
      rw [show a + (b + 1) = a + b + 1 by omega] at h2
      rw [show a + 1 + (b + 1) = a + b + 1 + 1 by omega, qFact_succ (a + b + 1),
        show a + b + 1 + 1 = (a + 1) + (b + 1) by omega, qInt_add, qBinom_succ_succ,
        qFact_succ a, qFact_succ b]
      rw [qFact_succ a] at h1
      rw [qFact_succ b] at h2
      linear_combination T (-((a + 1 : ℕ) : ℤ)) * qInt (b + 1) * h1 +
        T ((b + 1 : ℕ) : ℤ) * qInt (a + 1) * h2

theorem qBinom_eq_sum_box (a b : ℕ) :
    qBinom a b = ∑ α ∈ box a b, T (2 * ((∑ i, α i : ℕ) : ℤ) - a * b) := rfl

/-- `[a+b, a]` is the unique element `x ∈ A` with `x [a]! [b]! = [a+b]!`; in particular
`[a+b]! / ([a]! [b]!) ∈ A`. -/
theorem eq_qBinom_iff (a b : ℕ) (x : A) :
    x * qFact a * qFact b = qFact (a + b) ↔ x = qBinom a b := by
  refine ⟨fun h => mul_right_cancel₀ (mul_ne_zero (qFact_ne_zero a) (qFact_ne_zero b)) ?_,
    fun h => h ▸ qBinom_mul_qFact a b⟩
  rw [← mul_assoc, h, ← mul_assoc, qBinom_mul_qFact]

theorem qBinom_comm (a b : ℕ) : qBinom a b = qBinom b a := by
  have h := (qBinom_mul_qFact a b).trans ((add_comm a b).symm ▸ (qBinom_mul_qFact b a).symm)
  exact mul_right_cancel₀ (mul_ne_zero (qFact_ne_zero a) (qFact_ne_zero b))
    (by rw [← mul_assoc, h]; ring)

/-- `[a+b, a] [a+b+c, a+b] = [a+b+c, a] [b+c, b]`. -/
theorem qBinom_assoc (a b c : ℕ) :
    qBinom a b * qBinom (a + b) c = qBinom a (b + c) * qBinom b c := by
  have h : qBinom a (b + c) * qFact a * qFact (b + c) = qFact (a + b + c) := by
    rw [add_assoc]; exact qBinom_mul_qFact _ _
  refine mul_right_cancel₀ (mul_ne_zero (mul_ne_zero (qFact_ne_zero a) (qFact_ne_zero b))
    (qFact_ne_zero c)) ?_
  linear_combination qBinom (a + b) c * qFact c * qBinom_mul_qFact a b +
    qBinom_mul_qFact (a + b) c - qBinom a (b + c) * qFact a * qBinom_mul_qFact b c - h

/-! ### The abstract divided power algebra -/

/-- The free `A`-module on symbols `ϑ^{(a)}`, `a ∈ ℕ`, with the product
`ϑ^{(a)} ϑ^{(b)} = [a+b, a] ϑ^{(a+b)}`. -/
def DivPowAlg : Type := ℕ →₀ A

namespace DivPowAlg

noncomputable instance : AddCommGroup DivPowAlg := inferInstanceAs (AddCommGroup (ℕ →₀ A))

noncomputable instance : Module A DivPowAlg := inferInstanceAs (Module A (ℕ →₀ A))

/-- `r ϑ^{(a)}`. -/
noncomputable def single (a : ℕ) (r : A) : DivPowAlg := Finsupp.single a r

/-- The symbol `ϑ^{(a)}`. -/
noncomputable def θ (a : ℕ) : DivPowAlg := single a 1

@[elab_as_elim]
theorem induction_linear {p : DivPowAlg → Prop} (f : DivPowAlg) (h0 : p 0)
    (hadd : ∀ f g, p f → p g → p (f + g)) (hs : ∀ a r, p (single a r)) : p f :=
  Finsupp.induction_linear (motive := p) f h0 hadd hs

theorem single_add (a : ℕ) (r s : A) : single a (r + s) = single a r + single a s :=
  Finsupp.single_add a r s

theorem smul_single (c : A) (a : ℕ) (r : A) : c • single a r = single a (c * r) :=
  Finsupp.smul_single c a r

theorem single_eq_smul (a : ℕ) (r : A) : single a r = r • θ a := by
  rw [θ, smul_single, mul_one]

/-- The standard basis `{ϑ^{(a)}}`. -/
noncomputable def basis : Basis ℕ A DivPowAlg := Finsupp.basisSingleOne

@[simp] theorem basis_apply (a : ℕ) : basis a = θ a := rfl

instance : Module.Free A DivPowAlg := .of_basis basis

/-- The multiplication, as a bilinear map. -/
noncomputable def mulL : DivPowAlg →ₗ[A] DivPowAlg →ₗ[A] DivPowAlg :=
  Finsupp.lift _ A ℕ fun a => Finsupp.lift DivPowAlg A ℕ fun b => qBinom a b • θ (a + b)

theorem mulL_single (a b : ℕ) (r s : A) :
    mulL (single a r) (single b s) = single (a + b) (qBinom a b * r * s) := by
  show Finsupp.lift (DivPowAlg →ₗ[A] DivPowAlg) A ℕ _ (Finsupp.single a r) (Finsupp.single b s) = _
  rw [Finsupp.lift_apply, Finsupp.sum_single_index (by simp), LinearMap.smul_apply]
  erw [Finsupp.lift_apply, Finsupp.sum_single_index (by simp)]
  rw [smul_smul, smul_smul, ← single_eq_smul]
  ring_nf

noncomputable instance : Mul DivPowAlg := ⟨fun f g => mulL f g⟩

noncomputable instance : One DivPowAlg := ⟨θ 0⟩

theorem mul_def (f g : DivPowAlg) : f * g = mulL f g := rfl

theorem one_def : (1 : DivPowAlg) = θ 0 := rfl

theorem single_mul_single (a b : ℕ) (r s : A) :
    single a r * single b s = single (a + b) (qBinom a b * r * s) := mulL_single a b r s

theorem θ_mul_θ (a b : ℕ) : θ a * θ b = qBinom a b • θ (a + b) := by
  rw [θ, θ, single_mul_single, single_eq_smul, mul_one, mul_one]

private theorem mul_assoc' (f g h : DivPowAlg) : f * g * h = f * (g * h) := by
  induction f using induction_linear with
  | h0 => simp [mul_def]
  | hadd f f' hf hf' => simp only [mul_def, map_add, LinearMap.add_apply] at *; rw [hf, hf']
  | hs a r =>
    induction g using induction_linear with
    | h0 => simp [mul_def]
    | hadd g g' hg hg' => simp only [mul_def, map_add, LinearMap.add_apply] at *; rw [hg, hg']
    | hs b s =>
      induction h using induction_linear with
      | h0 => simp [mul_def]
      | hadd h h' hh hh' => simp only [mul_def, map_add] at *; rw [hh, hh']
      | hs c t =>
        simp only [single_mul_single, add_assoc]
        congr 1
        linear_combination r * s * t * qBinom_assoc a b c

private theorem mul_comm' (f g : DivPowAlg) : f * g = g * f := by
  induction f using induction_linear with
  | h0 => simp [mul_def]
  | hadd f f' hf hf' => simp only [mul_def, map_add, LinearMap.add_apply] at *; rw [hf, hf']
  | hs a r =>
    induction g using induction_linear with
    | h0 => simp [mul_def]
    | hadd g g' hg hg' => simp only [mul_def, map_add, LinearMap.add_apply] at *; rw [hg, hg']
    | hs b s =>
      rw [single_mul_single, single_mul_single, add_comm, qBinom_comm]
      ring_nf

private theorem one_mul' (f : DivPowAlg) : 1 * f = f := by
  induction f using induction_linear with
  | h0 => simp [mul_def]
  | hadd f f' hf hf' => simp only [mul_def, map_add] at *; rw [hf, hf']
  | hs a r => rw [one_def, θ, single_mul_single, zero_add, qBinom_zero_left, one_mul, one_mul]

noncomputable instance : CommRing DivPowAlg :=
  { (inferInstance : AddCommGroup DivPowAlg) with
    mul := (· * ·)
    one := 1
    left_distrib := fun f g h => map_add (mulL f) g h
    right_distrib := fun f g h => by simp only [mul_def, map_add, LinearMap.add_apply]
    zero_mul := fun f => by simp only [mul_def, map_zero, LinearMap.zero_apply]
    mul_zero := fun f => map_zero (mulL f)
    mul_assoc := mul_assoc'
    one_mul := one_mul'
    mul_one := fun f => (mul_comm' f 1).trans (one_mul' f)
    mul_comm := mul_comm' }

noncomputable instance : Algebra A DivPowAlg :=
  Algebra.ofModule (fun r f g => by simp only [mul_def, map_smul, LinearMap.smul_apply])
    (fun r f g => map_smul (mulL f) r g)

theorem algebraMap_def (r : A) : algebraMap A DivPowAlg r = single 0 r := by
  rw [Algebra.algebraMap_eq_smul_one, one_def, θ, smul_single, mul_one]

/-! #### Universal property -/

variable {B : Type*} [Semiring B] [Algebra A B]

/-- A linear map out of `DivPowAlg` whose values on the `ϑ^{(a)}` satisfy the product law is
multiplicative. -/
theorem map_mul_of_law (f : DivPowAlg →ₗ[A] B)
    (hmul : ∀ a b, f (θ a) * f (θ b) = qBinom a b • f (θ (a + b))) (x y : DivPowAlg) :
    f (x * y) = f x * f y := by
  induction x using induction_linear with
  | h0 => simp
  | hadd x x' hx hx' => rw [add_mul, map_add, map_add, hx, hx', add_mul]
  | hs a r =>
    induction y using induction_linear with
    | h0 => simp
    | hadd y y' hy hy' => rw [mul_add, map_add, map_add, hy, hy', mul_add]
    | hs b s =>
      rw [single_mul_single, single_eq_smul, single_eq_smul, single_eq_smul, map_smul, map_smul,
        map_smul, smul_mul_assoc, mul_smul_comm, hmul, smul_smul, smul_smul]
      congr 1
      ring

/-- A linear map out of `DivPowAlg` with `1 ↦ 1` whose values on the `ϑ^{(a)}` satisfy the
product law, as an `A`-algebra map. -/
noncomputable def ofLinearMap (f : DivPowAlg →ₗ[A] B) (h1 : f 1 = 1)
    (hmul : ∀ a b, f (θ a) * f (θ b) = qBinom a b • f (θ (a + b))) : DivPowAlg →ₐ[A] B :=
  AlgHom.ofLinearMap f h1 (map_mul_of_law f hmul)

@[simp] theorem ofLinearMap_apply (f : DivPowAlg →ₗ[A] B) (h1 : f 1 = 1)
    (hmul : ∀ a b, f (θ a) * f (θ b) = qBinom a b • f (θ (a + b))) (x : DivPowAlg) :
    ofLinearMap f h1 hmul x = f x := rfl

/-- The `A`-algebra map `ϑ^{(a)} ↦ e a`, for `e` satisfying `e 0 = 1` and the product law. -/
noncomputable def lift (e : ℕ → B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) : DivPowAlg →ₐ[A] B :=
  ofLinearMap (basis.constr A e) (by rw [one_def, ← basis_apply, Basis.constr_basis, h0])
    (fun a b => by simp only [← basis_apply, Basis.constr_basis, hmul])

@[simp] theorem lift_θ (e : ℕ → B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) (a : ℕ) : lift e h0 hmul (θ a) = e a := by
  rw [lift, ofLinearMap_apply, ← basis_apply, Basis.constr_basis]

theorem algHom_ext {f g : DivPowAlg →ₐ[A] B} (h : ∀ a, f (θ a) = g (θ a)) : f = g :=
  AlgHom.toLinearMap_injective (basis.ext fun a => h a)

end DivPowAlg

section Basis

variable {ι R M N : Type*} [Semiring R] [AddCommMonoid M] [Module R M] [AddCommMonoid N]
  [Module R N] (b : Basis ι R M) (f : M →ₗ[R] N)

/-- A linear map is injective iff it maps a basis to a linearly independent family. -/
theorem injective_iff_of_basis :
    Function.Injective f ↔ LinearIndependent R (fun i => f (b i)) := by
  have hf : f = Finsupp.linearCombination R (fun i => f (b i)) ∘ₗ b.repr.toLinearMap :=
    b.ext fun i => by simp
  generalize (fun i => f (b i)) = v at hf
  rw [hf, LinearMap.coe_comp, LinearEquiv.coe_toLinearMap, ← LinearEquiv.coe_toEquiv,
    Equiv.injective_comp]
  rfl

theorem range_eq_of_basis :
    LinearMap.range f = Submodule.span R (Set.range fun i => f (b i)) := by
  rw [LinearMap.range_eq_map, ← b.span_eq, Submodule.map_span, ← Set.range_comp]
  rfl

/-- A linear map is bijective iff it maps a basis to a basis. -/
theorem bijective_iff_of_basis : Function.Bijective f ↔
    LinearIndependent R (fun i => f (b i)) ∧ Submodule.span R (Set.range fun i => f (b i)) = ⊤ := by
  rw [Function.Bijective, injective_iff_of_basis b, ← range_eq_of_basis b, LinearMap.range_eq_top]

end Basis

namespace DivPowAlg

variable {B : Type*} [Semiring B] [Algebra A B]

/-- A linear map out of `DivPowAlg` is bijective iff the images of the `ϑ^{(a)}` form a basis. -/
theorem bijective_iff (f : DivPowAlg →ₗ[A] B) : Function.Bijective f ↔
    LinearIndependent A (fun a => f (θ a)) ∧ Submodule.span A (Set.range fun a => f (θ a)) = ⊤ :=
  bijective_iff_of_basis basis f

theorem lift_bijective_iff (e : ℕ → B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) :
    Function.Bijective (lift e h0 hmul) ↔
      LinearIndependent A e ∧ Submodule.span A (Set.range e) = ⊤ := by
  simpa using bijective_iff (lift e h0 hmul).toLinearMap

theorem lift_bijective_iff_basis (e : ℕ → B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) :
    Function.Bijective (lift e h0 hmul) ↔ ∃ b : Basis ℕ A B, ⇑b = e := by
  rw [lift_bijective_iff]
  refine ⟨fun h => ⟨Basis.mk h.1 h.2.ge, Basis.coe_mk _ _⟩, ?_⟩
  rintro ⟨b, rfl⟩
  exact ⟨b.linearIndependent, b.span_eq⟩

/-- The algebra isomorphism `ϑ^{(a)} ↦ e a` onto `B`, for a basis `e` of `B` satisfying the
product law. -/
noncomputable def liftEquiv (e : Basis ℕ A B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) : DivPowAlg ≃ₐ[A] B :=
  AlgEquiv.ofBijective (lift e h0 hmul) ((lift_bijective_iff_basis e h0 hmul).2 ⟨e, rfl⟩)

@[simp] theorem liftEquiv_θ (e : Basis ℕ A B) (h0 : e 0 = 1)
    (hmul : ∀ a b, e a * e b = qBinom a b • e (a + b)) (a : ℕ) :
    liftEquiv e h0 hmul (θ a) = e a :=
  lift_θ _ h0 hmul a

end DivPowAlg

/-! ### The integral form `U^+_A ⊂ U_q^+(sl_2) = K[E]` -/

local notation "K" => FractionRing A

theorem algebraMap_qFact_ne_zero (n : ℕ) : algebraMap A K (qFact n) ≠ 0 :=
  (map_ne_zero_iff _ (IsFractionRing.injective A K)).2 (qFact_ne_zero n)

/-- `[n] = (q^n - q^{-n}) / (q - q⁻¹)` in `K`. -/
theorem algebraMap_qInt (n : ℕ) :
    algebraMap A K (qInt n) =
      algebraMap A K (T n - T (-(n : ℤ))) / algebraMap A K (T 1 - T (-1)) := by
  have h : (T 1 - T (-1) : A) ≠ 0 := sub_ne_zero.2 fun h => by have := T_injective h; omega
  rw [eq_div_iff ((map_ne_zero_iff _ (IsFractionRing.injective A K)).2 h), ← map_mul, mul_comm,
    qInt_mul]

/-- `[a+b, a] = [a+b]! / ([a]! [b]!)` in `K`. -/
theorem algebraMap_qBinom (a b : ℕ) :
    algebraMap A K (qBinom a b) =
      algebraMap A K (qFact (a + b)) / (algebraMap A K (qFact a) * algebraMap A K (qFact b)) := by
  rw [eq_div_iff (mul_ne_zero (algebraMap_qFact_ne_zero a) (algebraMap_qFact_ne_zero b)),
    ← mul_assoc, ← map_mul, ← map_mul, qBinom_mul_qFact]

/-- The divided power `E^{(a)} = E^a / [a]!` in `U_q^+(sl_2) = K[E]`. -/
noncomputable def dp (a : ℕ) : Polynomial K :=
  Polynomial.C (algebraMap A K (qFact a))⁻¹ * Polynomial.X ^ a

theorem dp_zero : dp 0 = 1 := by simp [dp]

theorem smul_eq_C_mul (r : A) (p : Polynomial K) : r • p = Polynomial.C (algebraMap A K r) * p := by
  rw [Algebra.smul_def, Polynomial.algebraMap_apply]

/-- `E^{(a)} E^{(b)} = [a+b, a] E^{(a+b)}`. -/
theorem dp_mul (a b : ℕ) : dp a * dp b = qBinom a b • dp (a + b) := by
  have ha := algebraMap_qFact_ne_zero a
  have hb := algebraMap_qFact_ne_zero b
  have hab := algebraMap_qFact_ne_zero (a + b)
  have hc : (algebraMap A K (qFact a))⁻¹ * (algebraMap A K (qFact b))⁻¹ =
      algebraMap A K (qFact (a + b)) / (algebraMap A K (qFact a) * algebraMap A K (qFact b)) *
        (algebraMap A K (qFact (a + b)))⁻¹ := by
    field_simp
  rw [smul_eq_C_mul, dp, dp, dp, algebraMap_qBinom, pow_add]
  calc _ = Polynomial.C ((algebraMap A K (qFact a))⁻¹ * (algebraMap A K (qFact b))⁻¹) *
        (Polynomial.X ^ a * Polynomial.X ^ b) := by rw [Polynomial.C_mul]; ring
    _ = _ := by rw [hc, Polynomial.C_mul]; ring

theorem coeff_dp (a n : ℕ) : (dp a).coeff n = if n = a then (algebraMap A K (qFact a))⁻¹ else 0 :=
  Polynomial.coeff_C_mul_X_pow _ _ _

/-- The divided powers are `A`-linearly independent. -/
theorem linearIndependent_dp : LinearIndependent A dp := by
  rw [linearIndependent_iff']
  intro s g hg i hi
  have h := congrArg (fun p : Polynomial K => p.coeff i) hg
  simp only [Polynomial.finset_sum_coeff, Polynomial.coeff_smul, coeff_dp, smul_ite, smul_zero,
    sum_ite_eq, hi, if_true, Polynomial.coeff_zero] at h
  rw [Algebra.smul_def, mul_eq_zero] at h
  exact (IsFractionRing.injective A K) (h.resolve_right (inv_ne_zero
    (algebraMap_qFact_ne_zero i)) |>.trans (map_zero _).symm)

/-- The algebra map `DivPowAlg → K[E]`, `ϑ^{(a)} ↦ E^{(a)}`. -/
noncomputable def ιE : DivPowAlg →ₐ[A] Polynomial K := DivPowAlg.lift dp dp_zero dp_mul

@[simp] theorem ιE_θ (a : ℕ) : ιE (DivPowAlg.θ a) = dp a := DivPowAlg.lift_θ _ _ _ a

theorem ιE_injective : Function.Injective ιE := by
  have h : (fun a => ιE.toLinearMap (DivPowAlg.basis a)) = dp := funext fun a => ιE_θ a
  exact (injective_iff_of_basis DivPowAlg.basis ιE.toLinearMap).2 (h ▸ linearIndependent_dp)

/-- Lusztig's integral form `U^+_A`: the `A`-subalgebra of `U_q^+(sl_2) = K[E]` generated by the
divided powers `E^{(a)}`. -/
noncomputable def UA : Subalgebra A (Polynomial K) := Algebra.adjoin A (Set.range dp)

theorem dp_mem_UA (a : ℕ) : dp a ∈ UA := Algebra.subset_adjoin ⟨a, rfl⟩

theorem UA_eq_range : UA = ιE.range := by
  refine le_antisymm (Algebra.adjoin_le ?_) ?_
  · rintro _ ⟨a, rfl⟩
    exact ⟨DivPowAlg.θ a, ιE_θ a⟩
  · intro y hy
    obtain ⟨x, rfl⟩ := (AlgHom.mem_range _).1 hy
    clear hy
    induction x using DivPowAlg.induction_linear with
    | h0 => rw [map_zero]; exact zero_mem _
    | hadd x y hx hy => rw [map_add]; exact add_mem hx hy
    | hs a r =>
      rw [DivPowAlg.single_eq_smul, map_smul, ιE_θ]
      exact Subalgebra.smul_mem _ (dp_mem_UA a) r

/-- `U^+_A` is the `A`-span of the divided powers. -/
theorem toSubmodule_UA : Subalgebra.toSubmodule UA = Submodule.span A (Set.range dp) := by
  have h : (fun a => ιE.toLinearMap (DivPowAlg.basis a)) = dp := funext fun a => ιE_θ a
  have h' : Subalgebra.toSubmodule ιE.range = LinearMap.range ιE.toLinearMap :=
    Submodule.ext fun x => (AlgHom.mem_range _).trans LinearMap.mem_range.symm
  rw [UA_eq_range, h', range_eq_of_basis DivPowAlg.basis, h]

/-- `DivPowAlg ≃ₐ[A] U^+_A`, `ϑ^{(a)} ↦ E^{(a)}`. -/
noncomputable def DivPowAlg.equivUA : DivPowAlg ≃ₐ[A] UA :=
  (AlgEquiv.ofInjective ιE ιE_injective).trans (Subalgebra.equivOfEq _ _ UA_eq_range.symm)

@[simp] theorem DivPowAlg.equivUA_θ (a : ℕ) :
    (DivPowAlg.equivUA (DivPowAlg.θ a) : Polynomial K) = dp a :=
  ιE_θ a

namespace UA

/-- The basis `{E^{(a)}}` of `U^+_A`. -/
noncomputable def basis : Basis ℕ A UA := DivPowAlg.basis.map DivPowAlg.equivUA.toLinearEquiv

@[simp] theorem basis_apply (a : ℕ) : (basis a : Polynomial K) = dp a := by
  simp [basis]

theorem basis_eq (a : ℕ) : basis a = DivPowAlg.equivUA (DivPowAlg.θ a) := by
  simp [basis]

/-- `U^+_A` is a free `A`-module (with basis `{E^{(a)}}`). -/
instance : Module.Free A UA := .of_basis basis

theorem basis_mul (a b : ℕ) : basis a * basis b = qBinom a b • basis (a + b) := by
  apply Subtype.ext
  show (basis a : Polynomial K) * (basis b : Polynomial K) =
    qBinom a b • (basis (a + b) : Polynomial K)
  rw [basis_apply, basis_apply, basis_apply, dp_mul]

variable {B : Type*} [Semiring B] [Algebra A B]

/-- A linear map out of `U^+_A` with `1 ↦ 1` whose values on the `E^{(a)}` satisfy
`f(E^{(a)}) f(E^{(b)}) = [a+b, a] f(E^{(a+b)})`, as an `A`-algebra map. -/
noncomputable def ofLinearMap (f : UA →ₗ[A] B) (h1 : f 1 = 1)
    (hmul : ∀ a b, f (basis a) * f (basis b) = qBinom a b • f (basis (a + b))) : UA →ₐ[A] B :=
  (DivPowAlg.ofLinearMap (f ∘ₗ DivPowAlg.equivUA.toLinearMap) (by simp [h1])
    (fun a b => by simpa [basis_eq] using hmul a b)).comp DivPowAlg.equivUA.symm.toAlgHom

@[simp] theorem ofLinearMap_apply (f : UA →ₗ[A] B) (h1 : f 1 = 1)
    (hmul : ∀ a b, f (basis a) * f (basis b) = qBinom a b • f (basis (a + b))) (x : UA) :
    ofLinearMap f h1 hmul x = f x := by
  simp [ofLinearMap]

/-- A linear map out of `U^+_A` is bijective iff the images of the `E^{(a)}` form a basis. -/
theorem bijective_iff (f : UA →ₗ[A] B) : Function.Bijective f ↔
    LinearIndependent A (fun a => f (basis a)) ∧
      Submodule.span A (Set.range fun a => f (basis a)) = ⊤ :=
  bijective_iff_of_basis basis f

end UA

end OddMath.Frontier.QuantumSl2Plus
